### PR TITLE
Fix WARNINGS response when AppHMIType received

### LINKED ISSUE #647: RegisterAppInterface returns WARNING message if app has AppHMIType
1. Added HMItype in app policies
2. send AppHMIType from mobile app 

RegisterAppInterface responses WARNING with message
""info" : "Following AppHMITypes are not present in policy table:5,""

### PR DESCRIPTION
**Pull request by jacobkeeler**
When comparing the lists of AppHMITypes from the policy table and RegisterAppInterface message, the values are mistakenly read from the message object as strings when they are actually in enum form, resulting in a warning even if both lists include the same AppHMIType. 

This PR changes this so that the enum values are converted to strings when comparing the two lists, so that they are compared correctly.

Fixes #647

### CODE REVIEW

**Comment by LuxoftAKutsan** [comment]
@jacobkeeler please make proper commit name

File: src/components/application_manager/src/commands/mobile/register_app_interface_request.cc [hunk 1]
```diff
@@ -72,6 +72,32 @@ mobile_apis::AppHMIType::eType StringToAppHMIType(const std::string &str) {
   }
 }
 
+std::string AppHMITypeToString(mobile_apis::AppHMIType::eType type) {
+  if (mobile_apis::AppHMIType::DEFAULT == type) {
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/commands/mobile/register_app_interface_request.cc]: @jacobkeeler can you use switch?

File: src/components/application_manager/src/commands/mobile/register_app_interface_request.cc [hunk 2]
```diff
@@ -72,6 +72,32 @@ mobile_apis::AppHMIType::eType StringToAppHMIType(const std::string &str) {
...
+  } else if (mobile_apis::AppHMIType::SOCIAL == type) {
+    return "SOCIAL";
+  } else if (mobile_apis::AppHMIType::BACKGROUND_PROCESS == type) {
+    return "BACKGROUND_PROCESS";
+  } else if (mobile_apis::AppHMIType::TESTING == type) {
+    return "TESTING";
+  } else if (mobile_apis::AppHMIType::SYSTEM == type) {
+    return "SYSTEM";
+  } else {
+    return NULL;
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/commands/mobile/register_app_interface_request.cc]: @jacobkeeler This will cause core crash.  Probably we should have there some DCHECK or at lease log error

File: src/components/application_manager/src/commands/mobile/register_app_interface_request.cc [hunk 3]
```diff
@@ -93,7 +119,7 @@ struct CheckMissedTypes {
       : policy_app_types_(policy_app_types), log_(log) {}
 
   bool operator()(const smart_objects::SmartArray::value_type &value) {
-    std::string app_type_str = value.asString();
+    std::string app_type_str = AppHMITypeToString((mobile_apis::AppHMIType::eType)value.asUInt());
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/commands/mobile/register_app_interface_request.cc]: @jacobkeeler  please avoid using C-cast. Also value can be INVALID_ENUM, that is -1. So using it as unsigned int is not correct.

File: src/components/application_manager/src/commands/mobile/register_app_interface_request.cc (hunk 1 above)
Comment (jacobkeeler) [inline src/components/application_manager/src/commands/mobile/register_app_interface_request.cc]: I could do so, but there is a reverse function (StringToAppHMIType), already in the file which also uses if statements [here](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/application_manager/src/commands/mobile/register_app_interface_request.cc#L49-73). 

Do you just want me to change both of them to switch statements?

**Comment by jacobkeeler** [comment]
@LuxoftAKutsan All notes were fixed, please check changes

File: src/components/application_manager/src/commands/mobile/register_app_interface_request.cc [hunk 4]
```diff
@@ -73,28 +73,20 @@ mobile_apis::AppHMIType::eType StringToAppHMIType(const std::string &str) {
...
+    case mobile_apis::AppHMIType::MEDIA:              return "MEDIA";
+    case mobile_apis::AppHMIType::MESSAGING:          return "MESSAGING";
+    case mobile_apis::AppHMIType::NAVIGATION:         return "NAVIGATION";
+    case mobile_apis::AppHMIType::INFORMATION:        return "INFORMATION";
+    case mobile_apis::AppHMIType::SOCIAL:             return "SOCIAL";
+    case mobile_apis::AppHMIType::BACKGROUND_PROCESS: return "BACKGROUND_PROCESS";
+    case mobile_apis::AppHMIType::TESTING:            return "TESTING";
+    case mobile_apis::AppHMIType::SYSTEM:             return "SYSTEM";
+    default:
+      NOTREACHED();
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/commands/mobile/register_app_interface_request.cc]: @jacobkeeler NOTREACHED will be switched off in release mode, and you will just try to return NULL.
Compile will generate std::string(NULL) that will cause core crash,

Comment (AGaliuzov) [inline src/components/application_manager/src/commands/mobile/register_app_interface_request.cc]: @jacobkeeler I would rather suggest to create `map` with values instead of switch

Comment (jacobkeeler) [inline src/components/application_manager/src/commands/mobile/register_app_interface_request.cc]: @LuxoftAKutsan Fixed in 54fda30

File: src/components/application_manager/src/commands/mobile/register_app_interface_request.cc [hunk 5]
```diff
@@ -73,20 +74,23 @@ mobile_apis::AppHMIType::eType StringToAppHMIType(const std::string &str) {
...
+    {mobile_apis::AppHMIType::MEDIA, "MEDIA"},
+    {mobile_apis::AppHMIType::MESSAGING, "MESSAGING"},
+    {mobile_apis::AppHMIType::NAVIGATION, "NAVIGATION"},
+    {mobile_apis::AppHMIType::INFORMATION, "INFORMATION"},
+    {mobile_apis::AppHMIType::SOCIAL, "SOCIAL"},
+    {mobile_apis::AppHMIType::BACKGROUND_PROCESS, "BACKGROUND_PROCESS"},
+    {mobile_apis::AppHMIType::TESTING, "TESTING"},
+    {mobile_apis::AppHMIType::SYSTEM, "SYSTEM"}
+  };
+  try {
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/commands/mobile/register_app_interface_request.cc]: @jacobkeeler we use Google Stle guide and is doesn't allow exceptions 
https://google.github.io/styleguide/cppguide.html#Exceptions

Comment (jacobkeeler) [inline src/components/application_manager/src/commands/mobile/register_app_interface_request.cc]: @LuxoftAKutsan Alright, style issues should be fixed in 1309e08

**Comment by LuxoftAKutsan** [comment]
Reviewed
