### PR TITLE
SYNC-73520: Fixed Issue related to SetAppIcon Path

### LINKED ISSUE #3406: CCB: Fixed Issue related to SetAppIcon Path
### Bug Report
set_app_icon_request modifying the path as a URL
Converting "!#$&'()*+,:;=?@[] " to there corresponding hex values. This function is
not required for path.

##### Reproduction Steps
1. Execute setupIconrequest with "!#$&'()*+,:;=?@[] " 

##### Expected Behavior

"!#$&'()*+,:;=?@[] " transferent to HMI as is 

##### Observed Behavior
"!#$&'()*+,:;=?@[] " converted to hex values

##### OS & Version Information
* OS/Version: QNX 7.0 
* SDL Core Version: [5.0.1]( https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1) integrated to SYNC environment   
* Testing Against:  SyncProxy tester

### PR DESCRIPTION
**Pull request by LuxoftAKutsan**
Fixes #3406

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Need to create automated script for checking the issue 

### Summary
Removed the call to the function ConvertPathForURL() which was modifying the path as a URL
Converting "!#$&'()*+,:;=?@[] " to there corresponding hex values. This function is
not rquired for path.

### Tasks Remaining:
- [x] Internal Luxoft Review
- [ ] Create script to reproduce issue on open sdl 

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by LitvinenkoIra — APPROVED** [review]

**Review by ychernysheva — APPROVED** [review]

**Comment by dboltovskyi** [comment]
@JackLivio Please notice PR is ready for PM review

File: src/components/utils/include/utils/file_system.h [hunk 1]
```diff
@@ -256,14 +256,6 @@ bool ReadBinaryFile(const std::string& name,
 
 bool ReadFile(const std::string& name, std::string& result);
 
-/**
- * @brief Convert special symbols in system path to percent-encoded
- *
- * @param name path to file
- * @return returns converted path.
- */
-const std::string ConvertPathForURL(const std::string& path);
```
Comment (jacobkeeler) [inline src/components/utils/include/utils/file_system.h:265]: Since this is a public function, it will need to be deprecated instead of removed for now.

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

File: src/components/utils/include/utils/file_system.h (hunk 1 above)
Comment (LitvinenkoIra) [reply src/components/utils/include/utils/file_system.h:265]: Done in 3f4fe792854b71a882f27362609a544830e081e2

**Review by jacobkeeler — APPROVED** [review]
