### PR TITLE
Overhaul state manager to handle regular state changes during hmi events

### LINKED ISSUE #1916: Media app: system supports audio mixing and embedded navigation starts streaming (TTS session)
**Occurrence: Always** 

# Description
Media app: system supports audio mixing and embedded navigation starts streaming (TTS session)

## Preconditions
 - SDL and HMI are started.
- "MixingAudioSupported" = true at .ini file

## Steps to reproduce
1. media app in LIMITED and AUDIBLE due to active embedded navigation 
2. SDL receives TTS.Started from HMI (embedded navigation starts streaming)

## Actual result
N/A

## Expected result
SDL must send OnHMIStatus (LIMITED, ATTENUATED) to mobile app
send OnHMIStatus (LIMITED, AUDIBLE) to mobile app right after embedded navigation stops streaming (SDL receives TTS.Stopped from HMI)

# Environment

# Attachments

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [x] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

### PR DESCRIPTION
**Pull request by jacobkeeler**
Fixes #1916, #1917, #1918, #1920, #1908, #1608, #1907, #1903, #2322, #2227, #3167 

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
Add unit tests and ATF tests covering this overhaul

### Summary
The implementation of the state manager did not allow for state changes above a certain level during several different HMI events (such as AUDIO_SOURCE and EMBEDDED_NAVI). These changes add a way of separating the maximum HMI state from the initial HMI state for an event, and allows changes in the regular state to affect the current state. The effect of this is that an app can be activated if it doesn't conflict with the HMI event (such as a weather app being activated during AUDIO_SOURCE), even if it was deactivated when the event originally became active.

##### Enhancements
* Overhaul state manager to handle state changes during HMI events

##### Bug Fixes
* Fix several cases of incorrect states being given to apps when an HMI event is active

### Tasks Remaining:
- [x] Test fix against each individual issue linked
- [x] Add new unit tests covering overhauled functions
- [x] Add ATF test script changes

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/hmi_state.cc [hunk 1]
```diff
@@ -241,38 +265,123 @@ AudioSource::AudioSource(std::shared_ptr<Application> app,
 mobile_apis::HMILevel::eType AudioSource::hmi_level() const {
   using namespace mobile_apis;
 
+  if (WindowType::WIDGET == window_type() || keep_context_) {
+    return std::max(parent()->hmi_level(), max_hmi_level());
```
Comment (iCollin) [inline src/components/application_manager/src/hmi_state.cc:269]: do we need to check if parent() is valid? we do in `max_hmi_level`

File: src/components/application_manager/src/hmi_state.cc [hunk 2]
```diff
@@ -241,38 +265,123 @@ AudioSource::AudioSource(std::shared_ptr<Application> app,
...
+  }
+
+  auto expected = HMILevel::HMI_BACKGROUND;
+  if (is_navi_app()) {
+    expected = HMILevel::HMI_LIMITED;
+  }
+
+  return std::max(std::max(expected, max_hmi_level()), parent()->hmi_level());
```
Comment (iCollin) [inline src/components/application_manager/src/hmi_state.cc:277]: do we need to check if parent() is valid? we do in `max_hmi_level`

File: src/components/application_manager/src/hmi_state.cc [hunk 3]
```diff
@@ -241,38 +265,123 @@ AudioSource::AudioSource(std::shared_ptr<Application> app,
...
+}
+
+mobile_apis::AudioStreamingState::eType AudioSource::audio_streaming_state()
+    const {
+  return is_media_app() ? mobile_apis::AudioStreamingState::NOT_AUDIBLE
```
Comment (iCollin) [inline src/components/application_manager/src/hmi_state.cc:282]: do we need to check if parent() is valid? we do in `max_hmi_level`

File: src/components/application_manager/src/hmi_state.cc [hunk 4]
```diff
@@ -241,38 +265,123 @@ AudioSource::AudioSource(std::shared_ptr<Application> app,
...
+                        : parent()->audio_streaming_state();
+}
+
+mobile_apis::VideoStreamingState::eType AudioSource::video_streaming_state()
+    const {
+  return parent()->video_streaming_state();
```
Comment (iCollin) [inline src/components/application_manager/src/hmi_state.cc:288]: do we need to check if parent() is valid? we do in `max_hmi_level`

File: src/components/application_manager/src/hmi_state.cc [hunk 5]
```diff
@@ -241,38 +265,123 @@ AudioSource::AudioSource(std::shared_ptr<Application> app,
...
+                             : mobile_apis::AudioStreamingState::AUDIBLE;
+  return is_media_app() ? mobile_apis::AudioStreamingState::NOT_AUDIBLE
+                        : parent_max;
+}
+
+mobile_apis::VideoStreamingState::eType AudioSource::max_video_streaming_state()
+    const {
+  auto parent_max = parent() ? parent()->max_video_streaming_state()
+                             : mobile_apis::VideoStreamingState::STREAMABLE;
+  return parent_max;
```
Comment (iCollin) [inline src/components/application_manager/src/hmi_state.cc:319]:
```suggestion
  return parent() ? parent()->max_video_streaming_state()
                             : mobile_apis::VideoStreamingState::STREAMABLE;
```

File: src/components/application_manager/src/hmi_state.cc [hunk 6]
```diff
@@ -241,38 +265,123 @@ AudioSource::AudioSource(std::shared_ptr<Application> app,
...
 }
 
 EmbeddedNavi::EmbeddedNavi(std::shared_ptr<Application> app,
                            const ApplicationManager& app_mngr)
     : HmiState(app, app_mngr, STATE_ID_EMBEDDED_NAVI) {}
 
+mobile_apis::AudioStreamingState::eType EmbeddedNavi::audio_streaming_state()
+    const {
+  return is_navi_app() ? mobile_apis::AudioStreamingState::NOT_AUDIBLE
```
Comment (iCollin) [inline src/components/application_manager/src/hmi_state.cc:328]: do we need to check parent() is valid here? we do in `max_video_streaming_state`

File: src/components/application_manager/src/hmi_state.cc [hunk 7]
```diff
@@ -241,38 +265,123 @@ AudioSource::AudioSource(std::shared_ptr<Application> app,
...
+                       : parent()->audio_streaming_state();
+}
+
+mobile_apis::VideoStreamingState::eType EmbeddedNavi::video_streaming_state()
+    const {
+  return is_navi_app() ? mobile_apis::VideoStreamingState::NOT_STREAMABLE
```
Comment (iCollin) [inline src/components/application_manager/src/hmi_state.cc:334]: do we need to check parent() is valid here? we do in `max_video_streaming_state`

File: src/components/application_manager/src/hmi_state.cc [hunk 8]
```diff
@@ -241,38 +265,123 @@ AudioSource::AudioSource(std::shared_ptr<Application> app,
...
+                       : parent()->video_streaming_state();
+}
+
 mobile_apis::HMILevel::eType EmbeddedNavi::hmi_level() const {
   using namespace mobile_apis;
   using namespace helpers;
 
   if (WindowType::WIDGET == window_type()) {
-    return parent()->hmi_level();
+    return std::max(parent()->hmi_level(), max_hmi_level());
```
Comment (iCollin) [inline src/components/application_manager/src/hmi_state.cc:343]: do we need to check parent() is valid here? we do in `max_video_streaming_state`

File: src/components/application_manager/src/hmi_state.cc [hunk 9]
```diff
@@ -241,38 +265,123 @@ AudioSource::AudioSource(std::shared_ptr<Application> app,
...
+  }
+
+  auto expected = HMILevel::HMI_BACKGROUND;
+  if (is_media_app() || is_voice_communication_app()) {
+    expected = HMILevel::HMI_LIMITED;
+  }
+
+  return std::max(std::max(expected, max_hmi_level()), parent()->hmi_level());
```
Comment (iCollin) [inline src/components/application_manager/src/hmi_state.cc:351]: do we need to check parent() is valid here? we do in `max_video_streaming_state`

File: src/components/application_manager/include/application_manager/application_state.h [hunk 10]
```diff
@@ -197,6 +207,11 @@ class ApplicationState {
    */
   HmiStatesMap hmi_states_map_;
```
[the remark this answers is not in the document]
Comment (jacobkeeler) [reply src/components/application_manager/include/application_manager/application_state.h:208]: `HmiStatesMap` is a map which has pairs `<WindowID, std::vector<HmiStatePtr>>`, while `HmiStateMap` has pairs `<WindowID, HmiStatePtr>`, so they aren't interchangeable.

File: src/components/application_manager/src/hmi_state.cc [hunk 11]
```diff
@@ -142,13 +159,22 @@ VideoStreamingHmiState::VideoStreamingHmiState(
 
 mobile_apis::VideoStreamingState::eType
 VideoStreamingHmiState::video_streaming_state() const {
+  return std::max(parent()->video_streaming_state(),
```
[the remark this answers is not in the document]
Comment (jacobkeeler) [reply src/components/application_manager/src/hmi_state.cc:162]: In practice, this shouldn't be a problem only because if how I set it up (as is the case with why the check wasn't there prior to my changes). That said, I could add this check just for safety

**Comment by LuxoftAKutsan** [comment]
Hello, @jacobkeeler I am trying to understand the problem that this PR is willing to change, but as for me, the current is able to handle a situation with changing regular state within 2 active HMI events.

Detailed documentation is available in https://github.com/LuxoftSDL/sdl_core/blob/impl/state_controller_sdd/src/components/application_manager/doc/SDL.SDD.StateController.dox 

Sorry that it is not in sdl_core_guides yet, I will move it there and create PR later. 

Could you please explain may b with some sequence or state diagrams, what was the problem in existing design and how `maximum HMI level` fixing it ?

**Comment by jacobkeeler** [comment]
@LuxoftAKutsan The main issue is that the initial state that an app is put in due to an HMI event is not the highest state that the app can be in during that event (i.e. when a media app is put in LIMITED due to an EMBEDDED_NAVI event, it could later be put into FULL). This is the difference between `hmi_level` and `maximum_hmi_level`. I'll try to explain the problem with a few detailed examples:


## Case 1: Non-media App with AUDIO_SOURCE

### Old System
1. Non-media app is activated
State stack: [REGULAR]
Regular State: FULL, NOT_AUDIBLE
Current State: FULL, NOT_AUDIBLE

2. AUDIO_SOURCE event is activated on HMI
State stack: [REGULAR, AUDIO_SOURCE]
Regular State: FULL, NOT_AUDIBLE
Current State: BACKGROUND, NOT_AUDIBLE (calculated from AUDIO_SOURCE state `hmi_level`)

3. App is reactivated while AUDIO_SOURCE is still active
State stack: [REGULAR, AUDIO_SOURCE]
Regular State: FULL, NOT_AUDIBLE (Updated, but unchanged)
Current State: BACKGROUND, NOT_AUDIBLE
**The issue is that nothing changes in this step**

### New System
1. Non-media app is activated
State stack: [REGULAR]
Regular State: FULL, NOT_AUDIBLE
Current State: FULL, NOT_AUDIBLE

2. AUDIO_SOURCE event is activated on HMI
State stack: [REGULAR, AUDIO_SOURCE]
Regular State: FULL, NOT_AUDIBLE
Current State: BACKGROUND, NOT_AUDIBLE (calculated from AUDIO_SOURCE state `hmi_level`)

3. App is reactivated while AUDIO_SOURCE is still active
State stack: [AUDIO_SOURCE, REGULAR]
Regular State: FULL, NOT_AUDIBLE (Updated, but unchanged)
Current State: FULL, NOT_AUDIBLE

## Case 2: Media App with AUDIO_SOURCE
This case is meant to demonstrate why the `max_hmi_level` is needed for the new system. Both systems have the same behavior in this case.

### Old System
1. Media app is activated
State stack: [REGULAR]
Regular State: FULL, AUDIBLE
Current State: FULL, AUDIBLE

2. AUDIO_SOURCE event is activated on HMI
State stack: [REGULAR, AUDIO_SOURCE]
Regular State: FULL, AUDIBLE
Current State: BACKGROUND, NOT_AUDIBLE (calculated from AUDIO_SOURCE state `hmi_level`)

3. App is reactivated while AUDIO_SOURCE is still active
State stack: [REGULAR, AUDIO_SOURCE]
Regular State: FULL, AUDIBLE
Current State: BACKGROUND, NOT_AUDIBLE

### New System
1. Media app is activated
State stack: [REGULAR]
Regular State: FULL, AUDIBLE
Current State: FULL, AUDIBLE

2. AUDIO_SOURCE event is activated on HMI
State stack: [REGULAR, AUDIO_SOURCE]
Regular State: FULL, AUDIBLE
Current State: BACKGROUND, NOT_AUDIBLE (calculated from AUDIO_SOURCE state `hmi_level`)

3. App is reactivated while AUDIO_SOURCE is still active
State stack: [AUDIO_SOURCE, REGULAR]
Regular State: FULL, AUDIBLE (Updated, but unchanged)
Current State: BACKGROUND, NOT_AUDIBLE (affected by AUDIO_SOURCE `max_hmi_level`)

**Comment by JackLivio** [comment]
@alexkutsan Did jacob's comment resolve any open questions you had about the pr?

File: src/components/application_manager/src/application_state.cc [hunk 12]
```diff
@@ -201,17 +207,24 @@ void ApplicationState::RemoveHMIState(const WindowID window_id,
...
-  if (next != hmi_states.end()) {
-    HmiStatePtr next_state = *next;
-    HmiStatePtr prev_state = *prev;
-    next_state->set_parent(prev_state);
+  EraseHMIState(hmi_states, it);
+}
+
+void ApplicationState::EraseHMIState(HmiStates& hmi_states,
+                                     HmiStates::iterator it) {
+  if (it == hmi_states.begin()) {
```
Comment (JackLivio) [inline src/components/application_manager/src/application_state.cc:215]:
```suggestion
  if (hmi_states.begin() == it) {
```

I think this follows the code style we have been using lately

File: src/components/application_manager/src/application_state.cc [hunk 13]
```diff
@@ -201,17 +207,24 @@ void ApplicationState::RemoveHMIState(const WindowID window_id,
...
+    (*it)->set_parent(nullptr);
+  } else {
+    HmiStates::iterator next = it;
+    HmiStates::iterator prev = it;
+    next++;
+    prev--;
+
+    if (next != hmi_states.end()) {
```
Comment (JackLivio) [inline src/components/application_manager/src/application_state.cc:223]:
```suggestion
    if ( hmi_states.end() != next) {
```

File: src/components/application_manager/src/application_state.cc [hunk 14]
```diff
@@ -291,14 +288,7 @@ void ApplicationState::SetPostponedState(const WindowID window_id,
...
   sync_primitives::AutoLock auto_lock(hmi_states_map_lock_);
-  HmiStates& hmi_states = hmi_states_map_[window_id];
-  DCHECK_OR_RETURN_VOID(!hmi_states.empty());
-  HmiStatePtr front_state = hmi_states.front();
-  if (front_state->state_id() == HmiState::StateID::STATE_ID_POSTPONED) {
-    hmi_states.erase(hmi_states.begin());
-  }
-
-  hmi_states.insert(hmi_states.begin(), state);
+  postponed_states_map_[window_id] = state;
```
Comment (JackLivio) [inline src/components/application_manager/src/application_state.cc:291]: Should postponed_states_map_ require its own lock instead of sharing the hmi_states_map_lock_?

**Comment by JackLivio** [comment]
Seeing failed smoke tests:

FAILED	./test_scripts/API/SubtleAlertStyle/SubtleAlert/001_PositiveCase_With_SoftButtons_SUCCESS.lua
FAILED	./test_scripts/Smoke/API/031_PerformAudioPassThru_PositiveCase_SUCCESS.lua

**Review by JackLivio — APPROVED** [review]

**Comment by LuxoftAKutsan** [comment]
@jacobkeeler @JackLivio Oh, I see, StateController was not able to "reactivate" the application.
Agree with the approach.

**Review by JackLivio — APPROVED** [review]
