### PR TITLE
Fix/Revoked App Consent Activation

### LINKED ISSUE #3580: Revoked app can be activated via device consent in EXTERNAL_PROPRIETARY
### Bug Report
In EXTERNAL_PROPRIETARY policy mode, if an app is revoked, it can still be activated by providing consent for the device. This activation results in the app being brought to the foreground whenever it is reconnected as well.

##### Reproduction Steps
Using SDL HMI
1. app1 is revoked and connected, but device is not consented
2. Select app1 from the app list, accept consent prompt for device, HMI sends `SDL.OnAllowSDLFunctionality(true)`

##### Expected Behavior
app1 is not activated via `BC.ActivateApp` from SDL Core

##### Observed Behavior
SDL Core sends `BC.ActivateApp` to HMI, HMI brings app to foreground (although app1 still has `hmiLevel: NONE`). `BC.ActivateApp` is also sent to the HMI when the app reconnects.

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: 7.0.0
* Testing Against: Android Test Suite app

### PR DESCRIPTION
**Pull request by ShobhitAd**
Fixes #3580 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Manual Testing with Test suite app

### Summary
- Add permissions check in OnAllowSDLFunctionalityNotification for application revoked case

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by jacobkeeler — CHANGES_REQUESTED** [review]
I can still reproduce the issue on this branch

**Review by jacobkeeler — APPROVED** [review]

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 1]
```diff
@@ -1437,7 +1435,17 @@ void PolicyHandler::OnAllowSDLFunctionalityNotification(
...
     }
-    if (is_allowed) {
+
+    bool is_allowed_by_policies = true;
+    if (PolicyEnabled()) {
+      std::string policy_app_id = app->policy_app_id();
+      AppPermissions permissions(policy_app_id);
+      permissions = policy_manager->GetAppPermissionsChanges(app->mac_address(),
+                                                             policy_app_id);
+      is_allowed_by_policies = !permissions.appRevoked;
```
Comment (jacobkeeler) [inline src/components/application_manager/src/policies/policy_handler.cc:1445]:
```suggestion
      is_allowed_by_policies =
          policy_manager->IsApplicationRevoked(app->policy_app_id());
```
Seems the current fix has some obscure issues, try this instead

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

File: src/components/application_manager/src/policies/policy_handler.cc (hunk 1 above)
Comment (ShobhitAd) [reply src/components/application_manager/src/policies/policy_handler.cc]: Fixed in https://github.com/smartdevicelink/sdl_core/pull/3592/commits/842f85ca1ee94fbfb5abc40de8e2be42ac5a1479

**Review by jacobkeeler — APPROVED** [review]
