### PR TITLE
Fix streaming retry sequence

### LINKED ISSUE #3547: SDL sometimes doesn't send required number of StartStream/StartAudioStream requests
### Bug Report
During start of Video(Audio) streaming SDL sends `Navigation.StartStream` (`Navigation.StartAudioStream`) requests to HMI and waiting for response. In case if HMI responds with erroneous code SDL re-send the same request several times (equal to `StartStreamRetry` .ini parameter). SDL sometimes doesn't send required number of such requests

##### Occurrences
~10-15%

##### Reproduction Steps
1. Navi app is registered and activated
2. App try to start Video(Audio) service
=> SDL does send `Navi.StartStream` (`Navi.StartAudioStream`) requests to HMI
3. HMI responds with `REJECTED`

##### Expected Behavior
SDL re-sends `Navi.StartStream` (`Navi.StartAudioStream`) requests to HMI a few times (equal to `StartStreamRetry` .ini parameter)

##### Observed Behavior
SDL doesn't send required number of requests
There is an error in log for Video:
```
ERROR [21 Oct 2020 15:56:56,257][140043616237312][Commands] /home/developer/sdl/sdl_core/src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/navi_start_stream_request.cc:155 commands::NaviStartStreamRequest::RetryStartSession: NaviStartStreamRequest aborted. Application not found
```
There is an error in log for Audio:
```
ERROR [21 Oct 2020 16:29:37,566][0x7f311ffff700][Commands] /home/developer/sdl/sdl_core/src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/navi_audio_start_stream_request.cc:156 commands::AudioStartStreamRequest::RetryStartSession: StartAudioStreamRequest aborted. Application not found
```

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/release/7.0.0 (3ec2b6b)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - ATF Script: [3547_RetryStrategy_for_start_streaming.lua.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5417611/3547_RetryStrategy_for_start_streaming.lua.tar.gz)
 - Report and Logs: [2020-10-21_11-56-44.289_3547.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5417610/2020-10-21_11-56-44.289_3547.tar.gz)

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #3547 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Covered by ATF scripts

### Summary
There were noticed two issues related to a/v streaming:
1. Due to object self destruction after `TerminateRequest()` call any attempt to access member field of that object may cause an
undefined behavior - it might be a core crash or corrupted value sometimes. In this particular case, SDL tries to access `message_` field through `application_id()` function after object destruction. As a result, sometimes SDL crashes and sometimes this function just returns 0. Because of that, SDL was not able to find application by zero id and broke the retry sequence. This causes random failures of some ATF scripts. To avoid that issue, all retry logic was extracted into the separate function and `TerminateRequest` was moved after that function. This will guarantee that there is no attempts to access object fields after its destruction.
2. There was noticed that SDL makes one redundant retry attempt. That was because of late retry value increment. To fix that issue, increment has been placed before retry amount check.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by ychernysheva — APPROVED** [review]

**Review by LitvinenkoIra — APPROVED** [review]

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/hmi/navi_audio_start_stream_request.h [hunk 1]
```diff
@@ -77,13 +77,19 @@ class AudioStartStreamRequest : public app_mngr::commands::RequestToHMI,
    **/
   virtual void on_event(const app_mngr::event_engine::Event& event);
 
+ private:
   /**
    * @brief RetryStartSession resend HMI startSession request if needed.
    * If limit expired, set audio_stream_retry_number counter to 0
```
Comment (LitvinenkoIra) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/hmi/navi_audio_start_stream_request.h:83]: @AKalinich-Luxoft as a suggestion -
we can specify in the description that `RetryStartSessionInternal` function will be called inside and why do we need it

**Comment by LitvinenkoIra** [comment]
@VladSemenyuk please review this PR

**Review by VladSemenyuk — APPROVED** [review]

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/hmi/navi_audio_start_stream_request.h (hunk 1 above)
Comment (AKalinich-Luxoft) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/hmi/navi_audio_start_stream_request.h:83]: @LitvinenkoIra I thought about that...
Actually, I decided to remove that function to avoid confusions just because `RetryStartSessionInternal` is in the same namespace and with the same visibility so it might be called accidentally when it shouldn't. I encapsulated this logic inside of lambda inside of `RetryStartSession` to make code cleaner.
Please double check that commit - https://github.com/smartdevicelink/sdl_core/pull/3552/commits/d23a8851f67ef834f9e40be39e2c9c5b17b55664

**Review by LitvinenkoIra — APPROVED** [review]

**Comment by dboltovskyi** [comment]
@theresalech Please notice PR is ready for PM review

**Review by iCollin — APPROVED** [review]
