### PR TITLE
Merge module data instead of outright replacing each element

### LINKED ISSUE #2643: when SDL receive OnInteriorVehicleData, it shall update (not replace) the cached data
### Bug Report
when SDL receives OnInteriorVehicleData regarding LIGHT module, it shall update (not replace) the cached data. 
SDL shall replace cached data when receives a response of GetInteriorVehicleData.

##### Reproduction Steps
1. build sdl core release/5.0.0 and clone sdl hmi develop branch
2. run sdl core and sdl hmi
3. register a remote control app connect to sdl
4. activate the app from hmi
5. from the app, send GetInteriorVechicleData with moduleType=LIGHT, it get status of all available lights
6. on hmi change the status of one light
7. from the app, send GetInteriorVechicleData with moduleType=LIGHT again

##### Expected Behavior
App shall get the status of all available lights
SDL shall send the status of all available lights in the response

##### Observed Behavior
App only get one light in the response.
SDL only include the status of one recent changed light in the response

##### OS & Version Information
* OS/Version: Ubuntu 16.04 
* SDL Core Version:  5.0 release candidate (release 5.0.0 branch)
* SDL HMI Version: current develop branch
* Testing Against: remote control of Light

### PR DESCRIPTION
**Pull request by jacobkeeler**
Fixes #2643 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
1. Subscribe to LIGHT module
2. Update one light status via the HMI
3. Send another GetInteriorVehicleData for LIGHT module with subscribe=true
4. Verify that all light values are present, including the updated value

### Summary
Merges module data in cache when an OnInteriorVehicleData is received instead of replacing each element in the root object.

##### Bug Fixes
* Merges interior vehicle cache data instead of replacing.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_cache_impl.cc [hunk 1]
```diff
@@ -60,11 +68,54 @@ smart_objects::SmartObject MergeModuleData(
...
+    }
   }
   return result;
 }
 
+smart_objects::SmartObject MergeArray(const smart_objects::SmartObject& data1,
+                                      const smart_objects::SmartObject& data2) {
+  // Merge data only in the case where each value in the array is an Object with
+  // an ID included, otherwise replace
+  if (!data2.empty() &&
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_cache_impl.cc]: @jacobkeeler it is complicated to read 3 conditions in one if condition

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_cache_impl.cc [hunk 2]
```diff
@@ -60,11 +68,54 @@ smart_objects::SmartObject MergeModuleData(
...
+      if (value.getType() == smart_objects::SmartType::SmartType_Map) {
+        result[key] = MergeModuleData(result[key], value);
+      } else if (value.getType() == smart_objects::SmartType::SmartType_Array) {
+        result[key] = MergeArray(result[key], value);
+      } else {
+        result[key] = value;
+      }
+    } else {
+      result[key] = value;
+    }
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_cache_impl.cc]: @jacobkeeler Don't you think this way can be more short easier: 
```
    const smart_objects::SmartObject& value = it->second;
    smart_objects::SmartObject final_result = value;

    // Merge maps and arrays with `id` param included, replace other types

    if (result.keyExists(key) && value.getType() == result[key].getType()) {
      if (value.getType() == smart_objects::SmartType::SmartType_Map) {
        final_result = MergeModuleData(result[key], value);
      } else if (value.getType() == smart_objects::SmartType::SmartType_Array) {
        final_result = MergeArray(result[key], value);
      } 
    } 

    result[key] = final_result;
```

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_cache_impl.cc (hunk 1 above)
Comment (LuxoftAKutsan) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_cache_impl.cc]:
```cpp
DCHECK(data2.getElement(0).getType() !=
          smart_objects::SmartType::SmartType_Map); 
```
This function called from  MergeModuleData, and if this is map, there is mistake in MergeModuleData function, isn't it?

Comment (LuxoftAKutsan) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_cache_impl.cc]:
```cpp
if (data2.empty() || data2.getElement(0).keyExists(application_manager::strings::id)) {
  return data2;
}
```

Comment (LuxoftAKutsan) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_cache_impl.cc]: I would move this lambda out of loop, and give easy readable name
```cpp
auto result_contains = [&result_array](const smart_objects::SmartObject& id) {
   auto result_it = std::find_if(result_array->begin(), result_array->end(),
                       [&id](smart_objects::SmartObject& obj) -> bool {
                         return obj[application_manager::strings::id] == id;
                       });
}
```

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_cache_impl.cc [hunk 3]
```diff
@@ -60,11 +68,54 @@ smart_objects::SmartObject MergeModuleData(
...
+    auto data_it = data_array->begin();
+    for (; data_it != data_array->end(); ++data_it) {
+      auto result_it =
+          std::find_if(result_array->begin(),
+                       result_array->end(),
+                       [data_it](smart_objects::SmartObject& obj) -> bool {
+                         return obj[application_manager::strings::id] ==
+                                (*data_it)[application_manager::strings::id];
+                       });
+
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_cache_impl.cc]: @jacobkeeler 
```cpp
if (result_contains((*data_it)[application_manager::strings::id])) {
   *result_it = MergeModuleData(*result_it, *data_it);
} else {
  result_array->push_back(*data_it);
}
```

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_cache_impl.cc (hunk 1 above)
Comment (jacobkeeler) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_cache_impl.cc]: > ```c++
> DCHECK(data2.getElement(0).getType() !=
>           smart_objects::SmartType::SmartType_Map); 
> ```
> 
> This function called from MergeModuleData, and if this is map, there is mistake in MergeModuleData function, isn't it?

This is checking the type of the first element, not the array itself.

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_cache_impl.cc [hunk 4]
```diff
@@ -52,6 +53,13 @@ InteriorDataCacheImpl::~InteriorDataCacheImpl() {}
  * @param data2 - updated data
  * @return updated data1 with data2 keys and values
  */
+smart_objects::SmartObject MergeModuleData(
+    const smart_objects::SmartObject& data1,
+    const smart_objects::SmartObject& data2);
+
+smart_objects::SmartObject MergeArray(const smart_objects::SmartObject& data1,
```
[the remark this answers is not in the document]
Comment (jacobkeeler) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_cache_impl.cc]: fixed with https://github.com/smartdevicelink/sdl_core/pull/2667/commits/e60ff48533708c1b2b98e32fd60707eaa93e121a

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_cache_impl.cc (hunk 2 above)
Comment (jacobkeeler) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_cache_impl.cc]: fixed with https://github.com/smartdevicelink/sdl_core/pull/2667/commits/e60ff48533708c1b2b98e32fd60707eaa93e121a

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_cache_impl.cc (hunk 3 above)
Comment (jacobkeeler) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_cache_impl.cc]: I used a different form of lambda, so this no longer applies

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_cache_impl.cc [hunk 5]
```diff
@@ -60,11 +68,54 @@ smart_objects::SmartObject MergeModuleData(
   for (; it != data2.map_end(); ++it) {
     const std::string& key = it->first;
     const smart_objects::SmartObject& value = it->second;
-    result[key] = value;
+    // Merge maps and arrays with `id` param included, replace other types
+    if (result.keyExists(key) && value.getType() == result[key].getType()) {
```
[the remark this answers is not in the document]
Comment (jacobkeeler) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_cache_impl.cc]: > ```cpp
> DCHECK(value_type == result[key].getType()); // As I remember data smart object should be validated by mobile schema, so types of the keys should be the same.
> ```

While this is likely the case, I don't see any reason to restrict this function to this constraint, so I left this check in the if statement

**Comment by jacobkeeler** [comment]
@LuxoftAKutsan comments have been addressed
