### PR TITLE
Fix/sdl_does_not_send SDL.OnStatusUpdate(UPDATE_NEEDED)

### LINKED ISSUE #2489: SDL doesn't send SDL.OnStatusUpdate(UPDATE_NEEDED) in case of failed retry strategy during previous IGN_ON
### Bug Report
SDL doesn't send SDL.OnStatusUpdate(UPDATE_NEEDED) in case of failed retry strategy during previous IGN_ON

##### Reproduction Steps
1. Start SDL and HMI
2. Connect mobile device
3. Register new application → Policy Table Update sequence is triggered:
‘SDL.OnStatusUpdate (UPDATE_NEEDED)’ notification is sent to HMI
4. Perform Ignition Off / On
5. Start SDL and HMI
6. Connect mobile device
7. Register the same application

##### Expected Behavior
Policy Table Update sequence is triggered: ‘SDL.OnStatusUpdate (UPDATE_NEEDED)’ notification is sent to HMI

##### Observed Behavior
‘SDL.OnStatusUpdate (UPDATE_NEEDED)’ notification isn’t sent

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
* HTTP:
  - [Defects/4_5/1206_REQUEST_PTU_Trigger_PTU_failed_previous_IGN_ON](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1206_REQUEST_PTU_Trigger_PTU_failed_previous_IGN_ON.lua)
  - [Policies/build_options/050_ATF_Request_PTU_Trigger_PTU_failed_previous_IGN_ON_HTTP](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/build_options/050_ATF_Request_PTU_Trigger_PTU_failed_previous_IGN_ON_HTTP.lua)
  - [Policies/build_options/098_ATF_PTU_Unsuccessful_Even_After_Retry_Strategy_HTTP](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/build_options/098_ATF_PTU_Unsuccessful_Even_After_Retry_Strategy_HTTP.lua)
* PROPRIETARY:
  - [Policies/build_options/107_ATF_PTU_in_case_of_failed_retry_strategy_during_previous_IGN_ON_PROPRIETARY](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/build_options/107_ATF_PTU_in_case_of_failed_retry_strategy_during_previous_IGN_ON_PROPRIETARY.lua)
* EXTERNAL_PROPRIETARY:
  - [Policies/Policy_Table_Update/122_ATF_PTU_NotSuccessful_AppID_ListedPT_NewIgnCycle](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/Policy_Table_Update/122_ATF_PTU_NotSuccessful_AppID_ListedPT_NewIgnCycle.lua)

### PR DESCRIPTION
**Pull request by AByzhynar**
**NOTE** This PR must be merged after PR: #2488  ONLY
as it based on changes provided in PR specified above.

Fixes #2489 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
* HTTP:
  - [Defects/4_5/1206_REQUEST_PTU_Trigger_PTU_failed_previous_IGN_ON](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1206_REQUEST_PTU_Trigger_PTU_failed_previous_IGN_ON.lua)
  - [Policies/build_options/050_ATF_Request_PTU_Trigger_PTU_failed_previous_IGN_ON_HTTP](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/build_options/050_ATF_Request_PTU_Trigger_PTU_failed_previous_IGN_ON_HTTP.lua)
  - [Policies/build_options/098_ATF_PTU_Unsuccessful_Even_After_Retry_Strategy_HTTP](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/build_options/098_ATF_PTU_Unsuccessful_Even_After_Retry_Strategy_HTTP.lua)
* PROPRIETARY:
  - [Policies/build_options/107_ATF_PTU_in_case_of_failed_retry_strategy_during_previous_IGN_ON_PROPRIETARY](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/build_options/107_ATF_PTU_in_case_of_failed_retry_strategy_during_previous_IGN_ON_PROPRIETARY.lua)
* EXTERNAL_PROPRIETARY:
  - [Policies/Policy_Table_Update/122_ATF_PTU_NotSuccessful_AppID_ListedPT_NewIgnCycle](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/Policy_Table_Update/122_ATF_PTU_NotSuccessful_AppID_ListedPT_NewIgnCycle.lua)

### Summary
Added missed call of UpdateStatusManager::OnStausUpdate (UPDATE_NEEDED) to all Policy Flows:
HTTP, PROPRIETARY and  EXTERNAL_PROPRIETARY 

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/policy/policy_external/src/policy_manager_impl.cc [hunk 1]
```diff
@@ -1774,12 +1774,15 @@ StatusNotifier PolicyManagerImpl::AddApplication(
...
   if (IsNewApplication(application_id)) {
+    LOG4CXX_DEBUG(logger_, "Adding new application");
     AddNewApplication(application_id, device_consent);
     return std::make_shared<CallStatusChange>(update_status_manager_,
                                               device_consent);
   } else {
+    LOG4CXX_DEBUG(logger_, "Promote existed application");
     PromoteExistedApplication(application_id, device_consent);
-    return std::make_shared<utils::CallNothing>();
+    return std::make_shared<CallStatusChange>(update_status_manager_,
```
Comment (LuxoftAKutsan) [inline src/components/policy/policy_external/src/policy_manager_impl.cc]: @AByzhynar I would extract creating CallStatusChange from `if ` condition in case if we constructing it the same in both branches.

File: src/components/policy/policy_external/src/update_status_manager.cc [hunk 2]
```diff
@@ -121,9 +121,11 @@ void UpdateStatusManager::OnResetRetrySequence() {
 void UpdateStatusManager::OnNewApplicationAdded(const DeviceConsent consent) {
   LOG4CXX_AUTO_TRACE(logger_);
   if (kDeviceAllowed != consent) {
+    LOG4CXX_DEBUG(logger_, "Application registered from non-consented device");
     app_registered_from_non_consented_device_ = true;
```
Comment (APipko) [inline src/components/policy/policy_external/src/update_status_manager.cc]: Why app_registered_from_non_consented_device_ == true by default (in constructor)? It would be incorrect for consented device without applications, in this case SDL sends OnStatusUpdate(UPDATE_NEEDED) in OnDeviceConsented() without triggers

Comment (AByzhynar) [reply src/components/policy/policy_external/src/update_status_manager.cc]: @APipko It is impossible case for real usage.

Comment (APipko) [reply src/components/policy/policy_external/src/update_status_manager.cc]: @AByzhynar this case is not realistic, but not impossible. Setting `app_registered_from_non_consented_device_ = true` by default is illogical and confusing. Also sending redundant OnStatusUpdate(UPDATE_NEEDED) misleads during analyzing ATF test scripts logs.

Comment (AByzhynar) [reply src/components/policy/policy_external/src/update_status_manager.cc]: @APipko Detailed flow, please

Comment (APipko) [reply src/components/policy/policy_external/src/update_status_manager.cc]: @AByzhynar For example https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/RC/CLIMATE_RADIO/Capabilities/001_All_modules_all_params.lua#L34
Device is consented without registered applications

Comment (AByzhynar) [reply src/components/policy/policy_external/src/update_status_manager.cc]: @APipko Check your link again!!! CAREFULLY!!!! There is 1 application REGISTERED and ACTIVATED!!!!

Comment (APipko) [reply src/components/policy/policy_external/src/update_status_manager.cc]: @AByzhynar As far as I understand, registration and activation of the application are performed in the next lines. In line#34 only SDL started, HMI initialized, mobile connected and consented. And right after that OnStatusUpdate(UPDATE_NEEDED) is sent.
``` 
HMI->SDL : "method":"SDL.OnAllowSDLFunctionality"
MOB->SDL : controlMsg: StartService
SDL->HMI : "method":"BasicCommunication.UpdateDeviceList"
HMI->SDL : "result":{"method":"BasicCommunication.UpdateDeviceList","code":0}
SDL->HMI : "method":"SDL.OnStatusUpdate","params":{"status":"UPDATE_NEEDED"}
SDL->MOB : controlMsg: StartServiceACK 
MOB->SDL : rpcFunction: RegisterAppInterface 
```

**Comment by JackLivio** [comment]
Retargeting for release/5.0.0 branch

**Comment by AByzhynar** [comment]
@JackLivio AS the base branch was changed to release/5.0.0 and this PR depends on changes in #2488  
PR: #2488 2488 was also targeted to release/5.0.0 branch

**Comment by AByzhynar** [comment]
PR updated . Now testing all Policy flows (HTTP, PROPRIETARY and EXTENDED_PROPRIETARY) for regression.

File: src/components/policy/policy_regular/src/policy_manager_impl.cc [hunk 3]
```diff
@@ -1289,7 +1290,6 @@ bool PolicyManagerImpl::InitPT(const std::string& file_name,
   const bool ret = cache_->Init(file_name, settings);
   if (ret) {
     RefreshRetrySequence();
-    update_status_manager_.OnPolicyInit(cache_->UpdateRequired());
```
Comment (jacobkeeler) [inline src/components/policy/policy_regular/src/policy_manager_impl.cc]: This function is now unused

**Comment by JackLivio** [comment]
Merging, will remove `OnPolicyInit` in separate PR. Function is unused in regular policies as well.

**Comment by AByzhynar** [comment]
@JackLivio can we create separate PR with `OnPolicyInit() ` function removal? Or somebody from your team has already done this?

**Comment by jacobkeeler** [comment]
@AByzhynar it has already been done: #2650
