### PR TITLE
Fix SDL behavior during low voltage

### LINKED ISSUE #2996: SDL doesn't WAKE_UP after LOW_VOLTAGE signal
### Bug Report
SDL does not WAKE_UP after LOW_VOLTAGE signal

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile, register App
2. Send `LOW_VOLTAGE` signal
3. Wait a few seconds and send `WAKE_UP` signal

##### Expected Behavior
SDL wakes up and starts resumption sequence

##### Observed Behavior
SDL doesn't wake up

##### OS & Version Information
* OS/Version: Ubuntu 16.04 amd64
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (8db0c26)
* ATF: https://github.com/smartdevicelink/sdl_atf/tree/develop
* Testing Against: ATF (script, report and logs are in attachment)

##### Test Case, Sample Code, and / or Example App
- [SDL5_0/low_voltage.txt](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/master/test_sets/SDL5_0/low_voltage.txt)
- [2019-08-23_10-17-50.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3534944/2019-08-23_10-17-50.tar.gz)

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #2996 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Covered by ATF test scripts

### Summary
There were found a several problems during SDL testing with ATF scripts:
1. SDL ignores messages from mobile/HMI during low voltage but as they are still delivered to the independent external container (e.g. socket) during Low Voltage - when SDL wakes up - it is not aware what data was in the container and starts processing them. 
2. Sometimes SDL ignores messages on wake up due to timings
3. SDL low voltage process is not stopping properly by exit() function
4. SDL does not send OnAppUnregistered after wake up to HMI

To solve mentioned problems, the following changes were done:
1.  `exit()` was replaced with `_Exit()` which allow to force close the child process which has fully done its job.
2. Suspend transport events processing threads during low voltage, such as unexpected disconnect etc. These events should be processed when SDL wakes up completely.
3. Suspend all client listening threads and shut down sockets for a TCP connections to prevent any possibility to receive message during low voltage. These threads will be resumed on wake up.
4.  Set `low_voltage` flag to false in the end of `wakeup()` function to prevent any timing issues.
5. Don't add pending requests/notifications into request controller if low voltage event has happened, as it may happen at any moment
6. Don't handle received pending messages from mobile/HMI  in RPC handler if low voltage event has happened as it may happen at any moment

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by AByzhynar** [comment]
@theresalech PR is ready for **Livio** team review. Thank you.

**Comment by dboltovskyi** [comment]
@theresalech Please notice there is an update in scripts related to the issue which needs to be taken into account as well: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2261

**Comment by iCollin** [comment]
There is quite a bit of duplicated code in this PR. It would be more maintainable to add a parameter to existing functions in Transport Manager, Transport Adapter and TCP Client Listener that determines the functionality than to have these duplicate functions.

> 3. Suspend all client listening threads and shut down sockets for a TCP connections to prevent any possibility to receive message during low voltage. These threads will be resumed on wake up.

While shutting down sockets was added in this PR, the TCP Client Listener thread will be joined in both current version and this branch. In fact, this PR removes the joining of the Interface Listener thread which is happening currently.

**Comment by AByzhynar** [comment]
@iCollin Please check the reply. Thank you. 

> There is quite a bit of duplicated code in this PR. It would be more maintainable to add a parameter to existing functions in Transport Manager, Transport Adapter and TCP Client Listener that determines the functionality than to have these duplicate functions.

Sure. You are right. We will try to combine duplicated code into functions.


> > 1. Suspend all client listening threads and shut down sockets for a TCP connections to prevent any possibility to receive message during low voltage. These threads will be resumed on wake up.

> While shutting down sockets was added in this PR, the TCP Client Listener thread will be joined in both current version and this branch. In fact, this PR removes the joining of the Interface Listener thread which is happening currently. 

This was made intentionally as all the threads will be suspended during Low Voltage and all we need to do is just shutdown and close appropriate sockets and re-create them on WakeUp. So when the thread will be woken up - it will use new socket.

**Comment by theresalech** [comment]
@AByzhynar please let us know when this is ready for re-review

**Comment by AByzhynar** [comment]
@iCollin Duplilacted code removed in 768a22cdf6bc4f71c075fcd8a922f1d09fe3509f

**Comment by AByzhynar** [comment]
@theresalech PR is ready for re-review

**Comment by AByzhynar** [comment]
@iCollin Please don't merge after approval. I would like to squash commits to make history clear and understandable.

**Comment by iCollin** [comment]
> @iCollin Please don't merge after approval. I would like to squash commits to make history clear and understandable. Just `APPROVE` - and I will squash them and let you know that PR can be merged. Thank you.

I will squash and merge after I approve this PR, should get around to review in a few hours.

**Comment by AByzhynar** [comment]
> > @iCollin Please don't merge after approval. I would like to squash commits to make history clear and understandable. Just `APPROVE` - and I will squash them and let you know that PR can be merged. Thank you.
> 
> I will squash and merge after I approve this PR, should get around to review in a few hours.
Ok. Thank you. We have checked all unit tests as well as all regression tests.

File: src/components/transport_manager/src/transport_manager_impl.cc [hunk 1]
```diff
@@ -609,21 +628,19 @@ int TransportManagerImpl::Visibility(const bool& on_off) const {
...
-       it != transport_adapters_.end();
-       ++it) {
-    if (on_off) {
-      ret = (*it)->StartClientListening();
-    } else {
-      ret = (*it)->StopClientListening();
-    }
+  TransportAdapter::Error ret = TransportAdapter::Error::UNKNOWN;
+
+  for (auto adapter_ptr : transport_adapters_) {
```
Comment (AByzhynar) [inline src/components/transport_manager/src/transport_manager_impl.cc]: @iCollin I have updated the code and make it even more short and simple

File: src/components/transport_manager/src/transport_manager_impl.cc [hunk 2]
```diff
@@ -609,21 +628,19 @@ int TransportManagerImpl::Visibility(const bool& on_off) const {
...
+    ret = adapter_ptr->ChangeClientListening(required_action);
```
Comment (AByzhynar) [inline src/components/transport_manager/src/transport_manager_impl.cc]: @iCollin as well as here

**Comment by iCollin** [comment]
We would appreciate if you did not force push on sdl_core repository. It makes it difficult to review a PR because we cannot tell what was changed since the last review. In general, please do not rebase, do not force push against sdl_core. Instead, you can merge the current develop branch into your PR branch. Please pass this information along to your team members. Thank you
