### PR TITLE
Fix/sdl crash during set app icon

### LINKED ISSUE #3131: CCB: SmartDeviceLink crash SIGABRT in file_system::DirectorySize
### Bug Report
SmartDeviceLink crashed during SetAppIcon :file_system::

#### Linked issues from CCB list
- Potential fix for a core crash in SetAppIcon object 
- More potentially dangerous places fixes 

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile
2. Register new app

##### Expected Behavior
1. App registered successfully

##### Observed Behavior
1. SDL crashed during SetAppIcon

##### OS & Version Information
OS/Version: Ubuntu 16.04
SDL Core Version: https://github.com/AByzhynar/sdl_core/tree/fix/SegFault_in_TransportManagerDefault_unit_tests (a47127) on base https://github.com/smartdevicelink/sdl_core/tree/release/6.0.1 (60b57cd)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (91d5940)
Mobile Apps: SPT(20191112)
Transport: USB/WiFi
Testing : Manually

##### Attachments
[Core_dump.zip](https://github.com/smartdevicelink/sdl_core/files/3879507/Core_dump.zip)
[SDL.zip](https://github.com/smartdevicelink/sdl_core/files/3879508/SDL.zip)
[StackTrace.zip](https://github.com/smartdevicelink/sdl_core/files/3879509/StackTrace.zip)
[HMI_log.zip](https://github.com/smartdevicelink/sdl_core/files/3879512/HMI_log.zip)

### PR DESCRIPTION
**Pull request by AByzhynar**
Fixes #3131 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Manual testing was performed

### Summary
File system operations were performed in a way that sometimes they throw exceptions.
As SDL does not handle exceptions(it is exception-safe code): all file system operations which can throw exceptions were replaced by similar ones from boost library. Now all file system operations will not twrow the exceptions but will return appropriate error codes which are handled by SDL core. 

##### Breaking Changes
N/A

### Tasks Remaining:
- [x] [Rework Unit tests for updated file system functions]

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/utils/src/file_system.cc [hunk 1]
```diff
@@ -47,80 +47,115 @@
...
   fs::space_info si = fs::space(path, ec);
 
   if (ec) {
     // If something went wrong, assume no free space
-    return 0;
-  } else {
-    return si.free;
+    LOG4CXX_ERROR_WITH_ERRNO(logger_,
+                             "Unable to get available disk space: '"
+                                 << path << "', reason: " << ec.message());
```
[the remark this answers is not in the document]
Comment (AByzhynar) [reply src/components/utils/src/file_system.cc]: @AKalinich-Luxoft You are wrong. Check the following code: 
```cpp
#include <boost/filesystem.hpp>
#include <iostream>

using namespace boost::filesystem;
using boost::system::error_code;

int main()
{
  path p{"C:"};
  error_code ec;
  space_info s;
  s.capacity = 1;
  s.free = 1;
  s.available = 1;

  s = space(p, ec);
  if(ec) {
    std::cout << "Error occured" << "\n";   
  }
  std::cout << s.capacity << '\n';
  std::cout << s.free << '\n';
  std::cout << s.available << '\n';
 
  return 0;
}
```

but anyway I will make a change to make it more clear

**Comment by AByzhynar** [comment]
@theresalech PR is READY for Livio team review.

**Comment by theresalech** [comment]
@AByzhynar thank you. We are currently working on finalizing the roadmap with the Steering Committee, so will keep this PR in consideration for upcoming Core releases.

File: src/components/utils/src/file_system.cc [hunk 2]
```diff
@@ -47,80 +47,116 @@
...
+      if (ec) {
+        LOG4CXX_WARN_WITH_ERRNO(logger_,
+                                "Failed to get file_size: '"
+                                    << path << "', reason: " << ec.message());
+      } else {
+        // No error means we can add the file
+        dir_size += fsize;
+        LOG4CXX_DEBUG(logger_, "Adding: " << fsize << ", total: " << dir_size);
+      }
+    }
```
Comment (jacobkeeler) [inline src/components/utils/src/file_system.cc]: Shouldn't this be called recursively if this entry is a directory?

Comment (AByzhynar) [reply src/components/utils/src/file_system.cc]: @jacobkeeler No as we have used special iterator type from boost library: `recursive_directory_iterator`
recursive_directory_iterator provides standard library compliant iteration over the contents of a directory, including recursion into its sub-directories. 
Reference: [Recursive iterator](https://www.boost.org/doc/libs/1_66_0/libs/filesystem/doc/reference.html#Class-recursive_directory_iterator)
