### PR TITLE
Fix LastState methods thread safe access

### LINKED ISSUE #2465: CCB: Update LastState dictionary usages in resumption
### Bug Report
Needed implemented LastStateWrapper class for providing exclusive thread safe access to LastState instance from all places in the program.

##### Linked issues from CCB list
1. Fix potential mutex deadlocks in resumption storage
2. Fix deadlock while terminating 
3. LastState refactoring 

##### Description: 
Needed implemented LastStateWrapper class for providing exclusive thread-safe access to LastState instance from all places in the program. Needed replaced with LastStateWrapper object to avoid direct access to LastState instance from other components. 

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: [develop](https://github.com/smartdevicelink/sdl_core/commit/d36316738785c96dab2ee892762ed08c059fffde)
* Testing Against: ATF

##### BackTrace and Core file: 
[core.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3819142/core.tar.gz)
[GdbBackTrace.txt](https://github.com/smartdevicelink/sdl_core/files/3819143/GdbBackTrace.txt)

### PR DESCRIPTION
**Pull request by LitvinenkoIra**
Fixes #2465 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
There was implemented LastStateWrapper class for providing exclusive thread safe access to LastState instance from all places in the program. Also passing LastState object was replaced with LastStateWrapper object to avoid direct access to LastState instance from another components. Thus there was a small updates in architecture of AM and TM classes.
Also fixed related mocks and unit tests.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/app_launch/app_launch_data_json.cc [hunk 1]
```diff
@@ -204,9 +220,10 @@ bool AppLaunchDataJson::Clear() {
 
 uint32_t AppLaunchDataJson::GetCurentNumberOfAppData() const {
   LOG4CXX_AUTO_TRACE(logger_);
-
-  uint32_t list_size = GetSavedApplicationDataList().size();
-
+  resumption::LastStateAccessor accessor = last_state_wrapper_.get_accessor();
+  Json::Value dictionary = accessor.GetData().get_dictionary();
+  uint32_t list_size = GetSavedApplicationDataList(dictionary).size();
```
Comment (AByzhynar) [inline src/components/application_manager/src/app_launch/app_launch_data_json.cc]: @LitvinenkoIra const?

File: src/components/application_manager/src/app_launch/app_launch_data_json.cc [hunk 2]
```diff
@@ -241,8 +260,8 @@ bool AppLaunchDataJson::DeleteOldestAppData() {
 
   // Copy in temporary vector Json list without oldest record
   int32_t i = 0;
-  for (Json::Value::iterator it = GetSavedApplicationDataList().begin();
-       it != GetSavedApplicationDataList().end();
+  apps_list = GetSavedApplicationDataList(dictionary);
```
Comment (AByzhynar) [inline src/components/application_manager/src/app_launch/app_launch_data_json.cc]: @LitvinenkoIra Why did you call this function again?

File: src/components/resumption/include/resumption/last_state.h [hunk 3]
```diff
@@ -45,16 +43,23 @@ class LastState {
...
+  /**
+   * @brief Remove dictionary from filesystem
    */
-  virtual void SaveStateToFileSystem() = 0;
-
+  virtual void RemoveFromFileSystem() = 0;
+  /**
+    * @brief Get reference to dictionary
+    */
+  virtual Json::Value get_dictionary() const = 0;
```
Comment (AByzhynar) [inline src/components/resumption/include/resumption/last_state.h]: @LitvinenkoIra Where is the reference?

File: src/components/application_manager/src/resumption/resumption_data_json.cc [hunk 4]
```diff
@@ -503,7 +568,10 @@ bool ResumptionDataJson::DropAppDataResumption(const std::string& device_id,
...
   using namespace app_mngr;
   sync_primitives::AutoLock autolock(resumption_lock_);
-  Json::Value& application = GetFromSavedOrAppend(app_id, device_id);
+  resumption::LastStateAccessor accessor = last_state_wrapper_.get_accessor();
+  Json::Value dictionary = accessor.GetData().get_dictionary();
+  Json::Value& application =
+      GetFromSavedOrAppend(app_id, device_id, dictionary);
   if (application.isNull()) {
     LOG4CXX_DEBUG(logger_,
                   "Application " << app_id << " with device_id " << device_id
```
Comment (LitvinenkoIra) [inline src/components/application_manager/src/resumption/resumption_data_json.cc]: @LitvinenkoIra add _accessor.GetMutableData().set_dictionary(dictionary);_ before return

**Comment by LitvinenkoIra** [comment]
@AKalinich-Luxoft @AByzhynar please take a look at the latest updates

File: src/components/application_manager/src/app_launch/app_launch_data_json.cc [hunk 5]
```diff
@@ -219,7 +236,9 @@ bool AppLaunchDataJson::DeleteOldestAppData() {
   sync_primitives::AutoLock autolock(app_launch_json_lock_);
   std::vector<uint64_t> temp_array;
   std::vector<Json::Value> temp_json_list;
-  Json::Value& apps_list = GetSavedApplicationDataList();
+  resumption::LastStateAccessor accessor = last_state_wrapper_->get_accessor();
+  Json::Value dictionary = accessor.GetData().dictionary();
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/app_launch/app_launch_data_json.cc]: @LitvinenkoIra what is the purpose of copying dictionary if it won''t be modified? Can you init is with cont ref?

File: src/components/application_manager/src/resumption/resumption_data_json.cc [hunk 6]
```diff
@@ -148,32 +160,45 @@ void ResumptionDataJson::IncrementIgnOffCount() {
...
-      LOG4CXX_WARN(logger_, "Unknown key among saved applications");
-      Json::Value& ign_off_count = (*it)[strings::ign_off_count];
-      ign_off_count = 1;
+  Json::Value dictionary;
+  {
+    resumption::LastStateAccessor accessor =
+        last_state_wrapper_->get_accessor();
+    dictionary = accessor.GetData().dictionary();
+    Json::Value& saved_apps = GetSavedApplications(dictionary);
+    for (Json::Value::iterator it = saved_apps.begin(); it != saved_apps.end();
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/resumption/resumption_data_json.cc]: @LitvinenkoIra rename it to app or json_app

File: src/components/application_manager/src/app_launch/app_launch_data_json.cc (hunk 5 above)
Comment (LitvinenkoIra) [reply src/components/application_manager/src/app_launch/app_launch_data_json.cc]: @LuxoftAKutsan we modify the dictionary in _GetApplicationData_ function .
DeleteOldestAppData -> GetSavedApplicationDataList -> GetApplicationData

File: src/components/application_manager/src/resumption/resumption_data_json.cc (hunk 6 above)
Comment (LitvinenkoIra) [reply src/components/application_manager/src/resumption/resumption_data_json.cc]: @LuxoftAKutsan done 86d7ed7ca314f780ee977f843c0bacff8b471c4a

File: src/components/application_manager/src/app_launch/app_launch_data_json.cc (hunk 2 above)
Comment (LitvinenkoIra) [reply src/components/application_manager/src/app_launch/app_launch_data_json.cc]: @AByzhynar removed 86d7ed7ca314f780ee977f843c0bacff8b471c4a

**Comment by LitvinenkoIra** [comment]
@AKalinich-Luxoft @AByzhynar please take a look at the latest updates

File: src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h [hunk 7]
```diff
@@ -120,7 +122,7 @@ class AppLaunchDataJson : public AppLaunchDataImpl {
    * @return pointer to LastState functionality
    */
   resumption::LastState& last_state() const {
-    return last_state_;
+    return last_state_wrapper_->get_accessor().GetMutableData();
```
[the remark this answers is not in the document]
Comment (LitvinenkoIra) [reply src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h]: @AKalinich-Luxoft fixed 4a3b3cdfa0f84418bf9805759765cf1a519b5cf3

File: src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h [hunk 8]
```diff
@@ -52,8 +52,9 @@ class AppLaunchDataJson : public AppLaunchDataImpl {
   /**
    * @brief Constructor of AppLaunchDataJson object
    */
-  AppLaunchDataJson(const AppLaunchSettings& settings,
-                    resumption::LastState& last_state);
+  AppLaunchDataJson(
+      const AppLaunchSettings& settings,
+      std::shared_ptr<resumption::LastStateWrapper> last_state_wrapper);
```
[the remark this answers is not in the document]
Comment (LitvinenkoIra) [reply src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h]: @AKalinich-Luxoft done 
bad172b

**Comment by LitvinenkoIra** [comment]
@AKalinich-Luxoft @AByzhynar @LuxoftAKutsan  please take a look at the latest updates

File: src/components/application_manager/src/resumption/resumption_data_json.cc [hunk 9]
```diff
@@ -148,32 +156,45 @@ void ResumptionDataJson::IncrementIgnOffCount() {
...
-    to_save.append(*it);
+    SetSavedApplication(to_save, dictionary);
+    SetLastIgnOffTime(time(NULL), dictionary);
   }
-  SetSavedApplication(to_save);
-  SetLastIgnOffTime(time(NULL));
-  LOG4CXX_DEBUG(logger_, GetResumptionData().toStyledString());
+  {
+    resumption::LastStateAccessor accessor =
+        last_state_wrapper_->get_accessor();
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/src/resumption/resumption_data_json.cc]: @LitvinenkoIra this one has no sense.
Why do you need to re-acquire accessor here as you already has another one?
Just use existing accessor:
```
    SetSavedApplication(to_save, dictionary);
    SetLastIgnOffTime(time(NULL), dictionary);
    accessor.GetMutableData().set_dictionary(dictionary);
```
P.S. you could remove scopes from line 160 as you need accessor to be alive till the end of this function

Comment (LitvinenkoIra) [reply src/components/application_manager/src/resumption/resumption_data_json.cc]: @AKalinich-Luxoft fixed 585843bef0ad1e839a35048f1ee4eef77c9eaabc

**Comment by LitvinenkoIra** [comment]
Rebuild required

File: src/components/include/resumption/last_state.h [hunk 10]
```diff
@@ -0,0 +1,68 @@
+/*
+ * Copyright (c) 2017, Ford Motor Company
```
Comment (AByzhynar) [inline src/components/include/resumption/last_state.h]: @LitvinenkoIra Year...

File: src/components/include/resumption/last_state.h [hunk 11]
```diff
@@ -0,0 +1,68 @@
...
+  /**
+   * @brief Remove dictionary from filesystem
+   */
+  virtual void RemoveFromFileSystem() = 0;
+  /**
+   * @brief Gets internal dictionary
+   * @return Copy of internal dictionary json value
+   */
+  virtual Json::Value dictionary() const = 0;
+  /**
```
Comment (AByzhynar) [inline src/components/include/resumption/last_state.h]: @LitvinenkoIra Empty lines between functions...

File: src/components/include/resumption/last_state.h [hunk 12]
```diff
@@ -0,0 +1,68 @@
...
+   * @brief Resets internal dictionary
+   * @param dictionary New dictionary json value to be set
+   */
+  virtual void set_dictionary(const Json::Value& dictionary) = 0;
```
Comment (AByzhynar) [inline src/components/include/resumption/last_state.h]: @LitvinenkoIra Discription mismatches function name

Comment (LitvinenkoIra) [reply src/components/include/resumption/last_state.h]: @AByzhynar fixed d3243c5efacbfd978a09688a583d442c56865a90

File: src/components/include/resumption/last_state.h (hunk 11 above)
Comment (LitvinenkoIra) [reply src/components/include/resumption/last_state.h]: @AByzhynar fixed d3243c5efacbfd978a09688a583d442c56865a90

File: src/components/include/resumption/last_state.h (hunk 10 above)
Comment (LitvinenkoIra) [reply src/components/include/resumption/last_state.h]: @AByzhynar fixed d3243c5efacbfd978a09688a583d442c56865a90

File: src/components/application_manager/include/application_manager/resumption/resumption_data_json.h [hunk 13]
```diff
@@ -49,9 +49,15 @@ class ResumptionDataJson : public ResumptionData {
    * @brief Constructor of ResumptionDataJson
    */
   ResumptionDataJson(
-      LastState& last_state,
+      resumption::LastStateWrapperPtr last_state_wrapper,
       const application_manager::ApplicationManager& application_manager);
 
+  DEPRECATED
+  ResumptionDataJson(
```
Comment (ZhdanovP) [inline src/components/application_manager/include/application_manager/resumption/resumption_data_json.h]: @LitvinenkoIra Do we still store DEPRECATED code? I though that we got rid of it.

File: src/components/application_manager/include/application_manager/resumption/resumption_data_json.h [hunk 14]
```diff
@@ -176,7 +182,7 @@ class ResumptionDataJson : public ResumptionData {
   void Persist() OVERRIDE;
 
   resumption::LastState& last_state() const {
-    return last_state_;
+    return last_state_wrapper_->get_accessor().GetMutableData();
```
Comment (ZhdanovP) [inline src/components/application_manager/include/application_manager/resumption/resumption_data_json.h]: @LitvinenkoIra Don't we need lock this part?

File: src/components/application_manager/src/app_launch/app_launch_data_json.cc [hunk 15]
```diff
@@ -111,12 +114,22 @@ Json::Value& AppLaunchDataJson::GetApplicationListAndIndex(
   return apps_list;
 }
 
+Json::Value& AppLaunchDataJson::GetApplicationListAndIndex(
+    const ApplicationData& app_data, int32_t& founded_index) const {
+  static Json::Value value;
+  return value;
```
Comment (ZhdanovP) [inline src/components/application_manager/src/app_launch/app_launch_data_json.cc]: @LitvinenkoIra Do we still need this override when we have 

`Json::Value& AppLaunchDataJson::GetApplicationListAndIndex(
    const ApplicationData& app_data,
    int32_t& founded_index,
Json::Value& dictionary) const`
?

File: src/components/application_manager/src/app_launch/app_launch_data_json.cc [hunk 16]
```diff
@@ -111,12 +114,22 @@ Json::Value& AppLaunchDataJson::GetApplicationListAndIndex(
...
+
 bool AppLaunchDataJson::IsAppDataAlreadyExisted(
     const ApplicationData& app_data) const {
   LOG4CXX_AUTO_TRACE(logger_);
 
   int32_t index = NotFound;
-  GetApplicationListAndIndex(app_data, index);
+
+  resumption::LastStateAccessor accessor = last_state_wrapper_->get_accessor();
+  Json::Value dictionary = accessor.GetData().dictionary();
```
Comment (ZhdanovP) [inline src/components/application_manager/src/app_launch/app_launch_data_json.cc]: @LitvinenkoIra Don't we need thread safe here?

File: src/components/application_manager/include/application_manager/resumption/resumption_data_json.h (hunk 14 above)
Comment (LitvinenkoIra) [reply src/components/application_manager/include/application_manager/resumption/resumption_data_json.h]: @ZhdanovP this function is redundant, so I removed it

File: src/components/application_manager/src/app_launch/app_launch_data_json.cc (hunk 15 above)
Comment (LitvinenkoIra) [reply src/components/application_manager/src/app_launch/app_launch_data_json.cc]: @ZhdanovP removed

File: src/components/application_manager/src/app_launch/app_launch_data_json.cc (hunk 16 above)
Comment (LitvinenkoIra) [reply src/components/application_manager/src/app_launch/app_launch_data_json.cc]: @ZhdanovP take a look at last_state_wrapper implementation.
It's already thread safe

**Comment by LitvinenkoIra** [comment]
> @LitvinenkoIra Use `DEPRECATED` macro when you need to change public interface

@AByzhynar Done 
42cba48

File: src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h [hunk 17]
```diff
@@ -132,12 +134,12 @@ class AppLaunchDataJson : public AppLaunchDataImpl {
...
    * @return pointer to AppLaunch data block in Json file
    */
-  Json::Value& GetSavedApplicationDataList() const;
+  Json::Value& GetSavedApplicationDataList(Json::Value& dictionary) const;
 
   /**
    * @return pointer to AppLaunch records block in Json file
    */
-  Json::Value& GetApplicationData() const;
+  Json::Value& GetApplicationData(Json::Value& dictionary) const;
```
Comment (AByzhynar) [inline src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h]: @LitvinenkoIra Is it a part of public interface?

File: src/components/application_manager/src/application_manager_impl.cc [hunk 18]
```diff
@@ -1697,8 +1697,9 @@ void ApplicationManagerImpl::RemoveHMIFakeParameters(
   factory.attachSchema(*message, true);
 }
 
-bool ApplicationManagerImpl::Init(resumption::LastState& last_state,
-                                  media_manager::MediaManager* media_manager) {
+bool ApplicationManagerImpl::Init(
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_manager_impl.cc]: @LitvinenkoIra Is a part of public interface?

File: src/components/include/resumption/last_state.h (hunk 12 above)
Comment (AByzhynar) [reply src/components/include/resumption/last_state.h]: @LitvinenkoIra Description still mismatches... Method does no reset... It just sets value and it is called accordingly

File: src/components/include/resumption/last_state_wrapper.h [hunk 19]
```diff
@@ -0,0 +1,60 @@
...
+namespace resumption {
+class LastStateWrapper;
+typedef std::shared_ptr<LastStateWrapper> LastStateWrapperPtr;
+typedef DataAccessor<LastState> LastStateAccessor;
+
+class LastStateWrapper {
+ public:
+  /**
+   * @brief Getter for providing exclusive access to LastState instance using
+   * provided lock
```
Comment (AByzhynar) [inline src/components/include/resumption/last_state_wrapper.h]: @LitvinenkoIra Where is `provided lock`? Who does provide it?

File: src/components/include/utils/data_accessor.h [hunk 20]
```diff
@@ -59,6 +59,9 @@ class DataAccessor {
   const T& GetData() const {
     return data_;
   }
+  T& GetMutableData() const {
```
Comment (AByzhynar) [inline src/components/include/utils/data_accessor.h]: @LitvinenkoIra Empty lines between functions

File: src/components/resumption/include/resumption/last_state_impl.h [hunk 21]
```diff
@@ -45,35 +48,50 @@ namespace resumption {
 class LastStateImpl : public LastState {
  public:
   /**
-   * @brief Constructor
-   */
+     * @brief Constructor
+     */
```
Comment (AByzhynar) [inline src/components/resumption/include/resumption/last_state_impl.h]: @LitvinenkoIra Wrong indents?

File: src/components/resumption/include/resumption/last_state_impl.h [hunk 22]
```diff
@@ -45,35 +48,50 @@ namespace resumption {
...
-   */
+     * @brief Destructor
+     */
   ~LastStateImpl();
 
+  DEPRECATED
+  void SaveStateToFileSystem() {}
+
+  /**
+     * @brief Saving dictionary to filesystem
```
Comment (AByzhynar) [inline src/components/resumption/include/resumption/last_state_impl.h]: @LitvinenkoIra Same as above...

File: src/components/resumption/include/resumption/last_state_impl.h [hunk 23]
```diff
@@ -45,35 +48,50 @@ namespace resumption {
...
+     */
+  void SaveToFileSystem() OVERRIDE;
+  /**
```
Comment (AByzhynar) [inline src/components/resumption/include/resumption/last_state_impl.h]: @LitvinenkoIra Empty lines......

File: src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h (hunk 17 above)
Comment (LitvinenkoIra) [reply src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h]: @AByzhynar no, this is a private method

File: src/components/application_manager/src/application_manager_impl.cc (hunk 18 above)
Comment (LitvinenkoIra) [reply src/components/application_manager/src/application_manager_impl.cc]: @AByzhynar Yes. And method marked as deprecated https://github.com/smartdevicelink/sdl_core/pull/2626/files#diff-21171d7cbfd36d53d3224063bd66b757R124 
(take a look at application_manager.h)

File: src/components/resumption/include/resumption/last_state_impl.h (hunk 21 above)
Comment (LitvinenkoIra) [reply src/components/resumption/include/resumption/last_state_impl.h]: @AByzhynar fixed 47eff918a48b552f83b015152642dd51bbc6e8b6

File: src/components/include/utils/data_accessor.h (hunk 20 above)
Comment (LitvinenkoIra) [reply src/components/include/utils/data_accessor.h]: @AByzhynar fixed 47eff91

File: src/components/resumption/include/resumption/last_state_impl.h (hunk 22 above)
Comment (LitvinenkoIra) [reply src/components/resumption/include/resumption/last_state_impl.h]: @AByzhynar fixed 47eff91

File: src/components/resumption/include/resumption/last_state_impl.h (hunk 23 above)
Comment (LitvinenkoIra) [reply src/components/resumption/include/resumption/last_state_impl.h]: @AByzhynar fixed 47eff91

**Comment by LuxoftAKutsan** [comment]
@LitvinenkoIra  please squash commits to create better history

File: src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h [hunk 24]
```diff
@@ -53,7 +52,11 @@ class AppLaunchDataJson : public AppLaunchDataImpl {
    * @brief Constructor of AppLaunchDataJson object
    */
   AppLaunchDataJson(const AppLaunchSettings& settings,
-                    resumption::LastState& last_state);
+                    resumption::LastStateWrapperPtr last_state_wrapper);
+
+  DEPRECATED AppLaunchDataJson(const AppLaunchSettings& settings,
+                               resumption::LastState&) = delete;
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h]: @YarikMamykin do we really need to ` = delete` here?

File: src/components/application_manager/include/application_manager/app_service_manager.h [hunk 25]
```diff
@@ -65,7 +62,7 @@ class AppServiceManager {
    * @param app_manager
    */
   AppServiceManager(ApplicationManager& app_manager,
-                    resumption::LastState& last_state);
+                    resumption::LastStateWrapperPtr last_state);
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/include/application_manager/app_service_manager.h]: @YarikMamykin looks like its a public function. Should we deprecate this?

File: src/components/application_manager/include/application_manager/resumption/resume_ctrl.h [hunk 26]
```diff
@@ -113,9 +111,9 @@ class ResumeCtrl {
    * @brief RestoreAppWidgets add widgets for the application
    * @param application application which will be resumed
    * @param saved_app application specific section from backup file
-   * @return true if widgets resumed successfully otherwise - false
+   * @return the number of widget windows to be resumed
    */
-  virtual void RestoreAppWidgets(
+  virtual size_t RestoreAppWidgets(
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/include/application_manager/resumption/resume_ctrl.h]: @YarikMamykin I believe this is not related to wrapper fix

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_consent_manager.h [hunk 27]
```diff
@@ -70,7 +70,7 @@ class RCConsentManager {
   virtual rc_rpc_plugin::rc_rpc_types::ModuleConsent GetModuleConsent(
       const std::string& app_id,
       const std::string& mac_address,
-      const rc_rpc_types::ModuleUid& module_id) const = 0;
+      const rc_rpc_types::ModuleUid& module_id) = 0;
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_consent_manager.h]: @YarikMamykin is this related to fix?

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_consent_manager_impl.h [hunk 28]
```diff
@@ -149,21 +148,21 @@ class RCConsentManagerImpl : public RCConsentManager {
...
-  resumption::LastState& last_state_;
+  resumption::LastStateWrapperPtr last_state_;
   const uint32_t period_of_consent_expired_;
   mutable sync_primitives::Lock dictionary_control_lock_;
   mutable sync_primitives::Lock remote_control_lock_;
   mutable sync_primitives::Lock device_applications_lock_;
   mutable sync_primitives::Lock applications_lock_;
   mutable sync_primitives::Lock app_consents_lock_;
   mutable sync_primitives::Lock module_consents_lock_;
+  Json::Value last_state_dictionary_;
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_consent_manager_impl.h]: @YarikMamykin I think you should remove this variable as you can always get dictionary using accessor

File: src/components/application_manager/test/app_launch/app_launch_data_json_test.cc [hunk 29]
```diff
@@ -66,16 +67,17 @@ class AppLaunchDataJsonTest : public ::testing::Test {
  private:
   virtual void SetUp() {
     ::file_system::DeleteFile(kAppStorageFile);
-    test_last_state_ = std::unique_ptr<resumption::LastState>(
-        new resumption::LastStateImpl(kAppStorageFolder, kAppInfoStorage));
+    last_state_wrapper_ = std::make_shared<resumption::LastStateWrapperImpl>(
+        std::make_shared<resumption::LastStateImpl>("app_storage_folder",
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/test/app_launch/app_launch_data_json_test.cc]: @YarikMamykin why don't you use `kAppStorageFolder` and `kAppInfoStorage`?

File: src/components/application_manager/test/commands/command_request_impl_test.cc [hunk 30]
```diff
@@ -607,8 +609,10 @@ TEST_F(CommandRequestImplTest, AppNotFound_HashUpdateNotExpected) {
 }
 
 TEST_F(CommandRequestImplTest, SendProviderRequest_ByServiceType) {
-  resumption::LastStateImpl last_state("app_storage_folder",
-                                       "app_info_storage");
+  auto last_state = std::make_shared<resumption::LastStateWrapperImpl>(
+      std::make_shared<resumption::LastStateImpl>("app_storage_folder",
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/test/commands/command_request_impl_test.cc]: @YarikMamykin propose to declare a constants for that

File: src/components/include/resumption/last_state.h [hunk 31]
```diff
@@ -0,0 +1,74 @@
+/*
+ * Copyright (c) 2018, Ford Motor Company
```
Comment (AKalinich-Luxoft) [inline src/components/include/resumption/last_state.h]: @YarikMamykin 2019

File: src/components/include/resumption/last_state_wrapper.h [hunk 32]
```diff
@@ -0,0 +1,57 @@
+/*
+ * Copyright (c) 2018, Ford Motor Company
```
Comment (AKalinich-Luxoft) [inline src/components/include/resumption/last_state_wrapper.h]: @YarikMamykin 2019

File: src/components/include/transport_manager/transport_manager.h [hunk 33]
```diff
@@ -56,11 +53,16 @@ class TransportManager {
    **/
   virtual ~TransportManager() {}
 
+  DEPRECATED
+  virtual int Init(resumption::LastState&) {
+    return 1;
```
Comment (AKalinich-Luxoft) [inline src/components/include/transport_manager/transport_manager.h]: @YarikMamykin what is this?

File: src/components/resumption/include/resumption/last_state_wrapper_impl.h [hunk 34]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2017, Ford Motor Company
+ * Copyright (c) 2018, Ford Motor Company
```
Comment (AKalinich-Luxoft) [inline src/components/resumption/include/resumption/last_state_wrapper_impl.h]: @YarikMamykin 2019

File: src/components/resumption/src/last_state_wrapper_impl.cc [hunk 35]
```diff
@@ -0,0 +1,49 @@
+/* Copyright (c) 2018, Ford Motor Company
```
Comment (AKalinich-Luxoft) [inline src/components/resumption/src/last_state_wrapper_impl.cc]: @YarikMamykin 2019

File: src/components/transport_manager/include/transport_manager/iap2_emulation/iap2_transport_adapter.h [hunk 36]
```diff
@@ -103,9 +107,16 @@ class IAP2USBEmulationTransportAdapter : public TcpTransportAdapter {
    * @param last_state LastState instance reference
    * @param settings Settings reference
    */
+  IAP2USBEmulationTransportAdapter(
```
Comment (AKalinich-Luxoft) [inline src/components/transport_manager/include/transport_manager/iap2_emulation/iap2_transport_adapter.h]: @YarikMamykin is it related to fix?

File: src/components/transport_manager/test/transport_manager_default_test.cc [hunk 37]
```diff
@@ -80,11 +82,13 @@ TEST(TestTransportManagerDefault, Init_LastStateNotUsed) {
   transport_manager::TransportManagerDefault transport_manager(
       transport_manager_settings);
 
-  NiceMock<MockLastState> mock_last_state;
+  auto mock_last_state = std::make_shared<MockLastState>();
```
Comment (AKalinich-Luxoft) [inline src/components/transport_manager/test/transport_manager_default_test.cc]: @YarikMamykin maybe it makes more sense to create MockLastState as the member of `TestTransportManagerDefault`?

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_consent_manager.h (hunk 27 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_consent_manager.h]: @AKalinich-Luxoft , yes it is related to fix because the way to access LastState dictionary was changed.

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_consent_manager_impl.h (hunk 28 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_consent_manager_impl.h]: @AKalinich-Luxoft actually not always. Since 2dd6f73cf75d7c17d86e0313dde501d3766e61c2 `Json::Value& LastState::get_dictionary()` method is replaced with `Json::Value LastState::dictionary()` which returns copy of last state dictionary ( I guess it was done for thread safe access to dictionary ).
Since this change we have to remember changes made in RCConsentManager and update LastState dictionary when it is needed.

File: src/components/application_manager/include/application_manager/resumption/resume_ctrl.h (hunk 26 above)
Comment (YarikMamykin) [reply src/components/application_manager/include/application_manager/resumption/resume_ctrl.h]: @AKalinich-Luxoft I agree with you. This present here because develop branch currently doesn't have 2eafae9d0ae0b352d3b30bd1409bebdcfc447988

File: src/components/include/transport_manager/transport_manager.h (hunk 33 above)
Comment (YarikMamykin) [reply src/components/include/transport_manager/transport_manager.h]: @AKalinich-Luxoft this was provided with 2dd6f73cf75d7c17d86e0313dde501d3766e61c2. It is hard for me to answer why this `DEPRECATED Init` always returned 1)))

File: src/components/transport_manager/include/transport_manager/iap2_emulation/iap2_transport_adapter.h (hunk 36 above)
Comment (YarikMamykin) [reply src/components/transport_manager/include/transport_manager/iap2_emulation/iap2_transport_adapter.h]: @AKalinich-Luxoft , yes it is.

File: src/components/transport_manager/test/transport_manager_default_test.cc (hunk 37 above)
Comment (YarikMamykin) [reply src/components/transport_manager/test/transport_manager_default_test.cc]: @AKalinich-Luxoft fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/fbb80545f327f8a8bdae59ccd540dc284e7e8441

File: src/components/resumption/src/last_state_wrapper_impl.cc (hunk 35 above)
Comment (YarikMamykin) [reply src/components/resumption/src/last_state_wrapper_impl.cc]: @AKalinich-Luxoft fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/61f8fecf23bd114017777ce8d90cdb0fb952edf1

File: src/components/resumption/include/resumption/last_state_wrapper_impl.h (hunk 34 above)
Comment (YarikMamykin) [reply src/components/resumption/include/resumption/last_state_wrapper_impl.h]: @AKalinich-Luxoft fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/61f8fecf23bd114017777ce8d90cdb0fb952edf1

File: src/components/include/resumption/last_state.h (hunk 31 above)
Comment (YarikMamykin) [reply src/components/include/resumption/last_state.h]: @AKalinich-Luxoft fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/61f8fecf23bd114017777ce8d90cdb0fb952edf1

File: src/components/include/resumption/last_state_wrapper.h (hunk 32 above)
Comment (YarikMamykin) [reply src/components/include/resumption/last_state_wrapper.h]: @AKalinich-Luxoft fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/04c5cfc370f27b391e68d65c0f15c5f6fdace435

File: src/components/application_manager/test/commands/command_request_impl_test.cc (hunk 30 above)
Comment (YarikMamykin) [reply src/components/application_manager/test/commands/command_request_impl_test.cc]: @AKalinich-Luxoft  fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/9feb1741ceff524d2cdbb89b03596e288741eff2

File: src/components/application_manager/test/app_launch/app_launch_data_json_test.cc (hunk 29 above)
Comment (YarikMamykin) [reply src/components/application_manager/test/app_launch/app_launch_data_json_test.cc]: @AKalinich-Luxoft fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/5123861995b84627338520ff72ca611a3689295a

File: src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h (hunk 24 above)
Comment (YarikMamykin) [reply src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h]: @AKalinich-Luxoft fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/5123861995b84627338520ff72ca611a3689295a

File: src/components/application_manager/include/application_manager/app_service_manager.h (hunk 25 above)
Comment (YarikMamykin) [reply src/components/application_manager/include/application_manager/app_service_manager.h]: @AKalinich-Luxoft deprecated in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/e4b159464b7b99d6cffd74f6c4a263b2a7243026

File: src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h [hunk 38]
```diff
@@ -53,7 +52,11 @@ class AppLaunchDataJson : public AppLaunchDataImpl {
    * @brief Constructor of AppLaunchDataJson object
    */
   AppLaunchDataJson(const AppLaunchSettings& settings,
-                    resumption::LastState& last_state);
+                    resumption::LastStateWrapperPtr last_state_wrapper);
+
+  DEPRECATED AppLaunchDataJson(const AppLaunchSettings& settings,
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h]: We put it in new release. Remove deprecated staff

Comment (YarikMamykin) [reply src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h]: @LuxoftAKutsan removed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/4be3a56fad6056c2697510133c5a65a598a2ac85

**Comment by AByzhynar** [comment]
@YarikMamykin As I can see you did not remove `DEPRECATED` methods everywhere . WHy?

File: src/components/application_manager/src/app_launch/app_launch_data_json.cc [hunk 39]
```diff
@@ -82,12 +83,14 @@ Json::Value& AppLaunchDataJson::GetApplicationData() const {
 }
 
 Json::Value& AppLaunchDataJson::GetApplicationListAndIndex(
-    const ApplicationData& app_data, int32_t& founded_index) const {
+    const ApplicationData& app_data,
+    int32_t& founded_index,
```
Comment (AByzhynar) [inline src/components/application_manager/src/app_launch/app_launch_data_json.cc]: @YarikMamykin `founded` -> `found` ?

File: src/appMain/life_cycle_impl.cc [hunk 40]
```diff
@@ -80,9 +79,10 @@ LifeCycleImpl::LifeCycleImpl(const profile::Profile& profile)
 
 bool LifeCycleImpl::StartComponents() {
   LOG4CXX_AUTO_TRACE(logger_);
-  DCHECK(!last_state_);
-  last_state_ = new resumption::LastStateImpl(profile_.app_storage_folder(),
-                                              profile_.app_info_storage());
+  DCHECK(!last_state_wrapper_);
+  last_state_wrapper_ = std::make_shared<resumption::LastStateWrapperImpl>(
```
[the remark this answers is not in the document]
Comment (alexkutsan) [reply src/appMain/life_cycle_impl.cc]: @AByzhynar  I do not agree with such approach. LastStateWrapperImpl should know about Last state interface. But I would not say that Wrapper should create LastStateImpl.
If LastStateImpl will be extended with additional dependencies in the future - it should not affect LastStateWrapper. Also testing of last state wrapper would be more complicated if it will create LastStateImpl inside. 

If you have any additional arguments why LastStateWrapper whould create LastStateImpl inside please provide.

[the remark this answers is not in the document]
Comment (AByzhynar) [reply src/appMain/life_cycle_impl.cc]: @alexkutsan Ok. No problem. But create it in a separate line instead of mixing ctor into 2 make_shared operations. Such an approach makes it impossible to debug

File: src/components/application_manager/src/app_launch/app_launch_data_json.cc (hunk 39 above)
Comment (YarikMamykin) [reply src/components/application_manager/src/app_launch/app_launch_data_json.cc]: @AByzhynar , fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/1a5c4105394dc643ba414dbf70deb52afbc045ea

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_consent_manager_impl_test.cc [hunk 41]
```diff
@@ -42,6 +42,8 @@
 #include "rc_rpc_plugin/rc_consent_manager_impl.h"
 #include "resumption/last_state.h"
 #include "resumption/last_state_impl.h"
+#include "resumption/last_state_wrapper.h"
+#include "resumption/last_state_wrapper_impl.h"
```
[the remark this answers is not in the document]
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_consent_manager_impl_test.cc]: @AByzhynar , fixed in 1a5c410

File: src/appMain/life_cycle_impl.cc (hunk 40 above)
[the remark this answers is not in the document]
Comment (YarikMamykin) [reply src/appMain/life_cycle_impl.cc]: @AByzhynar , fixed in 1a5c410

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_consent_manager_impl.h (hunk 28 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_consent_manager_impl.h]: @AByzhynar please check https://github.com/smartdevicelink/sdl_core/pull/2626/commits/c5c0f062625e5fb1485ebb97f4f3258aedcc8f2f

File: src/components/application_manager/src/app_launch/app_launch_data_json.cc [hunk 42]
```diff
@@ -255,15 +272,15 @@ bool AppLaunchDataJson::DeleteOldestAppData() {
   }
 
   // Clear Json list
-  GetSavedApplicationDataList().clear();
+  GetSavedApplicationDataList(dictionary).clear();
 
   // Copy to Json new list without oldest one
   for (std::vector<Json::Value>::iterator it = temp_json_list.begin();
        it != temp_json_list.end();
        ++it) {
```
Comment (SNiukalov) [inline src/components/application_manager/src/app_launch/app_launch_data_json.cc]: @YarikMamykin 
Can we use a range-based for loop like below:
for (const auto& value : temp_json_list)

File: src/components/application_manager/src/app_service_manager.cc [hunk 43]
```diff
@@ -142,10 +142,12 @@ smart_objects::SmartObject AppServiceManager::PublishAppService(
     for (auto it = embedded_services.begin(); it != embedded_services.end();
          ++it) {
```
Comment (SNiukalov) [inline src/components/application_manager/src/app_service_manager.cc]: maybe range-based

File: src/components/application_manager/src/resumption/resumption_data_json.cc [hunk 44]
```diff
@@ -106,16 +110,19 @@ void ResumptionDataJson::SaveApplication(
...
   LOG4CXX_AUTO_TRACE(logger_);
   sync_primitives::AutoLock autolock(resumption_lock_);
-  for (Json::Value::iterator it = GetSavedApplications().begin();
-       it != GetSavedApplications().end();
-       ++it) {
+  resumption::LastStateAccessor accessor = last_state_wrapper_->get_accessor();
+  Json::Value dictionary = accessor.GetData().dictionary();
+  const Json::Value& saved_apps = GetSavedApplications(dictionary);
+
+  for (auto it = saved_apps.begin(); it != saved_apps.end(); ++it) {
```
Comment (SNiukalov) [inline src/components/application_manager/src/resumption/resumption_data_json.cc]: maybe range-based

File: src/components/application_manager/src/resumption/resumption_data_json.cc [hunk 45]
```diff
@@ -152,32 +160,38 @@ void ResumptionDataJson::IncrementIgnOffCount() {
...
-       it != GetSavedApplications().end();
-       ++it) {
-    if ((*it).isMember(strings::ign_off_count)) {
-      Json::Value& ign_off_count = (*it)[strings::ign_off_count];
+  Json::Value dictionary;
+  resumption::LastStateAccessor accessor = last_state_wrapper_->get_accessor();
+  dictionary = accessor.GetData().dictionary();
+  Json::Value& saved_apps = GetSavedApplications(dictionary);
+  for (auto json_app = saved_apps.begin(); json_app != saved_apps.end();
+       ++json_app) {
```
Comment (SNiukalov) [inline src/components/application_manager/src/resumption/resumption_data_json.cc]: maybe range-based

File: src/components/application_manager/src/resumption/resumption_data_json.cc [hunk 46]
```diff
@@ -152,32 +160,38 @@ void ResumptionDataJson::IncrementIgnOffCount() {
...
   using namespace app_mngr;
   LOG4CXX_AUTO_TRACE(logger_);
   sync_primitives::AutoLock autolock(resumption_lock_);
 
-  for (Json::Value::iterator it = GetSavedApplications().begin();
-       it != GetSavedApplications().end();
+  resumption::LastStateAccessor accessor = last_state_wrapper_->get_accessor();
+  Json::Value dictionary = accessor.GetData().dictionary();
+  Json::Value& saved_apps = GetSavedApplications(dictionary);
+  for (Json::Value::iterator it = saved_apps.begin(); it != saved_apps.end();
```
Comment (SNiukalov) [inline src/components/application_manager/src/resumption/resumption_data_json.cc]: maybe range-based

File: src/components/application_manager/src/resumption/resumption_data_json.cc [hunk 47]
```diff
@@ -336,20 +370,22 @@ ssize_t ResumptionDataJson::IsApplicationSaved(
...
+    const std::string& device_id,
+    Json::Value& dictionary) const {
   using namespace app_mngr;
   LOG4CXX_AUTO_TRACE(logger_);
   sync_primitives::AutoLock autolock(resumption_lock_);
-  for (Json::Value::iterator it = GetSavedApplications().begin();
-       it != GetSavedApplications().end();
+  Json::Value& saved_apps = GetSavedApplications(dictionary);
+  for (Json::Value::iterator it = saved_apps.begin(); it != saved_apps.end();
        ++it) {
```
Comment (SNiukalov) [inline src/components/application_manager/src/resumption/resumption_data_json.cc]: maybe range-based

File: src/components/application_manager/src/resumption/resumption_data_json.cc [hunk 48]
```diff
@@ -359,8 +395,10 @@ void ResumptionDataJson::GetDataForLoadResumeData(
   sync_primitives::AutoLock autolock(resumption_lock_);
   smart_objects::SmartObject so_array_data(smart_objects::SmartType_Array);
   int i = 0;
-  for (Json::Value::iterator it = GetSavedApplications().begin();
-       it != GetSavedApplications().end();
+  resumption::LastStateAccessor accessor = last_state_wrapper_->get_accessor();
+  Json::Value dictionary = accessor.GetData().dictionary();
+  Json::Value& saved_apps = GetSavedApplications(dictionary);
+  for (Json::Value::iterator it = saved_apps.begin(); it != saved_apps.end();
        ++it) {
```
Comment (SNiukalov) [inline src/components/application_manager/src/resumption/resumption_data_json.cc]: maybe range-based

Comment (YarikMamykin) [reply src/components/application_manager/src/resumption/resumption_data_json.cc]: @SNiukalov fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/f4e32226bda388a572a9edc282e74636a66ad925

File: src/components/application_manager/src/resumption/resumption_data_json.cc (hunk 47 above)
Comment (YarikMamykin) [reply src/components/application_manager/src/resumption/resumption_data_json.cc]: @SNiukalov fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/f4e32226bda388a572a9edc282e74636a66ad925

File: src/components/application_manager/src/resumption/resumption_data_json.cc (hunk 46 above)
Comment (YarikMamykin) [reply src/components/application_manager/src/resumption/resumption_data_json.cc]: @SNiukalov fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/f4e32226bda388a572a9edc282e74636a66ad925

File: src/components/application_manager/src/resumption/resumption_data_json.cc (hunk 45 above)
Comment (YarikMamykin) [reply src/components/application_manager/src/resumption/resumption_data_json.cc]: @SNiukalov fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/f4e32226bda388a572a9edc282e74636a66ad925

File: src/components/application_manager/src/resumption/resumption_data_json.cc (hunk 44 above)
Comment (YarikMamykin) [reply src/components/application_manager/src/resumption/resumption_data_json.cc]: @SNiukalov fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/f4e32226bda388a572a9edc282e74636a66ad925

File: src/components/application_manager/src/app_service_manager.cc (hunk 43 above)
Comment (YarikMamykin) [reply src/components/application_manager/src/app_service_manager.cc]: @SNiukalov fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/f4e32226bda388a572a9edc282e74636a66ad925

File: src/components/application_manager/src/app_launch/app_launch_data_json.cc (hunk 42 above)
Comment (YarikMamykin) [reply src/components/application_manager/src/app_launch/app_launch_data_json.cc]: @SNiukalov fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/f4e32226bda388a572a9edc282e74636a66ad925

File: src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h [hunk 49]
```diff
@@ -91,7 +91,8 @@ class AppLaunchDataJson : public AppLaunchDataImpl {
    * @return  pointer to json list object
    */
   Json::Value& GetApplicationListAndIndex(const ApplicationData& app_data,
-                                          int32_t& founded_index) const;
+                                          int32_t& found_index,
+                                          Json::Value& dictionary) const;
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h]: @YarikMamykin missing param description

File: src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h [hunk 50]
```diff
@@ -132,12 +126,12 @@ class AppLaunchDataJson : public AppLaunchDataImpl {
   /**
    * @return pointer to AppLaunch data block in Json file
    */
-  Json::Value& GetSavedApplicationDataList() const;
+  Json::Value& GetSavedApplicationDataList(Json::Value& dictionary) const;
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h]: @YarikMamykin missing param description

File: src/components/application_manager/include/application_manager/resumption/resumption_data_json.h [hunk 51]
```diff
@@ -216,13 +213,13 @@ class ResumptionDataJson : public ResumptionData {
...
    */
-  void SetSavedApplication(Json::Value& apps_json);
+  void SetSavedApplication(Json::Value& apps_json, Json::Value& dictionary);
 
   /**
    * @brief Setup IgnOff time to LastState
    * @param ign_off_time - igition off time
    */
-  void SetLastIgnOffTime(time_t ign_off_time);
+  void SetLastIgnOffTime(time_t ign_off_time, Json::Value& dictionary);
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/include/application_manager/resumption/resumption_data_json.h]: @YarikMamykin please provide description for all newly added params in this header

File: src/components/application_manager/src/app_launch/app_launch_data_json.cc [hunk 52]
```diff
@@ -187,15 +202,16 @@ std::vector<ApplicationDataPtr> AppLaunchDataJson::GetAppDataByDevMac(
       }
     }
   }
-
+  accessor.GetMutableData().set_dictionary(dictionary);
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/src/app_launch/app_launch_data_json.cc]: @YarikMamykin its a getter and I don't see that dictionary is modified in this function somehow. Why are you setting it?

File: src/components/application_manager/src/resumption/resumption_data_json.cc [hunk 53]
```diff
@@ -150,62 +157,69 @@ uint32_t ResumptionDataJson::GetHMIApplicationID(
...
       ign_off_count = 1;
     }
-    to_save.append(*it);
+    to_save.append(*json_app);
   }
-  SetSavedApplication(to_save);
-  SetLastIgnOffTime(time(NULL));
-  LOG4CXX_DEBUG(logger_, GetResumptionData().toStyledString());
+  SetSavedApplication(to_save, dictionary);
+  SetLastIgnOffTime(time(NULL), dictionary);
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/src/resumption/resumption_data_json.cc]: @YarikMamykin nullptr?

File: src/components/application_manager/test/commands/command_request_impl_test.cc [hunk 54]
```diff
@@ -53,6 +53,8 @@
 
 #include "application_manager/mock_app_service_manager.h"
 #include "resumption/last_state_impl.h"
+#include "resumption/last_state_wrapper.h"
+#include "resumption/last_state_wrapper_impl.h"
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/test/commands/command_request_impl_test.cc]: @YarikMamykin do you really need include both headers?

Comment (YarikMamykin) [reply src/components/application_manager/test/commands/command_request_impl_test.cc]: @AKalinich-Luxoft fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/3dcb90541c1ee0310a396d2564a95eba3e12237e

File: src/components/application_manager/src/resumption/resumption_data_json.cc (hunk 53 above)
Comment (YarikMamykin) [reply src/components/application_manager/src/resumption/resumption_data_json.cc]: @AKalinich-Luxoft fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/3dcb90541c1ee0310a396d2564a95eba3e12237e

File: src/components/application_manager/src/app_launch/app_launch_data_json.cc (hunk 52 above)
Comment (YarikMamykin) [reply src/components/application_manager/src/app_launch/app_launch_data_json.cc]: @AKalinich-Luxoft fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/3dcb90541c1ee0310a396d2564a95eba3e12237e

File: src/components/application_manager/include/application_manager/resumption/resumption_data_json.h (hunk 51 above)
Comment (YarikMamykin) [reply src/components/application_manager/include/application_manager/resumption/resumption_data_json.h]: @AKalinich-Luxoft fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/3dcb90541c1ee0310a396d2564a95eba3e12237e

File: src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h (hunk 50 above)
Comment (YarikMamykin) [reply src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h]: @AKalinich-Luxoft fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/3dcb90541c1ee0310a396d2564a95eba3e12237e

File: src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h (hunk 49 above)
Comment (YarikMamykin) [reply src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h]: @AKalinich-Luxoft fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/3dcb90541c1ee0310a396d2564a95eba3e12237e

File: src/components/application_manager/src/app_launch/app_launch_data_json.cc (hunk 52 above)
Comment (YarikMamykin) [reply src/components/application_manager/src/app_launch/app_launch_data_json.cc]: @AKalinich-Luxoft `GetSavedApplicationDataList` **(line: 185)** method modifies the Last State dictionary. Those changes should be saved.

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/test/commands/mobile/unsubscribe_vehicle_request_test.cc [hunk 55]
```diff
@@ -39,6 +39,8 @@
 #include "application_manager/mock_application_manager.h"
 #include "application_manager/mock_message_helper.h"
 #include "mobile/unsubscribe_vehicle_data_request.h"
+#include "resumption/last_state_wrapper.h"
+#include "resumption/last_state_wrapper_impl.h"
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/test/commands/mobile/unsubscribe_vehicle_request_test.cc]: @YarikMamykin WHy do we need both headers above?

File: src/components/application_manager/src/resumption/resumption_data_json.cc (hunk 45 above)
Comment (AByzhynar) [reply src/components/application_manager/src/resumption/resumption_data_json.cc]: @YarikMamykin i can't see it fixed

File: src/components/application_manager/src/resumption/resumption_data_json.cc [hunk 56]
```diff
@@ -238,11 +254,13 @@ bool ResumptionDataJson::RemoveApplicationFromSaved(
...
-  sync_primitives::AutoLock autolock(resumption_lock_);
+
   bool result = false;
   std::vector<Json::Value> temp;
-  for (Json::Value::iterator it = GetSavedApplications().begin();
-       it != GetSavedApplications().end();
+  resumption::LastStateAccessor accessor = last_state_wrapper_->get_accessor();
+  Json::Value dictionary = accessor.GetData().dictionary();
+  Json::Value& saved_apps = GetSavedApplications(dictionary);
+  for (Json::Value::iterator it = saved_apps.begin(); it != saved_apps.end();
```
Comment (AByzhynar) [inline src/components/application_manager/src/resumption/resumption_data_json.cc]: @YarikMamykin same as above

Comment (YarikMamykin) [reply src/components/application_manager/src/resumption/resumption_data_json.cc]: @AByzhynar fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/723596386f8f684930582be36f8ea2d1659bd7c1

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/test/commands/mobile/unsubscribe_vehicle_request_test.cc (hunk 55 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/test/commands/mobile/unsubscribe_vehicle_request_test.cc]: @AByzhynar fixed in https://github.com/smartdevicelink/sdl_core/pull/2626/commits/b1dca8ac899a638cf8878c402edcead1a66c1252

**Comment by YarikMamykin** [comment]
@theresalech this PR passed internal Luxoft review and ready for Livio team review. Please, take a look.

**Comment by theresalech** [comment]
@YarikMamykin thanks!  We will note this as a prioritized bug fix when planning the 6.1 Release.

File: src/components/transport_manager/src/bluetooth/bluetooth_transport_adapter.cc [hunk 57]
```diff
@@ -57,13 +57,13 @@ CREATE_LOGGERPTR_GLOBAL(logger_, "TransportManager")
 BluetoothTransportAdapter::~BluetoothTransportAdapter() {}
 
 BluetoothTransportAdapter::BluetoothTransportAdapter(
-    resumption::LastState& last_state, const TransportManagerSettings& settings)
-    : TransportAdapterImpl(
-          new BluetoothDeviceScanner(this, true, 0, settings.bluetooth_uuid()),
```
Comment (jacobkeeler) [inline src/components/transport_manager/src/bluetooth/bluetooth_transport_adapter.cc]: Why was this removed? `settings.bluetooth_uuid()`

File: src/components/transport_manager/test/transport_manager_default_test.cc [hunk 58]
```diff
@@ -145,18 +160,17 @@ TEST(TestTransportManagerDefault, Init_LastStateUsed) {
   EXPECT_CALL(transport_manager_settings,
               transport_manager_tcp_adapter_network_interface())
       .WillRepeatedly(ReturnRef(network_interface));
-  EXPECT_CALL(transport_manager_settings, bluetooth_uuid())
-      .WillRepeatedly(Return(kBTUUID.data()));
```
Comment (jacobkeeler) [inline src/components/transport_manager/test/transport_manager_default_test.cc]: Should not be removed

File: src/components/transport_manager/test/transport_adapter_test.cc [hunk 59]
```diff
@@ -945,15 +952,23 @@ TEST_F(TransportAdapterTest, AbortedConnectSuccess) {
...
 
   EXPECT_CALL(*dev_mock, Init()).WillOnce(Return(TransportAdapter::OK));
   EXPECT_CALL(*serverMock, Init()).WillOnce(Return(TransportAdapter::OK));
   EXPECT_CALL(transport_adapter, Restore()).WillOnce(Return(true));
   transport_adapter.Init();
 
+  EXPECT_CALL(*dev_mock, Init()).WillOnce(Return(TransportAdapter::OK));
+  EXPECT_CALL(*serverMock, Init()).WillOnce(Return(TransportAdapter::OK));
+  EXPECT_CALL(transport_adapter, Restore()).WillOnce(Return(true));
+  transport_adapter.Init();
```
Comment (jacobkeeler) [inline src/components/transport_manager/test/transport_adapter_test.cc]: Why is this init code here twice?

File: src/components/transport_manager/test/transport_adapter_test.cc [hunk 60]
```diff
@@ -1240,10 +1261,12 @@ TEST_F(TransportAdapterTest, StopDevice) {
 
 TEST_F(TransportAdapterTest, TransportConfigUpdated) {
   MockTransportAdapterImpl transport_adapter(
-      NULL, NULL, NULL, last_state_, transport_manager_settings);
+      NULL, NULL, NULL, last_state_wrapper_, transport_manager_settings);
   SetDefaultExpectations(transport_adapter);
   EXPECT_CALL(transport_adapter, Restore()).WillOnce(Return(true));
   transport_adapter.Init();
+  EXPECT_CALL(transport_adapter, Restore()).WillOnce(Return(true));
+  transport_adapter.Init();
```
Comment (jacobkeeler) [inline src/components/transport_manager/test/transport_adapter_test.cc]: Why is this init code here twice?

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/test/CMakeLists.txt [hunk 61]
```diff
@@ -53,6 +54,7 @@ file(GLOB SOURCES
   ${CMAKE_CURRENT_SOURCE_DIR}/vehicle_data_item_schema_test.cc
   ${COMPONENTS_DIR}/application_manager/src/message.cc
   ${COMPONENTS_DIR}/application_manager/src/event_engine/*
+  ${COMPONENTS_DIR}/resumption/src/last_state_wrapper_impl.cc
```
[the remark this answers is not in the document]
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/test/CMakeLists.txt]: @jacobkeeler According to the previous implementation of the LastState, the LastState entity has been used as the separate entity and the MockLastState has being used in the Unit tests as the separate entity too. But in the current implementation of the LastState is used with LastStateWrapper. So, MockLastState should be used with LastStateWrapper too.

File: src/components/application_manager/src/hmi_language_handler.cc [hunk 62]
```diff
@@ -81,8 +81,12 @@ void HMILanguageHandler::set_language_for(
   LOG4CXX_DEBUG(
       logger_,
       "Setting language " << language << " for interface " << interface);
-  Json::Value& dictionary = last_state_->get_dictionary();
-  dictionary[LanguagesKey][key] = language;
+  resumption::LastStateAccessor accessor = last_state_wrapper_->get_accessor();
+  Json::Value dictionary = accessor.GetData().dictionary();
+  if (dictionary.isMember(LanguagesKey)) {
```
[the remark this answers is not in the document]
Comment (IGapchuk) [reply src/components/application_manager/src/hmi_language_handler.cc]: @jacobkeeler Yes, you are right. Changed in 88aae2550069670287d04eb6fe86353862d01581

File: src/components/application_manager/src/resumption/resumption_data_db.cc [hunk 63]
```diff
@@ -368,7 +368,6 @@ uint32_t ResumptionDataDB::GetIgnOffTime() const {
 
 uint32_t ResumptionDataDB::GetGlobalIgnOnCounter() const {
   LOG4CXX_AUTO_TRACE(logger_);
-  sync_primitives::AutoLock autolock(resumption_lock_);
```
[the remark this answers is not in the document]
Comment (IGapchuk) [reply src/components/application_manager/src/resumption/resumption_data_db.cc]: @jacobkeeler Thank you. The lock has been removed by mistake with the lock in the ResumptionDataJson. Changed in 77f36e8a494a161d89e9392ab0fbb34b33d9cb31

File: src/components/include/utils/data_accessor.h [hunk 64]
```diff
@@ -56,10 +56,15 @@ class DataAccessor {
       --(*counter_);
     }
   }
+
   const T& GetData() const {
     return data_;
   }
 
+  T& GetMutableData() const {
+    return const_cast<T&>(data_);
```
[the remark this answers is not in the document]
Comment (IGapchuk) [reply src/components/include/utils/data_accessor.h]: @jacobkeeler Good point! It makes sense. The new entity MutableDataAccessor has been added. Please take a look at 5eb0286694afb2b451b5f99761bd0211403e54f7

File: src/components/transport_manager/src/bluetooth/bluetooth_transport_adapter.cc (hunk 57 above)
Comment (IGapchuk) [reply src/components/transport_manager/src/bluetooth/bluetooth_transport_adapter.cc]: @jacobkeeler Thank you. It seems mistake of the last rebase. Reverted in 94f5c6bae6135e79bfb949aac37a7fbb7baf91d9

File: src/components/transport_manager/test/transport_manager_default_test.cc (hunk 58 above)
Comment (IGapchuk) [reply src/components/transport_manager/test/transport_manager_default_test.cc]: @jacobkeeler Reverted in 90937393b007f9641c8e5ef9953d102e371ab773

File: src/components/transport_manager/test/transport_adapter_test.cc (hunk 59 above)
Comment (IGapchuk) [reply src/components/transport_manager/test/transport_adapter_test.cc]: @jacobkeeler Thank you. It is mistake of the last rebase. Removed in 5477ac1f48f21ba7a4312839e58907d64251d06a

File: src/components/transport_manager/test/transport_adapter_test.cc (hunk 60 above)
Comment (IGapchuk) [reply src/components/transport_manager/test/transport_adapter_test.cc]: @jacobkeeler Thank you. It is mistake of the last rebase. Removed in 5477ac1f48f21ba7a4312839e58907d64251d06a

**Comment by IGapchuk** [comment]
@jacobkeeler All comments have been processed. Please take a look at the new commits.

File: src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h [hunk 65]
```diff
@@ -53,7 +52,8 @@ class AppLaunchDataJson : public AppLaunchDataImpl {
    * @brief Constructor of AppLaunchDataJson object
    */
   AppLaunchDataJson(const AppLaunchSettings& settings,
-                    resumption::LastState& last_state);
+                    resumption::LastStateWrapperPtr last_state_wrapper);
```
Comment (jacobkeeler) [inline src/components/application_manager/include/application_manager/app_launch/app_launch_data_json.h]: re-add and deprecate old signature

File: src/components/application_manager/include/application_manager/hmi_capabilities_impl.h [hunk 66]
```diff
@@ -512,7 +508,7 @@ class HMICapabilitiesImpl : public HMICapabilities {
 
   const smart_objects::SmartObject* seat_location_capability() const OVERRIDE;
 
-  void Init(resumption::LastState* last_state) OVERRIDE;
+  void Init(resumption::LastStateWrapperPtr last_state_wrapper) OVERRIDE;
```
Comment (jacobkeeler) [inline src/components/application_manager/include/application_manager/hmi_capabilities_impl.h]: re-add and deprecate old signature

File: src/components/application_manager/include/application_manager/plugin_manager/rpc_plugin.h [hunk 67]
```diff
@@ -87,7 +83,7 @@ class RPCPlugin {
                     rpc_service::RPCService& rpc_service,
                     HMICapabilities& hmi_capabilities,
                     policy::PolicyHandlerInterface& policy_handler,
-                    resumption::LastState& last_state) = 0;
+                    resumption::LastStateWrapperPtr last_state) = 0;
```
Comment (jacobkeeler) [inline src/components/application_manager/include/application_manager/plugin_manager/rpc_plugin.h]: re-add and deprecate old signature

File: src/components/application_manager/include/application_manager/plugin_manager/rpc_plugin_manager_impl.h [hunk 68]
```diff
@@ -60,7 +57,7 @@ class RPCPluginManagerImpl : public RPCPluginManager {
                        rpc_service::RPCService& rpc_service,
                        HMICapabilities& hmi_capabilities,
                        policy::PolicyHandlerInterface& policy_handler,
-                       resumption::LastState& last_state);
+                       resumption::LastStateWrapperPtr last_state);
```
Comment (jacobkeeler) [inline src/components/application_manager/include/application_manager/plugin_manager/rpc_plugin_manager_impl.h]: re-add and deprecate old signature

File: src/components/application_manager/include/application_manager/resumption/resumption_data_json.h [hunk 69]
```diff
@@ -175,32 +181,32 @@ class ResumptionDataJson : public ResumptionData {
    */
   void Persist() OVERRIDE;
 
-  resumption::LastState& last_state() const {
```
Comment (jacobkeeler) [inline src/components/application_manager/include/application_manager/resumption/resumption_data_json.h]: deprecate, don't remove

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/include/app_service_rpc_plugin/app_service_rpc_plugin.h [hunk 70]
```diff
@@ -48,7 +47,7 @@ class AppServiceRpcPlugin : public plugins::RPCPlugin {
             app_mngr::rpc_service::RPCService& rpc_service,
             app_mngr::HMICapabilities& hmi_capabilities,
             policy::PolicyHandlerInterface& policy_handler,
-            resumption::LastState& last_state) OVERRIDE;
+            resumption::LastStateWrapperPtr last_state) OVERRIDE;
```
Comment (jacobkeeler) [inline src/components/application_manager/rpc_plugins/app_service_rpc_plugin/include/app_service_rpc_plugin/app_service_rpc_plugin.h]: re-add and deprecate old signature

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_consent_manager_impl.h [hunk 71]
```diff
@@ -46,7 +46,7 @@ namespace rc_rpc_plugin {
 class RCConsentManagerImpl : public RCConsentManager {
  public:
   RCConsentManagerImpl(
-      resumption::LastState& last_state,
+      resumption::LastStateWrapperPtr last_state,
```
Comment (jacobkeeler) [inline src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_consent_manager_impl.h]: re-add and deprecate old signature

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_rpc_plugin.h [hunk 72]
```diff
@@ -65,7 +61,7 @@ class RCRPCPlugin : public plugins::RPCPlugin {
             app_mngr::rpc_service::RPCService& rpc_service,
             app_mngr::HMICapabilities& hmi_capabilities,
             policy::PolicyHandlerInterface& policy_handler,
-            resumption::LastState& last_state) OVERRIDE;
+            resumption::LastStateWrapperPtr last_state) OVERRIDE;
```
Comment (jacobkeeler) [inline src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_rpc_plugin.h]: re-add and deprecate old signature

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/sdl_rpc_plugin.h [hunk 73]
```diff
@@ -48,7 +48,7 @@ class SDLRPCPlugin : public plugins::RPCPlugin {
             app_mngr::rpc_service::RPCService& rpc_service,
             app_mngr::HMICapabilities& hmi_capabilities,
             policy::PolicyHandlerInterface& policy_handler,
-            resumption::LastState& last_state) OVERRIDE;
+            resumption::LastStateWrapperPtr last_state) OVERRIDE;
```
Comment (jacobkeeler) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/sdl_rpc_plugin.h]: re-add and deprecate old signature

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h [hunk 74]
```diff
@@ -49,7 +49,7 @@ class VehicleInfoPlugin : public plugins::RPCPlugin {
             app_mngr::rpc_service::RPCService& rpc_service,
             app_mngr::HMICapabilities& hmi_capabilities,
             policy::PolicyHandlerInterface& policy_handler,
-            resumption::LastState& last_state) OVERRIDE;
+            resumption::LastStateWrapperPtr last_state) OVERRIDE;
```
Comment (jacobkeeler) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h]: re-add and deprecate old signature

File: src/components/resumption/src/last_state_impl.cc [hunk 75]
```diff
@@ -42,34 +42,39 @@ LastStateImpl::LastStateImpl(const std::string& app_storage_folder,
...
   DCHECK(file_system::CreateDirectoryRecursively(app_storage_folder_));
-  LOG4CXX_INFO(logger_,
-               "LastState::SaveStateToFileSystem " << app_info_storage_ << str);
+  LOG4CXX_INFO(
+      logger_,
+      "LastState::SaveToFileSystem " << app_info_storage_ << styled_string);
   DCHECK(file_system::Write(app_info_storage_, char_vector_pdata));
 }
 
-Json::Value& LastStateImpl::get_dictionary() {
```
Comment (jacobkeeler) [inline src/components/resumption/src/last_state_impl.cc]: deprecated method without definition

File: src/components/resumption/src/last_state_impl.cc [hunk 76]
```diff
@@ -42,34 +42,39 @@ LastStateImpl::LastStateImpl(const std::string& app_storage_folder,
...
   LOG4CXX_AUTO_TRACE(logger_);
 }
 
 LastStateImpl::~LastStateImpl() {
   LOG4CXX_AUTO_TRACE(logger_);
-  SaveStateToFileSystem();
+  SaveToFileSystem();
 }
 
-void LastStateImpl::SaveStateToFileSystem() {
```
Comment (jacobkeeler) [inline src/components/resumption/src/last_state_impl.cc]: deprecated method without definition

File: src/components/transport_manager/include/transport_manager/iap2_emulation/iap2_transport_adapter.h [hunk 77]
```diff
@@ -60,9 +60,13 @@ class IAP2BluetoothEmulationTransportAdapter : public TcpTransportAdapter {
    */
   IAP2BluetoothEmulationTransportAdapter(
       const uint16_t port,
-      resumption::LastState& last_state,
+      resumption::LastStateWrapperPtr last_state_wrapper,
       const TransportManagerSettings& settings);
 
+  IAP2BluetoothEmulationTransportAdapter(
```
Comment (jacobkeeler) [inline src/components/transport_manager/include/transport_manager/iap2_emulation/iap2_transport_adapter.h]:
```suggestion
  DEPRECATED IAP2BluetoothEmulationTransportAdapter(
```
?

File: src/components/transport_manager/include/transport_manager/tcp/tcp_transport_adapter.h [hunk 78]
```diff
@@ -49,9 +49,14 @@ class TcpTransportAdapter : public TransportAdapterImpl {
...
-                               resumption::LastState& last_state,
-                               const TransportManagerSettings& settings);
+  TcpTransportAdapter(uint16_t port,
+                      resumption::LastStateWrapperPtr last_state_wrapper,
+                      const TransportManagerSettings& settings);
+
+  DEPRECATED
+  TcpTransportAdapter(uint16_t port,
+                      resumption::LastState&,
+                      const TransportManagerSettings& settings) = delete;
```
Comment (jacobkeeler) [inline src/components/transport_manager/include/transport_manager/tcp/tcp_transport_adapter.h]: can't just do `= delete`, you need to define the function to work as it did before, otherwise this is a breaking change.

File: src/components/transport_manager/include/transport_manager/transport_manager_default.h [hunk 79]
```diff
@@ -56,7 +52,12 @@ class TransportManagerDefault : public TransportManagerImpl {
    *
    * @return Code error.
    */
-  int Init(resumption::LastState& last_state) OVERRIDE;
+  int Init(resumption::LastStateWrapperPtr last_state_wrapper) OVERRIDE;
+
+  DEPRECATED
+  int Init(resumption::LastState&) {
+    return 1;
```
Comment (jacobkeeler) [inline src/components/transport_manager/include/transport_manager/transport_manager_default.h]: needs to be defined properly, the function needs to work

File: src/components/include/application_manager/application_manager.h [hunk 80]
```diff
@@ -136,10 +131,16 @@ class ApplicationManager {
  public:
   virtual ~ApplicationManager() {}
 
+  DEPRECATED
+  virtual bool Init(resumption::LastState&,
+                    media_manager::MediaManager* media_manager) {
+    return false;
```
Comment (jacobkeeler) [inline src/components/include/application_manager/application_manager.h]: Needs a proper definition

File: src/components/include/application_manager/hmi_capabilities.h [hunk 81]
```diff
@@ -529,7 +526,10 @@ class HMICapabilities {
   virtual const smart_objects::SmartObject* seat_location_capability()
       const = 0;
 
-  virtual void Init(resumption::LastState* last_state) = 0;
+  DEPRECATED
+  virtual void Init(resumption::LastState&) {}
```
Comment (jacobkeeler) [inline src/components/include/application_manager/hmi_capabilities.h]: Need to properly write this function, empty body will not work properly

File: src/components/transport_manager/include/transport_manager/usb/usb_aoa_adapter.h [hunk 82]
```diff
@@ -44,8 +44,13 @@ namespace transport_adapter {
 
 class UsbAoaAdapter : public TransportAdapterImpl {
  public:
-  UsbAoaAdapter(resumption::LastState& last_state,
+  UsbAoaAdapter(resumption::LastStateWrapperPtr last_state_wrapper,
                 const TransportManagerSettings& settings);
+
+  DEPRECATED
+  UsbAoaAdapter(resumption::LastState&,
```
Comment (jacobkeeler) [inline src/components/transport_manager/include/transport_manager/usb/usb_aoa_adapter.h]: Include proper function definition

File: src/components/transport_manager/include/transport_manager/transport_manager_impl.h [hunk 83]
```diff
@@ -124,7 +124,12 @@ class TransportManagerImpl
    *
    * @return Code error.
    */
-  int Init(resumption::LastState& last_state) OVERRIDE;
+  int Init(resumption::LastStateWrapperPtr last_state_wrapper) OVERRIDE;
+
+  DEPRECATED
+  int Init(resumption::LastState&) {
+    return 1;
```
Comment (jacobkeeler) [inline src/components/transport_manager/include/transport_manager/transport_manager_impl.h]: Include proper function definition

File: src/components/transport_manager/include/transport_manager/transport_adapter/transport_adapter_impl.h [hunk 84]
```diff
@@ -82,9 +82,16 @@ class TransportAdapterImpl : public TransportAdapter,
...
-                       resumption::LastState& last_state,
+                       resumption::LastStateWrapperPtr last_state_wrapper,
                        const TransportManagerSettings& settings);
 
+  DEPRECATED
+  TransportAdapterImpl(DeviceScanner* device_scanner,
+                       ServerConnectionFactory* server_connection_factory,
+                       ClientConnectionListener* client_connection_listener,
+                       resumption::LastState& last_state_wrapper,
+                       const TransportManagerSettings& settings) = delete;
```
Comment (jacobkeeler) [inline src/components/transport_manager/include/transport_manager/transport_adapter/transport_adapter_impl.h]: Include proper function definition

**Comment by jacobkeeler** [comment]
@IGapchuk Pointed out a few missing deprecated definitions. Also, all deprecated functions must be defined in such a way that they still work as before, otherwise a breaking change is still made

File: src/components/application_manager/include/application_manager/resumption/resumption_data_json.h (hunk 69 above)
Comment (IGapchuk) [reply src/components/application_manager/include/application_manager/resumption/resumption_data_json.h]: @jacobkeeler Done in 051714ae2f3af31a9104199aa3c6f3e8937807a1

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/include/app_service_rpc_plugin/app_service_rpc_plugin.h (hunk 70 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/app_service_rpc_plugin/include/app_service_rpc_plugin/app_service_rpc_plugin.h]: @jacobkeeler Done in 4fdae6f97e8445b4aebe5269c4163e028115f508

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_consent_manager_impl.h (hunk 71 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_consent_manager_impl.h]: @jacobkeeler Done in 4fdae6f97e8445b4aebe5269c4163e028115f508

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_rpc_plugin.h (hunk 72 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_rpc_plugin.h]: @jacobkeeler Done in 4fdae6f97e8445b4aebe5269c4163e028115f508

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/sdl_rpc_plugin.h (hunk 73 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/sdl_rpc_plugin.h]: @jacobkeeler Done in 4fdae6f97e8445b4aebe5269c4163e028115f508

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h (hunk 74 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h]: @jacobkeeler Done in 4fdae6f97e8445b4aebe5269c4163e028115f508

File: src/components/application_manager/src/application_manager_impl.cc (hunk 18 above)
Comment (IGapchuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @jacobkeeler Done in 4fdae6f97e8445b4aebe5269c4163e028115f508

File: src/components/include/application_manager/application_manager.h (hunk 80 above)
Comment (IGapchuk) [reply src/components/include/application_manager/application_manager.h]: @jacobkeeler Done in 4fdae6f97e8445b4aebe5269c4163e028115f508

File: src/components/include/application_manager/hmi_capabilities.h (hunk 81 above)
Comment (IGapchuk) [reply src/components/include/application_manager/hmi_capabilities.h]: @jacobkeeler Done in 4fdae6f97e8445b4aebe5269c4163e028115f508

File: src/components/resumption/src/last_state_impl.cc (hunk 76 above)
Comment (IGapchuk) [reply src/components/resumption/src/last_state_impl.cc]: @jacobkeeler Done in 4fdae6f97e8445b4aebe5269c4163e028115f508

File: src/components/resumption/src/last_state_impl.cc (hunk 75 above)
Comment (IGapchuk) [reply src/components/resumption/src/last_state_impl.cc]: @jacobkeeler Done in 4fdae6f97e8445b4aebe5269c4163e028115f508

File: src/components/transport_manager/include/transport_manager/iap2_emulation/iap2_transport_adapter.h (hunk 77 above)
Comment (IGapchuk) [reply src/components/transport_manager/include/transport_manager/iap2_emulation/iap2_transport_adapter.h]: @jacobkeeler Done in 4fdae6f97e8445b4aebe5269c4163e028115f508

File: src/components/transport_manager/include/transport_manager/tcp/tcp_transport_adapter.h (hunk 78 above)
Comment (IGapchuk) [reply src/components/transport_manager/include/transport_manager/tcp/tcp_transport_adapter.h]: @jacobkeeler Done in 4fdae6f97e8445b4aebe5269c4163e028115f508

File: src/components/transport_manager/include/transport_manager/transport_adapter/transport_adapter_impl.h (hunk 84 above)
Comment (IGapchuk) [reply src/components/transport_manager/include/transport_manager/transport_adapter/transport_adapter_impl.h]: @jacobkeeler Done in 4fdae6f97e8445b4aebe5269c4163e028115f508

File: src/components/transport_manager/include/transport_manager/transport_manager_default.h (hunk 79 above)
Comment (IGapchuk) [reply src/components/transport_manager/include/transport_manager/transport_manager_default.h]: @jacobkeeler Done in 4fdae6f97e8445b4aebe5269c4163e028115f508

File: src/components/transport_manager/include/transport_manager/transport_manager_impl.h (hunk 83 above)
Comment (IGapchuk) [reply src/components/transport_manager/include/transport_manager/transport_manager_impl.h]: @jacobkeeler Done in 4fdae6f97e8445b4aebe5269c4163e028115f508

File: src/components/transport_manager/include/transport_manager/usb/usb_aoa_adapter.h (hunk 82 above)
Comment (IGapchuk) [reply src/components/transport_manager/include/transport_manager/usb/usb_aoa_adapter.h]: @jacobkeeler Done in 4fdae6f97e8445b4aebe5269c4163e028115f508

**Comment by IGapchuk** [comment]
@jacobkeeler All comments processed. Please take a look at 4fdae6f97e8445b4aebe5269c4163e028115f508 and 051714ae2f3af31a9104199aa3c6f3e8937807a1. We will run a regression testing with new changes.

File: src/components/resumption/src/last_state_impl.cc (hunk 75 above)
Comment (jacobkeeler) [reply src/components/resumption/src/last_state_impl.cc]: This comment was not resolved

File: src/components/resumption/src/last_state_impl.cc (hunk 76 above)
Comment (jacobkeeler) [reply src/components/resumption/src/last_state_impl.cc]: This comment was not resolved

File: src/components/transport_manager/include/transport_manager/tcp/tcp_transport_adapter.h (hunk 78 above)
Comment (jacobkeeler) [reply src/components/transport_manager/include/transport_manager/tcp/tcp_transport_adapter.h]: There is still no definition for this method

File: src/components/transport_manager/src/transport_manager_default.cc [hunk 85]
```diff
@@ -140,6 +140,10 @@ int TransportManagerDefault::Init(
   return E_SUCCESS;
 }
 
+int TransportManagerDefault::Init(resumption::LastState&) {
+  return 1;
```
Comment (jacobkeeler) [inline src/components/transport_manager/src/transport_manager_default.cc]:
```suggestion
  return Init(std::make_shared<LastStateWrapper>(last_state));
```

File: src/components/include/application_manager/hmi_capabilities.h (hunk 81 above)
Comment (jacobkeeler) [reply src/components/include/application_manager/hmi_capabilities.h]: Function body is still empty.

File: src/components/include/application_manager/application_manager.h (hunk 80 above)
Comment (jacobkeeler) [reply src/components/include/application_manager/application_manager.h]: Implementation remains unchanged

File: src/components/transport_manager/include/transport_manager/usb/usb_aoa_adapter.h (hunk 82 above)
Comment (jacobkeeler) [reply src/components/transport_manager/include/transport_manager/usb/usb_aoa_adapter.h]: Still no definition, see https://github.com/smartdevicelink/sdl_core/pull/2626#discussion_r372663000 for an example

File: src/components/transport_manager/include/transport_manager/transport_adapter/transport_adapter_impl.h (hunk 84 above)
Comment (jacobkeeler) [reply src/components/transport_manager/include/transport_manager/transport_adapter/transport_adapter_impl.h]: Still no definition, see https://github.com/smartdevicelink/sdl_core/pull/2626#discussion_r372663000 for an example

**Comment by jacobkeeler** [comment]
@IGapChuk responded to comments.

File: src/components/resumption/src/last_state_impl.cc (hunk 75 above)
Comment (IGapchuk) [reply src/components/resumption/src/last_state_impl.cc]: @jacobkeeler The method is marked as `DEPRECATED` and the definition has been added.

File: src/components/resumption/src/last_state_impl.cc (hunk 76 above)
Comment (IGapchuk) [reply src/components/resumption/src/last_state_impl.cc]: @jacobkeeler The method is marked as `DEPRECATED` and the definition has been added. Please, take a look at the 56361c87e7def67b2780721df021e4c7b98999ca

File: src/components/transport_manager/include/transport_manager/tcp/tcp_transport_adapter.h (hunk 78 above)
Comment (IGapchuk) [reply src/components/transport_manager/include/transport_manager/tcp/tcp_transport_adapter.h]: @jacobkeeler Unfortunately, we can't work with the previous implementation of  `TcpTransportAdapter` constructor, because the previous implementation has been taking in a reference to a `LastState` instance as a parameter and initializing the  `TransportAdapterImpl` parent class by this reference. But in the current implementation the `TransportAdapterImpl` in constructor takes in the `LastStateWrapperPtr` entity as parameter , that is a `std::shared_ptr<LastStateWrapper>`. Also, I believe that your solution https://github.com/smartdevicelink/sdl_core/pull/2626#discussion_r372663000 won't work properly. In this case, `LastStateWrapper` during deleting his own instance will free the memory allocated by the original object (the memory of the ingoing instance, that has provided the reference for `TcpTransportAdapter` ). As a result, when the original object will try to delete his own instance memory corruption will occur (core crash).

File: src/components/transport_manager/include/transport_manager/transport_manager_default.h (hunk 79 above)
Comment (IGapchuk) [reply src/components/transport_manager/include/transport_manager/transport_manager_default.h]: @jacobkeeler Please take a look https://github.com/smartdevicelink/sdl_core/pull/2626#discussion_r373481596

File: src/components/include/application_manager/application_manager.h (hunk 80 above)
Comment (IGapchuk) [reply src/components/include/application_manager/application_manager.h]: @jacobkeeler Please take a look https://github.com/smartdevicelink/sdl_core/pull/2626#discussion_r373481596

File: src/components/include/application_manager/hmi_capabilities.h (hunk 81 above)
Comment (IGapchuk) [reply src/components/include/application_manager/hmi_capabilities.h]: @jacobkeeler Please take a look https://github.com/smartdevicelink/sdl_core/pull/2626#discussion_r373481596

File: src/components/transport_manager/include/transport_manager/usb/usb_aoa_adapter.h (hunk 82 above)
Comment (IGapchuk) [reply src/components/transport_manager/include/transport_manager/usb/usb_aoa_adapter.h]: @jacobkeeler Please take a look https://github.com/smartdevicelink/sdl_core/pull/2626#discussion_r373481596

File: src/components/transport_manager/include/transport_manager/transport_adapter/transport_adapter_impl.h (hunk 84 above)
Comment (IGapchuk) [reply src/components/transport_manager/include/transport_manager/transport_adapter/transport_adapter_impl.h]: @jacobkeeler Please take a look https://github.com/smartdevicelink/sdl_core/pull/2626#discussion_r373481596

File: src/components/transport_manager/src/transport_manager_default.cc (hunk 85 above)
Comment (IGapchuk) [reply src/components/transport_manager/src/transport_manager_default.cc]: @jacobkeeler Please take a look https://github.com/smartdevicelink/sdl_core/pull/2626#discussion_r373481596

**Comment by IGapchuk** [comment]
@jacobkeeler All comments processed. Regression testing is completed successfully.

**Comment by jacobkeeler** [comment]
@IGapchuk Now merge conflicts must be resolved. Unfortunately they might be a bit complex since there were quite a few changes to the transport adapter in https://github.com/smartdevicelink/sdl_core/pull/3134

**Comment by jacobkeeler** [comment]
@IGapchuk We would appreciate if developers did not force push on sdl_core repository to a pr that is in review. It makes it difficult to review a PR because we cannot tell what was changed since the last review. In general, please do not rebase, and do not force push against sdl_core. Instead, you can merge the current develop branch into your PR branch. Thank you

**Comment by IGapchuk** [comment]
@jacobkeeler Please, let me explain my actions correctly. I didn't make a rebase onto the `develop` branch. I just made interactive rebase on the `fix branch` to squash all `--fixup` commits, because I believe that merging fix branch with `--fixup` commits is not a good idea (the history of commits will be in a non-readable state). I merged the `develop` branch into fix branch locally (I have one more commit `merge commit` over my commits), but I have several merge conflicts. I will resolve them and push the updates. Also, I going to start full regression on the fix branch. Thank you.

**Comment by jacobkeeler** [comment]
@IGapchuk I still maintain that force-pushing in any form has the possibility of invalidating my entire review up until this point, since I have no way of knowing for certain whether any other changes were made without reading through all of the code again. I understand the desire for a clean commit history, but force-pushing can force a full re-review of the PR, which puts it at risk for being included in the release. For this reason, I believe the best compromise in this case is to squash and merge to simplify the commit history. It's certainly not as powerful as having several, well-separated commits in a PR, but force-pushing in any way has too many risks associated with it in my experience.
