### PR TITLE
Fix/Invalid VR.AddCommand sent during CreateInteractionChoiceSet resumption

### LINKED ISSUE #3888: SDL requests invalid VR.AddCommand during CreateInteractionChoiceSet resumption without VR part
### Bug Report
SDL requests invalid `VR.AddCommand` during `CreateInteractionChoice` resumption without `VR` part

##### Precondition
1. SDL and HMI are started
2. Mobile app is registered and activated

##### Reproduction Steps
1. Mobile app requests `CreateInteractionChoiceSet` without `VR Command`
2. Perform transport reconnect  
5. Mobile app is registered with actual hash id

##### Expected Behavior
SDL does not request `VR.AddCommand` for  the `CreateInteractionChoiceSet` resumption without `VR Command` and resumes `CreateInteractionChoiceSet` internally

##### Observed Behavior
SDL request invalid `VR.AddCommand` message during resumption
```
SDL -> HMI [16:36:20:329]: {"id":96,"jsonrpc":"2.0","method":"VR.AddCommand","params":{"appID":856255661,"cmdID":4,"grammarID":0,"type":"Choice","vrCommands":null}}

VRRPC.js:295 FFW.VR.AddCommandResponse
RPCClient.js:323 HMI -> SDL [16:36:20:330]: {"jsonrpc":"2.0","id":96,"error":{"code":11,"message":"Parameter 'vrCommands' does not exists!","data":{"method":"VR.AddCommand"}}}
```

##### Note:
In case of deleting such `CreateInteractionChoiceSet`(without `VR` part) after it adding ( step 1 from ) SDL also requests invalid `VR.DeleteCommand`
```
{"id":70,"jsonrpc":"2.0","method":"VR.DeleteCommand","params":{"appID":1326361392,"cmdID":1,"grammarID":null,"type":"Choice"}}
```

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/8.1-RC1 ([25e47c7](https://github.com/smartdevicelink/sdl_core/commit/25e47c7f34f90f5393958f998c1861efa966d702))
* Testing Against: HMI: https://github.com/smartdevicelink/sdl_hmi/tree/release/5.7.0 ([cd2d250](https://github.com/smartdevicelink/sdl_hmi/commit/cd2d250cba100d1e0dd354172d2e24c0bd3449fc)), SyncProxyTester: 20210729-Android

##### Logs
[SmartDeviceLinkCore.zip](https://github.com/smartdevicelink/sdl_core/files/8333946/SmartDeviceLinkCore.zip)

### PR DESCRIPTION
**Pull request by ShobhitAd**
Fixes #3888 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
ATF tests PR submitted for issue

### Summary
Modified creation messages for AddCommand DeleteCommand requests
Added check of vr part in VRAddCommandRequest
Added check of grammar_id in VRDeleteCommandRequest
Added unit tests

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/message_helper/message_helper.cc [hunk 1]
```diff
@@ -1590,13 +1594,15 @@ MessageHelper::CreateAddVRCommandRequestFromChoiceToHMI(
...
-          (*(it->second))[strings::choice_set][j][strings::vr_commands];
       msg_params[strings::type] = hmi_apis::Common_VRCommandType::Choice;
       msg_params[strings::grammar_id] = choice_grammar_id;
-
+      msg_params[strings::cmd_id] =
+          (*(it->second))[strings::choice_set][j][strings::choice_id];
+      if ((*(it->second))[strings::choice_set][j].keyExists(
+              strings::vr_commands)) {
+        msg_params[strings::vr_commands] =
+            (*(it->second))[strings::choice_set][j][strings::vr_commands];
```
Comment (jacobkeeler) [inline src/components/application_manager/src/message_helper/message_helper.cc:1604]:
```suggestion
      if (!(*(it->second))[strings::choice_set][j].keyExists(
              strings::vr_commands)) {
        continue;
```
Seems like we should just skip over this request if it doesn't have any VR commands. Should reduce the logic in this PR quite a bit

File: src/components/application_manager/src/message_helper/message_helper.cc [hunk 2]
```diff
@@ -738,10 +738,13 @@ void MessageHelper::SendDeleteChoiceSetRequest(smart_objects::SmartObject* cmd,
...
 
   SmartObject msg_params = SmartObject(smart_objects::SmartType_Map);
-
   msg_params[strings::app_id] = application->app_id();
   msg_params[strings::type] = hmi_apis::Common_VRCommandType::Choice;
-  msg_params[strings::grammar_id] = (*cmd)[strings::grammar_id];
+
+  if (cmd->keyExists(strings::grammar_id) &&
+      (*cmd)[strings::grammar_id].asInt() != -1) {
+    msg_params[strings::grammar_id] = (*cmd)[strings::grammar_id];
```
Comment (jacobkeeler) [inline src/components/application_manager/src/message_helper/message_helper.cc:746]:
```suggestion
  if (!cmd->keyExists(strings::grammar_id) ||
      (*cmd)[strings::grammar_id].asInt() == -1) {
    return;
```
Same here, should just skip over it

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

**Comment by jacobkeeler** [comment]
Ah, another note is that we would need to skip the `VR.DeleteCommand` sending step in `delete_interaction_choice_set_request.cc` as part of this solution as well.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/vr_add_command_request.cc [hunk 3]
```diff
@@ -57,7 +57,19 @@ VRAddCommandRequest::~VRAddCommandRequest() {}
...
+    event_engine::Event event(hmi_apis::FunctionID::VR_AddCommand);
+
+    (*message_)[strings::params][strings::message_type] =
+        static_cast<int32_t>(application_manager::MessageType::kResponse);
+    (*message_)[strings::params][application_manager::hmi_response::code] =
+        static_cast<int32_t>(hmi_apis::Common_Result::SUCCESS);
+
+    event.set_smart_object(*message_);
+    event.raise(application_manager_.event_dispatcher());
+  }
```
Comment (jacobkeeler) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/vr_add_command_request.cc:72]: I would remove all of these other changes from the PR, we shouldn't encounter these cases with my suggested changes

File: src/components/application_manager/src/message_helper/message_helper.cc [hunk 4]
```diff
@@ -1590,12 +1597,16 @@ MessageHelper::CreateAddVRCommandRequestFromChoiceToHMI(
...
           smart_objects::SmartObject(smart_objects::SmartType_Map);
       msg_params[strings::app_id] = app->app_id();
+      msg_params[strings::type] = hmi_apis::Common_VRCommandType::Choice;
+      msg_params[strings::grammar_id] = choice_grammar_id;
       msg_params[strings::cmd_id] =
           (*(it->second))[strings::choice_set][j][strings::choice_id];
+      if (!(*(it->second))[strings::choice_set][j].keyExists(
+              strings::vr_commands)) {
+        continue;
+      }
```
Comment (jacobkeeler) [inline src/components/application_manager/src/message_helper/message_helper.cc:1607]: Might suggest moving this toward the top of the loop, for the sake of it.

File: src/components/application_manager/src/message_helper/message_helper.cc [hunk 5]
```diff
@@ -738,10 +738,16 @@ void MessageHelper::SendDeleteChoiceSetRequest(smart_objects::SmartObject* cmd,
...
 
   SmartObject msg_params = SmartObject(smart_objects::SmartType_Map);
-
   msg_params[strings::app_id] = application->app_id();
   msg_params[strings::type] = hmi_apis::Common_VRCommandType::Choice;
+
+  if (!cmd->keyExists(strings::grammar_id) ||
+      (*cmd)[strings::grammar_id].asInt() == -1) {
+    return;
+  }
```
Comment (jacobkeeler) [inline src/components/application_manager/src/message_helper/message_helper.cc:747]: Same here, probably wouldn't hurt to put this check toward the top of the function before we start constructing things

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

**Review by jacobkeeler — APPROVED** [review]
