### PR TITLE
Fix nonfunctional certificate/key path keywords

### LINKED ISSUE #2190: Cert processing invalid, CertificatePath and CACertificatePath keywords are nonfunctional
### Bug Report
The keywords CertificatePath and CACertificatePath in the smartDeviceLink.ini file are intended to allow the system integrator to specify both the preloaded CA certificates directory and the systems certificate file in pem file format.  With the implementation of the EXTERNAL_PROPRIETARY policy mode in release 4.3.0 the keywords have (mistakenly) become nonfunctional as SDL core is always looking for a certificate via the policy table now (even though the keywords still exist in the Security Manager section of the smartDeviceLink.ini file linked below).  Including the certificate in the policy table inside of the implementation of the EXTERNAL_PROPRIETARY policy mode was only intended to allow the core to periodically update its certificate on the file system -- the intent was not to remove the capability for an integrator to specify their root ca and initial module certificate.

https://github.com/smartdevicelink/sdl_core/blob/master/src/appMain/smartDeviceLink.ini#L158
https://github.com/smartdevicelink/sdl_core/blob/master/src/appMain/smartDeviceLink.ini#L168

##### Reproduction Steps
Clone any branch of sdl core with a release version of 4.3.0 or above.  Take note of the invalid certificate processing flow (core only utilizes and processes certificates from the policy table and does not allow the integrator to specify root ca and system certificates).  Also take note of the CertificatePath and CACertificatePath keywords as they are not utilized properly anymore.

##### Expected Behavior
SDL Core will use the CertificatePath and CACertificatePath keywords specified in the ini file allowing the system integrator to provide both a system side certificate and preloaded CA certificates where needed.  SDL Core will update the system side certificate via policy table update.

##### Observed Behavior
SDL Core ignores both the CertificatePath and CACertificatePath keywords that would allow the system integrator to specify certificates for their environment, instead SDL Core only processes the certificate provided via the policy table.

##### OS & Version Information
* OS/Version:  Ubuntu 16.04
* SDL Core Version: Release 4.5.1
* Testing Against: Tested with WebHMI and app built with 4.5.0 Android Proxy release

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #2190 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Will be tested on the integration branch
Unit tests

### Summary
Currently, SDL Core ignores both the `CertificatePath` and `KeyPath` keywords that would allow the system integrator to specify certificates for their environment, instead SDL Core only processes the certificate
provided via the policy table. This fix makes these keywords functional. 

**NOTE**
This fix is closely related to #2218 and should be merged **before** it.
This fix should be merged **after** features #2105 and #2068. 

### Changelog
Following changes were done:
- Added getters for `CertificatePath` and `KeyPath` parameters in `SecurityManagerSettings` class to provide another components access to these properties
- Added methods for loading certificate and private key data from the files specified by `CertificatePath` and `KeyPath` keywords
- `CryptoManager` component implementation was updated. Now this component also read certificate data from files (if they are present and accessible) on its own initialization

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/security_manager/src/crypto_manager_impl.cc [hunk 1]
```diff
@@ -235,7 +243,15 @@ bool CryptoManagerImpl::OnCertificateUpdated(const std::string& data) {
...
   }
 
-  return set_certificate(data);
+  if (!set_certificate(data)) {
+    LOG4CXX_ERROR(logger_, "Failed to save certificate data");
+    return false;
+  }
+
+  X509* module_certificate = LoadModuleCertificateFromFile();
+  EVP_PKEY* module_key = LoadModulePrivateKeyFromFile();
```
Comment (olohvinenko) [inline src/components/security_manager/src/crypto_manager_impl.cc]: Shouldn't we free allocated resources (X509 and EVP_PKEY)?

Comment (KVGrygoriev) [reply src/components/security_manager/src/crypto_manager_impl.cc]: +1 I see BIO_free, but didn't see X509_free & EVP_PKEY_free

File: src/components/security_manager/src/crypto_manager_impl.cc [hunk 2]
```diff
@@ -411,4 +427,81 @@ void CryptoManagerImpl::InitCertExpTime() {
...
+  LOG4CXX_DEBUG(logger_, "Certificate and key are successfully updated");
+  return true;
+}
+
+X509* CryptoManagerImpl::LoadModuleCertificateFromFile() {
+  LOG4CXX_AUTO_TRACE(logger_);
+
+  const std::string cert_path = get_settings().module_cert_path();
+  BIO* bio_cert = BIO_new_file(cert_path.c_str(), "r");
+  if (NULL == bio_cert) {
```
Comment (AByzhynar) [inline src/components/security_manager/src/crypto_manager_impl.cc]: @AKalinich-Luxoft `if(!bio_cert)`..

File: src/components/security_manager/src/crypto_manager_impl.cc [hunk 3]
```diff
@@ -411,4 +427,81 @@ void CryptoManagerImpl::InitCertExpTime() {
...
+    LOG4CXX_WARN(logger_,
+                 "Failed to open " << cert_path << " file: " << LastError());
+    return NULL;
+  }
+
+  utils::ScopeGuard bio_guard = utils::MakeGuard(BIO_free, bio_cert);
+  UNUSED(bio_guard);
+
+  X509* module_certificate = NULL;
+  if (0 == PEM_read_bio_X509(bio_cert, &module_certificate, NULL, NULL)) {
```
Comment (AByzhynar) [inline src/components/security_manager/src/crypto_manager_impl.cc]: @AKalinich-Luxoft `if(!PEM_read_bio_X509(...`

File: src/components/security_manager/src/crypto_manager_impl.cc [hunk 4]
```diff
@@ -411,4 +427,81 @@ void CryptoManagerImpl::InitCertExpTime() {
   strptime("1 Jan 1970 00:00:00", "%d %b %Y %H:%M:%S", &expiration_time_);
 }
 
+bool CryptoManagerImpl::UpdateModuleCertificateData(X509* certificate,
+                                                    EVP_PKEY* key) {
+  LOG4CXX_AUTO_TRACE(logger_);
+  if (NULL != certificate) {
```
Comment (AByzhynar) [inline src/components/security_manager/src/crypto_manager_impl.cc]: @AKalinich-Luxoft `if(certificate)`

File: src/components/security_manager/src/crypto_manager_impl.cc (hunk 1 above)
Comment (AByzhynar) [reply src/components/security_manager/src/crypto_manager_impl.cc]: @KVGrygoriev Maybe I am wrong but I thought that BIO_free cleans up it as well.

Comment (AKalinich-Luxoft) [reply src/components/security_manager/src/crypto_manager_impl.cc]: @olohvinenko @KVGrygoriev @AByzhynar 
Thank you guys, good point. I added scope guards for all allocated X509 and EVP_PKEY objects so the will be automatically released when guard will comes out of scope.
See 65a8cb2fce55a81ed184b172d4c9490ea00e1f3a

File: src/components/security_manager/src/crypto_manager_impl.cc (hunk 2 above)
Comment (AKalinich-Luxoft) [reply src/components/security_manager/src/crypto_manager_impl.cc]: @AByzhynar fixed in 65a8cb2fce55a81ed184b172d4c9490ea00e1f3a

File: src/components/security_manager/src/crypto_manager_impl.cc (hunk 3 above)
Comment (AKalinich-Luxoft) [reply src/components/security_manager/src/crypto_manager_impl.cc]: @AByzhynar fixed in 65a8cb2fce55a81ed184b172d4c9490ea00e1f3a

File: src/components/security_manager/src/crypto_manager_impl.cc (hunk 4 above)
Comment (AKalinich-Luxoft) [reply src/components/security_manager/src/crypto_manager_impl.cc]: @AByzhynar fixed in 65a8cb2fce55a81ed184b172d4c9490ea00e1f3a

**Comment by mrapitis** [comment]
@theresalech this PR is ready for review.

**Comment by JackLivio** [comment]
@AKalinich-Luxoft Can you please resolve merge conflicts now that #2105 & #2068 have been merged into develop?
