### PR TITLE
Fix deadlock in policy handler

### LINKED ISSUE #3179: CCB: Fix deadlock in PolicyHandler
### Bug Report
Deadlock in PolicyHandler 

### Detailed analysis:
A deadlock occurs due to wrong use of a policy_manager_lock_ mutex. dlclose call should be guaranteed after deleting the PolicyManager

##### Reproduction Steps
1. TBD

##### Expected Behavior
SDL should not crash

##### Observed Behavior
SDL crashed

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

### PR DESCRIPTION
**Pull request by IGapchuk**
Fixes #3179 

This PR is **not ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
This PR provides the next changes:
- the policy manager mutex is used in scope of the lambda function for creating policy manager instance;
- dlclose is called after deleting policy manager instance; 

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 1]
```diff
@@ -308,7 +295,8 @@ PolicyHandler::~PolicyHandler() {}
 
 PolicyEncryptionFlagGetterInterfaceSPtr
 PolicyHandler::PolicyEncryptionFlagGetter() const {
-  return policy_manager_;
+  DCHECK_OR_RETURN(atomic_policy_manager_, nullptr);
+  return atomic_policy_manager_;
```
Comment (LitvinenkoIra) [inline src/components/application_manager/src/policies/policy_handler.cc:299]: @IGapchuk I can see the duplicate of atomic_policy_manager_ getter here:https://github.com/smartdevicelink/sdl_core/pull/3497/files#diff-7ec0ea8e1e752c736fb05b5f89890fbfR774 (function LoadPolicyManager) 
Please leave only one getter

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 2]
```diff
@@ -1201,20 +1242,22 @@ bool PolicyHandler::ReceiveMessageFromSDK(const std::string& file,
...
+  auto policy_manager = LoadPolicyManager();
+  DCHECK_OR_RETURN(policy_manager, false);
+  SDL_LOG_DEBUG("policy_manager_ = " << policy_manager);
   bool ret = true;
   AsyncRunner::Stop();
   sync_primitives::AutoWriteLock lock(policy_manager_lock_);
-  if (policy_manager_) {
-    policy_manager_.reset();
+  if (policy_manager) {
+    policy_manager.reset();
```
Comment (SNiukalov) [inline src/components/application_manager/src/policies/policy_handler.cc:1260]: @IGapchuk 
Maybe ExchangePolicyManager(nullptr);

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 3]
```diff
@@ -1201,20 +1242,22 @@ bool PolicyHandler::ReceiveMessageFromSDK(const std::string& file,
...
+    policy_manager->OnPTUFinished(load_pt_result);
   }
 
   return is_ptu_successful;
 }
 
 bool PolicyHandler::UnloadPolicyLibrary() {
   SDL_LOG_AUTO_TRACE();
-  SDL_LOG_DEBUG("policy_manager_ = " << policy_manager_);
+  auto policy_manager = LoadPolicyManager();
```
Comment (SNiukalov) [inline src/components/application_manager/src/policies/policy_handler.cc:1253]: @IGapchuk 
It is rudiment

**Review by SNiukalov — CHANGES_REQUESTED** [review]

File: src/components/application_manager/include/application_manager/policies/policy_handler.h [hunk 4]
```diff
@@ -703,7 +703,7 @@ class PolicyHandler : public PolicyHandlerInterface,
 
 #ifdef BUILD_TESTS
   void SetPolicyManager(std::shared_ptr<PolicyManager> pm) {
-    policy_manager_ = pm;
+    ExchangePolicyManager(std::move(pm));
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/include/application_manager/policies/policy_handler.h:706]: Why move for shared ptr?

File: src/components/application_manager/include/application_manager/policies/policy_handler.h [hunk 5]
```diff
@@ -901,8 +901,31 @@ class PolicyHandler : public PolicyHandlerInterface,
...
+  std::shared_ptr<PolicyManager> LoadPolicyManager() const;
+
+  /**
+   * @brief Exchange a policy manager
+   * This method is thread safe
+   * @param policy_manager - new policy manager
+   * @return Pointer to the previous policy manager
+   * or null if the policy manager not set previously
+   */
+  std::shared_ptr<PolicyManager> ExchangePolicyManager(
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/include/application_manager/policies/policy_handler.h:918]: Looks like return value is redundant, isn't it?

**Review by LuxoftAKutsan — CHANGES_REQUESTED** [review]
Please add the root cause of the issue description.
Please also add fix description

**Review by SNiukalov — CHANGES_REQUESTED** [review]

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 6]
```diff
@@ -334,39 +333,45 @@ bool PolicyHandler::LoadPolicyLibrary() {
...
+    if (NULL == error_string) {
+      policy_manager = std::shared_ptr<PolicyManager>(
+          create_manager(&logger::Logger::instance()), policy_destroyer);
+    } else {
+      SDL_LOG_WARN(error_string);
+      dlclose(dl_policy_handle);
+      return std::shared_ptr<PolicyManager>();
+    }
 
     policy_manager->set_listener(this);
```
Comment (SNiukalov) [inline src/components/application_manager/src/policies/policy_handler.cc:376]: My suggestion:

    DeleteManager delete_manager = reinterpret_cast<DeleteManager>(
        dlsym(dl_policy_handle, "DeleteManager"));
    error_string = dlerror();
    if (NULL != error_string) {
      SDL_LOG_WARN(error_string);
      dlclose(dl_policy_handle);
      return std::shared_ptr<PolicyManager>();
    }

    auto policy_destroyer = [delete_manager,
                             dl_policy_handle](PolicyManager* policy_manager) {
      SDL_LOG_DEBUG("Delete Policy Manager");
      delete_manager(policy_manager);
      dlclose(dl_policy_handle);
    };

    std::shared_ptr<PolicyManager> policy_manager(
        create_manager(&logger::Logger::instance()), policy_destroyer);

    policy_manager->set_listener(this);

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 7]
```diff
@@ -317,55 +322,71 @@ bool PolicyHandler::PolicyEnabled() const {
...
   SDL_LOG_AUTO_TRACE();
-  sync_primitives::AutoWriteLock lock(policy_manager_lock_);
-  if (!PolicyEnabled()) {
-    SDL_LOG_WARN(
-        "System is configured to work without policy "
-        "functionality.");
-    policy_manager_.reset();
-    return false;
-  }
+  ExchangePolicyManager(nullptr);
```
Comment (LitvinenkoIra) [inline src/components/application_manager/src/policies/policy_handler.cc:325]: @IGapchuk shouldn't we check if Policy enabled or not before calling this?

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 8]
```diff
@@ -317,55 +322,71 @@ bool PolicyHandler::PolicyEnabled() const {
...
-  const char* error = dlerror();
-  if (!policy_handle) {
-    SDL_LOG_ERROR((error == NULL
-                       ? "Unknown error in dlopen while loading policy table"
-                       : error));
-    return false;
-  }
+    if (!dl_policy_handle) {
+      SDL_LOG_ERROR("An error occurs while calling dlopen");
+      return std::shared_ptr<PolicyManager>();
```
Comment (LitvinenkoIra) [inline src/components/application_manager/src/policies/policy_handler.cc:340]: @IGapchuk @SNiukalov Is this is a good approach to return shared_ptr as bool here? How do you think?

**Review by LitvinenkoIra — CHANGES_REQUESTED** [review]

**Review by YarikMamykin — APPROVED** [review]

File: src/components/application_manager/src/policies/policy_handler.cc (hunk 1 above)
Comment (IGapchuk) [reply src/components/application_manager/src/policies/policy_handler.cc]: @LitvinenkoIra The `LoadPolicyManager` method in the base changes in this PR and the `PolicyEncryptionFlagGetter` method is the interface method. So we decided to combine the approaches and call `LoadPolicyManager` inside the `PolicyEncryptionFlagGetter`.

File: src/components/application_manager/src/policies/policy_handler.cc (hunk 2 above)
Comment (IGapchuk) [reply src/components/application_manager/src/policies/policy_handler.cc]: @SNiukalov Please, take a look at the new changes in the `fixup` commits. The branch has was force pushed.

File: src/components/application_manager/src/policies/policy_handler.cc (hunk 3 above)
Comment (IGapchuk) [reply src/components/application_manager/src/policies/policy_handler.cc]: @SNiukalov Please, take a look at the new changes in the `fixup` commits. The branch has was force pushed.

File: src/components/application_manager/include/application_manager/policies/policy_handler.h (hunk 4 above)
Comment (IGapchuk) [reply src/components/application_manager/include/application_manager/policies/policy_handler.h]: @LuxoftAKutsan Changed

File: src/components/application_manager/include/application_manager/policies/policy_handler.h (hunk 5 above)
Comment (IGapchuk) [reply src/components/application_manager/include/application_manager/policies/policy_handler.h]: @LuxoftAKutsan Return value was removed

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 9]
```diff
@@ -317,55 +323,66 @@ bool PolicyHandler::PolicyEnabled() const {
...
+          if (delete_manager) {
+            delete_manager(pm);
+          }
+          dlclose(dl_handle);
+        }};
+
+    policy_manager->set_listener(this);
+
+    return policy_manager;
   };
```
[the remark this answers is not in the document]
Comment (IGapchuk) [reply src/components/application_manager/src/policies/policy_handler.cc:378]: @SNiukalov Changed

File: src/components/application_manager/src/policies/policy_handler.cc (hunk 8 above)
Comment (IGapchuk) [reply src/components/application_manager/src/policies/policy_handler.cc:339]: @LitvinenkoIra This place is the scope of the lambda function that returns the `std::shared_ptr<PolicyManager>`.

File: src/components/application_manager/src/policies/policy_handler.cc (hunk 7 above)
Comment (IGapchuk) [reply src/components/application_manager/src/policies/policy_handler.cc]: @LitvinenkoIra Replaced in the b2c140b69b9b991bb55f761ffb848301cf014c26

**Review by LitvinenkoIra — APPROVED** [review]

**Review by SNiukalov — APPROVED** [review]

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 10]
```diff
@@ -322,7 +322,6 @@ bool PolicyHandler::PolicyEnabled() const {
 
 bool PolicyHandler::LoadPolicyLibrary() {
   SDL_LOG_AUTO_TRACE();
-  ExchangePolicyManager(nullptr);
```
Comment (SNiukalov) [inline src/components/application_manager/src/policies/policy_handler.cc]: @IGapchuk 
Why you need to remove it, I believe we can leave it in this

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 11]
```diff
@@ -794,10 +835,23 @@ void PolicyHandler::GetRegisteredLinks(
...
 
+std::shared_ptr<PolicyManager> PolicyHandler::LoadPolicyManager() const {
+  sync_primitives::AutoReadLock lock{policy_manager_lock_};
+  return atomic_policy_manager_;
+}
+
+void PolicyHandler::ExchangePolicyManager(
+    std::shared_ptr<PolicyManager> policy_manager) {
+  sync_primitives::AutoWriteLock lock{policy_manager_lock_};
+  std::swap(atomic_policy_manager_, policy_manager);
```
[the remark this answers is not in the document]
Comment (IGapchuk) [reply src/components/application_manager/src/policies/policy_handler.cc]: @SNiukalov Changed in 43aa7dd0a9f841a6ebfe08021d7e8dcff674821e

File: src/components/application_manager/src/policies/policy_handler.cc (hunk 10 above)
Comment (IGapchuk) [reply src/components/application_manager/src/policies/policy_handler.cc]: @SNiukalov Was moved after `PolicyEnabled` check. Please take a look at 43aa7dd0a9f841a6ebfe08021d7e8dcff674821e

**Review by SNiukalov — APPROVED** [review]

**Review by SNiukalov — APPROVED** [review]

**Review by LitvinenkoIra — APPROVED** [review]

**Comment by IGapchuk** [comment]
@theresalech Please be informed, the internal review of the PR is completed and the PR is ready for the Livio team review. Thank you!

**Review by LuxoftAKutsan — APPROVED** [review]

**Review by ShobhitAd — APPROVED** [review]
