### PR TITLE
Fix SIGKILL due to not clearing the requestinfo set.

### LINKED ISSUE #3169: CCB: Fix SIGKILL due to not clearing the requestinfo set
### Bug Report
SignalKill in SDL

### Detailed analysis:
time_sorted_pending_requests_ set containing the RequestInfoPtr is getting released twice.

##### Reproduction Steps
1. Register CitySeeker App.
2. Launch the App.
3. Do a proper Ignition Off / Ignition On.
4. Try the above steps more than one time if it is not reproducible.

##### Expected Behavior
No crash

##### Observed Behavior
SDL crashed
[bt.txt](https://github.com/smartdevicelink/sdl_core/files/3932159/bt.txt)

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

### PR DESCRIPTION
**Pull request by LuxoftAKutsan**
Fixes #3169

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Tested on SYNC SDL. 
For open sdl will be created test script

### Summary
Adopted fix from SYNC sdl

### Tasks Remaining:
- [ ] Luxoft internal review 

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/request_info.cc [hunk 1]
```diff
@@ -116,6 +116,15 @@ FakeRequestInfo::FakeRequestInfo(uint32_t app_id, uint32_t correaltion_id) {
   correlation_id_ = correaltion_id;
 }
 
+RequestInfoSet::~RequestInfoSet() {
+  sync_primitives::AutoLock lock(pending_requests_lock_);
+  auto it = time_sorted_pending_requests_.begin();
+  while (!time_sorted_pending_requests_.empty()) {
+    RemoveRequest(*it);
```
Comment (jacobkeeler) [inline src/components/application_manager/src/request_info.cc:123]: seems this would cause a double `Acquire` for `pending_requests_lock_` since it isn't recursive

Comment (jacobkeeler) [reply src/components/application_manager/src/request_info.cc:123]:
```suggestion
    Erase(*it);
```
Seems this would fix the issue

**Comment by theresalech** [comment]
@LuxoftAKutsan, can you please let us know when this is ready for re-review?

**Comment by LuxoftAKutsan** [comment]
@theresalech this work is planned. We will notify when fix with test scripts will be available.

**Comment by IGapchuk** [comment]
Hi, @jacobkeeler. Please take a look at the new one commit 9f781124a2dd2713c82b52322906ea89c3cd6c4d with changes according to your comment https://github.com/smartdevicelink/sdl_core/pull/3376#discussion_r444440238. Also please pay attention that we have back-merged the develop branch into the fix branch - 35df43395f4a3690ea4d7eb0c8c6fa5791c95ddd. We would like to ask you to suspend the fix merge until we check full regression on the fix branch. Thank you!

**Comment by jacobkeeler** [comment]
@IGapchuk seems the CI is passing on our end, can you confirm if the full regression has passed on your end?

**Comment by dboltovskyi** [comment]
@jacobkeeler Please notice full regression is passed on our end
