### PR TITLE
Fix/usb handler thread safe stop

### LINKED ISSUE #3184: CCB: wait for UsbHandler thread end in UsbHandler dtor
### Bug Report
Data races related to UsbHandler

### Detailed analysis:
The Thread dedicated to handling libusb events should exit successfully on it's own. This guarantees that libusb_close() being called on all devices, as well as libusb_exit() call is properly sequenced.
Thread exits in recommended by libusb doc way:
  1. set exit flag
  2. deregister hotplug callbacks, which will wake up
     libusb_handle_events() once again.

The way the Thread being joined should be changed. It should ensure that join() is called with kNoStop flag, which prevents force stop using pthread_cancel().

##### Reproduction Steps
1. TBD

##### Expected Behavior
SDL should not crash

##### Observed Behavior
SDL crashed

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #3184 and #3188 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Covered by unit tests

### Summary
- Wait for UsbHandler thread end in UsbHandler dtor 
- Using atomic bool for `shutdown_requested_` flag

### Tasks Remaining:
- [ ] Test this fix

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by SNiukalov — APPROVED** [review]

File: src/components/transport_manager/src/usb/libusb/usb_handler.cc [hunk 1]
```diff
@@ -89,8 +89,27 @@ UsbHandler::UsbHandler()
...
+  DeregisterHotplugCallbacks();
+
+  // Now it is safe to join the Thread and free up resources
+  JoinAndDeleteThread();
+  InvokeLibusbExit();
+}
+
+void UsbHandler::RequestStopThread() {
+  SDL_LOG_AUTO_TRACE();
+  shutdown_requested_.exchange(true);
```
Comment (YarikMamykin) [inline src/components/transport_manager/src/usb/libusb/usb_handler.cc:108]: Oh no, here we go again :)) 
Why `exchange` instead of `store`?

**Review by YarikMamykin — CHANGES_REQUESTED** [review]

File: src/components/transport_manager/src/usb/libusb/usb_handler.cc (hunk 1 above)
Comment (AKalinich-Luxoft) [reply src/components/transport_manager/src/usb/libusb/usb_handler.cc]: @YarikMamykin its a secret code to confuse enemies. Fixed in https://github.com/smartdevicelink/sdl_core/pull/3492/commits/51c490c263a9eebb67b0a4caa4a701b8fcd22787

**Review by LuxoftAKutsan — APPROVED** [review]

**Review by YarikMamykin — APPROVED** [review]

**Review by ShobhitAd — APPROVED** [review]
