### PR TITLE
Remove dependency between optional params in OnRemoteControlSettings

### LINKED ISSUE #2845: SDL ignores accessMode if allowed parameter does not exist in OnRemoteControlSettings
### Bug Report
The parameters of HMI function `OnRemoteControlSettings` are defined as optional in HMI_API.xml. That means HMI can send a  `OnRemoteControlSettings`  notification with
- only `allowed` parameter 
- or only `accessMode` parameter 
- or both parameters. 

When SDL receives such notifications, it shall update its internal value and use the new value when needed.

However, the current SDL behavior (please see [RCOnRemoteControlSettingsNotification::Run](https://github.com/smartdevicelink/sdl_core/blob/d36316738785c96dab2ee892762ed08c059fffde/src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/commands/hmi/rc_on_remote_control_settings_notification.cc#95)) is to ignore the `accessMode` parameter if `allowed` parameter does not exist or `allowed=false` in the notification.
That means `allowed` is mandatory and HMI shall always include  `allowed` parameter.

Suggest to update the [hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/blob/master/docs/RC/OnRemoteControlSettings/index.md) to have a clause that HMI shall 
always include  `allowed` parameter  if we do not change sdl core.

A better solution is to  decouple the dependency of two parameters and update the sdl logic to make the parameters truly optional .
SDL shall do the flowing

if `accessMode` parameter exist {
    SetAccessMode(access_mode);
}
if `allowed` parameter exist {
   if `allowed`=true {
         set_rc_enabled(true);
    } else {
        DisallowRCFunctionality();
        ResetAllAllocations();
        set_rc_enabled(false);
  }
}

##### Reproduction Steps
From HMI send a `OnRemoteControlSettings`  notification with only `accessMode` parameter.

##### Expected Behavior
SDL update its internal value of `accessMode`.

##### Observed Behavior
SDL does not update its internal value of `accessMode`.

##### OS & Version Information

* SDL Core Version: 5.0
* Testing Against: HMI

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #2845

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

##### Reproduction Steps
From HMI send a `OnRemoteControlSettings`  notification with only `accessMode` parameter.

##### Expected Behavior
SDL update its internal value of `accessMode`.

##### Observed Behavior
SDL does not update its internal value of `accessMode`.

### Summary
The current SDL behavior (please see [RCOnRemoteControlSettingsNotification::Run](https://github.com/smartdevicelink/sdl_core/blob/d36316738785c96dab2ee892762ed08c059fffde/src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/commands/hmi/rc_on_remote_control_settings_notification.cc#95)) is to ignore the `accessMode` parameter if `allowed` parameter does not exist or `allowed=false` in the notification.
That means `allowed` is mandatory and HMI shall always include  `allowed` parameter, however it may be optional according to API.
The proposed solution removes the dependency between `accessMode` and `allowed` parameters.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by AKalinich-Luxoft** [comment]
@theresalech this PR is ready for Livio review

**Comment by theresalech** [comment]
@AKalinich-Luxoft , thank you! We will include this in the upcoming release if time allows.

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/commands/hmi/rc_on_remote_control_settings_notification.cc [hunk 1]
```diff
@@ -87,35 +87,34 @@ void RCOnRemoteControlSettingsNotification::DisallowRCFunctionality() {
 void RCOnRemoteControlSettingsNotification::Run() {
   SDL_LOG_AUTO_TRACE();
 
-  if (!(*message_)[app_mngr::strings::msg_params].keyExists(
-          message_params::kAllowed)) {
+  if ((*message_)[app_mngr::strings::msg_params].empty()) {
     SDL_LOG_DEBUG("Notification is ignored due to \"allow\" parameter absense");
```
Comment (ShobhitAd) [inline src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/commands/hmi/rc_on_remote_control_settings_notification.cc:91]:
```suggestion
    SDL_LOG_DEBUG("Notification is ignored due to absence of any parameters");
```
Since both parameters are non-mandatory

**Review by ShobhitAd — CHANGES_REQUESTED** [review]
Requesting a minor change

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/commands/hmi/rc_on_remote_control_settings_notification.cc (hunk 1 above)
Comment (AKalinich-Luxoft) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/commands/hmi/rc_on_remote_control_settings_notification.cc]: @ShobhitAd fixed in https://github.com/smartdevicelink/sdl_core/pull/3749/commits/57c6318e145a7ec01f9adc9d28b5549d45d1fa1a

**Review by ShobhitAd — APPROVED** [review]
