### PR TITLE
Fix result code generic error while subscribing to vehicle data

### LINKED ISSUE #3196: SDL responds "resultCode: GENERIC_ERROR" while dataType:VEHICLEDATA_EXTERNTEMP is VEHICLE_DATA_NOT_AVAILABLE and not in subscribed list store
## Occurrence
Always

## Preconditions
1. Core and HMI are started.
2. SubscribeVehicleData (speed, externalTemperature), OnVehicleData is allowed by policy for app_1 and app_2.
3. Navi App1 and navi app2 are registered and activated.

## Steps to reproduce
1. Send SubscribeVehicleData (speed, externalTemperature) from app_1
=> SDL responds SubscribeVehicleData ((speed:success),(externalTemperature:VEHICLE_DATA_NOT_AVAILABLE), SUCCESS).
2. Send SubscribeVehicleData (speed, externalTemperature) from app_2.

## Actual result
SDL sends "resultCode: GENERIC_ERROR, success:false" to mobile app1 and app2.

## Expected result
SDL should send "SUCCESS, (speed: SUCCESS),
(externalTemperature: VEHICLE_DATA_NOT_AVAILABLE)" to mobile app1 and app2.

# Environment
SDL repo: https://github.com/smartdevicelink/sdl_core
SDL branch: develop
SDL commit: e137556
OS: Ubuntu 16.04 LTS

### PR DESCRIPTION
**Pull request by ychernysheva**
Fixes #3196

This PR is **[ready]** for review.

### Risk
This PR makes **[no]** API changes.

### Testing Plan
Covered within existing unit tests and ATF tests.

### Summary
This pull request is intended to fix issue with sending "resultCode: GENERIC_ERROR" from SDL to mobile, if some parameters of VehicleData have valid (existing in API) result codes, which are different from SUCCESS or DATA_ALREADY_SUBSCRIBED. Due to this fix SDL can process all valid result codes without generating generic error, which will be present only in case, if result code of particular parameter is absent in API.

## CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by ychernysheva** [comment]
Full regression was passed successfully on commit b0868c0a2de0d2210e7a8a7aa9e94f702fc5d01c

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/subscribe_vehicle_data_request.cc [hunk 1]
```diff
@@ -201,20 +201,39 @@ bool SubscribeVehicleDataRequest::CheckSubscriptionStatus(
...
+  std::set<hmi_apis::Common_VehicleDataResultCode::eType> skiped_result_codes(
+      {hmi_apis::Common_VehicleDataResultCode::VDRC_TRUNCATED_DATA,
+       hmi_apis::Common_VehicleDataResultCode::VDRC_DISALLOWED,
+       hmi_apis::Common_VehicleDataResultCode::VDRC_USER_DISALLOWED,
+       hmi_apis::Common_VehicleDataResultCode::VDRC_INVALID_ID,
+       hmi_apis::Common_VehicleDataResultCode::VDRC_DATA_NOT_AVAILABLE,
+       hmi_apis::Common_VehicleDataResultCode::VDRC_DATA_NOT_SUBSCRIBED,
+       hmi_apis::Common_VehicleDataResultCode::VDRC_IGNORED});
+
+  for (auto vi_name = vi_waiting_for_subscribe_.begin();
```
Comment (YarikMamykin) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/subscribe_vehicle_data_request.cc:216]: Can we replace this cycle with foreach like:
`for(auto& vi_name : vi_waiting_for_subscribe_) `?

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/subscribe_vehicle_data_request.cc [hunk 2]
```diff
@@ -201,20 +201,39 @@ bool SubscribeVehicleDataRequest::CheckSubscriptionStatus(
...
     const bool is_subscription_successful = CheckSubscriptionStatus(
-        ConvertRequestToResponseName(vi_name), msg_params);
+        ConvertRequestToResponseName(*vi_name), msg_params);
 
     if (is_subscription_successful) {
       auto& ext = VehicleInfoAppExtension::ExtractVIExtension(*app);
-      ext.subscribeToVehicleInfo(vi_name);
-      vi_waiting_for_subscribe_.erase(vi_name);
+      ext.subscribeToVehicleInfo(*vi_name);
+      vi_name = vi_waiting_for_subscribe_.erase(vi_name);
```
Comment (YarikMamykin) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/subscribe_vehicle_data_request.cc:224]: In case of foreach loop you can get rid off saving next to erased item iterator.

**Comment by YarikMamykin** [comment]
@ychernysheva by the way are there any UT planned?

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/subscribe_vehicle_data_request.cc [hunk 3]
```diff
@@ -201,20 +201,39 @@ bool SubscribeVehicleDataRequest::CheckSubscriptionStatus(
...
+       hmi_apis::Common_VehicleDataResultCode::VDRC_DISALLOWED,
+       hmi_apis::Common_VehicleDataResultCode::VDRC_USER_DISALLOWED,
+       hmi_apis::Common_VehicleDataResultCode::VDRC_INVALID_ID,
+       hmi_apis::Common_VehicleDataResultCode::VDRC_DATA_NOT_AVAILABLE,
+       hmi_apis::Common_VehicleDataResultCode::VDRC_DATA_NOT_SUBSCRIBED,
+       hmi_apis::Common_VehicleDataResultCode::VDRC_IGNORED});
+
+  for (auto vi_name = vi_waiting_for_subscribe_.begin();
+       vi_name != vi_waiting_for_subscribe_.end();) {
     const bool is_subscription_successful = CheckSubscriptionStatus(
```
Comment (mkorniichuk) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/subscribe_vehicle_data_request.cc:218]: @ychernysheva according to naming, `CheckSubscriptionStatus` function will get the res_code of specific vehicle_info. And if it should be skipped, you will do the same afterward. How about moving the skipping check of vehicle info to this function?

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/subscribe_vehicle_data_request.cc [hunk 4]
```diff
@@ -201,20 +201,39 @@ bool SubscribeVehicleDataRequest::CheckSubscriptionStatus(
 }
 
 bool SubscribeVehicleDataRequest::SubscribePendingVehicleData(
-    ApplicationSharedPtr app, const smart_objects::SmartObject& msg_params) {
+    ApplicationSharedPtr app, smart_objects::SmartObject& msg_params) {
   LOG4CXX_DEBUG(logger_, "Subscribing to all pending VehicleData");
 
-  for (const auto& vi_name : vi_waiting_for_subscribe_) {
+  std::set<hmi_apis::Common_VehicleDataResultCode::eType> skiped_result_codes(
```
Comment (YarikMamykin) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/subscribe_vehicle_data_request.cc:207]: Maybe it is good place for `using hmi_apis::Common_VehicleDataResultCode = VD_ResultCode`

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/subscribe_vehicle_data_request.cc (hunk 1 above)
Comment (ychernysheva) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/subscribe_vehicle_data_request.cc:216]: I think, no, because it may cause strange behavior, and if we will use range-based for, sometimes it may work good, and sometimes not. Instead, proposed way of iterating is safe, because in this case we don't need to bother about correct order of iterators after possible call of erase(). This approach is common for cases with possible erasing from associative containers like set.

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/subscribe_vehicle_data_request.cc (hunk 2 above)
Comment (ychernysheva) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/subscribe_vehicle_data_request.cc:224]: In this case we need this iterator to guarantee correct order of elements in container during iteration with possible erasing.

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/subscribe_vehicle_data_request.cc (hunk 3 above)
Comment (ychernysheva) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/subscribe_vehicle_data_request.cc:218]: @mkorniichuk I think, that in this case is easier to check for subscription repeatedly with minor changes to base logic. If I move this part to CheckSubscriptionStatus, I'll still need to add some check in SubscribePendingVehicleData to separate skiped result codes from invalid result codes, in other case it can affect logic of generation generic error message, and this issue became more complicated.

**Comment by ychernysheva** [comment]
@YarikMamykin Unfortunately, I cannot add unit tests, because this component is uncovered by unit tests at all at this moment.

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/subscribe_vehicle_data_request.cc (hunk 4 above)
Comment (ychernysheva) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/subscribe_vehicle_data_request.cc:208]: Done in commit 664d9086492f57c7307e13597b7979113f0a4ada

**Comment by ychernysheva** [comment]
Commits were force-pushed due to rebase on branch release/6.1.0

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/subscribe_vehicle_data_request.cc (hunk 3 above)
Comment (mkorniichuk) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/subscribe_vehicle_data_request.cc:220]: @ychernysheva now result code will be checked inside CheckSubscriptionStatus and then further once more. This leads to code duplications and complications in further bugfix, from my perspective. I still would suggest move this logic to `CheckSubscriptionStatus` and make some enum as a result, or remove `CheckSubscriptionStatus` at all. But it is up to you.

**Comment by ychernysheva** [comment]
@theresalech this PR is ready for review. Thank you

**Comment by theresalech** [comment]
@ychernysheva please advise if this is a regression issue introduced by Core 6.1, or if it is an issue that already exists in SDL Core.  Thank you!

**Comment by ychernysheva** [comment]
@theresalech This is a fix for the issue that already exists in SDL Core, and this defect is in the scope of release 6.1.

**Comment by dboltovskyi** [comment]
@theresalech Please notice this is not a regression issue, so please include it into release if time allows. Thank you.

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/subscribe_vehicle_data_request.cc [hunk 5]
```diff
@@ -32,10 +32,13 @@
 #include <boost/algorithm/string.hpp>
 #include "application_manager/application_impl.h"
 #include "application_manager/message_helper.h"
+#include "interfaces/HMI_API.h"
```
[the remark this answers is not in the document]
Comment (ychernysheva) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/subscribe_vehicle_data_request.cc]: Thank you for note, this include is removed in commit 7a0bc3e121b95dfc9d5481c8a106c09dd439c4d1. Just kindly reminder, that there is two fixup commits, and squashing may be needed.
