### PR TITLE
Fix UpdateAppList/UpdateDeviceList spam

### LINKED ISSUE #3326: SDL sends redundant BC.UpdateAppList and BC.UpdateDeviceList requests in case BT is turned on from SDL start
### Bug Report
SDL sends redundant UpdateAppList requests in case BT is turned on from SDL start

##### Reproduction Steps
1. BT module is turned on
2. HMI and SDL are started

##### Expected Behavior
SDL sends BC.UpdateDeviceList in case of app registration of unregistration.
So after system start there are no BC.UpdateDeviceList requests.
BC.UpdateDeviceList is sent only with WebEngine device(in case SDL is build with WE ON )

##### Observed Behavior
SDL sends cyclically BC.UpdateDeviceList and BC.UpdateDeviceList requests in ~ 2seconds and then in ~40 seconds.

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: 74d24927cf77282c44678eba219adadbb6dcd072
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

##### Logs
[SmartDeviceLinkCore_update_devicelist_applist.zip](https://github.com/smartdevicelink/sdl_core/files/4450504/SmartDeviceLinkCore_update_devicelist_applist.zip)

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #3326 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Covered by manual testing

### Summary
There was noticed a continuous spam of update app and device list requests from SDL to HMI even if there is no any devices connected and apps registered.
After analysis, there was found a couple of places where logic should be updated:
- In `OnHMIStartedCooperation` don't send update app list after refreshing cloud app information as this function able to trigger the same request itself when needed
- When update app list timer is expired, don't send update app list if no any apps were registered while timer was running 
- In transport manager, don't raise `OnDeviceListUpdated` event if no any devices were added/removed
- SDL should not connect web engine device in `ConnectAllDevices()` due to specific of that device. It should be connected only when some web engine application is launched.
- <s>In transport adapter, don't notify listeners via `OnConnectionStatusUpdated()` callbacks if device connection status was not actually changed</s>

All these actions together prevents all possible reasons of `UpdateAppList`/`UpdateDeviceList` spam observed before fix.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/transport_manager/src/transport_manager_impl.cc [hunk 1]
```diff
@@ -711,10 +711,9 @@ void TransportManagerImpl::CreateWebEngineDevice() {
 
   ws_device->set_keep_on_disconnect(true);
 
-  RaiseEvent(&TransportManagerListener::OnDeviceAdded, web_engine_device_info_);
-  device_list_.push_back(
-      std::make_pair(web_socket_ta, web_engine_device_info_));
   web_socket_ta->AddDevice(ws_device);
+  OnDeviceListUpdated(web_socket_ta);
+  web_socket_ta->ConnectDevice(unique_device_id);
```
Comment (AKalinich-Luxoft) [inline src/components/transport_manager/src/transport_manager_impl.cc:716]: @AKalinich-Luxoft consider `ConnectAllDevices()` function instead

Comment (AKalinich-Luxoft) [reply src/components/transport_manager/src/transport_manager_impl.cc]: Done in https://github.com/smartdevicelink/sdl_core/pull/3339/commits/54d3c07aeb18dcc52a6bee741efcee9b307a81c6

**Comment by theresalech** [comment]
@AKalinich-Luxoft can you please let us know if this is ready for Livio review?

**Comment by AKalinich-Luxoft** [comment]
> @AKalinich-Luxoft can you please let us know if this is ready for Livio review?

@theresalech  Yes, it is ready for Livio review. Updated PR description accordingly.

File: src/components/transport_manager/src/transport_adapter/transport_adapter_impl.cc [hunk 2]
```diff
@@ -339,6 +339,13 @@ ConnectionStatus TransportAdapterImpl::GetConnectionStatus(
 
 void TransportAdapterImpl::ConnectionStatusUpdated(DeviceSptr device,
                                                    ConnectionStatus status) {
+  if (device->connection_status() == status) {
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/transport_manager/src/transport_adapter/transport_adapter_impl.cc]: @iCollin agree. This block of code was removed completely as it is not actual after updating logic in `ConnectAllDevices()` - connection status of web engine device will not be affected by that function anymore.
See https://github.com/smartdevicelink/sdl_core/pull/3339/commits/30c5525949fabb5e81e86afd10645ddb4d8aa79c
