### PR TITLE
Fix deadlock in connection_handler

### LINKED ISSUE #3166: CCB: Fixes deadlock in connection_handler
### Bug Report
Too many threads created no app registration over iOS USB

### Detailed analysis:
Deadlock causing the iAP2 protocol threads to increase without control due to missing acknowledge from SDL to a StartServiceACK from Mobile.

##### Reproduction Steps
1. Connected Android BT Apps registered no issues.
2. Disconnect Android BT.  
3. Connect iOS USB.  
4. Issue observed.

##### Expected Behavior
Not so many threads created, no crashes 

##### Observed Behavior
Too many threads created and sometimes SDL crashes
[bt.txt](https://github.com/smartdevicelink/sdl_core/files/3932103/bt.txt)

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

### PR DESCRIPTION
**Pull request by IGapchuk**
Fixes #3166 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
This PR provides changes for avoiding deadlock in the connection_handler during work with connections list.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/connection_handler/src/connection_handler_impl.cc [hunk 1]
```diff
@@ -461,16 +461,22 @@ void ConnectionHandlerImpl::OnSessionStartedCallback(
     return;
   }
 #endif  // ENABLE_SECURITY
-  sync_primitives::AutoReadLock lock(connection_list_lock_);
-  ConnectionList::iterator it =
-      connection_list_.find(primary_connection_handle);
-  if (connection_list_.end() == it) {
+
+  Connection* connection = nullptr;
+  {
```
Comment (LuxoftAKutsan) [inline src/components/connection_handler/src/connection_handler_impl.cc:466]: propose to wrap this if with some kind of lambda like `find connection` and use lock inside

**Review by LuxoftAKutsan — APPROVED** [review]

**Review by LitvinenkoIra — APPROVED** [review]

**Review by SNiukalov — APPROVED** [review]

**Comment by IGapchuk** [comment]
@theresalech Please be informed, the PR is ready for Livio team review. Thank you!

**Comment by theresalech** [comment]
@IGapchuk, thank you for letting us know. Based on the Steering Committee approved timeline, Livio has started testing for Core 7.0, so we will work to include this PR and any other bug fix PRs as time allows before release.
