### PR TITLE
Fix/sdl 3620 SDL does not respond with NACK to start RPC service request with invalid data

### LINKED ISSUE #3620: SDL does not respond with NACK to start RPC service request with invalid data
### Bug Report
SDL does not respond with NACK to start RPC service request with invalid data

##### Reproduction Steps
1. Start SDL, HMI, connect mobile device
2. App tries to start RPC service over 5th SDL protocol with invalid data in bson payload

##### Expected Behavior
SDL does:
 - send 'OnServiceUpdate' notification to HMI with 'REQUEST_REJECTED'
 - respond with `NACK` to start service request with appropriate `reason`

##### Observed Behavior
SDL does:
 - send 'OnServiceUpdate' notification to HMI with 'REQUEST_REJECTED'
 - not send `StartServiceNack` to mobile app

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (61ea4ef)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - ATF Script: [3620.lua.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5870776/3620.lua.tar.gz)
 - Report and Logs: [2021-01-25_21-30-42.461_3620.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5870777/2021-01-25_21-30-42.461_3620.tar.gz)

### PR DESCRIPTION
**Pull request by VladSemenyuk**
Fixes #3620

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
ATF, Unit tests

### Summary
Fix memory leak with session after Start RPC service NACK.
Fix OnServiceUpdate sending after Start RPC service with invalid data in bson payload for protected mode.
Fix NACK sending for Start any service with non-existent session id.

##### Bug Fixes
**Start RPC service with invalid data in bson payload**
not send StartServiceNack to mobile app
session added in SDL Connection handler(memory leak)

**Start RPC service with not null session id(except for RPC start service for protected mode)**
not send StartServiceNack to mobile app

**Start any service with non-existent session id(existent session ids are returned in RPC StartServiceAck)**
not send StartServiceNack to mobile app

**Start RPC service with invalid data in bson payload for protected mode**
not send 'OnServiceUpdate' notification to HMI with 'REQUEST_REJECTED'

**Start RPC service for protected mode before HMI has provided BC.OnSystemTimeReady notification**
not send 'OnServiceUpdate' notification to HMI with 'REQUEST_REJECTED'

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by VladSemenyuk** [comment]
@JackLivio this PR is ready for review

File: src/components/include/protocol_handler/protocol_handler.h [hunk 1]
```diff
@@ -138,7 +138,7 @@ class ProtocolHandler {
    * generated_session_id is 0.
    */
   virtual void NotifySessionStarted(
-      const SessionContext& context,
+      SessionContext& context,
```
Comment (iCollin) [inline src/components/include/protocol_handler/protocol_handler.h:141]: unfortunately this is not allowed on a public method.

to change this parameter to non-const we need to mark this method as DEPRECATED and define a new method with the new signature.

**Comment by jordynmackool** [comment]
@VladSemenyuk please see the [comment](https://github.com/smartdevicelink/sdl_core/pull/3647#discussion_r597698019) above. Thanks!

File: src/components/include/protocol_handler/protocol_handler.h (hunk 1 above)
Comment (AKalinich-Luxoft) [reply src/components/include/protocol_handler/protocol_handler.h]: @iCollin sorry for that. I declared a new function for that and deprecated the old one.
Note, that I have to make some extra tricks with casts in unit tests to avoid ambiguous call errors.
Fixed in https://github.com/smartdevicelink/sdl_core/pull/3647/commits/77231fce35b028d5691fd42efaff4e155a47be3b

**Comment by AKalinich-Luxoft** [comment]
> @VladSemenyuk please see the [comment](https://github.com/smartdevicelink/sdl_core/pull/3647#discussion_r597698019) above. Thanks!

@jordynmackool comments have been processed here

File: src/components/protocol_handler/src/protocol_handler_impl.cc [hunk 2]
```diff
@@ -2083,10 +2122,20 @@ void ProtocolHandlerImpl::NotifySessionStarted(
...
+    context.is_start_session_failed_ = true;
   }
 }
 
+void ProtocolHandlerImpl::NotifySessionStarted(
+    const SessionContext& context,
+    std::vector<std::string>& rejected_params,
+    const std::string err_reason) {
+  NotifySessionStarted(
+      const_cast<SessionContext&>(context), rejected_params, err_reason);
```
Comment (iCollin) [inline src/components/protocol_handler/src/protocol_handler_impl.cc:2136]: I fear this will cause undefined behavior if called with a const context.

We need to preserve the old functionality (of calling with a const context) until a major version bump.

Comment (AKalinich-Luxoft) [reply src/components/protocol_handler/src/protocol_handler_impl.cc]: @iCollin agree, it's unsafe code. I replaced this cast with the local copy of the same context. As const version of deprecated function is not supposed to change the context, but supposed to use the same callbacks, I believe we can work in this way - https://github.com/smartdevicelink/sdl_core/pull/3647/commits/58fb660c930d0fe7cd42cd8123e12c4522363dc2
Note, that deprecated function is unused for now.

**Review by iCollin — APPROVED** [review]
