### PR TITLE
Fix SDL does not unsubscribe from softbuttons after receiving a response.

### LINKED ISSUE #885: For some RPCs, Core does not unsubscribe from softbuttons after receiving a response
For all of the popup-based RPCs which contain softButtons, Core is supposed to stop processing softButton events once a response is received for the RPC. Currently the only one that does this is [ScrollableMessage](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/application_manager/src/commands/mobile/scrollable_message_response.cc#L55), for all of the others Core stays subscribed to their softButtons after receiving a response.

Affected RPCs: Alert, ShowConstantTBT, AlertManeuver, UpdateTurnList

### PR DESCRIPTION
**Pull request by IGapchuk**
Fixes #885.

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Covered by Unit tests.

### Summary
When SDL recives AlertManeuverResponse, AlertResponse, UpdateTurnListResponse, ScrollableMessageResponse, ShowConstantTBTResponse SDL unsubscribes from soft 
buttons before sends response to mobile.
Added unit test cases for specified responses.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/alert_response.cc [hunk 1]
```diff
@@ -59,6 +59,17 @@ AlertResponse::~AlertResponse() {}
 void AlertResponse::Run() {
   LOG4CXX_AUTO_TRACE(logger_);
 
+  mobile_apis::Result::eType result_code =
+      static_cast<mobile_apis::Result::eType>(
+          (*message_)[strings::msg_params][strings::result_code].asInt());
+  ApplicationSharedPtr application = application_manager_.application(
```
Comment (mked-luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/alert_response.cc]: @IGapchuk application() method expects `uint32_t`, so i think connection key extracted from smart object should be casted to this type

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/update_turn_list_response.cc [hunk 2]
```diff
@@ -57,6 +57,17 @@ UpdateTurnListResponse::~UpdateTurnListResponse() {}
...
+  mobile_apis::Result::eType result_code =
+      static_cast<mobile_apis::Result::eType>(
+          (*message_)[strings::msg_params][strings::result_code].asInt());
+  ApplicationSharedPtr application = application_manager_.application(
+      (*message_)[strings::params][strings::connection_key].asInt());
+
+  if ((mobile_apis::Result::REJECTED != result_code) && application) {
+    application->UnsubscribeFromSoftButtons(
+        (*message_)[strings::params][strings::function_id].asInt());
+  }
```
Comment (mked-luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/update_turn_list_response.cc]: @IGapchuk , as a suggestion, to avoid duplication, we can make a method in app manager that accepts function id, connection key and result code, and performs unsubscribe if needed.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/alert_response.cc (hunk 1 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/alert_response.cc]: @mked-luxoft Fixed in 86f78e521e510b3a41cafe03b1b9bfed2c7b2433.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/update_turn_list_response.cc (hunk 2 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/update_turn_list_response.cc]: @mked-luxoft Moved to app manager in 86f78e521e510b3a41cafe03b1b9bfed2c7b2433.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/simple_response_commands_test.cc [hunk 3]
```diff
@@ -131,6 +127,36 @@ TYPED_TEST(MobileResponseCommandsTest, Run_SendResponseToMobile_SUCCESS) {
   command->Run();
 }
 
+template <class CammandWithUnsubscribe>
+class MobileResponseWithUnsubscribeCommandsTest
+    : public CommandsTest<CommandsTestMocks::kIsNice> {
+ public:
+  typedef CammandWithUnsubscribe CommandWithUnsubscribeType;
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/simple_response_commands_test.cc]: @IGapchuk why do you need this typedef if your new type name longer than old one? :)

File: src/components/application_manager/test/include/application_manager/commands/commands_test.h [hunk 4]
```diff
@@ -97,9 +97,10 @@ class CommandsTest : public ::testing::Test {
 
   typedef NiceMock<MockApplicationManagerSettings> MockAppManagerSettings;
   typedef NiceMock<application_manager_test::MockRPCService> MockRPCService;
-  typedef typename TypeIf<kIsNice,
-                          NiceMock<MockApplicationManager>,
-                          MockApplicationManager>::Result MockAppManager;
+  typedef
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/test/include/application_manager/commands/commands_test.h]: @IGapchuk is this an autoformat fix?

File: src/components/application_manager/include/application_manager/application_manager_impl.h [hunk 5]
```diff
@@ -1030,6 +1030,8 @@ class ApplicationManagerImpl
   bool IsSOStructValid(const hmi_apis::StructIdentifiers::eType struct_id,
                        const smart_objects::SmartObject& display_capabilities);
 
+  virtual bool UnsubscribeAppFromSoftButtons(
+      const commands::MessageSharedPtr& response_message) OVERRIDE;
```
[the remark this answers is not in the document]
Comment (IGapchuk) [reply src/components/application_manager/include/application_manager/application_manager_impl.h]: @AKalinich-Luxoft Fixed in a749f2af0baab2b1647f5f4203a2ee95d9013924.

File: src/components/application_manager/test/include/application_manager/commands/commands_test.h (hunk 4 above)
Comment (IGapchuk) [reply src/components/application_manager/test/include/application_manager/commands/commands_test.h]: @AKalinich-Luxoft Yes, it's an autoformat fix. I have added NiceMock wrapper for MockApplicationManager and removed it after that. Added it again in a749f2af0baab2b1647f5f4203a2ee95d9013924.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/simple_response_commands_test.cc (hunk 3 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/simple_response_commands_test.cc]: @AKalinich-Luxoft Fixed in c65a8ac14947dd4afe2bb1c68bffa2744a5065d2.

File: src/components/application_manager/src/application_manager_impl.cc [hunk 6]
```diff
@@ -3614,6 +3614,28 @@ bool ApplicationManagerImpl::IsSOStructValid(
   return true;
 }
 
+bool ApplicationManagerImpl::UnsubscribeAppFromSoftButtons(
+    const commands::MessageSharedPtr response_message) {
+  const mobile_apis::Result::eType result_code =
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/application_manager_impl.cc]: @IGapchuk split to couple of short lines

File: src/components/application_manager/src/application_manager_impl.cc [hunk 7]
```diff
@@ -3614,6 +3614,28 @@ bool ApplicationManagerImpl::IsSOStructValid(
...
+      static_cast<mobile_apis::Result::eType>(
+          (*response_message)[strings::msg_params][strings::result_code]
+              .asUInt());
+  const uint32_t connection_key =
+      (*response_message)[strings::params][strings::connection_key].asUInt();
+  const auto function_id = static_cast<mobile_apis::FunctionID::eType>(
+      (*response_message)[strings::params][strings::function_id].asInt());
+
+  ApplicationSharedPtr app = application(connection_key);
+  if ((mobile_apis::Result::REJECTED != result_code) && app) {
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/application_manager_impl.cc]: @IGapchuk DCKECK or return app above

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/scrollable_message_response.cc [hunk 8]
```diff
@@ -55,15 +55,7 @@ ScrollableMessageResponse::ScrollableMessageResponse(
...
-  mobile_apis::Result::eType result_code =
-      static_cast<mobile_apis::Result::eType>(
-          (*message_)[strings::msg_params][strings::result_code].asInt());
-  ApplicationSharedPtr application = application_manager_.application(
-      (*message_)[strings::params][strings::connection_key].asInt());
-  if ((mobile_apis::Result::REJECTED != result_code) && application) {
-    application->UnsubscribeFromSoftButtons(
-        (*message_)[strings::params][strings::function_id].asInt());
-  }
+  application_manager_.UnsubscribeAppFromSoftButtons(message_);
```
[the remark this answers is not in the document]
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/scrollable_message_response.cc]: @ZhdanovP Changed in 7ace858a1e660c34f15068e8f3adb351ce26b100.

File: src/components/include/test/application_manager/mock_application_manager.h [hunk 9]
```diff
@@ -273,6 +273,9 @@ class MockApplicationManager : public application_manager::ApplicationManager {
   MOCK_METHOD2(IsSOStructValid,
                bool(const hmi_apis::StructIdentifiers::eType struct_id,
                     const smart_objects::SmartObject& display_capabilities));
+  MOCK_METHOD1(UnsubscribeAppFromSoftButtons,
+               bool(const application_manager::commands::MessageSharedPtr
```
Comment (APipko) [inline src/components/include/test/application_manager/mock_application_manager.h]: What is the return type of UnsubscribeAppFromSoftButtons? Bool or void?

File: src/components/application_manager/src/application_manager_impl.cc [hunk 10]
```diff
@@ -3614,6 +3614,33 @@ bool ApplicationManagerImpl::IsSOStructValid(
...
+      (*response)[strings::params][strings::function_id].asInt());
+
+  ApplicationSharedPtr app = application(connection_key);
+  DCHECK_OR_RETURN(app, false);
+  if (Result::REJECTED != result_code) {
+    app->UnsubscribeFromSoftButtons(function_id);
+    LOG4CXX_DEBUG(logger_,
+                  "Application has unsubscribed from softbusttons. FunctionID: "
+                      << function_id << ", app_id:" << app->app_id());
+    return true;
```
Comment (APipko) [inline src/components/application_manager/src/application_manager_impl.cc]: What is the return type of this method? Bool or void?

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/simple_response_commands_test.cc [hunk 11]
```diff
@@ -131,6 +127,35 @@ TYPED_TEST(MobileResponseCommandsTest, Run_SendResponseToMobile_SUCCESS) {
   command->Run();
 }
 
+template <class CammandWithUnsubscribe>
```
Comment (APipko) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/simple_response_commands_test.cc]: Typo C**o**mmandWithUnsubscribe

File: src/components/application_manager/include/application_manager/application_manager_impl.h [hunk 12]
```diff
@@ -1030,6 +1030,8 @@ class ApplicationManagerImpl
   bool IsSOStructValid(const hmi_apis::StructIdentifiers::eType struct_id,
                        const smart_objects::SmartObject& display_capabilities);
 
+  virtual void UnsubscribeAppFromSoftButtons(
+      const commands::MessageSharedPtr response) OVERRIDE;
```
Comment (APipko) [inline src/components/application_manager/include/application_manager/application_manager_impl.h]: Please, add blank line between methods

Comment (APipko) [inline src/components/application_manager/include/application_manager/application_manager_impl.h]: Please, add blank line between methods.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/simple_response_commands_test.cc (hunk 11 above)
Comment (APipko) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/simple_response_commands_test.cc]: Typo C**o**mmandWithUnsubscribe

File: src/components/application_manager/src/application_manager_impl.cc (hunk 10 above)
Comment (APipko) [inline src/components/application_manager/src/application_manager_impl.cc]: What is the return type of this metod? Bool or void?

File: src/components/include/test/application_manager/mock_application_manager.h (hunk 9 above)
Comment (APipko) [inline src/components/include/test/application_manager/mock_application_manager.h]: What is the return type of UnsubscribeAppFromSoftButtons? Bool or void?

File: src/components/application_manager/include/application_manager/application_manager_impl.h (hunk 12 above)
Comment (IGapchuk) [reply src/components/application_manager/include/application_manager/application_manager_impl.h]: @APipko Fixed in 9062a2e6bb5787c23a1e305bcbe7176ae28bfc9e.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/scrollable_message_response.cc (hunk 8 above)
[the remark this answers is not in the document]
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/scrollable_message_response.cc]: @ZhdanovP In 9062a2e6bb5787c23a1e305bcbe7176ae28bfc9e return value bool returned, because we need that parameter for Unit tests.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/simple_response_commands_test.cc (hunk 11 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/simple_response_commands_test.cc]: @APipko Fixed in return value bool returned, because we need that parameter for Unit tests..

File: src/components/application_manager/src/application_manager_impl.cc (hunk 10 above)
Comment (IGapchuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @APipko Return value bool. We need that parameter for Unit tests. Was reverted in 9062a2e6bb5787c23a1e305bcbe7176ae28bfc9e.

File: src/components/include/application_manager/application_manager.h [hunk 13]
```diff
@@ -726,6 +726,14 @@ class ApplicationManager {
   virtual bool IsSOStructValid(
       const hmi_apis::StructIdentifiers::eType struct_id,
       const smart_objects::SmartObject& display_capabilities) = 0;
+
+  /**
+   * @brief Unsubscribe application that specified in message from softbuttons.
+   * @param MessageSharedPtr - Response message recivied from HMI.
```
Comment (jacobkeeler) [inline src/components/include/application_manager/application_manager.h:732]:
```suggestion
   * @param MessageSharedPtr - Response message received from HMI.
```

File: src/components/application_manager/test/include/application_manager/commands/commands_test.h [hunk 14]
```diff
@@ -97,12 +97,13 @@ class CommandsTest : public ::testing::Test {
...
+      typename TypeIf<kIsNice,
+                      NiceMock<MockApplicationManager>,
+                      NiceMock<MockApplicationManager> >::Result MockAppManager;
```
Comment (jacobkeeler) [inline src/components/application_manager/test/include/application_manager/commands/commands_test.h:103]: This change makes no sense, it makes `kIsNice` meaningless

**Comment by jacobkeeler** [comment]
@AByzhynar @IGapchuk I left a few review comments on this PR, as a note. We are looking to get this fix in between releases if possible. I realize other things might take higher priority, but please let us know if you are able to update this PR when possible.

File: src/components/include/application_manager/application_manager.h [hunk 15]
```diff
@@ -845,6 +845,14 @@ class ApplicationManager {
   virtual bool IsSOStructValid(
       const hmi_apis::StructIdentifiers::eType struct_id,
       const smart_objects::SmartObject& display_capabilities) = 0;
+
+  /**
+   * @brief Unsubscribe application that specified in message from softbuttons.
```
Comment (iCollin) [inline src/components/include/application_manager/application_manager.h:850]:
```suggestion
   * @brief Unsubscribe application specified in message from softbuttons.
```

**Comment by jacobkeeler** [comment]
@iCollin https://github.com/smartdevicelink/sdl_core/blame/304aa9aad5834b6fdcca03f7d372ad6e26e98cc0/src/components/application_manager/src/application_impl.cc#L1112-L1120
Seems this is the old code. I think it might have been that way specifically because `ScrollableMessage` was the only one that unsubscribed from softbuttons before. Now the two cases will probably need to be merged.
Seems the latest code changes were made in the [widgets PR](https://github.com/smartdevicelink/sdl_core/commit/e96730b471a19d43d5de333de0e5c6af6db2e70a) making the difference in the cases less clear.

**Comment by jacobkeeler** [comment]
@iCollin addressed comments

**Comment by IGapchuk** [comment]
Hi @jacobkeeler @iCollin ! We have made the changes according to the comment https://github.com/smartdevicelink/sdl_core/pull/2629#pullrequestreview-427531958. Now softbutton subscriptions are keeping in pair with related WindowID. Please, take a look at b78984c3bdca33f37d81c4d692319615f5704e20. Also, we've made back-merge develop branch into the fix branch a3f552f70c97934cadda2cba5153baaf6f02341e

**Comment by AKalinich-Luxoft** [comment]
@JackLivio @iCollin 
Conflicts have been resolved and `develop` branch has been merged into the current PR (my apologizes for a force-push but last merge commit has messed up the branch)

File: src/components/application_manager/test/message_helper/message_helper_test.cc [hunk 16]
```diff
@@ -888,16 +888,45 @@ TEST_F(MessageHelperTest,
   }
 }
 
-TEST_F(MessageHelperTest, SubscribeApplicationToSoftButton_CallFromApp) {
-  // Create application mock
+TEST_F(MessageHelperTest,
+       SubscribeApplicationToSoftButton_SoftbuttonsIsAnsent_DoesntCallFromApp) {
```
Comment (ShobhitAd) [inline src/components/application_manager/test/message_helper/message_helper_test.cc:892]:
```suggestion
       SubscribeApplicationToSoftButton_SoftbuttonsAreAbsent_DoesntCallFromApp) {
```

**Review by ShobhitAd — CHANGES_REQUESTED** [review]

File: src/components/application_manager/include/application_manager/application.h [hunk 17]
```diff
@@ -170,9 +170,14 @@ typedef std::map<uint32_t, smart_objects::SmartObject*> PerformChoice;
...
- * @brief Defines id of SoftButton
+ * @brief Defines id of SoftButtons related to a specified WindowID
  */
-typedef std::set<std::pair<uint32_t, WindowID> > SoftButtonID;
+typedef std::set<std::pair<WindowID, std::set<uint32_t> > > SoftButtonIDs;
+
+/**
+ * @brief Defines id of SoftButtons for specified WindowID
+ */
+typedef std::pair<WindowID, std::set<uint32_t> > WindowSoftButtons;
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/application_manager/include/application_manager/application.h]: @ShobhitAd fixed in https://github.com/smartdevicelink/sdl_core/pull/2629/commits/6ef9cfb61065b10785ad4fc37f0b0b0463f86fb7

File: src/components/application_manager/include/application_manager/application.h [hunk 18]
```diff
@@ -963,8 +968,8 @@ class Application : public virtual InitialApplicationData,
    * @param cmd_id Unique command id from mobile API
    * @param list of softbuttons were created by command.
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/application_manager/include/application_manager/application.h]: @ShobhitAd fixed in https://github.com/smartdevicelink/sdl_core/pull/2629/commits/6ef9cfb61065b10785ad4fc37f0b0b0463f86fb7

File: src/components/application_manager/test/message_helper/message_helper_test.cc (hunk 16 above)
Comment (AKalinich-Luxoft) [reply src/components/application_manager/test/message_helper/message_helper_test.cc]: @ShobhitAd fixed in https://github.com/smartdevicelink/sdl_core/pull/2629/commits/6ef9cfb61065b10785ad4fc37f0b0b0463f86fb7

**Review by ShobhitAd — APPROVED** [review]
