### PR TITLE
Fix trying to unlock mutex not held by any thread

### LINKED ISSUE #3186: CCB: Fix trying to unlock mutex not held by any thread
### Bug Report
Data races related to MessageQueue

### Detailed analysis:
Mutex released before call Broadcast.

##### Reproduction Steps
1. TBD

##### Expected Behavior
SDL should not crash

##### Observed Behavior
SDL crashed

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

### PR DESCRIPTION
**Pull request by LuxoftAKutsan**
Fixes #3186

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Regression automated testing

### Summary

Fix trying to unlock mutex not held by any thread
Helgrind considers that this issue is an error because we release mutex before call Broadcast.

- [ ] Luxoft internal review 
- [ ] Regression automated testing

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/include/utils/message_queue.h [hunk 1]
```diff
@@ -171,13 +171,11 @@ bool MessageQueue<T, Q>::IsShuttingDown() const {
...
-    if (shutting_down_) {
-      return;
-    }
-    queue_.push(element);
+  sync_primitives::AutoLock auto_lock(queue_lock_);
+  if (shutting_down_) {
+    return;
   }
+  queue_.push(element);
   queue_new_items_.Broadcast();
```
Comment (jacobkeeler) [inline src/components/include/utils/message_queue.h:179]: It seems to me like this change would cause a DCHECK, I'm surprised that this is supposed to fix an issue. If one thread has called `Wait`, that would mean that when the `Broadcast` is received we would reach `AssertFreeAndMarkTaken`, which will cause a `NOTREACHED` call if the lock is still held.

Comment (LuxoftAKutsan) [reply src/components/include/utils/message_queue.h:179]: Fix moved from SYNC4 codebase. Additional testing and description will be provided

**Comment by theresalech** [comment]
@LuxoftAKutsan, can you please let us know when this is ready for re-review?

**Comment by LuxoftAKutsan** [comment]
@theresalech this work is planned. We will notiy when fix with test scripts will be available.

File: src/components/include/utils/message_queue.h (hunk 1 above)
Comment (LuxoftAKutsan) [reply src/components/include/utils/message_queue.h:179]: `Broadcast()` will unlock the `queue_lock_` and let the process that is waiting on `Wait()` to lock the `queue_lock_`. 

In another case between `Broadcast()` from thread1 and `Wait()` from thread2 some other thread may acquire `queue_lock_` that will prevent ability for thread2 to squre

**Comment by LuxoftAKutsan** [comment]
@jacobkeeler @theresalech full regression tested on this PR. Results are similar to develop

File: src/components/include/utils/message_queue.h (hunk 1 above)
Comment (JackLivio) [reply src/components/include/utils/message_queue.h:179]: Confirmed logic from online resources: https://docs.oracle.com/cd/E19455-01/806-5257/sync-27/index.html

> Call pthread_cond_broadcast() under the protection of the same mutex that is used with the condition variable being signaled. Otherwise, the condition variable could be signaled between the test of the associated condition and blocking in pthread_cond_wait(), which can cause an infinite wait.

**Review by JackLivio — APPROVED** [review]
