### PR TITLE
Fix SSL max block size logic

### LINKED ISSUE #3640: SDL crashes while sending OnSystemRequest in case if RPC service is protected and SDL protocol version is 3rd and greater
### Bug Report
This is a continuation of original issue which is described in https://github.com/smartdevicelink/sdl_core/issues/2922 and had been fixed in scope of Release 6.0.
Current issue addresses the same scenario but version of SDL protocol is >= 3

##### Reproduction Steps
1. Register new app with SDL protocol version >= 3
=> Policy Update is started
2. Switch RPC service to protected mode
=> SDL continues PTU sequence
=> SDL->App: OnSystemRequest(with snapshot)

##### Expected Behavior
SDL proceed with OnSystemRequest notification successfully

##### Observed Behavior
SDL crashes with error:
```
smartDeviceLinkCore: /home/developer/sdl/sdl_core/src/components/security_manager/src/ssl_context_impl.cc:470:
virtual bool security_manager::CryptoManagerImpl::SSLContextImpl::Encrypt(const uint8_t*, size_t, const uint8_t**, size_t*):
Assertion `(len == static_cast<size_t>(read_size))' failed.
```

##### OS & Version Information
* OS/Version: Ubuntu 20.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (d8cd806)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - ATF Script: [003_PTU_all_flows_Protected_Mode_v3.lua.tar.gz](https://github.com/smartdevicelink/sdl_core/files/6076555/003_PTU_all_flows_Protected_Mode_v3.lua.tar.gz)
 - Report and Logs: [2021-02-25_14-39-18.239_3640.tar.gz](https://github.com/smartdevicelink/sdl_core/files/6045404/2021-02-25_14-39-18.239_3640.tar.gz)

### PR DESCRIPTION
**Pull request by jacobkeeler**
Fixes #3640 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Run test script provided in #3640 

### Summary
Fixes `get_max_block_size` logic when the cipher name provided is unknown. Also adds the cipher name used in the provided test to the list of known ciphers.

##### Bug Fixes
* Fixes `get_max_block_size` logic when the cipher name provided is unknown. 
* Adds missing cipher name to the list of known ciphers.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by VladSemenyuk — APPROVED** [review]

File: src/components/security_manager/src/ssl_context_impl.cc [hunk 1]
```diff
@@ -522,16 +524,15 @@ bool CryptoManagerImpl::SSLContextImpl::Decrypt(const uint8_t* const in_data,
 
 size_t CryptoManagerImpl::SSLContextImpl::get_max_block_size(size_t mtu) const {
   SDL_LOG_AUTO_TRACE();
+  const auto max_allowed_block_size =
+      mtu > SSL3_RT_MAX_PLAIN_LENGTH ? SSL3_RT_MAX_PLAIN_LENGTH : mtu;
   if (!max_block_size_) {
     // FIXME(EZamakhov): add correct logics for TLS1/1.2/SSL3
```
Comment (JackLivio) [inline src/components/security_manager/src/ssl_context_impl.cc:530]: @jacobkeeler Can this FIXME comment be removed?

**Review by JackLivio — APPROVED** [review]
