### PR TITLE
Cover connection handler and policy handler with unit tests

### LINKED ISSUE #2449: Increase unit tests coverage
### Bug Report
Need  to increase unit tests coverage 

- Add Unit tests to cover changes in Session and Policy Handler 

- Modified Policy Handler Unit tests.

- Add Unit tests for Connection Handler.

- Add Unit tests for RPC Service.

- Add Unit tests for CacheManager.

##### OS & Version Information
* OS/Version: Ubutnu 18
* SDL Core Version: 6.0

### PR DESCRIPTION
**Pull request by mkorniichuk**
Fixes #2449

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
Improved unit test coverage for connection handler and protocol handler

##### Breaking Changes
* Few tests added to connection_handler_impl_test.cc and to connection_test.cc
* There were 2 mocks for telemetry observer. So, one is removed (src/components/include/test/protocol_handler/mock_telemetry_observer.h). Fixed mock_telemetry_observer.h (src/components/protocol_handler/test/include/protocol_handler/mock_telemetry_observer.h)
* Added tests to protocol_handler_tm_test.cc
* set_hash_id and get_hash_id are covered with unit tests.
* set_hash_id, get_hash_id, ConvertPacketDataToString, get_protocol_observers_count declarations are added to protocol_handler_impl.h under BUILD_TEST flag.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/connection_handler/test/connection_handler_impl_test.cc [hunk 1]
```diff
@@ -398,6 +398,10 @@ TEST_F(ConnectionHandlerTest, AddConnection_StopConnection) {
 }
 
 TEST_F(ConnectionHandlerTest, GetConnectionSessionsCount) {
+  EXPECT_TRUE(connection_handler_->getConnectionList().empty());
```
Comment (LuxoftAKutsan) [inline src/components/connection_handler/test/connection_handler_impl_test.cc]: @mkorniichuk if it is the only possible default state use ASSERT, if it is precondition for test use ON_CALL, if it is tested functionality - use EXPECT.

File: src/components/connection_handler/test/connection_handler_impl_test.cc [hunk 2]
```diff
@@ -442,10 +453,21 @@ TEST_F(ConnectionHandlerTest, GetDeviceID) {
...
 
+  std::string invalid_mac_address;
+  EXPECT_FALSE(
+      connection_handler_->GetDeviceID(invalid_mac_address, &test_handle));
+
   EXPECT_TRUE(connection_handler_->GetDeviceID(test_mac_address, &test_handle));
   EXPECT_EQ(device_handle_, test_handle);
 }
 
+TEST_F(ConnectionHandlerTest, GetDataOnDeviceID) {
```
Comment (LuxoftAKutsan) [inline src/components/connection_handler/test/connection_handler_impl_test.cc]: @mkorniichuk describe test case in test case name

File: src/components/protocol_handler/include/protocol_handler/protocol_handler_impl.h [hunk 3]
```diff
@@ -160,6 +160,18 @@ struct TransportDescription {
 typedef std::map<std::string, TransportDescription> TransportTypes;
 }  // namespace impl
 
+#ifdef BUILD_TESTS
+/**
+ * Function return packet data as std::string.
+ * If packet data is not printable return error message
+ */
+std::string ConvertPacketDataToString(const uint8_t* data,
```
Comment (LuxoftAKutsan) [inline src/components/protocol_handler/include/protocol_handler/protocol_handler_impl.h]: @mkorniichuk dowe rely need to add this add this functionwith BUILD_TESTS flag? It is rather bad practive to extend class for testing

Comment (mkorniichuk) [reply src/components/protocol_handler/include/protocol_handler/protocol_handler_impl.h]: @LuxoftAKutsan A function ConvertPacketDataToString as well as get_hash_id and set_hash_id are functions, not a class members and are used only in protocol_handler_impl.cc. Their declaration can be removed from the header file at all, but in this case, all tests for these functions have to be removed as well. And, I suppose, include source file is even worse.

**Comment by mkorniichuk** [comment]
Rebuild required

**Comment by mkorniichuk** [comment]
Rebuild required

**Comment by mkorniichuk** [comment]
Rebuild required

**Comment by mkorniichuk** [comment]
Rebuild required

**Comment by mkorniichuk** [comment]
Rebuild required

**Comment by mkorniichuk** [comment]
Rebuild required

**Comment by mkorniichuk** [comment]
Rebuild required

**Comment by mkorniichuk** [comment]
Rebuild required

**Comment by mkorniichuk** [comment]
Rebuild required

**Comment by mkorniichuk** [comment]
Rebuild required

**Comment by mkorniichuk** [comment]
Rebuild required

**Comment by mkorniichuk** [comment]
Rebuild required

File: src/components/utils/test/convert_utils_test.cc [hunk 4]
```diff
@@ -30,26 +31,53 @@
...
+TEST(ConvertUtilsTest, ConvertLongLongUIntToUInt64_CorrectValue) {
+  unsigned long long int value_to_convert = 42;
+  EXPECT_EQ(typeid(uint64_t),
+            typeid(ConvertLongLongUIntToUInt64(value_to_convert)));
+}
+
+TEST(ConvertUtilsTest, ConvertBinaryDataToString_ValidCharacteres_CorrectText) {
+  const uint8_t data[] = {'s', 'u', 'c', 'c', 'e', 's', 's'};
+  const size_t data_size = 7;
+  EXPECT_EQ("success", ConvertBinaryDataToString(&data[0], data_size));
```
Comment (IGapchuk) [inline src/components/utils/test/convert_utils_test.cc:70]: @mkorniichuk I believe you should change the const literal `"success"` to a predefined const `std::string = "success"`, because you check the method that convert a data to the `std::string`.

File: src/components/connection_handler/test/connection_handler_impl_test.cc [hunk 5]
```diff
@@ -412,15 +416,22 @@ TEST_F(ConnectionHandlerTest, GetAppIdOnSessionKey) {
...
-                connection_key_, &app_id, NULL, device_id));
+                connection_key_, &app_id, NULL, &test_handle));
   EXPECT_EQ(test_id, app_id);
 }
 
+TEST_F(ConnectionHandlerTest, GetAppIdOnSessionKey_InvalidConnectionId) {
+  uint8_t invalid_id = 0;
+  EXPECT_EQ(
+      -1,
+      connection_handler_->GetDataOnSessionKey(invalid_id, NULL, NULL, NULL));
```
Comment (IGapchuk) [inline src/components/connection_handler/test/connection_handler_impl_test.cc:432]: @mkorniichuk Since we use the C++ 11 standard, you could use the `nullptr` instead of `NULL` macros.

File: src/components/protocol_handler/test/protocol_handler_tm_test.cc [hunk 6]
```diff
@@ -3367,11 +3482,872 @@ TEST_F(ProtocolHandlerImplTest, SendMessageToMobileApp_SendMultiframeMessage) {
...
+  ASSERT_EQ(0u, protocol_handler_impl->get_protocol_observers_count());
+
+  protocol_handler_impl->AddProtocolObserver(&protocol_observer_mock);
+  ASSERT_EQ(1u, protocol_handler_impl->get_protocol_observers_count());
+
+  protocol_handler_impl->RemoveProtocolObserver(&protocol_observer_mock);
+  EXPECT_EQ(0u, protocol_handler_impl->get_protocol_observers_count());
+}
+
+TEST_F(ProtocolHandlerImplTest, GetSessionObserver_CorrectObserver) {
```
Comment (ychernysheva) [inline src/components/protocol_handler/test/protocol_handler_tm_test.cc:3557]: I think that this test is redundant, code of this method is too simple to check.

File: src/components/protocol_handler/test/protocol_handler_tm_test.cc [hunk 7]
```diff
@@ -3367,11 +3482,872 @@ TEST_F(ProtocolHandlerImplTest, SendMessageToMobileApp_SendMultiframeMessage) {
...
+  OnTMMessageSend();
+  ProtocolFramePtr protocol_packet =
+      std::make_shared<ProtocolPacket>(connection_id,
+                                       PROTOCOL_VERSION_3,
+                                       PROTECTION_OFF,
+                                       FRAME_TYPE_SINGLE,
+                                       kRpc,
+                                       FRAME_DATA_SINGLE,
+                                       session_id,
+                                       0u,
```
Comment (ychernysheva) [inline src/components/protocol_handler/test/protocol_handler_tm_test.cc:3603]: Please consider replacing this number with constant with meaningful name.

File: src/components/protocol_handler/test/protocol_handler_tm_test.cc [hunk 8]
```diff
@@ -3367,11 +3482,872 @@ TEST_F(ProtocolHandlerImplTest, SendMessageToMobileApp_SendMultiframeMessage) {
...
+  transport_manager::DataSendError data_send_error;
+  const uint8_t data_size = 8u;
+  uint8_t data[data_size];
+  RawMessagePtr message = std::make_shared<RawMessage>(
+      connection_key, PROTOCOL_VERSION_3, &data[0], data_size);
+
+  tm_listener->OnTMMessageSendFailed(data_send_error, message);
+}
+
+TEST_F(ProtocolHandlerImplTest, OnConnectionClosed) {
```
Comment (ychernysheva) [inline src/components/protocol_handler/test/protocol_handler_tm_test.cc:3650]: I think that this test doesn't check anything, we still need them?

File: src/components/protocol_handler/test/protocol_handler_tm_test.cc [hunk 9]
```diff
@@ -3367,11 +3482,872 @@ TEST_F(ProtocolHandlerImplTest, SendMessageToMobileApp_SendMultiframeMessage) {
...
+          protocol_handler_impl.get());
+  protocol_handler::impl::RawFordMessageFromMobile message(
+      std::make_shared<protocol_handler::ProtocolPacket>(connection_id,
+                                                         PROTOCOL_VERSION_3,
+                                                         PROTECTION_OFF,
+                                                         FRAME_TYPE_SINGLE,
+                                                         kControl,
+                                                         FRAME_DATA_SINGLE,
+                                                         session_id,
+                                                         1u,
```
Comment (ychernysheva) [inline src/components/protocol_handler/test/protocol_handler_tm_test.cc:3701]: Same situation with unclear value, please check similar cases across all file

File: src/components/protocol_handler/test/protocol_handler_tm_test.cc [hunk 10]
```diff
@@ -3367,11 +3482,872 @@ TEST_F(ProtocolHandlerImplTest, SendMessageToMobileApp_SendMultiframeMessage) {
...
+                                                         message_id,
+                                                         &some_data[0]));
```
Comment (ychernysheva) [inline src/components/protocol_handler/test/protocol_handler_tm_test.cc:3703]: Unclear meaning of pointer to "some data" with index, maybe it will be better to create constant or variable with self-explained name.

Comment (ychernysheva) [reply src/components/protocol_handler/test/protocol_handler_tm_test.cc:3703]: Please check all similar cases across the file

**Comment by iCollin** [comment]
@mkorniichuk is work still planned on this PR?

File: src/components/connection_handler/test/connection_handler_impl_test.cc [hunk 11]
```diff
@@ -413,15 +417,22 @@ TEST_F(ConnectionHandlerTest, GetAppIdOnSessionKey) {
...
 
   uint32_t app_id = 0;
+  DeviceHandle test_handle;
   const uint32_t test_id = SessionHash(uid_, out_context_.new_session_id_);
 
-  connection_handler::DeviceHandle* device_id = NULL;
   EXPECT_EQ(0,
             connection_handler_->GetDataOnSessionKey(
-                connection_key_, &app_id, NULL, device_id));
+                connection_key_, &app_id, nullptr, &test_handle));
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/connection_handler/test/connection_handler_impl_test.cc]: @iCollin this is because we have a separate test for each param. This particular UT verifies app_id param. I removed redundant param to avoid confusions.
See https://github.com/smartdevicelink/sdl_core/pull/2682/commits/0b92f716443b0246f9af8210846e8b2c53fa7221

File: src/components/connection_handler/test/connection_handler_impl_test.cc [hunk 12]
```diff
@@ -463,10 +485,12 @@ TEST_F(ConnectionHandlerTest, GetConnectionType) {
...
   const DeviceHandle handle = 0;
+  std::string test_mac_address;
   std::string test_connection_type;
-  EXPECT_EQ(0,
-            connection_handler_->GetDataOnDeviceID(
-                handle, NULL, NULL, NULL, &test_connection_type));
+  EXPECT_EQ(
+      0,
+      connection_handler_->GetDataOnDeviceID(
+          handle, nullptr, nullptr, &test_mac_address, &test_connection_type));
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/connection_handler/test/connection_handler_impl_test.cc]: @iCollin this is because we have a separate test for each param. This particular UT verifies app_id param. I removed redundant param to avoid confusions.
See 0b92f71

File: src/components/protocol_handler/test/protocol_handler_tm_test.cc [hunk 13]
```diff
@@ -3807,11 +3948,1038 @@ TEST_F(ProtocolHandlerImplTest, SendMessageToMobileApp_SendMultiframeMessage) {
...
+  uint32_t times = 0;
+
+  AddSession(waiter, times);
+
+#ifdef ENABLE_SECURITY
+  EXPECT_CALL(session_observer_mock, GetSSLContext(_, _)).Times(0);
+#endif  // ENABLE_SECURITY
+  EXPECT_CALL(transport_manager_mock, SendMessageToDevice(_)).Times(0);
+  // Act
+  RawMessagePtr message;
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/protocol_handler/test/protocol_handler_tm_test.cc:4069]: @iCollin does not make any sense as default-constructed shared pointer is already assigned with null. Existing version more clear as for me.

File: src/components/protocol_handler/test/protocol_handler_tm_test.cc [hunk 14]
```diff
@@ -3807,11 +3948,1038 @@ TEST_F(ProtocolHandlerImplTest, SendMessageToMobileApp_SendMultiframeMessage) {
...
+
+TEST_F(ProtocolHandlerImplTest, OnTMMessageSend_InvalidData_Cancelled) {
+  const uint8_t data_size = 8u;
+  uint8_t data[data_size];
+  // Create invalid data
+  for (uint8_t i = 0; i < data_size; ++i) {
+    data[i] = -1;
+  }
+  RawMessagePtr message = std::make_shared<RawMessage>(
+      connection_key, PROTOCOL_VERSION_3, &data[0], data_size, PROTECTION_OFF);
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/protocol_handler/test/protocol_handler_tm_test.cc]: @iCollin fixed in https://github.com/smartdevicelink/sdl_core/pull/2682/commits/0b92f716443b0246f9af8210846e8b2c53fa7221

File: src/components/protocol_handler/test/protocol_handler_tm_test.cc [hunk 15]
```diff
@@ -3807,11 +3948,1038 @@ TEST_F(ProtocolHandlerImplTest, SendMessageToMobileApp_SendMultiframeMessage) {
...
+      std::make_shared<protocol_handler::ProtocolPacket>(connection_id,
+                                                         PROTOCOL_VERSION_3,
+                                                         PROTECTION_OFF,
+                                                         FRAME_TYPE_CONTROL,
+                                                         kControl,
+                                                         FRAME_DATA_HEART_BEAT,
+                                                         session_id,
+                                                         some_data.size(),
+                                                         message_id,
+                                                         &some_data[0]),
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/protocol_handler/test/protocol_handler_tm_test.cc]: @iCollin fixed in https://github.com/smartdevicelink/sdl_core/pull/2682/commits/0b92f716443b0246f9af8210846e8b2c53fa7221

File: src/components/protocol_handler/test/protocol_handler_tm_test.cc [hunk 16]
```diff
@@ -3807,11 +3948,1038 @@ TEST_F(ProtocolHandlerImplTest, SendMessageToMobileApp_SendMultiframeMessage) {
...
+TEST_F(ProtocolHandlerImplTest, GetHashId_ProtocolVersion5_ValidData) {
+  auto protocol_handler_impl_as_listener =
+      static_cast<protocol_handler::impl::FromMobileQueue::Handler*>(
+          protocol_handler_impl.get());
+
+  const uint8_t data_size = 5u;
+  uint8_t data[data_size] = {0x00};
+  data[0] = data_size;
+
+  BsonObject obj = bson_object_from_bytes(&data[0]);
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/protocol_handler/test/protocol_handler_tm_test.cc]: @iCollin fixed in https://github.com/smartdevicelink/sdl_core/pull/2682/commits/0b92f716443b0246f9af8210846e8b2c53fa7221

File: src/components/protocol_handler/test/protocol_handler_tm_test.cc [hunk 17]
```diff
@@ -3807,11 +3948,1038 @@ TEST_F(ProtocolHandlerImplTest, SendMessageToMobileApp_SendMultiframeMessage) {
...
+          connection_id,
+          PROTOCOL_VERSION_5,
+          PROTECTION_OFF,
+          FRAME_TYPE_CONTROL,
+          kControl,
+          FRAME_DATA_END_SERVICE_ACK,
+          session_id,
+          data_size,
+          message_id,
+          &data[0]));
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/protocol_handler/test/protocol_handler_tm_test.cc]: @iCollin fixed in https://github.com/smartdevicelink/sdl_core/pull/2682/commits/0b92f716443b0246f9af8210846e8b2c53fa7221

File: src/components/protocol_handler/test/protocol_handler_tm_test.cc [hunk 18]
```diff
@@ -3807,11 +3948,1038 @@ TEST_F(ProtocolHandlerImplTest, SendMessageToMobileApp_SendMultiframeMessage) {
...
+}
+
+TEST_F(ProtocolHandlerImplTest, GetHashId_ProtocolVersion5_ValidData) {
+  auto protocol_handler_impl_as_listener =
+      static_cast<protocol_handler::impl::FromMobileQueue::Handler*>(
+          protocol_handler_impl.get());
+
+  const uint8_t data_size = 5u;
+  uint8_t data[data_size] = {0x00};
+  data[0] = data_size;
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/protocol_handler/test/protocol_handler_tm_test.cc]: @iCollin agree. Applied in https://github.com/smartdevicelink/sdl_core/pull/2682/commits/0b92f716443b0246f9af8210846e8b2c53fa7221

File: src/components/protocol_handler/test/protocol_handler_tm_test.cc [hunk 19]
```diff
@@ -3807,11 +3948,1038 @@ TEST_F(ProtocolHandlerImplTest, SendMessageToMobileApp_SendMultiframeMessage) {
...
+
+TEST_F(ProtocolHandlerImplTest, PopValidAndExpiredMultiframes) {
+  using namespace protocol_handler;
+  std::shared_ptr<TestAsyncWaiter> waiter = std::make_shared<TestAsyncWaiter>();
+  uint32_t times = 0;
+
+  AddSession(waiter, times);
+
+  // Create messages so the execution will enter
+  // PopValidAndExpiredMultiframes
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/protocol_handler/test/protocol_handler_tm_test.cc]: @iCollin removed in https://github.com/smartdevicelink/sdl_core/pull/2682/commits/0b92f716443b0246f9af8210846e8b2c53fa7221

File: src/components/utils/test/convert_utils_test.cc [hunk 20]
```diff
@@ -30,26 +31,55 @@
...
+  unsigned long long int value_to_convert = 42;
+  EXPECT_EQ(typeid(uint64_t),
+            typeid(ConvertLongLongUIntToUInt64(value_to_convert)));
+}
+
+TEST(ConvertUtilsTest, ConvertBinaryDataToString_ValidCharacteres_CorrectText) {
+  const uint8_t data[] = {'s', 'u', 'c', 'c', 'e', 's', 's'};
+  const std::string convertion_result = "success";
+  const size_t data_size = 7;
+  EXPECT_EQ(convertion_result, ConvertBinaryDataToString(&data[0], data_size));
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/utils/test/convert_utils_test.cc]: @iCollin fixed in https://github.com/smartdevicelink/sdl_core/pull/2682/commits/0b92f716443b0246f9af8210846e8b2c53fa7221

File: src/components/utils/test/convert_utils_test.cc [hunk 21]
```diff
@@ -30,26 +31,55 @@
...
-                    const date_time::TimeDuration& start_time));
-  MOCK_METHOD1(EndMessageProcess, void(std::shared_ptr<MessageMetric> m));
-};
+TEST(ConvertUtilsTest,
+     ConvertBinaryDataToString_NotValidCharacters_CorrectText) {
+  const size_t data_size = 7;
+  uint8_t data[data_size];
+  data[0] = 0u;
+  const std::string is_raw_data = "is raw data";
+  EXPECT_EQ(is_raw_data, ConvertBinaryDataToString(&data[0], data_size));
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/utils/test/convert_utils_test.cc]: @iCollin fixed in https://github.com/smartdevicelink/sdl_core/pull/2682/commits/0b92f716443b0246f9af8210846e8b2c53fa7221

**Comment by AKalinich-Luxoft** [comment]
> @mkorniichuk is work still planned on this PR?

@iCollin 
Sorry for late response. Looks like involved people left SDL project so this PR was not tracked.
I addressed all your comments, resolved conflicts and fix affected unit tests according to new functionality of release 7.0
Please review one more time and let me know if any other changes required here.

**Review by iCollin — APPROVED** [review]
