### PR TITLE
Fix/Send OnAppPropertiesChange in case one of nicknames is removed

### LINKED ISSUE #3321: SDL does not send OnAppPropertiesChange notification to HMI in case one of nicknames is removed
### Bug Report
SDL does not send OnAppPropertiesChange notification to HMI in case one of nicknames is removed

##### Reproduction Steps
1. SDL and HMI are started
2. HMI sends BC.SetAppProperties request with application properties (without two nicknames) of the policyAppID to SDL
HMI → SDL : SetAppProperties ( properties:
{nicknames:{**"Hello Sdl1", "HelloSdl2"**} ,
policyAppID:"12345678",
enabled: true,
transportType:"WS",
hybridAppPreference: "CLOUD"})
3. HMI sends BC.SetAppProperties request with application properties (without one of nicknames) of the policyAppID to SDL
HMI → SDL : SetAppProperties ( properties:
{nicknames:{**"Hello Sdl1"**} ,
policyAppID:"12345678",
enabled: true,
authToken:"AuthToken8888",
transportType:"WS",
hybridAppPreference: "CLOUD"}

##### Expected Behavior
  1. SDL sends BC.OnAppPropertiesChange notification with appropriate app properties parameters (without one of nicknames) to HMI
SDL → HMI: OnAppPropertiesChange ({ properties:
{nicknames:{**"Hello Sdl1"**} ,
policyAppID:"12345678",
enabled: true,
transportType:"WS",
hybridAppPreference: "CLOUD"}

##### Observed Behavior
  1. SDL **does not send** BC.OnAppPropertiesChange notification with appropriate app properties parameters (without one of nicknames) to HMI

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: 74d24927cf77282c44678eba219adadbb6dcd072
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

##### Test Case, Sample Code, and / or Example App
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/defect/onAppPropertiesChange_remove_nickname/test_scripts/Defects/6_1/3321_OnAppPropertiesChange_remove_nickname.lua
SDL_ATF_logs: [Logs_OnAppProperties.zip](https://github.com/smartdevicelink/sdl_core/files/4426703/Logs_OnAppProperties.zip)

### PR DESCRIPTION
**Pull request by SNiukalov**
Fixes #3321 

This PR is **not ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Use scripts from
[smartdevicelink/sdl_atf_test_scripts/onAppPropertiesChange_remove_nickname]( https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/defect/onAppPropertiesChange_remove_nickname/test_scripts/Defects/6_1/3321_OnAppPropertiesChange_remove_nickname.lua)
UTs

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/test/policy_handler_test.cc [hunk 1]
```diff
@@ -3031,10 +3032,33 @@ TEST_F(PolicyHandlerTest, GetAppPropertiesStatus_NicknameChanged_SUCCESS) {
             policy_handler_.GetAppPropertiesStatus(properties, kPolicyAppId_));
 }
 
-TEST_F(PolicyHandlerTest, GetAppPropertiesStatus_NicknameNotChanged_SUCCESS) {
+TEST_F(PolicyHandlerTest,
+       GetAppPropertiesStatus_NicknameRemoveChanged_SUCCESS) {
```
Comment (AByzhynar) [inline src/components/application_manager/test/policy_handler_test.cc:3036]: @SNiukalov May be ..._RemoveChangedNickname_... ?

File: src/components/application_manager/test/policy_handler_test.cc [hunk 2]
```diff
@@ -3031,10 +3032,33 @@ TEST_F(PolicyHandlerTest, GetAppPropertiesStatus_NicknameChanged_SUCCESS) {
...
 
-  const std::string kFakeNickname = "fake_nickname";
+  smart_objects::SmartObject properties;
+  properties[strings::app_id] = kPolicyAppId_;
+  properties[strings::nicknames] =
+      smart_objects::SmartObject(smart_objects::SmartType_Array);
+  properties[strings::nicknames].asArray()->push_back(
+      smart_objects::SmartObject(kFakeNickname));
+
+  std::shared_ptr<policy::StringArray> nicknames =
```
Comment (mvorobio) [inline src/components/application_manager/test/policy_handler_test.cc:3046]:
```suggestion
  auto nicknames =
```

File: src/components/application_manager/test/policy_handler_test.cc (hunk 1 above)
Comment (SNiukalov) [reply src/components/application_manager/test/policy_handler_test.cc]: @AByzhynar 
Thanks, fixed in:https://github.com/smartdevicelink/sdl_core/pull/3336/commits/e8b6796277ec4c559a26fb8e02562d0929e67b94

File: src/components/application_manager/test/policy_handler_test.cc (hunk 2 above)
Comment (SNiukalov) [reply src/components/application_manager/test/policy_handler_test.cc]: @mvorobio 
Thanks,fixed in:https://github.com/smartdevicelink/sdl_core/pull/3336/commits/e8b6796277ec4c559a26fb8e02562d0929e67b94

File: src/components/application_manager/test/policy_handler_test.cc [hunk 3]
```diff
@@ -3031,10 +3032,32 @@ TEST_F(PolicyHandlerTest, GetAppPropertiesStatus_NicknameChanged_SUCCESS) {
...
 
-  const std::string kFakeNickname = "fake_nickname";
+  smart_objects::SmartObject properties;
+  properties[strings::app_id] = kPolicyAppId_;
+  properties[strings::nicknames] =
+      smart_objects::SmartObject(smart_objects::SmartType_Array);
+  properties[strings::nicknames].asArray()->push_back(
+      smart_objects::SmartObject(kFakeNickname));
+
+  auto nicknames = std::make_shared<policy::StringArray>(2, kFakeNickname);
```
Comment (AByzhynar) [inline src/components/application_manager/test/policy_handler_test.cc:3046]: @SNiukalov Missed required header file inclusion

Comment (SNiukalov) [reply src/components/application_manager/test/policy_handler_test.cc:3047]: @AByzhynar 
Thanks, fixed in:https://github.com/smartdevicelink/sdl_core/pull/3336/commits/19023b6acd3686175ff83e5c6e3ab453c09d6b35

**Comment by SNiukalov** [comment]
@theresalech PR is ready for Livio team review. Thank you.

**Comment by theresalech** [comment]
@SNiukalov thank you!  Is this PR resolving a 6.1 Regression issue, or an existing issue in SDL Core?

**Comment by dboltovskyi** [comment]
@theresalech Please notice this is not a regression issue. However it's related to [0240-sdl-js-pwa](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0240-sdl-js-pwa.md) proposal which is in scope of upcoming release.
We will appreciate if PM be able to review this fix.
