### PR TITLE
Fix/sdl must send generic error hmi doesnt respond during timeout

### LINKED ISSUE #1880: SDL does not send GENERIC_ERROR in case HMI does NOT respond during <DefaultTimeout>+<RPCs_internal_timeout>
**Occurrence: Always** 

# Description
SDL must send GENERIC_ERROR to app in case HMI does NOT respond during DefaultTimeout+2*RPCs_internal_timeout for all RPCs with own timer

## Preconditions
- Core, HMI started.
- App is registered on HMI.
- App is activated.

## Steps to reproduce
1.  SDL transfers *RPC with own timeout from mobile app to HMI 
and HMI does NOT respond during DefaultTimeout+2*RPCs_own_timeout

Script for reproducing: https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1880_DefaultAndRPCTimeoutGENERIC_ERROR.lua

## Actual result
N/A

## Expected result
SDL must respond 'GENERIC_ERROR, success:false' to mobile app

# Environment

# Attachments
Note: Extract attached folder with script to test_scripts folder. 
[Defects.zip](https://github.com/smartdevicelink/sdl_core/files/1512868/Defects.zip)

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [x] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

### LINKED ISSUE #2397: SDL must send GENERIC_ERROR to app in case HMI does NOT respond during <DefaultTimeout>+<RPCs_internal_timeout> for all RPCs with own timer
### Bug Report
SDL must send GENERIC_ERROR to app in case HMI does NOT respond during DefaultTimeout> + RPCs_internal_timeout for all RPCs with own timer

##### Reproduction Steps
1. In case
SDL does NOT receive VR.PerformInteraction_response or OnResetTimeout_notification from HMI
and DefaultTimeout timer is expired

##### Expected Behavior
SDL must:
Send PerformInteraction (GENERIC_ERROR) to mobile app

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

### PR DESCRIPTION
**Pull request by ValeriiMalkov**
Fixes #1880 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
This PR provided bugfix when SDL doesn't respond during `DefaultTimeout`+`RPCs_internal_timeout` for all RPCs with own timer.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/alert_request.cc [hunk 1]
```diff
@@ -74,13 +74,12 @@ AlertRequest::~AlertRequest() {}
...
+  uint32_t request_timeout_ = 0;
   if ((*message_)[strings::msg_params].keyExists(strings::duration)) {
-    default_timeout_ =
+    request_timeout_ =
         (*message_)[strings::msg_params][strings::duration].asUInt();
-  } else {
-    const int32_t def_value = 5000;
-    default_timeout_ = def_value;
   }
+  default_timeout_ = default_timeout_ + request_timeout_;
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/alert_request.cc]: @ValeriiMalkov use +=

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 2]
```diff
@@ -92,7 +93,9 @@ bool PerformInteractionRequest::Init() {
 
   if (mobile_apis::InteractionMode::BOTH == interaction_mode_ ||
       mobile_apis::InteractionMode::MANUAL_ONLY == interaction_mode_) {
-    default_timeout_ *= 2;
+    default_timeout_ = default_timeout_ + (request_timeout_ * 2);
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @ValeriiMalkov use +=

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/scrollable_message_request.cc [hunk 3]
```diff
@@ -65,13 +65,12 @@ ScrollableMessageRequest::~ScrollableMessageRequest() {}
...
+  uint32_t request_timeout_ = 0;
   if ((*message_)[strings::msg_params].keyExists(strings::timeout)) {
-    default_timeout_ =
+    request_timeout_ =
         (*message_)[strings::msg_params][strings::timeout].asUInt();
-  } else {
-    const int32_t def_value = 30000;
-    default_timeout_ = def_value;
   }
+  default_timeout_ = default_timeout_ + request_timeout_;
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/scrollable_message_request.cc]: @ValeriiMalkov use +=

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/alert_request.cc [hunk 4]
```diff
@@ -74,13 +74,12 @@ AlertRequest::~AlertRequest() {}
 bool AlertRequest::Init() {
   /* Timeout in milliseconds.
      If omitted a standard value of 10000 milliseconds is used.*/
+  uint32_t request_timeout_ = 0;
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/alert_request.cc]: @ValeriiMalkov why underscore in loca variables? Please retake this https://github.com/smartdevicelink/sdl_core/wiki/SDL-Coding-Style-Guide

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/alert_request.cc (hunk 1 above)
Comment (ValeriiMalkov) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/alert_request.cc]: @AKalinich-Luxoft Fixed in commit 76a1afadfa7423d3c12719ea6f4e49a302c04395

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc (hunk 2 above)
Comment (ValeriiMalkov) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @AKalinich-Luxoft Fixed in commit 76a1afadfa7423d3c12719ea6f4e49a302c04395

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/scrollable_message_request.cc (hunk 3 above)
Comment (ValeriiMalkov) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/scrollable_message_request.cc]: @AKalinich-Luxoft Fixed in commit 76a1afadfa7423d3c12719ea6f4e49a302c04395

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 5]
```diff
@@ -93,9 +93,9 @@ bool PerformInteractionRequest::Init() {
 
   if (mobile_apis::InteractionMode::BOTH == interaction_mode_ ||
       mobile_apis::InteractionMode::MANUAL_ONLY == interaction_mode_) {
-    default_timeout_ = default_timeout_ + (request_timeout_ * 2);
+    default_timeout_ += request_timeout * 2;
```
Comment (ZhdanovP) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @ValeriiMalkov may be is better to move value 2 to const variable with appropriate name, in order to avoid magic values?

Comment (ValeriiMalkov) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @ZhdanovP See please commit feedf047105e492833c264de6001f8bfdd50943e

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 6]
```diff
@@ -82,8 +82,10 @@ PerformInteractionRequest::~PerformInteractionRequest() {}
 bool PerformInteractionRequest::Init() {
   /* Timeout in milliseconds.
      If omitted a standard value of 10000 milliseconds is used.*/
+  uint32_t request_timeout = 0;
+  const uint32_t increase_value = 2;
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @ValeriiMalkov keep variable setup as close to usage as possible

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/scrollable_message_request.cc [hunk 7]
```diff
@@ -65,13 +65,12 @@ ScrollableMessageRequest::~ScrollableMessageRequest() {}
...
+  uint32_t request_timeout = 0;
   if ((*message_)[strings::msg_params].keyExists(strings::timeout)) {
-    default_timeout_ =
+    request_timeout =
         (*message_)[strings::msg_params][strings::timeout].asUInt();
-  } else {
-    const int32_t def_value = 30000;
-    default_timeout_ = def_value;
   }
+  default_timeout_ += request_timeout;
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/scrollable_message_request.cc]: @ValeriiMalkov I can see that before there was default value 30000. Is it redundant or we have this default value somewhere else?

Comment (LitvinenkoIra) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/scrollable_message_request.cc]: @ValeriiMalkov @LuxoftAKutsan If `timeout `param omitted a standard value of 30000 milliseconds should be used.

Comment (ValeriiMalkov) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/scrollable_message_request.cc]: @LitvinenkoIra @LuxoftAKutsan Standard value gets from `.ini` file which is 10000. I didn't find in req-t value which is 30000.

**Comment by ValeriiMalkov** [comment]
@LitvinenkoIra `Slider` works according the req-t, if timeout is ommited  a standard value of 10000 milliseconds should be used. 

And i tested this implementation via test script `1880_DefaultAndRPCTimeoutGENERIC_ERROR.lua`.
All tests passed. 

And help me please with default timeout in `ScrollableMessageRequest`. Which value is default ? 10000 or 30000.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 8]
```diff
@@ -82,17 +82,18 @@ PerformInteractionRequest::~PerformInteractionRequest() {}
 bool PerformInteractionRequest::Init() {
   /* Timeout in milliseconds.
      If omitted a standard value of 10000 milliseconds is used.*/
-  if ((*message_)[strings::msg_params].keyExists(strings::timeout)) {
-    default_timeout_ =
-        (*message_)[strings::msg_params][strings::timeout].asUInt();
-  }
+  auto& msg_params = (*message_)[strings::msg_params];
+  uint32_t request_timeout = msg_params[strings::timeout].asUInt();
+  const uint32_t increase_value = 2;
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @ValeriiMalkov reduce variable scope

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 9]
```diff
@@ -82,17 +82,18 @@ PerformInteractionRequest::~PerformInteractionRequest() {}
 bool PerformInteractionRequest::Init() {
   /* Timeout in milliseconds.
      If omitted a standard value of 10000 milliseconds is used.*/
-  if ((*message_)[strings::msg_params].keyExists(strings::timeout)) {
-    default_timeout_ =
-        (*message_)[strings::msg_params][strings::timeout].asUInt();
-  }
+  auto& msg_params = (*message_)[strings::msg_params];
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @mau it be const?

**Comment by vkushnirenko-luxoft** [comment]
Rebuild required

**Comment by LitvinenkoIra** [comment]
@LuxoftAKutsan please take a look at the latest updates b672d0996c2ad41b6890c1288d3d46af74423d55
