### PR TITLE
trigger ptu on startup only in proprietary policy mode

### LINKED ISSUE #3396: SDL doesn't start PTU on Days, Ignition Cycles or new Ignition cycle triggers for HTTP policy mode
### Bug Report
After merge of https://github.com/smartdevicelink/sdl_core/pull/3363 SDL does not start PTU sequence for the following triggers in `HTTP` policy mode:
 `1)` Number of ignition cycles (`exchange_after_x_ignition_cycles`)
 `2)` Number of days (`exchange_after_x_days`)
 `3)` New ignition cycle after unsuccessful retry

##### Reproduction Steps
1. Make sure SDL is built in `HTTP` policy mode
2. Start SDL, HMI, connect Mobile device, register application
3. Make sure at least one PTU trigger is in place: `1)`, `2)` or `3)`

##### Expected Behavior
SDL start PTU sequence by sending messages:
 - to HMI: SDL.OnStatusUpdate(UPDATE_NEEDED, UPDATING)
 - to App: OnSystemRequest

##### Observed Behavior
SDL does not start PTU sequence

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (b982ad29b9)
* Testing Against: ATF:
  - [052_ATF_PTU_Trigger_IGN_Cycles_HTTP.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/build_options/052_ATF_PTU_Trigger_IGN_Cycles_HTTP.lua)
  - [053_ATF_Policy_Table_Update_Trigger_After_N_Days_HTTP.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/build_options/053_ATF_Policy_Table_Update_Trigger_After_N_Days_HTTP.lua)
  - [098_ATF_PTU_Unsuccessful_Even_After_Retry_Strategy_HTTP.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/build_options/098_ATF_PTU_Unsuccessful_Even_After_Retry_Strategy_HTTP.lua)

##### Test Case, Sample Code, and / or Example App
 - [052.tar.gz](https://github.com/smartdevicelink/sdl_core/files/4678516/052.tar.gz)
 - [053.tar.gz](https://github.com/smartdevicelink/sdl_core/files/4678520/053.tar.gz)
 - [098.tar.gz](https://github.com/smartdevicelink/sdl_core/files/4678522/098.tar.gz)

### PR DESCRIPTION
**Pull request by iCollin**
Fixes #3396

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
ATF

### Summary
only "triggerPTUonStartup" in proprietary mode

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by AByzhynar** [comment]
@iCollin The root cause of the defect was: `SDL does not start PTU sequence in HTTP mode` and you chagede that it would start it only in `PROPRIETARY`. Is this correct?

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 1]
```diff
@@ -790,7 +790,7 @@ void PolicyHandler::OnSystemRequestReceived() const {
 }
 
 void PolicyHandler::TriggerPTUOnStartupIfRequired() {
-#ifndef EXTERNAL_PROPRIETARY_MODE
+#ifdef PROPRIETARY_MODE
```
Comment (AByzhynar) [inline src/components/application_manager/src/policies/policy_handler.cc:793]: @iCollin The root cause of the defect was: `SDL does not start PTU sequence in HTTP mode` and you changed that it would start it only in `PROPRIETARY`. Is this correct?

**Comment by ShobhitAd** [comment]
> @iCollin The root cause of the defect was: `SDL does not start PTU sequence in HTTP mode` and you changed that it would start it only in `PROPRIETARY`. Is this correct?

@AByzhynar Yes, thank you for noticing. It is difficult to understand because https://github.com/smartdevicelink/sdl_core/issues/3279 was related to multiple different PRs - the first fix PR(https://github.com/smartdevicelink/sdl_core/pull/3280) is related to the KMS trigger. The second fix PR(https://github.com/smartdevicelink/sdl_core/pull/3294) is related to the Ignition and DaysAfter triggers. The third PR (https://github.com/smartdevicelink/sdl_core/pull/3363) fixes the same issue as the second PR(which  seems to have been broken by other Policy fixes before the release).

PR #3363 was meant to address the following issue:

In regular policy mode, days and ignition cycles triggers are not checked when core starts up. 
This is because, before this PR was merged, `PolicyManagerImpl::CheckTriggers()` was only called after an app was registered rather than being called on startup (when the HMI has finished initializing). The PR added a `TriggerPTUOnStartupIfRequired` function to check the PTU triggers on HMIInit and start a PTU if required.

**Comment by ShobhitAd** [comment]
@iCollin While this does limit the #3363 fix to only work for PROPRIETARY policy mode, the PTU trigger check for Ignition cycles and days after won't work if there are no apps registered. Which means the "HMI PTU trigger with no apps" test cases for ignition cycles and daysAfter would fail for HTTP_POLICY mode. Is that a restriction we want to make?

**Comment by ShobhitAd** [comment]
> @iCollin While this does limit the #3363 fix to only work for PROPRIETARY policy mode, the PTU trigger check for Ignition cycles and days after won't work if there are no apps registered. Which means the "HMI PTU trigger with no apps" test cases for ignition cycles and daysAfter would fail for HTTP_POLICY mode. Is that a restriction we want to make?

It looks like HTTP policy mode does not rely on the HMI at all for the PTU process. In which case, the HMI PTU tests wouldn't apply for this policy mode. It should be fine then to restrict the #3363 fix to only work for PROPRIETARY policy mode
