### PR TITLE
Fix build with EXTERNAL PROPRIETARY policy flag

### LINKED ISSUE #2265: Build with EXTERNAL PROPRIETARY policy flag
### Bug Report
Develop branch **does not build** with EXTERNAL PROPRIETARY policy flag

commit: aaadc90

### PR DESCRIPTION
**Pull request by LitvinenkoIra**
Fixes #2265 

Update OnAllowSDLFunctionalityNotification function for EXTERNAL PROPRIETARY policy in accordance with the Feature/mobile projection 2 

This PR is **[ready]** for review.

#### Risk
This PR makes **[no]** API changes.

- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 1]
```diff
@@ -1250,12 +1250,15 @@ void PolicyHandler::OnAllowSDLFunctionalityNotification(
     if (is_allowed) {
       // Send HMI status notification to mobile
       // Put application in full
-      AudioStreamingState::eType state = app->is_audio()
+      AudioStreamingState::eType audio_state = app->IsAudioApplication()
```
Comment (EKuliiev) [inline src/components/application_manager/src/policies/policy_handler.cc]: @LitvinenkoIra would be nice to add **const** AudioStreamingState::eType audio_state = ...

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 2]
```diff
@@ -1250,12 +1250,15 @@ void PolicyHandler::OnAllowSDLFunctionalityNotification(
...
                                              ? AudioStreamingState::AUDIBLE
                                              : AudioStreamingState::NOT_AUDIBLE;
+      VideoStreamingState::eType video_state = app->IsVideoApplication()
```
Comment (EKuliiev) [inline src/components/application_manager/src/policies/policy_handler.cc]: @LitvinenkoIra would be nice to add **const** VideoStreamingState::eType video_state = app->IsVideoApplication() = ...
and then check_style.sh --fix
