### PR TITLE
Make usage logger stabilization

### LINKED ISSUE #2976: SDL does not send OnSDLClose notification by switching off with reason IGNITION_OFF
### Bug Report
SDL does not send OnSDLClose notification by switching off with reason IGNITION_OFF

##### Occurrence: 
Sometimes

##### Preconditions
1. SDL and HMI are started.
2. Mobile application is registered.

##### Reproduction Steps
1. Perform IGNITION_OFF (send BasicCommunication.OnExitAllApplications with reason = "IGNITION_OFF")

##### Expected Behavior
SDL sends OnSDLClose notification to HMI

##### Observed Behavior
SDL does not send OnSDLClose notification to HMI

##### OS & Version Information
* OS/Version: Ubuntu 16.04 amd64
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop
* ATF: https://github.com/smartdevicelink/sdl_atf/tree/develop

##### Test Case, Sample Code, and / or Example App
Test script: 
https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Smoke/ShutDown/001_ShutDown_IGNITION_OFF.lua

### PR DESCRIPTION
**Pull request by SNiukalov**
Fixes #2976

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
ATF script:
https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Smoke/ShutDown/001_ShutDown_IGNITION_OFF.lua

### Summary
Added custom deleter for logger
Added flush logger during each handle deleting
Added deleting logger thread during destroy each plugin
This changes are necessary to avoid deadlock during work with log4cxx.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/plugin_manager/rpc_plugin_manager_impl.cc [hunk 1]
```diff
@@ -77,6 +77,7 @@ RPCPluginManagerImpl::RPCPluginPtr RPCPluginManagerImpl::LoadPlugin(
   auto plugin_destroyer = [delete_plugin, plugin_dll](RPCPlugin* plugin) {
     LOG4CXX_DEBUG(logger_, "Delete plugin " << plugin->PluginName());
     delete_plugin(plugin);
+    DELETE_LOGGER();
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/src/plugin_manager/rpc_plugin_manager_impl.cc]: @SNiukalov why do you need to destroy logger on each plugin delete? Is there some relation? And which exactly instance of logger will be deleted?

File: src/components/utils/src/push_log.cc [hunk 2]
```diff
@@ -41,7 +41,24 @@ struct __attribute__((visibility("default"))) LogsEnabled {
...
+template <typename T>
+using logger_ptr = std::unique_ptr<T, std::function<void(T*)> >;
+
+static logger_ptr<LogMessageLoopThread> log_message_loop_thread;
+
+auto deinit_logger = [](LogMessageLoopThread* logMsgThread) {
+  delete logMsgThread;
+  logger::logger_status = logger::LoggerThreadNotCreated;
+
+  log4cxx::LoggerPtr logger(log4cxx::Logger::getLogger("Utils"));
```
Comment (AKalinich-Luxoft) [inline src/components/utils/src/push_log.cc]: @SNiukalov why utils? Maybe it's possible to get a logger ptr from input parameter `logMsgThread`? It might be any logger

Comment (SNiukalov) [reply src/components/utils/src/push_log.cc]: @AKalinich-Luxoft 
Hi, thanks to question I will try explain.

Each plugin has its own logger object, which is created when the plugin is loaded, this logger object must be deleted when the plugin is closed.
Removing logger  occurs in the address space of the plugin
In this case, the plugin only has access to its own logger.

Utils, because, this component is statically linked to the plug-in and is responsible for the log

File: src/components/include/utils/logger.h [hunk 3]
```diff
@@ -141,6 +143,8 @@ log4cxx_time_t time_now();
 
 #define DEINIT_LOGGER()
 
+#define DELETE_LOGGER()
```
Comment (LuxoftAKutsan) [inline src/components/include/utils/logger.h]: @SNiukalov  please add some description to this macro

**Comment by SNiukalov** [comment]
@AKalinich-Luxoft 
Remove ambiguity: https://github.com/smartdevicelink/sdl_core/pull/3022/commits/5a80841027eab4f87907ee3b7d98086cff8c40b9

File: src/components/include/utils/logger.h (hunk 3 above)
Comment (SNiukalov) [reply src/components/include/utils/logger.h]: @LuxoftAKutsan 
Fixed in:https://github.com/smartdevicelink/sdl_core/pull/3022/commits/5b3242f2ab66d30ea0c5b71bad649e3dabccb516

File: src/components/policy/policy_regular/src/policy_manager_impl.cc [hunk 4]
```diff
@@ -1813,3 +1804,13 @@ const std::vector<std::string> PolicyManagerImpl::GetRPCsForFunctionGroup(
...
+
+__attribute__((visibility("default"))) policy::PolicyManager* CreateManager() {
+  return new policy::PolicyManagerImpl();
+}
+
+__attribute__((visibility("default"))) void DeleteManager(
+    policy::PolicyManager* pm) {
+  delete pm;
+  DELETE_THREAD_LOGGER(policy::logger_);
+}
```
Comment (ZhdanovP) [inline src/components/policy/policy_regular/src/policy_manager_impl.cc]: @SNiukalov end of file?

Comment (SNiukalov) [reply src/components/policy/policy_regular/src/policy_manager_impl.cc]: @ZhdanovP  Thanks, fixed.

**Comment by SNiukalov** [comment]
@theresalech PR is ready for Livio team review. Thank you.
