### PR TITLE
Fix handling of RC.SetGlobalProperties response

### LINKED ISSUE #3668: SDL response with "GENERIC_ERROR" in case request ResetGlobalProperties ("USER_LOCATION")
### Bug Report
SDL response with "GENERIC_ERROR" in case request ResetGlobalProperties ("USER_LOCATION")

#### Precondition:
    1. Start SDL and HMI.
    2. Connect mobile device via any transport.
    3. Mobile application is registered and activated.
    4. Mobile application successfully sends SetGlobalProperties with userLocation parameter
     SetGlobalProperties { "userLocation":{"grid": {"col":2, "level":2,"row":2, "colspan":1,"levelspan":1, "rowspan":1 }

##### Reproduction Steps
1. Send ResetGlobalProperties with "USER_LOCATION"
App→SDL: ResetGlobalProperties (USER_LOCATION)

##### Expected Behavior
SDL sends RC.SetGlobalProperties request with default driver seat location properties to HMI
SDL→HMI: RC.SetGlobalProperties (
{ "userLocation":{"grid":{"col":0, "level":0,"row":0, "colspan":1,"levelspan":1, "rowspan":1 }}} 
HMI→SDL: RC.SetGlobalProperties ( SUCCESS )
SDL→App: ResetGlobalProperties( "success":true, resultCode":"SUCCESS" )

##### Observed Behavior
SDL→App: ResetGlobalProperties( "success":false , "resultCode":"GENERIC_ERROR")

##### SDL_logs:
[SDL_Log.zip](https://github.com/smartdevicelink/sdl_core/files/6162715/SDL_Log.zip)

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (c9fc559)
* Testing Against: HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (41c804d), SPT: SPT: 20210305-Android (1076)

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #3668 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Can be reproduced manually:
- Send ResetGlobalProperties with "USER_LOCATION"
- App→SDL: ResetGlobalProperties (USER_LOCATION)

**Expected Behavior**
SDL sends RC.SetGlobalProperties request with default driver seat location properties to HMI
SDL→HMI: RC.SetGlobalProperties (
{ "userLocation":{"grid":{"col":0, "level":0,"row":0, "colspan":1,"levelspan":1, "rowspan":1 }}}
HMI→SDL: RC.SetGlobalProperties ( SUCCESS )
SDL→App: ResetGlobalProperties( "success":true, resultCode":"SUCCESS" )

**Observed Behavior**
SDL→App: ResetGlobalProperties( "success":false , "resultCode":"GENERIC_ERROR")

### Summary
SDL sends `RC.SetGlobalProperties` request to HMI, however does not process a response from HMI. There was added processing of RC part of the request and covered by new unit test to fix that.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by ShobhitAd — CHANGES_REQUESTED** [review]

File: src/components/application_manager/include/application_manager/commands/command_request_impl.h [hunk 1]
```diff
@@ -273,6 +273,22 @@ class CommandRequestImpl : public CommandImpl,
   bool PrepareResultForMobileResponse(ResponseInfo& out_first,
                                       ResponseInfo& out_second) const;
 
+  /**
+   * @brief Checks result code from HMI for splitted RPC
+   * and returns parameter for sending to mobile app.
+   * @param first contains result_code from HMI response and
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/application_manager/include/application_manager/commands/command_request_impl.h]: @ShobhitAd applied in https://github.com/smartdevicelink/sdl_core/pull/3741/commits/6a711c722aee888166c2436b79cf068a9f6ca926

File: src/components/application_manager/include/application_manager/commands/command_request_impl.h [hunk 2]
```diff
@@ -273,6 +273,22 @@ class CommandRequestImpl : public CommandImpl,
...
+   * interface that returns response
+   * @param second contains result_code from HMI response and
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/application_manager/include/application_manager/commands/command_request_impl.h]: @ShobhitAd applied in https://github.com/smartdevicelink/sdl_core/pull/3741/commits/6a711c722aee888166c2436b79cf068a9f6ca926

File: src/components/application_manager/include/application_manager/commands/command_request_impl.h [hunk 3]
```diff
@@ -273,6 +273,22 @@ class CommandRequestImpl : public CommandImpl,
...
+   * interface that returns response
+   * * @param third contains result_code from HMI response and
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/application_manager/include/application_manager/commands/command_request_impl.h]: @ShobhitAd applied in https://github.com/smartdevicelink/sdl_core/pull/3741/commits/6a711c722aee888166c2436b79cf068a9f6ca926

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/reset_global_properties_request.cc [hunk 4]
```diff
@@ -146,6 +147,14 @@ void ResetGlobalPropertiesRequest::on_event(const event_engine::Event& event) {
       GetInfo(message, tts_response_info_);
       break;
     }
+    case hmi_apis::FunctionID::RC_SetGlobalProperties: {
+      SDL_LOG_INFO("Received RC_SetGlobalProperties event");
```
Comment (ShobhitAd) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/reset_global_properties_request.cc:151]: This event is not triggered in the case of multiple properties being reset. For example
1. Sending SetGlobalProperties request with `userLocation`, `helpPrompt` and `menuTitle`
2. Sending ResetGlobalProperties request with `properties` {USER_LOCATION, HELPPROMPT, MENUNAME}

**Review by ShobhitAd — CHANGES_REQUESTED** [review]

**Comment by jordynmackool** [comment]
@AKalinich-Luxoft please see review feedback from Shobhit above. Thanks!

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/reset_global_properties_request.cc (hunk 4 above)
Comment (AKalinich-Luxoft) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/reset_global_properties_request.cc:151]: @ShobhitAd we were not able to reproduce this test case. Attached is the ATF script which we used: [3668_App_resets_UserLocation_HelpPrompt_MenuTitle.zip](https://github.com/smartdevicelink/sdl_core/files/6889260/3668_App_resets_UserLocation_HelpPrompt_MenuTitle.zip)

And here is the logs: [2021-07-27_09-58-59.097_3668.tar.gz](https://github.com/smartdevicelink/sdl_core/files/6889264/2021-07-27_09-58-59.097_3668.tar.gz)

As you can see, SDL is properly triggering RC events and handles them in `on_event()`.

Could you please provide your steps on how to reproduce the issue you are currently observing?

Comment (ShobhitAd) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/reset_global_properties_request.cc:151]: @AKalinich-Luxoft my reproduction steps are similar to those of the attached ATF test. However, the problem with this test case is that since the **UI** and **TTS** reset responses are successful the overall response (based on how the results are combined) to mobile will also be successful, regardless of the result of **RC** response.

Looking at the attached SmartDeviceLinkCore log file, when I searched for `commands::ResetGlobalPropertiesRequest::on_event: Received` I was only seeing two results - one for the "UI_SetGlobalProperties event" and the other for "TTS_SetGlobalProperties event".

I tried modifying the ATF test to check the case where **UI** and **TTS** return `UNSUPPORTED_RESOURCE` responses and **RC** returns a SUCCESS response and the test fails in this case. Here are the logs for the modified test
[UNSUPPORTED_RESOURCE_test.zip](https://github.com/smartdevicelink/sdl_core/files/6896609/UNSUPPORTED_RESOURCE_test.zip)

Comment (dboltovskyi) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/reset_global_properties_request.cc:151]: @ShobhitAd Thank you for your explanation. Good catch. We've extended test coverage in https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2534/commits/abb2e314ce21df8b2cbb00005360f1d54d4481f6 Script `3` is failing now by the reason you described.

Comment (AKalinich-Luxoft) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/reset_global_properties_request.cc:151]: @ShobhitAd this issue is fixed in https://github.com/smartdevicelink/sdl_core/pull/3741/commits/d70d992c7de3752991d99f29451252cda4c4e45f
New ATF script is passed with the new changes done

**Review by ShobhitAd — APPROVED** [review]
