### PR TITLE
Use atomic bool in ApplicationManager

### LINKED ISSUE #3182: CCB: Use atomic bool in ApplicatinManager
### Bug Report
Deadlock inside class "ApplicationManagerImpl"

### Detailed analysis:
Deadlock happens because of using two mutexes for one critical section
inside classes "ApplicationManagerImpl" and "ResumeCtrlImpl".
We are trying to lock one section by different mutexes.
Resolving, by copy set of applications into temporary set and use it
instead of guarded app set which returns by function 'applications()'.
Use atomic bool for flag 'is_stopping_' in class 'ApplicationManagerImpl', remove mutex 'stopping_application_mng_lock_' which needed for guarding of i's_stopping_'.

##### Reproduction Steps
1. TBD

##### Expected Behavior
SDL should not crash

##### Observed Behavior
SDL crashed

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #3182 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Covered by unit tests

### Summary
Replace bool flag 'is_stopping_' in class ApplicationManagerImpl and remove mutex 'stopping_application_mng_lock_'.

### Tasks Remaining:
- [x] Test this fix

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by LuxoftAKutsan — APPROVED** [review]

File: src/components/application_manager/src/application_manager_impl.cc [hunk 1]
```diff
@@ -229,7 +229,7 @@ ApplicationManagerImpl::ApplicationManagerImpl(
 ApplicationManagerImpl::~ApplicationManagerImpl() {
   SDL_LOG_AUTO_TRACE();
 
-  is_stopping_ = true;
+  is_stopping_.exchange(true);
```
Comment (YarikMamykin) [inline src/components/application_manager/src/application_manager_impl.cc:232]: Why using `exchange` instead of `store`?
I think `exchange` could be more suitable in case we wanted to save previous value of `is_stopping_` variable.

**Review by YarikMamykin — CHANGES_REQUESTED** [review]

File: src/components/application_manager/src/application_manager_impl.cc (hunk 1 above)
Comment (AKalinich-Luxoft) [reply src/components/application_manager/src/application_manager_impl.cc]: @YarikMamykin actually, just moved a fix without any changes. However I agree that `store` is more applicable in that case. Replaced in https://github.com/smartdevicelink/sdl_core/pull/3491/commits/8209b59b0d52b22d82ab243a7c0d631de55bd662

**Review by YarikMamykin — APPROVED** [review]

**Review by SNiukalov — APPROVED** [review]
