### PR TITLE
SDL restores AddCommands in the order they were created

### LINKED ISSUE #1878: CCB: SDL restores AddCommands in the order they were created
### Bug Report
SDL must restore AddCommands in the same order as they were created by mobile app

##### Reproduction Steps
1.  App successfully added some AddCommands (UI+VR, only UI, only VR)
2.  Ignition Off -> Ignition On
3.  App registers -> SDL successfully performs HMILevel resumption and data resumption 

##### Expected Behavior
The order of resumed AddCommands must be the same as order being before resumption.
- SDL must generate <internal_consecutiveNumber>
- assign this <internal_consecutiveNumber> to each AddCommand requested by app,
- restore AddCommand by this <internal_consecutiveNumber> during data resumption (meaning: SDL must send UI.AddCommands to HMI by <internal_consecutiveNumber> one by one from resumption list)

##### Observed Behavior
The order of resumed AddCommands is different from order being before resumption 

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: [develop](https://github.com/smartdevicelink/sdl_core/commit/d36316738785c96dab2ee892762ed08c059fffde)
* Testing Against: ATF

### PR DESCRIPTION
**Pull request by APipko**
Fixes #1878 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
SDL generates and assigns internal_id for each AddCommand from mobile app
and restores AddCommands by this internal_id

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/message_helper/message_helper.cc [hunk 1]
```diff
@@ -1319,7 +1319,12 @@ smart_objects::SmartObjectList MessageHelper::CreateAddCommandRequestToHMI(
 
       smart_objects::SmartObject msg_params =
           smart_objects::SmartObject(smart_objects::SmartType_Map);
-      msg_params[strings::cmd_id] = i->first;
+
+      if ((*i->second).keyExists(strings::cmd_id)) {
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/src/message_helper/message_helper.cc]: @APipko `cmd_id` is a mandatory parameter for AddCommand, so if it is missing then whole request will be invalid anyway. I suggest do not return such request from this function at all.

File: src/components/application_manager/test/message_helper/message_helper_test.cc [hunk 2]
```diff
@@ -279,8 +279,9 @@ TEST(MessageHelperTestCreate,
   object[strings::menu_params] = 1;
   object[strings::cmd_icon] = 1;
   object[strings::cmd_icon][strings::value] = "10";
+  object[strings::cmd_id] = 5;
 
-  vis.insert(std::pair<uint32_t, smart_objects::SmartObject*>(5, &object));
+  vis.insert(std::pair<uint32_t, smart_objects::SmartObject*>(1, &object));
```
Comment (BSolonenko) [inline src/components/application_manager/test/message_helper/message_helper_test.cc]: @APipko What is this magic number 1?

File: src/components/application_manager/test/resumption/resume_ctrl_test.cc [hunk 3]
```diff
@@ -355,7 +355,7 @@ TEST_F(ResumeCtrlTest, StartResumption_AppWithCommands) {
       .WillByDefault(ReturnRef(*mock_help_prompt_manager_));
 
   for (uint32_t i = 0; i < count_of_commands; ++i) {
-    EXPECT_CALL(*mock_app_, AddCommand(i, test_application_commands[i]));
+    EXPECT_CALL(*mock_app_, AddCommand(i + 1, test_application_commands[i]));
```
Comment (BSolonenko) [inline src/components/application_manager/test/resumption/resume_ctrl_test.cc]: @APipko  Maybe it's better to use `cmd_num` instead of `i` and `internal_id` instead of `i + 1`, as you do in `resume_ctrl_impl.cc` ?

File: src/components/application_manager/test/message_helper/message_helper_test.cc (hunk 2 above)
Comment (BSolonenko) [inline src/components/application_manager/test/message_helper/message_helper_test.cc]: @APipko  What is this magic number `1`?

**Comment by APipko** [comment]
@AKalinich-Luxoft , @BSolonenko fixed

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/add_command_request.h [hunk 4]
```diff
@@ -142,6 +142,15 @@ class AddCommandRequest : public app_mngr::commands::CommandRequestImpl {
    */
   bool IsWhiteSpaceExist();
 
+  /**
+   * @brief Calculates command`s internal consecutive number used during
+   * resumption. This method is called when we add a new command.
+   * @param[in] app Application for wich a consecutive number is calculated
+   * @return internal consecutive number
+   */
+  uint32_t CalcAppInternalConsecutiveNumber(
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/add_command_request.h]: @APipko Description does not match function name

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/add_command_request.h [hunk 5]
```diff
@@ -142,6 +142,15 @@ class AddCommandRequest : public app_mngr::commands::CommandRequestImpl {
    */
   bool IsWhiteSpaceExist();
 
+  /**
+   * @brief Calculates command`s internal consecutive number used during
+   * resumption. This method is called when we add a new command.
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/add_command_request.h]: @APipko Who is `we` ?

File: src/components/application_manager/src/application_data_impl.cc [hunk 6]
```diff
@@ -39,6 +39,25 @@
 namespace application_manager {
 CREATE_LOGGERPTR_GLOBAL(logger_, "ApplicationManager")
 
+namespace {
+struct CommandIdComparator {
+  CommandIdComparator(const std::string& key, uint32_t id)
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_data_impl.cc]: @APipko Why `id` is non-const?

File: src/components/application_manager/src/resumption/resume_ctrl_impl.cc [hunk 7]
```diff
@@ -622,15 +622,18 @@ void ResumeCtrlImpl::AddCommands(ApplicationSharedPtr application,
   if (saved_app.keyExists(strings::application_commands)) {
     const smart_objects::SmartObject& app_commands =
         saved_app[strings::application_commands];
-    for (size_t i = 0; i < app_commands.length(); ++i) {
-      const smart_objects::SmartObject& command = app_commands[i];
+
+    uint32_t internal_id = 1;
```
Comment (AByzhynar) [inline src/components/application_manager/src/resumption/resume_ctrl_impl.cc]: @APipko magic number? At least leave a comment why it is 1. In such cases it is better to use const named variables.

File: src/components/application_manager/test/message_helper/message_helper_test.cc [hunk 8]
```diff
@@ -276,14 +276,21 @@ TEST(MessageHelperTestCreate,
 
   smart_objects::SmartObject& object = *smartObjectPtr;
 
+  uint64_t app_id = 1;
```
Comment (AByzhynar) [inline src/components/application_manager/test/message_helper/message_helper_test.cc]: @APipko Why do you use somewhere 64bit values and in other place 32bit? Also please don't use implicit conversions. If type is unsigned - add `u` postfix to initial value

File: src/components/application_manager/test/message_helper/message_helper_test.cc [hunk 9]
```diff
@@ -276,14 +276,21 @@ TEST(MessageHelperTestCreate,
...
+  std::string cmd_icon_value = "10";
+  int64_t cmd_id = 5;
+  uint32_t internal_id = 1;
```
Comment (AByzhynar) [inline src/components/application_manager/test/message_helper/message_helper_test.cc]: @APipko Why these values are non-const?

Comment (APipko) [reply src/components/application_manager/test/message_helper/message_helper_test.cc]: @AByzhynar fixed in 360382e6f413851ab2931500eee7f46130872c7b

File: src/components/application_manager/src/commands/command_impl.cc [hunk 10]
```diff
@@ -214,5 +214,21 @@ DEPRECATED void CommandImpl::ReplaceHMIByMobileAppId(
   }
 }
 
+// static
```
Comment (AByzhynar) [inline src/components/application_manager/src/commands/command_impl.cc]: @APipko What is this comment here for?

File: src/components/application_manager/src/resumption/resume_ctrl_impl.cc [hunk 11]
```diff
@@ -623,13 +623,14 @@ void ResumeCtrlImpl::AddCommands(ApplicationSharedPtr application,
     const smart_objects::SmartObject& app_commands =
         saved_app[strings::application_commands];
 
-    uint32_t internal_id = 1;
-    for (size_t cmd_num = 0; cmd_num < app_commands.length();
-         ++cmd_num, ++internal_id) {
+    for (size_t cmd_num = 0; cmd_num < app_commands.length(); ++cmd_num) {
```
Comment (AByzhynar) [inline src/components/application_manager/src/resumption/resume_ctrl_impl.cc]: @APipko May we use here `for (auto cmd: app_commands) {  const smart_objects::SmartObject& command = cmd...)`? I mean C++ 11 loops.

File: src/components/application_manager/test/resumption/resume_ctrl_test.cc [hunk 12]
```diff
@@ -354,10 +354,31 @@ TEST_F(ResumeCtrlTest, StartResumption_AppWithCommands) {
   ON_CALL(*mock_app_, help_prompt_manager())
       .WillByDefault(ReturnRef(*mock_help_prompt_manager_));
 
-  for (uint32_t cmd_id = 0, internal_id = 1; cmd_id < count_of_commands;
+  std::vector<application_manager::CommandsMap> command_vec;
+  for (uint32_t count = 0u; count <= count_of_commands; ++count) {
+    command_vec.emplace_back();
```
Comment (AByzhynar) [inline src/components/application_manager/test/resumption/resume_ctrl_test.cc]: @APipko Why do you need to call this function every  iteration? Can you use vector:reserve once instead? Use C++11 loops please

File: src/components/application_manager/src/commands/command_impl.cc (hunk 10 above)
Comment (APipko) [reply src/components/application_manager/src/commands/command_impl.cc]: @AByzhynar This comment is the notice about static method, like for another static methods in sdl_core

File: src/components/application_manager/src/resumption/resume_ctrl_impl.cc (hunk 11 above)
Comment (KVGrygoriev) [reply src/components/application_manager/src/resumption/resume_ctrl_impl.cc]: @AByzhynar if she makes change it according C++11 loops, Livio might treats it like refactoring and will decline this PR.

File: src/components/application_manager/src/commands/command_impl.cc (hunk 10 above)
Comment (EKuliiev) [reply src/components/application_manager/src/commands/command_impl.cc]: @APipko as for me '// static' is redundant comment.

File: src/components/application_manager/src/resumption/resume_ctrl_impl.cc (hunk 11 above)
Comment (EKuliiev) [reply src/components/application_manager/src/resumption/resume_ctrl_impl.cc]: @KVGrygoriev , in this case the fragment of code already changed.
Refactoring in this PR, for example fixing namespaces
https://github.com/smartdevicelink/sdl_core/pull/2515/files#diff-15145cb256e32e52eee68267f0001477R167
And as for me should be moved to separate commit.

File: src/components/application_manager/src/commands/command_impl.cc [hunk 13]
```diff
@@ -214,5 +214,21 @@ DEPRECATED void CommandImpl::ReplaceHMIByMobileAppId(
...
+uint32_t CommandImpl::CalcCommandInternalConsecutiveNumber(
+    ApplicationConstSharedPtr app) {
+  LOG4CXX_AUTO_TRACE(logger_);
+  const DataAccessor<CommandsMap> accessor = app->commands_map();
+  const CommandsMap& commands = accessor.GetData();
+
+  uint32_t last_command_number = 0u;
+  if (!commands.empty()) {
+    CommandsMap::const_reverse_iterator commands_it = commands.rbegin();
```
Comment (EKuliiev) [inline src/components/application_manager/src/commands/command_impl.cc]: @APipko may be simplified to 
last_command_number = commands.rbegin()->first;

File: src/components/application_manager/src/resumption/resume_ctrl_impl.cc (hunk 11 above)
Comment (APipko) [reply src/components/application_manager/src/resumption/resume_ctrl_impl.cc]: @AByzhynar I can't use C++11 loop here because app_commands is SmartObject instance and doesn't have methods begin(), end()

File: src/components/application_manager/src/commands/command_impl.cc (hunk 10 above)
Comment (APipko) [reply src/components/application_manager/src/commands/command_impl.cc]: @AByzhynar fixed in 6057cfc3c4a9f31c19569f7f6b335e0077921d65

File: src/components/application_manager/src/application_data_impl.cc [hunk 14]
```diff
@@ -483,28 +502,53 @@ void DynamicApplicationDataImpl::SetGlobalProperties(
...
 }
 
 smart_objects::SmartObject* DynamicApplicationDataImpl::FindCommand(
-    uint32_t cmd_id) {
+    const uint32_t cmd_id) {
   sync_primitives::AutoLock lock(commands_lock_ptr_);
-  CommandsMap::const_iterator it = commands_.find(cmd_id);
+
+  CommandIdComparator is_id_equal(strings::cmd_id, cmd_id);
+  CommandsMap::const_iterator it =
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/application_data_impl.cc]: @APipko can you use auto to keep it in one line?

**Comment by LitvinenkoIra** [comment]
Rebased to the latest develop (e137556)

**Comment by LitvinenkoIra** [comment]
Rebased to the latest develop (e137556)

**Comment by IGapchuk** [comment]
Rebased to the lates develop (49c29364460faa527bc758d0fd6b108463f8d82d)

**Comment by LitvinenkoIra** [comment]
@theresalech This PR is ready for Livio review

File: src/components/application_manager/src/message_helper/message_helper.cc [hunk 15]
```diff
@@ -1434,7 +1434,13 @@ smart_objects::SmartObjectList MessageHelper::CreateAddCommandRequestToHMI(
...
+        msg_params[strings::cmd_id] = (*i->second)[strings::cmd_id].asUInt();
+      } else {
+        LOG4CXX_ERROR(logger_, "Command ID is missing.");
+        return requests;
```
Comment (iCollin) [inline src/components/application_manager/src/message_helper/message_helper.cc]: What about the rest of the commands?

```suggestion
        continue;
```

Comment (ydementieiev) [reply src/components/application_manager/src/message_helper/message_helper.cc]: @iCollin fix in [641713c](https://github.com/smartdevicelink/sdl_core/pull/2515/commits/641713c8103e6dac7314734aaed2bd714bdf189f)
