### PR TITLE
Fix the SDL incorrect validates display_capabilities.

### LINKED ISSUE #3113: SDL doesn't populate displayCapabilities in RAI response with default values if HMI doesn't provide UI.GetCapabilities
### Bug Report
SDL doesn't populate `displayCapabilities` in RAI response with default values if HMI doesn't provide UI.GetCapabilities

##### Reproduction Steps
1. Start SDL, Web-HMI, 
Make sure Web-HMI doesn't not provide `UI.GetCapabilities` response to SDL
2. Connect Mobile device and register new application
```
App->SDL: RegisterAppInterface(...) request
SDL->App: RegisterAppInterface(...) response
```

##### Expected Behavior
SDL populates `displayCapabilities` in RAI response with default ones (defined in `hmi_capabilities.json`)

##### Observed Behavior
SDL doesn't provide `displayCapabilities` in RAI response

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/release/6.0.0 (4d283e6)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
  - Script: [GH-3113.lua.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3809648/GH-3113.lua.tar.gz)
  - Reports and logs: [2019-11-05_10-13-28.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3809650/2019-11-05_10-13-28.tar.gz)

### PR DESCRIPTION
**Pull request by IGapchuk**
Fixes #3113 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
There is the issue when SDL incorrect validates display capabilities as a Smart Object. The route cause of the issue is the missed `"alertIcon"` parameter in  the `<string value, hmi_apis::Common_ImageFieldName::eType>` mapping. During validation, a Smart Object SDL can't find mandatory parameter and fail validation. As a result, SDL doesn't set display capabilities into the HMI capabilities entity.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/hmi_capabilities_impl.cc [hunk 1]
```diff
@@ -339,6 +339,8 @@ void InitCapabilities() {
   image_field_name_enum.insert(
       std::make_pair(std::string("locationImage"),
                      hmi_apis::Common_ImageFieldName::locationImage));
+  image_field_name_enum.insert(std::make_pair(
```
Comment (AByzhynar) [inline src/components/application_manager/src/hmi_capabilities_impl.cc]: @IGapchuk Check coding style please. As I can see your line is different than the others in the file

Comment (IGapchuk) [reply src/components/application_manager/src/hmi_capabilities_impl.cc]: @AByzhynar It's not a coding style formatting issue. Coding style formatting is right. It looks like that , because `"alertIcon"` and `hmi_apis::Common_ImageFieldName::alertIcon` lexemes are shorter that `"locationImage"` and `hmi_apis::Common_ImageFieldName::locationImage`.

**Comment by IGapchuk** [comment]
@theresalech Please notice, PR passed internal Luxoft code review and ready for Livio team review. Please, tale a look.

**Comment by theresalech** [comment]
@IGapchuk thank you.  We are currently working on finalizing the roadmap with the Steering Committee, so will keep these in consideration for upcoming Core releases.
