### PR TITLE
fixup! remove struct timeval and use boost time_duration instead

### LINKED ISSUE #2403: Build with EXTERNAL PROPRIETARY policy flag
### Bug Report
Develop branch **does not build** with EXTERNAL PROPRIETARY policy flag

commit:  734fb7d

### PR DESCRIPTION
**Pull request by LitvinenkoIra**
Fixes #2403 

This PR is **[ready]** for review.

### Risk
This PR makes **[no]** API changes.

### Summary
Add missing changes regarding using boost time_duration instead of timeval struct 

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/policy/policy_external/test/policy_manager_impl_ptu_test.cc [hunk 1]
```diff
@@ -926,7 +926,7 @@ TEST_F(
 uint32_t GetCurrentDaysCount() {
   date_time::TimeDuration current_time = date_time::getCurrentTime();
   const uint32_t kSecondsInDay = 60 * 60 * 24;
-  return current_time.tv_sec / kSecondsInDay;
+  return date_time::getSecs(current_time) / kSecondsInDay;
```
Comment (ZhdanovP) [inline src/components/policy/policy_external/test/policy_manager_impl_ptu_test.cc]: @LitvinenkoIra May be is better to move `date_time::getSecs(current_time)` in separate const variable?

Comment (KVGrygoriev) [reply src/components/policy/policy_external/test/policy_manager_impl_ptu_test.cc]: @ZhdanovP Could you give some arguments for this?

Comment (ZhdanovP) [reply src/components/policy/policy_external/test/policy_manager_impl_ptu_test.cc]: @KVGrygoriev I see it useful during debug

Comment (ZhdanovP) [reply src/components/policy/policy_external/test/policy_manager_impl_ptu_test.cc]: @KVGrygoriev Exactly, ok, closed =)
