### PR TITLE
Fix resumption for menuLayout global property

### LINKED ISSUE #3541: Resumption for menuLayout does not occur within SetGlobalProperties, AddSubMenu RPCs
### Bug Report
Resumption for `menuLayout` does not occur

##### Preconditions
1. SDL and HMI are started
2. Mobile app is registered and activated
3. Mobile app requests `SetGlobalProperties`/`AddSubMenu` with all mandatory params and `menuLayout`
4. `SetGlobalProperties` is set successfully/`AddSubMenu` is added successfully

##### Reproduction Steps
1. Perform Ignition off and ignition on/ transport reconnect
2. Mobile app registers with actual hashID 

##### Expected Behavior
SDL resumes `SetGlobalProperties`/`AddSubMenu`  with the same data added by the app

##### Observed Behavior
SDL resumes `SetGlobalProperties`/`AddSubMenu` without `menuLayout`

##### OS & Version Information
* OS/Version: 18.04
* SDL Core Version: tag 7.0.0-RC1 5c72cddc35
* Testing Against: HMI: develop 727d0d3, SPT: 20201007 

##### Logs:
[SmartDeviceLinkCore.zip](https://github.com/smartdevicelink/sdl_core/files/5377496/SmartDeviceLinkCore.zip)

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #3541 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
- SDL and HMI are started
- Mobile app is registered and activated
- Mobile app requests SetGlobalProperties/AddSubMenu with all mandatory params and menuLayout
- SetGlobalProperties is set successfully/AddSubMenu is added successfully
- Perform Ignition off and ignition on/ transport reconnect
- Mobile app registers with actual hashID

### Summary
SDL never saved the `menuLayout`, so when resuming the device, we did not add it to the request SetGlobalProperty. And for the submenu, we did not correctly add it to the request. Was added set and get methods for `menuLayout` to the application interface. As well as a `menuLayout` field. In the command to restore global properties and submenus added a menuLayout to the request. Affected unit tests were updated accordingly.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by AKalinich-Luxoft** [comment]
@theresalech this PR is ready for Livio review

File: src/components/application_manager/src/message_helper/message_helper.cc [hunk 1]
```diff
@@ -1313,6 +1313,9 @@ MessageHelper::CreateGlobalPropertiesRequestsToHMI(
       if (app->menu_icon()) {
         ui_msg_params[strings::menu_icon] = (*app->menu_icon());
       }
+      if (app->menu_layout()) {
```
Comment (iCollin) [inline src/components/application_manager/src/message_helper/message_helper.cc:1316]: the if block that contains this needs the condition `|| app->menu_layout()`

I tested with this patch and all worked.
```
diff --git a/src/components/application_manager/src/message_helper/message_helper.cc b/src/components/application_manager/src/message_helper/message_helper.cc
index 61db5b6ec5..f5f227de4f 100644
--- a/src/components/application_manager/src/message_helper/message_helper.cc
+++ b/src/components/application_manager/src/message_helper/message_helper.cc
@@ -1289,7 +1289,7 @@ MessageHelper::CreateGlobalPropertiesRequestsToHMI(
 
   if (can_send_ui &&
       (app->vr_help_title() || app->vr_help() || app->keyboard_props() ||
-       app->menu_title() || app->menu_icon())) {
+       app->menu_title() || app->menu_icon() || app->menu_layout())) {
     smart_objects::SmartObjectSPtr ui_global_properties = CreateMessageForHMI(
         hmi_apis::messageType::request, app_mngr.GetNextHMICorrelationID());
     if (ui_global_properties) {

```

Comment (AKalinich-Luxoft) [reply src/components/application_manager/src/message_helper/message_helper.cc:1316]: @iCollin nice catch! Fixed in https://github.com/smartdevicelink/sdl_core/pull/3733/commits/0d92a875156c404b9fdab82686de2e4efe05c065
