### PR TITLE
Fix core crash on accesing the application pointer.

### LINKED ISSUE #3156: CCB: Fixed core crash on accesing the application pointer
### Bug Report
iOS switch from BT to USB is causing SDL to crash

### Detailed analysis:
App pointer check missing from ApplyPostponedStateForApp() function.

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile
2. iOS initially paired to B/T
3. Launch SYNC Proxy Tester
4. Go to Apps Page
5. Connect Same iOS device via USB
6. Observe behavior

##### Expected Behavior
SDL should not crash

##### Observed Behavior
When Apps un-register and re-register over USB, SDL is crashing

#### Occurrence: 
Random

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

### PR DESCRIPTION
**Pull request by IGapchuk**
Fixes #3156

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
The issue will occur when the state controller gets an application collection from the application manager and tries to apply a functor to each application.
One of the application's pointers could be uninitialized and the state controller should check if pointer is valid.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/include/application_manager/state_controller_impl.h [hunk 1]
```diff
@@ -152,12 +152,17 @@ class StateControllerImpl : public event_engine::EventObserver,
...
+    {
+      DataAccessor<ApplicationSet> accessor = app_mngr_.applications();
+      applications = accessor.GetData();
+    }
+
+    ApplicationSet::iterator it = applications.begin();
+    for (; it != applications.end(); ++it) {
+      auto app = *it;
+      if (app) {
+        func(app);
```
Comment (SNiukalov) [inline src/components/application_manager/include/application_manager/state_controller_impl.h]: Can we use range-based like it:
for (auto& app : applications) {      
      if (app) {
        func(app);
      }
    }

File: src/components/application_manager/include/application_manager/state_controller_impl.h [hunk 2]
```diff
@@ -152,12 +152,17 @@ class StateControllerImpl : public event_engine::EventObserver,
...
+    ApplicationSet applications;
+    {
+      DataAccessor<ApplicationSet> accessor = app_mngr_.applications();
+      applications = accessor.GetData();
+    }
+
+    ApplicationSet::iterator it = applications.begin();
+    for (; it != applications.end(); ++it) {
+      auto app = *it;
+      if (app) {
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/include/application_manager/state_controller_impl.h]: @IGapchuk you don't need this check anymore. Because you copied applications collection of shared ptrs, `ApplicationImpl` instance will not be destroyed until `applications` variable is destroyed as it also holds the same shared ptrs. That's why all pointers in this loop will be valid. You can remove this check

File: src/components/application_manager/include/application_manager/state_controller_impl.h (hunk 1 above)
Comment (IGapchuk) [reply src/components/application_manager/include/application_manager/state_controller_impl.h]: @SNiukalov Changed in c874387b10610d059a863f43497779f73aaa26e7

File: src/components/application_manager/include/application_manager/state_controller_impl.h (hunk 2 above)
Comment (IGapchuk) [reply src/components/application_manager/include/application_manager/state_controller_impl.h]: @AKalinich-Luxoft Removed in c874387b10610d059a863f43497779f73aaa26e7

**Comment by AByzhynar** [comment]
@IGapchuk Why PR destination is `MASTER` ?

**Comment by IGapchuk** [comment]
@theresalech PR is ready for the Livio team review.

**Comment by theresalech** [comment]
Hi @IGapchuk - this issue is not currently scoped for the Core 6.1 release, as approved by the Steering Committee.  Livio can work to include as time allows, but the issue should be raised to the Steering Committee if it's imperative for Luxoft in 6.1.

**Comment by IGapchuk** [comment]
@theresalech 
Regarding the Open SDL issue https://github.com/smartdevicelink/sdl_core/issues/3156 which this PR fixes:
The issue was found in Sync4 on the production environment. The issue leads to SDL crash (detailed issue's root cause you can find in the PR description).
The issue has been fixed and the fix has been integrated into Sync4.
We believe it is an important SDL fix and it should be integrated into Open SDL as well.
Could you please include this fix into Core 6.1 release scope if it's possible?
