### PR TITLE
Fix RC.SetGlobalProperties during resumption

### LINKED ISSUE #3469: SDL doesn't send RC.SetGlobalProperties during resumption
### Bug Report
SDL doesn't send RC.SetGlobalProperties during resumption

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile device, register application
2. Send `SetGlobalProperties` with `userLocation` parameter
=> SDL sends `RC.SetGlobalProperties` request to HMI and after receiving succesful response sends `OnHashChange` notification to the app
3. Perform unexpected disconnect and then reconnect (with correct hashId)
=> SDL starts resumption procedure

##### Expected Behavior
SDL sends RC.SetGlobalProperties during resumption trying to restore global properties

##### Observed Behavior
SDL doesn't send RC.SetGlobalProperties during resumption

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (6560d02)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - ATF Script: [3469.lua.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5008643/3469.lua.tar.gz)
 - Report and logs: [2020-07-31_15-07-07_3469.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5008646/2020-07-31_15-07-07_3469.tar.gz)

### PR DESCRIPTION
**Pull request by VadymLuchko**
Fixes #3469 

This PR is ready for review.

Risk
This PR makes no API changes.

Testing Plan
ATF

Summary
Added request for RC_SetGlobalProperties to MessageHelper::CreateGlobalPropertiesRequestsToHMI()
Also UserLocation information added to resumption data (json and DB)

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by VadymLuchko** [comment]
@JackLivio  this PR is ready for review

File: src/components/application_manager/src/resumption/resume_ctrl_impl.cc [hunk 1]
```diff
@@ -644,6 +644,10 @@ bool ResumeCtrlImpl::RestoreApplicationData(ApplicationSharedPtr application,
   bool result = resumption_storage_->GetSavedApplication(
       application->policy_app_id(), device_mac, saved_app);
   if (result) {
+    if (saved_app.keyExists(strings::user_location)) {
+      application->set_user_location(saved_app[strings::user_location]);
+    }
+
```
Comment (iCollin) [inline src/components/application_manager/src/resumption/resume_ctrl_impl.cc:650]: I think this should be in `ResumptionDataProcessorImpl::Restore`

Comment (VadymLuchko) [reply src/components/application_manager/src/resumption/resume_ctrl_impl.cc]: @iCollin fixed in https://github.com/smartdevicelink/sdl_core/pull/3622/commits/7d1f02a59c5cec1963918b5476ae9ff9ec6cd1b8

**Review by iCollin — APPROVED** [review]
