### PR TITLE
Fix for a potential SDL crash on boot 

### LINKED ISSUE #3163: CCB: Fix for a potential SDL crash on boot
### Bug Report
SmartDeviceLink crash

### Detailed analysis:
One of the reasons why SDL is crashing on start is related to lazy initialization of the HMI/Mobile/v4 API classes. These classes are initialized on demand when some of the threads are trying to get the object of that class first time. Most likely, at SDL start might be a situation when HMI/Mobile/v4 API classes are constructing in the one thread and at that moment another thread is trying to get access to the inner data of not-yet-fully-constructed object and this causes a core crash with ~ISchemaItem() calls in stack trace. That is possible because access to these factories is not synchronized.

To avoid such situation, factory creation should be moved to AM ctor and all other sub-components should just use getters when they need to get access to API instances.

##### Reproduction Steps
1. Simulate ignition OFF followed by door open and door close. Wait until SYNC is fully powered down
2. Wait 2 minutes
3. Simulate door open, door close followed by ignition on.
4. Wait 5 seconds
5. Simulate gear change to R
6. Wait 5 seconds
7. Simulate gear change to D
8. After 10 seconds, simulate gear change to P.
9. Wait 2 minutes.
10. Repeat 1 - 9 for 36 hours.

##### Expected Behavior
No crashes

##### Observed Behavior
Detected SmartDeviceLink core dump (once)

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

### PR DESCRIPTION
**Pull request by ychernysheva**
Fixes #3163

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
One of the reasons why SDL is crashing on start is related to lazy initialization of the HMI/Mobile/v4
API classes. These classes are initialized on demand when some of threads are trying to get the object of that class first time. Most likely, at SDL start might be a situation when HMI/Mobile/v4 API classes are
constructing in the one thread and at that moment another thread is trying to get access to the inner data of not-yet-fully-constructed object and this causes a core crash with ~ISchemaItem() calls in stack trace. That is possible because access to these factories is not synchronized.

To avoid such situation, factory creation was moved to AM ctor and all other sub components just use getters when they need to get access to API instances.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by ychernysheva** [comment]
@JackLivio This PR is ready for review.
Thank you!

File: src/components/application_manager/include/application_manager/rpc_handler_impl.h [hunk 1]
```diff
@@ -181,8 +181,11 @@ class RPCHandlerImpl : public RPCHandler,
                           const bool validate_params = true);
   std::shared_ptr<Message> ConvertRawMsgToMessage(
       const ::protocol_handler::RawMessagePtr message);
+
   hmi_apis::HMI_API& hmi_so_factory();
   mobile_apis::MOBILE_API& mobile_so_factory();
+  ns_smart_device_link_rpc::V1::v4_protocol_v1_2_no_extra&
+  v4_protocol_so_factory();
```
Comment (iCollin) [inline src/components/application_manager/include/application_manager/rpc_handler_impl.h:188]: function is only called internally, i think it would be better and less convoluted to just call `app_manager_.v4_protocol_so_factory()` instead of adding another function.

File: src/components/application_manager/src/application_manager_impl.cc [hunk 2]
```diff
@@ -174,8 +174,10 @@ ApplicationManagerImpl::ApplicationManagerImpl(
     , policy_handler_(new policy::PolicyHandler(policy_settings, *this))
     , protocol_handler_(NULL)
     , request_ctrl_(am_settings)
-    , hmi_so_factory_(NULL)
-    , mobile_so_factory_(NULL)
+    , hmi_so_factory_(hmi_apis::HMI_API())
+    , mobile_so_factory_(mobile_apis::MOBILE_API())
+    , v4_protocol_so_factory_(
+          ns_smart_device_link_rpc::V1::v4_protocol_v1_2_no_extra())
```
Comment (iCollin) [inline src/components/application_manager/src/application_manager_impl.cc:180]:
```suggestion
```

these lines are implied, I think we should remove them

File: src/components/application_manager/include/application_manager/application_manager_impl.h [hunk 3]
```diff
@@ -1610,8 +1613,10 @@ class ApplicationManagerImpl
     mobile_apis::SystemContext::eType system_context;
   };
 
-  hmi_apis::HMI_API* hmi_so_factory_;
-  mobile_apis::MOBILE_API* mobile_so_factory_;
+  hmi_apis::HMI_API hmi_so_factory_;
+  mobile_apis::MOBILE_API mobile_so_factory_;
+  ns_smart_device_link_rpc::V1::v4_protocol_v1_2_no_extra
+      v4_protocol_so_factory_;
```
Comment (iCollin) [inline src/components/application_manager/include/application_manager/application_manager_impl.h:1619]: I think this variable name should include `mobile` to match the other api schemas and make it more obvious what this schema is.

File: src/components/application_manager/include/application_manager/rpc_handler_impl.h (hunk 1 above)
Comment (LitvinenkoIra) [reply src/components/application_manager/include/application_manager/rpc_handler_impl.h]: Done in 4c89818

File: src/components/application_manager/src/application_manager_impl.cc (hunk 2 above)
Comment (LitvinenkoIra) [reply src/components/application_manager/src/application_manager_impl.cc]: Done in 4c89818

File: src/components/application_manager/include/application_manager/application_manager_impl.h (hunk 3 above)
Comment (LitvinenkoIra) [reply src/components/application_manager/include/application_manager/application_manager_impl.h]: Done in 4c89818

**Review by iCollin — APPROVED** [review]
