### PR TITLE
App Services Allow Unknown RPC Passthrough

### LINKED ISSUE #2877: SDL doesn't take into account functional group permissions for Consumer App
### Bug Report
SDL doesn't take into account functional group permissions for Consumer App that is defined in Policy Table

##### Reproduction Steps
1. App_1 (Service Provider) and App_2 (Consumer) are registered on SDL.
2. AppServiceProvider permissions(with NAVIGATION AppService permissions to handle rpc `SendLocation`) are assigned for App_1
3. SendLocation permissions **are NOT assigned** for App_2
4. App_1 sends a PublishAppService (with {serviceType=NAVIGATION, handledRPC=SendLocation} in the manifest)
5. App_2 sends a SendLocation request to Core

##### Expected Behavior
1. Core does not forward the request to App_1
2. Core does not forward the request to HMI
3. Core responds to App_2 with { success = false, resultCode = "DISALLOWED" }

##### Observed Behavior
1. Core forwards the request to App_1
2. Core does not forward the request to HMI
3. Core responds to App_2 with { success = true, resultCode = "SUCCESS" } (In case if App_1 responds to request successfully)

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: [5.1.0](https://github.com/smartdevicelink/sdl_core/commit/b9500e5e6f1c39db7eaee3a7416179edf0ac5dc6)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
[2019-04-04_16-42-41.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3043764/2019-04-04_16-42-41.tar.gz)

### PR DESCRIPTION
**Pull request by JackLivio**
Fixes #2877 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Add new field to application policies in sdl_preloaded_pt.json
 > "allow_unknown_rpc_passthrough" : true

### Summary
Adds new field to policies. Field will allow/disallow an app consumer from performing an unknown rpc request that is passed through to another app service.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/rpc_passing_handler.cc [hunk 1]
```diff
@@ -93,6 +93,63 @@ bool RPCPassingHandler::CanHandleFunctionID(int32_t function_id) {
...
+  ApplicationSharedPtr app = app_manager_.application(connection_key);
+  PolicyHandlerInterface& policy_handler = app_manager_.GetPolicyHandler();
+  if (!app) {
+    return false;
+  } else if (function_id_str.empty()) {
+    // Unknown RPC, just do basic revoked and user consent checks
+    std::string device_mac;
+    app_manager_.connection_handler().get_session_observer().GetDataOnDeviceID(
+        app->device(), NULL, NULL, &device_mac, NULL);
+    return policy_handler.UnknownRPCPassthroughAllowed(app->policy_app_id()) &&
```
Comment (JackLivio) [inline src/components/application_manager/src/rpc_passing_handler.cc]: 👍

**Comment by JackLivio** [comment]
@alexkutsan Ready for review

File: src/components/application_manager/src/rpc_handler_impl.cc [hunk 2]
```diff
@@ -118,16 +118,17 @@ void RPCHandlerImpl::ProcessMessageFromMobile(
...
         (*so_from_mobile)[strings::params][strings::message_type].asInt();
-    if (app_manager_.GetAppServiceManager()
-            .GetRPCPassingHandler()
-            .RPCPassThrough(*so_from_mobile)) {
+    RPCPassingHandler& handler =
+        app_manager_.GetAppServiceManager().GetRPCPassingHandler();
+    // Check permissions for requests, otherwise attempt passthrough
+    if ((application_manager::MessageType::kRequest != message_type ||
+         handler.IsPassthroughAllowed(*so_from_mobile)) &&
+        handler.RPCPassThrough(*so_from_mobile)) {
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/rpc_handler_impl.cc]: @jacobkeeler   I would not keep `handler.IsPassthroughAllowed` and `handler.RPCPassThrough` in one if condition. 
handler.IsPassthroughAllowed - Checking method, it does not have any actions.
handler.RPCPassThrough - Action method. I would avoid keeping this method in if condition, especially within checking method. 
Just to improve readability.

File: src/components/application_manager/src/rpc_passing_handler.cc [hunk 3]
```diff
@@ -93,6 +93,63 @@ bool RPCPassingHandler::CanHandleFunctionID(int32_t function_id) {
   return false;
 }
 
+bool RPCPassingHandler::IsPassthroughAllowed(
+    smart_objects::SmartObject rpc_message) {
+  LOG4CXX_AUTO_TRACE(logger_);
+  mobile_api::FunctionID::eType function_id =
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/rpc_passing_handler.cc]: @jacobkeeler  good place for auto

File: src/components/application_manager/src/rpc_passing_handler.cc [hunk 4]
```diff
@@ -93,6 +93,63 @@ bool RPCPassingHandler::CanHandleFunctionID(int32_t function_id) {
...
+      static_cast<mobile_api::FunctionID::eType>(
+          rpc_message[strings::params][strings::function_id].asInt());
+  uint32_t connection_key =
+      rpc_message[strings::params][strings::connection_key].asUInt();
+  std::string function_id_str =
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/rpc_passing_handler.cc]: @jacobkeeler 
In case if we need function_id only to get string function id, I would not split this expressions by retrieving connection_key.

File: src/components/application_manager/src/rpc_passing_handler.cc [hunk 5]
```diff
@@ -93,6 +93,63 @@ bool RPCPassingHandler::CanHandleFunctionID(int32_t function_id) {
...
+      MessageHelper::StringifiedFunctionID(function_id);
+  ApplicationSharedPtr app = app_manager_.application(connection_key);
+  PolicyHandlerInterface& policy_handler = app_manager_.GetPolicyHandler();
+  if (!app) {
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/rpc_passing_handler.cc]: @jacobkeeler 
can we move this safety check upper?

File: src/components/application_manager/src/rpc_passing_handler.cc [hunk 6]
```diff
@@ -93,6 +93,63 @@ bool RPCPassingHandler::CanHandleFunctionID(int32_t function_id) {
...
+    return false;
+  } else if (function_id_str.empty()) {
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/rpc_passing_handler.cc]: @jacobkeeler 
 we ca avoid else. We use return in if.

File: src/components/application_manager/src/rpc_passing_handler.cc [hunk 7]
```diff
@@ -93,6 +93,63 @@ bool RPCPassingHandler::CanHandleFunctionID(int32_t function_id) {
...
+    std::string device_mac;
+    app_manager_.connection_handler().get_session_observer().GetDataOnDeviceID(
+        app->device(), NULL, NULL, &device_mac, NULL);
+    return policy_handler.UnknownRPCPassthroughAllowed(app->policy_app_id()) &&
+           !policy_handler.IsApplicationRevoked(app->policy_app_id()) &&
+           policy::kDeviceAllowed ==
+               app_manager_.GetUserConsentForDevice(device_mac);
+  }
+
+  RPCParams params;
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/rpc_passing_handler.cc]: @jacobkeeler 
can we extract RPC params checking to separate function to make this a bit more easy to read?

File: src/components/application_manager/src/rpc_service_impl.cc [hunk 8]
```diff
@@ -126,7 +126,31 @@ bool RPCServiceImpl::ManageMobileCommand(
   auto plugin =
       app_manager_.GetPluginManager().FindPluginToProcess(function_id, source);
   if (!plugin) {
-    LOG4CXX_WARN(logger_, "Filed to find plugin : " << plugin.error());
+    LOG4CXX_WARN(logger_, "Failed to find plugin : " << plugin.error());
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/rpc_service_impl.cc]: @jacobkeeler I would extract it to function

**Comment by dboltovskyi** [comment]
@JackLivio It seems new `allow_unknown_rpc_passthrough` parameter is not stored in Policy DB for `EXTERNAL_PROPRIETARY` mode

File: src/components/policy/policy_external/src/cache_manager.cc [hunk 9]
```diff
@@ -1541,6 +1541,21 @@ void CacheManager::GetAppServiceParameters(
   }
 }
 
+bool CacheManager::UnknownRPCPassthroughAllowed(
+    const std::string& policy_app_id) const {
+  const policy_table::ApplicationPolicies& policies =
```
Comment (LuxoftAKutsan) [inline src/components/policy/policy_external/src/cache_manager.cc]: @jacobkeeler auto

File: src/components/policy/policy_external/src/cache_manager.cc [hunk 10]
```diff
@@ -1541,6 +1541,21 @@ void CacheManager::GetAppServiceParameters(
...
+      pt_->policy_table.app_policies_section.apps;
+  policy_table::ApplicationPolicies::const_iterator policy_iter =
+      policies.find(policy_app_id);
+  if (policies.end() != policy_iter) {
+    auto app_policy = (*policy_iter).second;
```
Comment (LuxoftAKutsan) [inline src/components/policy/policy_external/src/cache_manager.cc]: @jacobkeeler const

File: src/components/policy/policy_regular/src/sql_pt_queries.cc [hunk 11]
```diff
@@ -876,14 +879,17 @@ const std::string kInsertApplicationFull =
...
+    "  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
 
 const std::string kSelectApplicationFull =
     "SELECT `keep_context`, `steal_focus`, `default_hmi`, `priority_value`, "
     "  `is_revoked`, `is_default`, `is_predata`, `memory_kb`,"
     "  `heart_beat_timeout_ms`, `certificate`, `hybrid_app_preference_value`, "
-    "  `endpoint`, `enabled`, `auth_token`, `cloud_transport_type`, `icon_url` "
+    "  `endpoint`, `enabled`, `auth_token`, `cloud_transport_type`, "
+    "`icon_url`, "
+    "  `allow_unknown_rpc_passthrough` "
```
Comment (LuxoftAKutsan) [inline src/components/policy/policy_regular/src/sql_pt_queries.cc]: @jacobkeeler  will we update preloaded policy?

Comment (JackLivio) [reply src/components/policy/policy_regular/src/sql_pt_queries.cc]: I dont think there is a need for this. If the field is missing it will default to false.

File: src/components/application_manager/src/rpc_passing_handler.cc [hunk 12]
```diff
@@ -93,6 +93,74 @@ bool RPCPassingHandler::CanHandleFunctionID(int32_t function_id) {
...
+bool RPCPassingHandler::ExtractRPCParams(
+    const smart_objects::SmartObject& s_map,
+    const ApplicationSharedPtr app,
+    const std::string& function_id_str) {
+  LOG4CXX_AUTO_TRACE(logger_);
+  RPCParams params;
+
+  if (smart_objects::SmartType_Map == s_map.getType()) {
+    smart_objects::SmartMap::const_iterator iter = s_map.map_begin();
+    smart_objects::SmartMap::const_iterator iter_end = s_map.map_end();
```
Comment (ShobhitAd) [inline src/components/application_manager/src/rpc_passing_handler.cc]: Probably don't need to make local variables for these iterators since they are only used in the for loop
