### PR TITLE
Fix Consumer Friendly Messages removing from PT

### LINKED ISSUE #1027: [Policy]: SDL does not write UserFriendlyMessages to DB
## Occurrence
Always.

## Preconditions
1. SDL built with DEXTENDED_POLICY: ON.
2. First SDL life cycle.

## Steps to reproduce
1. Start SDL.
2. Register app and perform PTU.

## Actual result
During PTU HMI sends GetUserFriendlyMessage to SDL but SDL responds "messages":[
{"messageCode":"StatusPending"}
] where "messages" is re-sent part of request. UserFriendlyMessage are absent in DB.

## Expected result
SDL should write UserFriendlyMessage to DB and correctly respond to HMI GetUserFriendlyMessage request.

# Environment
SDL: https://github.com/smartdevicelink/sdl_core.git: a6c32b45832653d6b851be9b19355fa35f377e07
ATF: https://github.com/smartdevicelink/sdl_atf.git: 962e1eff8664d97af5e59ec4e22f39b9ea76f5eb
OS: Ubuntu 14.04 LTS

# Attachments
[att_issue#1027.zip](https://github.com/smartdevicelink/sdl_core/files/576436/att_issue.1027.zip).

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
In case PTU comes with omitted `consumer_friendly_messages` param, SDL should maintain current `consumer_friendly_messages` section in Local PT. 
Currently SDL removes all `consumer_friendly_messages` from PT even if this param was omitted in PTU.

Related PR in another branch: #1415 
Fixes #1027

### CODE REVIEW

**Comment by AKalinich-Luxoft** [comment]
@AByzhynar, @LitvinenkoIra, @LuxoftAKutsan, @dev-gh please review

File: src/components/policy/policy_regular/src/sql_pt_representation.cc [hunk 1]
```diff
@@ -1177,9 +1177,11 @@ bool SQLPTRepresentation::SaveConsumerFriendlyMessages(
   // the policy table. So it won't be changed/updated
   if (messages.messages.is_initialized()) {
     utils::dbms::SQLQuery query(db());
-    if (!query.Exec(sql_pt::kDeleteMessageString)) {
-      LOG4CXX_WARN(logger_, "Incorrect delete from message.");
-      return false;
+    if (!messages.messages->empty()) {
```
Comment (dev-gh) [inline src/components/policy/policy_regular/src/sql_pt_representation.cc]: @AKalinich-Luxoft 
I think it would be better to avoid deep nesting e.g. like
```

if (!msg.is_initialized()) {
   return false;
}
if (msg.empty()) {
   return false;
}
<process messages>

```

Comment (AKalinich-Luxoft) [inline src/components/policy/policy_regular/src/sql_pt_representation.cc]: @dev-gh I've done some refactoring for this function for both cc-files. See https://github.com/smartdevicelink/sdl_core/pull/1615/commits/045a313b4d99b6141ae99e71ff0e9d1d20520a1c

File: src/components/policy/policy_external/src/sql_pt_representation.cc [hunk 2]
```diff
@@ -1264,46 +1264,48 @@ bool SQLPTRepresentation::SaveConsumerFriendlyMessages(
...
-  if (messages.messages.is_initialized()) {
-    utils::dbms::SQLQuery query(db());
-    if (!messages.messages->empty()) {
-      if (!query.Exec(sql_pt::kDeleteMessageString)) {
-        LOG4CXX_WARN(logger_, "Incorrect delete from message.");
-        return false;
-      }
-    }
+  if (!messages.messages.is_initialized()) {
+    LOG4CXX_INFO(logger_, "Messages list is empty");
```
Comment (AByzhynar) [inline src/components/policy/policy_external/src/sql_pt_representation.cc]: @AKalinich-Luxoft I would extend logger message with message type specification

File: src/components/policy/policy_external/src/sql_pt_representation.cc [hunk 3]
```diff
@@ -1264,46 +1264,48 @@ bool SQLPTRepresentation::SaveConsumerFriendlyMessages(
...
-    } else {
-      LOG4CXX_WARN(logger_, "Incorrect update statement for version.");
+  utils::dbms::SQLQuery query(db());
+  bool delete_query_exec_result = true;
+  if (!messages.messages->empty()) {
+    delete_query_exec_result = query.Exec(sql_pt::kDeleteMessageString);
+  }
+
+  if (!delete_query_exec_result) {
+    LOG4CXX_WARN(logger_, "Incorrect delete from message.");
```
Comment (AByzhynar) [inline src/components/policy/policy_external/src/sql_pt_representation.cc]: @AKalinich-Luxoft Can not understand log message meaning

File: src/components/policy/policy_external/src/sql_pt_representation.cc (hunk 2 above)
Comment (AKalinich-Luxoft) [inline src/components/policy/policy_external/src/sql_pt_representation.cc]: @AByzhynar fixed in https://github.com/smartdevicelink/sdl_core/pull/1615/commits/36a37e964f03b3c01decee10c80a67b8c5ec1590

File: src/components/policy/policy_external/src/sql_pt_representation.cc (hunk 3 above)
Comment (AKalinich-Luxoft) [inline src/components/policy/policy_external/src/sql_pt_representation.cc]: @AByzhynar fixed in https://github.com/smartdevicelink/sdl_core/pull/1615/commits/36a37e964f03b3c01decee10c80a67b8c5ec1590
