### PR TITLE
Fix/WSS re-connection loop

### LINKED ISSUE #3889: WSS Re-connection infinite loop
### Bug Report
Currently, if a WSS Cloud App with a valid endpoint and invalid certificate is activated, core keeps attempting to re-connect to the cloud app.

##### Reproduction Steps
1. Setup test suite appJava with SSL enabled. Change the following params in `Config.java`
```
    public static final TransportType TRANSPORT_TYPE = TransportType.WEB_SOCKET_SERVER;
    public static final String APP_ID = "123e4567-e89b-12d3-a456-426655440000";
    public static final String APP_NAME = "Test Suite SE";
    ...
    public static final boolean ENABLE_SSL = true;
    public static final String CERTIFICATE_PEM = "<server_certificate_string>";
    public static final String KEY_PEM = "<server_key_string>";
```
2. Add cloud app entry for the cloud (with transport type WSS) in sdl_preloaded_pt.json. Replace `<client_certificate_string>` with an invalid certificate
```
"123e4567-e89b-12d3-a456-426655440000": {
                "keep_context": false,
                "steal_focus": false,
                "priority": "NONE",
                "default_hmi": "NONE",
                "groups": ["Base-4", "CloudAppStore"],
                "RequestType": [],
                "RequestSubType": [],
                "nicknames": ["Test Suite SE"],
                "hybrid_app_preference": "CLOUD",
                "endpoint": "wss://<core_ip>:4355",
                "auth_token": "none",
                "cloud_transport_type": "WSS",
                "enabled": true,
                "certificate": "<client_certificate_string>"
            },
```
3. Start Core and HMI
4. Click on cloud app entry in app list

##### Expected Behavior
- Cloud app fails to activate
- SDL sends `BasicCommunication.UpdateAppList` to the HMI with the cloud app endpoint and `"cloudConnectionStatus":"RETRY"`
- SDL sends `BasicCommunication.UpdateAppList` to the HMI with the cloud app endpoint and `"cloudConnectionStatus":"NOT_CONNECTED"`

##### Observed Behavior
- Cloud app fails to activate
- SDL **repeatedly** sends `BasicCommunication.UpdateAppList` to the HMI with the cloud app endpoint and `"cloudConnectionStatus":"RETRY"`
- SDL **repeatedly** sends `BasicCommunication.UpdateAppList` to the HMI with the cloud app endpoint and `"cloudConnectionStatus":"NOT_CONNECTED"`

**NOTE:** Core seems to sometimes send some invalid data to the HMI in the UpdateDeviceList request during this reconnection loop, such as `"transportType":-1` and `"cloudConnectionStatus":-1`

##### OS & Version Information
* OS/Version: Ubuntu 20.04
* SDL Core Version: release/8.1.0
* Testing Against: Test Suite (appJava)

### PR DESCRIPTION
**Pull request by ShobhitAd**
Fixes #3889 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Test WSS connection use Test Suite appJava

1. Start appJava with SSL enabled and an invalid certificate/key pair.
2. Add cloud app entry to sdl_preloaded_pt.json with valid certificate
3. Start Core and HMI
4. Activate app
- Activation fails and HMI receives UpdateAppList with `cloudConnectionStatus "NOT_CONNECTED"`
5. Restart appJava with valid certifcate/key pair
6. Activate app
-  Activation is sucessful. App goes into HMI_FULL.

### Summary
Re-connection loop occurs in the case of a succesful tcp layer connection and failed ssl handshake. This is probably due to `ShutDown()` being called during a re-activation attempt.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/transport_manager/src/cloud/websocket_client_connection.cc [hunk 1]
```diff
@@ -141,31 +142,36 @@ TransportAdapter::Error WebsocketClientConnection::Start() {
...
+    wss_->next_layer().handshake(ssl::stream_base::client, ec);
 
     if (ec) {
       std::string str_err = "ErrorMessage: " + ec.message();
       SDL_LOG_ERROR("Could not complete SSL Handshake failed with host/port: "
                     << host << ":" << port);
       SDL_LOG_ERROR(str_err);
-      Shutdown();
+      // Reset SSL Context and websocket stream
+      ctx_ = ssl::context(ssl::context::tlsv12_client);
```
Comment (jacobkeeler) [inline src/components/transport_manager/src/cloud/websocket_client_connection.cc:160]: Seems that you'll need to apply the cipher list again here:
```
  const char* wss_ciphers =
      "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-"
      "CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-"
      "SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-"
      "AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256";
  SSL_CTX_set_cipher_list(ctx_.native_handle(), wss_ciphers);
```
Could probably create a function to clear out the connection, so that it doesn't need to be copied in several places.

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

File: src/components/transport_manager/src/cloud/websocket_client_connection.cc (hunk 1 above)
Comment (ShobhitAd) [reply src/components/transport_manager/src/cloud/websocket_client_connection.cc]: Added in https://github.com/smartdevicelink/sdl_core/pull/3891/commits/db339b798d1e706246f4ffdce4abe474d24fc018

**Review by jacobkeeler — APPROVED** [review]
