### PR TITLE
Fix policy table loading with functional_group RPCs greater than 50

### LINKED ISSUE #968: Ubuntu: Policy table can't be loaded when RPCs added in functional_group is greater than 50.
## Occurrence
Always

## Preconditions
1. Add to sdl_preloaded_pt.json 51 RPCs.

## Steps to reproduce
1. Start SDL.
2. SDL tries to load Policy table.

## Actual result
1. SDL gets "Parsed table is not valid policy_table.policy_table.functional_groupings["Base-4"].rpcs: map has invalid size" and closed.

## Expected result
1. Policy table is loaded successfully.
2. SDL continues to work normally.

_**Notes:**_
In requirements no limitation of RPCs that shall be included in functional_group is found.

# Environment
\-

# Attachments
[att_issue#968.zip](https://github.com/smartdevicelink/sdl_core/files/575620/att_issue.968.zip).

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
SDL rejects to load policy table when sdl_preloaded_pt.json contains at least one functional group with more than 50 RPCs. The fix changes number of allowed RPC's to unlimited (65535).

Changes was taken from related PR #1328 from another branch
Fixes #968

### CODE REVIEW

**Comment by AKalinich-Luxoft** [comment]
Rebuild required

**Comment by AKalinich-Luxoft** [comment]
Rebuild pull_request_UT

**Comment by AKalinich-Luxoft** [comment]
@AByzhynar, @LitvinenkoIra, @LuxoftAKutsan, @dev-gh please review

File: src/components/policy/policy_regular/include/policy/policy_table/types.h [hunk 1]
```diff
@@ -67,7 +67,7 @@ typedef Array<Enum<HmiLevel>, 0, 4> HmiLevels;
 
 typedef Array<Enum<Parameter>, 0, 24> Parameters;
 
-typedef Map<RpcParameters, 0, 50> Rpc;
+typedef Map<RpcParameters, 0, 65535> Rpc;
```
Comment (LuxoftAKutsan) [inline src/components/policy/policy_regular/include/policy/policy_table/types.h]: @AKalinich-Luxoft it really should be so big? If yes, could you please use some platform specific constant of intmax?

Comment (AKalinich-Luxoft) [inline src/components/policy/policy_regular/include/policy/policy_table/types.h]: @LuxoftAKutsan yes, not just big. We don't have any limitations regarding rpc count, so it should be unlimited. Replaced with macro. See https://github.com/smartdevicelink/sdl_core/pull/1610/commits/d4aa621768d568d6dc563fbdf620155875bd6257
