### PR TITLE
Fix VD items subscriptions after PTU

### LINKED ISSUE #3079: Core dump by ignition off after removing of custom vehicle data during PTU
### Bug Report
Core dump by ignition off after removing of custom vehicle data during PTU

##### Reproduction Steps
1. App is registered and activated
2. custom_data_1 presets in DB
3. PTU is performed with removing custom_data_1
4. Ignition off is performed

##### Expected Behavior
SDL shuts down successful

##### Observed Behavior
Core dump
```
smartDeviceLinkCore: /home/jenkins/workspace/Release_6.0.0_SDL_NoUT_Proprietary/src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc:159: ns_smart_device_link::ns_smart_objects::SmartObjectSPtr vehicle_info_plugin::VehicleInfoPlugin::GetUnsubscribeIVIRequest(const std::vector<std::__cxx11::basic_string<char> >&): Assertion `(!key_name.empty())' failed.
log4cxx: No appender could be found for logger (ApplicationManager).
```

##### OS & Version Information
* OS/Version:Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/6.0.0_RC ( 2b09ea3 )
* ATF: [develop](https://github.com/smartdevicelink/sdl_atf/tree/develop)
* Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/API/VehicleData/GenericNetworkSignalData/036_Subscribtion_after_removing_VD_from_permissions.lua

##### Log
[SmartDeviceLinkCore.zip](https://github.com/smartdevicelink/sdl_core/files/3733576/SmartDeviceLinkCore.zip)

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #3079  and #3080 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Covered with ATF scripts

### Summary
There was found an issue that SDL still kept subscriptions for custom vehicle data items even
for case when they were removed during PTU. By that reason, SDL was crashing with DCHECK on
attempt to unsubscribe from non existing custom data.

There was added missing logic of internal unsubscribe in case  some custom vehicle data was removed by policies.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h [hunk 1]
```diff
@@ -72,6 +72,7 @@ class VehicleInfoPlugin : public plugins::RPCPlugin {
                                      VehicleInfoAppExtension& ext);
 
  private:
+  void UnsubscribeFromNotExistingVDItems();
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h]: @AKalinich-Luxoft `...NonExisting...`

Comment (AKalinich-Luxoft) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h]: @AByzhynar fixed in https://github.com/smartdevicelink/sdl_core/commit/334284c3bf4d0930bb84a16cb67d040b59102065

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc [hunk 2]
```diff
@@ -98,26 +98,39 @@ void VehicleInfoPlugin::OnApplicationEvent(
...
+                              << " has been removed by policy");
+            out_items.push_back(subscription_name);
+          }
+        }
       }
     }
+  };
+
+  StringsVector items_to_unsubscribe;
+  get_items_to_unsubscribe(items_to_unsubscribe);
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc]: @AKalinich-Luxoft I would rather use it like 
```cpp
StringsVector items_to_unsubscribe =get_items_to_unsubscribe();
```

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc [hunk 3]
```diff
@@ -98,26 +98,39 @@ void VehicleInfoPlugin::OnApplicationEvent(
...
-          custom_vehicle_data_manager_->IsValidCustomVehicleDataName(
-              subscription_name);
-      if (!is_std_vd_name && !is_valid_custom_vd_name) {
-        LOG4CXX_DEBUG(logger_,
-                      "Vehicle data item " << subscription_name
-                                           << " has been revoked by policy");
-        ext.unsubscribeFromVehicleInfo(subscription_name);
+  typedef std::vector<std::string> StringsVector;
+
+  auto get_items_to_unsubscribe = [this](StringsVector& out_items) {
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc]: @AByzhynar added a return type for a getter.
See https://github.com/smartdevicelink/sdl_core/pull/3081/commits/7aa5625d93c526d8a1332fa5ae3c32e0c4a6a02c

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc (hunk 2 above)
Comment (AKalinich-Luxoft) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc]: @AByzhynar I choose the option 1 with get_ prefix. It's a labmda and I am considering it as a local variable so kept appropriate naming. Please take a look at https://github.com/smartdevicelink/sdl_core/pull/3081/commits/7aa5625d93c526d8a1332fa5ae3c32e0c4a6a02c

File: src/components/include/policy/policy_regular/policy/policy_manager.h [hunk 4]
```diff
@@ -563,6 +563,13 @@ class PolicyManager : public usage_statistics::StatisticsManager,
   virtual const std::vector<policy_table::VehicleDataItem> GetVehicleDataItems()
       const = 0;
 
+  /**
+   * @brief Gets removed vehicle data items
+   * @return Structure with vehicle data items
+   */
+  virtual const std::vector<policy_table::VehicleDataItem>
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/include/policy/policy_regular/policy/policy_manager.h]: @AByzhynar agree that there is no sense in const return type here. Removed it from everywhere in interfaces. See https://github.com/smartdevicelink/sdl_core/pull/3081/commits/7aa5625d93c526d8a1332fa5ae3c32e0c4a6a02c

File: src/components/policy/policy_regular/include/policy/cache_manager.h [hunk 5]
```diff
@@ -919,6 +922,16 @@ class CacheManager : public CacheManagerInterface {
    */
   void CheckSnapshotInitialization();
 
+  /**
+   * @brief Checks for custom vehicle data items removed after PTU and stores
+   * the difference
+   * @param items_before list of vehicle data items before PTU was applied
+   * @param items_after list of vehicle data items after PTU was applied
+   */
+  void SetRemovedCustomVdItems(
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/policy/policy_regular/include/policy/cache_manager.h]: @AByzhynar agree. Splitted on two separate functions. See https://github.com/smartdevicelink/sdl_core/pull/3081/commits/7aa5625d93c526d8a1332fa5ae3c32e0c4a6a02c

**Comment by jordynmackool** [comment]
@AKalinich-Luxoft please advise when this is ready for Livio review

**Comment by dboltovskyi** [comment]
@jordynmackool Please notice this PR is ready for review.

**Comment by dboltovskyi** [comment]
Please notice our team decided to extend test coverage regarding related issue.
Additional ATF test scripts created in https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2286
However on a current head commit 8b2a3e4 of this PR one new script is failed.
So please notice we're going to push an update.

**Comment by dboltovskyi** [comment]
@theresalech Please notice update is completed and PR is ready for review.

File: src/components/policy/policy_external/src/cache_manager.cc [hunk 6]
```diff
@@ -1922,6 +1941,46 @@ void CacheManager::CheckSnapshotInitialization() {
...
+
+    auto it =
+        std::find_if(items_after.begin(), items_after.end(), item_predicate);
+    if (items_after.end() == it) {
+      removed_items.push_back(item_to_search);
+    }
+  }
+
+  LOG4CXX_DEBUG(logger_,
+                "Was found " << removed_items.size() << " removed VD items");
```
Comment (ShobhitAd) [inline src/components/policy/policy_external/src/cache_manager.cc]:
```suggestion
                "Found " << removed_items.size() << " removed custom VD items");
```

File: src/components/policy/policy_regular/src/cache_manager.cc [hunk 7]
```diff
@@ -1226,6 +1242,46 @@ void CacheManager::CheckSnapshotInitialization() {
...
+
+    auto it =
+        std::find_if(items_after.begin(), items_after.end(), item_predicate);
+    if (items_after.end() == it) {
+      removed_items.push_back(item_to_search);
+    }
+  }
+
+  LOG4CXX_DEBUG(logger_,
+                "Was found " << removed_items.size() << " removed VD items");
```
Comment (ShobhitAd) [inline src/components/policy/policy_regular/src/cache_manager.cc]:
```suggestion
                "Found " << removed_items.size() << " removed custom VD items");
```

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h [hunk 8]
```diff
@@ -72,6 +72,7 @@ class VehicleInfoPlugin : public plugins::RPCPlugin {
                                      VehicleInfoAppExtension& ext);
 
  private:
+  void UnsubscribeFromNonExistingVDItems();
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h]: @ShobhitAd good point. Renamed in https://github.com/smartdevicelink/sdl_core/pull/3081/commits/b6060b86c65aa0d5fedc207fb399ad9fcfbc9e4b

File: src/components/policy/policy_external/src/cache_manager.cc (hunk 6 above)
Comment (AKalinich-Luxoft) [reply src/components/policy/policy_external/src/cache_manager.cc]: @ShobhitAd fixed in https://github.com/smartdevicelink/sdl_core/pull/3081/commits/b6060b86c65aa0d5fedc207fb399ad9fcfbc9e4b

File: src/components/policy/policy_regular/src/cache_manager.cc (hunk 7 above)
Comment (AKalinich-Luxoft) [reply src/components/policy/policy_regular/src/cache_manager.cc]: @ShobhitAd fixed in https://github.com/smartdevicelink/sdl_core/pull/3081/commits/b6060b86c65aa0d5fedc207fb399ad9fcfbc9e4b
