### PR TITLE
Fix SDL respond UNSUPPORTED_RESOURCE on SystemRequest (QUERY_APPS)

### LINKED ISSUE #2399: SDL must respond UNSUPPORTED_RESOURCE to mobile app in case SDL 4.0 feature is required to be ommited in implementation
### Bug Report
SDL must respond UNSUPPORTED_RESOURCE to mobile app in case SDL 4.0 feature is required to be ommited in implementation

##### Reproduction Steps
1. In case SDL 4.0 was omited in implementation 
and mobile app sends SystemRequest (QUERY_APPS) 

##### Expected Behavior
SDL must:
respond SystemRequest (UNSUPPORTED_RESOURCE, success:false) to modile application.

##### OS & Version Information
* OS/Version: 
* SDL Core Version:
* Testing Against:

### PR DESCRIPTION
**Pull request by Ypostolov**
Fixes #2399 

This PR is ready for review.

### Risk
This PR makes no API changes.

### Testing Plan
Changes in PR are already covered within existing unit tests.

### Summary
SDL respond UNSUPPORTED_RESOURCE on SystemRequest (QUERY_APPS) to mobile app in case SDL 4.0 feature is required to be ommited in implementation.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/system_request.cc [hunk 1]
```diff
@@ -511,6 +510,13 @@ void SystemRequest::Run() {
     return;
   }
 
+  if (mobile_apis::RequestType::QUERY_APPS == request_type &&
+      application_manager_.get_settings().max_supported_protocol_version() <
+          4) {
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/system_request.cc]: @Ypostolov 4 is like a magic number extract ti variable with comment

Comment (Ypostolov) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/system_request.cc]: @LuxoftAKutsan 
Fixed in 3540848c21d445e1c079e44df650449f6b506029
