### PR TITLE
Fix CheckButtonName check for module types other than CLIMATE and RADIO

### LINKED ISSUE #3945: CheckButtonName check not working for module types other than CLIMATE and RADIO
### Bug Report
Currently, core only checks if a button name is compatible with the module type (in CheckButtonName) if the module type in the request is CLIMATE or RADIO. 

If the user were to send a ButtonPress request with a different type, core would currently not send the "Request module type and button name mismatch!" response and forward the invalid request to the HMI

##### Reproduction Steps
1. Add RemoteControl permissions in preloaded_pt
```json
"app_policies": {
            "default": {
                "keep_context": false,
                "steal_focus": false,
                "priority": "NONE",
                "default_hmi": "NONE",
                "groups": [
                    "Base-4",
+                    "RemoteControl"
                ],
+                "moduleType": [],
                "RequestType": [],
                "RequestSubType": []
            },
```
3. Start core and HMI
4. Register and activate RPC Builder app with appHMIType REMOTE_CONTROL
5. Send ButtonPress with params `{"moduleType":"HMI_SETTINGS","buttonName":"FAN_UP","buttonPressMode":"LONG"}`

##### Expected Behavior
App receives INVALID_DATA response with info "Request module type and button name mismatch!"

##### Observed Behavior
App receives SUCCESS response

##### OS & Version Information
* OS/Version: Ubuntu 20.04
* SDL Core Version: release/8.2.0
* Testing Against: RPC Builder

### PR DESCRIPTION
**Pull request by ShobhitAd**
Fixes #3945

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Run issue reproduction steps with RPC Builder

### Summary
Currently, core only checks if a button name is compatible with the module type (in `CheckButtonName`) if the module typein the request is CLIMATE or RADIO. If the user were to send a ButtonPress request with a different type (e.g. ButtonPress(PLAY_PAUSE, HMI_SETTINGS), core would currently **not** send the "Request module type and button name mismatch!" response and forward the invalid request to the HMI

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_helpers.cc [hunk 1]
```diff
@@ -30,12 +30,17 @@ const std::vector<std::string> RCHelpers::buttons_radio() {
...
   data.push_back(enums_value::kRepeat);
   return data;
 }
 
+const std::vector<std::string> RCHelpers::buttons_audio() {
+  std::vector<std::string> data;
+  data.push_back(enums_value::kSource);
+  return data;
+}
+
```
Comment (jacobkeeler) [inline src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_helpers.cc:43]:
```suggestion
  data.push_back(enums_value::kSource);
  data.push_back(enums_value::kShuffle);
  data.push_back(enums_value::kRepeat);
  return data;
}

```
Gotta revert this, the `SOURCE` button is tied to the `RADIO` module, not the `AUDIO` module (for however odd that is design-wise).

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_helpers.cc (hunk 1 above)
Comment (ShobhitAd) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_helpers.cc]: Ah I see. Reverted the previous commit

**Review by jacobkeeler — CHANGES_REQUESTED** [review]
