### PR TITLE
Fix misplaced OnDataVideoStreaming

### LINKED ISSUE #3142: SDL sends misplaced OnVideoDataStreaming notification
### Bug Report
SDL sends misplaced OnVideoDataStreaming notification which leads to a video streaming issue on HMI

##### Reproduction Steps
1. Register 2 Navigation apps
2. Activate 1st app and start streaming
3. Activate 2nd app and start streaming.
4. `Navigation.OnVideoDataStreaming { "available" = true }` is sent to HMI
5. 1st app obtains `NOT_STREAMABLE` state but keeps sending data. Since timeout is not yet expired, the application is not yet unregistered. But the stream is suspended.

##### Expected Behavior
SDL provides HMI with streaming data from 2nd application and keeps streaming from 1st application suspended.
No extra notifications are sent to HMI.

##### Observed Behavior
SDL sends `OnVideoDataStreaming { "available" = false }` notification to HMI. 
Though, 1st application keeps streaming. And this notification could cause streaming issue on HMI.

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: develop (891497bc9fb23434242dbe92e1f13dd1273fcb21)
* Testing Against: WebHMI [91d5940](https://github.com/smartdevicelink/sdl_hmi/tree/91d59402b8e0967f9a3532b2cf3f2537ee068b95)

### PR DESCRIPTION
**Pull request by mkorniichuk**
Fixes #3142

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
Fix misplaces sending of OnDataVideoStreaming notification.

SDL used to send OnDataVideoStreaming from the application instance independently. Not it will be sent from application_manager, taking into account common service status, not status of certain app.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/application_manager_impl.cc [hunk 1]
```diff
@@ -3477,6 +3477,45 @@ void ApplicationManagerImpl::ProcessPostponedMessages(const uint32_t app_id) {
   std::for_each(messages.begin(), messages.end(), push_allowed_messages);
 }
 
+void ApplicationManagerImpl::ProcessOnDataStreamingNotification(
+    const protocol_handler::ServiceType service_type,
+    const uint32_t app_id,
+    const bool status) {
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_manager_impl.cc]: @mkorniichuk status is unclear name. May be `send_required` or `send_needed` or something more meaningful?

File: src/components/include/application_manager/application_manager.h [hunk 2]
```diff
@@ -296,6 +296,18 @@ class ApplicationManager {
...
+   * @brief Updates streaming service status for specified session and notifies
+   * HMI via notification if required
+   * @param service_type Id of service which status should be updated
+   * @param app_id Id of session which status should be updated
+   * @param status New streming status for specified session
+   */
+  virtual void ProcessOnDataStreamingNotification(
+      const protocol_handler::ServiceType service_type,
+      const uint32_t app_id,
+      const bool status) = 0;
```
Comment (AKalinich-Luxoft) [inline src/components/include/application_manager/application_manager.h]: @mkorniichuk better names for this param is `should_be_inserted`, `insert_required`, `is_new_service` etc.. Otherwise you can declare enum class describing actions should be done by your function (`kAddService`, `kRemoveService`). 
BTW this will make your code much cleaner as `kAddService` is more descriptive than just true or false while passing the params.

File: src/components/application_manager/src/application_manager_impl.cc (hunk 1 above)
Comment (mkorniichuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @AByzhynar fixed in 112037801c58a44cf62a8d078ab186fb9f25e7b5

File: src/components/include/application_manager/application_manager.h (hunk 2 above)
Comment (mkorniichuk) [reply src/components/include/application_manager/application_manager.h]: @AKalinich-Luxoft I've renamed this parameter in 112037801c58a44cf62a8d078ab186fb9f25e7b5.
As for me, it is better to use a variable, cause it stands for the availability of streaming data. And enum, from my perspective, is redundant.

File: src/components/application_manager/src/application_manager_impl.cc [hunk 3]
```diff
@@ -3477,6 +3477,46 @@ void ApplicationManagerImpl::ProcessPostponedMessages(const uint32_t app_id) {
...
 
+void ApplicationManagerImpl::ProcessOnDataStreamingNotification(
+    const protocol_handler::ServiceType service_type,
+    const uint32_t app_id,
+    const bool streaming_data_available) {
+  LOG4CXX_AUTO_TRACE(logger_);
+
+  bool should_send_notification = false;
+
+  {
```
Comment (ShobhitAd) [inline src/components/application_manager/src/application_manager_impl.cc]: Any reason why the code below is in a separate block ({...})?

**Comment by dboltovskyi** [comment]
@theresalech Please notice this PR is ready for PM review

File: src/components/include/test/application_manager/mock_application_manager.h [hunk 4]
```diff
@@ -143,6 +143,10 @@ class MockApplicationManager : public application_manager::ApplicationManager {
                void(uint32_t app_id,
                     mobile_apis::HMILevel::eType from,
                     mobile_apis::HMILevel::eType to));
+  MOCK_METHOD3(ProcessOnDataStreamingNotification,
+               void(const protocol_handler::ServiceType service_type,
+                    const uint32_t app_id,
+                    const bool status));
```
[the remark this answers is not in the document]
Comment (mkorniichuk) [reply src/components/include/test/application_manager/mock_application_manager.h]: @ShobhitAd good point. fixed in ed9369c2272f5dedb640010b196e21d39230f205

File: src/components/application_manager/src/application_manager_impl.cc (hunk 3 above)
Comment (mkorniichuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @ShobhitAd this extra scope is required for the following `streaming_services_lock_` to be unlocked at the end of the scope, not the entire method.
