### PR TITLE
Fix UpdateDeviceList content

### LINKED ISSUE #974: CCB: fix UpdateDeviceList conten
### Bug Report
SDL sends UpdateDeviceList with disconnected device in the deviceList 

##### Reproduction Steps
1. Connect several devices.
2. Disconnect devices
3. Initiate sending UpdateDeviceList from SDL

##### Expected Behavior
SDL sends UpdateDeviceList without disconnected devices.

##### Observed Behavior
Disconnected devices are presented in UpdateDeviceList

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: fa05b5f5b1af6fae7d684a5cc156ec2e68dbc197
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
* [att_issue#974.zip](https://github.com/smartdevicelink/sdl_core/files/575833/att_issue.974.zip)

### PR DESCRIPTION
**Pull request by Ypostolov**
Fixes #974

This PR is ready for review.

### Risk
This PR makes no API changes.

### Testing Plan
unit tests
atf test

### Summary
fixed UpdateDeviceList contetnt  for case, when device connected
ower tcp protocol was unexpectedly disconnected and
device has only one connection.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/transport_manager/src/transport_adapter/transport_adapter_impl.cc [hunk 1]
```diff
@@ -774,7 +774,7 @@ void TransportAdapterImpl::RemoveFinalizedConnection(
     const DeviceUID& device_handle, const ApplicationHandle& app_handle) {
   const DeviceUID device_uid = device_handle;
   LOG4CXX_AUTO_TRACE(logger_);
-  sync_primitives::AutoWriteLock lock(connections_lock_);
+  connections_lock_.AcquireForWriting();
```
Comment (EKuliiev) [inline src/components/transport_manager/src/transport_adapter/transport_adapter_impl.cc]: @Ypostolov 
1) potential dead lock  if (it_conn == connections_.end()) and if (info.state != ConnectionInfo::FINALISING) 
2) logging under critical section

Comment (Ypostolov) [reply src/components/transport_manager/src/transport_adapter/transport_adapter_impl.cc]: 1. Used scoped lock to avoid such situations. See 002e4222f6ca70b2d66bd3dc3da3850d9f6b325b
2. Using logger inside critical section - its a common case in SDL project and that's OK.

**Comment by vkushnirenko-luxoft** [comment]
Rebuild required

File: src/components/transport_manager/src/transport_adapter/transport_adapter_impl.cc [hunk 2]
```diff
@@ -774,23 +774,36 @@ void TransportAdapterImpl::RemoveFinalizedConnection(
...
+    ConnectionMap::iterator it_conn =
+        connections_.find(std::make_pair(device_uid, app_handle));
+    if (it_conn == connections_.end()) {
+      LOG4CXX_WARN(logger_,
+                   "Device_id: " << &device_uid << ", app_handle: "
+                                 << &app_handle << " connection not found");
+      return;
+    }
+    const ConnectionInfo& info = it_conn->second;
+    if (info.state != ConnectionInfo::FINALISING) {
```
Comment (LuxoftAKutsan) [inline src/components/transport_manager/src/transport_adapter/transport_adapter_impl.cc]: @Ypostolov swap if condition

File: src/components/transport_manager/src/transport_adapter/transport_adapter_impl.cc [hunk 3]
```diff
@@ -774,23 +774,36 @@ void TransportAdapterImpl::RemoveFinalizedConnection(
...
-  if (it_conn == connections_.end()) {
-    LOG4CXX_WARN(logger_,
-                 "Device_id: " << &device_uid << ", app_handle: " << &app_handle
-                               << " connection not found");
-    return;
+  {
+    sync_primitives::AutoWriteLock lock(connections_lock_);
+    ConnectionMap::iterator it_conn =
+        connections_.find(std::make_pair(device_uid, app_handle));
+    if (it_conn == connections_.end()) {
```
Comment (LuxoftAKutsan) [inline src/components/transport_manager/src/transport_adapter/transport_adapter_impl.cc]: @Ypostolov swap if condition

File: src/components/transport_manager/src/transport_adapter/transport_adapter_impl.cc [hunk 4]
```diff
@@ -774,23 +774,36 @@ void TransportAdapterImpl::RemoveFinalizedConnection(
...
-  ConnectionMap::iterator it_conn =
-      connections_.find(std::make_pair(device_uid, app_handle));
-  if (it_conn == connections_.end()) {
-    LOG4CXX_WARN(logger_,
-                 "Device_id: " << &device_uid << ", app_handle: " << &app_handle
-                               << " connection not found");
-    return;
+  {
+    sync_primitives::AutoWriteLock lock(connections_lock_);
+    ConnectionMap::iterator it_conn =
```
Comment (LuxoftAKutsan) [inline src/components/transport_manager/src/transport_adapter/transport_adapter_impl.cc]: @Ypostolov use auto

File: src/components/transport_manager/src/transport_adapter/transport_adapter_impl.cc (hunk 2 above)
Comment (Ypostolov) [reply src/components/transport_manager/src/transport_adapter/transport_adapter_impl.cc]: @alexkutsan 
fixed in 4be18be33fc5f36bfe297a0622dcf8c4853a45bc

File: src/components/transport_manager/src/transport_adapter/transport_adapter_impl.cc (hunk 3 above)
Comment (Ypostolov) [reply src/components/transport_manager/src/transport_adapter/transport_adapter_impl.cc]: @LuxoftAKutsan 
fixed in 4be18be33fc5f36bfe297a0622dcf8c4853a45bc

File: src/components/transport_manager/src/transport_adapter/transport_adapter_impl.cc (hunk 4 above)
Comment (Ypostolov) [reply src/components/transport_manager/src/transport_adapter/transport_adapter_impl.cc]: @LuxoftAKutsan 
fixed in 4be18be33fc5f36bfe297a0622dcf8c4853a45bc

**Comment by Ypostolov** [comment]
rebuild required

**Comment by LitvinenkoIra** [comment]
Rebased to the latest develop (e137556)

**Comment by mkorniichuk** [comment]
@theresalech, please be informed current PR is up to date and ready for Livio review
