### PR TITLE
Prevent HMI commands processing while SDL is stopping

### LINKED ISSUE #3774: SDL core dump on IGNITION_OFF
### Bug Report
SDL core dump on IGNITION_OFF

##### Reproduction Steps
1. SDL and HMI are started
2. Mobile App is registered
3. Perform ignition Off:
On "HMI" go to → Click the "Exit Application" button → Select “IGNITION_OFF” in “Exit Application reason” → Click the `Send state` button
SDL->HMI: BasicCommunication.OnExitAllApplications:{"reason":"IGNITION_OFF"}}

##### Expected Behavior
SDL starts the ignition off sequence
1. SDL sends to HMI OnSDLClose and stops working
SDL->HMI: BasicCommunication.OnSDLClose:{}

##### Observed Behavior
SDL starts the ignition off sequence
1. SDL sends to HMI OnSDLClose and stops working
SDL->HMI: BasicCommunication.OnSDLClose:{}
**Core dump is observed**

##### OS & Version Information
* OS/Version: [Ubuntu 18]
* SDL Core Version: [ https://github.com/smartdevicelink/sdl_core/tree/develop (35f5a06 )]
* HMI: [https://github.com/smartdevicelink/sdl_hmi/tree/develop (d2c882a)]
* SPT: 20210729-Android

### PR DESCRIPTION
**Pull request by VladSemenyuk**
Fixes #3774

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Manual, ATF

### Summary
Prevent HMI commands life time managment through RequestController while SDL is stopping.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by VladSemenyuk** [comment]
@jordynmackool this PR is ready for Livio review
Note, this is a fix for a regression found during the release testing and the review should be prioritized

File: src/components/application_manager/src/rpc_service_impl.cc [hunk 1]
```diff
@@ -392,7 +392,9 @@ bool RPCServiceImpl::ManageHMICommand(const commands::MessageSharedPtr message,
   if (kRequest == message_type) {
     SDL_LOG_DEBUG("ManageHMICommand");
     command->set_warning_info(warning_info);
-    request_ctrl_.AddHMIRequest(command);
+    if (!app_manager_.IsStopping()) {
```
Comment (iCollin) [inline src/components/application_manager/src/rpc_service_impl.cc:395]: Hello, can you please explain this change a bit?

Why would this only cover `AddHMIRequest`? Is this change necessary to prevent a crash? Why would this change not exit the method much earlier like the low voltage check?

**Comment by iCollin** [comment]
Hello @VladSemenyuk, I see you mention ATF in the testing plan, is there an ATF test to reproduce the related issue?

**Comment by iCollin** [comment]
Hello @VladSemenyuk, sorry to ping you so many times but this is an important issue late in our development cycle and we would like to take care of it as fast as possible.

After some review, I am not sure how this can be a regression issue. The only related differences between master and the release branch that I see are the following:

1. When a request from mobile times out, the order of events being unsubscribed from has changed.
a. On master, Core would unsubscribe from HMI events and then Mobile events.
b. On the release branch, Core will unsubscribe from Mobile events and then HMI events.

2. When a request from Mobile is cleaned up, Core will now unsubscribe from mobile and HMI events. On master, Core did not unsubscribe from any events in this method.

Can you please help me to understand, what caused this issue? If not, do you know about when (in which release) this bug was introduced? Thank you.

File: src/components/application_manager/src/rpc_service_impl.cc (hunk 1 above)
Comment (VladSemenyuk) [reply src/components/application_manager/src/rpc_service_impl.cc:395]: Hi!
>> Is this change necessary to prevent a crash?
This changes is neccesary here as HMI Commands gets corrupted if they being added to Request controller after ApplicationManger is requested to stop.
>>Why would this only cover AddHMIRequest?
HMI requests are stored in a separate collection in Request Controller and crash is related exactly to this collection.
>>Why would this change not exit the method much earlier like the low voltage check?
SDL need to send requests to HMI during stopping(e.g. Navigation.StopAudioStream, Navigation.StopStream reuqests), but in this case we don't need to wait for responses. By this reason we need to call Run() method, but we don't need to track it with Request controller.

**Comment by JackLivio** [comment]
We were able to reproduce the issue on the release branch by sending ignition off while video streaming.

**Review by iCollin — APPROVED** [review]
