### PR TITLE
Test for double data cleanup

### LINKED ISSUE #3135: CCB:  Fix undefined behavior after SO cleanup
### Bug Report
SDL crash in the random places.

##### Reproduction Steps
This issue is often observed during cable unplug
while audio/video streaming is active.

##### Expected Behavior
SDL no crashes

##### Observed Behavior
SDL crash in the random places.

#### OS & Version Information

OS/Version: Ubuntu 16.04
SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (e137556512215ded94228e33d21ab4c3e1af3017)
Testing : Unit tests

### PR DESCRIPTION
**Pull request by SNiukalov**
Fixes #3135

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Stability test

### Summary
After `cleanup_data()` call, `delete` is used to deallocate memory by pointer, however pointer is still holding a value of address of the already deallocated memory. By that reason SO still have an ability to access that data what might cause UB including core crashes in the random places.

This issue is often observed during cable unplug while audio/video streaming is active. To avoid such problem, NULL pointer is assigned explicitly to avoid unwanted memory access. Also this fixes possible "double free memory" issues.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/smart_objects/test/SmartObjectUnit_test.cc [hunk 1]
```diff
@@ -585,6 +586,26 @@ TEST(MapEraseTest, SmartObjectTest) {
...
+  };
+
+  DerivedSmartObject obj(SmartType_String);
+  ASSERT_EQ(SmartType_String, obj.getType());
+
+  obj = "test string_value";
+  ASSERT_EQ(std::string("test string_value"), obj.asString());
+
+  obj.cleanup_data();
+  obj.cleanup_data();
```
Comment (AByzhynar) [inline src/components/smart_objects/test/SmartObjectUnit_test.cc]: @SNiukalov It's confusing...Why did you call it twice?

File: src/components/smart_objects/src/smart_object.cc [hunk 2]
```diff
@@ -734,16 +734,28 @@ void SmartObject::duplicate(const SmartObject& OtherObject) {
 void SmartObject::cleanup_data() {
   switch (m_type) {
     case SmartType_String:
-      delete m_data.str_value;
+      if (m_data.str_value) {
+        delete m_data.str_value;
+        m_data.str_value = NULL;
```
Comment (AByzhynar) [inline src/components/smart_objects/src/smart_object.cc]: @SNiukalov Use `nullptr` everywhere instead of `NULL`

Comment (SNiukalov) [reply src/components/smart_objects/src/smart_object.cc]: Fixed in:https://github.com/smartdevicelink/sdl_core/pull/3146/commits/6915e49d17c1a2bb31e654ab1fa2fc3b668b9040

File: src/components/smart_objects/test/SmartObjectUnit_test.cc (hunk 1 above)
Comment (SNiukalov) [reply src/components/smart_objects/test/SmartObjectUnit_test.cc]: @AByzhynar 
In this case we try testing stability work clean_data function.
In previously implementation we will get crash or indefine behevior after twice call this function.
Unit tests will be finished with aborting.
But now this test case will working correctly.

Fixed in:https://github.com/smartdevicelink/sdl_core/pull/3146/commits/6915e49d17c1a2bb31e654ab1fa2fc3b668b9040

File: src/components/smart_objects/test/CMakeLists.txt [hunk 3]
```diff
@@ -53,5 +53,11 @@ set(EXCLUDE_PATHS
   SmartObjectConvertionTime_test.cc
 )
 
+# Enable detect Double-free, invalid free
+# AddressSanitizer is a fast memory error detector. 
+# It consists of a compiler instrumentation module and a run-time library.
+set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=address")
```
Comment (AKalinich-Luxoft) [inline src/components/smart_objects/test/CMakeLists.txt]: @SNiukalov do you really need address sanity enabled for unit tests? I believe this tool for debug purposes only

Comment (SNiukalov) [reply src/components/smart_objects/test/CMakeLists.txt]: @AKalinich-Luxoft 
Yes you are right. But without this option, we can't detect Double-free, becuase test always will finish normal. But with this option test will be aborted and show backtrace.

**Comment by SNiukalov** [comment]
@theresalech PR is ready for Livio team review. Thank you.

File: src/components/smart_objects/src/smart_object.cc [hunk 4]
```diff
@@ -734,16 +734,28 @@ void SmartObject::duplicate(const SmartObject& OtherObject) {
...
+      if (m_data.array_value) {
+        delete m_data.array_value;
+        m_data.array_value = nullptr;
+      }
       break;
     case SmartType_Binary:
-      delete m_data.binary_value;
+      if (m_data.binary_value) {
+        delete m_data.binary_value;
+        m_data.array_value = nullptr;
```
Comment (iCollin) [inline src/components/smart_objects/src/smart_object.cc]: while it's functionally the same, this is a copy paste error :)

**Comment by SNiukalov** [comment]
@iCollin 
Thanks, yes, you're right.
All changes for smart_object.cc were discarded
This mistake occurred because we have different issues (3135 and 3109)
PR rebased to the last develop commit.
