### PR TITLE
Fix/filter invalid parametres and rpcs

### LINKED ISSUE #1921: Processing invalid PT after cutting off unknown_parameter or unknown_RPC
**Occurrence: Always** 

## Steps to reproduce
1. Make sure SDL is built with default flags
2. Start SDL and HMI
3. Connect mobile device
4. Register new application
5. Create PT for policy table update with unknown_parameter or unknown_RPC
6. Perform policy table update from mobile app with created PT

## Expected result
1. SDL received UpdatedPT with at least one <unknown_parameter> or <unknown_RPC>
and after cutting off <unknown_parameter> or <unknown_RPC> UpdatedPT performs validation of received PT
2. SDL must log the error internally and discard Policy Table Update

## Actual result
SDL performs PT validation without cutting off <unknown_parameter> or <unknown_RPC>

## Test script
[1921_Invalid_PT_after_cutting_unknow_values.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1921_Invalid_PT_after_cutting_unknow_values.lua)

## Attachments

# Expected delivery
- [x] Source code updates
- [x] Code comments
- [x] **UTs add/update _(not required)_**
- [x] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

### PR DESCRIPTION
**Pull request by LuxoftAKutsan**
Fixes #1921

This PR is ready for review.

### Risk
This PR makes no API changes.

### Testing Plan
Tested with ATF script attached to  #1921

### Summary
Added generation most of policy enums. Added to policy enums RPC's
Added filtering of received RPC and parameters in policy update.

Added bson ad custom target to avoid cmake warning
Added logger initialization in unit tests run for analyzing unit test failures without debugging.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/policy/policy_external/include/policy/policy_table/enums.h [hunk 1]
```diff
@@ -35,31 +35,19 @@
...
-bool IsValidEnum(Priority val);
-const char* EnumToJsonString(Priority val);
-bool EnumFromJsonString(const std::string& literal, Priority* result);
-
-enum HmiLevel {
-  HL_BACKGROUND,
-  HL_FULL,
-  HL_LIMITED,
-  HL_NONE,
+enum Input {
```
Comment (AKalinich-Luxoft) [inline src/components/policy/policy_external/include/policy/policy_table/enums.h]: @LuxoftAKutsan Is this enum used somewhere?

File: src/components/policy/policy_external/src/policy_manager_impl.cc [hunk 2]
```diff
@@ -280,6 +280,51 @@ std::string PolicyManagerImpl::GetLockScreenIconUrl() const {
   return cache_->GetLockScreenIconUrl();
 }
 
+/**
+ * @brief FilterInvalidFunctions filter functions that are not present in schema
+ * @param rpcs list of functins to filter
```
Comment (AKalinich-Luxoft) [inline src/components/policy/policy_external/src/policy_manager_impl.cc]: @LuxoftAKutsan typo

File: src/components/policy/policy_external/src/policy_manager_impl.cc [hunk 3]
```diff
@@ -280,6 +280,51 @@ std::string PolicyManagerImpl::GetLockScreenIconUrl() const {
...
+  for (auto& param : *(rpc_parameters.parameters)) {
+    if (param.is_valid()) {
+      valid_params.push_back(param);
+    }
+  }
+  rpc_parameters.parameters->swap(valid_params);
+}
+
+/**
+ * @brief FilterPolicyTable fileter values that not present in schema
```
Comment (AKalinich-Luxoft) [inline src/components/policy/policy_external/src/policy_manager_impl.cc]: @LuxoftAKutsan typo

File: src/components/policy/policy_regular/src/policy_manager_impl.cc [hunk 4]
```diff
@@ -149,6 +149,51 @@ void PolicyManagerImpl::CheckTriggers() {
   }
 }
 
+/**
+ * @brief FilterInvalidFunctions filter functions that are not present in schema
+ * @param rpcs list of functins to filter
```
Comment (AKalinich-Luxoft) [inline src/components/policy/policy_regular/src/policy_manager_impl.cc]: @LuxoftAKutsan typo

File: src/components/policy/policy_regular/src/policy_manager_impl.cc [hunk 5]
```diff
@@ -149,6 +149,51 @@ void PolicyManagerImpl::CheckTriggers() {
...
+  for (auto& param : *(rpc_parameters.parameters)) {
+    if (param.is_valid()) {
+      valid_params.push_back(param);
+    }
+  }
+  rpc_parameters.parameters->swap(valid_params);
+}
+
+/**
+ * @brief FilterPolicyTable fileter values that not present in schema
```
Comment (AKalinich-Luxoft) [inline src/components/policy/policy_regular/src/policy_manager_impl.cc]: @LuxoftAKutsan typo

File: src/components/test_main.cc [hunk 6]
```diff
@@ -3,6 +3,7 @@
 #include "utils/custom_string.h"
 int main(int argc, char** argv) {
   namespace custom_str = utils::custom_string;
+  INIT_LOGGER("log4cxx.properties", false);
```
Comment (AKalinich-Luxoft) [inline src/components/test_main.cc]: @LuxoftAKutsan do we need logger in tests?

File: src/components/policy/policy_external/CMakeLists.txt [hunk 7]
```diff
@@ -56,8 +58,33 @@ set(SOURCES
   ${POLICY_PATH}/src/status.cc
   ${POLICY_PATH}/src/cache_manager.cc
   ${COMPONENTS_DIR}/rpc_base/src/rpc_base/rpc_base.cc
+  ${CMAKE_CURRENT_BINARY_DIR}/
 )
 
+set (GENERATED_MOBILE_POLICY_TYPES "generated_MOBILE_API_policy_types")
```
Comment (AByzhynar) [inline src/components/policy/policy_external/CMakeLists.txt]: @LuxoftAKutsan redundant space after set?

File: src/components/policy/policy_external/src/policy_manager_impl.cc [hunk 8]
```diff
@@ -280,6 +280,51 @@ std::string PolicyManagerImpl::GetLockScreenIconUrl() const {
   return cache_->GetLockScreenIconUrl();
 }
 
+/**
+ * @brief FilterInvalidFunctions filter functions that are not present in schema
```
Comment (AByzhynar) [inline src/components/policy/policy_external/src/policy_manager_impl.cc]: @LuxoftAKutsan Make it shorter: `functions that are not present in schema` -> `functions that are absent in schema`

File: src/components/policy/policy_external/src/policy_manager_impl.cc [hunk 9]
```diff
@@ -280,6 +280,51 @@ std::string PolicyManagerImpl::GetLockScreenIconUrl() const {
...
+ * @param rpcs list of functins to filter
+ */
+void FilterInvalidFunctions(policy_table::Rpc& rpcs) {
+  policy_table::Rpc valid_rpcs;
+  for (auto& rpc : rpcs) {
```
Comment (AByzhynar) [inline src/components/policy/policy_external/src/policy_manager_impl.cc]: @LuxoftAKutsan `for (const auto& rpc: rpcs)` ?

File: src/components/test_main.cc (hunk 6 above)
Comment (AByzhynar) [reply src/components/test_main.cc]: @LuxoftAKutsan It would be great if we can use logger in tests

File: src/components/policy/policy_external/include/policy/policy_table/enums.h (hunk 1 above)
Comment (LuxoftAKutsan) [reply src/components/policy/policy_external/include/policy/policy_table/enums.h]: @AKalinich-Luxoft yes in cache manager.

File: src/components/test_main.cc (hunk 6 above)
Comment (LuxoftAKutsan) [reply src/components/test_main.cc]: @AKalinich-Luxoft yep, that's would be good to have logging in UT

File: src/components/policy/policy_external/src/policy_manager_impl.cc (hunk 2 above)
Comment (LuxoftAKutsan) [reply src/components/policy/policy_external/src/policy_manager_impl.cc]: @AKalinich-Luxoft fixed 829bec8

File: src/components/policy/policy_external/src/policy_manager_impl.cc (hunk 3 above)
Comment (LuxoftAKutsan) [reply src/components/policy/policy_external/src/policy_manager_impl.cc]: @AKalinich-Luxoft fixed 829bec8

File: src/components/policy/policy_regular/src/policy_manager_impl.cc (hunk 4 above)
Comment (LuxoftAKutsan) [reply src/components/policy/policy_regular/src/policy_manager_impl.cc]: @AKalinich-Luxoft fixed 829bec8

File: src/components/policy/policy_regular/src/policy_manager_impl.cc (hunk 5 above)
Comment (LuxoftAKutsan) [reply src/components/policy/policy_regular/src/policy_manager_impl.cc]: @AKalinich-Luxoft fixed 829bec8

File: src/components/policy/policy_external/CMakeLists.txt (hunk 7 above)
Comment (LuxoftAKutsan) [reply src/components/policy/policy_external/CMakeLists.txt]: @AByzhynar  fixed 829bec8

File: src/components/policy/policy_external/src/policy_manager_impl.cc (hunk 8 above)
Comment (LuxoftAKutsan) [reply src/components/policy/policy_external/src/policy_manager_impl.cc]: @AByzhynar fixed 829bec8

File: src/components/policy/policy_external/src/policy_manager_impl.cc (hunk 9 above)
Comment (LuxoftAKutsan) [reply src/components/policy/policy_external/src/policy_manager_impl.cc]: @AByzhynar fixed 829bec8

File: src/3rd_party/CMakeLists.txt [hunk 10]
```diff
@@ -205,6 +205,11 @@ else()
   get_filename_component(EMHASHMAP_LIBS_DIRECTORY ${EMHASHMAP_LIB} DIRECTORY)
   set(BSON_LIBS_DIRECTORY ${BSON_LIBS_DIRECTORY} CACHE INTERNAL "Installation path of bson libraries" FORCE)
   set(EMHASHMAP_LIBS_DIRECTORY ${BSON_LIBS_DIRECTORY} CACHE INTERNAL "Installation path of emashmap libraries" FORCE)
+  add_custom_target(
+      libbson
+      DEPENDS ${BSON_LIBS_DIRECTORY}
+      DEPENDS ${EMHASHMAP_LIBS_DIRECTORY}
```
Comment (mrapitis) [inline src/3rd_party/CMakeLists.txt]: @LuxoftAKutsan  Are these additions related to the policy changes? Can you please explain further?

Comment (LuxoftAKutsan) [reply src/3rd_party/CMakeLists.txt]: @mrapitis yep, this is not related to defect. It is just annoying issue that I was fixed in scope. 
I placed it in separate commit. So it can be safely removed.

**Comment by LuxoftAKutsan** [comment]
@mrapitis removed not related to fix code. 
Checked with https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1926/

File: src/components/policy/policy_regular/include/policy/policy_table/enums.h [hunk 11]
```diff
@@ -52,9 +54,9 @@ const char* EnumToJsonString(Priority val);
 bool EnumFromJsonString(const std::string& literal, Priority* result);
 
 enum HmiLevel {
-  HL_BACKGROUND,
```
Comment (mrapitis) [inline src/components/policy/policy_regular/include/policy/policy_table/enums.h]: Is there a reason we changed to ordering of the enum?

File: src/components/policy/policy_regular/include/policy/policy_table/enums.h [hunk 12]
```diff
@@ -89,6 +91,21 @@ enum Parameter {
   P_DEVICESTATUS,
   P_EMERGENCYEVENT,
   P_ECALLINFO,
+  P_ABS_STATE,
```
Comment (mrapitis) [inline src/components/policy/policy_regular/include/policy/policy_table/enums.h]: These elements were not previously present, can you please further explain the changes?

File: src/components/policy/policy_regular/test/policy_manager_impl_test.cc [hunk 13]
```diff
@@ -209,7 +209,7 @@ class PolicyManagerImplTest2 : public ::testing::Test {
     ON_CALL(policy_settings_, app_storage_folder())
         .WillByDefault(ReturnRef(kAppStorageFolder));
     manager->set_listener(&listener);
-    const char* levels[] = {"BACKGROUND", "FULL", "LIMITED", "NONE"};
+    const char* levels[] = {"FULL", "LIMITED", "BACKGROUND", "NONE"};
```
Comment (mrapitis) [inline src/components/policy/policy_regular/test/policy_manager_impl_test.cc]: Was there a reason the ordering of our enum was changed?

File: src/components/policy/policy_regular/include/policy/policy_table/enums.h (hunk 11 above)
Comment (LuxoftAKutsan) [reply src/components/policy/policy_regular/include/policy/policy_table/enums.h]: Unit tests passing, WE should change either in unit tests, or in enums. I can see that ordering mistake is in enums, before my changes this unit test probably was not affected by it.

File: src/components/policy/policy_regular/test/policy_manager_impl_test.cc (hunk 13 above)
Comment (LuxoftAKutsan) [reply src/components/policy/policy_regular/test/policy_manager_impl_test.cc]: @mrapitis returned changes back. 66e229195

File: src/components/policy/policy_regular/include/policy/policy_table/enums.h (hunk 11 above)
Comment (LuxoftAKutsan) [reply src/components/policy/policy_regular/include/policy/policy_table/enums.h]: @mrapitis return this changes back within enum ordering in unit tests.  66e229195

File: src/components/policy/policy_regular/include/policy/policy_table/enums.h (hunk 12 above)
Comment (LuxoftAKutsan) [reply src/components/policy/policy_regular/include/policy/policy_table/enums.h]: @mrapitis returned this changes back 6b4cb10d8136a5734041eca7d709d11e1dc7b317

**Comment by mrapitis** [comment]
@theresalech this PR is ready for review.

**Comment by conlain-k** [comment]
Hello all,
Testing this against ATF develop, the given 1921_Invalid_PT_after_cutting_unknown_values.lua
test fails for me with the following error: 

```
[17:02:12,746] Invalid_PTU_after_cutting_of_unknown_values                                           [FAIL] (10551 ms)
 HMI notification SDL.OnStatusUpdate: Timeout: HMI notification SDL.OnStatusUpdate: Timeout expired
```

Additionally, the protocol_handler test fails for me with a similar issue:
```
6: [ RUN      ] ProtocolHandlerImplTest.SendHeartBeat_Successful
6: /home/conlain/programs/sdl_core/src/components/protocol_handler/test/protocol_handler_tm_test.cc:1991: Failure
6: Actual function call count doesn't match EXPECT_CALL(transport_manager_mock, SendMessageToDevice(ExpectedMessage( FRAME_TYPE_CONTROL, FRAME_DATA_HEART_BEAT, PROTECTION_OFF, kControl)))...
6:          Expected: to be called once
6:            Actual: never called - unsatisfied and active
6: pure virtual method called
6: terminate called without an active exception
1/1 Test #6: protocol_handler_test ............***Exception: Child aborted  3.40 sec
```
I've attached the ATF output, I can also upload the log if needed. 
[filter_test_log.txt](https://github.com/smartdevicelink/sdl_core/files/2233620/filter_test_log.txt)

**Comment by dboltovskyi** [comment]
@conlain-k Regarding failed ATF test please notice that the last correct version of `1921` script is located in https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1926 which mentioned in https://github.com/smartdevicelink/sdl_core/issues/1921 
Please use it for testing.

**Comment by conlain-k** [comment]
@dboltovskyi the `protocol_handler_test` is somewhat sporadic -- in running it 10 times, it failed 8 times. It doesn't fail like that in develop -- I'll take a closer look tomorrow.

Trying it again with the `1921` script in smartdevicelink/sdl_atf_test_scripts#1926 does indeed work, thank you!

One other thing, it seems that this PR adds significantly more code generation, including another parsing pass over `MOBILE_API.xml`. Is that correct?

**Comment by LuxoftAKutsan** [comment]
@conlain-k  
> One other thing, it seems that this PR adds significantly more code generation, including another parsing pass over MOBILE_API.xml. Is that correct?

Yes, this code including code generation of c++ header that contains FunctionIDs for policy database.
The alternative solution could be : 

 1. Adding MOBILE_API generated files as the dependency for policy : 
    - Benefits: Do not need to generate additional files
    - Drawbacks: Hight coupling components, also mobile schema contains a lot of data that do not need for policies. 

2. Hard code FunctionIDs in enums.h the same as done for `Priority`, `HmiLevel`, `Parameter`, ... 
   - Benefits: Minor changes in the code 
   - Drawbacks: hardcoded values that need to be changed each time when list of functions is changed.

**Comment by LuxoftAKutsan** [comment]
@jacobkeeler  removed generation of FunctionIDs
