### PR TITLE
Fix app service extension resumption data processing

### LINKED ISSUE #3096: Application does not retrieve subscriptions to app service after resumption
### Bug Report
Application does not retrieve subscriptions to app service after resumption.

##### Reproduction Steps
1. Register application
2. Subscribe application to app service(s)
3. Perform unexpected disconnect
4. Perform resumption

##### Expected Behavior
After resumption application retrieves all its subscriptions to app service(s)

##### Observed Behavior
After resumption application **does not** retrieve all its subscriptions to app service(s)

##### OS & Version Information
* OS/Version: [Ubuntu 18.04]
* SDL Core Version: [https://github.com/smartdevicelink/sdl_core/tree/develop](url)
* Testing Against: ATF test scripts + UT
* Scripts: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2289

### PR DESCRIPTION
**Pull request by YarikMamykin**
Fixes #3096 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
ATF Regression testing + UT

### Summary
In case of resumption app services subscription data for particular application lost every time due to incorrect behaviour of AppServiceAppExtension::ProcessResumption method logic.
With fix resumption data is treated correctly.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/src/app_service_app_extension.cc [hunk 1]
```diff
@@ -103,7 +103,8 @@ void AppServiceAppExtension::ProcessResumption(
     const smart_objects::SmartObject& subscriptions_app_services =
         resumption_data[app_service_info];
     for (size_t i = 0; i < subscriptions_app_services.length(); ++i) {
-      std::string service_type = resumption_data[i].asString();
+      std::string service_type =
+          resumption_data[app_service_info][i].asString();
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/app_service_rpc_plugin/src/app_service_app_extension.cc]: @YarikMamykin why don't you use `subscriptions_app_services` declared above?

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/CMakeLists.txt [hunk 2]
```diff
@@ -0,0 +1,25 @@
+include(${CMAKE_SOURCE_DIR}/tools/cmake/helpers/sources.cmake)
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/CMakeLists.txt]: @YarikMamykin I believe we should insert copyright comment into cmake files as well...

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc [hunk 3]
```diff
@@ -0,0 +1,220 @@
...
+#include "gtest/gtest.h"
+
+namespace {
+const std::string kAppServiceType1 = "AppServiceType1";
+const std::string kAppServiceType2 = "AppServiceType2";
+const std::string kResumptionDataKey = "kResumptionDataKey";
+const std::string kAppServiceInfoKey = "appService";
+}  // namespace
+
+namespace app_service_plugin_test {
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc]: @YarikMamykin I suppose this should be wrapped into `test->components->app_service_plugin_test` namespaces

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc [hunk 4]
```diff
@@ -0,0 +1,220 @@
...
+                app_service_plugin_, *mock_app_)) {
+    ON_CALL(*mock_app_, AddExtension(_)).WillByDefault(Return(true));
+    ON_CALL(*mock_app_, QueryInterface(_))
+        .WillByDefault(Return(app_service_app_extension_));
+  }
+
+ protected:
+  app_service_rpc_plugin::AppServiceRpcPlugin app_service_plugin_;
+  std::shared_ptr<MockApplication> mock_app_;
+  std::shared_ptr<AppServiceAppExtension> app_service_app_extension_;
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc]: @YarikMamykin maybe unique?

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc [hunk 5]
```diff
@@ -0,0 +1,220 @@
...
+  const auto& subs = app_service_app_extension->Subscriptions();
+  EXPECT_EQ(1u, subs.size());
+  EXPECT_TRUE(
+      app_service_app_extension->IsSubscribedToAppService(kAppServiceType1));
+}
+
+TEST_F(AppServiceAppExtensionTest,
+       SubscribeToAppService_SubscribeOneAppServiceType_Twice_FAIL) {
+  auto app_service_app_extension =
+      std::make_shared<AppServiceAppExtension>(app_service_plugin_, *mock_app_);
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc]: @YarikMamykin I think this can be done in SetUp and removed from each test case

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc [hunk 6]
```diff
@@ -0,0 +1,220 @@
...
+    ASSERT_TRUE(
+        app_service_app_extension->SubscribeToAppService(app_service_type));
+    ASSERT_TRUE(
+        app_service_app_extension->IsSubscribedToAppService(app_service_type));
+  }
+  ASSERT_EQ(2u, app_service_app_extension->Subscriptions().size());
+
+  app_service_app_extension->UnsubscribeFromAppService();
+
+  for (const auto& app_service_type : {kAppServiceType1, kAppServiceType2}) {
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc]: @YarikMamykin please extract this into a separate list and use in both loops

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc [hunk 7]
```diff
@@ -0,0 +1,220 @@
...
+
+TEST_F(AppServiceAppExtensionTest, ProcessResumption_SUCCESS) {
+  auto app_service_app_extension =
+      std::make_shared<AppServiceAppExtension>(app_service_plugin_, *mock_app_);
+  app_service_app_extension->UnsubscribeFromAppService();
+  ASSERT_EQ(0u, app_service_app_extension->Subscriptions().size());
+
+  smart_objects::SmartObject resumption_data;
+  resumption_data[kAppServiceInfoKey] =
+      smart_objects::SmartObject(smart_objects::SmartType_Array);
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc]: @YarikMamykin suggest to create a `SmartType_Array` object first, then push back data and then just assign this object to `kAppServiceInfoKey` field of `resumption_data`

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/src/app_service_app_extension.cc (hunk 1 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/app_service_rpc_plugin/src/app_service_app_extension.cc]: @AKalinich-Luxoft fixed in 12854ed786c7b982ed2a5a553f560a4cad66dd8d

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/CMakeLists.txt (hunk 2 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/CMakeLists.txt]: @AKalinich-Luxoft fixed in 12854ed786c7b982ed2a5a553f560a4cad66dd8d

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc (hunk 3 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc]: @AKalinich-Luxoft fixed in d3a6bc63c0ded3551421683575a2de6a5850a091

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc (hunk 4 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc]: @AKalinich-Luxoft fixed in d3a6bc63c0ded3551421683575a2de6a5850a091

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc (hunk 5 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc]: @AKalinich-Luxoft fixed in d3a6bc63c0ded3551421683575a2de6a5850a091

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc (hunk 6 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc]: @AKalinich-Luxoft fixed in d3a6bc63c0ded3551421683575a2de6a5850a091

Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc]: @AKalinich-Luxoft  fixed in 2ec9ea198cf54b563252051776bd08f48acb560f

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc (hunk 7 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc]: @AKalinich-Luxoft  fixed in 2ec9ea198cf54b563252051776bd08f48acb560f

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/include/app_service_rpc_plugin/commands/mobile/get_app_service_data_request.h [hunk 8]
```diff
@@ -67,6 +67,11 @@ class GetAppServiceDataRequest : public app_mngr::commands::CommandRequestImpl {
    **/
   virtual void Run();
 
+  /*
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/app_service_rpc_plugin/include/app_service_rpc_plugin/commands/mobile/get_app_service_data_request.h]: @YarikMamykin Fix Doxygen comment

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc [hunk 9]
```diff
@@ -0,0 +1,213 @@
...
+
+using namespace app_service_rpc_plugin;
+namespace strings = application_manager::strings;
+namespace plugins = application_manager::plugin_manager;
+
+class AppServiceAppExtensionTest : public ::testing::Test {
+ public:
+  AppServiceAppExtensionTest() : mock_app_(new NiceMock<MockApplication>()) {}
+
+  void SetUp() {
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc]: @YarikMamykin Add `OVERRIDE` to TearDown & SetUp functions. Move them into `protected` area

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc [hunk 10]
```diff
@@ -0,0 +1,213 @@
...
+  resumption_data[kAppServiceInfoKey] = app_service_data;
+
+  app_service_app_extension_->ProcessResumption(resumption_data);
+
+  for (const auto& app_service_type : {kAppServiceType1, kAppServiceType2}) {
+    EXPECT_TRUE(
+        app_service_app_extension_->IsSubscribedToAppService(app_service_type));
+  }
+  EXPECT_EQ(2u, app_service_app_extension_->Subscriptions().size());
+  EXPECT_EQ(kAppServiceType1,
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc]: @YarikMamykin What is the sense of this last check?

Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc]: @AByzhynar fixed in 7fac4d2c0b4cd1d6ce1768602598fa10b9cf6c14

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc (hunk 9 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc]: @AByzhynar fixed in 7fac4d2c0b4cd1d6ce1768602598fa10b9cf6c14

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/include/app_service_rpc_plugin/commands/mobile/get_app_service_data_request.h (hunk 8 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/app_service_rpc_plugin/include/app_service_rpc_plugin/commands/mobile/get_app_service_data_request.h]: @AByzhynar fixed in 7fac4d2c0b4cd1d6ce1768602598fa10b9cf6c14

File: src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/CMakeLists.txt [hunk 11]
```diff
@@ -0,0 +1,55 @@
...
+set(APP_SERVICE_SRC_DIR "${APP_SERVICE_DIR}/src")
+set(APP_SERVICE_INCLUDE_DIR "${APP_SERVICE_DIR}/include/app_service_rpc_plugin")
+set(APP_SERVICE_TEST_DIR "${APP_SERVICE_DIR}/test")
+
+include_directories(
+  ${GMOCK_INCLUDE_DIRECTORY}
+  ${APP_SERVICE_INCLUDE_DIR}
+) 
+
+set(SOURCES ${APP_SERVICE_TEST_DIR}/app_service_plugin/app_service_app_extension_test.cc
```
[the remark this answers is not in the document]
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/CMakeLists.txt]: @LuxoftAKutsan fixed in b0036065b710a02a0c107a4b4e6763052bad4a79
