### PR TITLE
Fix SubscribeVehicleData request subscriptions

### LINKED ISSUE #996: Negative result code send instead of IGNORED for UnsubscribedVehicleData when VehicleInfo IsReady Missing
## Occurrence
Always

## Preconditions
ATF is properly set-up according to note below.
In user_modules>IsReady_Template in test_run folder of ATF build put attached file ATF_Interface_IsReady_missing_SingleRPC_Template.lua.
In test_scripts folder in sdl_atf_test_scripts folder of ATF build put attached file ATF_VehicleInfo_IsReady_missing_SingleRPC_USER_DISALLOWED.lua.

## Steps to reproduce
Run script. Check result in section Testing RPC = UnsubscribeVehicleData of test TC_UnsubscribeVehicleData_Only_USER_DISALLOWED_Case_1_IsReady_HMI_Does_Not_Respond (last one in script).

## Actual result
1. DISALLOWED recult code is sent
SDL->MOB(12:05:00) [version: 2, frameType: 1, encryption: false, serviceType: 7, frameInfo: 0, messageId: 14] :
{"resultCode":"USER_DISALLOWED","success":false}.

2. Issue is reproducible for resultCodes * "success":false*.

## Expected result
As described in requirement:
<<In case UnubscribeVehicleData request is trying to unsubscribe the parameter the application is not yet subscribed for (even if the request contains at least one subscribed parameter), SDL must:
1) ignore not subscribed items and transfer subscribed params of UnsubscribeVehicleData to HMI>>

SDL->MOB [version: 2, frameType: 1, encryption: false, serviceType: 7, frameInfo: 0, messageId: 14] :
{"resultCode":"IGNORED","success":false} 

_**Notes:**_
Current example is for USER_DISALLOWED but this applies for all negative result codes such as ABORTED, etc.
Please find attached sdl and ATF logs.
```
{code}
To reproduce using ATF need (checked on clean Ubuntu 14.04):
1. clone https://github.com/CustomSDL/sdl_atf_test_scripts/ repository
2. Goto cloned repo, in config.py of specify
sdl_repository = "https://github.com/smartdevicelink/sdl_core/"
sdl_branch = "release/4.2.0"
atf_repository = "https://github.com/smartdevicelink/sdl_atf/"
atf_branch = "962e1eff8664d97af5e59ec4e22f39b9ea76f5eb"
3. sudo apt-get install libexpat1-dev openssh-server libgl1-mesa-dev
4.sudo add-apt-repository ppa:ubuntu-toolchain-r/test
5 ./setup_env.sh
6. fab -H localhost prepare
7. Goto ~/SmartDeviceLinkCore/test_run
8. ./start.sh <path_to_attached_script> --sdl_core SDL_bin/
{code}
```
# Environment
SDL:
Repository: https://github.com/smartdevicelink/sdl_core/
Tag: 4.2.0
commit: a6c32b45832653d6b851be9b19355fa35f377e07
ATF version: 2.2 / 962e1eff8664d97a 

# Attachments
[att_issue#996.zip](https://github.com/smartdevicelink/sdl_core/files/576060/att_issue.996.zip).

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
The main idea here is to perform subscriptions only after SDL receives successful result from HMI. Currently SDL subscribes on requested vehicle data right after `SubscribeVehicleData` request received, event if HMI returns erroneous result. This is a reason why `UnsubscribedVehicleData` returns wrong result code on its call.

In case of erroneous result code SDL should not subscribe to requested VehicleData. 

Changes of this pull request was based on PR #1410 
Fixes #996

### CODE REVIEW

**Comment by AKalinich-Luxoft** [comment]
@AByzhynar, @LitvinenkoIra, @LuxoftAKutsan, @dev-gh please review

File: src/components/application_manager/src/commands/mobile/subscribe_vehicle_data_request.cc [hunk 1]
```diff
@@ -250,6 +250,15 @@ void SubscribeVehicleDataRequest::on_event(const event_engine::Event& event) {
       result_code = mobile_apis::Result::IGNORED;
       response_info = "Already subscribed on some provided VehicleData.";
     }
+
+    if (!vi_waiting_for_subscribe_.empty()) {
```
Comment (dev-gh) [inline src/components/application_manager/src/commands/mobile/subscribe_vehicle_data_request.cc]: @AKalinich-Luxoft 
Shouldn't this container to be cleaned off succeeded subscriptions?

Comment (AKalinich-Luxoft) [inline src/components/application_manager/src/commands/mobile/subscribe_vehicle_data_request.cc]: @dev-gh I think it's redundant here because this container is used only once after response received and after that this object will be destroyed.

File: src/components/application_manager/src/commands/mobile/subscribe_vehicle_data_request.cc [hunk 2]
```diff
@@ -250,6 +250,15 @@ void SubscribeVehicleDataRequest::on_event(const event_engine::Event& event) {
...
+      LOG4CXX_DEBUG(logger_, "Subscribing to all pending VehicleData");
+      VehicleInfoSubscriptions::const_iterator key =
```
Comment (JackLivio) [inline src/components/application_manager/src/commands/mobile/subscribe_vehicle_data_request.cc]: Shouldn't there be locks placed around `vi_waiting_for_subscribe_`? its use here and the `vi_waiting_for_subscribe_.insert` below could be called concurrently?

Comment (AKalinich-Luxoft) [inline src/components/application_manager/src/commands/mobile/subscribe_vehicle_data_request.cc]: @JackLivio there is no reasons to place locks around this variable.
`vi_waiting_for_subscribe_.insert` is in `SubscribeVehicleDataRequest::Run` which checks all request param and then sends request to HMI, and the second occurrence is in `SubscribeVehicleDataRequest::on_event` which is called when response from HMI will be received so its physically not possible to access this variable concurrently because response could not be received until request will not be sent.
