### PR TITLE
Do not send two END_SERVICE requests during streaming switching between apps 

### LINKED ISSUE #3328: SDL sends two END_SERVICE requests during streaming switching between apps
### Bug Report
SDL sends two END_SERVICE requests during streaming switching between apps

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile device, register 2 mobile applications:
- `App_1`: `PROJECTION`
- `App_2`: `NAVIGATION`
2. Activate `App_1` and start streaming
3. Activate `App_2` and start streaming

SDL does:
   - send OnHMIStatus(FULL, STREAMABLE) notification to `App_2`
   - send OnHMIStatus(LIMITED, NOT_STREAMABLE) notification to `App_1`
   - send Navi.OnVideoDataStreaming(false) notification to HMI
   - start 1st 'StopStreamingTimeout' timeout

Once timeout is expired SDL does:
   - send Navi.StopStream(App_1) request to HMI
   - send EndService(VIDEO) request to `App_1`
   - start 2nd 'StopStreamingTimeout' timeout
4. `App_1` stops streaming but does not send `EndServiceAck` within 2nd `StopStreamingTimeout` timeout

##### Expected Behavior
Once timeout is expired SDL does:
   - send OnAppInterfaceUnregistered(PROTOCOL_VIOLATION) notification to `App_1`
   - send BC.OnAppUnregistered(unexpectedDisconnect=false) notification to HMI
   - not send 2nd `EndService` request to `App_1`

##### Observed Behavior
Once timeout is expired SDL does:
   - send OnAppInterfaceUnregistered(PROTOCOL_VIOLATION) notification to `App_1`
   - send BC.OnAppUnregistered(unexpectedDisconnect=false) notification to HMI
   - send 2nd `EndService` request to `App_1`

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/release/6.1.0 (5954b40392)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - Script: [3139_04_Stop_streaming_forcibly_app_does_not_send_EndServiceAck](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/6_1/3139_04_Stop_streaming_forcibly_app_does_not_send_EndServiceAck.lua)
 - Report and Logs: [2020-04-08_13-42-44.tar.gz](https://github.com/smartdevicelink/sdl_core/files/4451984/2020-04-08_13-42-44.tar.gz)

### PR DESCRIPTION
**Pull request by LitvinenkoIra**
Fixes #3328 

This PR is **[not ready]** for review.

### Risk
This PR makes **[no]** API changes.

### Testing Plan
[ 3139_04_Stop_streaming_forcibly_app_does_not_send_EndServiceAck](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/6_1/3139_04_Stop_streaming_forcibly_app_does_not_send_EndServiceAck.lua) 

### Summary
Check if EndService has been sent before sending it during unregistration

### Tasks Remaining:
- [x] Check regression
- [x] Check unit tests

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/application_manager_impl.cc [hunk 1]
```diff
@@ -3215,7 +3215,10 @@ void ApplicationManagerImpl::UnregisterApplication(
     MessageHelper::SendUnsubscribedWayPoints(*this);
   }
 
-  EndNaviServices(app_id);
+  if (navi_app_to_stop_.end() ==
+      std::find(navi_app_to_stop_.begin(), navi_app_to_stop_.end(), app_id)) {
+    EndNaviServices(app_id);
+  }
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_manager_impl.cc:3221]: @LitvinenkoIra Could you be so kind and explain the logic here, please

Comment (LitvinenkoIra) [reply src/components/application_manager/src/application_manager_impl.cc:3221]: @AByzhynar In `EndNaviServices` function we add the `app_id` of application that should complete the services to the `navi_app_to_stop_` collection.
 So here we just need to check - if `app_id` already presents in  `navi_app_to_stop_`  collection -  we don’t need to call EndNaviServices, because we already called it once

**Comment by LitvinenkoIra** [comment]
@theresalech this PR is ready for review. Thank you

File: src/components/application_manager/src/application_manager_impl.cc [hunk 2]
```diff
@@ -3887,6 +3890,8 @@ void ApplicationManagerImpl::CloseNaviApp() {
         commands::Command::SOURCE_SDL);
     UnregisterApplication(app_id, ABORTED);
   }
+
+  navi_app_to_stop_.pop_front();
```
Comment (jacobkeeler) [inline src/components/application_manager/src/application_manager_impl.cc:3894]: Seems this is more likely to cause a race condition, perhaps it should be lock-protected?

File: src/components/application_manager/src/application_manager_impl.cc [hunk 3]
```diff
@@ -3215,7 +3215,10 @@ void ApplicationManagerImpl::UnregisterApplication(
     MessageHelper::SendUnsubscribedWayPoints(*this);
   }
 
-  EndNaviServices(app_id);
+  if (navi_app_to_stop_.end() ==
+      std::find(navi_app_to_stop_.begin(), navi_app_to_stop_.end(), app_id)) {
```
Comment (jacobkeeler) [inline src/components/application_manager/src/application_manager_impl.cc:3219]: Perhaps this check should be moved into the `EndNaviServices` function

**Comment by LitvinenkoIra** [comment]
@jacobkeeler Thank you for the review.
I will make the necessary changes, check the regression and let you know when this PR is ready for re-review.

File: src/components/application_manager/src/application_manager_impl.cc [hunk 4]
```diff
@@ -3894,7 +3920,10 @@ void ApplicationManagerImpl::CloseNaviApp() {
     UnregisterApplication(app_id, ABORTED);
   }
 
-  navi_app_to_stop_.pop_front();
+  {
+    sync_primitives::AutoLock lock(navi_app_to_stop_lock_);
+    navi_app_to_stop_.pop_front();
+  }
```
Comment (jacobkeeler) [inline src/components/application_manager/src/application_manager_impl.cc:3926]: I think this should stay at the top of the function, otherwise the timer could theoretically fire for 2 different apps, but the same app ID would be read twice

Comment (jacobkeeler) [reply src/components/application_manager/src/application_manager_impl.cc:3926]: Ah, I see that this would cause issues, perhaps you could put this value to the end of the queue and then remove it from there after?

File: src/components/application_manager/src/application_manager_impl.cc [hunk 5]
```diff
@@ -3863,9 +3891,13 @@ void ApplicationManagerImpl::CloseNaviApp() {
...
   using namespace mobile_apis::Result;
-  DCHECK_OR_RETURN_VOID(!navi_app_to_stop_.empty());
-  uint32_t app_id = navi_app_to_stop_.front();
-  navi_app_to_stop_.pop_front();
+  uint32_t app_id;
+
+  {
+    sync_primitives::AutoLock lock(navi_app_to_stop_lock_);
+    DCHECK_OR_RETURN_VOID(!navi_app_to_stop_.empty());
+    app_id = navi_app_to_stop_.front();
```
Comment (jacobkeeler) [inline src/components/application_manager/src/application_manager_impl.cc:3899]:
```suggestion
    app_id = navi_app_to_stop_.front();
    navi_app_to_stop_.pop_front();
    navi_app_to_stop_.push_back(app_id);
```
As a suggestion

File: src/components/application_manager/src/application_manager_impl.cc [hunk 6]
```diff
@@ -3887,6 +3919,11 @@ void ApplicationManagerImpl::CloseNaviApp() {
         commands::Command::SOURCE_SDL);
     UnregisterApplication(app_id, ABORTED);
   }
+
+  {
+    sync_primitives::AutoLock lock(navi_app_to_stop_lock_);
+    navi_app_to_stop_.pop_front();
```
Comment (jacobkeeler) [inline src/components/application_manager/src/application_manager_impl.cc:3925]:
```suggestion
    auto it = std::find(navi_app_to_stop_.begin(), navi_app_to_stop_.end(), app_id);
    if (navi_app_to_stop_.end() != it) {
        navi_app_to_stop_.erase(it);
    }
```
As a suggestion

File: src/components/application_manager/src/application_manager_impl.cc (hunk 4 above)
Comment (LitvinenkoIra) [reply src/components/application_manager/src/application_manager_impl.cc:3932]: This works, but the changes are not obvious, since this is a regression after https://github.com/smartdevicelink/sdl_core/pull/2425 I will try to rework that fix, and do not call EndService inside the UnregisterApp. I'll let you know when the changes are ready

Comment (LitvinenkoIra) [reply src/components/application_manager/src/application_manager_impl.cc]: @jacobkeeler I forced the commits to make the good commit history. I reworked the fix from #2425 in 898b824f78954871c0a31f5f6dea7f095827f959 and now SDL works as expected in accordance with https://github.com/smartdevicelink/sdl_core/issues/1409 and https://github.com/smartdevicelink/sdl_core/issues/3328
Now I'm checking the regression and I will let you know when it will be passed.

**Comment by jacobkeeler** [comment]
@LitvinenkoIra We would appreciate if developers did not force push to a PR that is in review. Force pushing makes it difficult to review a PR because we cannot tell what was changed since the last commit. In general, please do not rebase and do not force push against the SDL repositories. Instead, you can merge the current develop branch into your PR branch. Thank you

**Comment by LitvinenkoIra** [comment]
@jacobkeeler Ok, got it. Sorry for that, I just removed unnecessary changes, because we don't need all that logic with the `navi_to_stop_` queue. 
I moved the function `EndNaviServices` from `UnregisterApplication` to `UnregisterAllApplications()` and now SDL works as expected. 
You can find the protection for `navi_to_stop_` here 20109cf 
And fix for the issue here 898b824

File: src/components/application_manager/src/application_manager_impl.cc [hunk 7]
```diff
@@ -3215,8 +3223,6 @@ void ApplicationManagerImpl::UnregisterApplication(
     MessageHelper::SendUnsubscribedWayPoints(*this);
   }
 
-  EndNaviServices(app_id);
```
Comment (jacobkeeler) [inline src/components/application_manager/src/application_manager_impl.cc:3218]: Now `EndService` will not be sent for other unregister reasons, such as changing the system language
