### PR TITLE
Fix reading of Consumer Friendly Messages in PROPRIETARY mode

### LINKED ISSUE #3024: Consumer friendly messages are not properly read in PROPRIETARY policy mode
### Bug Report
Consumer friendly messages are not properly read in PROPRIETARY policy mode, cause is missing fields in `GatherConsumerFriendlyMessages`: https://github.com/smartdevicelink/sdl_core/blob/develop/src/components/policy/policy_regular/src/sql_pt_representation.cc#L683

##### Reproduction Steps
1. Start Core
2. Stop Core, `messages` table is properly populated in policy table
3. Start Core

##### Expected Behavior
`messages` table is properly populated in policy table

##### Observed Behavior
`messages` table is missing all text field entries, only `language` and `code` are populated for each entry

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: develop
* Testing Against: Modified hello-sdl-android

### PR DESCRIPTION
**Pull request by jacobkeeler**
Fixes #3024 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
Fix reading of Consumer Friendly Messages in PROPRIETARY mode

##### Bug Fixes
* Fix reading of Consumer Friendly Messages in PROPRIETARY mode

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/policy/policy_regular/src/sql_pt_representation.cc [hunk 1]
```diff
@@ -680,10 +680,35 @@ bool SQLPTRepresentation::GatherConsumerFriendlyMessages(
...
+      msg.line1 = query.GetString(3);
+      msg.line2 = query.GetString(4);
+      msg.text_body = query.GetString(5);
       msg.message_code = query.GetString(7);
-      std::string language = query.GetString(6);
 
-      (*messages->messages)[msg.message_code].languages[language];
+      std::string language = query.GetString(6);
+      if (!msg.tts.empty()) {
+        *(*messages->messages)[msg.message_code].languages[language].tts =
```
Comment (AByzhynar) [inline src/components/policy/policy_regular/src/sql_pt_representation.cc]: @jacobkeeler This dereferencing looks a bit confusing. Is it possible to create a reference to ` *(*messages->messages)[msg.message_code].languages` and use it like: 
```cpp
languages[language].tts = msg.tts 
```  

or even better to create reference to the entire expression `*(*messages->messages)[msg.message_code].languages[language]`
and use it like: 

```cpp
languages.tts = msg.tts
languages.label = msg.label

```

Comment (jacobkeeler) [reply src/components/policy/policy_regular/src/sql_pt_representation.cc]: @AByzhynar This was copied from the EXTERNAL_PROPRIETARY policy code, so I will make this change there as well.

**Comment by jacobkeeler** [comment]
@AByzhynar addressed comments
