### PR TITLE
Fix PROPRIETARY retry sequence

### LINKED ISSUE #3232: SDLCore failed to retry updating the Policy Table
### Bug Report
SDLCore failed to retry updating the Policy Table

##### Preconditions
Connect the head unit to any Android/iOS phone

##### Reproduction Steps
1. The first time of updating Policy Table is failed that caused by network problems
2. Fix the network problems soon.

##### Expected Behavior
SDLCore retries updating Policy Table is successful.

##### Observed Behavior
SDLCore retries updating Policy Table is failed.
It sends the correct URL to the phone for the first time of updating the Policy Table.
But when a retry is requested, it sends an empty URL to the phone,
so it certainly failed to update the Policy Table.

##### OS & Version Information
* SDL Core Version: SDL Core 6.0.1
* Testing Against:SDL Core 6.0.1 + HMI running on our development environment.

##### Occurrence:
100%

##### Recovery Method:
None

### PR DESCRIPTION
**Pull request by jacobkeeler**
Fixes #3232

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
1. Edit the policy table module config:
```
          ...
          "timeout_after_x_seconds": 5,
            "seconds_between_retries": [
                1,
                1,
                1,
                1,
                1
            ],
            "endpoints": {
                "0x07": {
                    "default": [
                        "http://smartdevicelink.com/api/1/policies/example1"
                    ],
                    "8675309": [
                        "http://smartdevicelink.com/api/1/policies/example2"
                    ],
                    "123456789": [
                        "http://smartdevicelink.com/api/1/policies/example3",
                        "http://smartdevicelink.com/api/1/policies/example4"
                    ]
                },
                "0x04": {
                    "default": [
                        "http://x.x.x.x:3000/api/1/softwareUpdate"
                    ]
                },
                "queryAppsUrl": {
                    "default": [
                        "http://sdl.shaid.server"
                    ]
                },
                "lock_screen_icon_url": {
                    "default": [
                        "http://i.imgur.com/TgkvOIZ.png"
                    ]
                },
                "custom_vehicle_data_mapping_url": {
                    "default": [
                        "http://x.x.x.x:3000/api/1/vehicleDataMap"
                    ]
                }
            },
            ...
```
2. Connect both apps with specific dummy URLs (`8675309` and `123456789`) in the `module_config.endpoints.0x07` section. 
3. Verify that all URLs pertaining to an app (including default URLs) are sent during the retry process before another application is chosen for performing a PTU.

### Summary
For PROPRIETARY policy updates, Core is responsible for the retry sequence and cycling through update URLs. This fixes the PROPRIETARY flow with a few specific changes:

1. Apps for PTU are chosen randomly using the existing process, but after an application is chosen, all URLs that are associated with that application will be attempted before moving onto the next application.
2. When an OnSystemRequest(PROPRIETARY) is received from the HMI in PROPRIETARY policy mode, Core will ignore the `appID` and `url` properties and populate them itself. This is because Core is responsible for providing these fields in PROPRIETARY mode.

##### Bug Fixes
* Fixes PROPRIETARY policy flow and URL cycling logic for PROPRIETARY and HTTP flow

### Tasks Remaining:
- [x] Fix Unit Tests

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/include/application_manager/policies/policy_handler.h [hunk 1]
```diff
@@ -412,11 +423,27 @@ class PolicyHandler : public PolicyHandlerInterface,
...
-   * @brief Chooses random application id to be used for snapshot sending
-   * considering HMI level
+   * @brief Chooses and stores random application id to be used for snapshot
+   * sending considering HMI level
+   * @param iteration_type The iteration type of the request. If RetryIteration,
+   * the previously chosen app ID (via ChoosePtuApplication) will be returned if
+   * available
+   * @return Application id or 0, if there are no suitable applications
+   */
+  uint32_t ChoosePtuApplication(
```
Comment (JackLivio) [inline src/components/application_manager/include/application_manager/policies/policy_handler.h:433]: Rename to `ChoosePTUApplication`? PTU is all caps in the param usage below.

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 2]
```diff
@@ -420,9 +423,28 @@ bool PolicyHandler::ClearUserConsent() {
   return policy_manager_->ResetUserConsent();
 }
 
-uint32_t PolicyHandler::GetAppIdForSending() const {
+uint32_t PolicyHandler::ChoosePtuApplication(
```
Comment (JackLivio) [inline src/components/application_manager/src/policies/policy_handler.cc:426]: What is the purpose of this method if it just returns GetAppIdForSending's response?

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 3]
```diff
@@ -459,7 +480,8 @@ uint32_t PolicyHandler::GetAppIdForSending() const {
     return 0;
   }
 
-  return ChooseRandomAppForPolicyUpdate(apps_with_none_level);
+  app_id = ChooseRandomAppForPolicyUpdate(apps_with_none_level);
```
Comment (JackLivio) [inline src/components/application_manager/src/policies/policy_handler.cc:483]: Why this change?

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 4]
```diff
@@ -1594,22 +1627,60 @@ void PolicyHandler::OnSnapshotCreated(const BinaryMessage& pt_string,
...
+    SendMessageToSDK(pt_string, url, app_id_for_sending);
+  }
+#endif  // PROPRIETARY_MODE
+}
+
+std::string PolicyHandler::GetNextUpdateUrl(
+    const PTUIterationType iteration_type, uint32_t& app_id) {
+  LOG4CXX_AUTO_TRACE(logger_);
+  POLICY_LIB_CHECK_OR_RETURN(std::string());
+  app_id = ChoosePtuApplication(iteration_type);
```
Comment (JackLivio) [inline src/components/application_manager/src/policies/policy_handler.cc:1645]: Modifying a function parameter?

**Comment by JackLivio** [comment]
@jacobkeeler Also fixes #1210

File: src/components/application_manager/src/policies/policy_handler.cc (hunk 2 above)
Comment (jacobkeeler) [reply src/components/application_manager/src/policies/policy_handler.cc:426]: `GetAppIdForSending` is a const method, so internal variables cannot be changed in the function. This function edits the `last_ptu_app_id_` field so that it can be cached for retry attempts.

File: src/components/application_manager/src/policies/policy_handler.cc (hunk 3 above)
Comment (jacobkeeler) [reply src/components/application_manager/src/policies/policy_handler.cc:483]: Probably as a result of changes that were since removed, I can revert this bit

**Comment by JackLivio** [comment]
@zhouxin627 We plan on merging this pr today. The issue is resolved for us. Let us know if you run into any issues.

**Comment by zhouxin627** [comment]
Hi @JackLivio @jacobkeeler, We suppose that our issue has been fixed. Thank you for your help.
