### PR TITLE
Start the new PTU after a failed retry sequence

### LINKED ISSUE #3136: SDL does not start the new PTU after a failed retry sequence in case some trigger occurs during the retry sequence
### Bug Report
SDL does not start the new PTU after a failed retry sequence in case some trigger occurs during the retry sequence

##### Reproduction Steps
1. New App1 is registered
2. SDL starts the PTU
3. Mobile app receives `BC.OnSystemRequest` notification but not provide the update
4. SDL starts the retry sequence
5. App2 is registered during retry sequence

##### Expected Behavior
After retry sequence is finished SDL sends `SDL.OnStatusUpdate(UPDATE_NEEDED)` notification to HMI and then `BC.PolicyUpdate` request to HMI to start the new PTU sequence after retry.

##### Observed Behavior
SDL does not send `BC.PolicyUpdate` request to HMI after retry sequence

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/891497bc9fb23434242dbe92e1f13dd1273fcb21
* ATF: https://github.com/smartdevicelink/sdl_atf/commit/37da7aba8929e14dbd692befdea8540c5dd1dbbb
* Script: TBA

##### Logs
TBA

### PR DESCRIPTION
**Pull request by ydementieiev**
Fixes #3136 

This PR is **[ready]** for review.

### Risk
This PR makes **[no]** API changes.

### Summary
SDL should start the new PTU after a failed retry sequence in case some trigger occurs during the retry sequence.
Provided changes allow to perform the following actions:
- Finish failed update with SDL.OnStatusUpdate(UPDATE_NEEDED);
- Send SDL.OnStatusUpdate(UPDATE_NEEDED) and request PTU for applications which were added during the previous update;
- Skip PTU for application which was registered  during application list update timer;
- Skip PTU for  application with the same policy_id;

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by AKalinich-Luxoft** [comment]
@ydementieiev please sign CLA

File: src/components/application_manager/include/application_manager/application_manager_impl.h [hunk 1]
```diff
@@ -1586,6 +1586,8 @@ class ApplicationManagerImpl
 
   uint32_t apps_size_;
 
+  bool is_registered_in_timeout_;
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/include/application_manager/application_manager_impl.h]: @ydementieiev suggest to use atomic bool as timer might be in a data race with another thread

File: src/components/application_manager/include/application_manager/policies/policy_handler.h [hunk 2]
```diff
@@ -183,9 +183,7 @@ class PolicyHandler : public PolicyHandlerInterface,
                          const std::string& policy_app_id,
                          const std::string& hmi_level) OVERRIDE;
 
-#ifndef EXTERNAL_PROPRIETARY_MODE
-  void OnPTUTimeOut() OVERRIDE;
-#endif
+  void OnPTUTimeOut();
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/include/application_manager/policies/policy_handler.h]: @ydementieiev OVERRIDE?

File: src/components/application_manager/include/application_manager/policies/policy_handler.h [hunk 3]
```diff
@@ -583,6 +593,19 @@ class PolicyHandler : public PolicyHandlerInterface,
...
+   * @param new_app_id app_id for this application
+   * @param policy_id policy_id for this application
+   */
+  void OnAddedNewApplicationToAppList(const uint32_t new_app_id,
+                                      const std::string policy_id) OVERRIDE;
+
+  /**
+   * @brief Application queue ready for PTU
+   */
+  std::vector<uint32_t> queue_applications_for_ptu_;
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/include/application_manager/policies/policy_handler.h]: @ydementieiev i think [queue](http://www.cplusplus.com/reference/queue/queue/) will be better container for your purposes

File: src/components/application_manager/include/application_manager/policies/policy_handler.h [hunk 4]
```diff
@@ -422,6 +420,18 @@ class PolicyHandler : public PolicyHandlerInterface,
    */
   uint32_t GetAppIdForSending() const OVERRIDE;
 
+  /**
+   * @brief Add application to PTU queue if don't have application
+   * with the same app_id
+   * @param new_app_id app id new application
+   */
+  void AddNewApplicationIdToPTUQueue(const uint32_t new_app_id);
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/include/application_manager/policies/policy_handler.h]: @ydementieiev can be renamed to `PushAppIdToQueue` and `PopAppIdFromQueue`

File: src/components/application_manager/include/application_manager/policies/policy_handler.h (hunk 3 above)
Comment (AKalinich-Luxoft) [reply src/components/application_manager/include/application_manager/policies/policy_handler.h]: @ydementieiev or even [set](http://www.cplusplus.com/reference/set/set/) as you want to keep only unique app id in your container

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 5]
```diff
@@ -2205,6 +2233,15 @@ void PolicyHandler::OnAppsSearchCompleted(const bool trigger_ptu) {
   policy_manager_->OnAppsSearchCompleted(trigger_ptu);
 }
 
+void PolicyHandler::OnAddedNewApplicationToAppList(
+    const uint32_t new_app_id, const std::string policy_id) {
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/src/policies/policy_handler.cc]: @ydementieiev nice to have auto trace here

File: src/components/include/policy/policy_external/policy/policy_manager.h [hunk 6]
```diff
@@ -533,6 +533,12 @@ class PolicyManager : public usage_statistics::StatisticsManager,
    */
   virtual void OnAppsSearchCompleted(const bool trigger_ptu) = 0;
 
+  /**
+   * @brief Change applicatios count ready for PTU
```
Comment (AKalinich-Luxoft) [inline src/components/include/policy/policy_external/policy/policy_manager.h]: @ydementieiev typo

File: src/components/include/policy/policy_regular/policy/policy_manager.h [hunk 7]
```diff
@@ -524,6 +524,12 @@ class PolicyManager : public usage_statistics::StatisticsManager,
    */
   virtual void OnAppsSearchCompleted(const bool trigger_ptu) = 0;
 
+  /**
+   * @brief Change applicatios count ready for PTU
```
Comment (AKalinich-Luxoft) [inline src/components/include/policy/policy_regular/policy/policy_manager.h]: @ydementieiev typo

File: src/components/policy/policy_external/include/policy/policy_manager_impl.h [hunk 8]
```diff
@@ -608,6 +608,12 @@ class PolicyManagerImpl : public PolicyManager {
    */
   void OnAppsSearchCompleted(const bool trigger_ptu) OVERRIDE;
 
+  /**
+   * @brief Change applicatios count ready for PTU
```
Comment (AKalinich-Luxoft) [inline src/components/policy/policy_external/include/policy/policy_manager_impl.h]: @ydementieiev typo

File: src/components/policy/policy_external/include/policy/policy_manager_impl.h [hunk 9]
```diff
@@ -1096,6 +1102,11 @@ class PolicyManagerImpl : public PolicyManager {
   bool IsPTValid(std::shared_ptr<policy_table::Table> policy_table,
                  policy_table::PolicyTableType type) const;
 
+  /**
+   * @brief Check that application for PTU more than zero
```
Comment (AKalinich-Luxoft) [inline src/components/policy/policy_external/include/policy/policy_manager_impl.h]: @ydementieiev
```suggestion
   * @brief Check that new applications for PTU were registered
```

File: src/components/policy/policy_external/include/policy/policy_manager_impl.h [hunk 10]
```diff
@@ -1305,6 +1316,11 @@ class PolicyManagerImpl : public PolicyManager {
    */
   uint32_t retry_sequence_index_;
 
+  /**
+   * @brief Count application ready for PTU
+   */
+  uint32_t count_application_;
```
Comment (AKalinich-Luxoft) [inline src/components/policy/policy_external/include/policy/policy_manager_impl.h]: @ydementieiev 
```suggestion
  uint32_t applications_count_;
```

File: src/components/policy/policy_external/src/update_status_manager.cc [hunk 11]
```diff
@@ -86,6 +86,11 @@ void UpdateStatusManager::OnUpdateSentOut(uint32_t update_timeout) {
   ProcessEvent(kOnUpdateSentOut);
 }
 
+void UpdateStatusManager::OnUpdatePostponed() {
+  LOG4CXX_AUTO_TRACE(logger_);
+  ProcessEvent(kPostponedUpdate);
```
Comment (AKalinich-Luxoft) [inline src/components/policy/policy_external/src/update_status_manager.cc]: @ydementieiev consider using of `SetPostponedStatus` - maybe you can use it instead of `kPostponedUpdate`

File: src/components/policy/policy_external/src/policy_manager_impl.cc [hunk 12]
```diff
@@ -550,6 +555,10 @@ void PolicyManagerImpl::OnPTUFinished(const PtProcessingResult ptu_result) {
 
   update_status_manager_.OnValidUpdateReceived();
 
+  if (HasApplicationForPTU()) {
```
Comment (mked-luxoft) [inline src/components/policy/policy_external/src/policy_manager_impl.cc]: is this condition independent from `ptu_result`?

File: src/components/policy/policy_regular/include/policy/policy_manager_impl.h [hunk 13]
```diff
@@ -1046,6 +1052,11 @@ class PolicyManagerImpl : public PolicyManager {
    */
   void OnPTUIterationTimeout();
 
+  /**
+   * @brief Check that application for PTU more than zero
+   */
+  bool HasApplicationForPTU();
```
Comment (mked-luxoft) [inline src/components/policy/policy_regular/include/policy/policy_manager_impl.h]: i think this method can be const

File: src/components/policy/policy_regular/src/policy_manager_impl.cc [hunk 14]
```diff
@@ -70,14 +70,17 @@ PolicyManagerImpl::PolicyManagerImpl()
...
           "Retry sequence timer",
           new timer::TimerTaskImpl<PolicyManagerImpl>(
               this, &PolicyManagerImpl::OnPTUIterationTimeout))
     , ignition_check(true)
     , retry_sequence_url_(0, 0, "")
     , send_on_update_sent_out_(false)
-    , trigger_ptu_(false) {}
+    , trigger_ptu_(false)
+    , ptu_requested_(false)
+    , last_registered_app_id_("") {}
```
Comment (mked-luxoft) [inline src/components/policy/policy_regular/src/policy_manager_impl.cc]: is it `policy_app_id`? if so, then i think that the variable's name should be changed accordingly

File: src/components/policy/policy_regular/src/update_status_manager.cc [hunk 15]
```diff
@@ -116,6 +118,10 @@ void UpdateStatusManager::OnNewApplicationAdded(const DeviceConsent consent) {
     return;
   }
   app_registered_from_non_consented_device_ = false;
+  if (last_update_was_failed_) {
+    last_update_was_failed_ = false;
+    ProcessEvent(kPostponedUpdate);
```
Comment (mked-luxoft) [inline src/components/policy/policy_regular/src/update_status_manager.cc]: are you sure that we still need to call `ProcessEvent(kOnNewAppRegistered);` if we enter this condition?

File: src/components/application_manager/include/application_manager/policies/policy_handler.h (hunk 3 above)
Comment (mked-luxoft) [reply src/components/application_manager/include/application_manager/policies/policy_handler.h]: @ydementieiev i think this container might need access synchronization

File: src/components/policy/policy_external/src/policy_manager_impl.cc (hunk 12 above)
Comment (ydementieiev) [reply src/components/policy/policy_external/src/policy_manager_impl.cc]: @mked-luxoft No, no matter what the `ptu_result` will be from last update, we need set status to UPDATE_NEEDE for next ptu

File: src/components/application_manager/include/application_manager/policies/policy_handler.h (hunk 2 above)
Comment (ydementieiev) [reply src/components/application_manager/include/application_manager/policies/policy_handler.h]: @AKalinich-Luxoft   `EXTERNAL_PROPRIETARY_MODE` build failed with `OVERRIDE`

File: src/components/application_manager/include/application_manager/application_manager_impl.h (hunk 1 above)
Comment (ydementieiev) [reply src/components/application_manager/include/application_manager/application_manager_impl.h]: @AKalinich-Luxoft done in [fe7b393](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/fe7b393fe80f89ac9137d6dd9b41a0dfd6ba28c6)

File: src/components/application_manager/include/application_manager/policies/policy_handler.h (hunk 3 above)
Comment (ydementieiev) [reply src/components/application_manager/include/application_manager/policies/policy_handler.h]: @AKalinich-Luxoft used set and add AutoLock for work with this container in [fe7b393](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/fe7b393fe80f89ac9137d6dd9b41a0dfd6ba28c6)

File: src/components/application_manager/include/application_manager/policies/policy_handler.h (hunk 4 above)
Comment (ydementieiev) [reply src/components/application_manager/include/application_manager/policies/policy_handler.h]: @AKalinich-Luxoft done in [fe7b393](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/fe7b393fe80f89ac9137d6dd9b41a0dfd6ba28c6)

File: src/components/application_manager/src/policies/policy_handler.cc (hunk 5 above)
Comment (ydementieiev) [reply src/components/application_manager/src/policies/policy_handler.cc]: @AKalinich-Luxoft done in [fe7b393](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/fe7b393fe80f89ac9137d6dd9b41a0dfd6ba28c6)

File: src/components/include/policy/policy_external/policy/policy_manager.h (hunk 6 above)
Comment (ydementieiev) [reply src/components/include/policy/policy_external/policy/policy_manager.h]: @AKalinich-Luxoft done in [fe7b393](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/fe7b393fe80f89ac9137d6dd9b41a0dfd6ba28c6)

File: src/components/policy/policy_external/include/policy/policy_manager_impl.h (hunk 8 above)
Comment (ydementieiev) [reply src/components/policy/policy_external/include/policy/policy_manager_impl.h]: @AKalinich-Luxoft done in [fe7b393](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/fe7b393fe80f89ac9137d6dd9b41a0dfd6ba28c6)

File: src/components/policy/policy_external/include/policy/policy_manager_impl.h (hunk 9 above)
Comment (ydementieiev) [reply src/components/policy/policy_external/include/policy/policy_manager_impl.h]: @AKalinich-Luxoft done in [fe7b393](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/fe7b393fe80f89ac9137d6dd9b41a0dfd6ba28c6)

File: src/components/policy/policy_external/include/policy/policy_manager_impl.h (hunk 10 above)
Comment (ydementieiev) [reply src/components/policy/policy_external/include/policy/policy_manager_impl.h]: @mked-luxoft  renamed [fe7b393](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/fe7b393fe80f89ac9137d6dd9b41a0dfd6ba28c6)

File: src/components/application_manager/include/application_manager/policies/policy_handler.h [hunk 16]
```diff
@@ -583,6 +593,19 @@ class PolicyHandler : public PolicyHandlerInterface,
    */
   void OnAppsSearchCompleted(const bool trigger_ptu) OVERRIDE;
 
+  /**
+   * @brief New application was added to application list
+   * @param new_app_id app_id for this application
+   * @param policy_id policy_id for this application
+   */
+  void OnAddedNewApplicationToAppList(const uint32_t new_app_id,
+                                      const std::string policy_id) OVERRIDE;
```
[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/application_manager/include/application_manager/policies/policy_handler.h]: @mked-luxoft  done [fe7b393](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/fe7b393fe80f89ac9137d6dd9b41a0dfd6ba28c6)

File: src/components/include/application_manager/policies/policy_handler_interface.h [hunk 17]
```diff
@@ -410,6 +410,14 @@ class PolicyHandlerInterface : public VehicleDataItemProvider {
    */
   virtual void OnAppsSearchCompleted(const bool trigger_ptu) = 0;
 
+  /**
+   * @brief Notify that new applocation was added to application list
```
[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/include/application_manager/policies/policy_handler_interface.h]: @mked-luxoft  done [fe7b393](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/fe7b393fe80f89ac9137d6dd9b41a0dfd6ba28c6)

File: src/components/policy/policy_regular/include/policy/policy_manager_impl.h (hunk 13 above)
Comment (ydementieiev) [reply src/components/policy/policy_regular/include/policy/policy_manager_impl.h]: @mked-luxoft  done [fe7b393](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/fe7b393fe80f89ac9137d6dd9b41a0dfd6ba28c6)

File: src/components/policy/policy_regular/src/policy_manager_impl.cc (hunk 14 above)
Comment (ydementieiev) [reply src/components/policy/policy_regular/src/policy_manager_impl.cc]: @mked-luxoft  done [fe7b393](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/fe7b393fe80f89ac9137d6dd9b41a0dfd6ba28c6)

File: src/components/policy/policy_regular/src/update_status_manager.cc (hunk 15 above)
Comment (ydementieiev) [reply src/components/policy/policy_regular/src/update_status_manager.cc]: @mked-luxoft  `ProcessEvent(kPostponedUpdate) `added for extra call `UPDATE_NEEDED` for new ptu if last was finished with the same status. I tried remove `ProcessEvent(kOnNewAppRegistered)` but it entailed a lot of regressions

File: src/components/include/policy/policy_regular/policy/policy_manager.h (hunk 7 above)
Comment (ydementieiev) [reply src/components/include/policy/policy_regular/policy/policy_manager.h]: @AKalinich-Luxoft done in [fe7b393](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/fe7b393fe80f89ac9137d6dd9b41a0dfd6ba28c6)

File: src/components/policy/policy_external/src/update_status_manager.cc (hunk 11 above)
Comment (ydementieiev) [reply src/components/policy/policy_external/src/update_status_manager.cc]: @AKalinich-Luxoft  I tried using `SetPostponedStatus` but always find a new regression after.  Now I renamed `OnUpdatePostponed` to name which more describe what this method do, look please

File: src/components/application_manager/include/application_manager/policies/policy_handler.h [hunk 18]
```diff
@@ -598,13 +598,13 @@ class PolicyHandler : public PolicyHandlerInterface,
    * @param new_app_id app_id for this application
    * @param policy_id policy_id for this application
    */
-  void OnAddedNewApplicationToAppList(const uint32_t new_app_id,
-                                      const std::string policy_id) OVERRIDE;
+  void OnAddedNewApplicationToAppList(const uint32_t& new_app_id,
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/include/application_manager/policies/policy_handler.h]: @ydementieiev there is no need to pass int as a reference

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 19]
```diff
@@ -466,21 +466,16 @@ uint32_t PolicyHandler::GetAppIdForSending() const {
...
-
-  if (std::find(queue_applications_for_ptu_.begin(),
-                queue_applications_for_ptu_.end(),
-                app_id) == queue_applications_for_ptu_.end()) {
-    queue_applications_for_ptu_.push_back(app_id);
-    policy_manager_->OnChangeApplicationCount(
-        queue_applications_for_ptu_.size());
-  }
+  sync_primitives::AutoLock lock(app_id_queue_lock_);
+  queue_applications_for_ptu_.insert(app_id);
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/src/policies/policy_handler.cc]: @ydementieiev check for return result of insert operation. If the same app_id is inserted, count will not be changed

File: src/components/policy/policy_external/include/policy/update_status_manager.h [hunk 20]
```diff
@@ -94,7 +94,7 @@ class UpdateStatusManager {
   /**
    * @brief Postponed update for PTU
    */
-  void OnUpdatePostponed();
+  void OnUpdateForNextInQueue();
```
Comment (AKalinich-Luxoft) [inline src/components/policy/policy_external/include/policy/update_status_manager.h]: @ydementieiev please update description

File: src/components/application_manager/include/application_manager/policies/policy_handler.h (hunk 2 above)
Comment (AKalinich-Luxoft) [reply src/components/application_manager/include/application_manager/policies/policy_handler.h]: @ydementieiev then add pure virtual `OnPTUTimeOut` into interface class for `EXTERNAL_PROPRIETARY_MODE`

File: src/components/application_manager/include/application_manager/policies/policy_handler.h (hunk 18 above)
Comment (ydementieiev) [reply src/components/application_manager/include/application_manager/policies/policy_handler.h]: @AKalinich-Luxoft done [f0f9ced](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/f0f9ced5f7902b7d25d333c8d1559a7e3f374f89)

File: src/components/application_manager/src/policies/policy_handler.cc (hunk 19 above)
Comment (ydementieiev) [reply src/components/application_manager/src/policies/policy_handler.cc]: @AKalinich-Luxoft done [f0f9ced](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/f0f9ced5f7902b7d25d333c8d1559a7e3f374f89)

File: src/components/policy/policy_external/include/policy/update_status_manager.h (hunk 20 above)
Comment (ydementieiev) [reply src/components/policy/policy_external/include/policy/update_status_manager.h]: @AKalinich-Luxoft done [f0f9ced](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/f0f9ced5f7902b7d25d333c8d1559a7e3f374f89)

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 21]
```diff
@@ -469,8 +469,12 @@ uint32_t PolicyHandler::GetAppIdForSending() const {
 void PolicyHandler::PushAppIdToQueue(const uint32_t app_id) {
   LOG4CXX_AUTO_TRACE(logger_);
   sync_primitives::AutoLock lock(app_id_queue_lock_);
-  queue_applications_for_ptu_.insert(app_id);
-  policy_manager_->OnChangeApplicationCount(queue_applications_for_ptu_.size());
+  std::pair<std::set<uint32_t>::iterator, bool> result;
+  result = queue_applications_for_ptu_.insert(app_id);
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/src/policies/policy_handler.cc]: @ydementieiev just
```
const auto result = queue_applications_for_ptu_.insert(app_id);
```

File: src/components/include/application_manager/policies/policy_handler_interface.h [hunk 22]
```diff
@@ -660,6 +660,8 @@ class PolicyHandlerInterface : public VehicleDataItemProvider {
                                  const std::string& policy_app_id,
                                  const std::string& hmi_level) = 0;
 
+  virtual void OnPTUTimeOut() = 0;
```
Comment (AKalinich-Luxoft) [inline src/components/include/application_manager/policies/policy_handler_interface.h]: @ydementieiev please add a description

File: src/components/application_manager/src/policies/policy_handler.cc (hunk 21 above)
Comment (ydementieiev) [reply src/components/application_manager/src/policies/policy_handler.cc]: @AKalinich-Luxoft done [1f93a08](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/1f93a08c7fe53782af96a4a1735f3d4d0cf2bb56)

File: src/components/include/application_manager/policies/policy_handler_interface.h (hunk 22 above)
Comment (ydementieiev) [reply src/components/include/application_manager/policies/policy_handler_interface.h]: @AKalinich-Luxoft done [1f93a08](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/1f93a08c7fe53782af96a4a1735f3d4d0cf2bb56)

File: src/components/application_manager/include/application_manager/policies/policy_handler.h [hunk 23]
```diff
@@ -183,9 +183,11 @@ class PolicyHandler : public PolicyHandlerInterface,
                          const std::string& policy_app_id,
                          const std::string& hmi_level) OVERRIDE;
 
-#ifndef EXTERNAL_PROPRIETARY_MODE
+  /**
+   * @brief OnPTUTimeOut the callback which signals if PTU timeout occured
```
Comment (AByzhynar) [inline src/components/application_manager/include/application_manager/policies/policy_handler.h]: @ydementieiev Suggested changes here: 
 - `the callback which signals if PTU timeout occured` -> `the callback which is performed when PTU timeout occurred`
 - Move description to iface

File: src/components/application_manager/include/application_manager/policies/policy_handler.h [hunk 24]
```diff
@@ -422,6 +424,18 @@ class PolicyHandler : public PolicyHandlerInterface,
    */
   uint32_t GetAppIdForSending() const OVERRIDE;
 
+  /**
+   * @brief Add application to PTU queue if don't have application
```
Comment (AByzhynar) [inline src/components/application_manager/include/application_manager/policies/policy_handler.h]: @ydementieiev `don't have application ...` -> `no application with the same app id exists`

File: src/components/application_manager/include/application_manager/policies/policy_handler.h [hunk 25]
```diff
@@ -422,6 +424,18 @@ class PolicyHandler : public PolicyHandlerInterface,
...
+   * with the same app_id
+   * @param new_app_id app id new application
+   */
+  void PushAppIdToQueue(const uint32_t new_app_id);
+
+  /**
+   * @brief Remove first from queue application
```
Comment (AByzhynar) [inline src/components/application_manager/include/application_manager/policies/policy_handler.h]: @ydementieiev `Remove the first application from applications queue`

File: src/components/application_manager/include/application_manager/policies/policy_handler.h [hunk 26]
```diff
@@ -583,6 +597,19 @@ class PolicyHandler : public PolicyHandlerInterface,
    */
   void OnAppsSearchCompleted(const bool trigger_ptu) OVERRIDE;
 
+  /**
+   * @brief New application was added to application list
+   * @param new_app_id app_id for this application
+   * @param policy_id policy_id for this application
+   */
+  void OnAddedNewApplicationToAppList(const uint32_t new_app_id,
```
Comment (AByzhynar) [inline src/components/application_manager/include/application_manager/policies/policy_handler.h]: @ydementieiev Move description to iface

File: src/components/application_manager/include/application_manager/policies/policy_handler.h [hunk 27]
```diff
@@ -583,6 +597,19 @@ class PolicyHandler : public PolicyHandlerInterface,
...
+                                      const std::string& policy_id) OVERRIDE;
+
+  /**
+   * @brief Application queue ready for PTU
```
Comment (AByzhynar) [inline src/components/application_manager/include/application_manager/policies/policy_handler.h]: @ydementieiev What does it mean `queue ready for PTU`?

File: src/components/application_manager/src/application_manager_impl.cc [hunk 28]
```diff
@@ -193,6 +193,7 @@ ApplicationManagerImpl::ApplicationManagerImpl(
               this, &ApplicationManagerImpl::OnTimerSendTTSGlobalProperties))
     , is_low_voltage_(false)
     , apps_size_(0)
+    , is_registered_in_timeout_(false)
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_manager_impl.cc]: @ydementieiev rename it according to the meaning please. 
`registered_during_timer_execution` or `...after_timer_expired` or `..before_expiration_timer_start_` , depends on the meaning

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 29]
```diff
@@ -2205,6 +2232,16 @@ void PolicyHandler::OnAppsSearchCompleted(const bool trigger_ptu) {
   policy_manager_->OnAppsSearchCompleted(trigger_ptu);
 }
 
+void PolicyHandler::OnAddedNewApplicationToAppList(
+    const uint32_t new_app_id, const std::string& policy_id) {
+  LOG4CXX_AUTO_TRACE(logger_);
+  if (last_registered_policy_app_id_ == policy_id) {
```
Comment (AByzhynar) [inline src/components/application_manager/src/policies/policy_handler.cc]: @ydementieiev swap comparables please

File: src/components/policy/policy_external/include/policy/update_status_manager.h [hunk 30]
```diff
@@ -91,6 +91,12 @@ class UpdateStatusManager {
    */
   void OnUpdateTimeoutOccurs();
 
+  /**
+   * @brief Update status for next in queue application
+   * after previous has finished
```
[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/policy/policy_external/include/policy/update_status_manager.h]: @AByzhynar  update description [c04c115ce](https://github.com/smartdevicelink/sdl_core/commit/c04c115ced5d0ea1dfcc5bb53fc9c01d6d09a998)

File: src/components/application_manager/src/policies/policy_handler.cc (hunk 29 above)
Comment (ydementieiev) [reply src/components/application_manager/src/policies/policy_handler.cc]: @AByzhynar  swaped [c04c115ce](https://github.com/smartdevicelink/sdl_core/commit/c04c115ced5d0ea1dfcc5bb53fc9c01d6d09a998)

File: src/components/application_manager/src/application_manager_impl.cc (hunk 28 above)
Comment (ydementieiev) [reply src/components/application_manager/src/application_manager_impl.cc]: @AByzhynar  done [c04c115ce](https://github.com/smartdevicelink/sdl_core/commit/c04c115ced5d0ea1dfcc5bb53fc9c01d6d09a998)

File: src/components/application_manager/include/application_manager/policies/policy_handler.h (hunk 27 above)
Comment (ydementieiev) [reply src/components/application_manager/include/application_manager/policies/policy_handler.h]: @AByzhynar  update description [c04c115ce](https://github.com/smartdevicelink/sdl_core/commit/c04c115ced5d0ea1dfcc5bb53fc9c01d6d09a998)

File: src/components/application_manager/include/application_manager/policies/policy_handler.h (hunk 26 above)
Comment (ydementieiev) [reply src/components/application_manager/include/application_manager/policies/policy_handler.h]: @AByzhynar  leaved description only in iface [c04c115ce](https://github.com/smartdevicelink/sdl_core/commit/c04c115ced5d0ea1dfcc5bb53fc9c01d6d09a998)

File: src/components/application_manager/include/application_manager/policies/policy_handler.h (hunk 25 above)
Comment (ydementieiev) [reply src/components/application_manager/include/application_manager/policies/policy_handler.h]: @AByzhynar  update description [c04c115ce](https://github.com/smartdevicelink/sdl_core/commit/c04c115ced5d0ea1dfcc5bb53fc9c01d6d09a998)

File: src/components/application_manager/include/application_manager/policies/policy_handler.h (hunk 24 above)
Comment (ydementieiev) [reply src/components/application_manager/include/application_manager/policies/policy_handler.h]: @AByzhynar  update description [c04c115ce](https://github.com/smartdevicelink/sdl_core/commit/c04c115ced5d0ea1dfcc5bb53fc9c01d6d09a998)

File: src/components/application_manager/include/application_manager/policies/policy_handler.h (hunk 23 above)
Comment (ydementieiev) [reply src/components/application_manager/include/application_manager/policies/policy_handler.h]: @AByzhynar  update description [c04c115ce](https://github.com/smartdevicelink/sdl_core/commit/c04c115ced5d0ea1dfcc5bb53fc9c01d6d09a998)

File: src/components/include/application_manager/policies/policy_handler_interface.h (hunk 17 above)
Comment (AByzhynar) [inline src/components/include/application_manager/policies/policy_handler_interface.h]: @ydementieiev still typo...?

File: src/components/policy/policy_external/include/policy/policy_manager_impl.h [hunk 31]
```diff
@@ -608,6 +608,12 @@ class PolicyManagerImpl : public PolicyManager {
    */
   void OnAppsSearchCompleted(const bool trigger_ptu) OVERRIDE;
 
+  /**
+   * @brief Change applications count ready for PTU
+   * @param new_app_count new applications count for PTU
+   */
```
Comment (AByzhynar) [inline src/components/policy/policy_external/include/policy/policy_manager_impl.h]: @ydementieiev Remove description form derived classes

File: src/components/policy/policy_regular/include/policy/policy_manager_impl.h [hunk 32]
```diff
@@ -624,6 +624,12 @@ class PolicyManagerImpl : public PolicyManager {
    */
   void OnAppsSearchCompleted(const bool trigger_ptu) OVERRIDE;
 
+  /**
+   * @brief Change applications count ready for PTU
+   * @param new_app_count new applications count for PTU
+   */
```
Comment (AByzhynar) [inline src/components/policy/policy_regular/include/policy/policy_manager_impl.h]: @ydementieiev Same as above

Comment (ydementieiev) [reply src/components/policy/policy_regular/include/policy/policy_manager_impl.h]: @AByzhynar  done [d24d1e1e4f](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/d24d1e1e4fdf41bfce5e7f6b037d8c6620da76e2)

File: src/components/policy/policy_external/include/policy/policy_manager_impl.h (hunk 31 above)
Comment (ydementieiev) [reply src/components/policy/policy_external/include/policy/policy_manager_impl.h]: @AByzhynar  done [d24d1e1e4f](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/d24d1e1e4fdf41bfce5e7f6b037d8c6620da76e2)

File: src/components/include/application_manager/policies/policy_handler_interface.h (hunk 17 above)
Comment (ydementieiev) [reply src/components/include/application_manager/policies/policy_handler_interface.h]: @AByzhynar  done [d24d1e1e4f](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/d24d1e1e4fdf41bfce5e7f6b037d8c6620da76e2)

**Comment by ydementieiev** [comment]
@theresalech this PR passed internal Luxoft review and ready for Livio team review.

File: src/components/application_manager/include/application_manager/policies/policy_handler.h [hunk 33]
```diff
@@ -422,6 +421,18 @@ class PolicyHandler : public PolicyHandlerInterface,
    */
   uint32_t GetAppIdForSending() const OVERRIDE;
 
+  /**
+   * @brief Add application to PTU queue if no application with
+   * the same app id exists
+   * @param new_app_id app id new application
+   */
+  void PushAppIdToQueue(const uint32_t new_app_id);
```
[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/application_manager/include/application_manager/policies/policy_handler.h]: @ShobhitAd done in [c4f21ec](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/c4f21ec320a09d48bdcf4368bcf450f7161edeed)

File: src/components/application_manager/include/application_manager/policies/policy_handler.h [hunk 34]
```diff
@@ -422,6 +421,18 @@ class PolicyHandler : public PolicyHandlerInterface,
...
+
+  /**
+   * @brief Remove the first application from applications queue
+   */
+  void PopAppIdFromQueue();
```
[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/application_manager/include/application_manager/policies/policy_handler.h]: @ShobhitAd done in [c4f21ec](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/c4f21ec320a09d48bdcf4368bcf450f7161edeed)

File: src/components/application_manager/include/application_manager/policies/policy_handler.h [hunk 35]
```diff
@@ -583,6 +594,14 @@ class PolicyHandler : public PolicyHandlerInterface,
    */
   void OnAppsSearchCompleted(const bool trigger_ptu) OVERRIDE;
 
+  void OnAddedNewApplicationToAppList(const uint32_t new_app_id,
+                                      const std::string& policy_id) OVERRIDE;
+
+  /**
+   * @brief Queue applications for which PTU has not yet been completed
+   */
+  std::set<uint32_t> queue_applications_for_ptu_;
```
[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/application_manager/include/application_manager/policies/policy_handler.h]: @ShobhitAd done in [c4f21ec](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/c4f21ec320a09d48bdcf4368bcf450f7161edeed)

File: src/components/policy/policy_regular/include/policy/update_status_manager.h [hunk 36]
```diff
@@ -213,6 +213,7 @@ class UpdateStatusManager : public UpdateStatusManagerInterface {
   UpdateEvent last_processed_event_;
   bool apps_search_in_progress_;
   bool app_registered_from_non_consented_device_;
+  bool last_update_was_failed_;
```
[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/policy/policy_regular/include/policy/update_status_manager.h]: @ShobhitAd done in [c4f21ec](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/c4f21ec320a09d48bdcf4368bcf450f7161edeed)

File: src/components/include/policy/policy_external/policy/policy_manager.h [hunk 37]
```diff
@@ -533,6 +533,12 @@ class PolicyManager : public usage_statistics::StatisticsManager,
    */
   virtual void OnAppsSearchCompleted(const bool trigger_ptu) = 0;
 
+  /**
+   * @brief Change applications count ready for PTU
+   * @param new_app_count new applications count for PTU
+   */
+  virtual void OnChangeApplicationCount(const uint32_t new_app_count) = 0;
```
[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/include/policy/policy_external/policy/policy_manager.h]: @ShobhitAd done in [c4f21ec](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/c4f21ec320a09d48bdcf4368bcf450f7161edeed)

File: src/components/include/policy/policy_regular/policy/policy_manager.h [hunk 38]
```diff
@@ -524,6 +524,12 @@ class PolicyManager : public usage_statistics::StatisticsManager,
    */
   virtual void OnAppsSearchCompleted(const bool trigger_ptu) = 0;
 
+  /**
+   * @brief Change applications count ready for PTU
+   * @param new_app_count new applications count for PTU
+   */
+  virtual void OnChangeApplicationCount(const uint32_t new_app_count) = 0;
```
[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/include/policy/policy_regular/policy/policy_manager.h]: @ShobhitAd done in [c4f21ec](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/c4f21ec320a09d48bdcf4368bcf450f7161edeed)

File: src/components/policy/policy_regular/src/policy_manager_impl.cc [hunk 39]
```diff
@@ -70,14 +70,17 @@ PolicyManagerImpl::PolicyManagerImpl()
...
           "Retry sequence timer",
           new timer::TimerTaskImpl<PolicyManagerImpl>(
               this, &PolicyManagerImpl::OnPTUIterationTimeout))
     , ignition_check(true)
     , retry_sequence_url_(0, 0, "")
     , send_on_update_sent_out_(false)
-    , trigger_ptu_(false) {}
+    , trigger_ptu_(false)
+    , ptu_requested_(false)
+    , last_registered_policy_app_id_("") {}
```
[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/policy/policy_regular/src/policy_manager_impl.cc]: @ShobhitAd done in [c4f21ec](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/c4f21ec320a09d48bdcf4368bcf450f7161edeed)

File: src/components/application_manager/include/application_manager/policies/policy_handler.h [hunk 40]
```diff
@@ -583,6 +594,14 @@ class PolicyHandler : public PolicyHandlerInterface,
    */
   void OnAppsSearchCompleted(const bool trigger_ptu) OVERRIDE;
 
+  void OnAddedNewApplicationToAppList(const uint32_t new_app_id,
+                                      const std::string& policy_id) OVERRIDE;
+
+  /**
+   * @brief Queue applications for which PTU has not yet been completed
+   */
+  std::set<uint32_t> applications_ptu_queue;
```
[the remark this answers is not in the document]
Comment (SNiukalov) [reply src/components/application_manager/include/application_manager/policies/policy_handler.h]: @ShobhitAd 
Fixed in:https://github.com/smartdevicelink/sdl_core/pull/3208/commits/96f6b479184645f2ecde61afca1741928eb3a619

**Comment by dboltovskyi** [comment]
@ShobhitAd Please notice scripts in [#2318](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2318) were updated.
However 2 of them are failed even if current PR would be merged to develop without conflicts. It seems GIT auto-merge works not so good.
Please see details in https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2318#issuecomment-582685933
Please do not merge this PR until issue is fixed.

**Comment by dboltovskyi** [comment]
@ShobhitAd Please notice all issues have been successfully fixed in ec86a40

**Comment by dboltovskyi** [comment]
@theresalech Please notice all comments in current PR in `core` and corresponding one in `scripts` are addressed. Please advise when it's planned to have PM review?

**Comment by dboltovskyi** [comment]
@theresalech Please notice all comments in current PR in `core` and corresponding one in `scripts` are addressed. Please advise when it's planned to have PM review?

File: src/components/policy/policy_regular/src/policy_manager_impl.cc [hunk 41]
```diff
@@ -1322,6 +1337,9 @@ void PolicyManagerImpl::ResetRetrySequence(
   LOG4CXX_AUTO_TRACE(logger_);
   sync_primitives::AutoLock auto_lock(retry_sequence_lock_);
   retry_sequence_index_ = 0;
+  if (listener_->CanUpdate()) {
+    ptu_requested_ = false;
```
Comment (jacobkeeler) [inline src/components/policy/policy_regular/src/policy_manager_impl.cc]: When would this flag be reset if `CanUpdate` is false?

File: src/components/policy/policy_regular/src/status.cc [hunk 42]
```diff
@@ -57,6 +57,9 @@ policy::UpdateNeededStatus::UpdateNeededStatus()
 void policy::UpdateNeededStatus::ProcessEvent(
     policy::UpdateStatusManagerInterface* manager, policy::UpdateEvent event) {
   switch (event) {
+    case kUpdateForNextInQueue:
+      manager->SetNextStatus(std::make_shared<UpdateNeededStatus>());
```
Comment (jacobkeeler) [inline src/components/policy/policy_regular/src/status.cc]: Same here, seems redundant since we are already in this state.

**Comment by jacobkeeler** [comment]
@ydementieiev After following the steps in #3136 (registering another app during the retry sequence for the first app), I see an issue where the `url` parameter is missing from  `OnSystemRequest` from the subsequent PTU retry after the first attempt fails. This means that the app cannot retrieve the policy table if the first attempt fails.

**Comment by theresalech** [comment]
@ydementieiev @dboltovskyi do you have an update here?  We would like to be able to review and merge this PR by the end of this week, so testing on Core 6.1 can begin.

**Comment by dboltovskyi** [comment]
@theresalech Please notice we identified one additional issue since last PM review. All updates are planned to be finished at `02/26` EOD EST

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 43]
```diff
@@ -1123,7 +1142,7 @@ bool PolicyHandler::ReceiveMessageFromSDK(const std::string& file,
   const bool is_ptu_successful =
       load_pt_result == PolicyManager::PtProcessingResult::kSuccess;
   OnPTUFinished(is_ptu_successful);
-
+  PopAppIdFromPTUQueue();
```
[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/application_manager/src/policies/policy_handler.cc]: @jacobkeeler done in [ca790d7](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/ca790d7a1ebe90caa163b4fcf951f512cdaddcec)

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 44]
```diff
@@ -1546,9 +1567,11 @@ void PolicyHandler::OnSnapshotCreated(const BinaryMessage& pt_string,
   POLICY_LIB_CHECK_VOID();
 #ifdef PROPRIETARY_MODE
   std::string policy_snapshot_full_path;
-  if (!SaveSnapshot(pt_string, policy_snapshot_full_path)) {
-    LOG4CXX_ERROR(logger_, "Snapshot processing skipped.");
-    return;
+  if (PTUIterationType::RetryIteration != iteration_type) {
```
[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/application_manager/src/policies/policy_handler.cc]: @jacobkeeler done in [ca790d7](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/ca790d7a1ebe90caa163b4fcf951f512cdaddcec)

[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/application_manager/src/policies/policy_handler.cc]: @jacobkeeler done in [ca790d7](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/ca790d7a1ebe90caa163b4fcf951f512cdaddcec)

File: src/components/policy/policy_external/include/policy/status.h [hunk 45]
```diff
@@ -55,7 +55,8 @@ enum UpdateEvent {
   kPendingUpdate,
   kScheduleManualUpdate,
   kOnResetRetrySequence,
-  kNoEvent
+  kNoEvent,
+  kUpdateForNextInQueue
```
[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/policy/policy_external/include/policy/status.h]: @jacobkeeler deleted in [ca790d7](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/ca790d7a1ebe90caa163b4fcf951f512cdaddcec)

[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/policy/policy_external/include/policy/status.h]: @jacobkeeler deleted in [ca790d7](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/ca790d7a1ebe90caa163b4fcf951f512cdaddcec)

[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/policy/policy_external/include/policy/status.h]: @jacobkeeler deleted in [ca790d7](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/ca790d7a1ebe90caa163b4fcf951f512cdaddcec)

File: src/components/policy/policy_regular/src/status.cc (hunk 42 above)
Comment (ydementieiev) [reply src/components/policy/policy_regular/src/status.cc]: @jacobkeeler deleted in [ca790d7](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/ca790d7a1ebe90caa163b4fcf951f512cdaddcec)

File: src/components/policy/policy_external/src/status.cc [hunk 46]
```diff
@@ -39,6 +39,9 @@ policy::UpToDateStatus::UpToDateStatus()
 void policy::UpToDateStatus::ProcessEvent(UpdateStatusManager* manager,
                                           policy::UpdateEvent event) {
   switch (event) {
+    case kUpdateForNextInQueue:
+      manager->SetNextStatus(std::make_shared<UpdateNeededStatus>());
```
[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/policy/policy_external/src/status.cc]: @jacobkeeler removed in [ca790d7](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/ca790d7a1ebe90caa163b4fcf951f512cdaddcec)

File: src/components/policy/policy_external/src/update_status_manager.cc [hunk 47]
```diff
@@ -152,6 +159,10 @@ void UpdateStatusManager::OnNewApplicationAdded(const DeviceConsent consent) {
   }
   LOG4CXX_DEBUG(logger_, "Application registered from consented device");
   app_registered_from_non_consented_device_ = false;
+  if (last_update_was_failed_) {
+    last_update_was_failed_ = false;
```
[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/policy/policy_external/src/update_status_manager.cc]: @jacobkeeler removed in [ca790d7](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/ca790d7a1ebe90caa163b4fcf951f512cdaddcec)

File: src/components/policy/policy_external/src/status.cc [hunk 48]
```diff
@@ -57,6 +60,9 @@ policy::UpdateNeededStatus::UpdateNeededStatus()
 void policy::UpdateNeededStatus::ProcessEvent(
     policy::UpdateStatusManager* manager, policy::UpdateEvent event) {
   switch (event) {
+    case kUpdateForNextInQueue:
```
[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/policy/policy_external/src/status.cc]: @jacobkeeler removed in [ca790d7](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/ca790d7a1ebe90caa163b4fcf951f512cdaddcec)

File: src/components/policy/policy_external/src/policy_manager_impl.cc [hunk 49]
```diff
@@ -1382,6 +1395,13 @@ void PolicyManagerImpl::RetrySequenceFailed() {
 
   listener_->OnPTUFinished(false);
   ResetRetrySequence(ResetRetryCountType::kResetWithStatusUpdate);
+
+  if (HasApplicationForPTU()) {
+    update_status_manager_.OnUpdateForNextInQueue();
+    StartPTExchange();
+  }
+  is_ptu_in_progress_ = false;
+  ptu_requested_ = false;
```
[the remark this answers is not in the document]
Comment (SNiukalov) [reply src/components/policy/policy_external/src/policy_manager_impl.cc]: @jacobkeeler moved in [ca790d7](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/ca790d7a1ebe90caa163b4fcf951f512cdaddcec)

File: src/components/policy/policy_regular/src/policy_manager_impl.cc (hunk 41 above)
Comment (ydementieiev) [reply src/components/policy/policy_regular/src/policy_manager_impl.cc]: @jacobkeeler this condition is no need here now I removed it in [b1acdb5](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/b1acdb52e5f2764df74a72fae8692feec9c1ec79)

File: src/components/policy/policy_external/src/policy_manager_impl.cc [hunk 50]
```diff
@@ -551,6 +556,10 @@ void PolicyManagerImpl::OnPTUFinished(const PtProcessingResult ptu_result) {
 
   update_status_manager_.OnValidUpdateReceived();
 
+  if (HasApplicationForPTU()) {
```
[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/policy/policy_external/src/policy_manager_impl.cc]: @jacobkeeler added `else if` in [b1acdb5](https://github.com/smartdevicelink/sdl_core/pull/3208/commits/b1acdb52e5f2764df74a72fae8692feec9c1ec79)

**Comment by dboltovskyi** [comment]
@jacobkeeler Please find an explanation for the comment: https://github.com/smartdevicelink/sdl_core/pull/3208#issuecomment-589228752:
We suppose you did manual testing to get this result.
As for `EXTERNAL_PROPRIETARY` HMI provides data in `BC.OnSystemRequest` including `url`
SDL just transfers this data to mobile app in OnSystemRequest.

We did some check using `sdl_hmi` and found out that within merge of [RGNSD](https://github.com/smartdevicelink/sdl_hmi/pull/210) feature logic related to `url` was broken.
`GetURLs` RPC was replaced by `GetPolicyConfigurationData` but usage of a new data structure was not aligned.

We have created an issue a against `sdl_hmi`: https://github.com/smartdevicelink/sdl_hmi/issues/278

**Comment by dboltovskyi** [comment]
@theresalech Please notice we made all planned updates in `sdl_core` and `sdl_atf_test_scripts` so they are ready for PM review.
However within merge of `WebEngine` feature there are a few conflicts which needs to be resolved (in core and scripts).
We have a plan to finish this activity tomorrow.

File: src/components/policy/policy_regular/src/update_status_manager.cc [hunk 51]
```diff
@@ -121,7 +121,12 @@ void UpdateStatusManager::OnNewApplicationAdded(const DeviceConsent consent) {
     return;
   }
   app_registered_from_non_consented_device_ = false;
-  ProcessEvent(kOnNewAppRegistered);
+  if (kOnResetRetrySequence == last_processed_event_) {
+    current_status_.reset(new UpToDateStatus());
```
[the remark this answers is not in the document]
Comment (ydementieiev) [reply src/components/policy/policy_regular/src/update_status_manager.cc]: @jacobkeeler We reset status here, because of, if last update was finished with update_needed status (failed for any reason), need started for new one app with the same status. This way we avoided the transition from update_needed to update_needed state (According to your comment [comment ](https://github.com/smartdevicelink/sdl_core/pull/3208#discussion_r381505225))

**Comment by dboltovskyi** [comment]
@jacobkeeler Please notice we resolved conflicts in `core` and `scripts`, so both PRs are ready for review.
