### PR TITLE
Fix case sensitive app name and id comparison

### LINKED ISSUE #992: [Policies] SDL should be case-insensetive to "AppID" against listed in policies manager
## Occurrence
Always.

## Preconditions
1. SDL is started.
2. Application with appName="Test" and appID="123QWE" is present in local policy table.

## Steps to reproduce
Register mobile application with appName="Test" and appID="123qwe"

## Expected result
SDL must allow such appName registration. SDL responds to RegisterAppInterface with SUCCESS=true.

## Actual result
DISALLOWED came for RegisterAppInterface

# Environment
commit: fb001871f96eec538c2446ab512f6098f2d51a39
HMI: HTML5
OS: Ubuntu 14.04 x64
SPT: v2.1.73
app type: media 

# Attachments
[att_issue#992.zip](https://github.com/smartdevicelink/sdl_core/files/576031/att_issue.992.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
SDL was not case sensitive according to application name and id.
Provided a new fixes by adding `COLLATE NOCASE` property to all `application_id` and `nickname.name` columns and indices to make them case insensitive for all queries from SDL.

Related PR from another branch PR #1383 
Fixes #992

### CODE REVIEW

**Comment by AKalinich-Luxoft** [comment]
@AByzhynar, @LitvinenkoIra, @LuxoftAKutsan, @dev-gh please review

**Comment by dev-gh** [comment]
@AKalinich-Luxoft 
Issue #992 expects SDL to be case insensitive however you CustomString::compare is case sensitive

**Comment by AKalinich-Luxoft** [comment]
@dev-gh yes, sorry. It was just wrong understanding of related requirements. Also as I could see there are a wrong fixes provided in related PR #1383 on another branch.
I've provided a new fixes by adding COLLATE NOCASE property to all application_id and nickname.name columns and indices to make them case insensitive for all queries from SDL. Now I suppose it works correctly.
Please review again.

File: src/components/policy/policy_regular/src/sql_pt_queries.cc [hunk 1]
```diff
@@ -233,42 +233,42 @@ const std::string kCreateSchema =
...
-    "  `application_id` VARCHAR(45) NOT NULL, "
+    "  `application_id` VARCHAR(45) NOT NULL COLLATE NOCASE, "
     "  PRIMARY KEY(`request_type`,`application_id`), "
     "  CONSTRAINT `fk_app_type_application1` "
     "    FOREIGN KEY(`application_id`) "
     "    REFERENCES `application`(`id`) "
     "); "
     "CREATE INDEX IF NOT EXISTS `app_type.fk_app_type_application1_idx` "
-    "  ON `app_type`(`application_id`); "
+    "  ON `app_type`(`application_id` COLLATE NOCASE); "
```
Comment (LuxoftAKutsan) [inline src/components/policy/policy_regular/src/sql_pt_queries.cc]: @AKalinich-Luxoft please make sure that this functionality is supported on qnx

Comment (AKalinich-Luxoft) [inline src/components/policy/policy_regular/src/sql_pt_queries.cc]: @LuxoftAKutsan it's supported on QNX
From [qnx.com](http://www.qnx.com/developers/docs/6.5.0/index.jsp?topic=%2Fcom.qnx.doc.qdb_en_dev_guide%2Fdatatypes.html):

> User-defined collation sequences
> 
> By default, when QDB compares two text values, the result of the comparison is determined using memcmp(), regardless of the encoding of the string. QDB lets you supply arbitrary comparison functions, known as user-defined collation sequences, to be used instead of memcmp(). See the chapter Writing User-Defined Functions for more information.
> 
> Aside from the default collation sequence BINARY, implemented using memcmp(), QDB features two extra built-in collation sequences intended for testing purposes, NOCASE and REVERSE:
> 
>     BINARY — Compare string data using memcmp(), regardless of text encoding.
>     REVERSE — Collate in the reverse order to BINARY.
>     NOCASE — The same as BINARY, except the 26 upper-case characters used by the English language are converted to their lower-case equivalents before the comparison is performed.
>

**Comment by JackLivio** [comment]
@AKalinich-Luxoft This did not work for me. I added this to my app policies section of my local pt
```
            "123QWE": {
                "keep_context": false,
                "steal_focus": false,
                "priority": "NONE",
                "default_hmi": "NONE",
                "groups": ["Base-4", "Location-1", "DrivingCharacteristics-3", "VehicleInfo-3", "Emergency-1"]
            }
```
and no matter if i registered the app as "123QWE" or "123qwe" I would always receive disallowed when performing a getVehicleData request when in HMI FULL.

However if i used an app id that is numbers only (i.e. "123456") in the preloaded table and the test app, getVehicleData would work fine.

**Comment by JackLivio** [comment]
I am using Ubuntu 14.04 and build with regular policies configuration

**Comment by AKalinich-Luxoft** [comment]
@JackLivio you are right. This issue was investigated and there was found one additional case when loading data from PT must be case insensitive. This issue was fixed in https://github.com/smartdevicelink/sdl_core/pull/1614/commits/6a002ddd092772e4f2af9832876bc6dd340526c8 
Please test your scenario again on this commit. Now it should work.
