### PR TITLE
Fix/Delay OnHMIStatus until RAI response is sent

### LINKED ISSUE #3499: Core sends OnHMIStatus(FULL) before RegisterAppInterface to Cloud applications
### Bug Report
It seems that core is sending the `OnHMIStatus(FULL)` before `RegisterAppInterface` when a cloud application is activated on the HMI. This is causing problem on the cloud application's end since it doesn't know how the handle the `OnHMIStatus` before the RAI

##### Reproduction Steps

1. In the test_suite, start appJava
2. Add the cloud app entry to the policy table
```json
"773692255":{
                "keep_context": false,
                "steal_focus": false,
                "priority": "NONE",
                "default_hmi": "NONE",
                "groups": [
                    "Base-4",
                    "CloudApp"
                ],
                "RequestType": [],
                "RequestSubType": [],
                "nicknames": ["Test Suite"],
                "hybrid_app_preference": "CLOUD",
                "endpoint": "ws://<cloud_app_ip>:4355",
                "enabled": true,
                "cloud_transport_type": "WS"
            },
```

3. Start core and the HMI
3. Activate the cloud app in the HMI

##### Expected Behavior
Core sends `RegisterAppInterface` before `OnHMIStatus(FULL)` to the cloud app.

##### Observed Behavior
Core sends `OnHMIStatus(FULL)` before `RegisterAppInterface` to the cloud app.

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: develop (https://github.com/smartdevicelink/sdl_core/commit/a36ea82740e648debf1b0367c24fed85d6ef2d80)
* Testing Against: sdl_test_suite

### PR DESCRIPTION
**Pull request by ShobhitAd**
Fixes #3499 

This PR is **not ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Manual testing with Test Suite App

### Tasks Remaining:
- [x] [Run ATF regression]

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/state_controller_impl.cc [hunk 1]
```diff
@@ -873,11 +909,20 @@ void StateControllerImpl::OnStateChanged(ApplicationSharedPtr app,
...
+    auto notification =
+        MessageHelper::CreateHMIStatusNotification(app, window_id);
+    app_mngr_.GetRPCService().ManageMobileCommand(
+        notification, commands::Command::SOURCE_SDL);
+  } else {
+    SDL_LOG_DEBUG(
+        "Application "
+        << app->app_id()
+        << " not ready to receive OnHMIStatus. Delaying notification");
+    pending_hmistatus_notification_apps_.insert(app->app_id());
```
Comment (JackLivio) [inline src/components/application_manager/src/state_controller_impl.cc:923]: There should probably be a lock used around pending_hmistatus_notification_apps_ usage

File: src/components/application_manager/include/application_manager/state_controller_impl.h [hunk 2]
```diff
@@ -430,6 +431,7 @@ class StateControllerImpl : public event_engine::EventObserver,
   typedef std::list<WindowStatePair> WindowStatePairs;
   std::map<uint32_t, WindowStatePairs> postponed_app_widgets_;
 
+  std::unordered_set<uint32_t> pending_hmistatus_notification_apps_;
```
Comment (JackLivio) [inline src/components/application_manager/include/application_manager/state_controller_impl.h:434]: Maybe rename to `apps_with_pending_hmistatus_notification_`

**Review by JackLivio — APPROVED** [review]
