### PR TITLE
Handle omitted parameter permissions properly in OnVehicleData notification

### LINKED ISSUE #3577: SDL doesn't allow VD parameters if parameters section is omited in policies for OnVehicleData
### Bug Report
SDL doesn't allow VD parameters if parameters section is omited in policies for `OnVehicleData`

In general there are 3 options related to parameters for RPC in policies:
  1. `parameters` section is omitted - allow all parameters
  2. `parameters` section contains empty array (e.g. `[]`) - disallow all parameters
  3. `parameters` section contains some parameters (e.g. `["speed, "gps"]`) - allow only defined parameters

##### Reproduction Steps
1. Make sure there is a functional group in policies with `OnVehicleData` but with omitted `parameters` section
1. Register app
2. Subscribe for some Vehicle Data
3. Send `VI.OnVehicleData` from HMI with any VD parameter

##### Expected Behavior
SDL allows transferring `OnVehicleData` to App

##### Observed Behavior
SDL doesn't allow transferring `OnVehicleData` to App

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (9dc3c070c5)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - ATF Script: [006_Two_apps_with_same_appName_DIFF_devices_send_subscribe_on_VehicleData](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/TheSameApp/Subscriptions/006_Two_apps_with_same_appName_DIFF_devices_send_subscribe_on_VehicleData.lua)
 - Report and Logs: [2020-11-17_12-25-13.123_3577.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5555128/2020-11-17_12-25-13.123_3577.tar.gz)

### PR DESCRIPTION
**Pull request by jacobkeeler**
Fixes #3577 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Run ATF tests listed in https://github.com/smartdevicelink/sdl_core/issues/3577#issuecomment-729083063

### Summary
Allow all parameters in OnVehicleData if parameters field is omitted

##### Bug Fixes
* Allow all parameters in OnVehicleData if parameters field is omitted

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/on_vehicle_data_notification.cc [hunk 1]
```diff
@@ -112,15 +112,23 @@ void OnVehicleDataNotification::Run() {
...
-      const auto& allowed_params = params_permissions.allowed_params;
-      auto param_allowed = allowed_params.find(param);
-      if (allowed_params.end() == param_allowed) {
-        SDL_LOG_DEBUG("Param " << param << " is not allowed by policy for app "
-                               << notify_apps[idx]->app_id()
-                               << ". It will be ignored.");
-        appSO[idx].erase(param);
+    if (parameters_permissions_.allowed_params.empty() &&
+        parameters_permissions_.disallowed_params.empty() &&
+        parameters_permissions_.undefined_params.empty()) {
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/on_vehicle_data_notification.cc:117]: in the else case all we check are allowed_params, why do we care if these other two arrays are empty here?

**Review by iCollin — COMMENTED** [review]
please run style script also
```
120,121c120
<     }
<     else {
---
>     } else {
in  src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/on_vehicle_data_notification.cc
```

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/on_vehicle_data_notification.cc (hunk 1 above)
Comment (jacobkeeler) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/on_vehicle_data_notification.cc:117]: This is the way that it is checked in `CommandImpl::CheckAllowedParameters`, I believe that all of the provided parameters would be in the `disallowed_params` list in the case that it is defined as `[]`, so these lists would not be empty.

**Review by iCollin — APPROVED** [review]

**Comment by dboltovskyi** [comment]
@jacobkeeler Please notice the following scripts start failing within this fix:
```
./test_scripts/API/VehicleData/OnVehicleData/002_OnVD_disallowed.lua
./test_scripts/API/VehicleData/OnVehicleData/003_OnVD_disallowed_after_PTU.lua
```
