### PR TITLE
Fix sdl versioning for vehicle data

### LINKED ISSUE #2997: SDL does not apply the versioning for vehicle data
### Bug Report
SDL does not apply the versioning for vehicle data

##### Preconditions
1. SDL and HMI are started
2. App has permissions for fuelRange, parameter is available `since` 5.0 version

##### Reproduction Steps
1. Register application with `majorVersion = 3, minorVersion = 0`
2. App requests `SubscribeVehicleData` with `fuelRange`

##### Expected Behavior
SDL procesess  the request with `fuelRange` as request with undefined data

##### Observed Behavior
SDL processed  the request with `fuelRange` as defined data

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/8db0c2601921fdd368bf86133780746b532c40f5
* ATF: https://github.com/smartdevicelink/sdl_atf/commit/d6c2138f8d894d1e343d971226a16c47019ee92e
* Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2256

##### Logs
[report.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3535582/report.tar.gz)

### PR DESCRIPTION
**Pull request by YarikMamykin**
Fixes #2997 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Added unit tests for RPCHandlerImpl class (GetMessageVersion method)
Adjust ATF test scripts for GetVehicleData.
Fix existing ATF tests for GenericNetworkSignalData, Resumption.

### Summary
Corrected processing of SyncMsgVersion according to mobile application version (on RegisterAppInterface).
Corrected validating of incoming parameters from mobile request.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/smart_objects/src/object_schema_item.cc [hunk 1]
```diff
@@ -251,25 +252,23 @@ CObjectSchemaItem::CObjectSchemaItem(const Members& members)
 
 void CObjectSchemaItem::RemoveFakeParams(
     SmartObject& Object, const utils::SemanticVersion& MessageVersion) {
-  for (SmartMap::const_iterator it = Object.map_begin();
-       it != Object.map_end();) {
+  for (SmartMap::const_iterator it = Object.map_begin(); it != Object.map_end();
```
Comment (mkorniichuk) [inline src/components/smart_objects/src/object_schema_item.cc]: @YarikMamykin I would simplify loop to `for (const auto& key : Object.enumerate()) {}`

File: src/components/smart_objects/src/object_schema_item.cc [hunk 2]
```diff
@@ -251,25 +252,23 @@ CObjectSchemaItem::CObjectSchemaItem(const Members& members)
...
-                   .mIsRemoved) {
-      ++it;
+    if (mMembers.end() == members_it && key.compare(connection_key) != 0 &&
+        key.compare(binary_data) != 0 && key.compare(app_id) != 0) {
       Object.erase(key);
-    } else {
-      ++it;
+    }
+
+    if (mMembers.end() != members_it) {
```
Comment (mkorniichuk) [inline src/components/smart_objects/src/object_schema_item.cc]: @YarikMamykin how about to swap comparisons with the previous one and use `continue;`?

File: src/components/smart_objects/src/object_schema_item.cc (hunk 1 above)
Comment (YarikMamykin) [reply src/components/smart_objects/src/object_schema_item.cc]: @mkorniichuk , fixed in 29d5f70ba69b90cc1f4bfcb30cdc4fbe7028e7a4

File: src/components/smart_objects/src/object_schema_item.cc (hunk 2 above)
Comment (YarikMamykin) [reply src/components/smart_objects/src/object_schema_item.cc]: @mkorniichuk , fixed in 29d5f70ba69b90cc1f4bfcb30cdc4fbe7028e7a4

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/register_app_interface_request.cc [hunk 3]
```diff
@@ -383,11 +383,7 @@ void RegisterAppInterfaceRequest::Run() {
   // Version negotiation
   utils::SemanticVersion module_version(
       major_version, minor_version, patch_version);
-  if (mobile_version < utils::rpc_version_5) {
-    // Mobile versioning did not exist for
-    // versions before 5.0
-    application->set_msg_version(utils::base_rpc_version);
-  } else if (mobile_version < module_version) {
```
Comment (jacobkeeler) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/register_app_interface_request.cc]: This logic should not be removed, the reason for which is in the comment:
```
    // Mobile versioning did not exist for
    // versions before 5.0
```
The proxies did not send an appropriate message version in their RAI before mobile versioning was introduced (I believe that iOS sent 1.0), so this logic was introduced to account for that.

File: src/components/application_manager/src/rpc_handler_impl.cc [hunk 4]
```diff
@@ -294,11 +294,11 @@ void RPCHandlerImpl::GetMessageVersion(
     if (sync_msg_version.keyExists(strings::patch_version)) {
       patch = sync_msg_version[strings::patch_version].asUInt();
     }
+
+    message_version = utils::base_rpc_version;
     utils::SemanticVersion temp_version(major, minor, patch);
     if (temp_version.isValid()) {
-      message_version = (temp_version >= utils::rpc_version_5)
-                            ? temp_version
-                            : utils::base_rpc_version;
```
Comment (jacobkeeler) [inline src/components/application_manager/src/rpc_handler_impl.cc]: The same applies here, this logic should not be removed

**Comment by jacobkeeler** [comment]
In addition, see my comment here: https://github.com/smartdevicelink/sdl_core/issues/2997#issuecomment-535066242

I do not believe this is a valid issue

File: src/components/smart_objects/include/smart_objects/object_schema_item.h [hunk 5]
```diff
@@ -67,7 +67,8 @@ struct SMember {
           const std::string& Until = "",
           const bool IsDeprecated = false,
           const bool IsRemoved = false,
-          const std::vector<SMember>& history_vector = {});
+          const std::vector<SMember>& history_vector = {},
+          const bool IsCustom = false);
```
Comment (LuxoftAKutsan) [inline src/components/smart_objects/include/smart_objects/object_schema_item.h]: @YarikMamykin  I would propose to use enum instead pof bool

File: src/components/smart_objects/include/smart_objects/object_schema_item.h [hunk 6]
```diff
@@ -50,6 +50,12 @@ namespace ns_smart_objects {
  * @brief Object member.
  **/
 struct SMember {
+
+  enum class Type {
```
Comment (LuxoftAKutsan) [inline src/components/smart_objects/include/smart_objects/object_schema_item.h]: @YarikMamykin use OEM_SPECIFIC and RPC_SPEC, and add doxygen description

File: src/components/smart_objects/include/smart_objects/object_schema_item.h (hunk 5 above)
Comment (YarikMamykin) [reply src/components/smart_objects/include/smart_objects/object_schema_item.h]: @LuxoftAKutsan fixed in e5df4ef22337bafe6ed7d68ff16c98b407f40d6c

File: src/components/smart_objects/include/smart_objects/object_schema_item.h (hunk 6 above)
Comment (YarikMamykin) [reply src/components/smart_objects/include/smart_objects/object_schema_item.h]: @LuxoftAKutsan fixed in e5df4ef22337bafe6ed7d68ff16c98b407f40d6c

File: src/components/application_manager/src/rpc_service_impl.cc [hunk 7]
```diff
@@ -535,13 +527,58 @@ void RPCServiceImpl::SendMessageToMobile(
                (*message)[jhs::S_PARAMS][jhs::S_MESSAGE_TYPE].asInt())) {
     allow_unknown_parameters = false;
   }
+
+  const auto api_function_id = static_cast<mobile_apis::FunctionID::eType>(
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/rpc_service_impl.cc]: @YarikMamykin  do we need api_function_id outside the if?

File: src/components/application_manager/src/rpc_service_impl.cc [hunk 8]
```diff
@@ -535,13 +527,58 @@ void RPCServiceImpl::SendMessageToMobile(
...
+      (*message)[strings::params][strings::function_id].asUInt());
+
+  if (app) {
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/rpc_service_impl.cc]: @YarikMamykin looks like app pointer was already checked previously.

File: src/components/application_manager/src/rpc_service_impl.cc [hunk 9]
```diff
@@ -535,13 +527,58 @@ void RPCServiceImpl::SendMessageToMobile(
...
+    mobile_so_factory().attachSchema(*message, false, app->msg_version());
+    rpc::ValidationReport report("RPC");
+    auto validation_result = message->validate(&report, app->msg_version());
+    LOG4CXX_DEBUG(logger_,
+                  "Attached schema to message, result if valid: "
+                      << validation_result
+                      << "\nError report: " << rpc::PrettyFormat(report));
+
+    if (validation_result != smart_objects::errors::eType::OK) {
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/rpc_service_impl.cc]: @YarikMamykin please extract it to the separate funciton `SendMessageToMobile` if huge enough

File: src/components/application_manager/src/rpc_service_impl.cc (hunk 7 above)
Comment (YarikMamykin) [reply src/components/application_manager/src/rpc_service_impl.cc]: @LuxoftAKutsan yes, it is used in code below.

File: src/components/application_manager/src/rpc_service_impl.cc (hunk 8 above)
Comment (YarikMamykin) [reply src/components/application_manager/src/rpc_service_impl.cc]: @LuxoftAKutsan yes, app pointer was already checked but no actions like return from method are permitted, so there is still potential danger of having a non-valid pointer.

File: src/components/application_manager/src/rpc_service_impl.cc (hunk 9 above)
Comment (YarikMamykin) [reply src/components/application_manager/src/rpc_service_impl.cc]: @LuxoftAKutsan please check adb85dd4c0c945e43ef981329d5a1ab766c55a48

File: src/components/application_manager/src/rpc_service_impl.cc [hunk 10]
```diff
@@ -179,9 +179,6 @@ bool RPCServiceImpl::ManageMobileCommand(
       return false;
     }
 #endif  // ENABLE_SECURITY
-
-    // Message for "CheckPermission" must be with attached schema
-    mobile_so_factory().attachSchema(*message, false);
```
Comment (AByzhynar) [inline src/components/application_manager/src/rpc_service_impl.cc]: @YarikMamykin Why did you remove it?

File: src/components/application_manager/src/rpc_service_impl.cc [hunk 11]
```diff
@@ -459,6 +456,36 @@ void RPCServiceImpl::Handle(const impl::MessageToMobile message) {
...
+            MessageHelper::CreateNegativeResponse(
+                (*message)[strings::params][strings::connection_key].asUInt(),
+                api_function_id,
+                (*message)[strings::params][strings::correlation_id].asUInt(),
+                static_cast<int32_t>(mobile_apis::Result::GENERIC_ERROR));
+
+        SendMessageToMobile(response);
+        return true;
+      }
+    } break;
```
Comment (AByzhynar) [inline src/components/application_manager/src/rpc_service_impl.cc]: @YarikMamykin `break` statement should be inside case

File: src/components/application_manager/src/rpc_service_impl.cc (hunk 10 above)
Comment (YarikMamykin) [reply src/components/application_manager/src/rpc_service_impl.cc]: @AByzhynar because this one is done in ValidateRPCSO method, that is called inside ConvertMessageToSO. So here we have obsolete second call of attachSchema

File: src/components/smart_objects/include/smart_objects/object_schema_item.h [hunk 12]
```diff
@@ -50,6 +50,12 @@ namespace ns_smart_objects {
  * @brief Object member.
  **/
 struct SMember {
+  /*
```
Comment (AByzhynar) [inline src/components/smart_objects/include/smart_objects/object_schema_item.h]: @YarikMamykin Wrong doxygen

File: src/components/application_manager/src/rpc_service_impl.cc (hunk 11 above)
Comment (YarikMamykin) [reply src/components/application_manager/src/rpc_service_impl.cc]: @AByzhynar fixed in 73592a6d3e685613557fde5ab85648db5b41a28e

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/register_app_interface_request.cc (hunk 3 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/register_app_interface_request.cc]: @jacobkeeler fixed in 0edc0fac733780419b36f487213defd7166340f7

**Comment by YarikMamykin** [comment]
@theresalech PR passed internal Luxoft review and ready for Livio team review.

File: src/components/smart_objects/include/smart_objects/object_schema_item.h [hunk 13]
```diff
@@ -50,6 +50,11 @@ namespace ns_smart_objects {
...
+   *  @brief Defines data type that SMember contains.
+   */
+  enum class Type { OEM_SPECIFIC = 0, RPC_SPECIFIC = 1 };
```
Comment (jacobkeeler) [inline src/components/smart_objects/include/smart_objects/object_schema_item.h]:
```suggestion
  enum class Type { POLICY = 0, API = 1 };
```

File: src/components/smart_objects/src/object_schema_item.cc [hunk 14]
```diff
@@ -78,29 +88,46 @@ SMember::SMember(const ISchemaItemPtr SchemaItem,
...
     }
   }
 
   return true;  // Not enough version information. Default true.
 }
 
+bool SMember::CheckCustomVehicleData(
+    const utils::SemanticVersion& MessageVersion) const {
+  if (mSince != boost::none) {
+    if (MessageVersion < mSince.get() && MessageVersion < kModuleVersion) {
```
Comment (jacobkeeler) [inline src/components/smart_objects/src/object_schema_item.cc]: Instead of treating policy types differently, I think it would be better to just keep any members which have a `since` value above the module version, since such a value would not exist in the API. These functions and the `Type` enum shouldn't be necessary in that case.

File: src/components/smart_objects/src/object_schema_item.cc [hunk 15]
```diff
@@ -278,16 +302,22 @@ const SMember& CObjectSchemaItem::GetCorrectMember(
     const SMember& member, const utils::SemanticVersion& messageVersion) {
   // Check if member is the correct version
   if (member.CheckHistoryFieldVersion(messageVersion)) {
```
Comment (jacobkeeler) [inline src/components/smart_objects/src/object_schema_item.cc]: Related to the comment above in `CheckCustomVehicleData`, but the main change here would adding the condition ` || (member.mSince != boost::none && member.mSince.get() > kModuleVersion)`

File: src/components/smart_objects/include/smart_objects/object_schema_item.h (hunk 13 above)
Comment (jacobkeeler) [reply src/components/smart_objects/include/smart_objects/object_schema_item.h]: Might not be needed, since I proposed a solution which doesn't need this enum

File: src/components/application_manager/src/rpc_service_impl.cc [hunk 16]
```diff
@@ -535,13 +559,36 @@ void RPCServiceImpl::SendMessageToMobile(
                (*message)[jhs::S_PARAMS][jhs::S_MESSAGE_TYPE].asInt())) {
     allow_unknown_parameters = false;
   }
+
+  const auto api_function_id = static_cast<mobile_apis::FunctionID::eType>(
+      (*message)[strings::params][strings::function_id].asUInt());
+
+  if (app) {
+    mobile_so_factory().attachSchema(*message, false, app->msg_version());
```
Comment (jacobkeeler) [inline src/components/application_manager/src/rpc_service_impl.cc]: This code block is resolving a separate issue from #2997 which I believe would need more consideration. Changes to this file should be removed from this PR

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_data_item_schema.cc [hunk 17]
```diff
@@ -129,7 +129,7 @@ smart_objects::ISchemaItemPtr VehicleDataItemSchema::GetPODTypeSchema(
     return FloatSchemaItem::create(
         FloatItemParam(policy_item.minvalue.is_initialized()
                            ? double(*policy_item.minvalue)
-                           : std::numeric_limits<double>::min()),
+                           : std::numeric_limits<double>::lowest()),
```
[the remark this answers is not in the document]
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_data_item_schema.cc]: @jacobkeeler fixed in 85ff5033e7f0276d39e2d9fb6ddf8ee0f9cb57ba

File: src/components/application_manager/src/rpc_service_impl.cc (hunk 16 above)
Comment (YarikMamykin) [reply src/components/application_manager/src/rpc_service_impl.cc]: @jacobkeeler fixed in 986bcf07dafae78bff53a2be8a14998b251ef955

File: src/components/smart_objects/src/object_schema_item.cc (hunk 14 above)
Comment (YarikMamykin) [reply src/components/smart_objects/src/object_schema_item.cc]: @jacobkeeler please take a look at 986bcf07dafae78bff53a2be8a14998b251ef955

File: src/components/smart_objects/src/object_schema_item.cc (hunk 15 above)
Comment (YarikMamykin) [reply src/components/smart_objects/src/object_schema_item.cc]: @jacobkeeler maybe it is better to aggregate all checks regarding since/until in CheckCustomVehicleData.  Please take a look at 986bcf0

File: src/components/smart_objects/include/smart_objects/object_schema_item.h (hunk 13 above)
Comment (YarikMamykin) [reply src/components/smart_objects/include/smart_objects/object_schema_item.h]: @jacobkeeler fixed in 986bcf0

File: src/components/smart_objects/src/object_schema_item.cc [hunk 18]
```diff
@@ -278,16 +302,22 @@ const SMember& CObjectSchemaItem::GetCorrectMember(
...
       if (member.mHistoryVector[i].CheckHistoryFieldVersion(messageVersion)) {
+        member.mHistoryVector[i].mIsValid = true;
         return member.mHistoryVector[i];
       }
     }
   }
+
+  // If member didn't pass checks above then
+  // it becomes not valid and must be removed.
+  member.mIsValid = false;
```
[the remark this answers is not in the document]
Comment (YarikMamykin) [reply src/components/smart_objects/src/object_schema_item.cc]: @jacobkeeler fixed in 986bcf0

File: src/components/smart_objects/src/object_schema_item.cc [hunk 19]
```diff
@@ -78,23 +82,8 @@ SMember::SMember(const ISchemaItemPtr SchemaItem,
 bool SMember::CheckHistoryFieldVersion(
     const utils::SemanticVersion& MessageVersion) const {
   if (MessageVersion.isValid()) {
-    if (mSince != boost::none) {
```
Comment (jacobkeeler) [inline src/components/smart_objects/src/object_schema_item.cc]: Why was this removed?

File: src/components/smart_objects/src/object_schema_item.cc (hunk 15 above)
Comment (jacobkeeler) [reply src/components/smart_objects/src/object_schema_item.cc]: Regarding 34fd6bd, this change does not make sense, now there is no check for the `since` value. Please revert this change.

File: src/components/smart_objects/src/object_schema_item.cc [hunk 20]
```diff
@@ -251,45 +245,43 @@ CObjectSchemaItem::CObjectSchemaItem(const Members& members)
...
       if (member.mHistoryVector[i].CheckHistoryFieldVersion(messageVersion)) {
-        return member.mHistoryVector[i];
+        return &member.mHistoryVector[i];
       }
     }
   }
+
   // Return member as default
-  return member;
+  return nullptr;
```
Comment (jacobkeeler) [inline src/components/smart_objects/src/object_schema_item.cc]:
```suggestion
  return (member.mSince != boost::none && member.mSince.get() > kModuleVersion) ? member : nullptr;
```

File: src/components/smart_objects/src/object_schema_item.cc (hunk 19 above)
Comment (YarikMamykin) [reply src/components/smart_objects/src/object_schema_item.cc]: @jacobkeeler please check 165604adbbcc033bb1fa837024a58ee8e5c72592

**Comment by YarikMamykin** [comment]
@jacobkeeler do you have any additional comments about this pull request?

File: src/components/application_manager/src/rpc_service_impl.cc (hunk 10 above)
Comment (jacobkeeler) [reply src/components/application_manager/src/rpc_service_impl.cc]: I believe this is not quite correct, but it does look like this call is covered in the `SendMessageToMobile` function, which should justify this change.

File: src/components/smart_objects/src/object_schema_item.cc [hunk 21]
```diff
@@ -251,45 +252,45 @@ CObjectSchemaItem::CObjectSchemaItem(const Members& members)
...
 
-    } else if (mMembers.end() != members_it &&
-               GetCorrectMember(members_it->second, MessageVersion)
-                   .mIsRemoved) {
-      ++it;
+    if (mMembers.end() != members_it) {
+      const SMember* member =
+          GetCorrectMember(members_it->second, MessageVersion);
+      if (!member || member->mIsRemoved) {
+        Object.erase(key);
```
Comment (jacobkeeler) [inline src/components/smart_objects/src/object_schema_item.cc]: These changes cause invalid iterators. There's a reason that this used a normal for loop rather than a range-based one. See https://en.cppreference.com/w/cpp/container/map/erase

> References and iterators to the erased elements are invalidated.

Comment (jacobkeeler) [reply src/components/smart_objects/src/object_schema_item.cc]: Ah, I see that this might not be the case, since `enumerate` seems to make a copy of the key list.

**Comment by jacobkeeler** [comment]
Note, the Travis build is failing on this branch:
```
/home/travis/build/smartdevicelink/sdl_core/src/components/smart_objects/src/object_schema_item.cc:36:35: fatal error: generated_msg_version.h: No such file or directory
```

Could be an issue with clean builds potentially

File: src/components/include/utils/semantic_version.h [hunk 22]
```diff
@@ -51,16 +51,18 @@ struct SemanticVersion {
...
-      major_version_ = static_cast<uint8_t>(major_int);
-      minor_version_ = static_cast<uint8_t>(minor_int);
-      patch_version_ = static_cast<uint8_t>(patch_int);
+      if (readElements != 2) {
+        major_version_ = 0;
+        minor_version_ = 0;
+        patch_version_ = 0;
+      }
     }
   }
```
[the remark this answers is not in the document]
Comment (IGapchuk) [reply src/components/include/utils/semantic_version.h]: @jacobkeeler Changed in 5ba1cd8014378d2bef471569939f66cf1f7919cf

File: src/components/smart_objects/src/object_schema_item.cc [hunk 23]
```diff
@@ -251,45 +252,45 @@ CObjectSchemaItem::CObjectSchemaItem(const Members& members)
...
+      }
+      continue;
+    }
+
+    if (mMembers.end() == members_it && key.compare(connection_key) != 0 &&
```
[the remark this answers is not in the document]
Comment (IGapchuk) [reply src/components/smart_objects/src/object_schema_item.cc]: @jacobkeeler Changed in 5ba1cd8014378d2bef471569939f66cf1f7919cf

File: src/components/smart_objects/src/object_schema_item.cc [hunk 24]
```diff
@@ -80,21 +84,13 @@ bool SMember::CheckHistoryFieldVersion(
...
-    if (mUntil != boost::none && (MessageVersion >= mUntil.get())) {
-      return false;  // Msg version newer than `until` field
-    } else {
-      return true;  // Mobile msg version falls within specified version range
+    if (mUntil != boost::none) {
+      if (MessageVersion >= mUntil.get()) {
+        return false;  // Msg version newer than `until` field
+      }
     }
   }
```
[the remark this answers is not in the document]
Comment (IGapchuk) [reply src/components/smart_objects/src/object_schema_item.cc]: @jacobkeeler Changed in 5ba1cd8014378d2bef471569939f66cf1f7919cf

**Comment by jacobkeeler** [comment]
@IGapchuk the build is still failing on Travis, I can approve after that is fixed

**Comment by IGapchuk** [comment]
@jacobkeeler The Travis build is fixed. Please take a look at the commit 72656a4013075e156711ff9fea7201531f3e19d2, that adds the dependency of SmartObject component on the Mobile_API. This dependency is necessary to build the project in the multithreading mode.
