### PR TITLE
SDL does not send UnsubscribeVehicleData request to HMI after unregister last app.

### LINKED ISSUE #2282: SDL does not send UnsubscribeVehicleData request to HMI after unregister second app
### Bug Report
SDL does not send UnsubscribeVehicleData request to HMI after unregister second app

##### Reproduction Steps
1. app1 and app2 are registered
2. Apps are activated, app1 in FULL, app2 in LIMITED
3. app1, app2 is subscribed to vd_1
4. Unregister app1 and app2 or perform unexpected disconnect

##### Expected Behavior
By unregistration of the second app2 SDL sends VehicleInfo.UnsubscribeVehicleData request to HMI.

##### Observed Behavior
SDL does not send VehicleInfo.UnsubscribeVehicleData request to HMI.

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: develop branch (2ec732c56e3f06b7043cf02cf98109720d6ff38a)
* Testing Against: ATF: [develop branch](https://github.com/smartdevicelink/sdl_atf/tree/develop)
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1936 (006_Success_flow_2_apps_unregister.lua)

[Updated_scrpt_for_reproducing_defect.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3656520/Updated_scrpt_for_reproducing_defect.tar.gz)

##### Attach
[SmartDeviceLinkCore_unsubscribe_unregister.log.tar.gz](https://github.com/smartdevicelink/sdl_core/files/2118408/SmartDeviceLinkCore_unsubscribe_unregister.log.tar.gz)

### PR DESCRIPTION
**Pull request by IGapchuk**
Fixes #2282

This PR is ready for review.

### Risk
This PR makes no API changes.

### Testing Plan
Covered by ATF script.

### Summary
This PR fixes defect, when SDL does not send UnsubscribeVehicleData request to HMI when the last application was unregistered.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/include/application_manager/message_helper.h [hunk 1]
```diff
@@ -279,6 +284,16 @@ class MessageHelper {
   static smart_objects::SmartObjectList CreateAddCommandRequestToHMI(
       ApplicationConstSharedPtr app, ApplicationManager& app_mngr);
 
+  /**
+   * @brief Creates Message for sending to HMI for unsubscribe from specified
+   * VehicleData. Puts in vehicle data types into message according to keys.
+   * @param message_to_hmi - message for sending.
+   * @param vehicle_data - collection with vehicle data types for ubsubscribe.
+   */
+  static void CreateUbsubscriveVehicleDataMessageForHMI(
```
Comment (ValeriiMalkov) [inline src/components/application_manager/include/application_manager/message_helper.h]: @IGapchuk Is it correct name of method? Maybe you mean `CreateUnsubscribeVehicleDataMessageForHMI` ?

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h [hunk 2]
```diff
@@ -71,6 +73,9 @@ class VehicleInfoPlugin : public plugins::RPCPlugin {
 
  private:
   void DeleteSubscriptions(app_mngr::ApplicationSharedPtr app);
+  void SelectVehicleDataForUbsubscribe(
```
Comment (ValeriiMalkov) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h]: @IGapchuk Same as above. Is it correct name of method?

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h [hunk 3]
```diff
@@ -71,6 +73,9 @@ class VehicleInfoPlugin : public plugins::RPCPlugin {
...
+      const app_mngr::ApplicationSharedPtr& app,
+      VehicleInfoSubscriptions& vd_for_unscribe);
```
Comment (ValeriiMalkov) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h]: @IGapchuk name of parameters

File: src/components/application_manager/include/application_manager/message_helper.h (hunk 1 above)
Comment (IGapchuk) [reply src/components/application_manager/include/application_manager/message_helper.h]: Done. Method was renamed.

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h (hunk 3 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h]: Done. vd_for_unscribe was renamed to vehical_data_for_unscribe.

File: src/components/application_manager/include/application_manager/message_helper.h [hunk 4]
```diff
@@ -279,6 +284,16 @@ class MessageHelper {
   static smart_objects::SmartObjectList CreateAddCommandRequestToHMI(
       ApplicationConstSharedPtr app, ApplicationManager& app_mngr);
 
+  /**
+   * @brief Creates Message for sending to HMI for unsubscribe from specified
+   * VehicleData. Puts in vehicle data types into message according to keys.
+   * @param message_to_hmi - message for sending.
+   * @param vehicle_data - collection with vehicle data types for ubsubscribe.
+   */
+  static void CreateUnsubscribeVehicleDataMessageForHMI(
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/include/application_manager/message_helper.h]: @IGapchuk make this function returning smart object as output value

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h [hunk 5]
```diff
@@ -71,6 +71,9 @@ class VehicleInfoPlugin : public plugins::RPCPlugin {
 
  private:
   void DeleteSubscriptions(app_mngr::ApplicationSharedPtr app);
+  void SelectVehicleDataForUnsubscribe(
+      const app_mngr::ApplicationSharedPtr& app,
+      std::set<mobile_apis::VehicleDataType::eType>& vehicle_data_for_unscribe);
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h]: @IGapchuk don't you have alias `VehicleInfoSubscriptions` ?

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc [hunk 6]
```diff
@@ -76,6 +75,22 @@ void VehicleInfoPlugin::OnApplicationEvent(
   if (plugins::ApplicationEvent::kApplicationRegistered == event) {
     application->AddExtension(
         std::make_shared<VehicleInfoAppExtension>(*this, *application));
+  } else if (plugins::ApplicationEvent::kApplicationUnregistered == event) {
+    DCHECK_OR_RETURN_VOID(application);
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc]: @IGapchuk extract logic to a function

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h [hunk 7]
```diff
@@ -71,6 +71,9 @@ class VehicleInfoPlugin : public plugins::RPCPlugin {
 
  private:
   void DeleteSubscriptions(app_mngr::ApplicationSharedPtr app);
+  void SelectVehicleDataForUnsubscribe(
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h]: @IGapchuk description required

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc [hunk 8]
```diff
@@ -158,7 +173,33 @@ void VehicleInfoPlugin::DeleteSubscriptions(
     }
   }
 }
+
+void VehicleInfoPlugin::SelectVehicleDataForUnsubscribe(
+    const app_mngr::ApplicationSharedPtr& app,
+    std::set<mobile_apis::VehicleDataType::eType>& vehicle_data_for_unscribe) {
+  VehicleInfoAppExtension& vehicle_extension =
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc]: @IGapchuk use auto

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc [hunk 9]
```diff
@@ -158,7 +173,33 @@ void VehicleInfoPlugin::DeleteSubscriptions(
...
+      VehicleInfoAppExtension::ExtractVIExtension(*app);
+  vehicle_data_for_unscribe = vehicle_extension.Subscriptions();
+  application_manager::ApplicationSet applications =
+      application_manager_->applications().GetData();
+  if (!applications.empty()) {
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc]: @IGapchuk I would say that it is redundant check, or move it before using unsubscriber

File: src/components/application_manager/src/message_helper/message_helper.cc [hunk 10]
```diff
@@ -1344,6 +1344,29 @@ smart_objects::SmartObjectList MessageHelper::CreateAddCommandRequestToHMI(
...
 
+void MessageHelper::CreateUnsubscribeVehicleDataMessageForHMI(
+    smart_objects::SmartObjectSPtr& message_to_hmi,
+    const VehicleInfoSubscriptions& vehicle_data,
+    const application_manager::ApplicationSharedPtr& app) {
+  message_to_hmi =
+      CreateMessageForHMI(hmi_apis::messageType::request, app->app_id());
+  (*message_to_hmi)[strings::params][strings::function_id] =
+      hmi_apis::FunctionID::VehicleInfo_UnsubscribeVehicleData;
+  smart_objects::SmartObject msg_params =
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/message_helper/message_helper.cc]: @IGapchuk good place for auto

File: src/components/application_manager/src/message_helper/message_helper.cc [hunk 11]
```diff
@@ -1344,6 +1344,29 @@ smart_objects::SmartObjectList MessageHelper::CreateAddCommandRequestToHMI(
...
+      smart_objects::SmartObject(smart_objects::SmartType_Map);
+  const VehicleData& v_data = MessageHelper::vehicle_data();
+  auto vehicle_data_setter =
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/message_helper/message_helper.cc]: @IGapchuk not clear what this lambda does, add some comments

File: src/components/application_manager/include/application_manager/message_helper.h (hunk 4 above)
Comment (IGapchuk) [reply src/components/application_manager/include/application_manager/message_helper.h]: Done.

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc [hunk 12]
```diff
@@ -158,7 +173,33 @@ void VehicleInfoPlugin::DeleteSubscriptions(
...
+    auto unsubscriber = [&applications, &vehicle_data_for_unscribe](
+        const VehicleDataType vehicle_data) {
+      for (auto app_it = applications.begin(); app_it != applications.end();
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc]: @IGapchuk you could use range-based loop here

File: src/components/application_manager/include/application_manager/message_helper.h (hunk 4 above)
Comment (IGapchuk) [reply src/components/application_manager/include/application_manager/message_helper.h]: Fixed in 73c67bf4f764f384b64cc45f9a7a3087eff31f1f.

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h (hunk 5 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h]: Fixed in 73c67bf4f764f384b64cc45f9a7a3087eff31f1f.

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc (hunk 6 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc]: Done in 73c67bf4f764f384b64cc45f9a7a3087eff31f1f.

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h (hunk 7 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h]: Done in 73c67bf4f764f384b64cc45f9a7a3087eff31f1f.

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc (hunk 8 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc]: Fixed in 73c67bf4f764f384b64cc45f9a7a3087eff31f1f.

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc (hunk 9 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc]: This check needs for not doing redundant selecting vehicle data different with other applications. Because, if we haven't other applications, that vehicle data of specified application will be only one data for unsubscribe.

File: src/components/application_manager/src/message_helper/message_helper.cc (hunk 10 above)
Comment (IGapchuk) [reply src/components/application_manager/src/message_helper/message_helper.cc]: Done in 73c67bf4f764f384b64cc45f9a7a3087eff31f1f.

File: src/components/application_manager/src/message_helper/message_helper.cc (hunk 11 above)
Comment (IGapchuk) [reply src/components/application_manager/src/message_helper/message_helper.cc]: Done in 73c67bf4f764f384b64cc45f9a7a3087eff31f1f.

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc (hunk 12 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc]: Done in 73c67bf4f764f384b64cc45f9a7a3087eff31f1f.

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc [hunk 13]
```diff
@@ -158,7 +159,50 @@ void VehicleInfoPlugin::DeleteSubscriptions(
...
+void VehicleInfoPlugin::SelectVehicleDataForUnsubscribe(
+    const app_mngr::ApplicationSharedPtr& app,
+    application_manager::VehicleInfoSubscriptions& vehicle_data_for_unscribe) {
+  auto vehicle_extension = VehicleInfoAppExtension::ExtractVIExtension(*app);
+  vehicle_data_for_unscribe = vehicle_extension.Subscriptions();
+  application_manager::ApplicationSet applications =
+      application_manager_->applications().GetData();
+  if (applications.empty()) {
+    LOG4CXX_DEBUG(logger_,
+                  "Other applications not exists. All existing vehicle data "
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc]: @IGapchuk you make an assumption that this method called after the app application was erased from the application list. This assumption is correct, but got user that will call this function further it is no obvious. For example, somebody will call this function on policy update if the application was disallowed. In that case, `applications()` won't be empty, and vehicle_data_collector will be called for each subscription, and for each application (including the app) because you have no check that `SelectVehicleDataForUnsubscribe::app` and `vehicle_data_collector::app` is equal we will have the situation that any data won't be elected ( everything will be erased).
So I would not make an assumption that `application()` is empty if the app is the only one existing app. I would better putt additional check inside vehicle_data_collector, and remove check if `applications()` is empty

Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc]: Done in e8b297ab1e2a8dee6bd07fdf2e64d38d1dd62b33.

File: src/components/application_manager/include/application_manager/message_helper.h [hunk 14]
```diff
@@ -279,6 +284,20 @@ class MessageHelper {
   static smart_objects::SmartObjectList CreateAddCommandRequestToHMI(
       ApplicationConstSharedPtr app, ApplicationManager& app_mngr);
 
+  /**
+   * @brief Creates Message for sending to HMI for unsubscribe from specified
+   * VehicleData. Creates and returns message with vehicle data for unsubscribe.
+   * @param vehicle_data - collection with vehicle data types to ubsubscribe.
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/include/application_manager/message_helper.h]: @IGapchuk typo in `ubsubscribe`

File: src/components/application_manager/include/application_manager/message_helper.h [hunk 15]
```diff
@@ -279,6 +284,20 @@ class MessageHelper {
...
+   * @param app - application, that must will be unsubscribe from specified
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/include/application_manager/message_helper.h]: @IGapchuk `application which should be unsubscribed from specified vehicle data`

File: src/components/application_manager/include/application_manager/message_helper.h [hunk 16]
```diff
@@ -279,6 +284,20 @@ class MessageHelper {
...
+   * vehicle data.
+   * @return - created message, that exists vehicle data for unsubscribe,
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/include/application_manager/message_helper.h]: @IGapchuk `request filled with vehicle data params to unsubscribe`

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h [hunk 17]
```diff
@@ -72,6 +73,25 @@ class VehicleInfoPlugin : public plugins::RPCPlugin {
  private:
   void DeleteSubscriptions(app_mngr::ApplicationSharedPtr app);
 
+  /**
+   * @brief Selects vehicle data of specified application for unsubscribing
+   * according to subscriptions of other registered applications that also
+   * subscribed to vehicle data .
+   * @param app - application, that was unregister.
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h]: @IGapchuk just `pointer to application instance`

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h [hunk 18]
```diff
@@ -72,6 +73,25 @@ class VehicleInfoPlugin : public plugins::RPCPlugin {
...
+   * @return vehicle_data_for_unscribe - collection with selected vehicle data
+   * to unsubscribe.
+   */
+  app_mngr::VehicleInfoSubscriptions SelectVehicleDataForUnsubscribe(
+      const app_mngr::ApplicationSharedPtr& application);
+
+  /**
+   * @brief Selects  for unsubscribing vehicle data for specific application and
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h]: @IGapchuk redundant space

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h [hunk 19]
```diff
@@ -72,6 +73,25 @@ class VehicleInfoPlugin : public plugins::RPCPlugin {
...
+   * sends message to HMI if application has that data and other applications
+   * haven't subscriptions for that same vehicle data.
+   * @param app - application, than must be unsubscribe to vehicle data.
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/include/vehicle_info_plugin/vehicle_info_plugin.h]: @IGapchuk `unsubscribe from`

File: src/components/application_manager/src/message_helper/message_helper.cc [hunk 20]
```diff
@@ -1344,6 +1344,32 @@ smart_objects::SmartObjectList MessageHelper::CreateAddCommandRequestToHMI(
   return requests;
 }
 
+smart_objects::SmartObjectSPtr
+MessageHelper::CreateUnsubscribeVehicleDataMessageForHMI(
+    const VehicleInfoSubscriptions& vehicle_data,
+    const application_manager::ApplicationSharedPtr& app) {
```
Comment (ZhdanovP) [inline src/components/application_manager/src/message_helper/message_helper.cc]: @IGapchuk We can use `ApplicationConstSharedPtr` instead of const reference

Comment (IGapchuk) [reply src/components/application_manager/src/message_helper/message_helper.cc]: @ZhdanovP Fixed in c85e66cb7cabc056ddd602e4803e96323969b5b0

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc (hunk 6 above)
Comment (jacobkeeler) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc]: Best to put this dcheck in the function as well.

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc [hunk 21]
```diff
@@ -171,6 +174,48 @@ void VehicleInfoPlugin::DeleteSubscriptions(
...
 }
+
+application_manager::VehicleInfoSubscriptions
+VehicleInfoPlugin::SelectVehicleDataForUnsubscribe(
+    const app_mngr::ApplicationSharedPtr& application) {
+  auto vehicle_extension =
+      VehicleInfoAppExtension::ExtractVIExtension(*application);
+  auto vehicle_data_for_unsubscribe = vehicle_extension.Subscriptions();
+  const application_manager::ApplicationSet& applications =
+      application_manager_->applications().GetData();
```
Comment (jacobkeeler) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/vehicle_info_plugin.cc]: Would this `DataAccessor` do anything if it goes out of scope immediately, as it does now? I think you need to keep a reference to the `DataAccessor` in this case.

**Comment by jacobkeeler** [comment]
@IGapchuk before addressing my comments, I'd like to note that it looks like you could use the `DeleteSubscriptions` method (which was added more recently) instead of adding the new `SelectVehicleDataForUnsubscribe` function

**Comment by IGapchuk** [comment]
@jacobkeeler I agree with you, in this case, we can use `DeleteSubscriptions`. But we need to little bit update it. Instead of sending it to HMI `UnsubscribeVehicleData`  request for each vehicle date, we could collect all data into one collection and send it to HMI via `UnsubscribeVehicleData` request only once.
Also please be informed, that the fix branch has been rebased onto the current develop branch and force pushed.

**Comment by IGapchuk** [comment]
@jacobkeeler Please be informed then all changes have been done and all regression tests have been passed successfully.
PR is ready for review.
