### PR TITLE
Fix sdl sends OnSystemRequest (QUERY_APPS) to the app

### LINKED ISSUE #995: CCB: Fix sdl sends query apps to the app
### Bug Report
SDL sends OnSystemRequest (QUERY_APPS) to the app after unsuccessful attempt 

##### Reproduction Steps
1. Make sure SDL4.0 feature is enabled in .ini file
2. Register app via 4th protocol.
3. App sends incorrect json on SystemRequest and receives error code in response.
4. Bring app to background and then to foreground again or register new app via 4th protocol.

##### Expected Behavior
SDL does not send OnSystemRequest(QUERY_APPS) to the same app after bringing it to foreground and also to new registered app after unsuccessful attempt to send query json.

##### Observed Behavior
SDL sends OnSystemRequest(QUERY_APPS) to the same app after bringing it to foreground and also to new registered app after unsuccessful attempt to send query json.

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: 
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
* [att_issue#995.zip](https://github.com/smartdevicelink/sdl_core/files/576054/att_issue.995.zip)

### PR DESCRIPTION
**Pull request by Ypostolov**
Fixes #995

This PR is ready for review.

### Risk
This PR makes no API changes.

### Plan
Provide ATF tests.

### Summary
In the current implementation SDL does not send OnSystemRequest(QUERY_APPS) to the same app after bringing it to foreground and also to new registered app after unsuccessful attempt to send query json.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/application_manager_impl.cc [hunk 1]
```diff
@@ -2467,6 +2470,7 @@ void ApplicationManagerImpl::UnregisterApplication(
   }
 
   commands_holder_->Clear(app_to_remove);
+  // QuerryApps_devices.erase(app_to_remove->device())
```
Comment (EKuliiev) [inline src/components/application_manager/src/application_manager_impl.cc]: @Ypostolov no commented code.

File: src/components/application_manager/include/application_manager/application_manager_impl.h [hunk 2]
```diff
@@ -1443,7 +1446,7 @@ class ApplicationManagerImpl
    * will send TTS global properties to HMI after timeout
    */
   std::map<uint32_t, TimevalStruct> tts_global_properties_app_list_;
-
+  std::set<connection_handler::DeviceHandle> QuerryApps_devices;
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/include/application_manager/application_manager_impl.h]: @Ypostolov please rename according to our naming rules

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/system_request.cc [hunk 3]
```diff
@@ -601,12 +602,13 @@ void SystemRequest::Run() {
     }
 
     CFormatterJsonBase::jsonValueToObj(root, sm_object);
+    application_manager_.ProcessQueryApp(sm_object, connection_key());
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/system_request.cc]: @Ypostolov unrelated changes. Please revert it

File: src/components/application_manager/src/application_manager_impl.cc [hunk 4]
```diff
@@ -943,15 +943,11 @@ ApplicationManagerImpl::AppsWaitingForRegistration() const {
...
-  AppsWaitRegistrationSet::iterator it = apps_to_register_.begin();
-  AppsWaitRegistrationSet::const_iterator it_end = apps_to_register_.end();
-  for (; it != it_end; ++it) {
-    if (handle == (*it)->device()) {
-      return true;
-    }
+  if (QuerryApps_devices.find(handle) != QuerryApps_devices.end()) {
+    return true;
+  } else {
+    return false;
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/src/application_manager_impl.cc]: @Ypostolov could be simplified:
```
return QuerryApps_devices.find(handle) != QuerryApps_devices.end();
```

File: src/components/application_manager/include/application_manager/application_manager_impl.h (hunk 2 above)
Comment (EKuliiev) [inline src/components/application_manager/include/application_manager/application_manager_impl.h]: @Ypostolov  what code style u are using?

Comment (Ypostolov) [reply src/components/application_manager/include/application_manager/application_manager_impl.h]: fixed inccdfc0c216991a5251ce103d0ef920c9d5dbc9c5

**Comment by Ypostolov** [comment]
Rebuild Pull_Request_UT

File: src/components/application_manager/include/application_manager/application_manager_impl.h [hunk 5]
```diff
@@ -1443,7 +1446,7 @@ class ApplicationManagerImpl
    * will send TTS global properties to HMI after timeout
    */
   std::map<uint32_t, TimevalStruct> tts_global_properties_app_list_;
-
+  std::set<connection_handler::DeviceHandle> querry_apps_devices_;
```
Comment (AByzhynar) [inline src/components/application_manager/include/application_manager/application_manager_impl.h]: @Ypostolov `query` not `querry`!

**Comment by vkushnirenko-luxoft** [comment]
Rebuild required

File: src/components/application_manager/include/application_manager/application_manager_impl.h (hunk 5 above)
Comment (Ypostolov) [reply src/components/application_manager/include/application_manager/application_manager_impl.h]: fixed cf05050f8c0ed76ade88e39c498ed2df15b78c82

**Comment by vkushnirenko-luxoft** [comment]
Rebuild required

File: src/components/application_manager/include/application_manager/application_manager_impl.h [hunk 6]
```diff
@@ -1443,7 +1446,7 @@ class ApplicationManagerImpl
    * will send TTS global properties to HMI after timeout
    */
   std::map<uint32_t, TimevalStruct> tts_global_properties_app_list_;
-
+  std::set<connection_handler::DeviceHandle> query_apps_devices_;
```
Comment (EKuliiev) [inline src/components/application_manager/include/application_manager/application_manager_impl.h]: @Ypostolov Can occurred data race with the filed 'query_apps_devices_'?

Comment (EKuliiev) [reply src/components/application_manager/include/application_manager/application_manager_impl.h]: @Ypostolov my opinion it should be protected.

Comment (Ypostolov) [reply src/components/application_manager/include/application_manager/application_manager_impl.h]: @EKuliiev @AByzhynar 
Fixed in e691feb95fa38c5a9082ca7e2fb1d1e2add1eccb

**Comment by Ypostolov** [comment]
Rebuild required

File: src/components/application_manager/src/application_manager_impl.cc [hunk 7]
```diff
@@ -738,42 +730,42 @@ void ApplicationManagerImpl::OnHMIStartedCooperation() {
...
   rpc_service_->ManageHMICommand(is_rc_ready);
 
-  std::shared_ptr<smart_objects::SmartObject> button_capabilities(
+  utils::SharedPtr<smart_objects::SmartObject> button_capabilities(
       MessageHelper::CreateModuleInfoSO(
           hmi_apis::FunctionID::Buttons_GetCapabilities, *this));
   rpc_service_->ManageHMICommand(button_capabilities);
 
-  std::shared_ptr<smart_objects::SmartObject> mixing_audio_supported_request(
+  utils::SharedPtr<smart_objects::SmartObject> mixing_audio_supported_request(
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_manager_impl.cc]: @Ypostolov Check all these changes. We already use shared_ptr from C++11 . Return previous code please

File: src/components/application_manager/src/application_manager_impl.cc [hunk 8]
```diff
@@ -791,6 +783,16 @@ uint32_t ApplicationManagerImpl::GetNextHMICorrelationID() {
   return corelation_id_;
 }
 
+bool ApplicationManagerImpl::BeginAudioPassThrough() {
+  sync_primitives::AutoLock lock(audio_pass_thru_lock_);
+  if (audio_pass_thru_active_) {
+    return false;
+  } else {
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_manager_impl.cc]: @Ypostolov `else`  is redunant is this particular case

File: src/components/application_manager/src/application_manager_impl.cc [hunk 9]
```diff
@@ -802,6 +804,16 @@ bool ApplicationManagerImpl::BeginAudioPassThru(uint32_t app_id) {
   }
 }
 
+bool ApplicationManagerImpl::EndAudioPassThrough() {
+  sync_primitives::AutoLock lock(audio_pass_thru_lock_);
+  if (audio_pass_thru_active_) {
+    audio_pass_thru_active_ = false;
+    return true;
+  } else {
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_manager_impl.cc]: @Ypostolov Same as above

File: src/components/application_manager/src/application_manager_impl.cc [hunk 10]
```diff
@@ -177,15 +173,15 @@ ApplicationManagerImpl::ApplicationManagerImpl(
...
+  std::srand(std::time(0));
   AddPolicyObserver(this);
 
   dir_type_to_string_map_ = {{TYPE_STORAGE, "Storage"},
                              {TYPE_SYSTEM, "System"},
                              {TYPE_ICONS, "Icons"}};
 
   sync_primitives::AutoLock lock(timer_pool_lock_);
-  TimerSPtr clearing_timer(std::make_shared<timer::Timer>(
+  TimerSPtr clearing_timer(utils::MakeShared<timer::Timer>(
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_manager_impl.cc]: @Ypostolov Check all these changes. We already use shared_ptr from C++11 . Return previous code please

File: src/components/application_manager/src/application_manager_impl.cc [hunk 11]
```diff
@@ -177,15 +173,15 @@ ApplicationManagerImpl::ApplicationManagerImpl(
     , is_low_voltage_(false)
     , apps_size_(0)
     , is_stopping_(false) {
-  std::srand(std::time(nullptr));
+  std::srand(std::time(0));
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_manager_impl.cc]: @Ypostolov Use `nullptr` like was before

File: src/components/application_manager/src/application_manager_impl.cc [hunk 12]
```diff
@@ -133,21 +128,21 @@ bool policy_app_id_comparator(const std::string& policy_app_id,
 uint32_t ApplicationManagerImpl::corelation_id_ = 0;
 const uint32_t ApplicationManagerImpl::max_corelation_id_ = UINT_MAX;
 
-namespace formatters = ns_smart_device_link::ns_json_handler::formatters;
-namespace jhs = ns_smart_device_link::ns_json_handler::strings;
+namespace formatters = NsSmartDeviceLink::NsJSONHandler::Formatters;
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_manager_impl.cc]: @Ypostolov Wrong namespaces. Please return back previous code

File: src/components/application_manager/src/application_manager_impl.cc [hunk 13]
```diff
@@ -92,13 +93,7 @@ DeviceTypes devicesType = {
                    hmi_apis::Common_TransportType::BLUETOOTH),
     std::make_pair(std::string("BLUETOOTH_IOS"),
                    hmi_apis::Common_TransportType::BLUETOOTH),
-    std::make_pair(std::string("WIFI"), hmi_apis::Common_TransportType::WIFI),
-    std::make_pair(std::string("USB_IOS_HOST_MODE"),
-                   hmi_apis::Common_TransportType::USB_IOS),
-    std::make_pair(std::string("USB_IOS_DEVICE_MODE"),
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_manager_impl.cc]: @Ypostolov Are you sure that we need to remove this code?

File: src/components/application_manager/src/application_manager_impl.cc [hunk 14]
```diff
@@ -65,6 +65,7 @@
 #include "utils/threads/thread.h"
 #include "utils/file_system.h"
 #include "utils/helpers.h"
+#include "utils/make_shared.h"
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_manager_impl.cc]: @Ypostolov Redundant in case of std::make_shared usage

**Comment by AByzhynar** [comment]
@Ypostolov Check your code for successful build after chages. Now is is not compilable.

**Comment by vkushnirenko-luxoft** [comment]
Rebuild required

**Comment by dboltovskyi** [comment]
Rebuild required

**Comment by dboltovskyi** [comment]
Rebuild required

**Comment by vkushnirenko-luxoft** [comment]
Rebuild required

**Comment by LitvinenkoIra** [comment]
Rebased to the latest develop(e137556)

**Comment by iCollin** [comment]
Changes look good. Just one question:
Why do you do this `query_apps_devices_.insert(device);` within the handler for the QueryApps response (`src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/system_request.cc:615`) instead of right after sending the QueryApps rpc?

**Comment by Ypostolov** [comment]
@iCollin 
We call https://github.com/smartdevicelink/sdl_core/blob/15253302c84a039e663673da051e6e4a35f82edc/src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/system_request.cc#L615 within the request:
https://github.com/smartdevicelink/sdl_core/blob/15253302c84a039e663673da051e6e4a35f82edc/src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/system_request.cc#L450
responce we handle later:
https://github.com/smartdevicelink/sdl_core/blob/15253302c84a039e663673da051e6e4a35f82edc/src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/system_request.cc#L660

**Comment by iCollin** [comment]
> @iCollin
> We call `OnQueryAppsRequest` within the request: `SystemRequest::Run` responce we handle later: `SystemRequest::on_event`

@Ypostolov Thank you! I was mistaken about when `Command::Run()` would be called.
