### PR TITLE
Remove redundant GetSystemInfo sending

### LINKED ISSUE #3302: SDL sends BC.GetSystemInfo twice
### Bug Report
SDL sends BC.GetSystemInfo twice on **EXTERNAL policy** flow

##### Reproduction Steps
1. Build SDL with  **EXTERNAL policy**
2. Start HMI and SDL

##### Expected Behavior
SDL requests BC.GetSystemInfo one time

##### Observed Behavior
SDL requests BC.GetSystemInfo twice

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: develop branch https://github.com/smartdevicelink/sdl_core/commit/9118fcdf8d5bfad411444513d44a59c8dfa6ff41
* Testing Against: atf test script

##### Test Case, Sample Code, and / or Example App
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2377
[TestingReports.zip](https://github.com/smartdevicelink/sdl_core/files/4370411/TestingReports.zip)

### PR DESCRIPTION
**Pull request by LitvinenkoIra**
Fixes #3302 

This PR is **[not ready]** for review.

### Risk
This PR makes **[no]** API changes.

### Testing Plan
ATF test script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2377

### Summary
SDL sends GetSystemInfo right after receiving BC.On_Ready from HMI in ApplicationManagerImpl::OnHMIStartedCooperation() - https://github.com/smartdevicelink/sdl_core/blob/develop/src/components/application_manager/src/application_manager_impl.cc#L852 
But also there was one more redundant sending of GetSystemInfo from policy_manager. So I just removed this redundant sending and some redundant functions also.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by LitvinenkoIra** [comment]
Full regression successfully passed http://172.26.147.12/view/Issue_3302/
SDL: fix/sdl_sends_get_system_info f644f397
Scripts: develop ff140f4

File: src/components/policy/policy_external/include/policy/cache_manager.h [hunk 1]
```diff
@@ -604,12 +604,6 @@ class CacheManager : public CacheManagerInterface {
                    const std::string& wers_country_code,
                    const std::string& language);
 
-  /**
-   * @brief Checks, if specific head unit is present in PT
-   * @return boot Suceess, if present, otherwise - false
-   */
-  bool IsMetaInfoPresent() const;
```
Comment (AByzhynar) [inline src/components/policy/policy_external/include/policy/cache_manager.h]: @LitvinenkoIra How this removal is related to redundant GetSystemInfo sending?

File: src/components/policy/policy_external/test/sql_pt_ext_representation_test.cc [hunk 2]
```diff
@@ -1184,7 +1184,6 @@ TEST_F(SQLPTExtRepresentationTest,
       "UPDATE `module_meta` SET `ccpu_version` = '4.1.3.B_EB355B', "
       "`wers_country_code` = 'WAEGB', `language` = 'ru-ru' ";
   ASSERT_TRUE(query_wrapper_->Exec(query_insert_meta_info));
-  EXPECT_TRUE(reps_->IsMetaInfoPresent());
```
Comment (AByzhynar) [inline src/components/policy/policy_external/test/sql_pt_ext_representation_test.cc]: @LitvinenkoIra If you removed this line - the entire test case had no sense

**Comment by AByzhynar** [comment]
@LitvinenkoIra Probably we don't have ATF test scripts for EXTERNAL POLICY which check related flow... But I think that you are breaking some functionality in EXTERNAL POLICY flow by your changes. Check the requirements again.

File: src/components/policy/policy_external/include/policy/cache_manager.h (hunk 1 above)
Comment (LitvinenkoIra) [reply src/components/policy/policy_external/include/policy/cache_manager.h]: @AByzhynar we call this function **only** inside PolicyManagerImpl::OnSystemReady() and nowhere else.

**Comment by LitvinenkoIra** [comment]
@AByzhynar All regression successfully passed and SDL **always** sends GetSystemInfo on start from App manager no matter which policies we use and after receiving the response, for external policy -  we write meta info in the database. And after that one more redundant GetSystemnfo sending occurred from the policy_manager. So I removed only this redundant sending (because according to the req- SDL should send this request once on startup) and all other functionality with saving meta info and so on - remained unchanged.

**Comment by iCollin** [comment]
While code looks good and regression passes, when starting the SDL HMI I still see at least two BC.GetSystemInfo requests immediately. Why are multiple requests made anyways?

**Comment by LitvinenkoIra** [comment]
@iCollin Thank you, could you please share the SDL log and I will check. Did you test it manually?
