### PR TITLE
Configure security level in ini file

### LINKED ISSUE #3664: Unable to establish secure connection on Ubuntu 20.04
### Bug Report
Unable to establish secure connection on Ubuntu 20.04. Though it can be done successfully on Ubuntu 18.04.
Same SDL commit, SPT version, settings and certificates.

OpenSSL version:
- Ubuntu 20.04: `1.1.1f`
- Ubuntu 18.04: `1.1.1`

##### Reproduction Steps
1. Make sure all required certificates are defined properly
2. Start SDL, HMI, connect mobile device, start SPT
3. Register new App
4. Enable secure RPC service

##### Expected Behavior
Handshake sequence is finished successfully and RPC service is switched to protected mode

##### Observed Behavior
Handshake sequence has failed and RPC service hasn't switched to protected mode

##### OS & Version Information
* OS/Version: Ubuntu 20.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (0df6608)
* Testing Against: SPT

##### Test Case, Sample Code, and / or Example App
 - Ubuntu 20.04 SDL log: [u20_SmartDeviceLinkCore.log.tar.gz](https://github.com/smartdevicelink/sdl_core/files/6153888/u20_SmartDeviceLinkCore.log.tar.gz) (FAIL)
 - Ubuntu 18.04 SDL log: [u18_SmartDeviceLinkCore.log.tar.gz](https://github.com/smartdevicelink/sdl_core/files/6153887/u18_SmartDeviceLinkCore.log.tar.gz) (SUCCESS), provided for comparison

### PR DESCRIPTION
**Pull request by VadymLuchko**
Fixes  #3664

This PR is **[ready]** for review.

### Risk
This PR makes **[no]** API changes.

### Testing Plan
Check secure connection with SyncProxyTester app 

### Summary
In Ubuntu 20.04, the OpenSSL 1.1.1f library has been modified to use Security Level 2 by default.
With this PR it becomes possible to change the Security Level in .ini file for establish secure connection with some applications that do not support this level.

In details about levels from openssl doc (https://www.openssl.org/docs/man1.1.0/man3/SSL_CTX_get_security_level.html):

Level 0
Everything is permitted. This retains compatibility with previous versions of OpenSSL.

Level 1
The security level corresponds to a minimum of 80 bits of security. Any parameters offering below 80 bits of security are excluded. As a result RSA, DSA and DH keys shorter than 1024 bits and ECC keys shorter than 160 bits are prohibited. All export ciphersuites are prohibited since they all offer less than 80 bits of security. SSL version 2 is prohibited. Any ciphersuite using MD5 for the MAC is also prohibited.

Level 2
Security level set to 112 bits of security. As a result RSA, DSA and DH keys shorter than 2048 bits and ECC keys shorter than 224 bits are prohibited. In addition to the level 1 exclusions any ciphersuite using RC4 is also prohibited. SSL version 3 is also not allowed. Compression is disabled.
...
(there are also levels 3,4,5 )

At this time setting the security level higher than 1 for general internet use is likely to cause considerable interoperability issues and is not recommended. This is because the SHA1 algorithm is very widely used in certificates and will be rejected at levels higher than 1 because it only offers 80 bits of security.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by VadymLuchko** [comment]
@JackLivio this PR is ready for review

File: src/components/security_manager/src/crypto_manager_impl.cc [hunk 1]
```diff
@@ -261,6 +261,10 @@ bool CryptoManagerImpl::Init() {
 #endif
   }
 
+#if OPENSSL_VERSION_NUMBER > OPENSSL1_1_VERSION
```
Comment (jacobkeeler) [inline src/components/security_manager/src/crypto_manager_impl.cc:264]:
```suggestion
#if OPENSSL_VERSION_NUMBER >= OPENSSL1_1_VERSION
```

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

File: src/components/security_manager/src/crypto_manager_impl.cc (hunk 1 above)
Comment (VadymLuchko) [reply src/components/security_manager/src/crypto_manager_impl.cc]: @jacobkeeler Done

**Review by jacobkeeler — APPROVED** [review]
