### PR TITLE
Fix/Deadlock during transport re-connect via USB

### LINKED ISSUE #3323: Deadlock during transport re-connect via USB
### Bug Report
Deadlock during transport re-connect via USB with Android device

##### Occurrences
2/30

##### Reproduction Steps
1. HMI and SDL are started
2. Register 3 mobile apps via USB
3. Perform transport re-connect

##### Expected Behavior
Mobile apps reconnect successfully.

##### Observed Behavior
Deadlock is occurred.

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: e8baa2d8f3f4b43d261323e0dd2c30843509e925
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

##### Logs
[SmartDeviceLinkCore.zip](https://github.com/smartdevicelink/sdl_core/files/4437220/SmartDeviceLinkCore.zip)

### PR DESCRIPTION
**Pull request by SNiukalov**
Fixes #3323 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Manual testing

### Summary
Sometimes we get a deadlock because we use the same lock in the same thread.
The situation is possible when calling the SendData, OnOutTransfer or AbortConnection functions.
They block the mutex at the start.
If in the PostOutTransfer function, which is called in SendData or indirectly in OnOutTransfer via PopOutMessage, we get the error LIBUSB_ERROR_NO_DEVICE,
this will call AbortConnection.
Which will cause a deadlock.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/transport_manager/src/usb/libusb/usb_connection.cc [hunk 1]
```diff
@@ -192,43 +194,50 @@ bool UsbConnection::PostOutTransfer() {
...
   LOG4CXX_TRACE(logger_, "enter with  Libusb_transfer*: " << transfer);
-  sync_primitives::AutoLock locker(out_messages_mutex_);
-  if (transfer->status == LIBUSB_TRANSFER_COMPLETED) {
-    bytes_sent_ += transfer->actual_length;
-    if (bytes_sent_ == current_out_message_->data_size()) {
-      LOG4CXX_DEBUG(
+  auto error_code = TransportAdapter::OK;
+  {
+    sync_primitives::AutoLock locker(out_messages_mutex_);
+    if (transfer->status == LIBUSB_TRANSFER_COMPLETED) {
```
Comment (AByzhynar) [inline src/components/transport_manager/src/usb/libusb/usb_connection.cc:212]: @SNiukalov Swap comparables please

File: src/components/transport_manager/src/usb/libusb/usb_connection.cc [hunk 2]
```diff
@@ -192,43 +194,50 @@ bool UsbConnection::PostOutTransfer() {
...
+      bytes_sent_ += transfer->actual_length;
+      if (bytes_sent_ == current_out_message_->data_size()) {
```
Comment (AByzhynar) [inline src/components/transport_manager/src/usb/libusb/usb_connection.cc:214]: @SNiukalov same as above

Comment (SNiukalov) [reply src/components/transport_manager/src/usb/libusb/usb_connection.cc]: @AByzhynar 
Thanks, fixed in:https://github.com/smartdevicelink/sdl_core/pull/3332/commits/0a50e19ee0dc5655e45a277c67cf9d42c8fc16bd

File: src/components/transport_manager/src/usb/libusb/usb_connection.cc (hunk 1 above)
Comment (SNiukalov) [reply src/components/transport_manager/src/usb/libusb/usb_connection.cc]: @AByzhynar 
Thanks, fixed in:https://github.com/smartdevicelink/sdl_core/pull/3332/commits/0a50e19ee0dc5655e45a277c67cf9d42c8fc16bd

File: src/components/transport_manager/src/usb/libusb/usb_connection.cc [hunk 3]
```diff
@@ -241,22 +250,37 @@ TransportAdapter::Error UsbConnection::SendData(
...
+    sync_primitives::AutoLock locker(out_messages_mutex_);
+    auto error_code = TransportAdapter::OK;
+    if (current_out_message_.use_count() != 0) {
+      out_messages_.push_back(message);
+    } else {
+      current_out_message_ = message;
+      error_code = PostOutTransfer();
     }
+    return error_code;
+  };
```
Comment (AByzhynar) [inline src/components/transport_manager/src/usb/libusb/usb_connection.cc:264]: @SNiukalov I would recommend to make this lambda more short & simple. 
Try to do something like : 
```cpp
auto process_message = [&]() {
  sync_primitives::AutoLock locker(out_messages_mutex_);
  if (current_out_message_.use_count() == 0) {
    current_out_message_ = message;
    return PostOutTransfer();
  } 
    out_messages_.push_back(message);
    return TransportAdapter::OK;
  };
```

File: src/components/transport_manager/src/usb/libusb/usb_connection.cc [hunk 4]
```diff
@@ -159,26 +159,28 @@ void UsbConnection::OnInTransfer(libusb_transfer* transfer) {
...
   }
   LOG4CXX_TRACE(logger_, "exit");
+  return error_code;
 }
 
-bool UsbConnection::PostOutTransfer() {
+TransportAdapter::Error UsbConnection::PostOutTransfer() {
   LOG4CXX_TRACE(logger_, "enter");
   out_transfer_ = libusb_alloc_transfer(0);
   if (0 == out_transfer_) {
```
Comment (AByzhynar) [inline src/components/transport_manager/src/usb/libusb/usb_connection.cc:180]: @SNiukalov compare it with `nullptr` please

File: src/components/transport_manager/src/usb/libusb/usb_connection.cc [hunk 5]
```diff
@@ -192,43 +194,50 @@ bool UsbConnection::PostOutTransfer() {
...
-      controller_->DataSendDone(device_uid_, app_handle_, current_out_message_);
-      PopOutMessage();
+          "USB out transfer failed: " << libusb_error_name(transfer->status));
+      controller_->DataSendFailed(
+          device_uid_, app_handle_, current_out_message_, DataSendError());
+      error_code = PopOutMessage();
+    }
+    if (current_out_message_.use_count() == 0) {
+      libusb_free_transfer(transfer);
+      out_transfer_ = NULL;
```
Comment (AByzhynar) [inline src/components/transport_manager/src/usb/libusb/usb_connection.cc:232]: @SNiukalov `nullptr`

Comment (SNiukalov) [reply src/components/transport_manager/src/usb/libusb/usb_connection.cc]: @AByzhynar 
Thanks, fixed in:https://github.com/smartdevicelink/sdl_core/pull/3332/commits/581a1b9d0e927f22754b6baa59c6df89ec19c721

File: src/components/transport_manager/src/usb/libusb/usb_connection.cc (hunk 4 above)
Comment (SNiukalov) [reply src/components/transport_manager/src/usb/libusb/usb_connection.cc]: @AByzhynar 
Thanks, fixed in:https://github.com/smartdevicelink/sdl_core/pull/3332/commits/581a1b9d0e927f22754b6baa59c6df89ec19c721

File: src/components/transport_manager/src/usb/libusb/usb_connection.cc (hunk 3 above)
Comment (SNiukalov) [reply src/components/transport_manager/src/usb/libusb/usb_connection.cc:262]: @AByzhynar 
Thanks, fixed in:https://github.com/smartdevicelink/sdl_core/pull/3332/commits/581a1b9d0e927f22754b6baa59c6df89ec19c721

Comment (AByzhynar) [reply src/components/transport_manager/src/usb/libusb/usb_connection.cc:262]: @SNiukalov Check it first - if it works. It was just an example))

Comment (SNiukalov) [reply src/components/transport_manager/src/usb/libusb/usb_connection.cc:262]: @AByzhynar 
Thanks, it is working, checked :)

File: src/components/transport_manager/src/usb/libusb/usb_connection.cc [hunk 6]
```diff
@@ -159,26 +159,28 @@ void UsbConnection::OnInTransfer(libusb_transfer* transfer) {
...
   LOG4CXX_TRACE(logger_, "exit");
+  return error_code;
 }
 
-bool UsbConnection::PostOutTransfer() {
+TransportAdapter::Error UsbConnection::PostOutTransfer() {
   LOG4CXX_TRACE(logger_, "enter");
   out_transfer_ = libusb_alloc_transfer(0);
-  if (0 == out_transfer_) {
+  if (nullptr == out_transfer_) {
```
Comment (ydementieiev) [inline src/components/transport_manager/src/usb/libusb/usb_connection.cc:180]: @SNiukalov how do you look at `if (!out_transfer_)` ?

Comment (SNiukalov) [reply src/components/transport_manager/src/usb/libusb/usb_connection.cc:180]: @ydementieiev 
Thanks, but i think nullptr here is more suitable here.
To avoid implicit nullptr conversions.

File: src/components/transport_manager/src/usb/libusb/usb_connection.cc [hunk 7]
```diff
@@ -241,22 +250,35 @@ TransportAdapter::Error UsbConnection::SendData(
...
-    current_out_message_ = message;
-    if (!PostOutTransfer()) {
-      controller_->DataSendFailed(
-          device_uid_, app_handle_, message, DataSendError());
-      LOG4CXX_TRACE(
-          logger_,
-          "exit with TransportAdapter::FAIL. Condition: !PostOutTransfer()");
-      return TransportAdapter::FAIL;
+
+  auto process_message = [&]() {
```
Comment (mvorobio) [inline src/components/transport_manager/src/usb/libusb/usb_connection.cc:254]: @SNiukalov Could we catch **this** only instead of catching by default?
```suggestion
  auto process_message = [this]() {
```

Comment (SNiukalov) [reply src/components/transport_manager/src/usb/libusb/usb_connection.cc]: @mvorobio 
Thanks, fixed in:https://github.com/smartdevicelink/sdl_core/pull/3332/commits/5904e97510a20cfd7b780f3906f2438231c7b5cb

File: src/components/transport_manager/src/usb/libusb/usb_connection.cc [hunk 8]
```diff
@@ -159,26 +159,28 @@ void UsbConnection::OnInTransfer(libusb_transfer* transfer) {
...
 }
 
-bool UsbConnection::PostOutTransfer() {
+TransportAdapter::Error UsbConnection::PostOutTransfer() {
   LOG4CXX_TRACE(logger_, "enter");
   out_transfer_ = libusb_alloc_transfer(0);
-  if (0 == out_transfer_) {
+  if (nullptr == out_transfer_) {
     LOG4CXX_ERROR(logger_, "libusb_alloc_transfer failed");
     LOG4CXX_TRACE(logger_, "exit with FALSE. Condition: 0 == out_transfer_");
```
[the remark this answers is not in the document]
Comment (SNiukalov) [reply src/components/transport_manager/src/usb/libusb/usb_connection.cc]: @ShobhitAd 
Thanks, fixed in: https://github.com/smartdevicelink/sdl_core/pull/3332/commits/e4e9c5b06bcb64c726a3ebac7d330a5e36f2a37a

File: src/components/transport_manager/src/usb/libusb/usb_connection.cc [hunk 9]
```diff
@@ -192,43 +194,50 @@ bool UsbConnection::PostOutTransfer() {
   if (LIBUSB_SUCCESS != libusb_ret) {
     LOG4CXX_ERROR(
         logger_,
-        "libusb_submit_transfer failed: " << libusb_error_name(libusb_ret)
-                                          << ". Abort connection.");
-    AbortConnection();
+        "libusb_submit_transfer failed: " << libusb_error_name(libusb_ret));
     LOG4CXX_TRACE(logger_,
                   "exit with FALSE. Condition: "
```
[the remark this answers is not in the document]
Comment (SNiukalov) [reply src/components/transport_manager/src/usb/libusb/usb_connection.cc]: @ShobhitAd 
Thanks, fixed in: https://github.com/smartdevicelink/sdl_core/pull/3332/commits/e4e9c5b06bcb64c726a3ebac7d330a5e36f2a37a

File: src/components/transport_manager/src/usb/libusb/usb_connection.cc [hunk 10]
```diff
@@ -192,43 +194,50 @@ bool UsbConnection::PostOutTransfer() {
...
                       << "LIBUSB_SUCCESS != libusb_fill_bulk_transfer");
-    return false;
+    return TransportAdapter::FAIL;
   }
   LOG4CXX_TRACE(logger_, "exit with TRUE");
```
[the remark this answers is not in the document]
Comment (SNiukalov) [reply src/components/transport_manager/src/usb/libusb/usb_connection.cc]: @ShobhitAd 
Thanks, fixed in: https://github.com/smartdevicelink/sdl_core/pull/3332/commits/e4e9c5b06bcb64c726a3ebac7d330a5e36f2a37a
