### PR TITLE
Fix perform interaction close pop up

### LINKED ISSUE #3838: SDL sends redundant UI.ClosePopUp request
### Bug Report
SDL sends redundant UI.ClosePopUp request in several cases

Issue is also relevant for cases:
  - SDL sends redundant UI.ClosePopUp request in case mobile App sends PerformInteraction request with BOTH interaction mode to SDL and HMI responds with 'SUCCESS' to VR.PerformInteraction request without choiceID
  - SDL sends redundant UI.ClosePopUp request in case mobile App sends two PerformInteraction requests with VR_ONLY interaction mode to SDL

##### Reproduction Steps
1. SDL and HMI are started
2. Mobile app is registered and activated
3. CreateInteractionChoiceSet is added
4.  App sends PerformInteraction request with VR_ONLY interaction mode to SDL
5. HMI responds with 'SUCCESS' to UI.PerformInteraction request
6. HMI responds with 'TIMED_OUT' to VR.PerformInteraction request

##### Expected Behavior
SDL does not send UI.ClosePopUp request to HMI 

##### Observed Behavior
SDL sends UI.ClosePopUp request to HMI

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: [https://github.com/smartdevicelink/sdl_core/tree/develop](https://github.com/smartdevicelink/sdl_core/tree/develop)

SDL logs: [Logs_SDL.zip](https://github.com/smartdevicelink/sdl_core/files/7734637/Logs_SDL.zip)

### PR DESCRIPTION
**Pull request by LitvinenkoIra**
Fixes #3838 

This PR is **[ready ]** for review.

### Risk
This PR makes **[no]** API changes.

### Testing Plan
ATF and manual

### Summary
In the PR we prevent to sending redundant UI.ClosePopUp request for VR interaction mode

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by LitvinenkoIra** [comment]
@theresalech This PR is ready for Livio review

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 1]
```diff
@@ -353,8 +355,14 @@ bool PerformInteractionRequest::ProcessVRResponse(
...
   }
 
+  const hmi_apis::Common_Result::eType code =
+      static_cast<hmi_apis::Common_Result::eType>(
+          message[strings::params][hmi_response::code].asInt());
+  const bool isResultSuccessful = hmi_apis::Common_Result::REJECTED != code;
+
   if (IsInterfaceAwaited(HmiInterfaces::HMI_INTERFACE_UI) &&
-      InteractionMode::MANUAL_ONLY != interaction_mode_) {
+      InteractionMode::MANUAL_ONLY != interaction_mode_ && isResultSuccessful) {
```
Comment (jacobkeeler) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc:364]: This looks to be fixing a different issue than #3838. Should there be a separate issue entered for this change?

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 2]
```diff
@@ -353,8 +355,14 @@ bool PerformInteractionRequest::ProcessVRResponse(
     return false;
   }
 
+  const hmi_apis::Common_Result::eType code =
+      static_cast<hmi_apis::Common_Result::eType>(
+          message[strings::params][hmi_response::code].asInt());
+  const bool isResultSuccessful = hmi_apis::Common_Result::REJECTED != code;
```
[the remark this answers is not in the document]
Comment (jacobkeeler) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc:361]: This seems like it is fixing a different issue than the one described in #3838

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 3]
```diff
@@ -880,7 +888,10 @@ bool PerformInteractionRequest::IsWhiteSpaceExist() {
 void PerformInteractionRequest::TerminatePerformInteraction() {
   SDL_LOG_AUTO_TRACE();
 
-  SendClosePopupRequestToHMI();
+  if (mobile_apis::InteractionMode::VR_ONLY != interaction_mode_) {
```
Comment (jacobkeeler) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc:891]:
```suggestion
  if (!ui_response_received_) {
```
Seems like this would be a better check in this case, since the issue is that this message is being sent when the HMI has already responded to the UI message

Comment (LitvinenkoIra) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: Done in d0ea3818b99115c4a00cb11bfe193f7d1fe7dbc5

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 4]
```diff
@@ -225,6 +225,8 @@ void PerformInteractionRequest::Run() {
   // increment amount of active requests
   ++pi_requests_count_;
 
+  SDL_LOG_ERROR("Send PerformInteraction requests");
+
```
[the remark this answers is not in the document]
Comment (LitvinenkoIra) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: Done in d0ea3818b99115c4a00cb11bfe193f7d1fe7dbc5

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc (hunk 2 above)
[the remark this answers is not in the document]
Comment (LitvinenkoIra) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: I propose to continue our discussion [here](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2620#discussion_r789564840)

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc (hunk 3 above)
Comment (LitvinenkoIra) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: Please note that we are performing the regression testing after the latest updates. I’ll let you know when the status will be known

Comment (LitvinenkoIra) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @jacobkeeler This PR is ready for review

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 5]
```diff
@@ -353,8 +355,16 @@ bool PerformInteractionRequest::ProcessVRResponse(
...
+  const hmi_apis::Common_Result::eType code =
+      static_cast<hmi_apis::Common_Result::eType>(
+          message[strings::params][hmi_response::code].asInt());
+  const bool is_result_successful =
+      CommandImpl::IsHMIResultSuccess(code, HmiInterfaces::HMI_INTERFACE_VR);
+
   if (IsInterfaceAwaited(HmiInterfaces::HMI_INTERFACE_UI) &&
-      InteractionMode::MANUAL_ONLY != interaction_mode_) {
+      InteractionMode::MANUAL_ONLY != interaction_mode_ &&
+      is_result_successful) {
```
Comment (jacobkeeler) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc:366]: Hmmm, this also seems like it misses a few cases:

1. If an app sends `BOTH` mode and the HMI responds with `SUCCESS` to VR, `UI.ClosePopUp` should only be sent if `choiceID` is included, otherwise you would want to wait for a UI response.
2. If an app sends `VR_ONLY` mode and the HMI responds with `SUCCESS` to VR, `UI.ClosePopUp` should be sent regardless of whether or not `choiceID` is included, since the `choiceID` cannot come from the UI.

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 6]
```diff
@@ -880,7 +890,10 @@ bool PerformInteractionRequest::IsWhiteSpaceExist() {
 void PerformInteractionRequest::TerminatePerformInteraction() {
   SDL_LOG_AUTO_TRACE();
 
-  SendClosePopupRequestToHMI();
+  if (!ui_choice_id_received_) {
```
[the remark this answers is not in the document]
Comment (LitvinenkoIra) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: Done in https://github.com/smartdevicelink/sdl_core/pull/3844/commits/8b100f9742d5f2e419fb7847b0a5e4603b035f16

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 7]
```diff
@@ -371,24 +367,26 @@ bool PerformInteractionRequest::ProcessVRResponse(
...
+      vr_result_code_, HmiInterfaces::HMI_INTERFACE_VR);
+
+  if (IsInterfaceAwaited(HmiInterfaces::HMI_INTERFACE_UI) &&
+      is_vr_result_successful) {
+    if ((mobile_apis::InteractionMode::BOTH == interaction_mode_ &&
+         vr_choice_id_received_ != INVALID_CHOICE_ID) ||
+        mobile_apis::InteractionMode::VR_ONLY == interaction_mode_) {
+      SDL_LOG_DEBUG("Send Close PopupRequest");
+      SendClosePopupRequestToHMI();
+    }
```
[the remark this answers is not in the document]
Comment (LitvinenkoIra) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: Done in [3df047b](https://github.com/smartdevicelink/sdl_core/pull/3844/commits/3df047bd65e5b7e75ff169c1a686046ed60a7943)

**Review by jacobkeeler — APPROVED** [review]
