### PR TITLE
Error message processing from HMI

### LINKED ISSUE #3014: SDL does not  resend Error GetVehicleData response from HMI
### Bug Report
SDL does not  resend Error GetVehicleData response from HMI

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile, register new App
2. Send GetVehicleData with speed = true
3. Send HMI response with {"error":{"code":9,"data":{"method":"VehicleInfo.GetVehicleData"},  message:"error message" },"id":57,"jsonrpc":"2.0"}

##### Expected Behavior
1) SDL sends to HMI VehicleInfo.GetVehicleData: "params":  { "speed":true }
2) SDL sends to mobile response of GetVehicleData with {"resultCode":"VEHICLE_DATA_NOT_AVAILABLE", "success":false, info = "error message"}

##### Observed Behavior
1) SDL sends to HMI VehicleInfo.GetVehicleData: "params":  { "speed":true }
2) SDL sends to mobile response of GetVehicleData with {"resultCode":"GENERIC_ERROR","success":false}

##### OS & Version Information
* OS/Version: OS/Version: Ubuntu 16.04 amd64
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (bc8288d)
* ATF: https://github.com/smartdevicelink/sdl_atf/tree/feature/script_runner (e4b9574)

##### Test Case, Sample Code, and / or Example App
[logs.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3575404/logs.tar.gz)
[script.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3580760/script.tar.gz)

### PR DESCRIPTION
**Pull request by mkorniichuk**
Fixes #3014, #2439

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
Fix for error message processing received from HMI (#3014).
Also, there is a fix for invalid result code received on Mobile (#2439). (previous fix is not actual due to new features merged into develop)

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/include/application_manager/commands/command_request_impl.h [hunk 1]
```diff
@@ -214,6 +214,22 @@ class CommandRequestImpl : public CommandImpl,
   mobile_apis::Result::eType GetMobileResultCode(
       const hmi_apis::Common_Result::eType& hmi_code) const;
 
+  /**
+   * @brief Checks result code from Mobile for single RPC
```
Comment (AByzhynar) [inline src/components/application_manager/include/application_manager/commands/command_request_impl.h]: @mkorniichuk Do we check result code coming from mobile?

File: src/components/application_manager/include/application_manager/commands/command_request_impl.h [hunk 2]
```diff
@@ -214,6 +214,22 @@ class CommandRequestImpl : public CommandImpl,
...
+   * @param result_code contains result code from Mobile response
+   * @return true if result code complies successful result codes,
+   * false otherwise.
+   */
+  static bool IsMobileResultSuccess(mobile_apis::Result::eType result_code);
+
+  /**
+   * @brief Checks result code from HMI for single RPC
+   * @param result_code contains result code from Mobile response
```
Comment (AByzhynar) [inline src/components/application_manager/include/application_manager/commands/command_request_impl.h]: @mkorniichuk `Mobile response` ?

File: src/components/application_manager/include/application_manager/commands/command_request_impl.h [hunk 3]
```diff
@@ -214,6 +214,22 @@ class CommandRequestImpl : public CommandImpl,
   mobile_apis::Result::eType GetMobileResultCode(
       const hmi_apis::Common_Result::eType& hmi_code) const;
 
+  /**
+   * @brief Checks result code from Mobile for single RPC
+   * @param result_code contains result code from Mobile response
+   * @return true if result code complies successful result codes,
```
Comment (mked-luxoft) [inline src/components/application_manager/include/application_manager/commands/command_request_impl.h]: i think it's better to use `complies to` or `if result code is successful`

File: src/components/application_manager/include/application_manager/commands/command_request_impl.h [hunk 4]
```diff
@@ -214,6 +214,22 @@ class CommandRequestImpl : public CommandImpl,
...
+   * false otherwise.
+   */
+  static bool IsMobileResultSuccess(mobile_apis::Result::eType result_code);
+
+  /**
+   * @brief Checks result code from HMI for single RPC
+   * @param result_code contains result code from Mobile response
+   * @return true if result code complies successful result codes,
```
Comment (mked-luxoft) [inline src/components/application_manager/include/application_manager/commands/command_request_impl.h]: same here

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/get_vehicle_data_request.cc [hunk 5]
```diff
@@ -119,13 +119,30 @@ void GetVehicleDataRequest::on_event(const event_engine::Event& event) {
...
-                (message[strings::msg_params].length() > 1));
+
+      auto data_not_available_with_params = [&result_code, &message]() {
+        if (hmi_apis::Common_Result::DATA_NOT_AVAILABLE != result_code) {
+          return false;
+        }
+
+        const auto& msg_params = message[strings::msg_params];
+        switch (msg_params.length()) {
+          case 0:
```
Comment (mked-luxoft) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/get_vehicle_data_request.cc]: i think it's better to avoid signed/unsigned comparisons

File: src/components/application_manager/src/commands/command_request_impl.cc [hunk 6]
```diff
@@ -909,18 +903,24 @@ bool CommandRequestImpl::IsMobileResultSuccess(
       mobile_apis::Result::SAVED);
 }
 
+bool CommandRequestImpl::IsHMIResultSuccess(
+    hmi_apis::Common_Result::eType result_code) {
```
Comment (AByzhynar) [inline src/components/application_manager/src/commands/command_request_impl.cc]: @mkorniichuk const to parameter?

File: src/components/application_manager/include/application_manager/commands/command_request_impl.h (hunk 1 above)
Comment (mkorniichuk) [reply src/components/application_manager/include/application_manager/commands/command_request_impl.h]: @AByzhynar fixed in 5db179eb26efd1a99c0178db3afb9d1e077cb383

File: src/components/application_manager/include/application_manager/commands/command_request_impl.h (hunk 2 above)
Comment (mkorniichuk) [reply src/components/application_manager/include/application_manager/commands/command_request_impl.h]: @AByzhynar fixed in 5db179eb26efd1a99c0178db3afb9d1e077cb383

File: src/components/application_manager/include/application_manager/commands/command_request_impl.h (hunk 3 above)
Comment (mkorniichuk) [reply src/components/application_manager/include/application_manager/commands/command_request_impl.h]: @mked-luxoft fixed in 5db179eb26efd1a99c0178db3afb9d1e077cb383

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/get_vehicle_data_request.cc (hunk 5 above)
Comment (mkorniichuk) [reply src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/get_vehicle_data_request.cc]: @mked-luxoft fixed in 5db179eb26efd1a99c0178db3afb9d1e077cb383

File: src/components/application_manager/src/commands/command_request_impl.cc (hunk 6 above)
Comment (mkorniichuk) [reply src/components/application_manager/src/commands/command_request_impl.cc]: @AByzhynar fixed in 5db179eb26efd1a99c0178db3afb9d1e077cb383

File: src/components/application_manager/include/application_manager/commands/command_request_impl.h (hunk 4 above)
Comment (mkorniichuk) [reply src/components/application_manager/include/application_manager/commands/command_request_impl.h]: @mked-luxoft fixed in 5db179eb26efd1a99c0178db3afb9d1e077cb383

File: src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/get_vehicle_data_request.cc [hunk 7]
```diff
@@ -119,13 +119,30 @@ void GetVehicleDataRequest::on_event(const event_engine::Event& event) {
       hmi_apis::Common_Result::eType result_code =
           static_cast<hmi_apis::Common_Result::eType>(
               message[strings::params][hmi_response::code].asInt());
+      mobile_apis::Result::eType mobile_result_code =
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/vehicle_info_plugin/src/commands/mobile/get_vehicle_data_request.cc]: @mkorniichuk May be `auto` ?

**Comment by mkorniichuk** [comment]
@theresalech current PR is ready for Livio review.

File: src/components/application_manager/src/commands/command_request_impl.cc [hunk 8]
```diff
@@ -909,18 +903,25 @@ bool CommandRequestImpl::IsMobileResultSuccess(
...
+      hmi_apis::Common_Result::WRONG_LANGUAGE,
+      hmi_apis::Common_Result::RETRY,
+      hmi_apis::Common_Result::SAVED);
+}
+
 bool CommandRequestImpl::PrepareResultForMobileResponse(
     hmi_apis::Common_Result::eType result_code,
     HmiInterfaces::InterfaceID interface) const {
   LOG4CXX_AUTO_TRACE(logger_);
   using namespace helpers;
```
[the remark this answers is not in the document]
Comment (mkorniichuk) [reply src/components/application_manager/src/commands/command_request_impl.cc]: @iCollin fixed in ddc21636ce187e74a88c7e0169673c0aa5b298a5

File: src/components/application_manager/src/rpc_handler_impl.cc [hunk 9]
```diff
@@ -405,7 +405,7 @@ bool RPCHandlerImpl::ConvertMessageToSO(
                     "Convertion result: "
                         << result << " function id "
                         << output[jhs::S_PARAMS][jhs::S_FUNCTION_ID].asInt());
-      if (!hmi_so_factory().attachSchema(output, !allow_unknown_parameters)) {
+      if (!hmi_so_factory().attachSchema(output, false)) {
```
[the remark this answers is not in the document]
Comment (mkorniichuk) [reply src/components/application_manager/src/rpc_handler_impl.cc]: @iCollin `!allow_unknown_parameters` was introduced within Read Generic Network Signal Data feature. But in the latest implementation, it was not necessary, moreover, it caused a regression issue. So, it is just some reverting.
