### PR TITLE
Append LD_LIBRARY_PATH in daemon.sh

### LINKED ISSUE #3700: daemon.sh overwrites LD_LIBRARY_PATH
[Delete any non-applicable sections, but we may ask for more information. Please reference the [SmartDeviceLink GitHub Best Practices](https://d83tozu1c8tt6.cloudfront.net/media/resources/SDL_GitHub_BestPractices.pdf) for further instructions on how to enter an issue.]

### Bug Report
This line in daemon.sh overwrites env var LD_LIBRARY_PATH
```
LD_LIBRARY_PATH=$DIR ${DIR}/${CORE_APPLICATION_NAME} &
```

##### Reproduction Steps
- Build Core with 3rd party libs
```
 export export THIRD_PARTY_INSTALL_PREFIX=~/ramdrv/b/3rd_party
 export THIRD_PARTY_INSTALL_PREFIX_ARCH=$THIRD_PARTY_INSTALL_PREFIX
```

- Set LD_LIBRARY_PATH
```
export LD_LIBRARY_PATH=/home/jack/core_3rd/lib:.
```

##### Expected Behavior
Core starts with 3rd party libs folder

##### Observed Behavior
Core cannot find lib .SO files.

### PR DESCRIPTION
**Pull request by JackLivio**
Fixes #3700 

This PR is **Ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Build SDL Core with 3rd party library env var set. Run core after setting LD_LIBRARY_PATH. See issue for more details.

### Summary
Appends LD_LIBRARY_PATH instead of overwriting in the daemon script.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/appMain/daemon.sh [hunk 1]
```diff
@@ -19,7 +19,7 @@ function core_start() {
     return 2
   else
     echo "Starting SmartDeviceLink Core"
-    LD_LIBRARY_PATH=$DIR ${DIR}/${CORE_APPLICATION_NAME} &
+    LD_LIBRARY_PATH=$DIR:$LD_LIBRARY_PATH ${DIR}/${CORE_APPLICATION_NAME} &
```
Comment (jacobkeeler) [inline src/appMain/daemon.sh:22]:
```suggestion
   ${DIR}/${CORE_APPLICATION_NAME} &
```
It looks like this variable is no longer necessary to set, the script runs fine without this part of the command. That said, I don't think it harms anything to keep it, so it's your call whether to apply this suggestion or not

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

**Review by jacobkeeler — APPROVED** [review]
