### PR TITLE
Fix defect: revoked app still be resumed as FULL.

### LINKED ISSUE #2447: Resumption: revoked app still be resumed as FULL
### Bug Report
Resumption: revoked app still be resumed as FULL 

### Precondition:
SDL Core and HMI are started.

##### Reproduction Steps
1. Register app with name = App1 and Id = 999 with uncheck Policy File Update
2. Enter FULL
3. Force stop application
4. Start SPT then register another app and send LPT update. Then app in step 1 becomes revoked
5. Register app with name = App1 and Id = 999 

##### Expected Behavior
SDL can't resume App1 as FULL

##### Observed Behavior
SDL resumes App1 as FULL and not send OnHMIStatus() notification to mobile app

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

### PR DESCRIPTION
**Pull request by IGapchuk**
Fixes #2447 

This PR is ready for review.

### Risk
This PR makes no API changes.

### Testing Plan
Covered by ATF tests.

### Summary
This changes did according to:

In case PolicesManager receives SDL.ActivateApp from HMI AND the Local PT contains the revoked permissions for the named application, PoliciesManager must respond with "isAppPermissionRevoked:true" AND "AppRevokedPermissions" param containing the list of revoked permissions to HMI.

HMI Information: 
If isAppPermissionsRevoked is set to "true", HMI is expected to send a request to SDL to get messages for specified permissions using GetUserFriendlyMessage and notifies user that provided permissions of application were decreased.

If app permissions were reduced after PTU, SDL sends OnAppPermissionChanged (isAppPermissionsRevoked: true) when app is in FULL or LIMITED
SDL doesn't notify HMI about revoked permissions twice

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/resumption/resume_ctrl_impl.cc [hunk 1]
```diff
@@ -482,15 +482,24 @@ void ResumeCtrlImpl::StartAppHmiStateResumption(
...
       CheckIgnCycleRestrictions(saved_app);
 
-  const bool restore_hmi_level_allowed =
-      is_resume_allowed_by_low_voltage && is_hmi_level_allowed_by_ign_cycle;
+  const bool is_app_revoked =
+      application_manager_.GetPolicyHandler().IsApplicationRevoked(
+          application->policy_app_id());
+
+  const mobile_apis::HMILevel::eType app_hmi_level = application->hmi_level();
+  const bool hmi_level_allow =
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/src/resumption/resume_ctrl_impl.cc]: @IGapchuk you can remove this check for allowed for resumption HMI level as it is already done in `CheckAppRestrictions()` before that. Just keep `is_app_revoked`

Comment (IGapchuk) [reply src/components/application_manager/src/resumption/resume_ctrl_impl.cc]: @AKalinich-Luxoft  Fixed in ec314ff446e9674f40a55a162cdc239a328613ec

**Comment by vkushnirenko-luxoft** [comment]
Rebuild required

**Comment by ZhdanovP** [comment]
@IGapchuk don't put in description links to Jira, this is the closed resource, better to use information from Jira tickets like a quote.
