### PR TITLE
Fix SDL does not set the app to NONE HMI level after a rejecting of StartService

### LINKED ISSUE #3073: SDL does not set the app to NONE HMI level after a rejecting of StartService
### Bug Report
SDL does not set the app to NONE HMI level after a rejecting of StartService

##### Precondition
1. HMI and SDL are started
2. Navigation app is registered and activated

##### Reproduction Steps
1. App requests start of the protected video/audio/rpc service
2. Protected service can't be started by any reason: invalid cert, invalid ptu, not successful response to GetSystemTime

##### Expected Behavior
1. SDL responds with NACK to mobile application
2. SDL sends BC.OnServiceUpdate(serviceEvent = "REQUEST_REJECTED") to HMI with the appropriate reason 
3. SDL sends BC.CloseApplication(appID)
4. SDL sets app to NONE HMI level and sends OnHMILevel(NONE) to mobile application 

##### Observed Behavior
SDL does not sent app to NONE HMI level and does not send the OnHMILevel(NONE) to mobile application 

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/2b09ea3adf962e25717b6b4cd751173f0aa40d02
* HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop(1db5de1dfb5afbbbcdca266662faeb0d7d2050e4)
* SPT: https://rink.hockeyapp.net/apps/dbc7db5274027027262185753824e34d
* Scripts: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2280

Logs:
[2019-10-11_12-09-16.zip](https://github.com/smartdevicelink/sdl_core/files/3716733/2019-10-11_12-09-16.zip)

### PR DESCRIPTION
**Pull request by IGapchuk**
Fixes #3073

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
There is the issue when SDL tries to start streaming service (VIDEO or AUDIO) and receives a rejected request from HMI (e.g. GetSystemTime(INVALID_TIME)). In this case, SDL should send to mobile device OnHMIStatus("NONE") notification and send CloseApplication request to HMI.
In the current implementation in the case when SDL receives a rejected request, it sends just OnServiceUpdate notification to HMI with reject reason.
This PR provides changes for ApplicationManagerImpl, In that case SDL removes records about service status and sends to mobile device OnHMIStatus("NONE") notification and sends CloseApplication request to HMI.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/application_manager_impl.cc [hunk 1]
```diff
@@ -2068,6 +2068,39 @@ void ApplicationManagerImpl::ProcessServiceStatusUpdate(
       service_type, service_event, reason, app_id);
 
   rpc_service_->ManageHMICommand(notification);
+
+  if (hmi_apis::Common_ServiceEvent::REQUEST_REJECTED == service_event) {
+    StopServicesForApp(app, service_type);
+    state_ctrl_.SetRegularState(app,
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/src/application_manager_impl.cc]: @IGapchuk better to use `StateControllerImpl::ExitDefaultWindow`

File: src/components/application_manager/include/application_manager/application_manager_impl.h [hunk 2]
```diff
@@ -1137,6 +1137,11 @@ class ApplicationManagerImpl
   protocol_handler::MajorProtocolVersion SupportedSDLVersion() const OVERRIDE;
 
  private:
+  /**
+   * @brief Stop services that failed to start
+   */
+  void StopServicesForApp(ApplicationSharedPtr app,
+                          hmi_apis::Common_ServiceType::eType service_type);
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/include/application_manager/application_manager_impl.h]: @IGapchuk const?

File: src/components/application_manager/include/application_manager/application_manager_impl.h [hunk 3]
```diff
@@ -1137,6 +1137,11 @@ class ApplicationManagerImpl
   protocol_handler::MajorProtocolVersion SupportedSDLVersion() const OVERRIDE;
 
  private:
+  /**
+   * @brief Stop services that failed to start
```
[the remark this answers is not in the document]
Comment (IGapchuk) [reply src/components/application_manager/include/application_manager/application_manager_impl.h]: @AKalinich-Luxoft Done 4bd2c82ea75a7727ac5dc9af879bcf6908e4649f

File: src/components/application_manager/src/application_manager_impl.cc (hunk 1 above)
Comment (IGapchuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @AKalinich-Luxoft I believe we can't use it because after setting regular state SDL should send to HMI CloseApplication Request for closing the specified application.

File: src/components/application_manager/include/application_manager/application_manager_impl.h (hunk 2 above)
Comment (IGapchuk) [reply src/components/application_manager/include/application_manager/application_manager_impl.h]: @AKalinich-Luxoft Done 4bd2c82ea75a7727ac5dc9af879bcf6908e4649f

File: src/components/application_manager/src/application_manager_impl.cc [hunk 4]
```diff
@@ -2068,6 +2068,39 @@ void ApplicationManagerImpl::ProcessServiceStatusUpdate(
...
+    LOG4CXX_WARN(logger_, "Received invalid app");
+    return;
+  }
+
+  switch (service_type) {
+    case hmi_apis::Common_ServiceType::VIDEO: {
+      {
+        sync_primitives::AutoLock lock(navi_service_status_lock_);
+        navi_service_status_.erase(app->app_id());
+      }
```
[the remark this answers is not in the document]
Comment (IGapchuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @AKalinich-Luxoft Removed in 4bd2c82ea75a7727ac5dc9af879bcf6908e4649f

File: src/components/application_manager/src/state_controller_impl.cc [hunk 5]
```diff
@@ -264,7 +264,7 @@ void StateControllerImpl::SetRegularState(ApplicationSharedPtr app,
 
   // SDL should send BC.ActivateApp for main window during resumption
   if (mobile_apis::PredefinedWindows::DEFAULT_WINDOW == window_id &&
-      mobile_apis::HMILevel::HMI_FULL == state->hmi_level()) {
+      (mobile_apis::HMILevel::HMI_FULL == state->hmi_level())) {
```
[the remark this answers is not in the document]
Comment (IGapchuk) [reply src/components/application_manager/src/state_controller_impl.cc]: @AKalinich-Luxoft Removed in 4bd2c82ea75a7727ac5dc9af879bcf6908e4649f

File: src/components/application_manager/src/application_manager_impl.cc [hunk 6]
```diff
@@ -2068,6 +2068,37 @@ void ApplicationManagerImpl::ProcessServiceStatusUpdate(
...
+    case hmi_apis::Common_ServiceType::VIDEO: {
+      sync_primitives::AutoLock lock(navi_service_status_lock_);
+      navi_service_status_.erase(app->app_id());
+      LOG4CXX_DEBUG(logger_,
+                    "ServiceType: " << service_type << " for appID: "
+                                    << app->app_id() << " is stopped");
+      break;
+    }
+    default:
+      break;
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_manager_impl.cc]: @IGapchuk Add some logging here

**Comment by AByzhynar** [comment]
@IGapchuk Fix PR description. AFAIK we don't have OnHMILevel notification

File: src/components/application_manager/src/application_manager_impl.cc (hunk 6 above)
Comment (IGapchuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @AByzhynar Added in 3d16f70fc4034c68e2cfc2baa8fb159fb4007a83

**Comment by IGapchuk** [comment]
@AByzhynar Also PR's description has been updated.

File: src/components/application_manager/src/application_manager_impl.cc [hunk 7]
```diff
@@ -2068,6 +2068,38 @@ void ApplicationManagerImpl::ProcessServiceStatusUpdate(
...
+  if (hmi_apis::Common_ServiceEvent::REQUEST_REJECTED == service_event) {
+    StopServicesForApp(app, service_type);
+    state_ctrl_.SetRegularState(app,
+                                mobile_apis::PredefinedWindows::DEFAULT_WINDOW,
+                                mobile_apis::HMILevel::HMI_NONE,
+                                true);
+  }
+}
+
+void ApplicationManagerImpl::StopServicesForApp(
```
Comment (JackLivio) [inline src/components/application_manager/src/application_manager_impl.cc]: What is the purpose of this method? I dont really follow how this addresses the original issue? Why is the only case for VIDEO and not audio/rpc?

Also 

> navi_service_status_.erase(app->app_id());

isnt really stopping anything, its just deleting the app id from a data structure.

**Comment by theresalech** [comment]
@IGapchuk please let us know when this is ready for re-review.  Thanks!

File: src/components/application_manager/src/application_manager_impl.cc [hunk 8]
```diff
@@ -2068,6 +2068,77 @@ void ApplicationManagerImpl::ProcessServiceStatusUpdate(
...
+      }
+
+      connection_handler().SendEndService(
+          app->app_id(), protocol_handler::ServiceType::kMobileNav);
+      app->StopStreamingForce(protocol_handler::ServiceType::kMobileNav);
+
+      LOG4CXX_DEBUG(logger_,
+                    "ServiceType: " << service_type << " for appID: " << app
+                                    << " is stopped");
+    } break;
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_manager_impl.cc]: @IGapchuk `break` must be inside the case statement

File: src/components/application_manager/src/application_manager_impl.cc [hunk 9]
```diff
@@ -2068,6 +2068,77 @@ void ApplicationManagerImpl::ProcessServiceStatusUpdate(
...
+                                    << " is stopped");
+      break;
+    }
+    case hmi_apis::Common_ServiceType::RPC: {
+      connection_handler().SendEndService(app->app_id(),
+                                          protocol_handler::ServiceType::kRpc);
+      LOG4CXX_DEBUG(logger_,
+                    "ServiceType: " << service_type << " for appID: " << app
+                                    << " is stopped");
+    } break;
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_manager_impl.cc]: @IGapchuk Move break into `case` statement

**Comment by dboltovskyi** [comment]
@theresalech Please notice fix is ready for review.

File: src/components/application_manager/src/application_manager_impl.cc [hunk 10]
```diff
@@ -2068,6 +2068,79 @@ void ApplicationManagerImpl::ProcessServiceStatusUpdate(
...
+  if (hmi_apis::Common_ServiceEvent::REQUEST_REJECTED == service_event &&
+      StopServicesForApp(app, service_type)) {
+    state_ctrl_.SetRegularState(app,
+                                mobile_apis::PredefinedWindows::DEFAULT_WINDOW,
+                                mobile_apis::HMILevel::HMI_NONE,
+                                true);
+  }
+}
+
+bool ApplicationManagerImpl::StopServicesForApp(
```
Comment (JackLivio) [inline src/components/application_manager/src/application_manager_impl.cc]: Thank you for these updates, but looking at the application manager methods there are a now a few ways of "stopping" a navigation service. To avoid code redundancy, can ProcessServiceStatusUpdate or StopServicesForApp make use o the EndNaviServices Method?

File: src/components/application_manager/src/application_manager_impl.cc [hunk 11]
```diff
@@ -2068,6 +2068,79 @@ void ApplicationManagerImpl::ProcessServiceStatusUpdate(
...
+    return false;
+  }
+
+  switch (service_type) {
+    case hmi_apis::Common_ServiceType::VIDEO: {
+      {
+        sync_primitives::AutoLock lock(navi_service_status_lock_);
+        auto app_services = navi_service_status_.find(app->app_id());
+        if (navi_service_status_.end() != app_services) {
+          navi_service_status_.erase(app_services);
```
Comment (JackLivio) [inline src/components/application_manager/src/application_manager_impl.cc]: Deleting the item from navi_service_status_ will delete the status for both video and audio, even though Video is the only service type specified here. EndNaviServices has a cleaner way of addressing this issue.

**Comment by theresalech** [comment]
@IGapchuk please let us know when this is ready for re-review. Thanks!

**Comment by IGapchuk** [comment]
Hi @JackLivio 

During the internal investigation, we make the result that sending EndService message to mobile in the case when we had sent ServiceStartNACK before, it is not applicable behavior for SDL.
In the case when SDL receives the, for example, GetSystemTime(REJECTED) message there is the next issue:
GetSystemTime_CURRENT_IMPLEMENTATION
We believe that sending ServiceStartACK to mobile should mean that the service is started successfully and only, in this case, serviceStatus should be marked as started ("true").

**Comment by IGapchuk** [comment]
The applicable behavior for SDL to send EndService is the case, when the application's HMI level has been changed to a non-streamable HMI level (NONE).
Please take a look at the diagram:
GetSystemTime_SUCCESS

**Comment by IGapchuk** [comment]
If SDL will send EndServer without sending StartServiceAck to an application, it could next situations:

1. In the case with one service won't be an issue:
Using_EndNaviServices_One_Service

2. But in case with two service could be the issue:
Using_EndNaviServices_Two_Services

**Comment by IGapchuk** [comment]
Our solution to fix the issue is removing the service status record on the SDL side when SDL receives the a rejected request (e.x. GetSystemTime RPC)
Please take a look at the diagram:
fix_solution

**Comment by IGapchuk** [comment]
@JackLivio please be informed that it is slightly different implementation.

**Comment by JackLivio** [comment]
@IGapchuk We would appreciate if you did not force push on sdl_core repository. It makes it difficult to review a PR because we cannot tell what was changed since the last review. In general, please do not rebase, do not force push against sdl_core. Instead, you can merge the current develop branch into your PR branch. Thank you

**Comment by JackLivio** [comment]
@IGapchuk Thank you for these charts. Question about this chart 



Is there supposed to be another start service NACK for the audio service that was rejected?

File: src/components/application_manager/include/application_manager/application_manager_impl.h [hunk 12]
```diff
@@ -1137,6 +1137,14 @@ class ApplicationManagerImpl
...
+   * @param app Application whose service should be stopped
+   * @param Service type that should be stopped
+   */
+  bool StopServicesForApp(
```
Comment (JackLivio) [inline src/components/application_manager/include/application_manager/application_manager_impl.h]: @IGapchuk Can the name of this method be changed to something other than "Stop" since video and audio services are just being cleaned up. Maybe "HandleRejectedServiceStatus()"?

**Comment by IGapchuk** [comment]
@JackLivio Thank you for the comments! I will avoid the force push during a code review.
About the last diagram and your question - yes, you are right, there was supposed to be another start service NACK for the audio service that was rejected (the behavior of the SDL, in this case, should be the same). It is just the mistake in the diagram. I added the few missed calls for the audio service into the diagram, please take a look:
fix_solution

File: src/components/application_manager/include/application_manager/application_manager_impl.h (hunk 12 above)
Comment (IGapchuk) [reply src/components/application_manager/include/application_manager/application_manager_impl.h]: @JackLivio  I agree with you, the `HandleRejectedServiceStatus` name looks better for the method.
Please, take a look at changes: 148c16bb64335b5be093c63d144ee5a48211d724

Comment (IGapchuk) [reply src/components/application_manager/include/application_manager/application_manager_impl.h]: @JackLivio  The comments have been processed. Please inform me when the review will be completed,`--fixup` commits should be squashed and fix branch should be rebased onto current develop. Thank you.

**Comment by IGapchuk** [comment]
@JackLivio The comments have been processed. Please inform me when the review will be completed,`--fixup` commits should be squashed and fix branch should be rebased onto current develop. Thank you.
