### PR TITLE
SDL forwards `OnButtonEvent` notification of `CUSTOM_BUTTON` to `BACKGROUND` App.

### LINKED ISSUE #967: CCB: SDL forw OnButtonEvent of CUSTOM_BTN to BACKGROUND
### Bug Report
SDL not forwards OnButtonEvent notification of CUSTOM_BUTTON to BACKGROUND App

##### Reproduction Steps
1. Make sure app is in BACKGROUND HMI level
2. Send OnButtonEvent(CUSTOM_BUTTON, SHORT/LONG) from HMI

##### Expected Behavior
Notification is re-sent to App

##### Observed Behavior
SDL didn't resend notification to App

##### OS & Version Information
commit: 
* OS/Version: Ubuntu 16.04
* SDL Core Version: a4c2702
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
* [att_issue#967.zip](https://github.com/smartdevicelink/sdl_core/files/575677/att_issue.967.zip)
* Updated script: [967_OnButtonPress_OnButtonEvent_in_background.lua.zip](https://github.com/smartdevicelink/sdl_core/files/2572423/967_OnButtonPress_OnButtonEvent_in_background.lua.zip)

### PR DESCRIPTION
**Pull request by ValeriiMalkov**
Fixes #967 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
This PR provided bugfixing when SDL doesn't send notification `onButtonEvent` notification to mobile of `CUSTOM_BUTTON` in `BACKGROUND` app.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by vkushnirenko-luxoft** [comment]
Rebuild required

**Comment by LitvinenkoIra** [comment]
Rebased to the latest develop ([e137556](https://github.com/smartdevicelink/sdl_core/commit/e137556512215ded94228e33d21ab4c3e1af3017))

**Comment by IGapchuk** [comment]
Rebased to the latest develop(49c29364460faa527bc758d0fd6b108463f8d82d)

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/on_button_event_notification.cc [hunk 1]
```diff
@@ -105,11 +105,10 @@ void OnButtonEventNotification::Run() {
     const auto window_id = app->GetSoftButtonWindowID(custom_btn_id);
     (*message_)[strings::msg_params][strings::window_id] = window_id;
     const auto window_hmi_level = app->hmi_level(window_id);
-    if ((mobile_api::HMILevel::HMI_FULL != window_hmi_level) &&
-        (mobile_api::HMILevel::HMI_LIMITED != window_hmi_level)) {
+    if ((mobile_api::HMILevel::HMI_NONE == window_hmi_level)) {
       LOG4CXX_WARN(logger_,
                    "CUSTOM_BUTTON OnButtonEvent notification is allowed only "
-                       << "in FULL or LIMITED hmi level");
+                       << "in FULL, LIMITED or BACKGROUND hmi level");
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/on_button_event_notification.cc]: lets change this log to match the condition:
`CUSTOM_BUTTON OnButtonEvent notification is not allowed in NONE hmi level`

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/on_button_press_notification.cc [hunk 2]
```diff
@@ -108,11 +108,10 @@ void OnButtonPressNotification::Run() {
     app->hmi_level(mobile_apis::PredefinedWindows::DEFAULT_WINDOW);
     (*message_)[strings::msg_params][strings::window_id] = window_id;
     const auto window_hmi_level = app->hmi_level(window_id);
-    if ((mobile_api::HMILevel::HMI_FULL != window_hmi_level) &&
-        (mobile_api::HMILevel::HMI_LIMITED != window_hmi_level)) {
+    if ((mobile_api::HMILevel::HMI_NONE == window_hmi_level)) {
       LOG4CXX_WARN(logger_,
                    "CUSTOM_BUTTON OnButtonPress notification is allowed only "
-                       << "in FULL or LIMITED hmi level");
+                       << "in FULL, LIMITED or BACKGROUND hmi level");
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/on_button_press_notification.cc]: lets change this log to match the condition:
`CUSTOM_BUTTON OnButtonPress notification is not allowed in NONE hmi level`

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/on_button_event_notification.cc (hunk 1 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/on_button_event_notification.cc]: @iCollin Changed in 5fd52473d47b5daa24949289dbad798e88ad943b

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/on_button_press_notification.cc (hunk 2 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/on_button_press_notification.cc]: @iCollin Changed in 5fd52473d47b5daa24949289dbad798e88ad943b

**Comment by IGapchuk** [comment]
@iCollin All comments have been processed.
Please, keep in mind that `--fixup` commit should be squashed before merge.
