### PR TITLE
Fix processing of VR only Perform Interaction response

### LINKED ISSUE #2830: SDL sends unsucces general PerformIntereaction response to mobile app in case choiceID was selected via VR
### Bug Report
SDL sends unsucces general PerformIntereaction response to mobile app in case choiceID was selected

##### Reproduction Steps
1. App is registered and activated
2. ChoiceSet is added
3. Mobile app requests PerformIntereaction(BOTH, VR_ONLY)
4. Make choice( in case BOTH only VR choice )

##### Expected Behavior
SDL receives successful VR.PI with choiceID value and sends UI.ClosePopUp to UI.PI, HMI responds with unsuccessful UI.PI, then SDL sends successful response with choiceID to mobile app. 

##### Observed Behavior
SDL responds with unsuccessful result code and without choiceId to mobile app and does not send UI.ClosePopUp to HMI

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/d5649c98c74b5cf6ce812157037e46f824c746c8
* Testing Against: HMI https://github.com/smartdevicelink/sdl_hmi/commit/7962e1e858ca2c672fd53b1a1cd4ab08f59e4a32
Log: 
[SmartDeviceLinkCore.log.tar.gz](https://github.ford.com/SmartDeviceLinkMirror/sdl_core/files/6026/SmartDeviceLinkCore.log.tar.gz)

##### Diagrams
VR_ONLY mode:
image
BOTH mode:
image
ClosePopUp 
closepopup

### PR DESCRIPTION
**Pull request by YarikMamykin**
Fixes #2830 #3112 #2990 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
ATF test script attached to https://github.com/smartdevicelink/sdl_core/issues/2830

### Summary
In case of successful VR.PerformInteraction response from HMI with choiceID present in response
SDL doesn't send UI_ClosePopUp request to HMI if VR.PerformInteraction response came before UI.PerformInteraction response. More than that, SDL doesn't send successful response to mobile with choiceID.
Another problem is next: in case of `InteractionMode::BOTH` mobile app doesn't receive successful response from SDL in case HMI responsed SUCCESS to UI or VR PerformInteraction. More over, SDL doesn't provide info message of unsuccessful (UI or VR PerformInteraction) response.

Next changes were added in this PR:
1. Added sending of UI_ClosePopUp request to HMI after VR.PerformInteraction response.
2. Added sending response with choiceID to mobile in case of successful VR.PerformInteraction response.
3. Added info message from unsuccessful (UI or VR PerformInteraction) response in `InteractionMode::BOTH` to response from SDL to MobileApp.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 1]
```diff
@@ -346,6 +347,17 @@ bool PerformInteractionRequest::ProcessVRResponse(
     return false;
   }
 
+  if ((InteractionMode::VR_ONLY == interaction_mode_ ||
+       InteractionMode::BOTH == interaction_mode_) &&
+      vr_result_code_ == Common_Result::SUCCESS) {
```
Comment (IGapchuk) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @YarikMamykin I believe you could make two separate Boolean variables and compare them. For example:
```
bool is_mode_to_close = (InteractionMode::VR_ONLY == interaction_mode_) || (InteractionMode::BOTH == interaction_mode_);
bool success_result = vr_result_code_ == Common_Result::SUCCESS;
if(is_mode_to_close && success_result)
{...}
```

**Comment by IGapchuk** [comment]
@YarikMamykin Also, I think will be better to add several UT cases that will cover the changes.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 2]
```diff
@@ -256,6 +256,7 @@ void PerformInteractionRequest::on_event(const event_engine::Event& event) {
       vr_result_code_ = static_cast<hmi_apis::Common_Result::eType>(
           message[strings::params][hmi_response::code].asUInt());
       GetInfo(message, vr_info_);
+
```
[the remark this answers is not in the document]
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @IGapchuk , fixed in a950e20d2a5000fda5b013f4bbf0193082630642

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc (hunk 1 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @IGapchuk , fixed in a950e20

**Comment by YarikMamykin** [comment]
@IGapchuk , new UT added in 9a3b657d1947f4c1ce4cea2f6641cf5de8870f8c

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h [hunk 3]
```diff
@@ -53,6 +53,10 @@ namespace commands {
 class PerformInteractionRequest
     : public app_mngr::commands::CommandRequestImpl {
  public:
+  /**
+   * @brief Enum, defines which PerformInteraction response came first
+   */
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h]: @YarikMamykin Can you add brief info why do we need it ?

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h [hunk 4]
```diff
@@ -93,6 +97,32 @@ class PerformInteractionRequest
...
 
+  /**
+   * @brief Prepare result code for sending to mobile application
+   * @param first contains result_code from HMI response and
+   * interface that returns response
+   * @param second contains result_code from HMI response and
+   * interface that returns response.
+   * @return resulting code for sending to mobile application.
+   */
+  virtual mobile_apis::Result::eType PrepareResultCodeForResponse(
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h]: @YarikMamykin Are you sure that it should be `virtual`?

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h [hunk 5]
```diff
@@ -53,6 +53,10 @@ namespace commands {
 class PerformInteractionRequest
     : public app_mngr::commands::CommandRequestImpl {
  public:
+  /**
+   * @brief Enum, defines which PerformInteraction response came first
+   */
+  enum class FirstPerformInteractionResponser { NONE, UI, VR };
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h]: @YarikMamykin `FirstAnsweredInterface`? May be a bit more clear? What do you think?

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 6]
```diff
@@ -269,7 +278,16 @@ void PerformInteractionRequest::on_event(const event_engine::Event& event) {
 
   if (!HasHMIResponsesToWait()) {
     LOG4CXX_DEBUG(logger_, "Send response in BOTH iteraction mode");
-    SendBothModeResponse(msg_param);
+    const bool do_send_vr_params_only =
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @YarikMamykin rename please `do_send_vr_params_only` -> `send_vr_params_only`

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 7]
```diff
@@ -346,6 +364,17 @@ bool PerformInteractionRequest::ProcessVRResponse(
...
 
+  if (first_responser_ == FirstPerformInteractionResponser::VR) {
+    // After VR.PerformInteraction response HMI should close UI popup window
+    // if UI.PerformInteraction response comes
+    // after VR.PerformInteraction response.
+    // In this case SDL should send UI_ClosePopUp request.
+    smart_objects::SmartObject hmi_request_params =
+        smart_objects::SmartObject(smart_objects::SmartType_Map);
+    hmi_request_params[hmi_request::method_name] = "UI.PerformInteraction";
+    SendHMIRequest(hmi_apis::FunctionID::UI_ClosePopUp, &hmi_request_params);
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @YarikMamykin Do we need to send it independently from response (success or failure)?

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 8]
```diff
@@ -1063,13 +1092,70 @@ void PerformInteractionRequest::SendBothModeResponse(
...
                perform_interaction_result_code,
                info.empty() ? NULL : info.c_str(),
                response_params);
 }
 
+mobile_apis::Result::eType
+PerformInteractionRequest::PrepareResultCodeForResponse(
+    const app_mngr::commands::ResponseInfo& ui_response,
+    const app_mngr::commands::ResponseInfo& vr_response) {
+  if (interaction_mode_ == mobile_apis::InteractionMode::VR_ONLY) {
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @YarikMamykin swap comparables in such cases

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 9]
```diff
@@ -1063,13 +1092,70 @@ void PerformInteractionRequest::SendBothModeResponse(
...
+    if (first_responser_ == FirstPerformInteractionResponser::VR) {
+      return MessageHelper::HMIToMobileResult(vr_result_code_);
+    }
+  }
+
+  if (interaction_mode_ == mobile_apis::InteractionMode::BOTH) {
+    if (IsVRPerformInteractionResponseSuccessfulInBothMode()) {
+      return MessageHelper::HMIToMobileResult(vr_result_code_);
+    } else {
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @YarikMamykin `else` is redundant

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 10]
```diff
@@ -1063,13 +1092,70 @@ void PerformInteractionRequest::SendBothModeResponse(
...
+  return (vr_perform_info.is_ok && interaction_mode_ == InteractionMode::BOTH);
+}
+
+void PerformInteractionRequest::StoreFirstPerformInteractionResponser(
+    FirstPerformInteractionResponser responser) {
+  first_responser_ =
+      (first_responser_ == FirstPerformInteractionResponser::NONE)
+          ? responser
+          : first_responser_;
+}
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @YarikMamykin Why do you make it so complicated? 
Leave it like: 
```cpp
void PerformInteractionRequest::StoreFirstPerformInteractionResponser(
    FirstPerformInteractionResponser responser) {
  if (FirstPerformInteractionResponser::NONE == first_responser_ ) {
  	first_responser_ = responser;
  }
}
```

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 11]
```diff
@@ -346,6 +364,17 @@ bool PerformInteractionRequest::ProcessVRResponse(
...
   }
 
+  if (first_responser_ == FirstPerformInteractionResponser::VR) {
+    // After VR.PerformInteraction response HMI should close UI popup window
+    // if UI.PerformInteraction response comes
+    // after VR.PerformInteraction response.
+    // In this case SDL should send UI_ClosePopUp request.
+    smart_objects::SmartObject hmi_request_params =
+        smart_objects::SmartObject(smart_objects::SmartType_Map);
+    hmi_request_params[hmi_request::method_name] = "UI.PerformInteraction";
```
Comment (IGapchuk) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @YarikMamykin I think will be better to create const variable for the `UI.PerformInteraction` string.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h (hunk 5 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h]: @AByzhynar , I think it is better to keep `FirstPerformInteractionResponser`, because this enum is related only to VR/UI.PerformInteraction responses. In my opinion, `FirstAnsweredInterface` has more general meaning for this case.

Comment (AByzhynar) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h]: @YarikMamykin Name is more clear and it is more general but as you have defined it in PI only - it is still related to PT only. So I still suggest to make name more clear

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc (hunk 7 above)
Comment (AByzhynar) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @YarikMamykin In this case update PR description accordingly

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc (hunk 11 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @IGapchuk fixed in https://github.com/smartdevicelink/sdl_core/pull/3122/commits/0190836450ab1d7e130bbb8e32315eb3325a9a68

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc (hunk 10 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @AByzhynar fixed in https://github.com/smartdevicelink/sdl_core/pull/3122/commits/0190836450ab1d7e130bbb8e32315eb3325a9a68

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc (hunk 9 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @AByzhynar fixed in https://github.com/smartdevicelink/sdl_core/pull/3122/commits/0190836450ab1d7e130bbb8e32315eb3325a9a68

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc (hunk 8 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @AByzhynar fixed in https://github.com/smartdevicelink/sdl_core/pull/3122/commits/0190836450ab1d7e130bbb8e32315eb3325a9a68

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc (hunk 6 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @AByzhynar fixed in https://github.com/smartdevicelink/sdl_core/pull/3122/commits/0190836450ab1d7e130bbb8e32315eb3325a9a68

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h (hunk 5 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h]: @AByzhynar fixed in https://github.com/smartdevicelink/sdl_core/pull/3122/commits/0190836450ab1d7e130bbb8e32315eb3325a9a68

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h (hunk 4 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h]: @AByzhynar fixed in https://github.com/smartdevicelink/sdl_core/pull/3122/commits/0190836450ab1d7e130bbb8e32315eb3325a9a68

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h (hunk 3 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h]: @AByzhynar fixed in https://github.com/smartdevicelink/sdl_core/pull/3122/commits/0190836450ab1d7e130bbb8e32315eb3325a9a68

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 12]
```diff
@@ -269,7 +276,16 @@ void PerformInteractionRequest::on_event(const event_engine::Event& event) {
 
   if (!HasHMIResponsesToWait()) {
     LOG4CXX_DEBUG(logger_, "Send response in BOTH iteraction mode");
-    SendBothModeResponse(msg_param);
+    const bool send_vr_params_only =
+        (first_responser_ == FirstAnsweredInterface::VR &&
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @YarikMamykin Swap comparable. Everywhere

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 13]
```diff
@@ -346,6 +362,19 @@ bool PerformInteractionRequest::ProcessVRResponse(
     return false;
   }
 
+  if (FirstAnsweredInterface::VR == first_responser_) {
+    // After VR.PerformInteraction response HMI should close UI popup window
+    // if UI.PerformInteraction response comes
+    // after VR.PerformInteraction response.
+    // In this case SDL should send UI_ClosePopUp request.
+    const std::string kUIPerformInteractionMethodName = "UI.PerformInteraction";
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @YarikMamykin wrong name for `local` variable. Rename please to `method_name`

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 14]
```diff
@@ -1063,13 +1092,68 @@ void PerformInteractionRequest::SendBothModeResponse(
...
                response_params);
 }
 
+mobile_apis::Result::eType
+PerformInteractionRequest::PrepareResultCodeForResponse(
+    const app_mngr::commands::ResponseInfo& ui_response,
+    const app_mngr::commands::ResponseInfo& vr_response) {
+  if (mobile_apis::InteractionMode::VR_ONLY == interaction_mode_) {
+    if (FirstAnsweredInterface::VR == first_responser_) {
+      return MessageHelper::HMIToMobileResult(vr_result_code_);
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @YarikMamykin As in the method we have so many `if` statements - may be it is worth to add short logging to every `if`?

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc (hunk 12 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @AByzhynar fixed in https://github.com/smartdevicelink/sdl_core/pull/3122/commits/8b1b9a79752b6e208df76048cff2e8c307b71492

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc (hunk 13 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @AByzhynar fixed in https://github.com/smartdevicelink/sdl_core/pull/3122/commits/8b1b9a79752b6e208df76048cff2e8c307b71492

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h [hunk 15]
```diff
@@ -93,6 +101,32 @@ class PerformInteractionRequest
...
 
+  /**
+   * @brief Prepare result code for sending to mobile application
+   * @param first contains result_code from HMI response and
+   * interface that returns response
+   * @param second contains result_code from HMI response and
+   * interface that returns response.
+   * @return resulting code for sending to mobile application.
+   */
+  mobile_apis::Result::eType PrepareResultCodeForResponse(
```
Comment (mkorniichuk) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h]: @YarikMamykin please, consider moving this and the next method to the protected or private section.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h [hunk 16]
```diff
@@ -93,6 +101,32 @@ class PerformInteractionRequest
    */
   virtual void onTimeOut();
 
+  /**
+   * @brief Prepare result code for sending to mobile application
+   * @param first contains result_code from HMI response and
```
Comment (mkorniichuk) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h]: @YarikMamykin please, fix params names

Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h]: @mkorniichuk please see https://github.com/smartdevicelink/sdl_core/pull/3122/commits/a2ef4e914f015f799ba346ae8ce22bc2e10c1214

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h (hunk 15 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h]: @mkorniichuk please see a2ef4e9

**Comment by YarikMamykin** [comment]
@theresalech and @jordynmackool this PR passed internal Luxoft review and ready for Livio team review. Please, take a look.

**Comment by jordynmackool** [comment]
@YarikMamykin thanks, we will review and let you know if we have any questions.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 17]
```diff
@@ -1063,13 +1091,73 @@ void PerformInteractionRequest::SendBothModeResponse(
...
+
+bool PerformInteractionRequest::
+    IsVRPerformInteractionResponseSuccessfulInBothMode() {
+  using namespace mobile_apis;
+  app_mngr::commands::ResponseInfo vr_perform_info(
+      vr_result_code_, HmiInterfaces::HMI_INTERFACE_VR, application_manager_);
+  return (vr_perform_info.is_ok && InteractionMode::BOTH == interaction_mode_);
+}
+
+void PerformInteractionRequest::StoreFirstAnsweredInterface(
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: unnecessary function, please remove

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h [hunk 18]
```diff
@@ -241,6 +289,8 @@ class PerformInteractionRequest
   hmi_apis::Common_Result::eType ui_result_code_;
   std::string ui_info_;
   std::string vr_info_;
+  smart_objects::SmartObject vr_params_;
+  FirstAnsweredInterface first_responser_;
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h]: `responser` -> `responder` everywhere :)

Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h]: @iCollin Renamed in f35543c901a896b89a2206e4bd57b6b213a7c5aa

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc (hunk 17 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @iCollin We need this function to save the first answered interface and use the saved value for the case when the current interaction mode is `InteractionMode::VR_ONLY` and SDL received the `VR_PerformInteraction` response. In this case, SDL Core should send the `UI_ClosePopUp` request to the HMI to close the UI menu.

**Comment by iCollin** [comment]
> @iCollin Regarding the case that you've described above ([#3122 (review)](https://github.com/smartdevicelink/sdl_core/pull/3122#pullrequestreview-340657457)):
> I believe, this SDL's behavior isn't applicable.
> According to the HMI integration guidelines, HMI should send the `VR_PerformInteraction` as the first response. You can find that in the diagrams: https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/blob/master/docs/VR/PerformInteraction/index.md.

@IGapchuk In that case, yes, the VR response does come in first, but the diagram just shows one possible interaction. The code within SDL Core does not require one interface's response before the other, and it should work properly regardless of which response arrives first.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc (hunk 17 above)
Comment (iCollin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @IGapchuk sorry, I should have explained more. It is a useful function, but since it will only ever be used in two specific places it actually takes more code to define the function than to just write the function body inline.

**Comment by YarikMamykin** [comment]
> @IGapchuk In that case, yes, the VR response does come in first, but the diagram just shows one possible interaction. The code within SDL Core does not require one interface's response before the other, and it should work properly regardless of which response arrives first.
>
@iCollin this point makes sense. Please take a look at latest changes :)

**Comment by YarikMamykin** [comment]
Hello @iCollin, thank you for tips about simplification of current solution. It looks better now :)
Please check https://github.com/smartdevicelink/sdl_core/pull/3122/commits/83329fd8dd891f14ee557ae41d8726f48741bcf8

I managed to remove `vr_params_`, but we still need `first_responder_` for next 2 reasons:
1. In case when VR response came before UI we need to tell HMI to close PopUp window with `UI_ClosePopUp` request.
2. Without knowing who was first responder in BOTH mode and in case we got choiceID from VR **and** from UI we will always overwrite choiceID with last-comming value. 

About failing test scripts: those 2 scripts you mentioned are updated. Appropriate PR is created here https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2319

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 19]
```diff
@@ -430,11 +466,14 @@ void PerformInteractionRequest::ProcessUIResponse(
 
     // result code must be GENERIC_ERROR in case wrong choice_id
     if (msg_params.keyExists(strings::choice_id)) {
-      if (!CheckChoiceIDFromResponse(app,
-                                     msg_params[strings::choice_id].asInt())) {
+      const std::int32_t ui_choise_id =
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: `choise` -> `choice`

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 20]
```diff
@@ -1127,43 +1117,58 @@ mobile_apis::Result::eType
...
-                                     << static_cast<int32_t>(first_responder_));
-
-  if (mobile_apis::InteractionMode::VR_ONLY == interaction_mode_) {
-    if (FirstAnsweredInterface::VR == first_responder_) {
-      return MessageHelper::HMIToMobileResult(vr_result_code_);
+  LOG4CXX_DEBUG(
+      logger_, "InteractionMode = " << static_cast<int32_t>(interaction_mode_));
+
+  auto result = mobile_api::Result::INVALID_ENUM;
+  switch (interaction_mode_) {
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: I think a switch statement makes this more difficult to read, if blocks with a return in them are easier to follow

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 21]
```diff
@@ -1127,43 +1117,58 @@ mobile_apis::Result::eType
...
     app_mngr::commands::ResponseInfo& vr_response) const {
-  if (mobile_apis::InteractionMode::VR_ONLY == interaction_mode_) {
-    if (FirstAnsweredInterface::VR == first_responder_) {
-      return vr_response.is_ok;
-    }
-  }
-
-  if (mobile_apis::InteractionMode::BOTH == interaction_mode_) {
-    return (vr_response.is_ok || ui_response.is_ok);
+  bool result = false;
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: again i think a switch is too verbose, especially since there is no default case

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 22]
```diff
@@ -1063,13 +1104,111 @@ void PerformInteractionRequest::SendBothModeResponse(
...
+  app_mngr::commands::ResponseInfo vr_perform_info(
+      vr_result_code_, HmiInterfaces::HMI_INTERFACE_VR, application_manager_);
+  return (vr_perform_info.is_ok && InteractionMode::BOTH == interaction_mode_);
+}
+
+void PerformInteractionRequest::SetChoiceIdToResponseMsgParams(
+    ns_smart_device_link::ns_smart_objects::SmartObject& msg_param) {
+  LOG4CXX_AUTO_TRACE(logger_);
+
+  std::int32_t choice_id = INVALID_CHOICE_ID;
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: this variable is unnecessary, you can set the choice id right on the smart object

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 23]
```diff
@@ -1063,13 +1104,111 @@ void PerformInteractionRequest::SendBothModeResponse(
...
+    case mobile_apis::InteractionMode::eType::MANUAL_ONLY: {
+      choice_id = ui_choice_id_received_;
+      break;
+    }
+    case mobile_apis::InteractionMode::eType::VR_ONLY: {
+      choice_id = vr_choice_id_received_;
+      break;
+    }
+    case mobile_apis::InteractionMode::eType::BOTH: {
+      choice_id = (first_responder_ == FirstAnsweredInterface::UI) &&
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: core receiving two valid choice ids is currently undefined behavior. (as far as I could find from documentation)

after speaking with a few engineers, we agree that if we have two valid and DIFFERENT choice ids, PerformInteraction should return an error. This will require an additional case at the top of SendBothModeResponse.
Then at this point, you can return either valid choice ID.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 24]
```diff
@@ -346,6 +370,18 @@ bool PerformInteractionRequest::ProcessVRResponse(
     return false;
   }
 
+  if (FirstAnsweredInterface::VR == first_responder_) {
+    // After VR.PerformInteraction response HMI should close UI popup window
+    // if UI.PerformInteraction response comes
+    // after VR.PerformInteraction response.
+    // In this case SDL should send UI_ClosePopUp request.
+    const std::string method_name = "UI.PerformInteraction";
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: to avoid code duplication, please add this to a function or repurpose and rename `TerminatePerformInteraction`.

If you create a new function for this, please remove `TerminatePerformInteraction` since it will then be useless.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 25]
```diff
@@ -1063,13 +1104,111 @@ void PerformInteractionRequest::SendBothModeResponse(
...
+  return (vr_perform_info.is_ok && InteractionMode::BOTH == interaction_mode_);
+}
+
+void PerformInteractionRequest::SetChoiceIdToResponseMsgParams(
+    ns_smart_device_link::ns_smart_objects::SmartObject& msg_param) {
+  LOG4CXX_AUTO_TRACE(logger_);
+
+  std::int32_t choice_id = INVALID_CHOICE_ID;
+
+  switch (interaction_mode_) {
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: again I think a switch is not appropriate here, if else will be easier to follow.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 26]
```diff
@@ -1063,13 +1104,111 @@ void PerformInteractionRequest::SendBothModeResponse(
...
+      break;
+    }
+
+    case mobile_apis::InteractionMode::MANUAL_ONLY: {
+      result = MessageHelper::HMIToMobileResult(ui_result_code_);
+      break;
+    }
+
+    case mobile_apis::InteractionMode::BOTH: {
+      if (IsVRPerformInteractionResponseSuccessfulInBothMode()) {
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: VR shouldn't take precedent here. This condition should just be dependent on which response included a valid choice_id.

```
if VR response had valid choice_id:
    return vr_code
else if UI response had valid choice_id:
    return ui_code
else
    return CommandRequestImpl::Prepare(ui, vr)
```

`IsVRPerformInteractionResponseSuccessfulInBothMode()` can be removed.

**Comment by YarikMamykin** [comment]
Hello @iCollin , I updated SDL core accordingly to your comments. Please take a look at latest changes.

In addition, I have only one remark regarding `TerminatePerformInteraction` method. As soon this method not only sends ClosePopup request to HMI but also disables PerformInteraction for particular app I have doubts about deleting it. But the idea of creating of separate method for ClosePopup request sounds good. You can find new `SendClosePopupRequestToHMI` method in PerformInteractionRequest class.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/perform_interaction_test.cc [hunk 27]
```diff
@@ -70,35 +70,109 @@ namespace strings = ::application_manager::strings;
...
+  }
+
+  MessageSharedPtr CreateHMIResponseMessage(
+      const hmi_apis::Common_Result::eType& response_code,
+      const std::string& message_info,
+      const int32_t command_id = kCommandId) {
+    MessageSharedPtr response_msg = CreateMessage(smart_objects::SmartType_Map);
+    (*response_msg)[strings::params][hmi_response::code] = response_code;
+    (*response_msg)[strings::msg_params][strings::cmd_id] = command_id;
+    (*response_msg)[am::strings::msg_params][am::strings::info] = message_info;
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/perform_interaction_test.cc]: Why mix `am::strings` and `strings::`? I know old code uses `am::` but please use `strings::` in your new code.

Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/perform_interaction_test.cc]: @iCollin fixed in https://github.com/smartdevicelink/sdl_core/pull/3122/commits/8e788552cae05a5fad4291e0fd234291f7d2e390

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 28]
```diff
@@ -1136,35 +1143,38 @@ bool PerformInteractionRequest::PrepareResultForMobileResponse(
...
 }
 
-void PerformInteractionRequest::SetChoiceIdToResponseMsgParams(
-    ns_smart_device_link::ns_smart_objects::SmartObject& msg_param) {
+bool PerformInteractionRequest::SetChoiceIdToResponseMsgParams(
+    ns_smart_device_link::ns_smart_objects::SmartObject& msg_param) const {
   LOG4CXX_AUTO_TRACE(logger_);
 
-  msg_param[strings::choice_id] = INVALID_CHOICE_ID;
+  const bool ui_choice_id_valid = INVALID_CHOICE_ID != ui_choice_id_received_;
```
[the remark this answers is not in the document]
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @iCollin fixed in https://github.com/smartdevicelink/sdl_core/pull/3122/commits/9d5a9d91c1c7f29bb83ed46718984986d0ba9c8c

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 29]
```diff
@@ -1136,35 +1143,38 @@ bool PerformInteractionRequest::PrepareResultForMobileResponse(
   if (mobile_apis::InteractionMode::MANUAL_ONLY == interaction_mode_) {
     return ui_response.is_ok;
   }
-  if (mobile_apis::InteractionMode::BOTH == interaction_mode_) {
-    return (vr_response.is_ok || ui_response.is_ok);
-  }
 
-  return CommandRequestImpl::PrepareResultForMobileResponse(ui_response,
-                                                            vr_response);
+  // BOTH mode
```
[the remark this answers is not in the document]
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @iCollin fixed in 9d5a9d9

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 30]
```diff
@@ -1114,17 +1121,17 @@ PerformInteractionRequest::PrepareResultCodeForResponse(
...
   }
-  if (mobile_apis::InteractionMode::BOTH == interaction_mode_) {
-    if (INVALID_CHOICE_ID != vr_choice_id_received_) {
-      return MessageHelper::HMIToMobileResult(vr_result_code_);
-    }
-    if (INVALID_CHOICE_ID != ui_choice_id_received_) {
-      return MessageHelper::HMIToMobileResult(ui_result_code_);
-    }
+
+  // BOTH mode
```
[the remark this answers is not in the document]
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @iCollin fixed in 9d5a9d9

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 31]
```diff
@@ -358,7 +364,8 @@ bool PerformInteractionRequest::ProcessVRResponse(
     return false;
   }
 
-  if (!ui_response_received_) {
+  if (!ui_response_received_ &&
+      InteractionMode::MANUAL_ONLY != interaction_mode_) {
     // After VR.PerformInteraction response HMI should close UI popup window
```
[the remark this answers is not in the document]
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @iCollin fixed in 9d5a9d9

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h [hunk 32]
```diff
@@ -232,7 +259,25 @@ class PerformInteractionRequest
...
+  void SendClosePopupRequestToHMI();
+
+  /**
+   * @brief Sets the choice according to the current interaction mode and first
+   * received choice id (UI or VR).
+   *
+   * @param msg_param Message parameters which will be included in the response
+   * to mobile device.
+   */
+  bool SetChoiceIdToResponseMsgParams(
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h]: We should add @return documentation here

Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/perform_interaction_request.h]: @iCollin added in https://github.com/smartdevicelink/sdl_core/pull/3122/commits/5e77a65c1a12eff7d2aef300861d5936fba60fc9

**Comment by YarikMamykin** [comment]
@iCollin , thank you for your help and patch file, I applied it in https://github.com/smartdevicelink/sdl_core/pull/3122/commits/00cb6d046f3b0980fc91e09e655bdfd4594e59c3

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/perform_interaction_test.cc [hunk 33]
```diff
@@ -518,6 +518,150 @@ TEST_F(
...
+
+  ASSERT_TRUE(command->Init());
+
+  MessageSharedPtr response_msg_vr = CreateHMIResponseMessage(
+      hmi_apis::Common_Result::UNSUPPORTED_RESOURCE, "VR error message");
+  am::event_engine::Event event_vr(hmi_apis::FunctionID::VR_PerformInteraction);
+  event_vr.set_smart_object(*response_msg_vr);
+
+  MessageSharedPtr response_msg_ui =
+      CreateHMIResponseMessage(hmi_apis::Common_Result::WARNINGS, "");
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/perform_interaction_test.cc]: suggestion: maybe we could add some info here and in the result?

Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/perform_interaction_test.cc]: @iCollin applied in https://github.com/smartdevicelink/sdl_core/pull/3122/commits/326effbbd94168eeecd83624c060deb8a5e11493

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc [hunk 34]
```diff
@@ -1111,18 +1111,41 @@ PerformInteractionRequest::PrepareResultCodeForResponse(
...
+    bool ui_warnings =
+        mobile_apis::Result::eType::WARNINGS == mobile_ui_result_code;
+
+    bool is_vr_success_and_ui_warnings = vr_success && ui_warnings;
+    bool is_ui_success_and_vr_warnings = ui_success && vr_warnings;
+
+    if (is_vr_success_and_ui_warnings || is_ui_success_and_vr_warnings) {
+      return mobile_apis::Result::eType::WARNINGS;
+    }
+  }
```
[the remark this answers is not in the document]
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc]: @iCollin optimized in https://github.com/smartdevicelink/sdl_core/pull/3122/commits/5c55a76756eb28d4f45f2fc9376e0b2d839a501c
