### PR TITLE
Fix PerformInteractionChoiceSet request behavior

### LINKED ISSUE #1883: ChoiceSet being processed in DeleteInteractionChoceSet
**Occurrence: Always** 

# Description
ChoiceSet being processed in DeleteInteractionChoceSet

## Preconditions
 - SDL and HMI are started.
 - App is registered and activated.

## Steps to reproduce
1.  HMI processes VR.DeleteCommands_request related to choiceSetID_1 AND app sends PerformInteractionChoiceSet with choiceSetID_1 

## Actual result
SDL responds INVALID_ID (success:false) to this PerfromInteraction

## Expected result
 SDL must respond REJECTED (success:false) to this PerfromInteraction

# Environment

# Attachments

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [x] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

### PR DESCRIPTION
**Pull request by ychernysheva**
Fixes #1883

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Covered by ATF test scripts, the new unit test is also added

### Summary
There is a case when DeleteInteractionChoiceSet request is sent to HMI, and SDL is waiting for response. If during this waiting period PerformInteractionChoiceSet request is sent, according to requirements SDL should reject such request.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by ychernysheva** [comment]
@theresalech this PR is ready for Livio review

File: src/components/application_manager/src/application_data_impl.cc [hunk 1]
```diff
@@ -926,20 +926,40 @@ void DynamicApplicationDataImpl::RemoveWindowInfo(const WindowID window_id) {
...
+  }
+  {
+    sync_primitives::AutoLock allowed_choice_sets_lock(
+        allowed_choice_sets_lock_);
+    auto choise_id_it = allowed_choice_sets_.find(choice_set_id);
+    if (allowed_choice_sets_.end() == choise_id_it) {
+      SDL_LOG_WARN("Choice set with id " << choice_set_id << " is not found");
+      return;
+    }
+    allowed_choice_sets_.erase(choise_id_it);
```
Comment (iCollin) [inline src/components/application_manager/src/application_data_impl.cc:962]:
```suggestion
    auto choice_id_it = allowed_choice_sets_.find(choice_set_id);
    if (allowed_choice_sets_.end() == choice_id_it) {
      SDL_LOG_WARN("Choice set with id " << choice_set_id << " is not found");
      return;
    }
    allowed_choice_sets_.erase(choice_id_it);
```

choise -> choice

**Review by iCollin — APPROVED** [review]
