### PR TITLE
Fix starting behavior of secured services for navi/non-navi applications

### LINKED ISSUE #1924: SDL must start PTU for any app except navi right after app successfully request to start first secure service
**Occurrence: Always** 

## Steps to reproduce
1. Make sure SDL is built with default flags
2. Start SDL and HMI
3. Connect mobile device
4. Register non-navi mobile application
5. PTU for new application without certificate is performed
6. Start secure RPC(7) service 

## Actual result
SDL does not start PTU after starting secure service.

## Expected result
1. SDL starts PolicyTableUpdate process on sending SDL.OnStatusUpdate(UPDATE_NEEDED) to HMI to get "certificate" right after application successfully requests to start first secure service.
2. SDL does not respond to StartService_request from mobile application till PTU is not finished.

## Test scripts
[1924_1_non-navi.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1924_1_non-navi.lua)
[1924_2_navi.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1924_2_navi.lua)

## Attachments

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [x] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

### LINKED ISSUE #1925: SDL must start PTU for navi app right after app successfully registration
**Occurrence: Always** 

## Steps to reproduce
1. Make sure SDL is built with default flags
2. Start SDL and HMI
3. Connect mobile device
4. Register non-navi mobile application
5. PTU for registered application without certificate and with navi application in PT is performed
6. Register navi application

## Expected result
SDL starts PolicyTableUpdate process on sending SDL.OnStatusUpdate(UPDATE_NEEDED) to HMI to get "certificate" after app successfully registration.

## Actual result
SDL does not start PolicyTableUpdate process.

## Test scripts
[1925_1_navi_no_cert_new_app.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1925_1_navi_no_cert_new_app.lua)
[1925_2_navi_no_cert_existing_app.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1925_2_navi_no_cert_existing_app.lua)
[1925_3_navi_cert_new_app.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1925_3_navi_cert_new_app.lua)
[1925_4_navi_cert_existing_app.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1925_4_navi_cert_existing_app.lua)
[1925_5_non-navi_no_cert_new_app.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1925_5_non-navi_no_cert_new_app.lua)
[1925_6_non-navi_no_cert_existing_app.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1925_6_non-navi_no_cert_existing_app.lua)
[1925_7_non-navi_cert_new_app.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1925_7_non-navi_cert_new_app.lua)
[1925_8_non-navi_cert_existing_app.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1925_8_non-navi_cert_existing_app.lua)

## Attachments

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [x] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #1925, #1924, #1923, #1922, #1912, #1894, #1891, #1888

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
Existing unit tests will be updated according to new logic and new unit tests will be provided.

### Summary
There was a wrong logic around processing of `ForceProtectedService` and `ForceUnprotectedService`
params from ini file and sending start service ACK/NACK for secured services. All these test cases could be covered with one pull request. Also there was a wrong logic for triggering PTU when no certificate in local PT and non-navi application is going to start secured service.

### Changelog
- `ServiceStartedContext` were moved to session observer 
`ServiceStartedContext` were moved to session observer and renamed to `StartingSessionContext`. Also new fields were added: `is_new_service` - to check later is this a new service for this session, `is_ptu_required` - to check later is session from this context requires triggering of PTU in case there is no certificate data in local PT
- Old `StartSessionHandler` class moved to a separate unit
Old `StartSessionHandler` class moved to a separate unit and renamed to `HandshakeHandler` according to its logic. Also this class was updated to use `StartingSessionContext` and was updated `OnHandshakeDone` logic according to requirements
- Refactoring in connection/protocol handlers
`NotifySessionStartedResult` function were updated to use `StartingSessionContext` class for accessing to needed data instead of tones of separate parameters. Old implementation were marked as deprecated. Also in protocol handler some raw pointer data were replaced with smart objects.
- Fixes in Crypto/Security managers
There was added `InitCertExpTime` function in crypto manager to set certificate expired data to some initial value because in case of no certificate it will not be inited and contain invalid data. Also in this case `IsCertificateUpdateRequired` sometimes returns wrong result because of not inited certificate
data. In crypto manager were added/updated debug logs for better understanding of it initialization process.
Also added function `IsPolicyCertificateDataEmpty` function for getting information regarding policy certificate presence.
- `ProtocolHandlerImpl` was extended with `PolicyHandlerObserver` logic
`ProtocolHandlerImpl` was extended with `PolicyHandlerObserver` logic and added function with related implementation. Also was updated logic of `NotifySessionStartedResult` with case when PTU should be triggered.
- Updates in connection and handler
Connection and its handler were extended with function `IsSessionServiceExists` to check is specified service exists in session. This function is needed for `ProtocolHandler`. Also there was added check for session protocol version when starting a new service.

### Tasks Remaining:
- [x] Fix failed unit tests
- [x] Provide new unit tests

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/connection_handler/src/connection_handler_impl.cc [hunk 1]
```diff
@@ -363,38 +363,41 @@ void ConnectionHandlerImpl::OnSessionStartedCallback(
     const BsonObject* params) {
   LOG4CXX_AUTO_TRACE(logger_);
 
-  uint32_t new_session_id = 0;
-  uint32_t hash_id = protocol_handler::HASH_ID_WRONG;
+  std::vector<std::string> empty;
```
Comment (LuxoftAKutsan) [inline src/components/connection_handler/src/connection_handler_impl.cc]: @AKalinich-Luxoft please specify what is in this vector.

File: src/components/connection_handler/src/connection_handler_impl.cc [hunk 2]
```diff
@@ -404,22 +407,24 @@ void ConnectionHandlerImpl::OnSessionStartedCallback(
...
   }
   sync_primitives::AutoReadLock read_lock(connection_handler_observer_lock_);
   if (connection_handler_observer_) {
-    const uint32_t session_key = KeyFromPair(connection_handle, new_session_id);
+    const uint32_t session_key =
+        KeyFromPair(connection_handle, context.new_session_id_);
+
+    uint32_t app_id = 0;
+    GetDataOnSessionKey(session_key, &app_id, NULL, NULL);
+    if (app_id) {
```
Comment (LuxoftAKutsan) [inline src/components/connection_handler/src/connection_handler_impl.cc]: @AKalinich-Luxoft avoid implicit casting int to bool

File: src/components/include/protocol_handler/session_observer.h [hunk 3]
```diff
@@ -54,6 +54,58 @@ namespace protocol_handler {
...
+  protocol_handler::ServiceType service_type_;
+  uint32_t hash_id_;
+  bool is_protected_;
+  bool is_new_service_;
+  bool is_ptu_required_;
+
+  /**
+   * @brief Constructor
+   */
+  StartingSessionContext()
```
Comment (LuxoftAKutsan) [inline src/components/include/protocol_handler/session_observer.h]: @AKalinich-Luxoft do we need empty constructor?

File: src/components/protocol_handler/include/protocol_handler/handshake_handler.h [hunk 4]
```diff
@@ -0,0 +1,129 @@
...
+
+class ProtocolHandlerImpl;
+
+/**
+ * \brief HandshakeHandler class for handling SSL handshake and sending
+ * Ack/Nack on its success or fail
+ */
+class HandshakeHandler : public security_manager::SecurityManagerListener {
+ public:
+  // DEPRECATED
```
Comment (LuxoftAKutsan) [inline src/components/protocol_handler/include/protocol_handler/handshake_handler.h]: @AKalinich-Luxoft please use DEPRECATED macro

File: src/components/protocol_handler/src/handshake_handler.cc [hunk 5]
```diff
@@ -0,0 +1,197 @@
...
+    std::shared_ptr<uint8_t> payload)
+    : protocol_handler_(protocol_handler)
+    , session_observer_(session_observer)
+    , context_(context)
+    , full_version_(full_version)
+    , protocol_version_(protocol_version)
+    , payload_(payload) {}
+
+HandshakeHandler::~HandshakeHandler() {
+  LOG4CXX_DEBUG(logger_, "Destroying StartSessionHandler: " << this);
```
Comment (LuxoftAKutsan) [inline src/components/protocol_handler/src/handshake_handler.cc]: @AKalinich-Luxoft is it correct name of class?

File: src/components/security_manager/src/security_manager_impl.cc [hunk 6]
```diff
@@ -236,13 +240,15 @@ void SecurityManagerImpl::RemoveListener(
...
+
 void SecurityManagerImpl::NotifyListenersOnHandshakeDone(
     const uint32_t& connection_key, SSLContext::HandshakeResult error) {
   LOG4CXX_AUTO_TRACE(logger_);
   std::list<SecurityManagerListener*>::iterator it = listeners_.begin();
   while (it != listeners_.end()) {
     if ((*it)->OnHandshakeDone(connection_key, error)) {
-      // On get notification remove listener
+      LOG4CXX_DEBUG(logger_, "Destroying listener: " << *it);
+      delete (*it);
```
Comment (LuxoftAKutsan) [inline src/components/security_manager/src/security_manager_impl.cc]: @AKalinich-Luxoft why we destroy listeners?

File: src/components/application_manager/include/application_manager/application_manager_impl.h [hunk 7]
```diff
@@ -853,15 +853,43 @@ class ApplicationManagerImpl
       const connection_handler::CloseSessionReason& close_reason) OVERRIDE;
 
 #ifdef ENABLE_SECURITY
-  // Overriden SecurityManagerListener method
+  /**
+   * @brief Notification about protection result
+   * @param connection_key Unique key of session which triggrs handshake
```
Comment (AByzhynar) [inline src/components/application_manager/include/application_manager/application_manager_impl.h]: @AKalinich-Luxoft typo

File: src/components/application_manager/src/application_manager_impl.cc [hunk 8]
```diff
@@ -1514,6 +1514,12 @@ void ApplicationManagerImpl::OnCertificateUpdateRequired() {
   GetPolicyHandler().OnPTExchangeNeeded();
 }
 
+bool ApplicationManagerImpl::GetPolicyCertificateData(std::string& data) {
+  LOG4CXX_AUTO_TRACE(logger_);
+  data = GetPolicyHandler().RetrieveCertificate();
+  return true;
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_manager_impl.cc]: @AKalinich-Luxoft Why do we need to return always `true` ?

File: src/components/connection_handler/src/connection.cc [hunk 9]
```diff
@@ -294,6 +313,23 @@ void Connection::SetProtectionFlag(
     service_rpc->is_protected_ = true;
   }
 }
+
+bool Connection::IsSessionServiceExists(
```
Comment (AByzhynar) [inline src/components/connection_handler/src/connection.cc]: @AKalinich-Luxoft `Is...exists` - this is wrong. `Does exist` - this one is correct. Or `SessionServiceExists` at least

File: src/components/include/security_manager/security_manager.h [hunk 10]
```diff
@@ -127,6 +127,24 @@ class SecurityManager : public protocol_handler::ProtocolObserver {
...
+   * @brief Check whether certificate should be updated
+   * @return true if certificate should be updated otherwise false
+   */
+  virtual bool IsCertificateUpdateRequired() = 0;
+
+  /**
+   * @brief Notify all listeners that certificate update required
+   * Allows to notify that certificate should be updated
+   */
+  virtual void NotifyOnCertififcateUpdateRequired() = 0;
```
Comment (AByzhynar) [inline src/components/include/security_manager/security_manager.h]: @AKalinich-Luxoft Typo

File: src/components/protocol_handler/include/protocol_handler/handshake_handler.h [hunk 11]
```diff
@@ -0,0 +1,129 @@
...
+#include "protocol_handler/protocol_packet.h"
+#include "protocol_handler/session_observer.h"
+#include "security_manager/security_manager_listener.h"
+
+namespace protocol_handler {
+
+class ProtocolHandlerImpl;
+
+/**
+ * \brief HandshakeHandler class for handling SSL handshake and sending
```
Comment (AByzhynar) [inline src/components/protocol_handler/include/protocol_handler/handshake_handler.h]: @AKalinich-Luxoft should be `@` insted of `\`

File: src/components/protocol_handler/src/handshake_handler.cc [hunk 12]
```diff
@@ -0,0 +1,197 @@
...
+
+void HandshakeHandler::OnCertificateUpdateRequired() {}
+
+bool HandshakeHandler::OnHandshakeDone(
+    uint32_t connection_key,
+    security_manager::SSLContext::HandshakeResult result) {
+  LOG4CXX_AUTO_TRACE(logger_);
+
+  if (connection_key != this->connection_key()) {
+    LOG4CXX_DEBUG(logger_, "Notification not for handler " << this);
```
Comment (AByzhynar) [inline src/components/protocol_handler/src/handshake_handler.cc]: @AKalinich-Luxoft As for me - this log message is a bit strange....

File: src/components/protocol_handler/src/handshake_handler.cc [hunk 13]
```diff
@@ -0,0 +1,197 @@
...
+  }
+
+  if (success) {
+    ProcessSuccessfulHandshake(connection_key, params);
+  } else {
+    ProcessFailedHandshake(params);
+  }
+
+  bson_object_deinitialize(&params);
+  return true;
```
Comment (AByzhynar) [inline src/components/protocol_handler/src/handshake_handler.cc]: @AKalinich-Luxoft Do we need to return always ` true` ? Is it really necessary?

File: src/components/include/protocol_handler/session_observer.h (hunk 3 above)
Comment (AKalinich-Luxoft) [reply src/components/include/protocol_handler/session_observer.h]: @LuxoftAKutsan yes. Default constructed context is used in NotifyServiceStartedResult() for delayed initialization and also required in HandshakeHandler class in deprecated constructor as there is no actual context passed.

File: src/components/protocol_handler/include/protocol_handler/handshake_handler.h (hunk 4 above)
Comment (AKalinich-Luxoft) [reply src/components/protocol_handler/include/protocol_handler/handshake_handler.h]: @LuxoftAKutsan pull request  #1938 with macro is not merged yet

File: src/components/security_manager/src/security_manager_impl.cc (hunk 6 above)
Comment (AKalinich-Luxoft) [reply src/components/security_manager/src/security_manager_impl.cc]: @LuxoftAKutsan because now SecurityManager class is responsible for a life time of its listeners so when some listener returns true in OnHandshakeDone() callback - this is a signal for SecurityManager to remove it from listeners and destroy object. Before this fix there was a suicide classes - listener destroys itself in own OnHandshakeDone call so here this responsibility were just moved to the outer component.
As a better alternative here - listeners could be updated to contain smart pointers to listeners however it requires too many changes on upper level.

File: src/components/application_manager/src/application_manager_impl.cc (hunk 8 above)
Comment (AKalinich-Luxoft) [reply src/components/application_manager/src/application_manager_impl.cc]: @AByzhynar because SecurityManager has several listeners and it have to iterate over all of them to get certificate data. Returning true from AM listener is a signal that some data was provided in output reference and SecurityManager should stop this loop and return the result. All other listeners returns false and in this case iteration loop will be continued.

File: src/components/protocol_handler/src/handshake_handler.cc (hunk 13 above)
Comment (AKalinich-Luxoft) [reply src/components/protocol_handler/src/handshake_handler.cc]: @AByzhynar yes. See my answer above:
https://github.com/smartdevicelink/sdl_core/pull/1971#discussion_r158717782

File: src/components/application_manager/include/application_manager/application_manager_impl.h [hunk 14]
```diff
@@ -853,15 +853,43 @@ class ApplicationManagerImpl
...
+   * @brief Notification that certificate update is required.
+   */
   void OnCertificateUpdateRequired() OVERRIDE;
 
+  /**
+   * @brief Get certificate data from policy
+   * @param reference to string where to save certificate data
+   * @return true if listener saved some data to string otherwise false
+   */
+  bool GetPolicyCertificateData(std::string& data) OVERRIDE;
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/application_manager/include/application_manager/application_manager_impl.h]: @LuxoftAKutsan yes, fixed in https://github.com/smartdevicelink/sdl_core/pull/1971/commits/a87c65251e81cb914deaa1f0fe1716175fe1270d

File: src/components/application_manager/include/application_manager/application_manager_impl.h [hunk 15]
```diff
@@ -853,15 +853,43 @@ class ApplicationManagerImpl
...
+   */
   security_manager::SSLContext::HandshakeContext GetHandshakeContext(
       uint32_t key) const OVERRIDE;
+
+  /**
+   * @brief Check if application with specified app_id has NAVIGATION HMI type
+   * @param app_id id of application to check
+   * @return true if application is navi otherwise returns false
+   */
+  bool CheckAppIsNavi(const uint32_t app_id) OVERRIDE;
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/application_manager/include/application_manager/application_manager_impl.h]: @LuxoftAKutsan yes, fixed in https://github.com/smartdevicelink/sdl_core/pull/1971/commits/a87c65251e81cb914deaa1f0fe1716175fe1270d

File: src/components/connection_handler/include/connection_handler/connection.h [hunk 16]
```diff
@@ -209,6 +211,17 @@ class Connection {
...
   void SetProtectionFlag(const uint8_t session_id,
                          const protocol_handler::ServiceType& service_type);
+
+  /**
+   * @brief Check if session contains service with specified service type
+   * @param session_id id of session to check
+   * @param service_type type of service to check
+   * @return true if session contains service with specified service type
+   */
+  bool IsSessionServiceExists(
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/connection_handler/include/connection_handler/connection.h]: @LuxoftAKutsan yes, fixed in https://github.com/smartdevicelink/sdl_core/pull/1971/commits/a87c65251e81cb914deaa1f0fe1716175fe1270d

File: src/components/connection_handler/src/connection_handler_impl.cc (hunk 1 above)
Comment (AKalinich-Luxoft) [reply src/components/connection_handler/src/connection_handler_impl.cc]: @LuxoftAKutsan renamed in https://github.com/smartdevicelink/sdl_core/pull/1971/commits/a87c65251e81cb914deaa1f0fe1716175fe1270d

File: src/components/connection_handler/src/connection_handler_impl.cc (hunk 2 above)
Comment (AKalinich-Luxoft) [reply src/components/connection_handler/src/connection_handler_impl.cc]: @LuxoftAKutsan ok, updated in https://github.com/smartdevicelink/sdl_core/pull/1971/commits/a87c65251e81cb914deaa1f0fe1716175fe1270d

File: src/components/protocol_handler/src/handshake_handler.cc (hunk 5 above)
Comment (AKalinich-Luxoft) [reply src/components/protocol_handler/src/handshake_handler.cc]: @LuxoftAKutsan no, this is an old debug message. Fixed in https://github.com/smartdevicelink/sdl_core/pull/1971/commits/a87c65251e81cb914deaa1f0fe1716175fe1270d

File: src/components/application_manager/include/application_manager/application_manager_impl.h (hunk 7 above)
Comment (AKalinich-Luxoft) [reply src/components/application_manager/include/application_manager/application_manager_impl.h]: @AByzhynar fixed in https://github.com/smartdevicelink/sdl_core/pull/1971/commits/a87c65251e81cb914deaa1f0fe1716175fe1270d

File: src/components/connection_handler/src/connection.cc (hunk 9 above)
Comment (AKalinich-Luxoft) [reply src/components/connection_handler/src/connection.cc]: @AByzhynar renamed in https://github.com/smartdevicelink/sdl_core/pull/1971/commits/a87c65251e81cb914deaa1f0fe1716175fe1270d

File: src/components/protocol_handler/include/protocol_handler/handshake_handler.h (hunk 11 above)
Comment (AKalinich-Luxoft) [reply src/components/protocol_handler/include/protocol_handler/handshake_handler.h]: @AByzhynar fixed in https://github.com/smartdevicelink/sdl_core/pull/1971/commits/a87c65251e81cb914deaa1f0fe1716175fe1270d

**Comment by AByzhynar** [comment]
@AKalinich-Luxoft Please pay your attention to build failure. Protocol handler and connection handler ut failed.

**Comment by AKalinich-Luxoft** [comment]
Rebuild required

File: src/components/include/protocol_handler/session_observer.h [hunk 17]
```diff
@@ -54,6 +54,58 @@ namespace protocol_handler {
  */
 enum { HASH_ID_NOT_SUPPORTED = 0, HASH_ID_WRONG = 0xFFFF0000 };
 
+/**
+ * @brief Struct with data containing attributes of starting session
+ **/
+struct StartingSessionContext {
+  transport_manager::ConnectionUID connection_id_;
+  uint8_t initial_session_id_;
```
Comment (yang1070) [inline src/components/include/protocol_handler/session_observer.h]: why initial_session_id_ is unit8, new_session_id_ is uint32?

File: src/components/include/protocol_handler/session_observer.h [hunk 18]
```diff
@@ -54,6 +54,58 @@ namespace protocol_handler {
...
+   * started.
+   * @param session_id Session ID specified to OnSessionStartedCallback()
+   * @param new_session_id Session ID generated
+   * @param service_type Type of service
+   * @param hash_id Hash ID generated from connection_handle and
+   * new_session_id
+   * @param is_protected Whether service will be protected
+   * @param is_new_service Whether service was already established
+   **/
+  StartingSessionContext(transport_manager::ConnectionUID connection_id,
```
Comment (yang1070) [inline src/components/include/protocol_handler/session_observer.h]: using this constructor, what's the value of is_new_service_ and is_ptu_required_?

Comment (AKalinich-Luxoft) [reply src/components/include/protocol_handler/session_observer.h]: @yang1070 is_new_service_ and is_ptu_required_ have type bool. C++ initialize all non-class types with zeroes (so-called zero initialization) in case if they was not listed in initializer list. For boolean it is a false value. However if you insist on that, I could list these values in initializer list explicitly.

Comment (AKalinich-Luxoft) [reply src/components/include/protocol_handler/session_observer.h]: @yang1070 I made some updates in StartingSessionContext constructors. Now is_new_service_ and is_ptu_required_  are specified in initialization list explicitly. Please see commit 36306024c326aad930a636931f64f00928fce51e

**Comment by AKalinich-Luxoft** [comment]
Rebuild required

File: src/components/include/protocol_handler/session_observer.h (hunk 17 above)
Comment (AKalinich-Luxoft) [reply src/components/include/protocol_handler/session_observer.h]: @yang1070 seems this difference was in old code before this pull request. Both values contains some session id value, so uint8_t is enough for both of them. Updated in https://github.com/smartdevicelink/sdl_core/commit/36306024c326aad930a636931f64f00928fce51e

File: src/components/protocol_handler/include/protocol_handler/protocol_handler_impl.h [hunk 19]
```diff
@@ -389,6 +393,7 @@ class ProtocolHandlerImpl
    * Only valid when generated_session_id is 0. Note, even if
    * generated_session_id is 0, the list may be empty.
    */
+  // DEPRECATED
   void NotifySessionStartedResult(
```
Comment (jacobkeeler) [inline src/components/protocol_handler/include/protocol_handler/protocol_handler_impl.h]: Merge current develop branch, so that the DEPRECATED macro can be used.

File: src/components/protocol_handler/src/protocol_handler_impl.cc [hunk 20]
```diff
@@ -1502,18 +1438,25 @@ RESULT_CODE ProtocolHandlerImpl::HandleControlMessageStartSession(
...
 }
 
+// DEPRECATED
 void ProtocolHandlerImpl::NotifySessionStartedResult(
     int32_t connection_id,
     uint8_t session_id,
     uint8_t generated_session_id,
     uint32_t hash_id,
     bool protection,
+    std::vector<std::string>& rejected_params) {}
```
Comment (jacobkeeler) [inline src/components/protocol_handler/src/protocol_handler_impl.cc]: For safety, just use this deprecated method as a wrapper function:
```
  // DEPRECATED
  void ProtocolHandlerImpl::NotifySessionStartedResult(
      int32_t connection_id,
      uint8_t session_id,
      uint8_t generated_session_id,
      uint32_t hash_id,
      bool protection,
      std::vector<std::string>& rejected_params) {
    protocol_handler::StartSessionContext context(
        connection_id,
        session_id,
        generated_session_id,
        0,
        hash_id,
        protection);
    NotifySessionStarted(context, rejected_params);
  }
```

File: src/components/security_manager/include/security_manager/security_manager_impl.h [hunk 21]
```diff
@@ -158,7 +164,13 @@ class SecurityManagerImpl : public SecurityManager,
    * @brief Notifiers for listeners.
    * Allows to notify that certificate should be updated
    */
-  void NotifyOnCertififcateUpdateRequired();
```
Comment (jacobkeeler) [inline src/components/security_manager/include/security_manager/security_manager_impl.h]: Since this is public, it will need to be deprecated instead of removed.

File: src/components/include/protocol_handler/protocol_handler.h [hunk 22]
```diff
@@ -129,6 +132,18 @@ class ProtocolHandler {
...
+   * @brief Called by connection handler to notify the context of
+   * OnSessionStartedCallback().
+   * @param context reference to structure with started session data
+   * @param rejected_params list of parameters name that are rejected.
+   * Only valid when generated_session_id is 0. Note, even if
+   * generated_session_id is 0, the list may be empty.
+   */
+  virtual void NotifySessionStartedContext(
+      const StartingSessionContext& context,
+      std::vector<std::string>& rejected_params) = 0;
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/include/protocol_handler/protocol_handler.h]: @jacobkeeler renamed to NotifySessionStarted in https://github.com/smartdevicelink/sdl_core/pull/1971/commits/324b740fa4a8d976b4e47db5d53bbf83659b4f8a

File: src/components/include/protocol_handler/session_observer.h [hunk 23]
```diff
@@ -54,6 +54,60 @@ namespace protocol_handler {
  */
 enum { HASH_ID_NOT_SUPPORTED = 0, HASH_ID_WRONG = 0xFFFF0000 };
 
+/**
+ * @brief Struct with data containing attributes of starting session
+ **/
+struct StartingSessionContext {
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/include/protocol_handler/session_observer.h]: @jacobkeeler renamed to SessionContext in https://github.com/smartdevicelink/sdl_core/commit/324b740fa4a8d976b4e47db5d53bbf83659b4f8a

File: src/components/protocol_handler/include/protocol_handler/protocol_handler_impl.h (hunk 19 above)
Comment (AKalinich-Luxoft) [reply src/components/protocol_handler/include/protocol_handler/protocol_handler_impl.h]: @jacobkeeler all commented DEPRECATED keywords in pull request were replaced to macro

File: src/components/protocol_handler/src/protocol_handler_impl.cc (hunk 20 above)
Comment (AKalinich-Luxoft) [reply src/components/protocol_handler/src/protocol_handler_impl.cc]: @jacobkeeler added wrapper to deprecated function. See https://github.com/smartdevicelink/sdl_core/commit/324b740fa4a8d976b4e47db5d53bbf83659b4f8a

File: src/components/security_manager/include/security_manager/security_manager_impl.h (hunk 21 above)
Comment (AKalinich-Luxoft) [reply src/components/security_manager/include/security_manager/security_manager_impl.h]: @jacobkeeler it was not removed. There just was added OVERRIDE macro for safety

Comment (jacobkeeler) [reply src/components/security_manager/include/security_manager/security_manager_impl.h]: @AKalinich-Luxoft It was deleted, note the difference in spelling. Unfortunately, fixing a typo means renaming the function, which is a breaking change. As long as we deprecated the function with the typo, we should be fine.

File: src/components/connection_handler/src/connection_handler_impl.cc [hunk 24]
```diff
@@ -403,22 +406,24 @@ void ConnectionHandlerImpl::OnSessionStartedCallback(
...
+    context.hash_id_ = protocol_handler::HASH_ID_NOT_SUPPORTED;
   }
   sync_primitives::AutoReadLock read_lock(connection_handler_observer_lock_);
   if (connection_handler_observer_) {
-    const uint32_t session_key = KeyFromPair(connection_handle, new_session_id);
+    const uint32_t session_key =
+        KeyFromPair(connection_handle, context.new_session_id_);
+
+    uint32_t app_id = 0;
+    GetDataOnSessionKey(session_key, &app_id, NULL, NULL);
```
Comment (jacobkeeler) [inline src/components/connection_handler/src/connection_handler_impl.cc]: The build fails on this line in the new version of develop, 

```
/home/jacob/sdl_core_master/src/components/connection_handler/src/connection_handler_impl.cc: In member function ‘virtual void connection_handler::ConnectionHandlerImpl::OnSessionStartedCallback(transport_manager::ConnectionUID, uint8_t, const protocol_handler::ServiceType&, bool, const BsonObject*)’:
/home/jacob/sdl_core_master/src/components/connection_handler/src/connection_handler_impl.cc:471:57: error: call of overloaded ‘GetDataOnSessionKey(const uint32_t&, uint32_t*, NULL, NULL)’ is ambiguous
     GetDataOnSessionKey(session_key, &app_id, NULL, NULL);
                                                         ^
In file included from /home/jacob/sdl_core_master/src/components/connection_handler/src/connection_handler_impl.cc:39:0:
/home/jacob/sdl_core_master/src/components/connection_handler/include/connection_handler/connection_handler_impl.h:500:11: note: candidate: virtual int32_t connection_handler::ConnectionHandlerImpl::GetDataOnSessionKey(uint32_t, uint32_t*, std::list<int>*, connection_handler::DeviceHandle*) const
   int32_t GetDataOnSessionKey(
           ^~~~~~~~~~~~~~~~~~~
/home/jacob/sdl_core_master/src/components/connection_handler/include/connection_handler/connection_handler_impl.h:515:22: note: candidate: virtual int32_t connection_handler::ConnectionHandlerImpl::GetDataOnSessionKey(uint32_t, uint32_t*, std::list<int>*, uint32_t*) const
   DEPRECATED int32_t GetDataOnSessionKey(uint32_t key,
```

casting the last argument to `DeviceHandle*` should do the trick.

File: src/components/security_manager/include/security_manager/security_manager_impl.h (hunk 21 above)
Comment (AKalinich-Luxoft) [reply src/components/security_manager/include/security_manager/security_manager_impl.h]: @jacobkeeler sorry, I missed difference in spelling. Old function was restored and marked as deprecated. Seee ff52d04eb98aeb40d13dd8fd596a82ed9158e99f

File: src/components/connection_handler/src/connection_handler_impl.cc (hunk 24 above)
Comment (AKalinich-Luxoft) [reply src/components/connection_handler/src/connection_handler_impl.cc]: @jacobkeeler yes, there was a build issue after rebase. Fixed in 7898292b5de8d80354ab3b9fecacbadcf9d41c61
Now build is OK.

File: src/components/connection_handler/test/connection_handler_impl_test.cc [hunk 25]
```diff
@@ -1172,13 +1191,13 @@ TEST_F(ConnectionHandlerTest, SessionStop_CheckHash) {
...
-            uid_, start_session_id_, &wrong_hash, kRpc);
+            uid_, out_context_.new_session_id_, &wrong_hash, kRpc);
     EXPECT_EQ(0u, end_audio_wrong_hash);
     EXPECT_EQ(protocol_handler::HASH_ID_WRONG, wrong_hash);
-    CheckSessionExists(uid_, start_session_id_);
+    CheckSessionExists(uid_, out_context_.new_session_id_);
 
     const uint32_t end_audio = connection_handler_->OnSessionEndedCallback(
-        uid_, start_session_id_, &hash, kRpc);
+        uid_, out_context_.new_session_id_, hash, kRpc);
```
Comment (jacobkeeler) [inline src/components/connection_handler/test/connection_handler_impl_test.cc]: `&` was deleted here, this means that the deprecated version of the function is being used. Use `&hash`

File: src/components/connection_handler/test/connection_handler_impl_test.cc [hunk 26]
```diff
@@ -1194,13 +1213,13 @@ TEST_F(ConnectionHandlerTest, SessionStop_CheckSpecificHash) {
 
     const uint32_t end_audio_wrong_hash =
         connection_handler_->OnSessionEndedCallback(
-            uid_, start_session_id_, &wrong_hash, kRpc);
+            uid_, out_context_.new_session_id_, wrong_hash, kRpc);
```
Comment (jacobkeeler) [inline src/components/connection_handler/test/connection_handler_impl_test.cc]: Use `&wrong_hash`

File: src/components/connection_handler/test/connection_handler_impl_test.cc [hunk 27]
```diff
@@ -1194,13 +1213,13 @@ TEST_F(ConnectionHandlerTest, SessionStop_CheckSpecificHash) {
...
     EXPECT_EQ(0u, end_audio_wrong_hash);
     EXPECT_EQ(protocol_handler::HASH_ID_WRONG, wrong_hash);
-    CheckSessionExists(uid_, start_session_id_);
+    CheckSessionExists(uid_, out_context_.new_session_id_);
 
     const uint32_t end_audio = connection_handler_->OnSessionEndedCallback(
-        uid_, start_session_id_, &hash, kRpc);
+        uid_, out_context_.new_session_id_, hash, kRpc);
```
Comment (jacobkeeler) [inline src/components/connection_handler/test/connection_handler_impl_test.cc]: Use `&hash`

File: src/components/protocol_handler/src/protocol_handler_impl.cc [hunk 28]
```diff
@@ -1188,128 +1242,6 @@ RESULT_CODE ProtocolHandlerImpl::HandleControlMessageEndServiceACK(
...
-  const std::vector<int> force_protected_service_;
-  ProtocolPacket::ProtocolVersion full_version_;
-  uint8_t* payload_;
-};
-}  // namespace
-#endif  // ENABLE_SECURITY
-
-// Suppress warning for deprecated method used within another deprecated method
-#pragma GCC diagnostic push
-#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
```
Comment (jacobkeeler) [inline src/components/protocol_handler/src/protocol_handler_impl.cc]: This should not be removed, it is necessary because this is deprecated and a deprecated method is used within this function. This pragma is to suppress this warning.

Comment (jacobkeeler) [reply src/components/protocol_handler/src/protocol_handler_impl.cc]: Plus, the pragma statement at the end of the function is still present.

File: src/components/connection_handler/test/connection_handler_impl_test.cc (hunk 25 above)
Comment (AKalinich-Luxoft) [reply src/components/connection_handler/test/connection_handler_impl_test.cc]: @jacobkeeler fixed in https://github.com/smartdevicelink/sdl_core/pull/1971/commits/c95042bdce0bc3d598ce8300e7b17d7d55e9e4b4

File: src/components/connection_handler/test/connection_handler_impl_test.cc (hunk 26 above)
Comment (AKalinich-Luxoft) [reply src/components/connection_handler/test/connection_handler_impl_test.cc]: @jacobkeeler fixed in https://github.com/smartdevicelink/sdl_core/pull/1971/commits/c95042bdce0bc3d598ce8300e7b17d7d55e9e4b4

File: src/components/connection_handler/test/connection_handler_impl_test.cc (hunk 27 above)
Comment (AKalinich-Luxoft) [reply src/components/connection_handler/test/connection_handler_impl_test.cc]: @jacobkeeler fixed in https://github.com/smartdevicelink/sdl_core/pull/1971/commits/c95042bdce0bc3d598ce8300e7b17d7d55e9e4b4

File: src/components/protocol_handler/src/protocol_handler_impl.cc (hunk 28 above)
Comment (AKalinich-Luxoft) [reply src/components/protocol_handler/src/protocol_handler_impl.cc]: @jacobkeeler good catch. Restored in https://github.com/smartdevicelink/sdl_core/pull/1971/commits/c95042bdce0bc3d598ce8300e7b17d7d55e9e4b4
