### PR TITLE
Check waypoint subscription size in resumption

### LINKED ISSUE #3683: SDL sends SubscribeWayPoints to HMI for 1st app even if there is a subscription for 2nd app.
### Bug Report
SDL sends `SubscribeWayPoints` to HMI for 1st app even if there is a subscription for 2nd app.

##### Reproduction Steps
1. AddSubMenu related to resumption is sent by App1
2. App1 and App2 are subscribed to WayPoints
3. Unexpected disconnect and reconnect are performed
4. App1 and App2 re-register with actual HashId
=> SDL does:
   - start resumption process for App1 and App2
   - send UI.AddSubMenu and Navi.SubscribeWayPoints requests related to App1 to HMI
5. HMI responds with <erroneous> resultCode to UI.AddSubMenu and <successful> to Navi.SubscribeWayPoints
=> SDL does:
   - not send revert Navi.UnsbscribeWayPoints request to HMI
   - not restore subscription to WP for App1 and responds RAI_Response(success=true,resultCode=RESUME_FAILED) to App1
   - restore subscription to WP for App2 and responds RAI_Response(success=true,resultCode=SUCCESS) to App2
6. App1 tries to subscribe to WayPoints

##### Expected Behavior
SDL does not send `SubscribeWayPoints request` to HMI since there is an active subscription for another app

##### Observed Behavior
SDL does send `SubscribeWayPoints` request to HMI

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/release/7.1.0-RC1 (c163c2d)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - ATF Script: [3683.lua.tar.gz](https://github.com/smartdevicelink/sdl_core/files/6280877/3683.lua.tar.gz)
 - Report and Logs: [2021-04-08_14-19-18.151_3683_FAIL.tar.gz](https://github.com/smartdevicelink/sdl_core/files/6280871/2021-04-08_14-19-18.151_3683_FAIL.tar.gz)

### PR DESCRIPTION
**Pull request by JackLivio**
Fixes #3683 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
See reproduction steps in issue #3683 

### Summary
Check size of waypoint subscription list before unsubscribing HMI from way points.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by jacobkeeler — APPROVED** [review]

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/sdl_rpc_plugin.cc [hunk 1]
```diff
@@ -131,14 +131,19 @@ void SDLRPCPlugin::RevertResumption(application_manager::Application& app) {
   pending_resumption_handler_->OnResumptionRevert();
 
   if (application_manager_->IsAppSubscribedForWayPoints(app)) {
-    application_manager_->UnsubscribeAppFromWayPoints(app.app_id());
-    if (!application_manager_->IsAnyAppSubscribedForWayPoints()) {
+    std::set<uint32_t> subscribed_apps =
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/sdl_rpc_plugin.cc:134]: @JackLivio probably good place for const auto

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/sdl_rpc_plugin.cc [hunk 2]
```diff
@@ -131,14 +131,19 @@ void SDLRPCPlugin::RevertResumption(application_manager::Application& app) {
...
+        application_manager_->GetAppsSubscribedForWayPoints();
+    bool send_unsubscribe = subscribed_apps.size() <= 1 &&
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/sdl_rpc_plugin.cc:136]: @JackLivio const bool?

Comment (AKalinich-Luxoft) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/sdl_rpc_plugin.cc:136]: @JackLivio do we really need to check "less than one"?
```suggestion
    bool send_unsubscribe = subscribed_apps.size() == 1 &&
```

Comment (JackLivio) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/sdl_rpc_plugin.cc]: @AKalinich-Luxoft Updated the modifiers, but I would suggest keeping <= for "safety".

**Review by AKalinich-Luxoft — APPROVED** [review]

**Review by jacobkeeler — APPROVED** [review]
