### PR TITLE
Fix wrong policy permissions calculation in EXTERNAL_PROPRIETARY

### LINKED ISSUE #2405: Wrong policy permissions calculation in EXTERNAL_PROPRIETARY flow
### Bug Report
There are observed a wrong behaviour on `EXTERNAL_PROPRIETARY` flow in several cases when SDL calculates a list of allowed parameters for RPC which is included in a several functional groups.

According to AppLink Policies Manager specification:

> To determine consent for a particular RPC in a particular HMI level with particular parameters (if applicable), the system shall find all of the functional groups the RPC is included in. If user consent is needed as listed within the functional group in the policy table, the system shall use a logical AND: backend permissions AND User permissions. If the RPC is listed under more than one group, the system shall perform a logical OR amongst all of the possible allowed permissions scenarios for the RPC (and parameter/or HMI level) defined by each of the functional groups.

According to that requirement SDL has a wrong behaviour for the  following test cases:
1. RPC_1 is present in `functional_group_1` with `parameters: [ ]` and in `functional_group_2` with `parameters: [ param1, param2]`. In this case param1, param2 should be allowed using logical OR between groups, however SDL returns DISALLOWED for any parameter
2. RPC_1 is present in `functional_group_1` with `parameters: [ ]` and in `functional_group_2` without parameters section. In this case all parameters should be allowed using logical OR between groups, however SDL returns DISALLOWED for any parameter

##### Reproduction Steps
1.  Update `preloaded_pt.json` - add to `functional_groupings` new test groups:
```
"GroupWithTwoParams": {
  "rpcs": {
    "GetVehicleData": {
                        "hmi_levels": ["BACKGROUND", "FULL", "LIMITED"],
                        "parameters": ["gps", "speed"]
    }
  }
}

"GroupWithAllAllowed": {
  "rpcs": {
    "GetVehicleData": {
                        "hmi_levels": ["BACKGROUND", "FULL", "LIMITED"]
    }
  }
}

"GroupWithAllDisallowed": {
  "rpcs": {
    "GetVehicleData": {
                        "hmi_levels": ["BACKGROUND", "FULL", "LIMITED"],
                        "parameters": []
    }
  }
}

```

2. Update `preloaded_pt.json` - add to `app_policies -> default -> groups` groups `GroupWithTwoParams`, "GroupWithAllAllowed" and `GroupWithAllDisallowed`
3. Start SDL
4. Register new mobile application
5. Activate application
6. Send GetVehicleData("gps", "speed")
7. Send GetVehicleData("rpm")

##### Expected Behavior
SDL responds with GetVehicleData(SUCCESS) + requested vehicle data) on GetVehicleData("gps", "speed")
SDL responds with GetVehicleData(SUCCESS) + requested vehicle data) on GetVehicleData("rpm")

##### Observed Behavior
SDL responds with GetVehicleData(DISALLOWED) on both requests

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #2405 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Covered with unit tests
ATF test scripts

### Summary
There was a problem when application has several allowed functional groups with the same RPC included. In case when some of functional groups have RPC with all parameters disallowed option, SDL ignores all allowed parameters for this RPC in other functional groups.

According to AppLink Policies Manager specification SDL should perform a logical OR amongst all of the possible allowed permissions scenarios for the RPC defined by each of the functional groups.

Current logic was updated to fit this requirement.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/policy/policy_external/include/policy/policy_helper.h [hunk 1]
```diff
@@ -255,8 +255,26 @@ struct FillNotificationData {
...
+                      const std::string& section) const;
+
+  /**
+   * @brief Checks if at least one parameter is allowed for the specified
+   * permissions
+   * @param permissions reference to the permissions structure
+   * @return true if at least one parameter is allowed for the specified
+   * permissions otherwise returns false
+   */
+  bool IsSomeParametersAllowed(const ParameterPermissions& permissions) const;
```
Comment (AByzhynar) [inline src/components/policy/policy_external/include/policy/policy_helper.h]: @AKalinich-Luxoft IsSomeParametersAllowed -> AreSomeParametersAllowed

File: src/components/policy/policy_external/src/policy_helper.cc [hunk 2]
```diff
@@ -620,33 +620,50 @@ void FillNotificationData::UpdateParameters(
...
+  // particular parameters (if applicable), the system shall find all of the
+  // functional groups the RPC is included in. If user consent is needed as
+  // listed within the functional group in the policy table, the system shall
+  // use a logical AND: backend permissions AND User permissions. If the RPC is
+  // listed under more than one group, the system shall perform a logical OR
+  // amongst all of the possible allowed permissions scenarios for the RPC (and
+  // parameter/or HMI level) defined by each of the functional groups.
+
+  if (!IsSomeParametersAllowed(out_parameter)) {
+    // Due to APPLINK-24201 SDL must consider cases when 'parameters' section is
```
Comment (AByzhynar) [inline src/components/policy/policy_external/src/policy_helper.cc]: @AKalinich-Luxoft We don't use JIRA IDs in OpenSDL

File: src/components/policy/policy_external/src/policy_helper.cc [hunk 3]
```diff
@@ -769,16 +786,23 @@ bool FillNotificationData::RpcParametersEmpty(RpcPermissions& rpc) {
...
+    return it_section->second.empty();
   }
   return true;
 }
 
+bool FillNotificationData::IsSomeParametersAllowed(
+    const ParameterPermissions& permissions) const {
+  return permissions.any_parameter_allowed ||
+         (kAllowedKey == current_key_ &&
+          !IsSectionEmpty(permissions, kAllowedKey));
```
Comment (AByzhynar) [inline src/components/policy/policy_external/src/policy_helper.cc]: @AKalinich-Luxoft Really hard to read this return statement

File: src/components/policy/policy_external/src/policy_helper.cc [hunk 4]
```diff
@@ -620,33 +620,50 @@ void FillNotificationData::UpdateParameters(
...
   }
 
   for (; it_parameters != it_parameters_end; ++it_parameters) {
     out_parameter[current_key_].insert(
         policy_table::EnumToJsonString(*it_parameters));
   }
+
+  // We should reset ALL DISALLOWED flags if at least one parameter is allowed
+  // due to a logical OR permissions check
+  if (IsSomeParametersAllowed(out_parameter)) {
```
Comment (conlain-k) [inline src/components/policy/policy_external/src/policy_helper.cc]: This logic seems convoluted and I'm not sure it produces the correct result.

File: src/components/policy/policy_external/src/policy_helper.cc [hunk 5]
```diff
@@ -620,33 +620,50 @@ void FillNotificationData::UpdateParameters(
...
-    if (!does_require_user_consent_) {
-      out_parameter.any_parameter_allowed = true;
-    }
-    if (does_require_user_consent_ && kAllowedKey == current_key_) {
-      out_parameter.any_parameter_allowed = true;
+    // If 'parameters' section is omitted
+    if (!in_parameters.is_initialized()) {
+      if (!does_require_user_consent_ ||
+          (does_require_user_consent_ && kAllowedKey == current_key_)) {
+        out_parameter.any_parameter_allowed = true;
```
Comment (conlain-k) [inline src/components/policy/policy_external/src/policy_helper.cc]: I don't think this gets set if `IsSomeParametersAllowed()` returns true at the top conditional

File: src/components/policy/policy_external/src/policy_helper.cc [hunk 6]
```diff
@@ -620,33 +620,50 @@ void FillNotificationData::UpdateParameters(
...
+  // To determine consent for a particular RPC in a particular HMI level with
+  // particular parameters (if applicable), the system shall find all of the
+  // functional groups the RPC is included in. If user consent is needed as
+  // listed within the functional group in the policy table, the system shall
+  // use a logical AND: backend permissions AND User permissions. If the RPC is
+  // listed under more than one group, the system shall perform a logical OR
+  // amongst all of the possible allowed permissions scenarios for the RPC (and
+  // parameter/or HMI level) defined by each of the functional groups.
+
+  if (!IsSomeParametersAllowed(out_parameter)) {
```
Comment (conlain-k) [inline src/components/policy/policy_external/src/policy_helper.cc]: This seems to short-circuit the adding of parameters within it, I think this conditional doesn't need to be here

**Comment by conlain-k** [comment]
Testing as described in the bug report #2405, the second test case 
``` SDL responds with GetVehicleData(SUCCESS) + requested vehicle data) on GetVehicleData("rpm")```
still fails. I think this is due the `any_parameter_allowed` flag being set only if the line 633 `(!IsSomeParametersAllowed(out_parameter))` conditional occurs. 

Proposed solution is to move the conditional at line 648 (https://github.com/AKalinich-Luxoft/sdl_core/blob/c71899ecf9d1be292646b80704a91fea97bb18d3/src/components/policy/policy_external/src/policy_helper.cc#L648) outside of the conditional scope started at line 633. Another solution would be to remove the line 633 conditional entirely, since that case is checked at the bottom of the function.

File: src/components/policy/policy_external/src/policy_helper.cc (hunk 5 above)
Comment (conlain-k) [reply src/components/policy/policy_external/src/policy_helper.cc]: This part should be outside of the line 633 conditional I believe

File: src/components/policy/policy_external/include/policy/policy_helper.h (hunk 1 above)
Comment (AKalinich-Luxoft) [reply src/components/policy/policy_external/include/policy/policy_helper.h]: @AByzhynar renamed in https://github.com/smartdevicelink/sdl_core/pull/2406/commits/80291097033c8a6cd44a95f2ff4ff4def57e5e8e

File: src/components/policy/policy_external/src/policy_helper.cc (hunk 2 above)
Comment (AKalinich-Luxoft) [reply src/components/policy/policy_external/src/policy_helper.cc]: @AByzhynar removed in https://github.com/smartdevicelink/sdl_core/pull/2406/commits/80291097033c8a6cd44a95f2ff4ff4def57e5e8e

File: src/components/policy/policy_external/src/policy_helper.cc (hunk 3 above)
Comment (AKalinich-Luxoft) [reply src/components/policy/policy_external/src/policy_helper.cc]: @AByzhynar splitted into two lines with the named consts
@conlain-k fixed in https://github.com/smartdevicelink/sdl_core/pull/2406/commits/80291097033c8a6cd44a95f2ff4ff4def57e5e8e

File: src/components/policy/policy_external/src/policy_helper.cc (hunk 4 above)
Comment (AKalinich-Luxoft) [reply src/components/policy/policy_external/src/policy_helper.cc]: @conlain-k I've updated the current logic and removed `IsSomeParametersAllowed` from line 633. It was really redundant there and it's correct to reset disallowed flags at this point. See updated implementation with commit IsSomeParametersAllowed

File: src/components/policy/policy_external/src/policy_helper.cc (hunk 5 above)
Comment (AKalinich-Luxoft) [reply src/components/policy/policy_external/src/policy_helper.cc]: @conlain-k good catch. I removed outer conditional and now it works as expected. See 80291097033c8a6cd44a95f2ff4ff4def57e5e8e

File: src/components/policy/policy_external/src/policy_helper.cc (hunk 6 above)
Comment (AKalinich-Luxoft) [reply src/components/policy/policy_external/src/policy_helper.cc]: @conlain-k removed in 80291097033c8a6cd44a95f2ff4ff4def57e5e8e

**Comment by AKalinich-Luxoft** [comment]
@conlain-k please check updated implementation. Now it should work as expected

File: src/components/policy/policy_external/src/policy_helper.cc [hunk 7]
```diff
@@ -620,7 +620,17 @@ void FillNotificationData::UpdateParameters(
   ParametersConstItr it_parameters = in_parameters.begin();
   ParametersConstItr it_parameters_end = in_parameters.end();
 
-  // Due to APPLINK-24201 SDL must consider cases when 'parameters' section is
+  // From AppLink Policies Manager specification:
```
Comment (JackLivio) [inline src/components/policy/policy_external/src/policy_helper.cc]: Please remove AppLink mentions
