### PR TITLE
Fix processing of receiving empty 'gpsData' struct

### LINKED ISSUE #1876: SDL does not sends GENERIC_ERROR in case of receiving empty 'gpsData' structure
**Occurrence: Always** 

# Description
SDL does not sends GENERIC_ERROR in case of receiving empty 'gpsData' structure

## Preconditions
 - SDL and HMI are started.
 - App is registered and activated.

## Steps to reproduce
1. HMI sends GetVehilceData_response with 'gpsData' structure and this structure is empty (has no parameters).

## Actual result
SDL does not send GENERIC_ERROR.

## Expected result
SDL must treat GetVehicleData_response as invalid and send 'GENERIC_ERROR, success:false, info: Invalid response received from system' to mobile app, log corresponding error internally.
### Requirement

GetVehilceData ( gps: [ ] ) -> empty structure | SDL treats this response as invalid and sends GENERIC_ERROR to mobile app
-- | --

# Environment

# Attachments
Note: Extract attached folder with script to test_scripts folder. 
[Defects.zip](https://github.com/smartdevicelink/sdl_core/files/1512937/Defects.zip)

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [x] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

### PR DESCRIPTION
**Pull request by KVGrygoriev**
Fixes #1876

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
[x] ATF

### Summary
In case HMI sends empty 'gpsData' structure SDL forwards it to mobile.
But the right flow - SDL should sends GENERIC_ERROR with info 'Invalid response received from system'.
That was implemented

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/commands/mobile/on_vehicle_data_notification.cc [hunk 1]
```diff
@@ -56,13 +56,24 @@ void OnVehicleDataNotification::Run() {
   std::vector<smart_objects::SmartObject> appSO;
 
   const VehicleData& vehicle_data = MessageHelper::vehicle_data();
+  const smart_objects::SmartObject incoming_msg_params = (*message_)[strings::msg_params];
   VehicleData::const_iterator it = vehicle_data.begin();
+  std::string key;
 
   for (; vehicle_data.end() != it; ++it) {
-    if (true == (*message_)[strings::msg_params].keyExists(it->first)) {
+    key = it->first;
```
Comment (EKuliiev) [inline src/components/application_manager/src/commands/mobile/on_vehicle_data_notification.cc]: @KVGrygoriev 
const std::string key = it->first;
would be more compact

File: src/components/application_manager/src/commands/mobile/on_vehicle_data_notification.cc [hunk 2]
```diff
@@ -56,13 +56,24 @@ void OnVehicleDataNotification::Run() {
   std::vector<smart_objects::SmartObject> appSO;
 
   const VehicleData& vehicle_data = MessageHelper::vehicle_data();
+  const smart_objects::SmartObject incoming_msg_params = (*message_)[strings::msg_params];
   VehicleData::const_iterator it = vehicle_data.begin();
+  std::string key;
 
   for (; vehicle_data.end() != it; ++it) {
```
Comment (EKuliiev) [inline src/components/application_manager/src/commands/mobile/on_vehicle_data_notification.cc]: @KVGrygoriev 
since this part of code should be modified better to use range based for loop
for (const auto element : vehicle_data)

File: src/components/application_manager/src/commands/mobile/get_vehicle_data_request.cc [hunk 3]
```diff
@@ -268,28 +268,46 @@ void GetVehicleDataRequest::on_event(const event_engine::Event& event) {
...
     case hmi_apis::FunctionID::VehicleInfo_GetVehicleData: {
       EndAwaitForInterface(HmiInterfaces::HMI_INTERFACE_VehicleInfo);
+
+      smart_objects::SmartObject incoming_msg_params = message[strings::msg_params];
+      
+      if (incoming_msg_params.keyExists(strings::gps)) {
+          if (incoming_msg_params[strings::gps].empty()) {
+              LOG4CXX_ERROR(logger_, "Invalid response received from system");
+
+              SendResponse(false,
```
Comment (EKuliiev) [inline src/components/application_manager/src/commands/mobile/get_vehicle_data_request.cc]: @KVGrygoriev according to our code style https://google.github.io/styleguide/cppguide.html#Naming
would be nice to add comment to magic value
SendResponse(/*var_name=*/false, ...

File: src/components/application_manager/src/commands/mobile/on_vehicle_data_notification.cc (hunk 1 above)
Comment (KVGrygoriev) [reply src/components/application_manager/src/commands/mobile/on_vehicle_data_notification.cc]: @EKuliiev each time creates new variable, I don't think it's a good idea
Look above, it's a cycle

File: src/components/application_manager/src/commands/mobile/get_vehicle_data_request.cc [hunk 4]
```diff
@@ -268,28 +268,46 @@ void GetVehicleDataRequest::on_event(const event_engine::Event& event) {
   switch (event.id()) {
     case hmi_apis::FunctionID::VehicleInfo_GetVehicleData: {
       EndAwaitForInterface(HmiInterfaces::HMI_INTERFACE_VehicleInfo);
+
+      smart_objects::SmartObject incoming_msg_params = message[strings::msg_params];
+      
+      if (incoming_msg_params.keyExists(strings::gps)) {
```
Comment (EKuliiev) [inline src/components/application_manager/src/commands/mobile/get_vehicle_data_request.cc]: @KVGrygoriev maybe better to combine
if (incoming_msg_params.keyExists(strings::gps) && incoming_msg_params[strings::gps].empty())

File: src/components/application_manager/src/commands/mobile/on_vehicle_data_notification.cc (hunk 2 above)
Comment (KVGrygoriev) [reply src/components/application_manager/src/commands/mobile/on_vehicle_data_notification.cc]: cycle didn't was modify

File: src/components/application_manager/src/commands/mobile/get_vehicle_data_request.cc [hunk 5]
```diff
@@ -268,28 +268,46 @@ void GetVehicleDataRequest::on_event(const event_engine::Event& event) {
...
+          if (incoming_msg_params[strings::gps].empty()) {
```
Comment (AByzhynar) [inline src/components/application_manager/src/commands/mobile/get_vehicle_data_request.cc]: @KVGrygoriev Why not to write : 
```
 if (incoming_msg_params.keyExists(strings::gps) && incoming_msg_params[strings::gps].empty())
```
instead of nested `if()` statements?

File: src/components/application_manager/src/commands/mobile/on_vehicle_data_notification.cc [hunk 6]
```diff
@@ -56,13 +56,24 @@ void OnVehicleDataNotification::Run() {
   std::vector<smart_objects::SmartObject> appSO;
 
   const VehicleData& vehicle_data = MessageHelper::vehicle_data();
+  const smart_objects::SmartObject incoming_msg_params = (*message_)[strings::msg_params];
```
Comment (AByzhynar) [inline src/components/application_manager/src/commands/mobile/on_vehicle_data_notification.cc]: @KVGrygoriev Why do you copy it? May we use const ref?

File: src/components/application_manager/src/commands/mobile/on_vehicle_data_notification.cc [hunk 7]
```diff
@@ -56,13 +56,24 @@ void OnVehicleDataNotification::Run() {
...
   VehicleData::const_iterator it = vehicle_data.begin();
+  std::string key;
 
   for (; vehicle_data.end() != it; ++it) {
-    if (true == (*message_)[strings::msg_params].keyExists(it->first)) {
+    key = it->first;
+
+    if (incoming_msg_params.keyExists(key)) {
+      if (strings::gps == key) {
+          if (incoming_msg_params[key].empty()) {
```
Comment (AByzhynar) [inline src/components/application_manager/src/commands/mobile/on_vehicle_data_notification.cc]: @KVGrygoriev Same as above about nested `if`s

File: src/components/application_manager/src/commands/mobile/get_vehicle_data_request.cc [hunk 8]
```diff
@@ -268,28 +268,46 @@ void GetVehicleDataRequest::on_event(const event_engine::Event& event) {
...
           result_code, HmiInterfaces::HMI_INTERFACE_VehicleInfo);
+
       std::string response_info;
       GetInfo(message, response_info);
       result = result ||
                ((hmi_apis::Common_Result::DATA_NOT_AVAILABLE == result_code) &&
-                (message[strings::msg_params].length() > 1));
+                !incoming_msg_params.empty());
 
       if (true ==
```
[the remark this answers is not in the document]
Comment (KVGrygoriev) [reply src/components/application_manager/src/commands/mobile/get_vehicle_data_request.cc]: @EKuliiev, see 41aa1c3b2744ac4a3d72c905a500c5b7b1e45ab3

File: src/components/application_manager/src/commands/mobile/get_vehicle_data_request.cc (hunk 4 above)
Comment (KVGrygoriev) [reply src/components/application_manager/src/commands/mobile/get_vehicle_data_request.cc]: @EKuliiev , @AByzhynar,  see 41aa1c3b2744ac4a3d72c905a500c5b7b1e45ab3

File: src/components/application_manager/src/commands/mobile/get_vehicle_data_request.cc (hunk 5 above)
Comment (KVGrygoriev) [reply src/components/application_manager/src/commands/mobile/get_vehicle_data_request.cc]: @AByzhynar , see 41aa1c3b2744ac4a3d72c905a500c5b7b1e45ab3

File: src/components/application_manager/src/commands/mobile/on_vehicle_data_notification.cc (hunk 6 above)
Comment (KVGrygoriev) [reply src/components/application_manager/src/commands/mobile/on_vehicle_data_notification.cc]: @AByzhynar, good point! See 41aa1c3b2744ac4a3d72c905a500c5b7b1e45ab3

File: src/components/application_manager/src/commands/mobile/on_vehicle_data_notification.cc (hunk 7 above)
Comment (KVGrygoriev) [reply src/components/application_manager/src/commands/mobile/on_vehicle_data_notification.cc]: @AByzhynar, see 41aa1c3b2744ac4a3d72c905a500c5b7b1e45ab3

**Comment by KVGrygoriev** [comment]
Rebuild required
