### PR TITLE
Fix SSL certificate output information in log

### LINKED ISSUE #1017: Security: SDL print out CN and serialNumber details of certificates in log.
## Occurrence
Always.

## Preconditions
1. App is configurated to send valid spt_credential.p12. 
2. SDL and HMI are started.

## Steps to reproduce
1. Register an app.
2. Start Secure RPC service.

## Actual result
SDL print out HU and mobile app`s certificates in logs with "CN" and "SERIALNUMBER".

## Expected result
SDL should print only <signing authority> (that is, "issuer & subject" of Root CA) and <expiration> fields

# Environment
Branch: Repository: https://github.com/smartdevicelink/sdl_core/ Tag: 4.2.0
HMI: 3acad9e9673fb479a
SDL: a6c32b45832653d6b851be9b19355fa35f377e07
ATF version: N/A
OS: Ubuntu 14.04 TTS x64
Transport: USB
Mobile device: Acer B1-710
Mobile OS: Android 4.1.2
Mobile App version: SPT ver 2.1.84 code 242
Mobile App type: Navi
Virtual machine using: N/A

# Attachments
[att_issue#1017.zip](https://github.com/smartdevicelink/sdl_core/files/576365/att_issue.1017.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
The problem was that SDL prints out to log full information about SSL certificates including CN and serial number. According to requirements It is correct for FS project, but incorrect for GENIVI.

In this pull request:
- Added `RemoveDisallowedInfo()` function to filter disallowed params from input data
- Added string filtering for subject and issuer data
- C-style casts were replaced with C++ casts for `ASN1_TIME`
- Small code refactoring in `PrintCertData()` function

Related pull request #1421 
Fixes #1017

### CODE REVIEW

**Comment by AKalinich-Luxoft** [comment]
@AByzhynar, @LitvinenkoIra, @LuxoftAKutsan, @dev-gh please review

**Comment by AKalinich-Luxoft** [comment]
@AByzhynar, @LuxoftAKutsan please review

File: src/components/security_manager/include/security_manager/crypto_manager_impl.h [hunk 1]
```diff
@@ -80,6 +80,15 @@ class CryptoManagerImpl : public CryptoManager {
...
    private:
     void PrintCertInfo();
+
+    /**
+     * @brief Removes disallowed for printing certificate information from input
+     * data
+     * @param in_data input data with certificate information
+     * @return filtered string with allowed for printing information
+     */
+    std::string RemoveDisallowedInfo(X509_NAME* in_data) const;
```
Comment (LuxoftAKutsan) [inline src/components/security_manager/include/security_manager/crypto_manager_impl.h]: @AKalinich-Luxoft return value can be const?

File: src/components/security_manager/src/ssl_context_impl.cc [hunk 2]
```diff
@@ -136,32 +138,69 @@ std::map<std::string, CryptoManagerImpl::SSLContextImpl::BlockSizeGetter>
     CryptoManagerImpl::SSLContextImpl::max_block_sizes =
         CryptoManagerImpl::SSLContextImpl::create_max_block_sizes();
 
+std::string CryptoManagerImpl::SSLContextImpl::RemoveDisallowedInfo(
+    X509_NAME* in_data) const {
```
Comment (LuxoftAKutsan) [inline src/components/security_manager/src/ssl_context_impl.cc]: @AKalinich-Luxoft in_data can be NULL ?

File: src/components/security_manager/include/security_manager/crypto_manager_impl.h (hunk 1 above)
Comment (AKalinich-Luxoft) [inline src/components/security_manager/include/security_manager/crypto_manager_impl.h]: @LuxoftAKutsan yes, done in https://github.com/smartdevicelink/sdl_core/pull/1636/commits/299664d8d96664a1e3102685faa8fa9ef1de86c2

File: src/components/security_manager/src/ssl_context_impl.cc (hunk 2 above)
Comment (AKalinich-Luxoft) [inline src/components/security_manager/src/ssl_context_impl.cc]: @LuxoftAKutsan yes, it can. Added checking for `in_data` for this specific case in https://github.com/smartdevicelink/sdl_core/pull/1636/commits/299664d8d96664a1e3102685faa8fa9ef1de86c2
