### PR TITLE
Set secure wss cipher list

### LINKED ISSUE #3884: Cloud Apps WSS handshake using weak cipher suite
### Bug Report
During the WSS connection with a cloud app, the ssl handshake is failing with the message "dh key length too small".

This was tested with a 2048 bit RSA signed CA certificate so the issue must be with the cipher suite key exchange method used by Core & the cloud application.

##### Reproduction Steps
1. Setup sdl java se app to use wss connections
2. Setup sdl core to connect to java app with a wss connection
3. Activate app

##### Expected Behavior
Secured communication is established and the app registers.
##### Observed Behavior
WSS error: dh key length too small, connection is not established

##### OS & Version Information
* OS/Version: Ubuntu 20 with openssl 1.1.1
* SDL Core Version: 8.1
* Testing Against: SDL Java SE in Android studio

### PR DESCRIPTION
**Pull request by JackLivio**
Fixes #3884 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Connect cloud application using wss with a signed CA.cert

### Summary
Sets the ssl context for wss connections to only use "hardened" cipher suites. This prevents the java server from using an insecure key exchange mechanism. Resolves the dh key length issue without reducing the operating systems security level.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/transport_manager/src/cloud/websocket_client_connection.cc [hunk 1]
```diff
@@ -59,6 +59,15 @@ WebsocketClientConnection::WebsocketClientConnection(
     , device_uid_(device_uid)
     , app_handle_(app_handle)
     , io_pool_(1) {
+  // SSL_CTX_set_security_level(ctx_.native_handle(), 1);
```
Comment (jacobkeeler) [inline src/components/transport_manager/src/cloud/websocket_client_connection.cc:62]:
```suggestion
```
Seems this was accidentally left in

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

**Review by jacobkeeler — APPROVED** [review]
