### PR TITLE
Fix SDL crash during application registration

### LINKED ISSUE #3108: SDL Crash - After all apps exited
### Bug Report
SDL crashes after all apps exited.

##### Occurence
Once

##### Precondition
1. HMI and SDL are started
2. Two apps are registered and activated 

##### Reproduction Steps
Unknown. 
SDL core crash happens during manual testing of RC Multiple Modules functionality.
2 app instances were involved.
After exiting of the last app (via Menu->Exit) - in 2-3 seconds SDL crashed.

##### Expected Behavior
SDL works normally without crashes

##### Observed Behavior
SDL crashed 

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/6.0.0_RC2 ( 4d283e )
* HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop ( bd53f1 ) 
* SPT: SyncProxyTester ( 20191028 Nightly-Android, Proxy Lib Ver 4.9.1 ) 

##### Attachments:
  - gdb: [gdb.txt](https://github.com/smartdevicelink/sdl_core/files/3793440/gdb.txt)
  - logs: N/A

### PR DESCRIPTION
**Pull request by IGapchuk**
Fixes #3108 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
There is an issue when SDL crashes during registration second application in the time when already exists a registered other one application.

In the current implementation ApplicationManager during application registering by the `ApplicationManager::RegisterApplication` method creates a new instance of the application and adds it to the collection of all registered applications. This method calls in the  RegisterAppInterfaceRequest, but all needed extensions will be added only by the `ApplicationManager::OnApplicationRegistered` method during sending RegisterAppInterface Response to the mobile.

According to the described behavior could appear case when a first application is registered successfully and all needed application extensions are successfully added too. The second application starts the registration process in someone thread, but in the other one thread, SDL receives `PolicyEvent::kApplicationPolicyUpdated` event and tries to unsubscribe all applications from removed in policy table Vehicle Data Items. All actions go on in the next sequence:

**Precondition:**
The first application is successfully registered and all needed extensions are added.

**The first thread:**
1. The Mobile device sends RegisterAppInterfaceRequest RPC to the SDL for registration of the second application.
2. SDL receives the RegisterAppInterfaceRequest and calls method Run.
3. Within method RegisterAppInterfaceRequest::Run ApplicationManager runs the method `RegisterApplication`.

**The second thread:**
4. The SDL receives the `PolicyEvent::kApplicationPolicyUpdated` event and forwards the event to each plugin for processing it.
5. `VehicleInfoPlugin` tries to unsubscribe all registered applications from removed in policy table Vehicle Data Items. 
- The plugin finds the first application and unsubscribes it from all removed Vehicle Data Items. 
- The plugin finds the second application and doesn't find any extensions for the application and crashes on the DCHECK with an uninitialized pointer to the extension.

### Changelog
**RPC plugin:**
- Add the new Application event  (`ApplicationEvent::kRCStatusChanged`). The event uses to inform `RcRPCPlugin` that `OnRcStatus` notification should be sent.

**RC RPC plugin:**
- Split adding `RCExtension` to an application and sending `OnRCStatus` notification to the separate actions.

**ApplicatioManager:**
- Split adding all extensions to an application and sending OnRCStatus notification to separate actions (via applying to each plugin the new application event;
- Add the new method for applying someone functor to each plugin. The new method uses for applying the `ApplicationEvent::kRCStatusChanged` event to RCRPCPlugin

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by JackLivio** [comment]
Does this fix isue #31089instead of #3108 ?

**Comment by IGapchuk** [comment]
Hi, @JackLivio.
This PR is related to issue #3108 and more precise investigation revealed that the route cause of the SDL's crash is related to application registration as well.

File: src/components/application_manager/include/application_manager/application_manager_impl.h [hunk 1]
```diff
@@ -1136,7 +1136,28 @@ class ApplicationManagerImpl
    */
   protocol_handler::MajorProtocolVersion SupportedSDLVersion() const OVERRIDE;
 
+  /**
+   * @brief Applies functor for each plugin
+   * @param functor Functor that will be applied to each plugin
+   */
+  void ForEachPlugin(
```
Comment (AByzhynar) [inline src/components/application_manager/include/application_manager/application_manager_impl.h]: @IGapchuk May be it is worth to replace function name with more detailed name something like ApplyFunctorForEachPlugin?

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/register_app_interface_request.cc [hunk 2]
```diff
@@ -875,6 +876,18 @@ void RegisterAppInterfaceRequest::SendRegisterAppInterfaceResponseToMobile(
   // Default HMI level should be set before any permissions validation, since it
   // relies on HMI level.
   application_manager_.OnApplicationRegistered(application);
+
+  if (application->is_remote_control_supported()) {
+    auto add_rc_extension = [application](plugin_manager::RPCPlugin& plugin) {
+      if (plugin.PluginName() ==
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/register_app_interface_request.cc]: @IGapchuk Why did you use it for rc_rpc_plugin ONLY?

File: src/components/application_manager/include/application_manager/application_manager_impl.h (hunk 1 above)
Comment (IGapchuk) [reply src/components/application_manager/include/application_manager/application_manager_impl.h]: @AByzhynar I agree with you. The name has been changed in 5a5d11ccdf1f25ae506f64a45f4fb13ab18bfcd1

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/register_app_interface_request.cc (hunk 2 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/register_app_interface_request.cc]: @AByzhynar On the current implementation, all extensions added to an application during running `ApplicationManagerImpl::RegisterApplication` method that called on the 377 line. But at that moment, the application is not marked as `remote_control_supported` and RCPlugin can't add RCExtension to the application. So we do that in this place when default HMI level will be set and the default window will be added.

File: src/components/application_manager/src/application_manager_impl.cc [hunk 3]
```diff
@@ -4176,6 +4164,42 @@ ApplicationManagerImpl::SupportedSDLVersion() const {
...
+  apps_size_ = static_cast<uint32_t>(applications_.size());
+}
+
+void ApplicationManagerImpl::AddExtensionsToApp(
+    ApplicationSharedPtr application) {
+  LOG4CXX_AUTO_TRACE(logger_);
+  DCHECK_OR_RETURN_VOID(application);
+  sync_primitives::AutoLock lock(applications_list_lock_ptr_);
+
+  std::function<void(plugin_manager::RPCPlugin&)> on_app_registered =
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/src/application_manager_impl.cc]: @IGapchuk auto ?

File: src/components/application_manager/include/application_manager/application_manager_impl.h [hunk 4]
```diff
@@ -1136,7 +1136,28 @@ class ApplicationManagerImpl
...
+      std::function<void(plugin_manager::RPCPlugin&)> functor) OVERRIDE;
+
  private:
+  /**
+   * @brief Adds application to registered applications list and marks it as
+   * registered
+   * @param application Application taht should be added to registered
```
[the remark this answers is not in the document]
Comment (IGapchuk) [reply src/components/application_manager/include/application_manager/application_manager_impl.h]: @AKalinich-Luxoft Fixed in e792e3aa3409c421efb5f81bb14a5e7013b9ed0b

File: src/components/application_manager/src/application_manager_impl.cc (hunk 3 above)
Comment (IGapchuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @AKalinich-Luxoft Has been changed in e792e3aa3409c421efb5f81bb14a5e7013b9ed0b

**Comment by theresalech** [comment]
@AByzhynar can you please advise if this is ready for Livio review?

**Comment by AByzhynar** [comment]
@IGapchuk As PR author could you please answer @theresalech if this PR is ready for Livio review. Thank you.

**Comment by IGapchuk** [comment]
Hi @theresalech.
This PR needs in one more internal review's iteration and after this iteration PR will be ready for Livio review.

File: src/components/include/application_manager/application_manager.h [hunk 5]
```diff
@@ -390,6 +390,12 @@ class ApplicationManager {
   virtual bool IsAppTypeExistsInFullOrLimited(
       ApplicationConstSharedPtr app) const = 0;
 
+  /**
+   * @brief Completes application registration
+   * @param application Application which registration should be completed
```
Comment (AByzhynar) [inline src/components/include/application_manager/application_manager.h]: @IGapchuk Add more details to description. It is not clear what does it mean `Completes application registration`. But what is under the hood?

File: src/components/application_manager/include/application_manager/application_manager_impl.h [hunk 6]
```diff
@@ -1136,7 +1136,24 @@ class ApplicationManagerImpl
...
+      std::function<void(plugin_manager::RPCPlugin&)> functor) OVERRIDE;
+
  private:
+  /**
+   * @brief Adds application to registered applications list and marks it as
+   * registered
+   * @param application Application that should be added to registered
+   * applications list.
+   */
+  void AddAppToRegisteredAppList(ApplicationSharedPtr application);
```
Comment (alexkutsan) [inline src/components/application_manager/include/application_manager/application_manager_impl.h]: can be const?

File: src/components/application_manager/include/application_manager/application_manager_impl.h [hunk 7]
```diff
@@ -1136,7 +1136,24 @@ class ApplicationManagerImpl
...
+
+  /**
+   * @brief Adds all extensions to applications
+   * @param application Application to which will be added extensions
+   */
+  void AddExtensionsToApp(ApplicationSharedPtr application);
```
Comment (alexkutsan) [inline src/components/application_manager/include/application_manager/application_manager_impl.h]: can be const?

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/register_app_interface_request.cc (hunk 2 above)
Comment (alexkutsan) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/register_app_interface_request.cc]: Sounds like a hack. Requires additional comment in the code.

File: src/components/application_manager/src/application_manager_impl.cc [hunk 8]
```diff
@@ -4176,6 +4164,41 @@ ApplicationManagerImpl::SupportedSDLVersion() const {
...
+      "App with app_id: " << application->app_id()
+                          << " has been added to registered applications list");
+  apps_size_ = static_cast<uint32_t>(applications_.size());
+}
+
+void ApplicationManagerImpl::AddExtensionsToApp(
+    ApplicationSharedPtr application) {
+  LOG4CXX_AUTO_TRACE(logger_);
+  DCHECK_OR_RETURN_VOID(application);
+  sync_primitives::AutoLock lock(applications_list_lock_ptr_);
```
Comment (alexkutsan) [inline src/components/application_manager/src/application_manager_impl.cc]: Why do we lock applications_list_lock_ptr_? in case if plugin will need to use applications_list_ inside and lock it again, it will be a dead lock

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/register_app_interface_request.cc (hunk 2 above)
Comment (alexkutsan) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/register_app_interface_request.cc]: Do we have an option to mark application rc before all plugins extensions will be added?

File: src/components/application_manager/include/application_manager/application_manager_impl.h (hunk 7 above)
Comment (IGapchuk) [reply src/components/application_manager/include/application_manager/application_manager_impl.h]: @alexkutsan Changed in 9631f38080e906c4b63be2d3e2c449628e284ccf

File: src/components/application_manager/src/application_manager_impl.cc (hunk 8 above)
Comment (IGapchuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @alexkutsan Removed in 9631f38080e906c4b63be2d3e2c449628e284ccf

File: src/components/application_manager/src/application_manager_impl.cc [hunk 9]
```diff
@@ -4176,6 +4163,28 @@ ApplicationManagerImpl::SupportedSDLVersion() const {
...
+
+  // Add application to registered app list and set appropriate mark.
+  application->MarkRegistered();
+  applications_.insert(application);
+  LOG4CXX_DEBUG(
+      logger_,
+      "App with app_id: " << application->app_id()
+                          << " has been added to registered applications list");
+  apps_size_ = static_cast<uint32_t>(applications_.size());
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/src/application_manager_impl.cc]: What? this variable confuses me.

File: src/components/application_manager/include/application_manager/plugin_manager/rpc_plugin.h [hunk 10]
```diff
@@ -65,7 +65,8 @@ enum ApplicationEvent {
   kApplicationRegistered,
   kApplicationUnregistered,
   kDeleteApplicationData,
-  kGlobalPropertiesUpdated
+  kGlobalPropertiesUpdated,
+  kRCStatusChanged
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/include/application_manager/plugin_manager/rpc_plugin.h]: Smells like a separate bug, please mention in description this changes and do separate commit

File: src/components/application_manager/src/application_manager_impl.cc (hunk 9 above)
Comment (IGapchuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @LuxoftAKutsan This variable uses for `AM ListUpdater` for starting PTU.

**Comment by jordynmackool** [comment]
@IGapchuk please let me know when you have completed your review.

**Comment by IGapchuk** [comment]
Hello, @jordynmackool.
We would like to inform you, that the internal review is done and PR is ready for to Livio team review.

**Comment by JackLivio** [comment]
Updating the target to the hotfix release branch 6.0.1
