### PR TITLE
Fix merge module data incorrect behavior

### LINKED ISSUE #2988: SDL incorrect update interior vehicle data for LIGHT RC module with OnInteriorVehicleData notification
### Bug Report
SDL incorrect updates interior vehicle data cache for LIGHT RC module with OnInteriorVehicleData notification

##### Reproduction Steps
0.Precondition:
  1) SDL and HMI are started with App 1 and App 2 application data in LPT
  2) HMI sent LIGHT module capabilities to the SDL
  3) HMI has next data for LIGHT RC module:
``` [
{
      id = "READING_LIGHTS",
      status = "ON",
      density = 0.5,
      color = { red = 150, green = 200, blue = 250 }
    },
    {
      id = "AMBIENT_LIGHTS",
      status = "ON",
      density = 0.7,
      color = { red = 100, green = 100, blue = 100 }
    }
]
```
  3) Mobile is connected to the SDL
  4) App 1 and App 2 are registered and activated

1. Send correct "GetInteriorVehicleData"(moduleType = "LIGHT", subscribe = true) request from App 1 to the SDL
2. Update data of LIGHT RC module with  `id: "AMBIENT_LIGHTS"` on HMI:
 HMI sends OnInteriorVehicleData ( 
``` 
lightState = [
   {
      id = "AMBIENT_LIGHTS",
      status = "ON",
      density = 0.3,
      color = { red = 50, green = 150, blue = 120 }
    }
]
```
)
3. Send correct "GetInteriorVehicleData"(moduleType = "LIGHT") request from App 2 to the SDL

##### Expected Behavior
SDL responds on "GetInteriorVehicleData" to the App 2 with data:
```
lightState = [
    {
      id = "READING_LIGHTS",
      status = "ON",
      density = 0.5,
      color = { red = 150, green = 200, blue = 250 }
    },
    {
      id = "AMBIENT_LIGHTS",
      status = "ON",
      density = 0.3,
      color = { red = 50, green = 150, blue = 120 }
    }
]
```

##### Observed Behavior
SDL responds on "GetInteriorVehicleData" to the App 2 with data:
```
lightState = [
   {
      id = "AMBIENT_LIGHTS",
      status = "ON",
      density = 0.3,
      color = { red = 50, green = 150, blue = 120 }
    }
]
```

##### OS & Version Information
* OS/Version: Ubuntu 16.04 amd64
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (b7a3f9c)
* ATF: https://github.com/smartdevicelink/sdl_atf/tree/develop
* Test scripts: https://github.com/smartdevicelink/sdl_atf_test_scripts/commits/develop (b0cabdc)
##### Test Case, Sample Code, and / or Example App
[logs.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3486704/logs.tar.gz)
[test_script.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3486705/test_script.tar.gz)

### LINKED ISSUE #2997: SDL does not apply the versioning for vehicle data
### Bug Report
SDL does not apply the versioning for vehicle data

##### Preconditions
1. SDL and HMI are started
2. App has permissions for fuelRange, parameter is available `since` 5.0 version

##### Reproduction Steps
1. Register application with `majorVersion = 3, minorVersion = 0`
2. App requests `SubscribeVehicleData` with `fuelRange`

##### Expected Behavior
SDL procesess  the request with `fuelRange` as request with undefined data

##### Observed Behavior
SDL processed  the request with `fuelRange` as defined data

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/8db0c2601921fdd368bf86133780746b532c40f5
* ATF: https://github.com/smartdevicelink/sdl_atf/commit/d6c2138f8d894d1e343d971226a16c47019ee92e
* Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2256

##### Logs
[report.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3535582/report.tar.gz)

### PR DESCRIPTION
**Pull request by YarikMamykin**
Fixes #2988 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Added unit tests for RCHelpers

### Summary
Moved MergeModuleData and MergeArray methods from InteriorDataCache to RCHelpers.
Previously, when data for module was saved into SDL cache, on update SDL reseted cached data with new one, no matter of data type. It is critical in case we have array of objects which have field _"id"_ .  

So instead of merging MergeArray function just replaced existing data with the new one.
(See detailed issue description here https://github.com/smartdevicelink/sdl_core/issues/2988).

With this fix data stored in SDL cache will be merged - existing data will be updated and new one added.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_helpers.h [hunk 1]
```diff
@@ -146,6 +146,29 @@ class RCHelpers {
...
       smart_objects::SmartObject& msg_params);
+
+  /**
+   * @brief MergeModuleData all keys and values from first parameter and
+   * update and append keys and values from the second
+   * @param data1 - initial data
+   * @param data2 - updated data
+   * @return updated data1 with data2 keys and values
+   */
+  static smart_objects::SmartObject MergeModuleData(
```
Comment (LitvinenkoIra) [inline src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_helpers.h]: @YarikMamykin please create two separate commits - one for refactoring and one for the fix

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_helpers.cc [hunk 2]
```diff
@@ -276,4 +276,86 @@ void RCHelpers::RemoveRedundantGPSDataFromIVDataMsg(
...
+  // an ID included, otherwise replace
+
+  if (data1.getType() != smart_objects::SmartType::SmartType_Array ||
+      data2.getType() != smart_objects::SmartType::SmartType_Array ||
+      data2.empty()) {
+    return data2;
+  }
+
+  auto& data2_array = *data2.asArray();
+  for (const auto& e : data2_array) {
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_helpers.cc]: @YarikMamykin Bad variable name even it is temporary. `e` is a bad name. NAme it at least `item`

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/interior_data_cache_test.cc [hunk 3]
```diff
@@ -177,4 +178,21 @@ TEST_F(InteriorDataCacheTest, Exist2ModuleTypesRemoveOneAnotherOneLeft) {
   EXPECT_EQ(data2, retrieved_data2);
 }
 
+TEST_F(InteriorDataCacheTest, CheckCacheDataMerge) {
+  rc_rpc_plugin::InteriorDataCacheImpl cache;
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/interior_data_cache_test.cc]: @YarikMamykin 
Move it to the place before its first usage

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/interior_data_cache_test.cc [hunk 4]
```diff
@@ -177,4 +178,21 @@ TEST_F(InteriorDataCacheTest, Exist2ModuleTypesRemoveOneAnotherOneLeft) {
...
+  const std::string module_id = "random_module_id";
+  rc_rpc_plugin::ModuleUid module(module_type_key, module_id);
+
+  smart_objects::SmartObject data;
+  data["key"] = "value";
+  cache.Add(module, data);
+  data["key"] = "value1";
+  cache.Add(module, data);
+
+  auto retrieved_data = cache.Retrieve(module);
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/interior_data_cache_test.cc]: @YarikMamykin const?

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc [hunk 5]
```diff
@@ -0,0 +1,278 @@
...
+const std::string kKeyValue = "value";
+const std::string kArray = "array";
+}  // namespace
+
+namespace rc_rpc_plugin_test {
+using namespace rc_rpc_plugin;
+
+class RCHelpersTest : public ::testing::Test {
+ public:
+  RCHelpersTest() {}
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc]: @YarikMamykin What do you need an empty ctor for?

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc [hunk 6]
```diff
@@ -0,0 +1,278 @@
...
+
+  smart_objects::SmartObject genSmartObject(const int& object_number,
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc]: @YarikMamykin Bad function name. Read please [SDL Coding style](https://github.com/smartdevicelink/sdl_core/wiki/SDL-Coding-Style-Guide)

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc [hunk 7]
```diff
@@ -0,0 +1,278 @@
...
+  std::map<std::string, std::string> expected_keys_values = {
+      {"key1", "value1"}, {"key2", "value2"}};
+  auto it = expected_keys_values.begin();
+
+  data1[it->first] = it->second;
+  ++it;
+  data2[it->first] = it->second;
+
+  auto result = RCHelpers::MergeModuleData(data1, data2);
+  for (auto& e : expected_keys_values) {
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc]: @YarikMamykin same as above

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc [hunk 8]
```diff
@@ -0,0 +1,278 @@
...
+    result[kKeyValue] = kKeyValue + std::to_string(object_number);
+    if (use_id_key) {
+      result[kKeyId] = kKeyId + std::to_string(object_number);
+    }
+    return result;
+  }
+};
+
+TEST_F(RCHelpersTest, MergeModuleData_OneOfParamsNotSmartMap) {
+  using namespace smart_objects;
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc]: @YarikMamykin MAy be moving it outside instead of using in every test - is a better idea?

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc [hunk 9]
```diff
@@ -0,0 +1,278 @@
...
+TEST_F(RCHelpersTest, MergeModuleData_Recursive) {
+  using namespace smart_objects;
+
+  SmartObject data1(SmartType_Map);
+  SmartObject data2(SmartType_Map);
+
+  data1["key1"]["subkey1"] = "subvalue1";
+  data2["key1"]["subkey2"] = 30;
+
+  auto result = RCHelpers::MergeModuleData(data1, data2);
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc]: @YarikMamykin const?

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc [hunk 10]
```diff
@@ -0,0 +1,278 @@
...
+  EXPECT_NE(result, data1);
+  EXPECT_EQ(result, data2);
+}
+
+TEST_F(RCHelpersTest, MergeArray_FirstArrayEmpty) {
+  using namespace smart_objects;
+  SmartObject data1(SmartType_Array);
+  SmartObject data2(SmartType_Array);
+  *data2.asArray() = std::vector<SmartObject>{
+      SmartObject(10),
```
Comment (AByzhynar) [inline src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc]: @YarikMamykin MAgic numbers?

Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc]: @AByzhynar , fixed in b61ba7c099f2c1b7caf78e8180514ad3e9cf253a

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc (hunk 9 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc]: @AByzhynar , fixed in b61ba7c099f2c1b7caf78e8180514ad3e9cf253a

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc (hunk 8 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc]: @AByzhynar , fixed in b61ba7c099f2c1b7caf78e8180514ad3e9cf253a

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc (hunk 7 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc]: @AByzhynar , fixed in b61ba7c099f2c1b7caf78e8180514ad3e9cf253a

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc (hunk 6 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc]: @AByzhynar , fixed in b61ba7c099f2c1b7caf78e8180514ad3e9cf253a

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc (hunk 5 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc]: @AByzhynar , fixed in b61ba7c099f2c1b7caf78e8180514ad3e9cf253a

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/interior_data_cache_test.cc (hunk 4 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/interior_data_cache_test.cc]: @AByzhynar , fixed in 688641776f

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/interior_data_cache_test.cc (hunk 3 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/interior_data_cache_test.cc]: @AByzhynar , fixed in 6886417

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_helpers.cc (hunk 2 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_helpers.cc]: @AByzhynar , fixed in 66a90ade0c

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_helpers.h (hunk 1 above)
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_helpers.h]: @LitvinenkoIra , please take a look at 688641776f (fix) and 66a90ade0c (refactoring)

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_helpers.cc [hunk 11]
```diff
@@ -276,4 +276,86 @@ void RCHelpers::RemoveRedundantGPSDataFromIVDataMsg(
...
+    const smart_objects::SmartObject& data1,
+    const smart_objects::SmartObject& data2) {
+  if (data1.getType() != smart_objects::SmartType::SmartType_Map ||
+      data2.getType() != smart_objects::SmartType::SmartType_Map) {
+    return data2;
+  }
+
+  smart_objects::SmartObject result = data1;
+
+  for (auto it = data2.map_begin(); it != data2.map_end(); ++it) {
```
[the remark this answers is not in the document]
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_helpers.cc]: @AByzhynar , we can't use _const auto_ here, because of iteration with _++it_

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_helpers.cc [hunk 12]
```diff
@@ -276,4 +276,86 @@ void RCHelpers::RemoveRedundantGPSDataFromIVDataMsg(
...
+  smart_objects::SmartObject result = data1;
+  smart_objects::SmartArray* result_array = result.asArray();
+
+  auto find_by_id = [](smart_objects::SmartArray* array,
+                       const smart_objects::SmartObject& id)
+      -> smart_objects::SmartArray::iterator {
+    return std::find_if(array->begin(),
+                        array->end(),
+                        [&id](const smart_objects::SmartObject& obj) -> bool {
+                          return obj[application_manager::strings::id] == id;
```
[the remark this answers is not in the document]
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_helpers.cc]: @AByzhynar , swapped in 7143134f4cc8c7470d20a02ee71c1c44c25842c9

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_helpers.cc [hunk 13]
```diff
@@ -276,4 +276,86 @@ void RCHelpers::RemoveRedundantGPSDataFromIVDataMsg(
...
+                        });
+  };
+
+  auto merge = [&result_array,
+                &find_by_id](const smart_objects::SmartObject& data) -> void {
+    auto element_id = data[application_manager::strings::id];
+    auto result_it = find_by_id(result_array, element_id);
+
+    if (result_it != result_array->end()) {
```
[the remark this answers is not in the document]
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_helpers.cc]: @AByzhynar , swapped in 7143134f4cc8c7470d20a02ee71c1c44c25842c9

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc [hunk 14]
```diff
@@ -0,0 +1,258 @@
...
+TEST_F(RCHelpersTest, MergeArray_OneOfParamsNotSmartArray) {
+  SmartObject data1(SmartType_Array);
+  SmartObject data2(SmartType_Map);
+
+  const auto result = RCHelpers::MergeArray(data1, data2);
+  EXPECT_NE(result, data1);
+  EXPECT_EQ(result, data2);
+}
+
+TEST_F(RCHelpersTest, MergeArray_FirstArrayEmpty) {
```
[the remark this answers is not in the document]
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc]: @AByzhynar , reworked in 5eeb3f03fae72787ecbf2818b27b1264f4122c95

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_helpers.cc (hunk 11 above)
[the remark this answers is not in the document]
Comment (AByzhynar) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_helpers.cc]: > @AByzhynar , we can't use _const auto_ here, because of iteration with _++it_

@YarikMamykin Can we use range-based loop here?

[the remark this answers is not in the document]
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_helpers.cc]: @AByzhynar , no, we can't because of SmartObject implementation.

File: src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc [hunk 15]
```diff
@@ -0,0 +1,278 @@
...
+
+namespace rc_rpc_plugin_test {
+using namespace rc_rpc_plugin;
+
+class RCHelpersTest : public ::testing::Test {
+ public:
+  RCHelpersTest() {}
+
+  smart_objects::SmartObject genSmartObject(const int& object_number,
+                                            const bool& use_id_key) {
```
[the remark this answers is not in the document]
Comment (YarikMamykin) [reply src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_helpers_test.cc]: @LuxoftAKutsan , fixed in 1e132d46ee68699bb721ed29530f4162bce08dd8
