### PR TITLE
Fix RPC response in case filename contains forbidden symbols

### LINKED ISSUE #975: [TV] SDL must respond with INVALID_DATA on SystemRequest that uploads a file containing `../` sequences
## Occurrence
Always.

## Preconditions
1. SDL and HMI are started.
2. App is registered.
3. App HMIlevel=FULL.
4. Save any file to sdcard on mobile.

## Steps to reproduce
1. Select SystemRequest in "Send Message" (SPT).
2. Use for request file from precondition, specify file name - /test.
3. Set request type - PROPRIETARY.
4. Send SystemRequest.

## Actual result
SUCCESS is returned to SystemRequest.

## Expected result
SDL responses with INVALID DATA result code.

# Environment
SDL repo: https://github.com/smartdevicelink/sdl_core.git.
SDL branch: master.
SDL commit: a6c32b4.
HMI: https://github.com/LuxoftSDL/sdl_hmi: 01cb5b49883ed6288e34fcf7db24fd0439d08312.
OS: Ubuntu 14.04 LTS.

# Attachments
[att_issue#975.zip](https://github.com/smartdevicelink/sdl_core/files/575840/att_issue.975.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
According to requirements SDL must respond with `INVALID_DATA` to RPC request, which contains some filename param, which contains '/' symbol. The main idea here is to prevent access to files outside SDL working directory using such RPCs.

In this pull request:
- Added `IsFileNameValid` function to check filename symbols
- Added checking filename param for: `DeleteFile`, `PutFile`, `SetAppIcon`, `SystemRequest`

Related PR from another branch: #1373 
Fixes #975

### CODE REVIEW

**Comment by AKalinich-Luxoft** [comment]
@AByzhynar, @LitvinenkoIra, @LuxoftAKutsan, @dev-gh please review

File: src/components/application_manager/include/application_manager/commands/command_request_impl.h [hunk 1]
```diff
@@ -212,6 +212,14 @@ class CommandRequestImpl : public CommandImpl,
   bool HasDisallowedParams() const;
 
   /**
+   * @brief Checks if file name contains invalid symbols e.g. '/'
```
Comment (AByzhynar) [inline src/components/application_manager/include/application_manager/commands/command_request_impl.h]: @AKalinich-Luxoft Is this check for any invalid symbols or only '/'?

Comment (AByzhynar) [inline src/components/application_manager/include/application_manager/commands/command_request_impl.h]: @AKalinich-Luxoft Pay attemtion to `IsFileNamePortable(..)` function from Profile. Probably you can move it out to utils and make it available for all needed components. Or write similar function .

Comment (AKalinich-Luxoft) [inline src/components/application_manager/include/application_manager/commands/command_request_impl.h]: @AByzhynar according to [Wikipedia](https://en.wikipedia.org/wiki/Filename) the only prohibited character in file names for Unix-like systems is '/' so this function seems correct

Comment (AByzhynar) [inline src/components/application_manager/include/application_manager/commands/command_request_impl.h]: @AKalinich-Luxoft Ok. Thank you.

File: src/components/application_manager/include/application_manager/commands/command_request_impl.h [hunk 2]
```diff
@@ -212,6 +212,14 @@ class CommandRequestImpl : public CommandImpl,
...
+   * @param file_name file name to check
+   * @return true if file name does not contain any invalid symbol otherwise
+   * returns false
+   */
+  bool IsFileNameValid(const std::string& file_name) const;
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/include/application_manager/commands/command_request_impl.h]: @AKalinich-Luxoft looks like it is utils function isn't it?

Comment (AKalinich-Luxoft) [inline src/components/application_manager/include/application_manager/commands/command_request_impl.h]: @LuxoftAKutsan yes, it is. Was moved to `file_system` utils functions. See https://github.com/smartdevicelink/sdl_core/pull/1613/commits/f050b8f14ed2f3e048d7a4a0b2f1c424255649ac

File: src/components/utils/src/file_system.cc [hunk 3]
```diff
@@ -222,6 +222,10 @@ std::string file_system::GetAbsolutePath(const std::string& path) {
   return std::string(abs_path);
 }
 
+bool file_system::IsFileNameValid(const std::string& file_name) {
+  return file_name.end() == std::find(file_name.begin(), file_name.end(), '/');
```
Comment (JackLivio) [inline src/components/utils/src/file_system.cc]: Shouldn't the find be searching for '../' and not '/'?

Comment (AKalinich-Luxoft) [inline src/components/utils/src/file_system.cc]: @JackLivio we should check all possible cases with the file name which contains some path in order to block the app access for any folder beyond SDL storage folder. Getting access to external folder could be achieved in few ways:
- By specifying '../' in filename
- Putting some softlink in SDL folder which will link to some external folder and then specifying './someLink/filename'

Also we have requirement to check exactly '/' symbol in filenames, so '../' is just one of cases which should be covered.
