### PR TITLE
Fix PTU notifications order

### LINKED ISSUE #3042: Sometimes SDL rejects requests for custom VehicleData
### Bug Report
In [SDL-0173 Read Generic Network Signal data](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0173-Read-Generic-Network-Signal-data.md) it was introduced a possibility for SDL to handle custom `VehicleData` parameters.
These parameters can be defined through standard PTU process.
*Sometimes* SDL is unable to proceed with just set custom parameters.  

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile, register App
2. Perform PTU with setting of a new custom `VehicleData` parameter(s)
3. Send `SubscribeVehicleData` with subscription to one (or more) new parameter(s)

##### Expected Behavior
SDL proceed with subscription successfully

##### Observed Behavior
SDL rejects request with `INVALID_DATA` result code

##### OS & Version Information
* OS/Version: Ubuntu 16.04 amd64
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (3ea6b1a)
* ATF: https://github.com/smartdevicelink/sdl_atf/tree/develop
* Testing Against: ATF (script, report and logs are below)

##### Test Case, Sample Code, and / or Example App
 - Script: [GenericNetworkSignalData/001_SubscribeVehicleData_with_PTU_with_VDitems](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/API/VehicleData/GenericNetworkSignalData/001_SubscribeVehicleData_with_PTU_with_VDitems.lua)
 - Logs: [Issue_3042.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3632883/Issue_3042.tar.gz)

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #3042 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Covered by ATF test scripts

### Summary
The existing order of actions were changed to make it more obvious for external systems like
HMI and mobile apps. The main concern was that SDL is sending `OnStatusUpdate(UP_TO_DATE)` when policy table update was not actually done. The order of actions done during PTU was updated
to perform sending of `UP_TO_DATE` only when all policy actions were actually done.

### Tasks Remaining:
- [x] [Fix failed unit tests]
- [x] [Perform full regression testing]

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 1]
```diff
@@ -1106,15 +1106,21 @@ bool PolicyHandler::ReceiveMessageFromSDK(const std::string& file,
...
+      load_pt_result == PolicyManager::LoadPtResult::kSuccess;
+  OnPTUFinished(is_ptu_successful);
+
+  if (is_ptu_successful) {
     LOG4CXX_INFO(logger_, "PTU was successful.");
     policy_manager_->CleanupUnpairedDevices();
-    int32_t correlation_id = application_manager_.GetNextHMICorrelationID();
-
     SetDaysAfterEpoch();
+    policy_manager_->OnPTUFinished(load_pt_result);
```
Comment (mkorniichuk) [inline src/components/application_manager/src/policies/policy_handler.cc]: @AKalinich-Luxoft is there any reason, for not doing this once before or after `if (is_ptu_successful)`?

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 2]
```diff
@@ -1106,15 +1106,21 @@ bool PolicyHandler::ReceiveMessageFromSDK(const std::string& file,
                                           const BinaryMessage& pt_string) {
   POLICY_LIB_CHECK(false);
 
-  bool ret = policy_manager_->LoadPT(file, pt_string);
-  LOG4CXX_INFO(logger_, "Policy table is saved: " << std::boolalpha << ret);
-  if (ret) {
+  auto load_pt_result = policy_manager_->LoadPT(file, pt_string);
```
Comment (mked-luxoft) [inline src/components/application_manager/src/policies/policy_handler.cc]: i think `load_pt_result` should be const

File: src/components/include/policy/policy_external/policy/policy_manager.h [hunk 3]
```diff
@@ -85,8 +88,10 @@ class PolicyManager : public usage_statistics::StatisticsManager,
    * @param pt_content PTU as binary string
    * @return true if successfully
```
Comment (mked-luxoft) [inline src/components/include/policy/policy_external/policy/policy_manager.h]: as i undrestand, this method is no longer returning `bool`

File: src/components/policy/policy_external/src/policy_manager_impl.cc [hunk 4]
```diff
@@ -467,94 +466,109 @@ bool PolicyManagerImpl::LoadPT(const std::string& file,
...
+void PolicyManagerImpl::OnPTUFinished(const LoadPtResult ptu_result) {
+  LOG4CXX_AUTO_TRACE(logger_);
+
+  if (LoadPtResult::kWrongPtReceived == ptu_result) {
+    LOG4CXX_DEBUG(logger_, "Wrong PT was received");
+    update_status_manager_.OnWrongUpdateReceived();
+    return;
+  }
+
+  update_status_manager_.OnValidUpdateReceived();
```
Comment (mked-luxoft) [inline src/components/policy/policy_external/src/policy_manager_impl.cc]: Do we really need to call this if result is `LoadPtResult::kNewPtRequired` ? Since we'll schedule next PT update right away in that case

File: src/components/application_manager/src/policies/policy_handler.cc (hunk 1 above)
Comment (AKalinich-Luxoft) [reply src/components/application_manager/src/policies/policy_handler.cc]: @mkorniichuk yes. The main idea of this PR was to provide a strict order of policy actions and send UP_TO_DATE only when all policy related actions were done.
This is the best place for `policy_manager_->OnPTUFinished` as such functions as `CleanupUnpairedDevices` and `SetDaysAfterEpoch` are still affecting policy database.

File: src/components/policy/policy_external/src/policy_manager_impl.cc (hunk 4 above)
Comment (AKalinich-Luxoft) [reply src/components/policy/policy_external/src/policy_manager_impl.cc]: @mked-luxoft yes, as SDL should send UP_TO_DATE before starting new PT interation. The same logic was in `LoadPT` before my fix

File: src/components/application_manager/src/policies/policy_handler.cc (hunk 2 above)
Comment (AKalinich-Luxoft) [reply src/components/application_manager/src/policies/policy_handler.cc]: @mked-luxoft fixed in https://github.com/smartdevicelink/sdl_core/commit/d6e668e24d4444f10daf55c953b21af69c1be690

File: src/components/include/policy/policy_external/policy/policy_manager.h (hunk 3 above)
Comment (AKalinich-Luxoft) [reply src/components/include/policy/policy_external/policy/policy_manager.h]: @mked-luxoft good point. Description was updated in https://github.com/smartdevicelink/sdl_core/commit/d6e668e24d4444f10daf55c953b21af69c1be690

File: src/components/application_manager/test/policy_handler_test.cc [hunk 5]
```diff
@@ -468,7 +471,10 @@ TEST_F(PolicyHandlerTest, ReceiveMessageFromSDK) {
   EXPECT_CALL(app_manager_, GetNextHMICorrelationID());
   EXPECT_CALL(mock_message_helper_, CreateGetVehicleDataRequest(_, _, _));
   EXPECT_CALL(*mock_policy_manager_, PTUpdatedAt(_, _));
-  EXPECT_CALL(*mock_policy_manager_, LoadPT("", msg)).WillOnce(Return(true));
+  EXPECT_CALL(*mock_policy_manager_, LoadPT("", msg))
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/test/policy_handler_test.cc]: @AKalinich-Luxoft why do we expect LoadPT with empty string?

Comment (LuxoftAKutsan) [inline src/components/application_manager/test/policy_handler_test.cc]: @AKalinich-Luxoft why do we expect LoadPT with empty string?

File: src/components/policy/policy_external/src/policy_manager_impl.cc [hunk 6]
```diff
@@ -467,94 +466,109 @@ bool PolicyManagerImpl::LoadPT(const std::string& file,
...
   }
 
-  update_status_manager_.OnValidUpdateReceived();
   cache_->SaveUpdateRequired(false);
+  sync_primitives::AutoLock lock(apps_registration_lock_);
 
-  {
-    sync_primitives::AutoLock lock(apps_registration_lock_);
+  // Get current DB data, since it could be updated during awaiting of PTU
+  std::shared_ptr<policy_table::Table> policy_table_snapshot =
```
Comment (LuxoftAKutsan) [inline src/components/policy/policy_external/src/policy_manager_impl.cc]: auto

File: src/components/application_manager/test/policy_handler_test.cc (hunk 5 above)
Comment (AKalinich-Luxoft) [reply src/components/application_manager/test/policy_handler_test.cc]: @LuxoftAKutsan it's a nature of this test case - we are passing empty string in `ReceiveMessageFromSDK` and expecting `LoadPT` to be called with the same argument

Comment (AKalinich-Luxoft) [reply src/components/application_manager/test/policy_handler_test.cc]: @LuxoftAKutsan it's a nature of this test case - we are passing empty string in `ReceiveMessageFromSDK` and expecting `LoadPT` to be called with the same argument

File: src/components/policy/policy_external/src/policy_manager_impl.cc (hunk 6 above)
Comment (AKalinich-Luxoft) [reply src/components/policy/policy_external/src/policy_manager_impl.cc]: @LuxoftAKutsan fixed in https://github.com/smartdevicelink/sdl_core/pull/3051/commits/cd1b519dd9acd9a5e3ad93a849aa3d98076556d3

**Comment by AKalinich-Luxoft** [comment]
@theresalech PR is ready for Livio team review

File: src/components/policy/policy_external/src/policy_manager_impl.cc [hunk 7]
```diff
@@ -1871,9 +1903,11 @@ std::string PolicyManagerImpl::ForcePTExchange() {
...
 void policy::PolicyManagerImpl::StopRetrySequence() {
   LOG4CXX_AUTO_TRACE(logger_);
-  if (update_status_manager_.IsUpdateRequired()) {
-    ResetRetrySequence(ResetRetryCountType::kResetWithStatusUpdate);
-  }
+
+  const ResetRetryCountType reset_type =
+      cache_->UpdateRequired() ? ResetRetryCountType::kResetWithStatusUpdate
+                               : ResetRetryCountType::kResetInternally;
+  ResetRetrySequence(reset_type);
```
Comment (jacobkeeler) [inline src/components/policy/policy_external/src/policy_manager_impl.cc]: Also irrelevant, what was the purpose of this change?

Comment (AKalinich-Luxoft) [reply src/components/policy/policy_external/src/policy_manager_impl.cc]: @jacobkeeler unfortunately, it is a part of fix. Without those changes we noticed that the following two scripts are failing:
```
./test_scripts/Policies/App_Permissions/024_ATF_APP_UNAUTHORIZED_If_Failed_Nickname_Validation_After_PTU.lua
./test_scripts/Policies/Validation_of_PolicyTables/245_ATF_preloaded_pt_parameter_trigger_in_local_pt.lua
``
The issue is that in some cases SDL is not sending `UP_TO_DATE` after `UPDATING`.
For example there was an app registered, then PTU in progress (UPDATING) which revokes app permissions, then SDL unregisters this unauthorized app and invokes `StopRetrySequence()` which checks `IsUpdateRequired()` in `UpdateStatusManager` and it returns `true` for UPDATING status, so `ResetRetrySequence` -> `OnResetRetrySequence` will change status to `UPDATE_NEED`, however PTU was finished successfully (`OnValidUpdateReceived()` will be called later).
By that reason, its more reliable to check `update_required` flag in cache manager, which is set right after valid PT update was received. That's why these changes were done in both policy managers.

Please let me know if you need more details about that

File: src/components/policy/policy_regular/src/policy_manager_impl.cc [hunk 8]
```diff
@@ -1227,9 +1261,10 @@ void PolicyManagerImpl::StopRetrySequence() {
     timer_retry_sequence_.Stop();
   }
 
-  if (update_status_manager_.IsUpdateRequired()) {
-    ResetRetrySequence(ResetRetryCountType::kResetWithStatusUpdate);
-  }
+  const ResetRetryCountType reset_type =
+      cache_->UpdateRequired() ? ResetRetryCountType::kResetWithStatusUpdate
+                               : ResetRetryCountType::kResetInternally;
+  ResetRetrySequence(reset_type);
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/policy/policy_regular/src/policy_manager_impl.cc]: @jacobkeeler same comment as below

File: src/components/policy/policy_external/include/policy/policy_manager_impl.h [hunk 9]
```diff
@@ -860,7 +862,6 @@ class PolicyManagerImpl : public PolicyManager {
   inline void SetSendOnUpdateFlags(const bool send_on_update_sent_out,
                                    const bool wrong_ptu_update_received) {
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/policy/policy_external/include/policy/policy_manager_impl.h]: @jacobkeeler good point. Fixed in https://github.com/smartdevicelink/sdl_core/pull/3051/commits/ff19860ee7b528a3e7d3cf307fa1fb465b15bc89

File: src/components/policy/policy_external/src/policy_manager_impl.cc (hunk 7 above)
Comment (jacobkeeler) [reply src/components/policy/policy_external/src/policy_manager_impl.cc]: Hmmm, well is there a reason to call `ResetRetrySequence(ResetRetryCountType::kResetInternally)` if `UpdateRequired` is false?

It seems to me like the change should just be made to the existing `if` statement, rather than adding this new conditional

Comment (jacobkeeler) [reply src/components/policy/policy_external/src/policy_manager_impl.cc]: @AKalinich-Luxoft Hmmm, well is there a reason to call `ResetRetrySequence(kResetInternally)` if `UpdateRequired()` is false?

It seems to me like the change should just be made to the existing `if` statement, rather than adding this new conditional:
```cpp
  if (cache_->UpdateRequired()) {
    ResetRetrySequence(ResetRetryCountType::kResetWithStatusUpdate);
  }
```

Comment (AKalinich-Luxoft) [reply src/components/policy/policy_external/src/policy_manager_impl.cc]: @jacobkeeler hmm, you are right. `kResetInternally` will be called indirectly when PTU is finished with `UP_TO_DATE`. Updated as you suggested in https://github.com/smartdevicelink/sdl_core/pull/3051/commits/f70d036ce4f3e618182ee2e2cf1b0badd38816c8
