### PR TITLE
Fix/Add Startup PTU trigger check

### LINKED ISSUE #3279: SDL does not send BC.PolicyUpdate to HMI if no apps are registered
### Bug Report
Currently, if there are no registered apps, triggering a PTU results in the HMI sending a `BasicCommunication.OnSystemRequest` with `fileName: null`. 

The PTS filename is never set in the HMI because SDL does not send a `BasicCommunication.PolicyUpdate` request(which contains the PTS path) to the HMI. This prevents us from being able to use the HMI vehicle modem to handle the PTU if no apps are registered.

##### Reproduction Steps
Using the sdl hmi with external proprietary checked:
1. Build core with external proprietary
2. Start the policy server
3. Modify the `0x07` endpoint in the PT
4. Register app, successful PTU should occur
5. Unregister app
6. Change the kilometers to 5000 to trigger a PTU

##### Expected Behavior
1. SDL sends a `BasicCommunication.PolicyUpdate` request to the HMI.
2. The HMI sends a `BasicCommunication.OnSystemRequest(PROPRIETARY)` notification to SDL with a valid PTS `fileName`.

##### Observed Behavior
1. SDL does NOT send a `BasicCommunication.PolicyUpdate` request to the HMI.
2. The HMI sends a `BasicCommunication.OnSystemRequest(PROPRIETARY)` notification to SDL with `fileName: null`.

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: origin/develop (https://github.com/smartdevicelink/sdl_core/commit/94f92bb7eb440c0ee878896b6281f38009d64094)
* Testing Against: Test Suite

### PR DESCRIPTION
**Pull request by ShobhitAd**
Fixes #3279 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
ATF Test and manual tests

### Summary
Currently, the IgnitionCycles and Days PTU triggers are not checked in the regular policy mode when SDL starts.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 1]
```diff
@@ -787,6 +787,12 @@ void PolicyHandler::OnSystemRequestReceived() const {
   policy_manager_->ResetTimeout();
 }
 
+void PolicyHandler::TriggerPTUIfRequired() {
+#ifndef EXTERNAL_PROPRIETARY_MODE
+  policy_manager_->TriggerPTUIfRequired();
```
Comment (iCollin) [inline src/components/application_manager/src/policies/policy_handler.cc:792]: I think the policy mode check should go where the call is originally triggered, at the end of `ApplicationManagerImpl::OnHMIStartedCooperation`

Comment (ShobhitAd) [reply src/components/application_manager/src/policies/policy_handler.cc]: The `TriggerPTUIfRequired` function is not implemented for external policies. In this case, it would be fine if I have the `EXTERNAL_POLICY` flag check in OnHMIStartedCooperation but If I had to use it somewhere else I’d have to add the policy flag check for each call. It might be neater for this to be handled in the policy handler. 

For now I think we could  add a note in the policy_handler function brief stating that its only implemented for regular policies at the moment

Comment (ShobhitAd) [reply src/components/application_manager/src/policies/policy_handler.cc]: Made the change in https://github.com/smartdevicelink/sdl_core/pull/3363/commits/454e5fbda47c6a7c0c14c8d8206354a33e1a3685
