### PR TITLE
Fix sdl crash when policies disabled

### LINKED ISSUE #3285: SDL stops responding in case it has been started with EnablePolicy=false
### Bug Report
SDL stops responding in case it has been started with EnablePolicy=false

##### Reproduction Steps
1. `EnablePolicy` value is set to `false` in `ini` file
2. Start SDL
3. Connect mobile device and try to register app

##### Expected Behavior
SDL connects the device and registers the app successful

##### Observed Behavior
SDL disconnects the device after the connection and stops responding

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/3dcc409766b49f9914963a5c7b2ef0c0dc5fddc8
* ATF: develop
* Test script: https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_6/842_App_does_not_activate_when_policies_are_disabled.lua

##### Logs:
[Script_1.zip](https://github.com/smartdevicelink/sdl_core/files/4317796/Script_1.zip)

### PR DESCRIPTION
**Pull request by YarikMamykin**
Fixes #3285 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
ATF and unit testing

### Summary
When `EnablePolicy=false` inside smartdevicelink.ini file pointer to `PolicyManager` inside of `PolicyHandler` class is not set.

This way when `PushAppIdToPTUQueue` method was called there were no check for `PolicyManager` pointer validity, and so core crash happened on `policy_manager_->UpdatePTUReadyAppsCount()` call. So check for enabled policy added.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 1]
```diff
@@ -470,7 +470,7 @@ void PolicyHandler::PushAppIdToPTUQueue(const uint32_t app_id) {
   LOG4CXX_AUTO_TRACE(logger_);
   sync_primitives::AutoLock lock(app_id_queue_lock_);
   const auto result = applications_ptu_queue_.insert(app_id);
-  if (result.second) {
+  if (result.second && PolicyEnabled()) {
```
Comment (ydementieiev) [inline src/components/application_manager/src/policies/policy_handler.cc]: @YarikMamykin I think you don't need check `PolicyEnabled()` just only add `POLICY_LIB_CHECK_VOID();` instead and also maybe need add verification to `OnAddedNewApplicationToAppList` and `PopAppIdFromPTUQueue` functions?  Can you check this one?

Comment (YarikMamykin) [reply src/components/application_manager/src/policies/policy_handler.cc]: @ydementieiev I checked `PopAppIdFromPTUQueue` - this one executed only with enabled policies and `OnAddedNewApplicationToAppList` contains `PushAppIdToPTUQueue` only that is fixed by this PR.

Comment (YarikMamykin) [reply src/components/application_manager/src/policies/policy_handler.cc]: @ydementieiev POLICY_LIB_CHECK_VOID macro added in https://github.com/smartdevicelink/sdl_core/pull/3292/commits/0b561fa7c66d903bafc639f1908fea37ad5315d9

Comment (YarikMamykin) [reply src/components/application_manager/src/policies/policy_handler.cc]: @ydementieiev https://github.com/smartdevicelink/sdl_core/pull/3292/commits/c0ab36d8248e296f98c81b75500154f4cbfb332b

File: src/components/application_manager/test/policy_handler_test.cc [hunk 2]
```diff
@@ -3126,6 +3126,22 @@ TEST_F(PolicyHandlerTest, GetEnabledLocalApps_SUCCESS) {
   EXPECT_EQ(enabled_local_apps, policy_handler_.GetEnabledLocalApps());
 }
 
+TEST_F(PolicyHandlerTest, PushAppIdToPTUQueue_PolicyEnabled_SUCCESS) {
+  ChangePolicyManagerToMock();
+  EXPECT_CALL(*mock_policy_manager_, UpdatePTUReadyAppsCount(_));
```
Comment (AByzhynar) [inline src/components/application_manager/test/policy_handler_test.cc]: @YarikMamykin Why don't we check apps count?

Comment (YarikMamykin) [reply src/components/application_manager/test/policy_handler_test.cc]: @AByzhynar added check in https://github.com/smartdevicelink/sdl_core/pull/3292/commits/73964199f3149237d32109dbd2f17a3e8e56a8dd

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 3]
```diff
@@ -1661,6 +1662,7 @@ DeviceConsent PolicyHandler::GetUserConsentForDevice(
 }
 
 Json::Value PolicyHandler::GetPolicyTableData() const {
+  POLICY_LIB_CHECK(Json::Value());
```
Comment (AByzhynar) [inline src/components/application_manager/src/policies/policy_handler.cc]: @YarikMamykin If you decided to use MACRO - make it more clear. 
I mean make POLICY_LIB_CHECK() for void functions and POLICY_LIB_CHECK_OR_RETURN() for non-void ones. 
Ii is not obvious in the code why do you pass parameters of different types to the macro.

File: src/components/application_manager/test/policy_handler_test.cc [hunk 4]
```diff
@@ -3126,6 +3126,95 @@ TEST_F(PolicyHandlerTest, GetEnabledLocalApps_SUCCESS) {
...
+  ChangePolicyManagerToMock();
+  const uint32_t expected_apps_count = 1u;
+  EXPECT_CALL(*mock_policy_manager_, UpdatePTUReadyAppsCount(_));
+  policy_handler_.PushAppIdToPTUQueue(kAppId1_);
+  EXPECT_EQ(expected_apps_count,
+            policy_handler_.applications_ptu_queue_.size());
+}
+
+TEST_F(PolicyHandlerTest, PushAppIdToPTUQueue_PolicyDisabled_FAIL) {
+  ChangePolicyManagerToMock();
```
Comment (AByzhynar) [inline src/components/application_manager/test/policy_handler_test.cc]: @YarikMamykin AICS you are calling `ChangePolicyManagerToMock();` in every test case. Is it worth to move it to SetUp() instead of calling in every test case?

File: src/components/application_manager/test/policy_handler_test.cc (hunk 2 above)
Comment (AByzhynar) [reply src/components/application_manager/test/policy_handler_test.cc]: @YarikMamykin Is it possible to check parameter of `UpdatePTUReadyAppsCount(_)` insted of `_` using?

File: src/components/application_manager/src/policies/policy_handler.cc (hunk 3 above)
Comment (YarikMamykin) [reply src/components/application_manager/src/policies/policy_handler.cc]: @AByzhynar reworked in https://github.com/smartdevicelink/sdl_core/pull/3292/commits/f037262a5638e889e9533a5ec17ac10e286176fa

File: src/components/application_manager/test/policy_handler_test.cc (hunk 4 above)
Comment (YarikMamykin) [reply src/components/application_manager/test/policy_handler_test.cc]: @AByzhynar actually not all tests use `ChangePolicyManagerToMock();`. More than that, I gave a shot and tried to move it inside SetUp method and this caused segmentation fault in some tests. So unfortunately it has to stay this way.

File: src/components/application_manager/test/policy_handler_test.cc (hunk 2 above)
Comment (YarikMamykin) [reply src/components/application_manager/test/policy_handler_test.cc]: @AByzhynar done in https://github.com/smartdevicelink/sdl_core/pull/3292/commits/55f94fb5c04ed4edfe064d13dfd0de6d18e53395

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 5]
```diff
@@ -141,7 +141,7 @@ struct HMILevelPredicate
 
 }  // namespace
 
-#define POLICY_LIB_CHECK(return_value)                                      \
+#define POLICY_LIB_CHECK_OR_RETURN(return_value)                            \
```
Comment (IGapchuk) [inline src/components/application_manager/src/policies/policy_handler.cc]: @YarikMamykinI propose to consider to name it like `POLICY_LIB_CHECK_AND_RETURN`. Because you don't check OR return `policy_manager_`. You check it anyway AND return if `policy_manager_` is invalid.

Comment (YarikMamykin) [reply src/components/application_manager/src/policies/policy_handler.cc]: @IGapchuk I don't agree, because return value works only when `policy_manager_` is invalid. So your version is not applicable here.

**Comment by JackLivio** [comment]
@YarikMamykin Let us know when this pr is ready for review :)

**Comment by YarikMamykin** [comment]
@JackLivio this PR is ready for Livio code review.

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 6]
```diff
@@ -2695,7 +2698,7 @@ bool PolicyHandler::CheckHMIType(const std::string& application_id,
                                  mobile_apis::AppHMIType::eType hmi,
                                  const smart_objects::SmartObject* app_types) {
   LOG4CXX_AUTO_TRACE(logger_);
-  POLICY_LIB_CHECK(false);
+  POLICY_LIB_CHECK_OR_RETURN(false);
   std::vector<int> policy_hmi_types;
   bool ret = policy_manager_->GetHMITypes(application_id, &policy_hmi_types);
```
[the remark this answers is not in the document]
Comment (jacobkeeler) [reply src/components/application_manager/src/policies/policy_handler.cc]: missing check in `GetAppPropertiesStatus`

[the remark this answers is not in the document]
Comment (jacobkeeler) [reply src/components/application_manager/src/policies/policy_handler.cc]: missing check in `IsNewApplication`

[the remark this answers is not in the document]
Comment (jacobkeeler) [reply src/components/application_manager/src/policies/policy_handler.cc]: missing check in `OnLocalAppAdded`

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 7]
```diff
@@ -468,6 +468,7 @@ uint32_t PolicyHandler::GetAppIdForSending() const {
 
 void PolicyHandler::PushAppIdToPTUQueue(const uint32_t app_id) {
   LOG4CXX_AUTO_TRACE(logger_);
+  POLICY_LIB_CHECK_VOID();
```
[the remark this answers is not in the document]
Comment (YarikMamykin) [reply src/components/application_manager/src/policies/policy_handler.cc]: @jacobkeeler please take a look at https://github.com/smartdevicelink/sdl_core/pull/3292/commits/d58a0d84e88497bb4822f9a360edf9843ff73964

File: src/components/application_manager/src/policies/policy_handler.cc (hunk 6 above)
[the remark this answers is not in the document]
Comment (YarikMamykin) [reply src/components/application_manager/src/policies/policy_handler.cc]: @jacobkeeler please take a look at https://github.com/smartdevicelink/sdl_core/pull/3292/commits/d58a0d84e88497bb4822f9a360edf9843ff73964
