### PR TITLE
Fix SDL crash on validation of numeric schemas with type overflow

### LINKED ISSUE #3226: SDL crashes when the HMI sends UI.OnTouchEvent with the 'ts' param has a value greater than maxvalue (not valid)
### Bug Report
SDL crashes when the HMI sends UI.OnTouchEvent with the 'ts' param has a value greater than maxvalue (not valid)

##### Reproduction Steps
1. SDL and HMI are started
2. Navi_App is registered and activated
3. OnTouchEventOnlyGroup is allowed by policies
4. HMI sends OnTouchEvent notification with the 'ts' param has a value greater than maxvalue (not valid)

##### Expected Behavior
No Crash should be observed while testing

##### Observed Behavior
SDL crashed while testing

#### OS & Version Information
* OS/Version : Ubuntu 16.04
* SDL Core Version: 
* ATF: develop

[logs.zip](https://github.com/smartdevicelink/sdl_core/files/4148083/logs.zip)

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #3226 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

##### Reproduction Steps
1. SDL and HMI are started
2. Navi_App is registered and activated
3. OnTouchEventOnlyGroup is allowed by policies
4. HMI sends OnTouchEvent notification with the 'ts' param has a value greater than maxvalue (not valid)

##### Expected Behavior
No Crash should be observed while testing

##### Observed Behavior
SDL crashed while testing

### Summary
SDL crashes when the HMI sends UI.OnTouchEvent with the 'ts' param has a value greater than maxvalue.
Was added processing for the case where the SDL gets numbers that go beyond the type limit.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by AKalinich-Luxoft** [comment]
@theresalech This PR is ready for Livio review

**Comment by theresalech** [comment]
@AKalinich-Luxoft , thank you! We will include this in the upcoming release if time allows.

File: src/components/smart_objects/include/smart_objects/number_schema_item.h [hunk 1]
```diff
@@ -157,11 +157,20 @@ errors::eType TNumberSchemaItem<NumberType>::validate(
     report->set_validation_info(validation_info);
     return errors::INVALID_VALUE;
   }
+
   NumberType value(0);
   if (typeid(int32_t) == typeid(value)) {
-    value = utils::SafeStaticCast<int64_t, int32_t>(Object.asInt());
+    if (Object.asInt() > std::numeric_limits<int32_t>::max() ||
+        Object.asInt() < std::numeric_limits<int32_t>::min()) {
```
Comment (jacobkeeler) [inline src/components/smart_objects/include/smart_objects/number_schema_item.h:164]: One issue with this approach, some integer parameters don't have a `maxvalue` param, so those should be able to handle whatever value is sent (barring it being larger that 64 bits, since that is a hard limit).
Something like `cancelID` is currently stored in a 32 bit integer, but has no limitations as far as range. This change would make it so any value larger than 32 bits would be rejected.

To solve this, I think that we should use 64 bits for parameters which are missing either `maxValue` or `minValue`. This would need to be done in the RPC spec parser script. That, combined with this fix, should cover all cases.

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

**Comment by theresalech** [comment]
Hi @AKalinich-Luxoft , can you please review and respond to Jacob's comment? We are looking to complete development for the Core 8.0 release soon, so will need to make progress on this PR quickly in order to ensure its inclusion in the release. Thank you!

**Comment by AKalinich-Luxoft** [comment]
> Hi @AKalinich-Luxoft , can you please review and respond to Jacob's comment? We are looking to complete development for the Core 8.0 release soon, so will need to make progress on this PR quickly in order to ensure its inclusion in the release. Thank you!

@theresalech Luxoft is working on the fix and going to provide extra changes according to Livio comments above.

**Comment by jordynmackool** [comment]
Hi @AKalinich-Luxoft, Livio is going to begin Release candidate prep, starting on 2021-08-30. As mentioned in Theresa's comment above, we will need to make progress on this PR asap for it to be included in the upcoming release. Can you please provide timing on when Luxoft will have this PR ready for Livio review? Thanks!

**Comment by jordynmackool** [comment]
@AKalinich-Luxoft It looks like you have made new commits to this PR, is this ready for Livio review?

**Comment by AKalinich-Luxoft** [comment]
> @AKalinich-Luxoft It looks like you have made new commits to this PR, is this ready for Livio review?

@jordynmackool this PR will be ready for review today. We have all the required changes and just need some time to finalize the regression testing. I will let you know once it is ready for Livio review.

**Comment by AKalinich-Luxoft** [comment]
@jordynmackool regression testing is finished. This PR is ready for Livio review

File: src/components/smart_objects/include/smart_objects/number_schema_item.h (hunk 1 above)
Comment (AKalinich-Luxoft) [reply src/components/smart_objects/include/smart_objects/number_schema_item.h]: @jacobkeeler generator script has been updated in https://github.com/smartdevicelink/sdl_core/pull/3750/commits/2852ac4f1c79432194480c159dfb1a5d55d154fa and https://github.com/smartdevicelink/sdl_core/pull/3750/commits/9891d9398d2bf72c37043c538e3b3eb04e33b8da
Now generator has rules for int/uint 32/64 by analyzing `minValue` and `maxValue` and providing the best fit for each integer in the schema.
Note that schema item itself has been updated to properly reflect all changes from generator.

File: tools/InterfaceGenerator/generator/generators/SmartFactoryBase.py [hunk 2]
```diff
@@ -840,22 +840,36 @@ def _gen_schema_item_decl_code(self, param, member_name, default_value):
...
+                        [[u"uint64_t", param.min_value],
+                         [u"uint64_t", param.max_value],
+                         [u"uint64_t", param.default_value]]))
+            elif (param.min_value is not None and param.min_value >= 0) and (param.max_value is not None and param.max_value < 2 ** 32):
+                code = self._impl_code_integer_item_template.substitute(
+                    type=u"uint32_t",
+                    params=self._gen_schema_item_param_values(
+                        [[u"uint32_t", param.min_value],
+                         [u"uint32_t", param.max_value],
+                         [u"uint32_t", param.default_value]]))
```
Comment (jacobkeeler) [inline tools/InterfaceGenerator/generator/generators/SmartFactoryBase.py:856]:
```suggestion
            if param.min_value is not None and param.min_value >= 0:
                if param.max_value is None or param.max_value >= 2 ** 32:
                    code = self._impl_code_integer_item_template.substitute(
                        type=u"uint64_t",
                        params=self._gen_schema_item_param_values(
                            [[u"uint64_t", param.min_value],
                             [u"uint64_t", param.max_value],
                             [u"uint64_t", param.default_value]]))
                else:
                    code = self._impl_code_integer_item_template.substitute(
                        type=u"uint32_t",
                        params=self._gen_schema_item_param_values(
                            [[u"uint32_t", param.min_value],
                             [u"uint32_t", param.max_value],
                             [u"uint32_t", param.default_value]]))
```
To simplify the expression a bit

File: tools/InterfaceGenerator/generator/generators/SmartFactoryBase.py [hunk 3]
```diff
@@ -840,22 +840,36 @@ def _gen_schema_item_decl_code(self, param, member_name, default_value):
...
+            elif  (param.min_value is not None and param.min_value > -(2 ** 31) and param.min_value < 0) and (param.max_value is not None and param.max_value < 2 ** 31):
```
Comment (jacobkeeler) [inline tools/InterfaceGenerator/generator/generators/SmartFactoryBase.py:857]:
```suggestion
            elif (param.min_value is not None and param.min_value > -(2 ** 31)) and (param.max_value is not None and param.max_value < 2 ** 31):
```
The `param.min_value < 0` is implied if `param.min_value is not None` because of the previous case

File: tools/InterfaceGenerator/generator/generators/SmartFactoryBase.py [hunk 4]
```diff
@@ -840,22 +840,36 @@ def _gen_schema_item_decl_code(self, param, member_name, default_value):
...
                 code = self._impl_code_integer_item_template.substitute(
                     type=u"int32_t",
                     params=self._gen_schema_item_param_values(
-                        [[u"int32_t", param.min_value],
+                        [[u"int32_t", param.min_value],
```
Comment (jacobkeeler) [inline tools/InterfaceGenerator/generator/generators/SmartFactoryBase.py:861]:
```suggestion
                        [[u"int32_t", param.min_value],
```

**Review by jacobkeeler — CHANGES_REQUESTED** [review]
Some suggestions for optimization

File: tools/InterfaceGenerator/generator/generators/SmartFactoryBase.py [hunk 5]
```diff
@@ -840,22 +840,36 @@ def _gen_schema_item_decl_code(self, param, member_name, default_value):
...
+            elif  (param.min_value is not None and param.min_value > -(2 ** 31) and param.min_value < 0) and (param.max_value is not None and param.max_value < 2 ** 31):
                 code = self._impl_code_integer_item_template.substitute(
                     type=u"int32_t",
                     params=self._gen_schema_item_param_values(
-                        [[u"int32_t", param.min_value],
+                        [[u"int32_t", param.min_value], 
                          [u"int32_t", param.max_value],
                          [u"int32_t", param.default_value]]))
-            elif param.max_value < 2 ** 63:
+            elif (param.min_value is None or param.min_value > -(2 ** 63)) and (param.max_value is None or param.max_value < 2 ** 63):
```
Comment (jacobkeeler) [inline tools/InterfaceGenerator/generator/generators/SmartFactoryBase.py:864]:
```suggestion
            elif (param.min_value is None or param.min_value > -(2 ** 63)) and (param.max_value is None or param.max_value <= 2 ** 63):
```
Same minor logic error here

File: tools/InterfaceGenerator/generator/generators/SmartFactoryBase.py (hunk 2 above)
Comment (AKalinich-Luxoft) [reply tools/InterfaceGenerator/generator/generators/SmartFactoryBase.py]: @jacobkeeler fixed in https://github.com/smartdevicelink/sdl_core/pull/3750/commits/4e8df45491863d74a54320049c9cf671bf1baaf4

File: tools/InterfaceGenerator/generator/generators/SmartFactoryBase.py (hunk 3 above)
Comment (AKalinich-Luxoft) [reply tools/InterfaceGenerator/generator/generators/SmartFactoryBase.py]: @jacobkeeler fixed in https://github.com/smartdevicelink/sdl_core/pull/3750/commits/24fdeb3a0befd2835936e0ae973c568c80a39a6b

File: tools/InterfaceGenerator/generator/generators/SmartFactoryBase.py (hunk 4 above)
Comment (AKalinich-Luxoft) [reply tools/InterfaceGenerator/generator/generators/SmartFactoryBase.py]: @jacobkeeler fixed in https://github.com/smartdevicelink/sdl_core/pull/3750/commits/24fdeb3a0befd2835936e0ae973c568c80a39a6b

File: tools/InterfaceGenerator/generator/generators/SmartFactoryBase.py (hunk 5 above)
Comment (AKalinich-Luxoft) [reply tools/InterfaceGenerator/generator/generators/SmartFactoryBase.py]: @jacobkeeler fixed in https://github.com/smartdevicelink/sdl_core/pull/3750/commits/24fdeb3a0befd2835936e0ae973c568c80a39a6b

File: src/components/smart_objects/include/smart_objects/number_schema_item.h [hunk 6]
```diff
@@ -157,11 +158,20 @@ errors::eType TNumberSchemaItem<NumberType>::validate(
     report->set_validation_info(validation_info);
     return errors::INVALID_VALUE;
   }
+
   NumberType value(0);
   if (typeid(int32_t) == typeid(value)) {
-    value = utils::SafeStaticCast<int64_t, int32_t>(Object.asInt());
+    if (Object.asInt() < std::numeric_limits<int32_t>::min() ||
+        Object.asInt() > std::numeric_limits<int32_t>::max()) {
+      return errors::OUT_OF_RANGE;
```
Comment (jacobkeeler) [inline src/components/smart_objects/include/smart_objects/number_schema_item.h:166]:
```suggestion 
      std::string validation_info = "Value out of range";
      report->set_validation_info(validation_info);
      return errors::OUT_OF_RANGE;
```
Probably best to include error info here

File: src/components/smart_objects/include/smart_objects/number_schema_item.h [hunk 7]
```diff
@@ -157,11 +158,20 @@ errors::eType TNumberSchemaItem<NumberType>::validate(
...
+    }
+    value = Object.asInt();
   } else if (typeid(uint32_t) == typeid(value)) {
-    value = utils::SafeStaticCast<uint64_t, uint32_t>(Object.asUInt());
+    if (Object.asInt() < std::numeric_limits<uint32_t>::min() ||
+        Object.asInt() > std::numeric_limits<uint32_t>::max()) {
+      return errors::OUT_OF_RANGE;
```
Comment (jacobkeeler) [inline src/components/smart_objects/include/smart_objects/number_schema_item.h:172]:
```suggestion
      std::string validation_info = "Value out of range";
      report->set_validation_info(validation_info);
      return errors::OUT_OF_RANGE;
```
Probably best to include error info here

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

File: src/components/smart_objects/include/smart_objects/number_schema_item.h (hunk 6 above)
Comment (AKalinich-Luxoft) [reply src/components/smart_objects/include/smart_objects/number_schema_item.h:169]: @jacobkeeler good point. Fixed in https://github.com/smartdevicelink/sdl_core/pull/3750/commits/e1412cc9e6773f70b999805507dbbcba38150fd0

File: src/components/smart_objects/include/smart_objects/number_schema_item.h (hunk 7 above)
Comment (AKalinich-Luxoft) [reply src/components/smart_objects/include/smart_objects/number_schema_item.h:178]: @jacobkeeler good point. Added in https://github.com/smartdevicelink/sdl_core/pull/3750/commits/e1412cc9e6773f70b999805507dbbcba38150fd0

**Review by jacobkeeler — APPROVED** [review]
