### PR TITLE
Re-order rai logic for plugins

### LINKED ISSUE #3172: CCB: Fix SIGSEGV Crash subscribed_data
### Bug Report
SmartDeviceLink crash with SIGSEGV

### Detailed analysis:
unprotected access to the VehicleInfoAppExtension::subscribed_data from different threads

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile
2. Register app
3. Perform multiple RPC scenarios and send OnVehicleDataNotification
4. Observe behavior

##### Expected Behavior
SDL should not crash

##### Observed Behavior
SDL crashed
[bt.txt](https://github.com/smartdevicelink/sdl_core/files/3932241/bt.txt)

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

### PR DESCRIPTION
**Pull request by JackLivio**
Fixes #3172 #3162 

This PR is **Ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Send on vehicle data notification at same time app registers. Core should not crash.

### Summary
Moves the call to add the newly registered app to the applications list later in the registration process. This ensures that an app has all of its necessary plugins added before it is accessible by the applications accessor.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/include/application_manager/application_manager.h [hunk 1]
```diff
@@ -558,6 +558,9 @@ class ApplicationManager {
       const std::shared_ptr<smart_objects::SmartObject>&
           request_for_registration) = 0;
 
+  virtual void FinalizeAppRegistration(ApplicationSharedPtr application,
```
Comment (LuxoftAKutsan) [inline src/components/include/application_manager/application_manager.h:561]: Would be nice to have doxygen description

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/register_app_interface_request.cc [hunk 2]
```diff
@@ -742,6 +742,13 @@ void RegisterAppInterfaceRequest::Run() {
   SetupAppDeviceInfo(application);
   auto status_notifier = AddApplicationDataToPolicy(application);
 
+  auto on_app_registered = [application](plugin_manager::RPCPlugin& plugin) {
+    plugin.OnApplicationEvent(plugin_manager::kApplicationRegistered,
+                              application);
+  };
+  application_manager_.ApplyFunctorForEachPlugin(on_app_registered);
```
Comment (LuxoftAKutsan) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/register_app_interface_request.cc:749]: In this case it is important to remember that when the plugin received `kApplicationRegistered` event, the application is not finally registered. I would add this as a comment in the `kApplicationRegistered` enum

**Review by LuxoftAKutsan — APPROVED** [review]

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/register_app_interface_request.cc (hunk 2 above)
Comment (JackLivio) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/register_app_interface_request.cc:749]: Noting that this placement is the most important part of the change. This event needed to happen before an app was added to the applications accessor in the app manager.

**Review by jacobkeeler — APPROVED** [review]
