### PR TITLE
Fix Policy Table validation in case group subsection is empty/invalid

### LINKED ISSUE #973: [Policies] PT is considered as valid with no items in "groups" sub-section from "default"
## Occurrence
Always

## Preconditions
Erase items of "group" from "default" of sdl_preloaded_pt.json.

## Steps to reproduce
Start SDL.

## Actual result
SDL continue running.

## Expected result
PoliciesManager must consider Preloaded PolicyTable as invalid in case "groups" sub-section in "default" section has empty value, log error then shut SDL down.

_**Note:**_ the same SDL behavior with missed items in "groups" sub-section from "device", "pre_DataConsent", "app_id".

# Environment
SDL repo: https://github.com/smartdevicelink/sdl_core.git
SDL branch: master
SDL commit: a6c32b4
HMI: https://github.com/LuxoftSDL/sdl_hmi: 01cb5b49883ed6288e34fcf7db24fd0439d08312
OS: Ubuntu 14.04 LTS

# Attachments
[att_issue#973.zip](https://github.com/smartdevicelink/sdl_core/files/575738/att_issue.973.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
This issue was already fixed for external policy, but still was not fixed for regular policy.
In this PR was added validation checks for empty and upper bound of group subsection of each section which were missed in regular policies.

Related PR with fixes #1422 
Fixes #973

### CODE REVIEW

**Comment by AKalinich-Luxoft** [comment]
@AByzhynar, @LitvinenkoIra, @LuxoftAKutsan, @dev-gh please review

File: src/components/policy/policy_regular/src/policy_table/validation.cc [hunk 1]
```diff
@@ -115,8 +115,13 @@ bool ApplicationPoliciesSection::Validate() const {
 }
 
 bool ApplicationParams::Validate() const {
+  // Check for empty "groups" sub-sections
+  if (groups.empty()) {
```
Comment (LuxoftAKutsan) [inline src/components/policy/policy_regular/src/policy_table/validation.cc]: @AKalinich-Luxoft can groups empty alowness be checkes with template parameter?

Comment (AKalinich-Luxoft) [inline src/components/policy/policy_regular/src/policy_table/validation.cc]: @LuxoftAKutsan yes, it could be checked with template paramter, however now `groups` have a type  `Array<String<1, 255>, 0, 255> Strings` so if I change this type to `Array<String<1, 255>, 1, 255> Groups;` to check empty alowness, it will lead to a lot of changes in a lot of functions where it used. That's why it's safer just to add this check to `ApplicationParams::Validate()`
