### PR TITLE
Fixed Regular Policy endpoints validation

### LINKED ISSUE #978: [Policies] PM doesn't validate the size of section "default" in "endpoints" of Policy Table
## Occurrence
Always

## Preconditions
Edit sdl_prealoaded_pt.json to have 4 items in "default" section of "endpoints".

## Steps to reproduce
Start SDL.

## Actual result
SDl continue working, no errors in log observed.

## Expected result
Policy Manager must verify that section "default" in Policy Table has value as array from 1 to 3 string elements so PM must log error and shut SDL down.

_**Note:**_ PM also doesn't verify if "default" section of "endpoints" is present in sdl_preloaded_pt.json and size of appId section during PTU(see SmartDeviceLink_endpoints_appId_array_outUpperBound.log).

# Environment
SDL repo: https://github.com/smartdevicelink/sdl_core.git
SDL branch: master
SDL commit: a6c32b4
HMI: https://github.com/LuxoftSDL/sdl_hmi: 01cb5b49883ed6288e34fcf7db24fd0439d08312
OS: Ubuntu 14.04 LTS

# Attachments
[att_issue#978.zip](https://github.com/smartdevicelink/sdl_core/files/575863/att_issue.978.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
For regular policies there was a wrong upper bound for endpoints which allows for each endpoint to have a list with more than 3 items. This issue was fixed for external policies earlier.

The second part of issue is that PM does not check endpoints for containing "default" group. This check was added for all policies flows.

Related PR #1380 
Fixes #978

### CODE REVIEW

**Comment by AKalinich-Luxoft** [comment]
@AByzhynar, @LitvinenkoIra, @LuxoftAKutsan, @dev-gh please review

File: src/components/policy/policy_regular/src/policy_table/validation.cc [hunk 1]
```diff
@@ -136,6 +136,24 @@ bool ModuleConfig::Validate() const {
       return false;
     }
   }
+
+  if (endpoints.empty()) {
```
Comment (LuxoftAKutsan) [inline src/components/policy/policy_regular/src/policy_table/validation.cc]: @AKalinich-Luxoft does this chek mandatory?
isn't template parameter typedef Array<String<10, 255>, 1, 3> URL; does not specify explicitly that length of this array should be greater than 0?

Comment (dev-gh) [inline src/components/policy/policy_regular/src/policy_table/validation.cc]: @LuxoftAKutsan @AKalinich-Luxoft 
It is not mandatory if endpoints.valid() is called.

Comment (AKalinich-Luxoft) [inline src/components/policy/policy_regular/src/policy_table/validation.cc]: @dev-gh @LuxoftAKutsan yes, this check is not mandatory because `endpoints.valid()` is called in `ModuleConfig::is_valid()` before `Validate()` call. Removed in https://github.com/smartdevicelink/sdl_core/pull/1623/commits/259302189fc77a42848144353c9acee9207a667d
