### PR TITLE
Fix core prematurely sends success for delete interaction choice set

### LINKED ISSUE #1833: Core prematurely sends success for DeleteInteractionChoiceSet
### Bug Report
SDL Core deletes UI Interaction Choice set before response received from HMI for successfully deleting the corresponding VR Command. Core also responds success to mobile before knowing the status of the VR.DeleteCommand response. If the VR.DeleteCommand was unsuccessful then the mobile will no longer be synchronized with the state of the HMI.

##### Reproduction Steps
Change HMI to not respond to VR.DeleteCommand
Create Interaction choice set
Delete Interaction choice set

##### Expected Behavior
Mobile should receive error from core (Timed out or generic error)

##### Observed Behavior
Mobile receives success from core.

### PR DESCRIPTION
**Pull request by IGapchuk**
Fixes #1833

This PR is **not ready** for review.

### Risk
This PR makes no API changes.

### Testing Plan
Covered by ATF test.

### Summary
DeleteInteractionChoiceSetRequest was contain implementation, according to that, SDL never not waits for HMI response and sends to Mobile response (success = true, resultCode = "SUCCESS"). This PR provides changes, that remove that implementation. Also, according to requirements, when at-least on of HMI VR_DeleteCommand response will contains any ERROR result code, except WARNINGS, SDL has to send response with that error code and success_result as false. And if on of HMI VR_DeleteCommand response will contains at-least one WARNINGS resulst_code, SDL has to send to Mobile response with WARNINGS and success_result as true.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/delete_interaction_choice_set_request.h [hunk 1]
```diff
@@ -34,6 +34,9 @@
 #ifndef SRC_COMPONENTS_APPLICATION_MANAGER_RPC_PLUGINS_SDL_RPC_PLUGIN_INCLUDE_SDL_RPC_PLUGIN_COMMANDS_MOBILE_DELETE_INTERACTION_CHOICE_SET_REQUEST_H_
 #define SRC_COMPONENTS_APPLICATION_MANAGER_RPC_PLUGINS_SDL_RPC_PLUGIN_INCLUDE_SDL_RPC_PLUGIN_COMMANDS_MOBILE_DELETE_INTERACTION_CHOICE_SET_REQUEST_H_
 
+#include <set>
+#include <stdint.h>
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/delete_interaction_choice_set_request.h]: @IGapchuk use C++ style name `<cstdint>`

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/delete_interaction_choice_set_request.h [hunk 2]
```diff
@@ -43,6 +46,8 @@ namespace app_mngr = application_manager;
 
 namespace commands {
 
+using SentRequestsSet = std::set<std::uint32_t>;
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/delete_interaction_choice_set_request.h]: @IGapchuk why don't you use typedef instead?

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 3]
```diff
@@ -53,9 +55,14 @@ DeleteInteractionChoiceSetRequest::DeleteInteractionChoiceSetRequest(
                          application_manager,
                          rpc_service,
                          hmi_capabilities,
-                         policy_handler) {}
+                         policy_handler)
+    , response_result_code_(
+          hmi_apis::Common_Result::eType::UNSUPPORTED_RESOURCE)
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @IGapchuk not sure that unsupported resource good initial value. Suggest INVALID_ENUM

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 4]
```diff
@@ -53,9 +55,14 @@ DeleteInteractionChoiceSetRequest::DeleteInteractionChoiceSetRequest(
...
+    , response_result_(false) {}
 
-DeleteInteractionChoiceSetRequest::~DeleteInteractionChoiceSetRequest() {}
+DeleteInteractionChoiceSetRequest::~DeleteInteractionChoiceSetRequest() {
+  unsubscribe_from_all_events();
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @IGapchuk please check dtor in base class. As I remember this function is called somewhere there

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 5]
```diff
@@ -87,25 +94,70 @@ void DeleteInteractionChoiceSetRequest::Run() {
...
   return true;
 }
 
+void DeleteInteractionChoiceSetRequest::on_event(
+    const event_engine::Event& event) {
+  using namespace helpers;
+  LOG4CXX_AUTO_TRACE(logger_);
+
+  const smart_objects::SmartObject& message = event.smart_object();
+  response_result_code_ = static_cast<hmi_apis::Common_Result::eType>(
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @IGapchuk you must check `event.id()` to make sure that you are handling event which you are expecting for

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 6]
```diff
@@ -87,25 +94,70 @@ void DeleteInteractionChoiceSetRequest::Run() {
...
+      message[strings::params][hmi_response::code].asInt());
+  const std::uint32_t correlation_id = static_cast<uint32_t>(
+      message[strings::params][strings::correlation_id].asUInt());
+
+  auto found_request =
+      std::find(sent_requests_.begin(), sent_requests_.end(), correlation_id);
+  if (found_request == sent_requests_.end()) {
+    LOG4CXX_DEBUG(logger_,
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @IGapchuk better to use WARNING error level

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 7]
```diff
@@ -87,25 +94,70 @@ void DeleteInteractionChoiceSetRequest::Run() {
...
+                  "Request with " << *found_request
+                                  << " correlation_id is not found.");
+    return;
+  }
+  sent_requests_.erase(found_request);
+
+  if (sent_requests_.empty()) {
+    const mobile_apis::Result::eType result_code =
+        MessageHelper::HMIToMobileResult(response_result_code_);
+    response_result_ =
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @IGapchuk please take a look on `ResponseInfo` class. Maybe you could reuse it in your code.
It also handles success result codes like SUCCESS/WARNINGS via `is_ok` field

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 8]
```diff
@@ -87,25 +94,70 @@ void DeleteInteractionChoiceSetRequest::Run() {
...
+            mobile_apis::Result::WARNINGS);
+    if (response_result_) {
+      ApplicationSharedPtr app =
+          application_manager_.application(connection_key());
+      const uint32_t choice_set_id =
+          (*message_)[strings::msg_params][strings::interaction_choice_set_id]
+              .asUInt();
+      app->RemoveChoiceSet(choice_set_id);
+    }
+    SendResponse(response_result_, result_code);
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @IGapchuk `SendReponse` call should be always in the end of function as after this call command will be destroyed at its members could be invalidated

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 9]
```diff
@@ -87,25 +94,70 @@ void DeleteInteractionChoiceSetRequest::Run() {
...
+        MessageHelper::HMIToMobileResult(response_result_code_);
+    response_result_ =
+        helpers::Compare<mobile_apis::Result::eType, helpers::EQ, helpers::ONE>(
+            result_code,
+            mobile_apis::Result::SUCCESS,
+            mobile_apis::Result::WARNINGS);
+    if (response_result_) {
+      ApplicationSharedPtr app =
+          application_manager_.application(connection_key());
+      const uint32_t choice_set_id =
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @IGapchuk please add check if `app` is valid as this function could return invalid pointer in case application was unexpectedly unregistered

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 10]
```diff
@@ -87,25 +94,70 @@ void DeleteInteractionChoiceSetRequest::Run() {
...
+        "Response sent. Sussess: " << (response_result_ ? "true" : "false")
+                                   << ",error_code: " << result_code);
+  }
+}
+
+void DeleteInteractionChoiceSetRequest::onTimeOut() {
+  LOG4CXX_AUTO_TRACE(logger_);
+
+  {
+    sync_primitives::AutoLock auto_lock(requests_lock_);
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @IGapchuk why this mutex in one place only? You should protect all places where you're accessing `sent_requests_`

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 11]
```diff
@@ -87,25 +94,70 @@ void DeleteInteractionChoiceSetRequest::Run() {
...
+    unsubscribe_from_all_events();
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @IGapchuk most likely it is not needed here as will be called in dtor

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 12]
```diff
@@ -87,25 +94,70 @@ void DeleteInteractionChoiceSetRequest::Run() {
...
+    sent_requests_.clear();
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @IGapchuk this list will be cleared in dtor anyway. I think it is redundant to clear it here if you don't have special reasons for that

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 13]
```diff
@@ -87,25 +94,70 @@ void DeleteInteractionChoiceSetRequest::Run() {
...
+    response_result_ = false;
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @IGapchuk redundant line, as you could just pass `false` in `SendReponse`
And after `SendReponse` call nothing else will be called for this command

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 14]
```diff
@@ -159,7 +211,9 @@ void DeleteInteractionChoiceSetRequest::SendVrDeleteCommand(
   choice_set = &((*choice_set)[strings::choice_set]);
   for (uint32_t i = 0; i < (*choice_set).length(); ++i) {
     msg_params[strings::cmd_id] = (*choice_set)[i][strings::choice_id];
-    SendHMIRequest(hmi_apis::FunctionID::VR_DeleteCommand, &msg_params);
+    const std::uint32_t sent_request = SendHMIRequest(
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @IGapchuk rename to something like `delete_command_corr_id`

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc (hunk 6 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @AKalinich-Luxoft Fixed in e32b004ae4d7e84e153d6b8082cb3c1a800a41ec.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc (hunk 9 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @AKalinich-Luxoft Added in e32b004ae4d7e84e153d6b8082cb3c1a800a41ec.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc (hunk 8 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @AKalinich-Luxoft Replaced in e32b004ae4d7e84e153d6b8082cb3c1a800a41ec.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/delete_interaction_choice_set_request.h (hunk 1 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/delete_interaction_choice_set_request.h]: @AKalinich-Luxoft Changed in e32b004ae4d7e84e153d6b8082cb3c1a800a41ec.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/delete_interaction_choice_set_request.h (hunk 2 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/delete_interaction_choice_set_request.h]: @AKalinich-Luxoft Changed in e32b004ae4d7e84e153d6b8082cb3c1a800a41ec.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc (hunk 3 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @AKalinich-Luxoft Changed in e32b004ae4d7e84e153d6b8082cb3c1a800a41ec.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc (hunk 4 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @AKalinich-Luxoft Deleted in e32b004ae4d7e84e153d6b8082cb3c1a800a41ec.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc (hunk 5 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @AKalinich-Luxoft Checking added in e32b004ae4d7e84e153d6b8082cb3c1a800a41ec.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc (hunk 7 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @AKalinich-Luxoft  I think it will be a redundant information. We need to store only result_code (it should rewriting every received event from HMI)  and result_success (it calculates from every result_code changes) for responding to mobile.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc (hunk 10 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @AKalinich-Luxoft Fixed in e32b004ae4d7e84e153d6b8082cb3c1a800a41ec.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc (hunk 11 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @AKalinich-Luxoft Fixed in e32b004ae4d7e84e153d6b8082cb3c1a800a41ec.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc (hunk 12 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @AKalinich-Luxoft  Deleted in e32b004ae4d7e84e153d6b8082cb3c1a800a41ec.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc (hunk 13 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @AKalinich-Luxoft Deleted in e32b004ae4d7e84e153d6b8082cb3c1a800a41ec,

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc (hunk 14 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @AKalinich-Luxoft Renamed in e32b004ae4d7e84e153d6b8082cb3c1a800a41ec.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/delete_interaction_choice_set_request.h [hunk 15]
```diff
@@ -43,6 +46,8 @@ namespace app_mngr = application_manager;
 
 namespace commands {
 
+typedef std::set<std::uint32_t> SentRequestsSet;
```
Comment (BSolonenko) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/delete_interaction_choice_set_request.h]: @IGapchuk you don't need to specify std for this type

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 16]
```diff
@@ -87,23 +91,47 @@ void DeleteInteractionChoiceSetRequest::Run() {
...
+  if (event.id() == hmi_apis::FunctionID::VR_DeleteCommand) {
+    {
+      sync_primitives::AutoLock auto_lock(requests_lock_);
+      const smart_objects::SmartObject& message = event.smart_object();
+      response_result_code_ = static_cast<hmi_apis::Common_Result::eType>(
+          message[strings::params][hmi_response::code].asInt());
+      const std::uint32_t correlation_id = static_cast<uint32_t>(
+          message[strings::params][strings::correlation_id].asUInt());
+
+      auto found_request = std::find(
```
Comment (BSolonenko) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @IGapchuk use `sent_requests_.find(correlation_id)`

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 17]
```diff
@@ -87,23 +91,47 @@ void DeleteInteractionChoiceSetRequest::Run() {
...
+          sent_requests_.begin(), sent_requests_.end(), correlation_id);
+      if (found_request == sent_requests_.end()) {
```
Comment (BSolonenko) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @IGapchuk please swap arguments

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 18]
```diff
@@ -157,10 +185,46 @@ void DeleteInteractionChoiceSetRequest::SendVrDeleteCommand(
...
+    }
+    const uint32_t choice_set_id =
+        (*message_)[strings::msg_params][strings::interaction_choice_set_id]
+            .asUInt();
+    app->RemoveChoiceSet(choice_set_id);
   }
+
+  LOG4CXX_DEBUG(
+      logger_,
+      "Response sent. Sussess: " << (response_result_ ? "true" : "false")
```
Comment (BSolonenko) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @IGapchuk you can use `std::boolalpha` instead of `(response_result_ ? "true" : "false")`

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 19]
```diff
@@ -31,6 +31,8 @@
  POSSIBILITY OF SUCH DAMAGE.
  */
 
+#include <algorithm>
```
Comment (BSolonenko) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @IGapchuk you do not need this library

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/delete_interaction_choice_set_request.h [hunk 20]
```diff
@@ -34,6 +34,9 @@
 #ifndef SRC_COMPONENTS_APPLICATION_MANAGER_RPC_PLUGINS_SDL_RPC_PLUGIN_INCLUDE_SDL_RPC_PLUGIN_COMMANDS_MOBILE_DELETE_INTERACTION_CHOICE_SET_REQUEST_H_
 #define SRC_COMPONENTS_APPLICATION_MANAGER_RPC_PLUGINS_SDL_RPC_PLUGIN_INCLUDE_SDL_RPC_PLUGIN_COMMANDS_MOBILE_DELETE_INTERACTION_CHOICE_SET_REQUEST_H_
 
+#include <set>
+#include <cstdint>
```
Comment (BSolonenko) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/delete_interaction_choice_set_request.h]: @IGapchuk do you need this library?

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/delete_interaction_choice_set_request.h (hunk 15 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/delete_interaction_choice_set_request.h]: @BSolonenko Deleted in 05a0ac563f1b887f483b99518f63582d86643583.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc (hunk 16 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @BSolonenko Changed in 05a0ac563f1b887f483b99518f63582d86643583.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc (hunk 17 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @BSolonenko Fixed in 05a0ac563f1b887f483b99518f63582d86643583.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc (hunk 18 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @BSolonenko Added in 05a0ac563f1b887f483b99518f63582d86643583.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc (hunk 19 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: If we use std::uint32_t we need this library.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/delete_interaction_choice_set_request.h (hunk 20 above)
Comment (IGapchuk) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/delete_interaction_choice_set_request.h]: If we use std::uint32_t, we have to use this library.

**Comment by IGapchuk** [comment]
The PR's branch was rebased onto the current `sdl_core` `develop` branch (https://github.com/smartdevicelink/sdl_core/commit/fca624f637f0e430f0b4fa932f1933009c277562)

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 21]
```diff
@@ -53,7 +53,9 @@ DeleteInteractionChoiceSetRequest::DeleteInteractionChoiceSetRequest(
                          application_manager,
                          rpc_service,
                          hmi_capabilities,
-                         policy_handler) {}
+                         policy_handler)
+    , response_result_code_(hmi_apis::Common_Result::eType::INVALID_ENUM)
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc:57]: would generic error may be more appropriate for the initial code?

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 22]
```diff
@@ -87,23 +89,46 @@ void DeleteInteractionChoiceSetRequest::Run() {
...
+    const event_engine::Event& event) {
+  using namespace helpers;
+  LOG4CXX_AUTO_TRACE(logger_);
 
-  app->RemoveChoiceSet(choice_set_id);
+  if (event.id() == hmi_apis::FunctionID::VR_DeleteCommand) {
+    {
+      sync_primitives::AutoLock auto_lock(requests_lock_);
+      const smart_objects::SmartObject& message = event.smart_object();
+      response_result_code_ = static_cast<hmi_apis::Common_Result::eType>(
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc:108]: if an error response comes in, but then a successful response comes in, the `response_result_code_` will be success even though an error occurred.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 23]
```diff
@@ -87,23 +89,46 @@ void DeleteInteractionChoiceSetRequest::Run() {
...
-  msg_params[strings::app_id] = app->app_id();
+void DeleteInteractionChoiceSetRequest::on_event(
+    const event_engine::Event& event) {
+  using namespace helpers;
+  LOG4CXX_AUTO_TRACE(logger_);
 
-  app->RemoveChoiceSet(choice_set_id);
+  if (event.id() == hmi_apis::FunctionID::VR_DeleteCommand) {
+    {
+      sync_primitives::AutoLock auto_lock(requests_lock_);
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc:106]: i think it is good practice to lock this lock just immediately before the protected data is accessed, i would move this line immediately above `sent_requests_.find`

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 24]
```diff
@@ -157,12 +182,48 @@ void DeleteInteractionChoiceSetRequest::SendVrDeleteCommand(
...
+      sent_requests_.insert(delte_cmd_hmi_corr_id);
+    }
   }
 }
 
+void DeleteInteractionChoiceSetRequest::
+    SendDeleteInteractionChoiceSetResponse() {
+  const mobile_apis::Result::eType result_code =
+      MessageHelper::HMIToMobileResult(response_result_code_);
+  response_result_ =
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc:200]: this compare should be `IsHMIResultSuccess(response_result_code_)`, perhaps this should be done on every response like so (all responses should be considered):

in on_event:
response_result_ = response_result_ && IsHMIResultSuccess

**Review by iCollin — COMMENTED** [review]
@IGapchuk Hello,

Would it be possible to rebase this branch on the latest develop? The logger and FindChoiceSet references need to be updated.

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 25]
```diff
@@ -157,12 +182,48 @@ void DeleteInteractionChoiceSetRequest::SendVrDeleteCommand(
...
+        (*message_)[strings::msg_params][strings::interaction_choice_set_id]
+            .asUInt();
+    app->RemoveChoiceSet(choice_set_id);
+  }
+
+  LOG4CXX_DEBUG(logger_,
+                "Response sent. Result code: " << result_code
+                                               << " sussess: " << std::boolalpha
+                                               << result_code);
+  SendResponse(response_result_, result_code);
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc:224]: i understand only doing `app.RemoveChoiceSet` when the result code is success or warnings, but i think this result bool should use `PrepareResultForMobileResponse`

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 26]
```diff
@@ -89,23 +90,44 @@ void DeleteInteractionChoiceSetRequest::Run() {
...
-  msg_params[strings::app_id] = app->app_id();
+void DeleteInteractionChoiceSetRequest::on_event(
+    const event_engine::Event& event) {
+  using namespace helpers;
+  SDL_LOG_AUTO_TRACE();
 
-  app->RemoveChoiceSet(choice_set_id);
+  if (event.id() == hmi_apis::FunctionID::VR_DeleteCommand) {
+    const smart_objects::SmartObject& message = event.smart_object();
+    const auto result_code = static_cast<hmi_apis::Common_Result::eType>(
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc:107]: there is currently no way for result_code to be set to success

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc (hunk 22 above)
Comment (AKalinich-Luxoft) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @iCollin I replaced this logic with having a vector of result codes. Final result code will be SUCCESS by default, but in case of any error it will contain the first error from this vector

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc (hunk 23 above)
Comment (AKalinich-Luxoft) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @iCollin fixed in https://github.com/smartdevicelink/sdl_core/pull/2601/commits/59029ef38e9f4161255d6a6f929ff3bdf7870d68

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc (hunk 25 above)
Comment (AKalinich-Luxoft) [reply src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc]: @iCollin fixed in PrepareResultForMobileResponse

File: src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc [hunk 27]
```diff
@@ -89,23 +90,49 @@ void DeleteInteractionChoiceSetRequest::Run() {
...
+    response_result_codes_.push_back(result_code);
+    const std::uint32_t correlation_id = static_cast<uint32_t>(
+        message[strings::params][strings::correlation_id].asUInt());
+
+    bool should_send_response = false;
+    {
+      sync_primitives::AutoLock auto_lock(requests_lock_);
+      auto found_request = sent_requests_.find(correlation_id);
+      if (sent_requests_.end() == found_request) {
+        SDL_LOG_WARN("Request with " << *found_request
```
Comment (iCollin) [inline src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc:118]:
```suggestion
        SDL_LOG_WARN("Request with " << correlation_id
```

**Review by iCollin — APPROVED** [review]
