### PR TITLE
Fix SDL app stream processing with non-streamable state.

### LINKED ISSUE #3139: SDL does not stops streaming from mobile app with NOT_STREAMABLE state
### Bug Report
SDL keeps processing video streaming data from an application with **NOT_STREAMABLE** streaming state.

##### Reproduction Steps
1. Register Navigation and Projection applications
2. Activate Navigation app and start streaming
3. Activate Projection app: Navigation app should receive **LIMITED** HMI level and **NOT_STREAMABLE** state. 
**!NOTE**: Navigation app keeps streaming

##### Expected Behavior
After timeout expires, SDL unregisters Navigation application with **PROTOCOL_VIOLATION** reason

##### Observed Behavior
SDL keeps processing stream from Navigation application

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: develop (891497bc9fb23434242dbe92e1f13dd1273fcb21)
* Testing Against: WebHMI [91d5940](https://github.com/smartdevicelink/sdl_hmi/tree/91d59402b8e0967f9a3532b2cf3f2537ee068b95)

### PR DESCRIPTION
**Pull request by mkorniichuk**
Fixes #3139

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
For determining whether an application is allowed to stream,
SDL considered only HMI_Level.
Now streaming state is also taken into account.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/include/application_manager/application_manager_impl.h [hunk 1]
```diff
@@ -1278,8 +1278,14 @@ class ApplicationManagerImpl
...
-                  const mobile_apis::HMILevel::eType from,
-                  const mobile_apis::HMILevel::eType to);
+                  const HmiStatePtr from,
+                  const HmiStatePtr to);
+
+  /**
+   * @brief Starts EndStream timer for a specified application
+   * @param app_id Application to process
+   */
+  void StartEndStreamTimer(uint32_t app_id);
```
Comment (mked-luxoft) [inline src/components/application_manager/include/application_manager/application_manager_impl.h]: const?

File: src/components/application_manager/src/application_manager_impl.cc [hunk 2]
```diff
@@ -3478,50 +3483,91 @@ void ApplicationManagerImpl::ProcessPostponedMessages(const uint32_t app_id) {
...
 }
 
+void ApplicationManagerImpl::StartEndStreamTimer(uint32_t app_id) {
+  LOG4CXX_DEBUG(logger_, "Start end stream timer for app " << app_id);
+  navi_app_to_end_stream_.push_back(app_id);
+  TimerSPtr end_stream_timer(std::make_shared<timer::Timer>(
+      "AppShouldFinishStreaming",
+      new TimerTaskImpl<ApplicationManagerImpl>(
+          this, &ApplicationManagerImpl::EndNaviStreaming)));
+  end_stream_timer->Start(navi_end_stream_timeout_, timer::kPeriodic);
```
Comment (mked-luxoft) [inline src/components/application_manager/src/application_manager_impl.cc]: does this timer need to be periodic?

File: src/components/application_manager/src/application_manager_impl.cc [hunk 3]
```diff
@@ -3283,17 +3283,23 @@ bool ApplicationManagerImpl::HMILevelAllowsStreaming(
...
     LOG4CXX_WARN(logger_, "An application is not registered.");
     return false;
   }
-  return Compare<eType, EQ, ONE>(
-      app->hmi_level(mobile_api::PredefinedWindows::DEFAULT_WINDOW),
-      HMI_FULL,
-      HMI_LIMITED);
+
+  const auto hmi_state = app->CurrentHmiState(DEFAULT_WINDOW);
+  const bool allow_streaming =
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_manager_impl.cc]: @mkorniichuk I would recommend to split it to 2 separate bool variables

File: src/components/application_manager/src/application_manager_impl.cc [hunk 4]
```diff
@@ -3478,50 +3483,91 @@ void ApplicationManagerImpl::ProcessPostponedMessages(const uint32_t app_id) {
...
-      timer_pool_.push_back(end_stream_timer);
-    }
-  } else if (to == HMI_NONE) {
-    LOG4CXX_TRACE(logger_, "HMILevel to NONE");
-    if (from == HMI_FULL || from == HMI_LIMITED || from == HMI_BACKGROUND) {
-      EndNaviServices(app_id);
-    }
+  if (hmi_level_from == hmi_level_to &&
+      streaming_state_from == streaming_state_to) {
+    LOG4CXX_TRACE(logger_, "HMILevel && streaming state was not changed");
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_manager_impl.cc]: @mkorniichuk was -> were

File: src/components/application_manager/src/application_manager_impl.cc [hunk 5]
```diff
@@ -3478,50 +3483,91 @@ void ApplicationManagerImpl::ProcessPostponedMessages(const uint32_t app_id) {
...
+                      << std::boolalpha << end_streaming_by_hmi_level);
+    EndNaviServices(app_id);
   }
 }
 
+void ApplicationManagerImpl::StartEndStreamTimer(uint32_t app_id) {
+  LOG4CXX_DEBUG(logger_, "Start end stream timer for app " << app_id);
+  navi_app_to_end_stream_.push_back(app_id);
+  TimerSPtr end_stream_timer(std::make_shared<timer::Timer>(
+      "AppShouldFinishStreaming",
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_manager_impl.cc]: @mkorniichuk Unclear name for the timer. MAy be `AppStreamingEndTimer` ?

File: src/components/application_manager/src/application_manager_impl.cc [hunk 6]
```diff
@@ -3478,50 +3483,91 @@ void ApplicationManagerImpl::ProcessPostponedMessages(const uint32_t app_id) {
...
+    return;
+  }
+
+  const bool end_streaming_by_hmi_level =
+      full_or_limited_hmi_level(hmi_level_from) && HMI_NONE == hmi_level_to;
+  if (end_streaming_by_hmi_level) {
+    LOG4CXX_TRACE(logger_,
+                  "End streaming services by hmi level: "
+                      << std::boolalpha << end_streaming_by_hmi_level);
+    EndNaviServices(app_id);
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/src/application_manager_impl.cc]: @mkorniichuk you may add one more trace log with message "No actions required for app " << app_id
in the end of this function for case when all `if` statements were false

File: src/components/application_manager/test/state_controller/state_controller_test.cc [hunk 7]
```diff
@@ -1454,9 +1451,7 @@ TEST_F(StateControllerImplTest, MoveSimpleAppToValidStates) {
     EXPECT_CALL(message_helper_mock_,
                 SendHMIStatusNotification(simple_app_, kDefaultWindowId, _));
     EXPECT_CALL(app_manager_mock_,
-                OnHMILevelChanged(simple_app_id_,
-                                  initial_state->hmi_level(),
-                                  state_to_setup->hmi_level()));
+                OnHMIStateChanged(simple_app_id_, _, state_to_setup));
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/test/state_controller/state_controller_test.cc]: @mkorniichuk why did you removed `initial_state` check? I think its necessary to verify as well

File: src/components/application_manager/include/application_manager/application_manager_impl.h (hunk 1 above)
Comment (mkorniichuk) [reply src/components/application_manager/include/application_manager/application_manager_impl.h]: @mked-luxoft fixed in 4f71e8ac39d897fdc5afcaef8e44c504fbda9ef3

File: src/components/application_manager/src/application_manager_impl.cc (hunk 2 above)
Comment (mkorniichuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @mked-luxoft fixed in 4f71e8ac39d897fdc5afcaef8e44c504fbda9ef3

File: src/components/application_manager/src/application_manager_impl.cc (hunk 3 above)
Comment (mkorniichuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @AByzhynar fixed in 4f71e8ac39d897fdc5afcaef8e44c504fbda9ef3

File: src/components/application_manager/src/application_manager_impl.cc (hunk 4 above)
Comment (mkorniichuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @AByzhynar fixed in 4f71e8ac39d897fdc5afcaef8e44c504fbda9ef3

File: src/components/application_manager/src/application_manager_impl.cc (hunk 5 above)
Comment (mkorniichuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @AByzhynar fixed in 4f71e8ac39d897fdc5afcaef8e44c504fbda9ef3

File: src/components/application_manager/src/application_manager_impl.cc (hunk 6 above)
Comment (mkorniichuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @AKalinich-Luxoft fixed in 4f71e8ac39d897fdc5afcaef8e44c504fbda9ef3

File: src/components/application_manager/test/state_controller/state_controller_test.cc (hunk 7 above)
Comment (mkorniichuk) [reply src/components/application_manager/test/state_controller/state_controller_test.cc]: @AKalinich-Luxoft fixed in 4f71e8ac39d897fdc5afcaef8e44c504fbda9ef3

File: src/components/application_manager/src/application_manager_impl.cc [hunk 8]
```diff
@@ -3553,16 +3554,17 @@ void ApplicationManagerImpl::ProcessApp(const uint32_t app_id,
                       << std::boolalpha << end_streaming_by_hmi_level);
     EndNaviServices(app_id);
   }
+  LOG4CXX_TRACE(logger_, "No actions required for app " << app_id);
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/src/application_manager_impl.cc]: @mkorniichuk you should also add `return` for the last if statement to avoid  double logging

Comment (mkorniichuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @AKalinich-Luxoft fixed in 9a3bfe0aef2ba3121af594707ec1728d5480f057

**Comment by dboltovskyi** [comment]
@theresalech Please notice this PR is ready for PM review

File: src/components/application_manager/src/policies/policy_handler.cc [hunk 9]
```diff
@@ -2411,13 +2411,13 @@ void PolicyHandler::UpdateHMILevel(ApplicationSharedPtr app,
...
                    "Changing hmi level of application "
                        << app->app_id() << " to default hmi level " << level);
-      // Set application hmi level
-      application_manager_.ChangeAppsHMILevel(app->app_id(), level);
       // If hmi Level is full, it will be seted after ActivateApp response
       MessageHelper::SendHMIStatusNotification(
           app,
           mobile_apis::PredefinedWindows::DEFAULT_WINDOW,
           application_manager_);
+      // Set application hmi level
```
Comment (ShobhitAd) [inline src/components/application_manager/src/policies/policy_handler.cc]: Could you please explain why this change(moving the HMILevelChange to happen after sending the notification rather than before) was necessary?

File: src/components/application_manager/src/application_manager_impl.cc [hunk 10]
```diff
@@ -3283,17 +3283,24 @@ bool ApplicationManagerImpl::HMILevelAllowsStreaming(
     uint32_t app_id, protocol_handler::ServiceType service_type) const {
```
Comment (ShobhitAd) [inline src/components/application_manager/src/application_manager_impl.cc]: This function should probably be renamed since it now checks both the hmi level and the streaming state. Maybe `HMIStateAllowsStreaming` would work better

Comment (mkorniichuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @ShobhitAd fixed in db2d1c86722705169c2633a18b01c6f072059952

File: src/components/application_manager/src/policies/policy_handler.cc (hunk 9 above)
Comment (mkorniichuk) [reply src/components/application_manager/src/policies/policy_handler.cc]: @ShobhitAd good point! These changes indeed seem to be unnecessary.
Reverted in a fixup commit 83c595c25a549134fb01b376313eb03dfaf185d0

**Comment by mkorniichuk** [comment]
@ShobhitAd There are conflicts appeared after the latest commits. I'll rebase after review for not to mess up comments.

**Comment by ShobhitAd** [comment]
@mkorniichuk Changes approved. Rather than rebasing and force-pushing could you please merge in develop.

**Comment by mkorniichuk** [comment]
@ShobhitAd here you go. Please, take a look. Thanks!
