### PR TITLE
Stop app unregister timer after streaming session restarted

### LINKED ISSUE #3140: SDL unregister streaming app if it's deactivated/activated during `StopStreamingTimeout`
### Bug Report
SDL unregister streaming app if it's deactivated/activated during `StopStreamingTimeout`

##### Reproduction Steps
1. Set StopStreamingTimeout = 3000 in SDL .INI file
2. Start SDL, HMI, connect Mobile device
3. Register 2 NAVIGATION applications: App_1 and App_2 
4. Activate App_1 and start Video streaming
=> SDL starts streaming successfully
5. Deactivate App_1 and activate App_2
=> SDL stops streaming successfully
6. Deactivate App_2, activate App_1 and start Video streaming (within `StopStreamingTimeout`)
-- 

##### Expected Behavior
SDL does not send `OnAppInterfaceUnregistered` notification to App_1 and `BC.OnAppUnregistered` notification to HMI

##### Observed Behavior
SDL unregisters App_1 with `PROTOCOL_VIOLATION` reason once `StopStreamingTimeout` expires

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: develop (891497bc9fb23434242dbe92e1f13dd1273fcb21)
* Testing Against: ATF

### PR DESCRIPTION
**Pull request by mkorniichuk**
Fixes #3140

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
SDL starts a timer for an app to be unregistered if it continues streaming. And when timeout expired and Application already stopped service - nothing would happen. But if the application restarts streaming service, SDL would not know that it is a new session. And so, in this case, after timer expiration, SDL will unregister an application, despite the fact it is a brand new streaming session. Current PR implements the cleaning up of timers on service start.

**UPD:** 11.01.2020

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/application_manager/src/application_manager_impl.cc [hunk 1]
```diff
@@ -3525,19 +3542,25 @@ void ApplicationManagerImpl::ProcessApp(const uint32_t app_id,
...
-
-  sync_primitives::AutoLock lock(timer_pool_lock_);
-  new_timer_pool.push_back(timer_pool_[0]);
-
-  for (size_t i = 1; i < timer_pool_.size(); ++i) {
-    if (timer_pool_[i]->is_running()) {
-      new_timer_pool.push_back(timer_pool_[i]);
+  auto clear_timer_pool = [](std::vector<TimerSPtr> vector_to_clear) {
+    std::vector<TimerSPtr> new_timer_pool;
+    for (size_t i = 0; i < vector_to_clear.size(); ++i) {
```
Comment (mked-luxoft) [inline src/components/application_manager/src/application_manager_impl.cc]: i think this can be range based

File: src/components/application_manager/src/application_manager_impl.cc [hunk 2]
```diff
@@ -3525,19 +3542,25 @@ void ApplicationManagerImpl::ProcessApp(const uint32_t app_id,
...
 
-  std::vector<TimerSPtr> new_timer_pool;
-
-  sync_primitives::AutoLock lock(timer_pool_lock_);
-  new_timer_pool.push_back(timer_pool_[0]);
-
-  for (size_t i = 1; i < timer_pool_.size(); ++i) {
-    if (timer_pool_[i]->is_running()) {
-      new_timer_pool.push_back(timer_pool_[i]);
+  auto clear_timer_pool = [](std::vector<TimerSPtr> vector_to_clear) {
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/src/application_manager_impl.cc]: @mkorniichuk whole function can be replaced with `copy_if` + `clear`

File: src/components/application_manager/include/application_manager/application_manager_impl.h [hunk 3]
```diff
@@ -1554,8 +1554,11 @@ class ApplicationManagerImpl
   uint32_t navi_close_app_timeout_;
   uint32_t navi_end_stream_timeout_;
 
-  std::vector<TimerSPtr> timer_pool_;
-  sync_primitives::Lock timer_pool_lock_;
+  std::vector<TimerSPtr> close_app_timer_pool_;
+  std::vector<TimerSPtr> end_stream_timer_pool_;
```
Comment (AKalinich-Luxoft) [inline src/components/application_manager/include/application_manager/application_manager_impl.h]: @mkorniichuk why did you divided the timers pool?

**Comment by AByzhynar** [comment]
@mkorniichuk I would recommend to be more specific in PR description. 
- Add details please to the summary.
- PR name does not explicitly match PR description.

File: src/components/application_manager/src/application_manager_impl.cc (hunk 1 above)
Comment (mkorniichuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @mked-luxoft fixed in 3d068569c1b872894e5596413a51bddc49747ab0

File: src/components/application_manager/src/application_manager_impl.cc [hunk 4]
```diff
@@ -1893,6 +1898,18 @@ void ApplicationManagerImpl::OnStreamingConfigured(
...
                                               : it->second.second = true;
+
+      for (size_t i = 0; i < navi_app_to_stop_.size(); ++i) {
+        if (app_id == navi_app_to_stop_[i]) {
+          {
+            sync_primitives::AutoLock lock(close_app_timer_pool_lock_);
+            close_app_timer_pool_[i]->Stop();
+            close_app_timer_pool_.erase(close_app_timer_pool_.begin() + i);
+            navi_app_to_stop_.erase(navi_app_to_stop_.begin() + i);
+          }
```
[the remark this answers is not in the document]
Comment (mkorniichuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @AKalinich-Luxoft fixed in 3d068569c1b872894e5596413a51bddc49747ab0

File: src/components/application_manager/src/application_manager_impl.cc (hunk 2 above)
Comment (mkorniichuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @AKalinich-Luxoft fixed in 3d068569c1b872894e5596413a51bddc49747ab0

File: src/components/application_manager/src/application_manager_impl.cc [hunk 5]
```diff
@@ -1893,6 +1898,18 @@ void ApplicationManagerImpl::OnStreamingConfigured(
       // started audio service
       service_type == ServiceType::kMobileNav ? it->second.first = true
                                               : it->second.second = true;
+
+      for (size_t i = 0; i < navi_app_to_stop_.size(); ++i) {
+        if (app_id == navi_app_to_stop_[i]) {
+          {
+            sync_primitives::AutoLock lock(close_app_timer_pool_lock_);
+            close_app_timer_pool_[i]->Stop();
```
[the remark this answers is not in the document]
Comment (mkorniichuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @AKalinich-Luxoft that is exactly the point! I haven't found any condition for `find_if` to stop the timer. There is some kind of synchronization. Handler for `close_app_timer` takes the first item from `navi_app_to_stop_`. As well as `end_stream_timer` handler. So if you place timer to pool you have to place `app_id` to a specific queue. And after a timer expires - it'll take the first from the app_id list. But when it's time to stop or remove a certain timer - it becomes a problem. And that is the reason, why I decided to divide the timer pool.

File: src/components/application_manager/include/application_manager/application_manager_impl.h (hunk 3 above)
Comment (mkorniichuk) [reply src/components/application_manager/include/application_manager/application_manager_impl.h]: @AKalinich-Luxoft please, take a look at https://github.com/smartdevicelink/sdl_core/pull/3202#discussion_r365530445

**Comment by mkorniichuk** [comment]
@AByzhynar fixed PR description

File: src/components/application_manager/src/application_manager_impl.cc (hunk 5 above)
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply src/components/application_manager/src/application_manager_impl.cc]: @mkorniichuk actually, you have a container of shared pointers of timers. When you are erasing the element, timer is destroyed, and it is stopped by dtor so there is no need to call a separate `Stop()` before destruction

[the remark this answers is not in the document]
Comment (mkorniichuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @AKalinich-Luxoft fixed in 5d0c68a895dc9219a612f6bac584f18ce349d269

**Comment by dboltovskyi** [comment]
@theresalech Please notice this PR is ready for PM review

File: src/components/application_manager/src/application_manager_impl.cc [hunk 6]
```diff
@@ -1893,6 +1898,15 @@ void ApplicationManagerImpl::OnStreamingConfigured(
       // started audio service
       service_type == ServiceType::kMobileNav ? it->second.first = true
                                               : it->second.second = true;
+
+      for (size_t i = 0; i < navi_app_to_stop_.size(); ++i) {
+        if (app_id == navi_app_to_stop_[i]) {
```
Comment (AByzhynar) [inline src/components/application_manager/src/application_manager_impl.cc]: @mkorniichuk error prone comparison as `app_id` is non-const variable

File: src/components/application_manager/src/application_manager_impl.cc [hunk 7]
```diff
@@ -201,14 +204,9 @@ ApplicationManagerImpl::ApplicationManagerImpl(
...
 
-  sync_primitives::AutoLock lock(timer_pool_lock_);
-  TimerSPtr clearing_timer(std::make_shared<timer::Timer>(
-      "ClearTimerPoolTimer",
-      new TimerTaskImpl<ApplicationManagerImpl>(
-          this, &ApplicationManagerImpl::ClearTimerPool)));
   const uint32_t timeout_ms = 10000u;
-  clearing_timer->Start(timeout_ms, timer::kSingleShot);
-  timer_pool_.push_back(clearing_timer);
+  clear_pool_timer_.Start(timeout_ms, timer::kSingleShot);
```
Comment (iCollin) [inline src/components/application_manager/src/application_manager_impl.cc]: It seems that `ApplicationManagerImpl::ClearTimerPool` will only ever be called one time, 10 seconds after the Application Manager is constructed.

Do you agree that `ApplicationManagerImpl::ClearTimerPool` should be called more often? I propose increasing the timeout and using `timer::kPeriodic`.

Comment (mkorniichuk) [reply src/components/application_manager/src/application_manager_impl.cc]: @iCollin good point. Please take look. https://github.com/smartdevicelink/sdl_core/pull/3202/commits/4b7b3eae15682db636f68ef82e8afc2d1ffbbbc1
`kSingleShot` was introduced in https://github.com/smartdevicelink/sdl_core/commit/f6ebfe592402a87fe7118f0dbe65f8c46102e4e8
And this looks like a defect. We will run a regression testing with new changes.
How do you think, is this PR is a good place for this fix? Or it's better to create a new separate issue?

Comment (iCollin) [reply src/components/application_manager/src/application_manager_impl.cc]: I think this PR is a fine place for the fix, especially since we are moving one timer to a member variable.

**Comment by iCollin** [comment]
@mkorniichuk I found a few failing tests with the timer changes.

These were likely written after the regression occurred and just need to be updated. Let me know what you find, if it is not that simple perhaps we can open another PR for the timer changes and discuss there. 

```
./test_scripts/SDL5_0/Handling_VR_help_requests/005_SetGlobalProp_apply_limitation_only_for_addcommand.lua
./test_scripts/SDL5_0/Handling_VR_help_requests/018_SetGlobalProp_processing_30_commands_by_resumption.lua
./test_scripts/SDL5_0/Handling_VR_help_requests/033_SetGlobalProp_delete_last_command.lua
```

**Comment by mkorniichuk** [comment]
@iCollin I've reverted part of the last commit regarding `tts_global_properties_timer_`. As for me, this doesn't look like relative to this issue. And it requires more detailed investigation. We'll take a closer look and create a new issue if defect is actual.
