### PR TITLE
Fix certificate saving after policy table update

### LINKED ISSUE #2191: Cert processing invalid, module certificate should be updated when a policy table update occurs
### Bug Report
With the implementation of the EXTERNAL_PROPRIETARY policy mode in release 4.3.0, SDL Core should update the module certificate in the local file system when a policy table update occurs.  Currently SDL core is retrieving its certificate directly out of the policy table.  This issue is closely related to #2190 

##### Reproduction Steps
Clone any branch of sdl core with a release version of 4.3.0 or above. Take note of the certificate processing flow, core will directly processes its certificates from its policy table database.  

##### Expected Behavior
SDL Core will update the local file system when a policy table update occurs with the certificate provided via the updated policy table exchange.

##### Observed Behavior
Invalid certificate processing flow, data is not sourced properly as it should be.

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: Release 4.5.1
* Testing Against: Tested with WebHMI and app built with 4.5.0 Android Proxy release

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #2191 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Will be tested on the integration branch
Unit tests

### Summary
SDL Core should update the module certificate in the local file system when a policy table update occurs. Currently SDL core is retrieving its certificate directly out of the policy table. This fix provides functionality for saving module certificate to the file system. 

**NOTE**
This fix is closely related to #2217 and should be merged **after** it.
This fix should be merged **after** #2105 and #2068. 

### Changelog
Following changes were done:
- Added getters for `CertificatePath` and `KeyPath` parameters in `SecurityManagerSettings` class to provide another components an access to these properties
- Added methods for saving certificate and private key data to the files specified by `CertificatePath` and `KeyPath` keywords
- `CryptoManager` component implementation was updated. Now this component also saves certificate data to files (if write permission allowed) after PTU

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/security_manager/src/crypto_manager_impl.cc [hunk 1]
```diff
@@ -331,6 +336,8 @@ bool CryptoManagerImpl::set_certificate(const std::string& cert_data) {
     return false;
   }
 
+  // TODO(AKalinich): remove all lines below till the end of function when
```
Comment (mrapitis) [inline src/components/security_manager/src/crypto_manager_impl.cc]: Can we please remove the todo, as we can't merge these comments into develop?

File: src/components/security_manager/src/crypto_manager_impl.cc [hunk 2]
```diff
@@ -300,7 +305,7 @@ const CryptoManagerSettings& CryptoManagerImpl::get_settings() const {
   return *settings_;
 }
 
-bool CryptoManagerImpl::set_certificate(const std::string& cert_data) {
+bool CryptoManagerImpl::SaveCertificateData(const std::string& cert_data) {
   LOG4CXX_AUTO_TRACE(logger_);
```
Comment (KVGrygoriev) [inline src/components/security_manager/src/crypto_manager_impl.cc]: Function doesn't change internal state, it should be const
It would be better function will be called with prefix "Is", IsSaveCertificateData

File: src/components/security_manager/src/crypto_manager_impl.cc [hunk 3]
```diff
@@ -411,4 +407,59 @@ void CryptoManagerImpl::InitCertExpTime() {
   strptime("1 Jan 1970 00:00:00", "%d %b %Y %H:%M:%S", &expiration_time_);
 }
 
+bool CryptoManagerImpl::SaveModuleCertificateToFile(X509* certificate) const {
```
Comment (olohvinenko) [inline src/components/security_manager/src/crypto_manager_impl.cc]: Same as for PR #2217 - I suppose we should free allocated resources...

File: src/components/security_manager/src/crypto_manager_impl.cc (hunk 2 above)
Comment (AByzhynar) [reply src/components/security_manager/src/crypto_manager_impl.cc]: @AKalinich-Luxoft Agree with `const` , disagree with prefix `Is`.

File: src/components/security_manager/src/crypto_manager_impl.cc [hunk 4]
```diff
@@ -411,4 +407,59 @@ void CryptoManagerImpl::InitCertExpTime() {
...
+  LOG4CXX_AUTO_TRACE(logger_);
+
+  if (NULL == key) {
+    LOG4CXX_WARN(logger_, "Empty private key. Saving will be skipped");
+    return false;
+  }
+
+  const std::string key_path = get_settings().module_key_path();
+  BIO* bio_key = BIO_new_file(key_path.c_str(), "w");
+  if (NULL == bio_key) {
```
Comment (AByzhynar) [inline src/components/security_manager/src/crypto_manager_impl.cc]: @AKalinich-Luxoft Use please `if (!bio_key)`

File: src/components/security_manager/src/crypto_manager_impl.cc [hunk 5]
```diff
@@ -411,4 +407,59 @@ void CryptoManagerImpl::InitCertExpTime() {
...
+    LOG4CXX_ERROR(logger_,
+                  "Failed to open " << key_path << " file: " << LastError());
+    return false;
+  }
+
+  utils::ScopeGuard bio_guard = utils::MakeGuard(BIO_free, bio_key);
+  UNUSED(bio_guard);
+
+  if (0 == PEM_write_bio_PrivateKey(bio_key, key, NULL, NULL, 0, NULL, NULL)) {
```
Comment (AByzhynar) [inline src/components/security_manager/src/crypto_manager_impl.cc]: @AKalinich-Luxoft Use please `(!PEM_write_bio_PrivateKey...)`
Like described here: [PEM_write_bio_PrivateKey](https://www.openssl.org/docs/man1.1.0/crypto/PEM_write_bio_PrivateKey.html)

File: src/components/security_manager/src/crypto_manager_impl.cc [hunk 6]
```diff
@@ -411,4 +407,59 @@ void CryptoManagerImpl::InitCertExpTime() {
...
+    return false;
+  }
+
+  return true;
+}
+
+bool CryptoManagerImpl::SaveModuleKeyToFile(EVP_PKEY* key) const {
+  LOG4CXX_AUTO_TRACE(logger_);
+
+  if (NULL == key) {
```
Comment (AByzhynar) [inline src/components/security_manager/src/crypto_manager_impl.cc]: @AKalinich-Luxoft Same as above  - `if(!key)`...

File: src/components/security_manager/src/crypto_manager_impl.cc (hunk 1 above)
Comment (AKalinich-Luxoft) [reply src/components/security_manager/src/crypto_manager_impl.cc]: @mrapitis sure, but we should not forget to remove redundant lines of code after these two pull requests merge
Fixed in https://github.com/smartdevicelink/sdl_core/pull/2218/commits/389a64f182249a4154554788f320575a697e2092

File: src/components/security_manager/src/crypto_manager_impl.cc (hunk 2 above)
Comment (AKalinich-Luxoft) [reply src/components/security_manager/src/crypto_manager_impl.cc]: @KVGrygoriev also disagree with prefix `Is`
Const added in https://github.com/smartdevicelink/sdl_core/pull/2218/commits/389a64f182249a4154554788f320575a697e2092

File: src/components/security_manager/src/crypto_manager_impl.cc (hunk 3 above)
Comment (AKalinich-Luxoft) [reply src/components/security_manager/src/crypto_manager_impl.cc]: @olohvinenko thanks, fixed in https://github.com/smartdevicelink/sdl_core/pull/2218/commits/389a64f182249a4154554788f320575a697e2092

File: src/components/security_manager/src/crypto_manager_impl.cc (hunk 4 above)
Comment (AKalinich-Luxoft) [reply src/components/security_manager/src/crypto_manager_impl.cc]: @AByzhynar fixed in https://github.com/smartdevicelink/sdl_core/pull/2218/commits/389a64f182249a4154554788f320575a697e2092

File: src/components/security_manager/src/crypto_manager_impl.cc (hunk 5 above)
Comment (AKalinich-Luxoft) [reply src/components/security_manager/src/crypto_manager_impl.cc]: @AByzhynar fixed in https://github.com/smartdevicelink/sdl_core/pull/2218/commits/389a64f182249a4154554788f320575a697e2092

File: src/components/security_manager/src/crypto_manager_impl.cc (hunk 6 above)
Comment (AKalinich-Luxoft) [reply src/components/security_manager/src/crypto_manager_impl.cc]: @AByzhynar fixed in https://github.com/smartdevicelink/sdl_core/pull/2218/commits/389a64f182249a4154554788f320575a697e2092

**Comment by AKalinich-Luxoft** [comment]
Rebuild required

**Comment by mrapitis** [comment]
@theresalech this PR is ready for review.

**Comment by JackLivio** [comment]
@AKalinich-Luxoft  Please resolve merge conflicts.

File: src/components/protocol_handler/src/protocol_handler_impl.cc [hunk 7]
```diff
@@ -839,58 +838,7 @@ void ProtocolHandlerImpl::OnConnectionClosed(
...
-      }
-    }
-  }
-
-  LOG4CXX_DEBUG(logger_, "Handshake handlers were notified");
-  ptu_pending_handlers_.clear();
-  is_ptu_triggered_ = false;
-#endif  // ENABLE_SECURITY
-}
+void ProtocolHandlerImpl::OnPTUFinished(const bool ptu_result) {}
```
Comment (JackLivio) [inline src/components/protocol_handler/src/protocol_handler_impl.cc]: Can we just remove this function if it doesn't do anything?

Comment (AKalinich-Luxoft) [reply src/components/protocol_handler/src/protocol_handler_impl.cc]: @JackLivio yes, it has default empty implementation in base class.
Fixed in https://github.com/smartdevicelink/sdl_core/pull/2218/commits/0a7317dda7adb28fc5a15234ab2bc09428153015

**Comment by AKalinich-Luxoft** [comment]
@JackLivio all conflicts was resolved
