### PR TITLE
Check for conflicting app resumption level

### LINKED ISSUE #3111: SDL switches applications into incorrect HMILevel after IGNITION_OFF/IGNITION_ON cycle
### Bug Report
There is an issue when SDL switches applications into incorrect HMILevel after IGNITION_OF/IGNITION_ON cycle.

##### Reproduction Steps
1. SDL and WebHMI are successfully started.
2. Register and activate App1 (SDL switches App1 into HMILevel::FULL).
3. Register and activate App2 (SDL switches App2 into HMILevel::FULL and switches App1 into HMILevel::BACKGROUND).
4. Send "BasicCommunication.OnExitAllApplications","params":{"reason":"IGNITION_OFF"} from WebHMI.
5. SDL is stopped successfully.
6. Start SDL (the new ignition cycle).
7. SDL and WebHMI are successfully started.
8. Register App1
9. Wait some time ~1sec
10. Register App2 
11. SDL starts resumption.
12. App1 is registered and does not resume the level because the  `BACKGROUND` level should not be resumed, so app is set to default HMI level (NONE)
13. App2 is registered and resumes HMI level FULL
14. Activate App1 manually from HMI after resumption is finished.

##### Expected Behavior
App1 is set to FULL HMI level and App2 is switched to BACKGROUND HMI level

##### Observed Behavior
1. HMI sends SDL.ActivateApp(appIs of App1)
2. SDL responds with success result code, but does not set app to FULL HMI level
3. There is no ability to change HMI level of App1 from NONE to something else.
Note: HMI level can be changes only after reregistration of App1

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: release/6.0.0 (4d283e625dfa09d166d572fa7bf6e98e91f05050)
* WebHMI: develop (https://github.com/smartdevicelink/sdl_hmi/commit/bd53f11339ee4d95a41caf5e5edf4ae0839d5957)

SDL log: 
  - [SmartDeviceLinkCore.log.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3797531/SmartDeviceLinkCore.log.tar.gz)
  - WebHMI log: [HMI_log.log.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3797533/HMI_log.log.tar.gz)
  - Script: [GH-3111.lua.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3801273/GH-3111.lua.tar.gz)

### PR DESCRIPTION
**Pull request by JackLivio**
Fixes #3111 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Use ATF script GH-3111.lua supplied in issue.

### Summary
When the resume controllers timer fires to resume an app, there is no check to see if the saved hmi level conflicts with an app that is already in a limited or full state. This fix looks for that case and returns false for RestoreAppHMIState. This will mark the resumption as failed and set the app is_resuming state to false. This allows an app to later be activated via SDL.ActivateApp.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by YarikMamykin** [comment]
@JackLivio changes on commit c872d7a5a128b3b8fc70ef6e4d6e179ef0d3f92f manually tested. 
Manual testing passed.

File: src/components/application_manager/include/application_manager/resumption/resume_ctrl.h [hunk 1]
```diff
@@ -115,7 +115,7 @@ class ResumeCtrl {
    * @param saved_app application specific section from backup file
    * @return true if widgets resumed successfully otherwise - false
    */
-  virtual void RestoreAppWidgets(
+  virtual size_t RestoreAppWidgets(
```
Comment (AByzhynar) [inline src/components/application_manager/include/application_manager/resumption/resume_ctrl.h]: @JackLivio Could you be so kind and update `return value` in description?

File: src/components/application_manager/src/resumption/resume_ctrl_impl.cc [hunk 2]
```diff
@@ -214,12 +214,20 @@ bool ResumeCtrlImpl::RestoreAppHMIState(ApplicationSharedPtr application) {
...
           SetAppHMIState(application, saved_hmi_level, true);
+      size_t restored_widgets = 0;
       if (app_hmi_state_is_set &&
           application->is_app_data_resumption_allowed()) {
-        RestoreAppWidgets(application, saved_app);
+        restored_widgets = RestoreAppWidgets(application, saved_app);
+      }
+      const bool does_app_with_same_level_exist =
+          application_manager_.IsAppTypeExistsInFullOrLimited(application);
+      if (does_app_with_same_level_exist && restored_widgets == 0) {
```
Comment (AByzhynar) [inline src/components/application_manager/src/resumption/resume_ctrl_impl.cc]: @JackLivio I would recommend to swap comparables : `restored_widgets == 0` to `0 == restored_widgets`
